---
title: "the alpha diversity"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(janitor)
```

```{r}
# the most updated ptb
ptb <- readxl::read_excel('../data/OPBG_clinicaldata_v2.xlsx') %>% 
  clean_names() %>% 
  mutate(pid = str_replace(pt_id_de_identified, 'N$',''),
         pid = str_replace(pid, '4-B','4B'),
         pid = str_replace(pid, '13-B','13')) %>% 
  select(pid, age_at_infusion, gender, disease, disease_class, car_construct, cr_y_n, orr_y_n, toxicity_y_n, cytokine_release_syndrome_y_n,crs_grade) %>% 
  rename(crs = cytokine_release_syndrome_y_n,
         cr = cr_y_n, 
         orr = orr_y_n,
         toxicity = toxicity_y_n) %>% 
  # remove three patients cuz they are on sponsored trial
  filter(!is.na(gender)) %>% 
  mutate(cr = if_else(cr == 'y', 'Y', cr)) %>% 
  mutate(disease = if_else(disease %in% c('LMC BCR/ABL+','BCP-ALL'), 'B-ALL', disease))

colnames(ptb)
ptb %>% mutate_if(is.character, as.factor) %>% 
  summary
```

```{r}
# a table 1 of the above things
library(gtsummary)
ptb_clean <- ptb %>% 
  select(-pid, -disease_class, -orr, -crs_grade) %>% 
  rename(age = age_at_infusion) %>% 
  rename_all(str_to_title) %>% 
  rename(CR = Cr, CRS = Crs)



ptb_clean %>% 
  tbl_summary(
    #type = list(all_double() ~ "continuous"), 
    statistic = list(all_continuous() ~ "{mean} ({sd})")
  ) %>%
  bold_labels() %>% 
  as_gt() %>%
  #gt::tab_footnote(footnote = "MDS/MPN = Myelodysplastic/myeloproliferative neoplasms") %>% 
  gt::gtsave(filename = "../data/002_pt_all.pdf")
```



```{r}
# eligible baseline stool sample before day 0 or close to day 0 
stools <- stb_new %>% 
  filter(pid %in% ptb$pid)

stools %>% write_csv('../data/002_STB.csv')
```

```{r}
stools <- read_csv('../data/002_STB.csv')
removedisease <- ptb %>% 
  count(disease, sort = T) %>% 
  filter(n == 1) %>% 
  pull(disease)

alpha <- read_csv('../data/001_alpha_div.csv')

# find the baseline samples that I'm gonna use 
baseline <- stools %>% 
  group_by(pid) %>% 
  arrange(day) %>% 
  slice_min(day) %>% 
  # the baseline sample need to be up until day 0
  filter(day < 1) %>% 
  # remove the patient CMT026 for now
  filter(pid != 'CMT026') %>% 
  inner_join(alpha) %>% 
  inner_join(ptb) %>% 
  # remove three diseases that there are only one patient
  filter(!disease %in% removedisease) 
```

```{r}
# the patients only in the baseline samples
ptb_clean_BL <- ptb %>% 
  select( -disease_class, -orr, -crs_grade) %>% 
  rename(age = age_at_infusion) %>% 
  rename_all(str_to_title) %>% 
  rename(CR = Cr, CRS = Crs) %>% 
  filter(Pid %in% baseline$pid) %>% 
  select(-Pid)

ptb_clean_BL %>% 
  tbl_summary(
    #type = list(all_double() ~ "continuous"), 
    statistic = list(all_continuous() ~ "{mean} ({sd})")
  ) %>%
  bold_labels() %>% 
  as_gt() %>%
  #gt::tab_footnote(footnote = "MDS/MPN = Myelodysplastic/myeloproliferative neoplasms") %>% 
  gt::gtsave(filename = "../data/002_pt_BL.pdf")
```


```{r}
baseline %>% 
  select(-orr) %>% 
  gather('grp', 'response', cr:toxicity) %>% 
  ggboxplot(x = 'response', y ='inv', add = 'dotplot', ylab = 'alpha diversity', title = '') +
  facet_grid(grp ~ disease) +
      stat_compare_means(comparisons= list(c('Y', 'N')),
            label= "p.format",
            method= 'wilcox.test',
						correct=FALSE)
ggsave('../data/002_baseline_two.pdf', width = 8, height = 7)
```

