ln -s ~/my_workdir/samples/Sample_1101T*/*R1* ~/my_workdir/samples/raw_input_R1.6.fastq.gz
ln -s ~/my_workdir/samples/Sample_1170R*/*R1* ~/my_workdir/samples/raw_input_R1.7.fastq.gz
ln -s ~/my_workdir/samples/Sample_1191U*/*R1* ~/my_workdir/samples/raw_input_R1.8.fastq.gz
ln -s ~/my_workdir/samples/Sample_1262N*/*R1* ~/my_workdir/samples/raw_input_R1.9.fastq.gz
ln -s ~/my_workdir/samples/Sample_1277P*/*R1* ~/my_workdir/samples/raw_input_R1.10.fastq.gz
ln -s ~/my_workdir/samples/Sample_1101T*/*R2* ~/my_workdir/samples/raw_input_R2.6.fastq.gz
ln -s ~/my_workdir/samples/Sample_1170R*/*R2* ~/my_workdir/samples/raw_input_R2.7.fastq.gz
ln -s ~/my_workdir/samples/Sample_1191U*/*R2* ~/my_workdir/samples/raw_input_R2.8.fastq.gz
ln -s ~/my_workdir/samples/Sample_1262N*/*R2* ~/my_workdir/samples/raw_input_R2.9.fastq.gz
ln -s ~/my_workdir/samples/Sample_1277P*/*R2* ~/my_workdir/samples/raw_input_R2.10.fastq.gz
