---
title: "Chi samples 16s metrics"
author: "Angel"
date: "2022-09-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(vdbR)
connect_database()
get_table_from_database('asv_alpha_diversity_ag')
```

for the quality of the sequences gather data from fastqc data like this:

```{r}
# >>Per sequence quality scores	pass
# #Quality	Count
# 11	1.0
# 12	0.0
# 13	0.0
# 14	0.0
# 15	1.0
# 16	2.0
# 17	2.0
# 18	2.0
# 19	4.0
# 20	3.0
# 21	16.0
# 22	27.0
# 23	77.0
# 24	140.0
# 25	263.0
# 26	539.0
# 27	927.0
# 28	1488.0
# 29	2166.0
# 30	3208.0
# 31	4735.0
# 32	6887.0
# 33	10271.0
# 34	17106.0
# 35	33208.0
# 36	45957.0
# 37	330.0
```

## for the 16s

Get the # read of raw and after filterandtrim
Get the quality score FastQC: for demultiplexed fastq files (16S) 

```{r}
# the samples in the 16s
amplicon <- read_csv('../data/whole_cohort_oligos_id.csv')

# find the demultiplexed fastq path
ampath <- amplicon %>% 
  inner_join(asv_alpha_diversity_ag)
```

