mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.1_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.2_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.3_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.4_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.5_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.7_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.8_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.10_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.11_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.14_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.15_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.16_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.17_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.18_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.19_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.20_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.22_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.23_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.26_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.31_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.32_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.33_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.34_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.36_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.37_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.38_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.39_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.40_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.41_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.42_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.43_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.44_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.45_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.46_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.47_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.48_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.49_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.51_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.52_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.53_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.54_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.55_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.59_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.62_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.63_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.66_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.67_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.68_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.71_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.76_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.78_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.79_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.80_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.81_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.82_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.83_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.84_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.85_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.86_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.88_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.89_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.91_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.92_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.93_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.95_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.96_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.97_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.101_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.102_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.103_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.104_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.105_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.106_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.107_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.108_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.109_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.110_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.111_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.112_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.113_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.114_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.115_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.116_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.118_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.119_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.120_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.122_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.123_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.125_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.127_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.128_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.129_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.130_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.131_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.134_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.135_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.136_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.137_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.138_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.139_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.140_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.142_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.144_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.145_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.146_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.147_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.148_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.149_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.150_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.172_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.175_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.176_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.177_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.178_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.181_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.182_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.183_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.184_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.185_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.186_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.187_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.188_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.189_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.190_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.191_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.193_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.196_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.197_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.198_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.200_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.201_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.202_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.203_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.204_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.205_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.206_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.208_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.210_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.212_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.215_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.216_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.217_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.218_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.219_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.220_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.221_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.222_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.223_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.224_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.225_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.226_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.227_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.229_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.230_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.231_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.232_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.233_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.234_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.235_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.236_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.237_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.238_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.239_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.240_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.241_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.242_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.243_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.246_R1.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.1_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.2_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.3_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.4_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.5_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.7_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.8_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.10_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.11_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.14_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.15_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.16_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.17_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.18_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.19_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.20_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.22_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.23_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.26_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.31_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.32_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.33_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.34_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.36_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.37_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.38_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.39_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.40_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.41_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.42_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.43_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.44_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.45_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.46_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.47_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.48_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.49_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.51_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.52_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.53_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.54_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.55_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.59_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.62_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.63_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.66_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.67_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.68_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.71_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.76_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.78_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.79_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.80_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.81_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.82_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.83_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.84_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.85_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.86_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.88_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.89_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.91_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.92_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.93_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.95_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.96_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.97_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.101_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.102_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.103_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.104_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.105_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.106_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.107_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.108_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.109_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.110_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.111_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.112_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.113_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.114_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.115_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.116_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.118_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.119_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.120_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.122_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.123_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.125_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.127_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.128_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.129_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.130_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.131_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.134_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.135_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.136_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.137_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.138_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.139_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.140_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.142_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.144_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.145_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.146_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.147_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.148_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.149_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.150_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.172_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.175_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.176_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.177_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.178_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.181_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.182_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.183_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.184_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.185_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.186_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.187_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.188_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.189_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.190_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.191_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.193_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.196_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.197_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.198_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.200_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.201_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.202_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.203_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.204_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.205_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.206_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.208_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.210_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.212_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.215_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.216_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.217_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.218_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.219_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.220_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.221_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.222_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.223_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.224_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.225_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.226_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.227_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.229_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.230_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.231_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.232_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.233_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.234_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.235_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.236_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.237_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.238_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.239_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.240_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.241_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.242_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.243_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
mv /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/91.tp.246_R2.fastq.gz /Users/daia1/MSK/work/projects/MSS_pipeline-/scripts/dada2_pipeline/data/downloaded/send
