---
title: "The beta diversity"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

## Load lib and tables

```{r}
library(tidyverse)
library(ggpubr)
library(vegan)
```

```{r}
# load the tables of the samples
df_baseline <- read_csv('../data/df_baseline.csv')
df_peri <- read_csv('../data/df_peri.csv')

# load the tsne coordinates table in the db
source('~/db.R')
dbListTables(con) %>% data.frame() %>% filter(grepl('tsne', .))
tsnec <- get_data_from_query_OTU(0, 'tsne_ag')
```

```{r}
# get the t1_scaled and t2_scaled from the db and join to the table
time <- bind_rows(
  df_baseline %>% 
    mutate(period = 'baseline'),
  df_peri %>% 
    mutate(period = 'peri')
) %>% 
  left_join(tsnec %>% select(sampleid, t1_scaled, t2_scaled), by = 'sampleid')
```

## TSNE visualizations

```{r}
# few samples don't have the tsne in the db
time %>% 
  filter(!is.na(t1_scaled)) %>% 
  ggscatter(x = 't1_scaled', y = 't2_scaled', color = 'eth', palette = 'jco', alpha = 0.8, 
            title = 'TSNE for two period of time') +
  facet_wrap(~period)
```

## Adonis test

http://rfunctions.blogspot.com/2019/03/betadisper-and-adonis-homogeneity-of.html

```{r}
source('~/db.R')
source('~/db_connect_simple.R')
get_table_from_database_predefined_filter('asv_counts_ag')
ANNOT <- get_data_from_query_OTU(0, 'asv_annotation_blast_ag')
```

### baseline

```{r}
# get the counts of those baseline samples 
# THERE ARE DUPLICATED SAMPLES IN THE CTS TABLE SO NEED TO REMOVE THE LOWER TOTAL COUNT ONES!!!!!
cts_bl <- asv_counts_ag %>% 
  filter(sampleid %in% df_baseline$sampleid)

cts_bl %>% 
  count(sampleid)
# good we have all the samples counts

cts_baseline <- cts_bl %>% 
  select(asv_key, sampleid, count) %>% 
  spread(key = 'sampleid', value = 'count', fill = 0) %>% 
  arrange(asv_key) %>% 
  column_to_rownames('asv_key') %>% 
  as.matrix()

dim(cts_baseline)
# cts_baseline %>% 
#   distinct(asv_key, sampleid)
```


```{r}
# filter out the singletons that have a count <= 50
# if we just count > 0 singletons
table(rowSums(cts_baseline > 0))

# remove the singletons that have a count <= 50
singletons_ma <- cts_baseline[rowSums(cts_baseline > 0) == 1,]
singletons_rm <- rownames(singletons_ma[rowSums(singletons_ma) <= 50,])

cts_baseline_fil <- cts_baseline[!rownames(cts_baseline) %in% singletons_rm,]
dim(cts_baseline_fil)
```

```{r}
dim(cts_baseline_fil)
cts_baseline_fil %>% 
  write.table('../data/cts_baseline_fil.txt', row.names = T, quote = F, sep = ',')
```


```{r}
# get the species info for the asv_key
annot <- ANNOT %>% 
  filter(asv_key %in% rownames(cts_baseline_fil)) %>% 
  mutate(ordr =  if_else(ordr == '', str_glue('of_class_{class}'), ordr),
         family =  if_else(family == '', str_glue('of_order_{ordr}'), family),
         genus =  if_else(genus == '', str_glue('of_family_{family}'), genus),
         species =  if_else(species == '', str_glue('of_genus_{genus}'), species)) %>% 
  mutate(taxa = str_glue('k__{kingdom}|p__{phylum}|c__{class}|o__{ordr}|f__{family}|g__{genus}|s__{species}'))

same_spp <- annot %>% 
  count(taxa) %>% 
  arrange(desc(n))

cts_baseline_fil_spp <- cts_baseline_fil %>% 
  as.data.frame() %>% 
  rownames_to_column('asv_key') %>% 
  full_join(annot %>%  select(asv_key, taxa), by  = 'asv_key') %>% 
  select(-asv_key) %>% 
  gather(key = 'sampleid', value = 'count', names(.)[1]:names(.)[ncol(.) - 1]) %>% 
  group_by(sampleid, taxa) %>% 
  summarise(cnt = sum(count)) %>% 
  spread(key = 'taxa', value = 'cnt') %>% 
  column_to_rownames('sampleid') 


dim(cts_baseline_fil_spp)
```

```{r}
# the pheno for the baseline samples 
cts_baseline_pheno <- df_baseline %>% 
  filter(sampleid %in% rownames(cts_baseline_fil_spp)) 

all.equal(rownames(cts_baseline_fil_spp), df_baseline$sampleid)
```


```{r}
# the adonis test
range(cts_baseline_fil_spp^0.25) # suitable range! double square root transformation
dist_bl_spp <- vegdist(cts_baseline_fil_spp^0.25, method = 'bray')
```

```{r}
# NMDS
# nmds <- metaMDS(dist_bl_spp)
# op <- ordiplot(nmds, type = 'n')
# cols <- c('blue','red')
# points(nmds, cex =2, pch =16, col=cols[cts_baseline_pheno$eth])
```


```{r}
pmv <- adonis(cts_baseline_fil_spp^0.25 ~ eth, data=cts_baseline_pheno, permutations=999, method = 'bray')
pmv
#densityplot(permustats(pmv))
```
```{r}
# distance based dispersion test
bd <- betadisper(dist_bl_spp, cts_baseline_pheno$eth)
boxplot(bd)
anova(bd)
permutest(bd)

# which spp are responsible for the difference
sim <- simper(cts_baseline_fil_spp^0.25 , group = cts_baseline_pheno$eth)
summary(sim)
```



```{r}
# Load libraries
library(microbiome)
library(ggplot2)
library(dplyr)

# Probiotics intervention example data 
data(peerj32) # Source: https://peerj.com/articles/32/
pseq <- peerj32$phyloseq # Rename the example data

# Pick relative abundances (compositional) and sample metadata 
pseq.rel <- microbiome::transform(pseq, "compositional")
otu <- abundances(pseq.rel)
meta <- meta(pseq.rel)


data<-read.csv('~/Downloads/datatest.csv',header=T,row.names=1,sep=";")
```



