---
title: "Compare Bio-Me normalized absolute quantification of the samples with our 16s results"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
library(tidyverse)
library(ggpubr)
library(kableExtra)
```

## Load the normalized absolute quantification from BioMe

```{r}
normcts <- read_csv('../data/frombiome/Merged Client Report_only_abundance.csv', 
                    col_types = cols(.default = col_number(), `Sample ID` = col_character())) %>%
  rename_all(~ gsub(" ", "_", .)) %>% 
  gather('species', 'normcts', names(.)[2]: names(.)[ncol(.)])
```


```{r}
# count the number of NA in each sample
normcts %>% 
  filter(is.na(normcts)) %>% 
  count(Sample_ID) %>% arrange(n)

all_NA_rm <- normcts %>% 
  filter(is.na(normcts)) %>% 
  count(Sample_ID) %>% 
  filter(n == 106) %>% 
  pull(Sample_ID)

# 20 samples to be reomved completely
normcts__ <- normcts %>% 
  filter(! Sample_ID %in% all_NA_rm) %>% 
  rename(sampleid = Sample_ID)

# how many effective samples went into comparison 
normcts__ %>% 
  distinct(sampleid) %>% 
  nrow
  
```

## summarise the bio-me table into genus level abundance

```{r}
# look at the species name in this table
biome_spp <- normcts__ %>% 
  distinct(species)

# need to remove the trail _subsp.....
# and break the species to make genus and the species name
normcts___ <- normcts__ %>% 
  mutate(species = str_replace(species, '_subsp.+$','')) %>% 
  separate(species, into = c('genus','species'), sep = '_', remove = T) %>% 
  group_by(sampleid , genus) %>% 
  summarise(ge_ncts = sum(normcts))

```

## Load our relab of the species of the same samples

```{r}
# our spp
library(vdbR)
connect_database(config_file = '~/dbConfig.txt')
get_table_from_database('asv_annotation_blast_ag')


# get the count relative and the annotation of the genus in the samples from our database
ourcts <- get_counts_subset(normcts___$sampleid) %>% 
  select(asv_key, sampleid, count_relative)


annot <- asv_annotation_blast_ag %>% 
  filter(asv_key %in% ourcts$asv_key) %>% 
  mutate(ordr =  if_else(ordr == '', str_glue('of_class_{class}'), ordr),
         family =  if_else(family == '', str_glue('of_order_{ordr}'), family),
         genus =  if_else(genus == '', str_glue('of_family_{family}'), genus),
         species =  if_else(species == '', str_glue('of_genus_{genus}'), species)) 

# replace the asv_key with the genus taxa level
# summarize from asv level to genus level
# get the relative abundance for the genera
ourcts_all <- ourcts %>% 
  left_join(annot %>%  select(asv_key, genus), by  = 'asv_key') %>% 
  group_by(sampleid, genus) %>% 
  summarise(relab = sum(count_relative)) %>% 
  ungroup() 

```

## How many genera are overlapping and how many are missing

```{r}
# the overlap of the species name
biome_genus <- normcts___ %>% 
  distinct(genus) %>% 
  pull(genus)

our_genus <- ourcts_all %>% 
  distinct(genus)%>%  
  pull(genus)

# a venn diagram
library(ggvenn)
two_list <- list(
  our_genus = our_genus,
  biome_genus = biome_genus)

ggvenn(two_list)

# the 4 that show in biome genus only 
setdiff(biome_genus, our_genus)
```

## the correlation between the overlapping genera at log10 transformed scales 

```{r}
all <- normcts___ %>% 
  inner_join(ourcts_all, by = c("sampleid", "genus")) %>% 
  # log10 transform both here
  mutate(logge_ncts = log10(ge_ncts + 1),
         logrelab = log10(relab + 2*10^-6))

# spearman correlation
spearman_res <- all %>% 
  split(.$sampleid) %>% 
  map(function(df){
    test = cor.test(df$logge_ncts, df$logrelab, method = 'spearman', exact = F)
    return(list(rho = round(test$estimate, 2), pval = test$p.value))
}) %>% 
  bind_rows(.id = 'sampleid')

# plot
# look at the distribution of the spearman correlation 
spearman_res %>% 
  ggboxplot(y = 'rho', add = 'jitter',
            ylab = 'Spearman rho', xlab = '')


# look at a series of scatterplot with rho and pvalue
all %>% 
  ggscatter(x = 'logge_ncts', y = 'logrelab', facet.by = 'sampleid',
            add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n")) +
  ggsave('../data/all_samples_67_scatter_genus_spearman_log10.pdf', width = 20, height = 18)
```

