---
title: "gliph2"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
library(tidyverse)
```

Their webpage: http://50.255.35.37:8080/. The software's web portal.

## Format the TCR data

```{r}
fns <- list.files('/Volumes/vandenBrinkLab/Susan/Human GVHD/TCRseq files/', full.names = T)

test <- read_tsv(fns[1], col_types = cols(.default = "c")) %>% 
        filter(frame_type == 'In') %>% 
        select(CDR3b = cdr3_amino_acid,
               v_family,
               TRBV = v_gene,
               TRBJ = j_gene,
               sample_name = sample_name,
               templates) %>% 
        mutate(CDR3a = "NA") %>% 
        mutate(sample_name = str_replace(sample_name, '_TCRB$', '')) %>% 
        mutate(subject = str_extract(sample_name, '^Pt\\d')) %>% 
        mutate(condition = str_replace(sample_name, '^Pt\\d_','')) %>% 
        mutate(`subject:condition` = str_glue('{subject}:{condition}')) %>% 
        select(-sample_name, -subject, -condition) %>% 
        mutate(templates = as.numeric(templates))   %>% 
  mutate(TRBV = if_else(is.na(TRBV), v_family, TRBV)) %>% 
        group_by(CDR3b, TRBV, TRBJ, CDR3a, `subject:condition`) %>% 
        summarise(count = sum(templates)) %>% 
        mutate(TRBV = str_replace(TRBV, 'TCRB.',''),
               TRBJ = str_replace(TRBJ, 'TCRB.','')) %>% 
        mutate(TRBV = str_replace(TRBV, '/.+$',''),
               TRBJ = str_replace(TRBJ, '/.+$','')) %>% 
        separate(TRBV, into = c('v1','v2'), sep = '-') %>% 
        separate(TRBJ, into = c('j1','j2'), sep = '-')  %>% 
        mutate(v1 = str_remove(v1, "^0+"),
               v2 = str_remove(v2, "^0+"),
               j1 = str_remove(j1, "^0+"),
               j2 = str_remove(j2, "^0+")) %>% 
        mutate(TRBV = if_else(is.na(v1), "NA", as.character(str_glue('TRBV{v1}-{v2}'))),
               TRBJ = if_else(is.na(j1), "NA", as.character(str_glue('TRBJ{j1}-{j2}'))))  %>%
  mutate(TRBV = str_replace(TRBV, '-NA','')) %>% 
        select(-v1, -v2,-j1, -j2) %>% 
        select(CDR3b, TRBV, TRBJ, CDR3a, `subject:condition`, count)

test %>% 
  filter(str_detect(TRBV, 'NA'))
```


```{r}
# there are NA in the v gene and J gene

all <- fns %>% 
  map(~ read_tsv(., col_types = cols(.default = "c")) %>% 
        filter(frame_type == 'In') %>% 
        select(CDR3b = cdr3_amino_acid,
               TRBV = v_gene,
               TRBJ = j_gene,
               sample_name = sample_name,
               templates) %>% 
        mutate(CDR3a = "NA") %>% 
        mutate(sample_name = str_replace(sample_name, '_TCRB$', '')) %>% 
        mutate(subject = str_extract(sample_name, '^Pt\\d')) %>% 
        mutate(condition = str_replace(sample_name, '^Pt\\d_','')) %>% 
        mutate(`subject:condition` = str_glue('{subject}:{condition}')) %>% 
        select(-sample_name, -subject, -condition) %>% 
        mutate(templates = as.numeric(templates))   %>% 
        group_by(CDR3b, TRBV, TRBJ, CDR3a, `subject:condition`) %>% 
        summarise(count = sum(templates)) %>% 
        mutate(TRBV = str_replace(TRBV, 'TCRB.',''),
               TRBJ = str_replace(TRBJ, 'TCRB.','')) %>% 
        mutate(TRBV = str_replace(TRBV, '/.+$',''),
               TRBJ = str_replace(TRBJ, '/.+$','')) %>% 
        separate(TRBV, into = c('v1','v2'), sep = '-') %>% 
        separate(TRBJ, into = c('j1','j2'), sep = '-')  %>% 
        mutate(v1 = str_remove(v1, "^0+"),
               v2 = str_remove(v2, "^0+"),
               j1 = str_remove(j1, "^0+"),
               j2 = str_remove(j2, "^0+")) %>% 
        mutate(TRBV = if_else(is.na(v1), "NA", as.character(str_glue('TRBV{v1}-{v2}'))),
               TRBJ = if_else(is.na(j1), "NA", as.character(str_glue('TRBJ{j1}-{j2}'))))  %>% 
        select(-v1, -v2,-j1, -j2) %>% 
        select(CDR3b, TRBV, TRBJ, CDR3a, `subject:condition`, count)) %>% 
        bind_rows()

all %>% 
  write_tsv('../data/all_tcr_data.tsv', col_names = F)
  

head(all)

all %>% 
  ungroup() %>% 
  filter(`subject:condition` == 'Pt3:colon') %>% 
  write_csv('../data/Pt3_colon_TCR_data.csv')
```

## Format the HLA table

```{r} 
# format the hla file as requested
hla <- read_csv('../data/HLA.csv', col_names = F) %>% 
  filter(!is.na(X1)) %>% 
  mutate(X1 = str_replace(X1, '_','')) %>% 
  transmute(subject = X1,
            allele = str_glue('{X2}*{X3}'))  %>% 
  split(.$subject) %>% 
  map(~ select(.data = ., -subject) %>% 
        t() %>% 
        as.data.frame(stringsAsFactors = F) )  %>% 
  bind_rows(.id = 'subject') %>% 
  as.tibble()
  
  
hla %>% 
  write_tsv('../data/all_hla.tsv', col_names = F)
  


head(hla)
```

## Assemble the parameter file

```{bash}
cat ../software/gliph2/gliph2/paramter_file
```

## To run it on the MSKCC cluster 

```{r}
# run on MSKCC's lilac cluster (need to submit since it's using too much memory)
# ./irtools.centos -c paramter_file
```

Ended up running on the web portal

## A look at the results

```{r}
read_csv('../data/gliph2_output/P1277_7AQ2XEPW79.csv') %>% 
  head(n = 100) %>% 
  kableExtra::kable() %>% 
  kableExtra::kable_styling(position = 'left', full_width = F)
```




