---
title: "Random forest and the quest of finding important differentiating features"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F) 
```

```{r}
library(tidyverse)
library(randomForest)
library(ggpubr)
library(kableExtra)
library(arrangements)
```

# Load the data

```{r}
# it contains all the pheno and all the genera info
dat <- read_csv('../data/pheno_unconventional_periengr_d30_allsamples.csv')

range(dat$sample_day)

# dat %>% 
#   count(mrn)
```
 
# clean the pheno table

```{r}
# the categorical has to be factored
pheno <- dat %>% 
  distinct(mrn, MAIT_reconstitution, MAIT_Vd2) %>% 
  mutate(MAIT_reconstitution = factor(MAIT_reconstitution),
         MAIT_Vd2 = factor(MAIT_Vd2)) %>% 
  mutate(mrn = as.character(mrn)) %>% 
  arrange(mrn)

pheno %>% 
  count(MAIT_reconstitution)

pheno %>% 
  count(MAIT_Vd2)
```


# get the median relab for all genera

```{r}
cts_median <- dat %>% 
  select(mrn, sampleid, Abiotrophia:Xanthomonas) %>% 
  gather('genus', 'relab',names(.)[3]:names(.)[ncol(.)] ) %>% 
  group_by(mrn, genus) %>% 
  summarise(median_relab = median(relab)) %>% 
  spread('mrn', 'median_relab') 
  

# get the top most abundant N genera
N <- 50

cts_median_top <- cts_median %>% 
  mutate(genus_sum = rowSums(.[2:ncol(.)])) %>% 
  arrange(desc(genus_sum)) %>% 
  top_n(n = N) %>% 
  select(-genus_sum) %>% 
  gather('mrn', 'med_relab', names(.)[2]:names(.)[ncol(.)]) %>% 
  spread('genus', 'med_relab') %>% 
  arrange(mrn) %>% 
  column_to_rownames('mrn') %>% 
  as.matrix()

all.equal(rownames(cts_median_top), pheno$mrn)

```

# random forest


```{r}
# for MAIT_reconstitution
set.seed(100)
mod_recon <- randomForest(cts_median_top, pheno$MAIT_reconstitution, importance = T)

impor_feature <- importance(mod_recon, type=1) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = 'genus') %>% 
  arrange(desc(MeanDecreaseAccuracy))


# plot the err rate change
mod_recon  %>% 
  pluck('err.rate') %>% 
  as.data.frame() %>% 
  mutate(ntree = seq(1, nrow(.))) %>% 
  gather(key = 'type', value = 'ERR', names(.)[1]:names(.)[ncol(.)-1]) %>% 
  ggline(x = 'ntree', y = 'ERR', color = 'type', palette = 'jama') +
  labs(x = 'Number of trees', 
       y = 'Error rate')
```

```{r}
set.seed(456)
# for MAIT_Vd2
mod_vd2 <- randomForest(cts_median_top, pheno$MAIT_Vd2, importance = T)

impor_feature <- importance(mod_vd2, type=1) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = 'genus') %>% 
  arrange(MeanDecreaseAccuracy)
 

# plot the err rate change
mod_vd2  %>% 
  pluck('err.rate') %>% 
  as.data.frame() %>% 
  mutate(ntree = seq(1, nrow(.))) %>% 
  gather(key = 'type', value = 'ERR', names(.)[1]:names(.)[ncol(.)-1]) %>% 
  ggline(x = 'ntree', y = 'ERR', color = 'type', palette = 'jama') +
  labs(x = 'Number of trees', 
       y = 'Error rate')
```

# the simper method

```{r}
set.seed(998)
library(vegan)
pmv_mait <- adonis(cts_median_top ~ MAIT_reconstitution, data=pheno, permutations=999, method = 'bray')
pmv_mait

pmv_vd2 <- adonis(cts_median_top ~ MAIT_Vd2, data=pheno, permutations=999, method = 'bray')
pmv_vd2


# to see the within group dispersion
dist_pmv <- vegdist(cts_median_top, method = 'bray')
bd <- betadisper(dist_pmv, pheno$MAIT_Vd2)
boxplot(bd)
anova(bd)        
```

```{r}
# use a loop to try all the vd2 combinations
vd2_4 <- pheno %>% 
  mutate(MAIT_Vd2 = as.character(MAIT_Vd2)) %>% 
  distinct(MAIT_Vd2) %>% 
  pull(MAIT_Vd2)

combi <- combinations(vd2_4, 2) %>% 
  as.data.frame() 
  
combi

all_top <- cts_median_top %>% 
  as.data.frame() %>% 
  rownames_to_column('mrn') %>% 
  full_join(pheno, by = 'mrn')
```

```{r}
set.seed(1001)
pairwise_adonis <- apply(combi, 1, function(Row){

  pheno_sub <- pheno %>% 
    filter(MAIT_Vd2 %in% c(Row[['V1']],Row[['V2']])) %>% 
    arrange(mrn)
  
  cts_median_top_sub <- cts_median_top %>% 
    as.data.frame() %>% 
    rownames_to_column('mrn') %>% 
    filter(mrn %in% pheno_sub$mrn) %>% 
    arrange(mrn) %>% 
    column_to_rownames('mrn')
  
  # calculate the within group dispersion anova
  dist_pmv <- vegdist(cts_median_top_sub, method = 'bray')
  bd <- betadisper(dist_pmv, pheno_sub$MAIT_Vd2)
  anova_res <- anova(bd)  
  
  # get the top N most contributing features
  sim <- simper(cts_median_top_sub , group = pheno_sub$MAIT_Vd2)

  genus_contri <- summary(sim) %>% 
    pluck(str_glue("{Row[['V1']]}_{Row[['V2']]}")) %>% 
    rownames_to_column('genus') %>% 
    arrange(desc(average)) %>% 
    head(n = 20)
  
  if(all.equal(rownames(cts_median_top_sub), pheno_sub$mrn)  == T){
    pmv_pair_vd2 <- adonis(cts_median_top_sub ~ MAIT_Vd2, data=pheno_sub, permutations=999, method = 'bray')
    return(list(pw_adonis_pval = pmv_pair_vd2$aov.tab$`Pr(>F)`[1],
           anova_pval = anova_res$`Pr(>F)`[1],
           topN_feature_df = genus_contri))
  }else{
    stop("rownames don't match")
    }
})

pw_adonis_pval_list <- list() 
for(i in 1:nrow(combi)){
  pw_adonis_pval_list[[i]]= pairwise_adonis[[i]]$pw_adonis_pval
}


anova_pval_list <- list() 
for(i in 1:nrow(combi)){
  anova_pval_list[[i]]= pairwise_adonis[[i]]$anova_pval
}


pw_adonis_pval_df <- pw_adonis_pval_list %>%
  as.data.frame() %>% 
  gather('id', 'adonis_pval') %>% 
  select(-id)


anova_pval_df <- anova_pval_list %>%
  as.data.frame() %>% 
  gather('id', 'anova_pval') %>% 
  select(-id) 

pairwise_adonis_res <- bind_cols(combi, pw_adonis_pval_df, anova_pval_df) %>% 
  transmute(pair = str_glue('{V1}_{V2}'),
            adonis_pval,
            anova_pval) %>% 
  mutate(fdr_pw_adonis = p.adjust(adonis_pval, method = 'BH'))

pairwise_adonis_res
```


```{r}
pairwise_adonis[[1]]$topN_feature_df
 
pairwise_adonis[[2]]$topN_feature_df 
```


# take a look at the pcoa of the two comparisons that are significant above

```{r}
# for the none and Vd2	
Row <- list(V1 = 'none', V2 = 'Vd2') # have a relatively bigger sample size
#Row <- list(V1 = 'none', V2 = 'both')
#Row <- list(V1 = 'Vd2', V2 = 'MAIT')
pheno_sub <- pheno %>% 
  filter(MAIT_Vd2 %in% c(Row[['V1']],Row[['V2']])) %>% 
  arrange(mrn)

cts_median_top_sub <- cts_median_top %>% 
  as.data.frame() %>% 
  rownames_to_column('mrn') %>% 
  filter(mrn %in% pheno_sub$mrn) %>% 
  arrange(mrn) %>% 
  column_to_rownames('mrn')

# calculate the within group dispersion anova
dist_pmv <- vegdist(cts_median_top_sub, method = 'bray')

bc <- cmdscale(dist_pmv, k = 2) 

bc %>% 
    as.data.frame() %>% 
    rownames_to_column('mrn') %>% 
    full_join(pheno_sub, by = 'mrn') %>% 
    ggscatter(x = 'V1', y = 'V2', color =  'MAIT_Vd2',  palette = 'jco') +
    labs(x = 'PCo 1', y = 'PCo 2', title = 'PCoA (BC distance)') 

```


```{r}
# wanna try to see it in 3D
# 1. get the distance matrix 
distance_matrix <- as.matrix(dist_pmv)
distance_matrix %>% write.table('../data/none_vd2_BC_matrix.tsv', sep = '\t', row.names = T)

# also write out the pheno_sub to tsv
pheno_sub %>% 
  # cuz they will only accept certain strings to be first column name
  rename(sampleid = mrn) %>% 
  write_tsv('../data/none_vd2_pheno.tsv')
```

```{bash}
# import it into qiime qza object
#qiime tools import --input-path ../data/none_vd2_BC_matrix.tsv  --output-path  ../data/none_vd2_BC_matrix.qza --type "DistanceMatrix"
  
# get the pcoa for the dist matrix
#qiime diversity pcoa --i-distance-matrix ../data/none_vd2_BC_matrix.qza   --o-pcoa ../data/none_vd2_BC_pcoa.qza
   
# visualize with emperor
#qiime emperor plot  --i-pcoa ../data/none_vd2_BC_pcoa.qza   --m-metadata-file ../data/none_vd2_pheno.tsv --o-visualization  ../data/none_vd2_BC_emperor.qzv
```

# Does RF work on other situations like enterococcus dominations samples

```{r}
# do an experiment and see if we can tell 0 and 1 patients apart, dominated or not dominated
# day −20 to +24 relative to HCT domination
library(readxl)
mrns <- read_excel('../data/MRN_file_enterococcus dominated.xlsx')
mrns %>%  
  count(Enterococcus.30)

set.seed(1)
# have a sample of 20 in each
sub <- bind_rows(
  mrns %>% 
    filter(Enterococcus.30 == 1) %>% 
    sample_n(20),
  mrns %>% 
    filter(Enterococcus.30 == 0) %>% 
    sample_n(20)
)
```


```{r}
# get the median relab of the top 50 in that period
source('~/db_connect_simple.R')
connect_database(config_file = '~/dbConfig.txt')
allo <- get_table_from_database('patient_allo_ag')
castori <- get_table_from_database('samples_castori_ag')
get_table_from_database_predefined_filter('asv_counts_ag')
get_table_from_database_predefined_filter('asv_alpha_diversity_ag')
ANNOT <- get_table_from_database('asv_annotation_blast_ag')

get_table_from_database("multivariate_clean_frozen_set_ag")
get_table_from_database("frozen_set_ag")
```






# Test: use RF to predict/classify day relative to transplant

```{r}
frozen_set_ag %>% 
  count(institution)

frozen_set_ag %>% 
  filter(institution == 'MSK_allo') %>% 
  filter(day_relative_to_hct < 100) %>% 
  gghistogram('day_relative_to_hct', bins = 100)

# [-20,-10] and [15, 25] in msk patients samples 
set.seed(988)
N_samp <- 125
  
stb_sub <- frozen_set_ag %>% 
  filter(institution == 'MSK_allo') %>% 
  filter(day_relative_to_hct %in% -20:-10 | day_relative_to_hct %in% 15:25 ) %>% 
  mutate(grp = if_else(day_relative_to_hct > 0, 'post', 'pre')) %>% 
  arrange(patient_id, grp, day_relative_to_hct) %>% 
  distinct(patient_id, grp, .keep_all = T) %>% 
  split(.$grp) %>% 
  map_dfr(~ sample_n(tbl = ., size = N_samp))  %>% 
  mutate(grp = factor(grp, levels = c('pre','post')))

stb_sub %>% 
  count(grp)

stb_sub %>% 
  count(patient_id) %>% 
  arrange(desc(n)) 


```

```{r}
# get the relative abundance for the top 50 genera count matrix

cts <- asv_counts_ag %>% 
  filter(sampleid %in% stb_sub$sampleid) %>% 
  select(asv_key, sampleid, count) %>% 
  spread(key = 'sampleid', value = 'count', fill = 0) %>% 
  arrange(asv_key)  

ncol(cts) - 1

annot <- ANNOT %>% 
  filter(asv_key %in% cts$asv_key) %>% 
  mutate(ordr =  if_else(ordr == '', str_glue('of_class_{class}'), ordr),
         family =  if_else(family == '', str_glue('of_order_{ordr}'), family),
         genus =  if_else(genus == '', str_glue('of_family_{family}'), genus),
         species =  if_else(species == '', str_glue('of_genus_{genus}'), species)) %>% 
  mutate(taxa_genus = str_glue('k__{kingdom}|p__{phylum}|c__{class}|o__{ordr}|f__{family}|g__{genus}'))



cts_all <- cts %>% 
  full_join(annot %>%  select(asv_key, taxa_genus), by  = 'asv_key') %>% 
  select(-asv_key) %>% 
  gather(key = 'sampleid', value = 'count', names(.)[1]:names(.)[ncol(.) - 1]) %>% 
  group_by(sampleid, taxa_genus) %>% 
  summarise(cnt = sum(count)) %>% 
  # get the total count from the db to calculate the relab
  left_join(asv_counts_ag %>% distinct(sampleid,count_total ), by = 'sampleid') %>% 
  mutate(relab = cnt/count_total) %>% 
  select(sampleid, taxa_genus, relab) 
  
# top 50
N <- 50
topN_genus <- cts_all %>% 
  group_by(taxa_genus) %>% 
  summarise(genus_sum = sum(relab)) %>% 
  arrange(desc(genus_sum)) %>% 
  top_n(N) %>% 
  pull(taxa_genus)

cts_top <- cts_all %>% 
  filter(taxa_genus %in% topN_genus) %>% 
  spread(key = 'taxa_genus', value = 'relab') %>% 
  arrange(sampleid) 

dim(cts_top)
stb_sub %>% 
  count(grp)
```


```{r}
# split to training and test set
# training 70% of each group, test: remaining
train_num <- stb_sub %>% 
  count(grp) %>% 
  distinct(n) %>% 
  summarise(num = round(n * 0.7)) %>% 
  pull(num)

set.seed(1001)
train_samples <- stb_sub %>% 
  split(.$grp) %>% 
  map_dfr(~ sample_n(tbl = ., size = train_num)) %>% 
  pull(sampleid)

test_samples <- setdiff(stb_sub$sampleid, train_samples)
  

# get the counts and the pheno of the train and test
train_cts <- cts_top %>% 
  filter(sampleid %in% train_samples) %>% 
  arrange(sampleid) %>% 
  column_to_rownames('sampleid') %>% 
  as.matrix() 
  
train_pheno <- stb_sub %>% 
  filter(sampleid %in% rownames(train_cts)) %>% 
  arrange(sampleid) 

test_cts <- cts_top %>% 
  filter(!sampleid %in% train_samples) %>% 
  arrange(sampleid) %>% 
  column_to_rownames('sampleid') %>% 
  as.matrix() 

test_pheno <- stb_sub %>% 
  filter(sampleid %in% rownames(test_cts)) %>% 
  arrange(sampleid) 


#
all.equal(rownames(train_cts), train_pheno$sampleid)
all.equal(rownames(test_cts), test_pheno$sampleid)
```

```{r}
set.seed(123)  
mod <- randomForest(train_cts, train_pheno$grp, importance = T) 
mod

impor_feature <- importance(mod, type=1) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = 'genus') %>% 
  arrange(desc(MeanDecreaseAccuracy))

impor_feature %>% 
  head

#varImpPlot(mod) 

# plot the err rate change
mod  %>% 
  pluck('err.rate') %>% 
  as.data.frame() %>% 
  mutate(ntree = seq(1, nrow(.))) %>% 
  gather(key = 'type', value = 'ERR', names(.)[1]:names(.)[ncol(.)-1]) %>% 
  ggline(x = 'ntree', y = 'ERR', color = 'type', palette = 'jco') +
  labs(x = 'Number of trees', 
       y = 'Error rate',
       title = 'Error rate')  +
  ylim(0, 1)    

```
  
```{r}
# if use the day relative to transplant which is a continuous variable to do prediction
set.seed(777)  
mod_drt <- randomForest(train_cts, train_pheno$day_relative_to_hct, importance = T) 
mod_drt  

#sqrt(sum((mod_drt$predicted - sub_pheno$day_relative_to_hct)^2) / nrow(sub_pheno))
# test on the test set
yhat.bag <- predict(mod_drt, newdata=test_cts)
plot(yhat.bag, test_pheno$day_relative_to_hct)
abline(0,1) 
```
  
  