---
title: "chapter 7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rethinking)
## R code 7.1
sppnames <- c( "afarensis","africanus","habilis","boisei",
    "rudolfensis","ergaster","sapiens")
brainvolcc <- c( 438 , 452 , 612, 521, 752, 871, 1350 )
masskg <- c( 37.0 , 35.5 , 34.5 , 41.5 , 55.5 , 61.0 , 53.5 )
d <- data.frame( species=sppnames , brain=brainvolcc , mass=masskg )

## R code 7.2
d$mass_std <- (d$mass - mean(d$mass))/sd(d$mass)
d$brain_std <- d$brain / max(d$brain)
```

```{r}
## R code 7.3
m7.1 <- quap(
    alist(
        brain_std ~ dnorm( mu , exp(log_sigma) ),
        mu <- a + b*mass_std,
        a ~ dnorm( 0.5 , 1 ),
        b ~ dnorm( 0 , 10 ),
        log_sigma ~ dnorm( 0 , 1 )
    ), data=d )

## R code 7.4
m7.1_OLS <- lm( brain_std ~ mass_std , data=d )
post <- extract.samples( m7.1_OLS )

## R code 7.5
set.seed(12)
s <- sim( m7.1 )
r <- apply(s,2,mean) - d$brain_std
resid_var <- var2(r)
outcome_var <- var2( d$brain_std )
1 - resid_var/outcome_var
```

```{r}
## R code 7.6
R2_is_bad <- function( quap_fit ) {
    s <- sim( quap_fit , refresh=0 )
    r <- apply(s,2,mean) - d$brain_std
    1 - var2(r)/var2(d$brain_std)
}

## R code 7.7
m7.2 <- quap(
    alist(
        brain_std ~ dnorm( mu , exp(log_sigma) ),
        mu <- a + b[1]*mass_std + b[2]*mass_std^2,
        a ~ dnorm( 0.5 , 1 ),
        b ~ dnorm( 0 , 10 ),
        log_sigma ~ dnorm( 0 , 1 )
    ), data=d , start=list(b=rep(0,2)) )

## R code 7.8
m7.3 <- quap(
    alist(
        brain_std ~ dnorm( mu , exp(log_sigma) ),
        mu <- a + b[1]*mass_std + b[2]*mass_std^2 +
                  b[3]*mass_std^3,
        a ~ dnorm( 0.5 , 1 ),
        b ~ dnorm( 0 , 10 ),
        log_sigma ~ dnorm( 0 , 1 )
    ), data=d , start=list(b=rep(0,3)) )

m7.4 <- quap(
    alist(
        brain_std ~ dnorm( mu , exp(log_sigma) ),
        mu <- a + b[1]*mass_std + b[2]*mass_std^2 +
                  b[3]*mass_std^3 + b[4]*mass_std^4,
        a ~ dnorm( 0.5 , 1 ),
        b ~ dnorm( 0 , 10 ),
        log_sigma ~ dnorm( 0 , 1 )
    ), data=d , start=list(b=rep(0,4)) )

m7.5 <- quap(
    alist(
        brain_std ~ dnorm( mu , exp(log_sigma) ),
        mu <- a + b[1]*mass_std + b[2]*mass_std^2 +
                  b[3]*mass_std^3 + b[4]*mass_std^4 +
                  b[5]*mass_std^5,
        a ~ dnorm( 0.5 , 1 ),
        b ~ dnorm( 0 , 10 ),
        log_sigma ~ dnorm( 0 , 1 )
    ), data=d , start=list(b=rep(0,5)) )

## R code 7.9
m7.6 <- quap(
    alist(
        brain_std ~ dnorm( mu , 0.001 ),
        mu <- a + b[1]*mass_std + b[2]*mass_std^2 +
                  b[3]*mass_std^3 + b[4]*mass_std^4 +
                  b[5]*mass_std^5 + b[6]*mass_std^6,
        a ~ dnorm( 0.5 , 1 ),
        b ~ dnorm( 0 , 10 )
    ), data=d , start=list(b=rep(0,6)) )
```

```{r}
## R code 7.10
post <- extract.samples(m7.1)
mass_seq <- seq( from=min(d$mass_std) , to=max(d$mass_std) , length.out=100 )
l <- link( m7.1 , data=list( mass_std=mass_seq ) )
mu <- apply( l , 2 , mean )
ci <- apply( l , 2 , PI )
plot( brain_std ~ mass_std , data=d )
lines( mass_seq , mu )
shade( ci , mass_seq )

## R code 7.11
#d_minus_i <- d[ -i , ]
```


```{r}
## R code 7.12
p <- c( 0.3 , 0.7 )
-sum( p*log(p) )

```

```{r}
## R code 7.13
set.seed(1)
lppd( m7.1 , n=1e4 )
```

```{r}
data(Laffer)
Laffer$rate_std <- standardize(Laffer$tax_rate)
Laffer$revenue_std <- standardize(Laffer$tax_revenue)

mline <- quap(
    alist(
        revenue_std ~ dnorm( mu , sigma ),
        mu <- a + b*rate_std,
        a ~ dnorm( 0 , 1 ),
        b ~ dnorm( 0 , 1 ),
        sigma ~ dexp( 1 )
    ), data=Laffer )
plot(precis(mline))


mline2 <- quap(
    alist(
        revenue_std ~ dnorm( mu , sigma ),
        mu <- a + b*rate_std,
        a ~ dnorm( 0 , 1 ),
        b ~ dnorm( 0 , 0.5 ),
        sigma ~ dexp( 1 )
    ), data=Laffer )
plot(precis(mline2), precis(mline))


plot( coeftab( mline , mline2  ) , pars=c("a","b") )
```

```{r}
mcurve <- quap(
    alist(
        revenue_std ~ dnorm( mu , sigma ),
        mu <- a +  b[1]*rate_std + b[2]*rate_std^2,
        a ~ dnorm( 0 , 1 ),
        b ~ dnorm( 0 , 1 ),
        sigma ~ dexp( 1 )
    ), data=Laffer ,start=list(b=rep(0,2)) )
plot(precis(mcurve, depth = 2))


rate_std <- seq( from=-3.5 , to=1.5 , length.out=30 )
pred_dat <- list( weight_s=rate_std , weight_s2=rate_std^2 )
mu <- link( mcurve , data=pred_dat )
mu.mean <- apply( mu , 2 , mean )
mu.PI <- apply( mu , 2 , PI , prob=0.89 )
sim.height <- sim( mcurve , data=pred_dat )
height.PI <- apply( sim.height , 2 , PI , prob=0.89 )


plot( revenue_std ~ rate_std , Laffer, col=col.alpha(rangi2,0.5) )
lines( weight.seq , mu.mean )
shade( mu.PI , weight.seq )
shade( height.PI , weight.seq )
```

```{r}
compare(mline, mcurve, func = PSIS)

compare(mline, mcurve, func = WAIC)
```

