---
title: "double check my 67 diet cleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
```

```{r}
all_code <- read_csv('../data/cleaned_diet_data/all_food_nsc_with_code_FINAL.csv')

# some cleaning , remove unnecessary columns, filter out some unnecessary rows, change column types
all <- read_excel('../data/source/new_list.xls') %>% 
  filter(!str_detect(Food_NSC, '^\\*\\*\\*\\*\\*\\*\\*')) %>% 
  filter(Por_eaten != 'na') %>% 
  select(- ...1, - Food, -Por_ordered, -SFA_g, -Cholesterol_mg, -MUFA_g, -PUFA_g, -Name) %>% 
  mutate(Por_eaten = as.numeric(Por_eaten)) %>% 
  filter(Por_eaten > 0) %>% 
  # I have a code for them
  filter(Food_NSC %in% all_code$Food_NSC) %>%  
  mutate(Date = mdy(Date)) %>% 
  # get rid of the + in the values
  mutate(Calories_kcal = str_replace_all(Calories_kcal, '\\+$',''),
           Proteing_g = str_replace_all(Proteing_g, '\\+$',''),
           Fat_g = str_replace_all(Fat_g, '\\+$',''),
           Carbohydrates_g = str_replace_all(Carbohydrates_g, '\\+$',''),
           Fibers_g = str_replace_all(Fibers_g, '\\+$',''),
           Sugars_g = str_replace_all(Sugars_g, '\\+$',''),
           Sodium_mg = str_replace_all(Sodium_mg, '\\+$','')) %>% 
    mutate(Calories_kcal = as.numeric(Calories_kcal),
           Proteing_g = as.numeric(Proteing_g),
           Fat_g = as.numeric(Fat_g),
           Carbohydrates_g = as.numeric(Carbohydrates_g),
           Fibers_g = as.numeric(Fibers_g),
           Sugars_g = as.numeric(Sugars_g),
           Sodium_mg = as.numeric(Sodium_mg)) 
```

## correct the outliers

```{r}
outlier_cor <- read_csv('../data/outlier_very_obvious_peter.csv') %>% 
  select(Food_NSC, Por_eaten:Sodium_mg)

outlier_to_be_corrected <- all %>% 
  filter(Food_NSC %in% outlier_cor$Food_NSC)  %>% 
  distinct(Food_NSC, Por_eaten, .keep_all = T) %>% 
  select(MRN:Por_eaten) %>% 
  left_join(outlier_cor) %>% 
  arrange(Food_NSC) %>% 
  unite(col = 'food_full', Food_NSC:Unit, sep = '__', remove = T)


# ok I have to do this programmatically
outlier_cor_res <- outlier_to_be_corrected %>% 
  arrange(food_full, Calories_kcal) %>% 
  group_by(food_full) %>% 
  mutate(Calories_kcal = Calories_kcal[1],
         Proteing_g = Proteing_g[1],
         Fat_g = Fat_g[1],
         Carbohydrates_g = Carbohydrates_g[1],
         Fibers_g = Fibers_g[1],
         Sugars_g = Sugars_g[1],
         Sodium_mg = Sodium_mg[1]) %>% 
  split(.$food_full) %>% 
  map_dfr(~ mutate(.data = ., ratio = Por_eaten/Por_eaten[1]) %>% 
        split(.$Por_eaten) %>% 
        map_dfr(~ mutate(.data = .,   
                   Calories_kcal = Calories_kcal*ratio,
                   Proteing_g = Proteing_g*ratio,
                   Fat_g = Fat_g*ratio,
                   Carbohydrates_g = Carbohydrates_g*ratio,
                   Fibers_g = Fibers_g*ratio,
                   Sugars_g = Sugars_g*ratio,
                   Sodium_mg = Sodium_mg*ratio)) %>% 
        select(-ratio))
############################################################################# 

# integrate these to the original all df expanding 30 to 240
outlier_or_not <- all %>% 
  split(.$Food_NSC %in% outlier_cor$Food_NSC)

corrected_all <- outlier_or_not %>% 
  pluck('TRUE') %>% 
  unite(col = 'food_full', Food_NSC:Unit, sep = '__', remove = T) %>% 
  select(MRN: Por_eaten) %>% 
  left_join(outlier_cor_res %>% select(food_full:Sodium_mg), by = c('food_full','Por_eaten'))

# goddamn it, this is the problem what the hell is cheerios -- each!!!
corrected_all %>% 
  filter(is.na(Calories_kcal)) %>% 
  write_csv('../data/!question/the_ones_with_unit_each_3_outlier_records.csv')
##################################### 

all_cor1 <- bind_rows(
  corrected_all,
  outlier_or_not %>% pluck('FALSE') %>% unite(col = 'food_full', Food_NSC:Unit, sep = '__', remove = T) 
) 

#all_cor1 has the correct format but there is three NA rows from the corrected_all!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  
```

## correct the ones with ridiculous calories


```{r}
peter1 <- read_csv('../data/source/All_data_check_calories_peter.csv')
peter2 <- read_csv('../data/source/All_data_to_be_checked_peter.csv')
peter_cal <- bind_rows(peter1, peter2) %>% 
  unite(col = 'food_full', Food_NSC:Unit, sep = '__', remove = T) %>% 
  select(food_full, Por_eaten:Sodium_mg) 
  
  

# now do the things very similar to how I correct the outliers
all_peter_cal <- all_cor1 %>% 
  filter(food_full %in% peter_cal$food_full) %>% 
  distinct(food_full, Por_eaten, .keep_all = T) %>% 
  select(MRN:Por_eaten) %>% 
  left_join(peter_cal) %>% 
  arrange(food_full, Calories_kcal)
 
# use the ratio to correct other portions
cal_cor_res <- all_peter_cal %>% 
  group_by(food_full) %>% 
  mutate(Calories_kcal = Calories_kcal[1],
         Proteing_g = Proteing_g[1],
         Fat_g = Fat_g[1],
         Carbohydrates_g = Carbohydrates_g[1],
         Fibers_g = Fibers_g[1],
         Sugars_g = Sugars_g[1],
         Sodium_mg = Sodium_mg[1]) %>% 
  split(.$food_full) %>% 
  map_dfr(~ mutate(.data = ., ratio = Por_eaten/Por_eaten[1]) %>% 
        split(.$Por_eaten) %>% 
        map_dfr(~ mutate(.data = .,   
                   Calories_kcal = Calories_kcal*ratio,
                   Proteing_g = Proteing_g*ratio,
                   Fat_g = Fat_g*ratio,
                   Carbohydrates_g = Carbohydrates_g*ratio,
                   Fibers_g = Fibers_g*ratio,
                   Sugars_g = Sugars_g*ratio,
                   Sodium_mg = Sodium_mg*ratio)) %>% 
        select(-ratio))


# integrate
cal_or_not <- all_cor1 %>% 
  split(.$food_full %in% cal_cor_res$food_full)

corrected_all_cal <- cal_or_not %>% 
  pluck('TRUE') %>% 
  select(MRN: Por_eaten) %>% 
  left_join(cal_cor_res %>% select(food_full:Sodium_mg) %>% distinct(), by = c('food_full','Por_eaten'))

all_cor2 <- bind_rows(
  corrected_all_cal,
  cal_or_not %>% pluck('FALSE')
)
colnames(all_cor2) 
```

## check the NA ones

```{r}
# now peter has returned the corrected three rows now i add them back to the dataset
three <- read_csv('../data/!question/the_ones_with_unit_each_3_outlier_records_peter.csv') %>% 
  mutate(Date = mdy(Date))

all_cor2__ <- bind_rows(
  all_cor2 %>% 
    filter(!is.na(Calories_kcal)),
  three
)

# now there is no NA!!!!
```


```{r}
# to keep all of the unique rows (all values in the row should be unique)
all_cor3 <- all_cor2__ %>% 
  distinct() 


```

## the food with multiple items

```{r}
multiple <- read_csv('../data/more_than_one_Peter_updated.csv') %>% 
  # remove the Lettuce and Tomato Garnish cuz the cal dont match
  filter(item1_value_raw_raw != 'Lettuce and Tomato Garnish')



# clean the multiple and get back the total cal
multiple_clean <- multiple %>% 
  select(-item1_index, -WWEIA.Category.Code, -WWEIA.Category.Description, -weight) %>% 
  group_by(item1_value_raw_raw) %>% 
  mutate(total_cal = sum(Calories_kcal)) %>% 
  mutate(component = str_replace(FNDDS.Main.Food.Description, ',.+$','')) %>% 
  mutate(Food_NSC = str_glue('{item1_value_raw_raw}--{component}'))

# the food code for these newly created items that need to be added to my food code db
multiple_clean_code <- multiple_clean %>% 
  ungroup() %>% 
  distinct(Food_NSC, Food.Code, FNDDS.Main.Food.Description) 
  

final_all_code <- bind_rows(
  all_code,
  multiple_clean_code
) 

final_all_code %>% 
  write_csv('../data/cleaned_diet_data/all_food_nsc_with_code_FINAL.csv')
```




```{r}
# now expand the multiples to other portions 
multiple_all <- all_cor3 %>% 
  separate(food_full, into = c('Food_NSC','Unit'), sep = '__') %>% 
  filter(Food_NSC %in% multiple$item1_value_raw_raw) %>% 
  distinct(Food_NSC, Por_eaten, Calories_kcal) %>% 
  arrange(Food_NSC) %>% 
  left_join(multiple_clean, by = c('Food_NSC'='item1_value_raw_raw','Calories_kcal'='total_cal')) %>% 
  select(-component)


# decided to output and manually correct it
multiple_all %>% 
  write_csv('../data/multiple_all_manually.csv')

# load back the manually corrected ones
multiple_all_cor <- read_csv('../data/multiple_all_manually_Angel.csv')

multiple_df_all <-  all_cor3 %>% 
  separate(food_full, into = c('Food_NSC','Unit'), sep = '__') %>% 
  filter(Food_NSC %in% multiple$item1_value_raw_raw) %>% 
  select(MRN:Por_eaten) %>% 
  left_join(multiple_all_cor, by = c('Food_NSC','Por_eaten')) %>% 
  select(-Calories_kcal, -Food.Code, -FNDDS.Main.Food.Description) %>% 
  select(-Food_NSC) %>% 
  rename(Food_NSC = Food_NSC.y.y) %>% 
  select(MRN:Meal, Food_NSC, Unit:Sodium_mg) %>% 
  rename(Calories_kcal = Calories_kcal.y)  
  
```


```{r}
# finally I can split the all_cor3 df and change this part about the multiples
all_cor3_split <- all_cor3 %>% 
  separate(food_full, into = c('Food_NSC','Unit'), sep = '__') %>% 
  split(.$Food_NSC %in% multiple$item1_value_raw_raw)

all_cor4 <- bind_rows(
  all_cor3_split %>% 
    pluck('FALSE'),
  multiple_df_all
)    
```

```{r}
all_cor4 %>% 
  summary()

# there are some NAs in all_cor4, output and manually correct them
all_cor4 %>% 
  write_csv('../data/!question/all_cor4.csv')

```


```{r}
protein_and_fat_NA <- all_cor4 %>% 
  filter(is.na(Proteing_g)) %>% 
  distinct(Food_NSC) %>% 
  pull(Food_NSC)

all_cor4 %>% 
  filter(Food_NSC %in% protein_and_fat_NA) %>% 
  arrange(Food_NSC, Unit) %>% 
  write_csv('../data/!question/protein_and_fat_NA_ones.csv')
```
```{r}
sugar_NA  <- all_cor4 %>% 
  filter(is.na(Sugars_g)) %>% 
  distinct(Food_NSC) %>% 
  arrange(Food_NSC) %>% 
  pull(Food_NSC)

sugar_NA_df <- all_cor4 %>% 
  filter(Food_NSC %in% sugar_NA) %>% 
  arrange(Food_NSC, Unit) %>% 
  select(Food_NSC:Sodium_mg) %>% 
  distinct()

###
fiber_NA  <- all_cor4 %>% 
  filter(is.na(Fibers_g)) %>% 
  distinct(Food_NSC) %>% 
  pull(Food_NSC)

fiber_NA_df <- all_cor4 %>% 
  filter(Food_NSC %in% fiber_NA) %>% 
  arrange(Food_NSC, Unit) %>% 
  select(Food_NSC:Sodium_mg) %>% 
  distinct()

length(intersect(fiber_NA, sugar_NA))

sugar_NA_df %>% 
  write_csv('../data/!question/sugar_and_fiber_NA_ones.csv')
```
 
**next is to integrate peter filled ones to the original all_cor4**

```{r}
sugar_and_fiber_filled <- read_csv('../data/!question/sugar_and_fiber_NA_ones_peter.csv') %>% 
  distinct(Food_NSC, Unit, Por_eaten, .keep_all = T)

# integrate the above info into all_cor4
all_cor4 <- read_csv('../data/!question/all_cor4.csv')

all_cor4_split_sugar_and_fiber <- all_cor4 %>% 
  split(.$Food_NSC %in% sugar_NA)

corrected_sugar_and_fiber <- all_cor4_split_sugar_and_fiber %>% 
  pluck('TRUE') %>% 
  select(MRN: Por_eaten) %>% 
  left_join(sugar_and_fiber_filled %>% select(Food_NSC:Sodium_mg) %>% distinct(), by = c("Food_NSC", "Unit", "Por_eaten")) 
 
all_cor5 <- bind_rows(
  corrected_sugar_and_fiber,
  all_cor4_split_sugar_and_fiber %>% pluck('FALSE')
)
summary(all_cor5)


```


 
## the calories == 0 ones that I need peter to give me the gram weight, all of the patients together

```{r}
old_cal0 <-  all_cor3 %>% 
  filter(Calories_kcal == 0) %>% 
  select(Food_NSC:Sodium_mg) %>% 
  distinct(Food_NSC, Por_eaten, Calories_kcal)


# WAIT FOR PETER TO CORRECT NA ONES FOR THIS PART CUZ SOME OF THE NA ONES SHOULD BE ZERO
new_cal0 <- read_csv('../data/cleaned_diet_data/new_all_cleaned_with_NA.csv')
```

