---
title: "the patient info meta data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This script is for organizing the meta data of the patient info, including transplant and nutrition info. intensity and source from the patient allo ag table. age, sex and admit_bmi from the nutrition_demographics_ag table.

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
source('~/db_connect_simple.R')
connect_database(config_file = '~/dbConfig.txt')
#dbListTables(con) %>% data.frame() %>% filter(grepl('nutri',.))
```

```{r}
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
```


## the demographic info

```{r}
# the current nutritional info that we have

#nutri <- get_table_from_database('nutrition_ag')
get_table_from_database('nutrition_demographics_ag')

# the info from this table that I wanna integrate into my meta
demo <- demogr %>% 
  select(mrn, sex, age_at_hsct, admit_bmi) %>% 
  filter(mrn %in% dtb$mrn)

nrow(demo)

# THERE ARE A DOZEN NA FOR THE PATIENTS the sex age and bmi column
demo %>% 
  filter(is.na(sex))

# ignore this table for now


# patients that missing the weight
wt <- nutrition_demographics_ag %>% 
  filter(mrn %in% dtb$mrn)  %>% 
  filter(is.na(admit_wt)) %>% 
  pull(mrn)
```

## the transplant info, only the source and intensity for now

```{r}
# getting the conmorbitity index from the table
list_table_from_database(pattern = 'comorbidity')
get_table_from_database('comorbidity_index_ag')
get_table_from_database('patients_msk_comorbidity_index_ag')

ci_pt <- patients_msk_comorbidity_index_ag %>% 
  filter(mrn %in% dtb$mrn)

have_ci_pts <- ci_pt %>% 
  filter(!is.na(ci))

need_ci_pts <- setdiff(dtb$mrn, have_ci_pts %>% pull(mrn))
# the above is the list that I need to have the CI

length(intersect(wt, need_ci_pts))

need_info <- tibble(
  mrn = need_ci_pts
) %>% 
  left_join(nutrition_demographics_ag %>% filter(mrn %in% dtb$mrn) %>% select(mrn, admit_wt))

need_info %>% 
  write_csv('../data/!question/patients_missing_CI_and_wt_diet.csv')

```


also getting the age and sex from this table

```{r}
get_table_from_database('patient_allo_ag')

# Collapse MSKCC messy diseases into broad, simplified categories
patient_allo_ag$disease.simple[patient_allo_ag$disease == "Leukemia" &
                                         patient_allo_ag$sub_hist == "Acute" &
                                         patient_allo_ag$sub_sub_hist == "Myelogenous"] <- "AML"
patient_allo_ag$disease.simple[patient_allo_ag$disease == "Leukemia" &
                                         patient_allo_ag$sub_hist == "Acute" &
                                         patient_allo_ag$sub_sub_hist == "Lymphoblastic"] <- "ALL"
patient_allo_ag$disease.simple[patient_allo_ag$disease == "Leukemia" &
                                         patient_allo_ag$sub_hist == "Chronic" &
                                         patient_allo_ag$sub_sub_hist == "Myelogenous"] <- "CML"
patient_allo_ag$disease.simple[patient_allo_ag$disease == "Leukemia" &
                                         patient_allo_ag$sub_hist == "Chronic" &
                                         patient_allo_ag$sub_sub_hist == "Myelomonocytic"] <- "MDS/MPN"
patient_allo_ag$disease.simple[patient_allo_ag$disease == "Leukemia (Second Primary)" &
                                         patient_allo_ag$sub_hist == "Acute" &
                                         patient_allo_ag$sub_sub_hist == "Myelogenous"] <- "AML"
patient_allo_ag$disease.simple[patient_allo_ag$disease == "Leukemia" &
                                         patient_allo_ag$sub_hist == "Acute" &
                                         (patient_allo_ag$sub_sub_hist == "Monoblastic" | 
                                            patient_allo_ag$sub_sub_hist == "Monocytic" |
                                            patient_allo_ag$sub_sub_hist == "Myelomonocytic" |
                                            patient_allo_ag$sub_sub_hist =="Promyelocytic")   ] <- "AML"
patient_allo_ag$disease.simple[grepl("Aplastic", patient_allo_ag$disease)] <- "AA"
patient_allo_ag$disease.simple[grepl("Aplastic", patient_allo_ag$sub_hist)] <- "AA"
patient_allo_ag$disease.simple[grepl("Myelodysplastic|Myeloproliferative", patient_allo_ag$disease)] <- "MDS/MPN"
patient_allo_ag$disease.simple[grepl("Non-Hodgkin", patient_allo_ag$disease)] <- "NHL"
patient_allo_ag$disease.simple[grepl("Myeloma", patient_allo_ag$disease)] <- "Myeloma"
patient_allo_ag$disease.simple[grepl("Hodgkin's Disease", patient_allo_ag$disease)] <- "Hodgkins"
patient_allo_ag$disease.simple[grepl("CLL", patient_allo_ag$sub_sub_hist)] <- "CLL"
patient_allo_ag$disease.simple %>% table(useNA ="ifany") %>% data.frame() %>% arrange(-Freq)
patient_allo_ag$disease.simple[grepl("Prolymphocytic", patient_allo_ag$sub_sub_hist)] <- "NHL"
patient_allo_ag$disease.simple[grepl("Biphenotypic|Plasmacytoid Dendritic|Ambiguous|NK-LGL", patient_allo_ag$sub_sub_hist)] <- "other"
patient_allo_ag$disease.simple[grepl("Non-Malignant Hemat Disorders", patient_allo_ag$disease)] <- "other"
patient_allo_ag$disease.simple %>% table(useNA  = "ifany")
```


```{r}
other <- patient_allo_ag %>% 
  filter(str_detect(indication, fixed('initial', ignore_case = T))) %>% 
  select(mrn, source , intensity, hct, age, sex, disease.simple) %>%  
  filter(mrn %in% dtb$mrn) %>% 
  mutate(source = if_else(str_detect(source, 'Cord' ), 
                             'cord',
                             if_else(str_detect(source, 'SBA|CD34'), 
                                     'TCD',
                                     'unmodified'))) %>% 
  mutate(intensity = if_else(intensity %in% c('Ablative','ABLATIVE'), 'ablative',
                                         if_else(intensity %in% c('NONABL','Nonablative'), 'nonablative','reduced'))) %>% 
  mutate(disease.simple = if_else(is.na(disease.simple), 'AML', disease.simple))
```




```{r}
new1 <- tibble(
  mrn = 38084143,
  source = 'TCD',
  intensity = 'ablative',
  hct = ymd('2020, January 17'),
  age = 61.1,
  sex = 'M',
  disease.simple = 'AML'
)

ptb <- bind_rows(other, new1) %>% 
  full_join(wt %>% select(mrn, admit_wt))
```

```{r}
# the break down of the disease type
ptb %>% 
  count(disease.simple) %>% 
  mutate(disea_perc = round(n/97*100,1)) %>% 
  arrange(-disea_perc)


ptb %>% 
  count(source) %>% 
  mutate(source_perc = round(n/97*100,1)) %>% 
  arrange(-source_perc)
```


```{r}
# output this table this is the patient meta table
ptb %>% 
  write_csv('../data/cleaned_patients/diet_patients_97.csv')
```
