---
title: "Tree building"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
library(tidyverse)
library(data.tree)
library(viridisLite)
library(readxl)
```

# the food database

```{r}
### The food database with all the unique food from the diet project
# need to get rid of the all the special characters, so that you will only see underscores
# all!!!! including the semicolon damn the semi colon


# uniq_food is a table with the food_nsc and food code and description
dtb1 <-  read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv') %>% 
  mutate(Food_code = as.character(Food_code))
dtb2 <- read_rds('../data/136_updated_dtb2.rds')

dtball <- read_csv('../data/152_combined_DTB.csv')

uniq_food <- dtball %>% 
  distinct(Food_code, description)  


#codes <- read_tsv('../data/finalized/paired/pNday/prophylactic_p5d_diet_foodID_dehydrated_weight_per_pt.tsv') %>% 
  #pull(Food_code)

length(intersect(uniq_food$Food.Code, current_all))

food_database <- uniq_food %>% 
  distinct(Food_code, .keep_all = T)  %>%  
  rename(FoodID = Food_code) %>% 
  mutate(description = str_replace_all(description,',| |-|\\(|\\)|%|/|"|;','_')) %>% 
  mutate(description = str_replace_all(description,"'",""))  
```


# the nodes

```{r}
nodes_fn <- '../data/source/NodeLabelsMCT.txt'

num.levels <- 7
```

# the df transformation

```{r}
fdata <- food_database
nodes <- read.table(nodes_fn, header = TRUE, sep="\t", fill = TRUE , colClasses="character")

main <- fdata[,c("FoodID", "description")]


# if there happen to be duplicate FoodIDs in main, remove them
main <- main[!duplicated(main$FoodID),]

flevels <- NULL
for(i in 1:num.levels)
    flevels <- cbind(flevels, I(substr(main$FoodID, 1, i)))
colnames(flevels) <- paste0("L",1:num.levels)
main <- data.frame(main, flevels, stringsAsFactors=F)


# melt the data, merge to get the node names, then cast back
main.melt <- reshape2::melt(main, id.vars = "FoodID", variable.name = "Level", value.name = "Level.code")
main.merge <- merge(main.melt, nodes, by = "Level.code")
main.cast <- data.table::dcast(main.merge, FoodID ~ Level, value.var = "Main.food.description")

# prepend level to all level descriptions
main.cast[is.na(main.cast)] <- ""
main.cast[,colnames(main.cast)[-1]] <- sapply(colnames(main.cast)[-1], function(colname) paste(colname, main.cast[,colname], sep="_"))

# merge back with original table to grab Food Description
main.join <- merge(main.cast, main[,c("FoodID","description")], by="FoodID")

# create a proper newick string for the tree
newickstring <- paste("foodtreeroot", apply(main.join, 1, function(xx) paste(xx[-1], collapse="/")), sep="/")
# create a proper taxonomy string for QIIME
taxonomy <- apply(main.join, 1, function(xx) paste(xx[-1], collapse=";"))

final.table <- data.frame(main.join, newickstring, taxonomy, stringsAsFactors=F) %>% 
  # THE BELOW IS ESSENTIAL, THAT WE WANNA USE FOOD ID INSTEAD OF DESCRIPTION TO REPRESENT THE FOOD
  mutate(newickstring = str_glue('foodtreeroot/{L1}/{L2}/{L3}/{L4}/{L5}/{L6}/{FoodID}'))
```

```{r}
final.table %>% 
  write_csv('../data/source/final_table_for_writing_out_to_newick.csv')
```


# make the tree in newick

```{r}
#### Make and export the tree ####
# the below is the tree that is gonna be used in the procrustes since the food is represented by food_code
foodTree <- as.Node(final.table, pathName = "newickstring")
tree <- ToNewick(foodTree)
cat(tree, file = '../data/cleaned_tree/output_food_tree_datatree.newick')
```


```{r}
# make another tree with leave nodes as the name description so it is not some numbers
# final.table <- read_csv('../data/source/final_table_for_writing_out_to_newick.csv')
# 
# final_table_name <- final.table%>% 
#   mutate(newickstring_name = str_glue('foodtreeroot/{L1}/{L2}/{L3}/{L4}/{L5}/{L6}/{description}'))
# 
# #### Make and export the tree ####
# foodTree <- as.Node(final_table_name, pathName = "newickstring_name")
# tree <- ToNewick(foodTree)
# cat(tree, file = '../data/cleaned_tree/output_food_tree_datatree_name.newick')
```


# plot the tree in graphlan

```{bash}
# in terminal
# in the source dir
graphlan/graphlan_annotate.py --annot annotation.base.txt output_food_tree_datatree.newick  guide_1.xml
graphlan/graphlan.py guide_1.xml food_tree.pdf --dpi 300 --size 3.5
```

```{r}
library(networkD3)
useRtreeList <- ToListExplicit(foodTree, unname = TRUE)
radialNetwork( useRtreeList)
```

# output the foodID taxanomy into a table that could be used in taxUMAP

```{r}
actual_foodids <- read_csv('../data/cleaned_diet_data/FINAL_97_food_code_counts_matrix.csv') %>% 
  pull(Food_code)

food_taxa <- final.table %>% 
  filter(FoodID %in% actual_foodids) %>% 
  select(L1, L2, L3, L4, FoodID)

food_taxa %>% 
  write_csv('../data/cleaned_diet_data/taxUMAP_foodID_taxa.csv')
```


