---
title: "Compute per day diet alpha diversity for every patient using qiime"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) 
```

Convert the date of the hct to fdrt. 

```{r}
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods.csv') 
ptb <- read_csv('../data/cleaned_patients/diet_patients_97.csv')  
```

# convert the hct to fdrt

```{r}
dtb1 <- dtb %>% 
  left_join(ptb %>% select(mrn, hct), by = "mrn") %>% 
  mutate(fdrt = Date - hct) %>% 
  select(-hct, -Date)   

dtb1 %>% 
  write_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt.csv')
```

# create the fid consists of mrn and fdrt, and then format the table needed to compute the food alpha diversity

```{r}
# use the dtb with EN data also 
# updated 2021-7-29 since in 2020-10 the dtb changed 
DTB <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')


fcts <-  DTB %>% 
  mutate(fid = str_glue('P{mrn}d{fdrt}')) %>% 
  select(fid, Food_code, dehydrated_weight) %>% 
  group_by(fid, Food_code) %>% 
  summarise(daily_de_wt = sum(dehydrated_weight)) %>% 
  spread(key = 'fid', value = 'daily_de_wt', fill = 0) 

fcts %>% 
  write_tsv('../data/cleaned_diet_data/FINAL_97_food_code_counts_matrix.tsv')
```

```{bash} 
biom convert -i ../data/cleaned_diet_data/FINAL_97_food_code_counts_matrix.tsv -o ../data/cleaned_diet_data/FINAL_97_food_code_counts_matrix.biom --to-hdf5 --table-type="Table"

qiime tools import \
  --input-path ../data/cleaned_diet_data/FINAL_97_food_code_counts_matrix.biom \
  --output-path ../data/cleaned_diet_data/FINAL_97_food_code_counts_matrix.qza \
  --type 'FeatureTable[Frequency]' 

qiime tools import \
  --input-path ../data/cleaned_tree/output_food_tree_datatree.newick \
  --output-path ../data/cleaned_tree/output_food_tree_datatree.qza \
  --type 'Phylogeny[Rooted]'

qiime diversity alpha-phylogenetic \
  --i-table ../data/cleaned_diet_data/FINAL_97_food_code_counts_matrix.qza  \
  --i-phylogeny ../data/cleaned_tree/output_food_tree_datatree.qza \
  --p-metric faith_pd \
  --o-alpha-diversity ../data/cleaned_diet_data/FINAL_97_faith_pd.qza


# export to tsv format
qiime tools export --input-path ../data/cleaned_diet_data/FINAL_97_faith_pd.qza --output-path ../data/cleaned_diet_data/FINAL_97_faith_pd
```
