---
title: "Calculate unifrac beta diversity"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE}
library(tidyverse)
library(vegan)
library(ape) 
library(ggpubr)
library(viridis)
library(RColorBrewer)
```

# Beta diversity calculations

The counts table can't have a column that is completely all zeros. 

```{r}
fcts <- read_tsv('../data/cleaned_diet_data/FINAL_97_food_code_counts_matrix.tsv') %>% 
  summarise_all(funs(sum)) %>% 
  gather('id', 'value', names(.)[2]:names(.)[ncol(.)]) %>% 
  arrange(value) 
```

good no zero columns so that I can directly use that table and the following is in snakefile with qiime


# visualize in ggplot 

```{r}
#Check the beta distance matrix
beta_un_uni <- read.delim('../data/cleaned_diet_data/FINAL_97_unweighted_unifrac_distance_matrix/distance-matrix.tsv', sep = '\t', row.names = 1)  
food_dist <- as.dist(beta_un_uni)

# the percent variance
eigen <- pcoa(food_dist)$values$Eigenvalues

percent_var <- signif(eigen/sum(eigen), 3)*100


# join the axis with the meta information
meta <-  read_csv('../data/cleaned_diet_data/wide_food_grp-and_nutrients_total.csv')

#pcoa
pcoa_f <- as.data.frame(pcoa(food_dist)$vectors) %>% 
  select(Axis.1, Axis.2, Axis.3) %>% 
  rownames_to_column('fid') %>% 
  separate(fid, into = c('mrn','fdrt'), sep = 'd', convert = T) %>% 
  mutate(mrn = as.numeric(str_replace(mrn, '^P',''))) %>% 
  inner_join(meta)

colnames(pcoa_f)
```

## food group

```{r} 
food_groups_sub <- pcoa_f %>% 
  select(mrn, fdrt, Axis.1, Axis.2, Axis.3, starts_with('fg'))

food_groups_sub_total <- food_groups_sub %>% 
  gather('food_group_total', 'dedywt', names(.)[6]:names(.)[ncol(.)]) 

# food groups total log transform the dewt
pseudo_cnt <- food_groups_sub_total %>% 
  filter(dedywt > 0) %>% 
  arrange(dedywt) %>% 
  slice(1) %>% 
  mutate(pseudo = dedywt*0.1) %>% 
  pull(pseudo)

food_groups_sub_total_log <- food_groups_sub_total %>% 
  mutate(dedywt = dedywt + pseudo_cnt) %>% 
  mutate(log_dewt = log10(dedywt))

```


```{r}
food_groups_sub_total_log %>% 
  ggplot(aes(x = Axis.1, y = Axis.2, col = log_dewt)) +
  geom_point(alpha=0.5, size = 2.5) +
  xlab(paste0("PC 1 [",percent_var[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var[2],"%]")) +
  theme_classic() +
  theme(legend.position = 'top') +
  labs(title = 'PCoA of unweighted unifrac distance diet data PC1 VS PC2') + 
  #scale_colour_manual(values = rev(brewer.pal(10,"RdYlBu"))) +
  scale_color_viridis() +
  facet_wrap(~food_group_total) +
  ggsave('../figs/pcoa_food_group_total_log_12.jpg', height = 10, width = 15)

 
food_groups_sub_total_log %>% 
  ggplot(aes(x = Axis.2, y = Axis.3, col = log_dewt)) +
  geom_point(alpha=0.5, size = 2.5) +
  xlab(paste0("PC 2 [",percent_var[2],"%]")) +
  ylab(paste0("PC 3 [",percent_var[3],"%]")) +
  theme_classic() +
  theme(legend.position = 'top') +
  labs(title = 'PCoA of unweighted unifrac distance diet data PC2 VS PC3') + 
  #scale_colour_manual(values = rev(brewer.pal(10,"RdYlBu"))) +
  scale_color_viridis() +
  facet_wrap(~food_group_total) +
  ggsave('../figs/pcoa_food_group_total_log_23.jpg', height = 10, width = 15)
```

## nutrient

```{r}
nutrients_sub_total <- pcoa_f %>% 
  select(mrn, fdrt, Axis.1, Axis.2, Axis.3, starts_with('Nut')) %>%   
  gather('nutrients_total', 'dedywt', names(.)[6]:names(.)[ncol(.)]) 


pseudo_cnt <- nutrients_sub_total %>% 
  filter(dedywt > 0) %>% 
  arrange(dedywt) %>% 
  slice(1) %>% 
  mutate(pseudo = dedywt*0.1) %>% 
  pull(pseudo)

nutrients_sub_total_log <- nutrients_sub_total %>% 
  mutate(dedywt = dedywt + pseudo_cnt) %>% 
  mutate(log_dewt = log10(dedywt))
```

```{r}
nutrients_sub_total_log %>% 
  ggplot(aes(x = Axis.1, y = Axis.2, col = log_dewt)) +
  geom_point(alpha=0.5, size = 2.5) +
  xlab(paste0("PC 1 [",percent_var[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var[2],"%]")) +
  theme_classic() +
  theme(legend.position = 'top') +
  labs(title = 'PCoA of unweighted unifrac distance diet data PC1 VS PC2') + 
  #scale_colour_manual(values = rev(brewer.pal(10,"RdYlBu"))) +
  scale_color_viridis() +
  facet_wrap(~nutrients_total) +
  ggsave('../figs/nutrients_total_log_12.jpg', height = 10, width = 15)

 
nutrients_sub_total_log %>% 
  ggplot(aes(x = Axis.2, y = Axis.3, col = log_dewt)) +
  geom_point(alpha=0.5, size = 2.5) +
  xlab(paste0("PC 2 [",percent_var[2],"%]")) +
  ylab(paste0("PC 3 [",percent_var[3],"%]")) +
  theme_classic() +
  theme(legend.position = 'top') +
  labs(title = 'PCoA of unweighted unifrac distance diet data PC2 VS PC3') + 
  #scale_colour_manual(values = rev(brewer.pal(10,"RdYlBu"))) +
  scale_color_viridis() +
  facet_wrap(~nutrients_total) +
  ggsave('../figs/nutrients_total_log_23.jpg', height = 10, width = 15)
```


