---
title: "Cleaning the new list (all table)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(lubridate)
library(ggpubr)
```

Cleaning the new list, which is a table with all patients eaten food of all time
with food_NSC included that could be used to join with unique that could link to FNDDS food code


```{r}
# uni is the table with unique food_nsc translated to fndds code
uni <- read_excel('../data/source/eaten_FNDDS.xlsx', sheet = 1)

uni_rm <- read_excel('../data/source/eaten_FNDDS.xlsx', sheet = 2, col_names = F)

uniq_food <- uni %>% 
  distinct(item1_value_raw_raw,  .keep_all = T)

# The all table with all the records
all <- read_excel('../data/source/new_list.xls') %>% 
  # remove some entries that like a section header instead of real food
  filter(!Food_NSC %in% uni_rm$...1) %>% 
  # remove the records that have 0 in Por_eaten since that means ordered but not eaten
  mutate(Por_eaten = as.numeric(Por_eaten)) %>% 
  filter(Por_eaten != 0) %>% 
  # remove the 4 columns since we don't care SFA_g, Cholesterol_mg, MUFA_g, PUFA_g c
  select(-SFA_g, -Cholesterol_mg, -MUFA_g, -PUFA_g) 

# the corrected table (with many essencial columns NA) from Peter
corr <- read_csv('../data/source/NA_in_all_table_removed.csv')

# update the all table with corrected table from Peter
All <- bind_rows(
  corr %>% 
    mutate(Date = dmy(Date)),
  all %>% 
    filter(!...1 %in% corr$...1) %>% 
  # remove the + sign after numbers in some columns
    mutate(Calories_kcal = str_replace_all(Calories_kcal, '\\+$',''),
           Proteing_g = str_replace_all(Proteing_g, '\\+$',''),
           Fat_g = str_replace_all(Fat_g, '\\+$',''),
           Carbohydrates_g = str_replace_all(Carbohydrates_g, '\\+$',''),
           Fibers_g = str_replace_all(Fibers_g, '\\+$',''),
           Sugars_g = str_replace_all(Sugars_g, '\\+$',''),
           Sodium_mg = str_replace_all(Sodium_mg, '\\+$','')) %>% 
    mutate(Calories_kcal = as.numeric(Calories_kcal),
           Proteing_g = as.numeric(Proteing_g),
           Fat_g = as.numeric(Fat_g),
           Carbohydrates_g = as.numeric(Carbohydrates_g),
           Fibers_g = as.numeric(Fibers_g),
           Sugars_g = as.numeric(Sugars_g),
           Sodium_mg = as.numeric(Sodium_mg)) %>% 
    mutate(Date = mdy(Date))
) %>% 
  rename(key = ...1)  %>% 
  select(-Name) %>% 
  separate(Meal, into = c('Meal','Menu'), sep = '  \\(Menu: ')
```

```{r}
# suspicious records with calories
check <- All %>% 
  filter(Calories_kcal < 10 | Calories_kcal > 590) %>% 
  distinct(Food_NSC, .keep_all = T)

check %>% 
  write_csv('../data/source/All_data_check_calories.csv')
```


```{r}
# merging with the table Peter corrected the unique record to check
not_check <- All %>% 
  filter(Calories_kcal >= 10 & Calories_kcal <= 590) %>% 
  distinct(Food_NSC, .keep_all = T)

not_check %>% 
  write_csv('../data/source/All_data_to_be_checked.csv')

```


```{r}
# regain the Calories_kcal < 10 | Calories_kcal > 590 table expanding the unique items
cal_corre <- read_csv('../data/source/All_data_check_calories_peter.csv') %>% 
  select(Food_NSC:Sodium_mg)

# the remaining that checked by peter
remain_corre <- read_csv('../data/source/All_data_to_be_checked_peter.csv') %>% 
  select(Food_NSC:Sodium_mg)

corre_all <- bind_rows(
  cal_corre,
  remain_corre
) %>% 
  distinct(Food_NSC, .keep_all = T)

# the All table but without the nutrient values
corre_All <- All %>% 
  select(key:Food_NSC) %>% 
  left_join(corre_all, by  = 'Food_NSC')


# output the above corrected finalized all table
corre_All %>% 
  write_csv('../data/finalized/all_patients_record.csv')
```

```{r}
uniq_food
```

```{r}
# the fndds table
fndds <- read_excel('../data/source/2015-2016 FNDDS At A Glance - FNDDS Nutrient Values.xlsx', skip = 1) %>% 
  rename_all(funs(str_replace_all(., ' ','_'))) %>% 
  rename_all(funs(str_replace_all(., '\\(|\\)|,',''))) %>% 
  select(Food_code, 
         Energy_kcal, 
         Protein_g, 
         Total_Fat_g,
         Carbohydrate_g,
         Fiber_total_dietary_g,
         Sugars_total_g,
         Sodium_mg)


# clean the unique food list
# specifically combine the fndds nutrient value if there are several food codes to one food_nsc
uniq_food <- uniq_food %>% 
  select(-item1_index) %>% 
  rename(Food_NSC = item1_value_raw_raw)

u1 <- uniq_food %>% 
  #filter(is.na(...7)) %>% 
  select(Food_NSC:WWEIA.Category.Description)

u2 <- uniq_food %>% 
  filter(!is.na(...7)) %>% 
  select(Food_NSC, ...7:...10) %>% 
  rename(Food.Code = ...7,
         FNDDS.Main.Food.Description = ...8,
         WWEIA.Category.Code = ...9,
         WWEIA.Category.Description = ...10)

u3 <- uniq_food %>% 
  filter(!is.na(...11)) %>% 
  select(Food_NSC, ...11:...14) %>% 
  rename(Food.Code = ...11,
         FNDDS.Main.Food.Description = ...12,
         WWEIA.Category.Code = ...13,
         WWEIA.Category.Description = ...14)

uniq_fndds <- bind_rows(
  u1, u2, u3
)   %>% 
  rename(Food_code = Food.Code) %>% 
  left_join(fndds , by = 'Food_code') %>% 
  group_by(Food_NSC) %>% 
  summarise(energy = sum(Energy_kcal),
            protein = sum(Protein_g),
            fat = sum(Total_Fat_g),
            carbohydrate = sum(Carbohydrate_g),
            fiber = sum(Fiber_total_dietary_g),
            sugar = sum(Sugars_total_g),
            sodium = sum(Sodium_mg))

uniq_fndds %>% 
  write_csv('../data/finalized/uniq_Food_NSC_fndds_nutrient_value.csv')
```


```{r}
# join with the unique food with food code 
not_check_uniqe_food_code <- not_check %>% 
  inner_join(uniq_food %>% 
               select(Food_NSC = item1_value_raw_raw,
                      Food.Code,
                      FNDDS.Main.Food.Description), by = 'Food_NSC') %>% 
  distinct(Food.Code, .keep_all = T)

not_check_uniqe_food_code %>% 
  write_csv('../data/not_check_uniqe_food_code.csv')
```
