---
title: "Selecting stool samples and the no empirical abx affected qualified stool samples"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) 
```

```{r}
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_enteralTPN.csv')
ptb <- read_csv('../data/cleaned_patients/diet_patients_97.csv')

source('~/db_connect_simple.R')
connect_database(config_file = "~/dbConfig.txt")
get_table_from_database('samples_castori_ag')
get_table_from_database_predefined_filter('asv_alpha_diversity_ag')
```

# selecting stool samples for the patients and also close to diet data

```{r}
# selecting all stool samples of the patients
stb <- ptb %>% 
  left_join(samples_castori_ag %>% 
              filter(sampletype == 'Stool' | sampletype == 'stool') %>% 
              select(mrn, sampleid, datecollection), by = 'mrn') %>% 
  mutate(sdrt = datecollection - hct)
```

```{r}
# remove all the stool samples collected >= 2 days after the latest diet sample for every patient
# get the latest diet sample for every patient
dtb_latest_dsample <- dtb %>% 
  arrange(mrn, desc(fdrt)) %>% 
  distinct(mrn, .keep_all = T) %>% 
  select(mrn, fdrt)  

# join the lastest dsample day to the stb 
stb_dsample_diff_tobe_removed <- stb %>% 
  left_join(dtb_latest_dsample, by = 'mrn')  %>% 
  mutate(diff = sdrt - fdrt) %>% 
  filter(diff >= 2) %>% 
  pull(sampleid)

stb1 <- stb %>% 
  filter(!sampleid %in% stb_dsample_diff_tobe_removed)

# also remove the stool samples that are earlier than the earliest diet sample for each patient
earliest_dsample <- dtb %>% 
  arrange(mrn, fdrt) %>% 
  distinct(mrn, .keep_all = T) %>% 
  select(mrn, fdrt)

early_2b_rm <- stb1 %>% 
  left_join(earliest_dsample, by = 'mrn')  %>% 
  mutate(diff = sdrt - fdrt) %>% 
  filter(diff <= 0) %>% 
  pull(sampleid)

stb2 <- stb1 %>% 
  filter(!sampleid %in% early_2b_rm) %>% 
  select(-hct, -datecollection)
 
```

```{r}
# now find the samples that have actually been sequenced that we have entry in the alpha div table
# and also have a satisfying total count
stb3 <- stb2 %>% 
  filter(sampleid %in% asv_alpha_diversity_ag$sampleid) %>%
  left_join(asv_alpha_diversity_ag %>% select(sampleid, count_total)) %>% 
  filter(count_total >= 400)

# there are patients that have more than 1 stool sample on the same day
stb3 %>% 
  distinct(mrn, sdrt)

# the sampleids are all different
stb3 %>% 
  distinct(sampleid)
```

# which stool samples affected by the empirical abx

```{r}
censor_abx <- c('active_atb_vanco_po',	'active_atb_imipenem',	'active_atb_meropenem',	'active_atb_ertapenem',		'active_atb_cefepime',		'active_atb_linezolid',	'active_atb_metro',	'active_atb_piptazo')

abx_all <- read_csv('../data/cleaned_stool/abx_all_samples_with_censoring_info.csv')
  
abx_this_censor_samples <- abx_all %>% 
  filter(sampleid %in% stb3$sampleid) %>% 
  select(sampleid, active_atb_cipro:active_atb_other) %>% 
  gather(key = 'abx_type', value = 'value', names(.)[2]:names(.)[ncol(.)]) %>% 
  filter(abx_type %in% censor_abx) %>% 
  filter(value == T) %>% 
  distinct(sampleid) %>% 
  pull(sampleid)
 
stb4 <- stb3 %>% 
  filter(!sampleid %in% abx_this_censor_samples) %>% 
  arrange(mrn, sdrt)

stb4 %>% 
  distinct(mrn, sdrt)# 9 are duplicated on the same day
```

# what about the same day there are two stool samples

```{r}
# remove the duplicated samples on the same day for now
stb5 <- stb4 %>% 
  arrange(mrn, sdrt, desc(count_total)) %>% 
  distinct(mrn, sdrt, .keep_all = T)
```

# has to have at least one real diet data in the previous three days (for the later pairing)

```{r}
# list the previous three days drt for every stool sample 
qual_stool_df <- stb5 %>% 
  mutate(p1d = sdrt-1,
         p2d = sdrt-2, 
         p3d = sdrt-3) %>% 
  select(mrn, p1d, p2d, p3d)

# use the no fake diet counts table and get the stool samples that should be removed -- not even one day
dtb_real <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt.csv')

no_real_diet_d_to_be_rm_stool_s <- function(mrn_, p1d_, p2d_, p3d_){
  df = dtb_real %>% 
    filter(mrn == mrn_) %>% 
    filter(fdrt == p1d_ | fdrt == p2d_ |fdrt == p3d_ ) %>% 
    nrow()
  return(df)
}

qual_stool2 <- pmap(qual_stool_df, function(mrn, p1d, p2d, p3d){
    no_real_diet_d_to_be_rm_stool_s(mrn, p1d, p2d, p3d)
  }) %>% 
  set_names(paste0("row", 1:nrow(qual_stool_df))) %>% 
  bind_rows() %>% 
  gather(key = 'id', value = 'num_d_records') %>% 
  arrange(num_d_records) %>% 
  full_join(stb5 %>% 
              mutate(id = paste0("row", 1:nrow(.))), by  = 'id')
  
stb6 <- qual_stool2 %>% 
  filter(num_d_records > 0)  %>%   
  select(-id, -num_d_records)
```
 
# visualize on the diet and stool pairing

```{r}
# the diet data
library(ggpubr)
stb6_plot <- stb6 %>% 
  mutate(y = 0.8)

dtb %>% 
  select(mrn, fdrt) %>% 
  mutate(y = 1) %>% 
  ggscatter(x = 'fdrt', y = 'y', color = 'forestgreen') +
  geom_point(data = stb6_plot, aes(x = sdrt, y  = y)) +
  facet_wrap(~mrn) +
  theme_bw() +
  ylim(0.7, 1.1) +
  theme(strip.text.x = element_blank()) +#hide the mrns
  ggsave('../figs/97_all_pair.pdf', width = 30, height = 12)
```

```{r}
# one thing I need to check does corrado's abx table cover all of my samples
yes <- abx_all %>% 
  filter(sampleid %in% stb3$sampleid)

ptb <- read_csv('../data/cleaned_patients/diet_patients_97.csv')

no <- stb3 %>% 
  filter(sampleid %in% setdiff(stb3$sampleid, yes$sampleid)) %>% 
  left_join(ptb ) %>%  
  distinct(mrn, hct) %>% 
  arrange(hct)

antibiotics %>% 
  filter(patient_id %in% no$mrn)

# pretty recent transplant 
```

