---
title: "Redundancy analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The distance based RDA

```{r}
library(vegan)
library(tidyverse)
library(rbiom)
```

# run RDA

```{r}
pheno1 <- pheno %>%  
  select(starts_with('fg'), intensity, sdrt) 


rda_fg <- rda(cts ~ ., pheno1)  
# VIFs
vif.cca(rda_fg)

rda_fg
```

```{r}
plot(rda_fg, display=c("species", "bp"), type="n", ylab="RDA2", main="Species", scaling="species")
text(rda_fg, display="species", col="black", scaling="species", cex = 0.5 )
text(rda_fg, display="bp", col="red", cex = 0.4)
```

## using the bray curtis distance first 

```{r}
# the meta data 
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d.csv') %>% 
    mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
    mutate(abx = factor(abx, levels = c('non_empirical','empirical')),
           mrn = factor(mrn))
 
pheno <- meta %>%  
  select(starts_with('fg'), intensity, sdrt, abx, mrn) 


pheno1 <- meta %>%  
  select(starts_with('fg'), intensity, sdrt, abx) 

pheno_fg <- meta %>%  
  select(starts_with('fg')) 


# using the genus level counts
cts <- read_csv('../data/cleaned_stool/ALL_stool_samples_genus_counts.csv')  %>% 
  filter(sampleid %in% meta$sampleid) %>% 
  select(sampleid, taxa_genus, relab) %>% 
  spread(key = 'taxa_genus', value = 'relab') %>% 
  column_to_rownames('sampleid')

res <- capscale(formula = cts ~ .,
                data = pheno,
                distance = 'bray',
                dfun = vegdist,
                #add = T,
                sqrt.dist = T)

plot(res)
anova(res)

res_pheno1 <- capscale(formula = cts ~ .,
                data = pheno1,
                distance = 'bray',
                dfun = vegdist,
                #add = T,
                sqrt.dist = T)
```

```{r}
# calculate the bray dissimilarity matrix
dist_ <- vegdist(cts, method = 'bray')

res_ <- capscale(formula = dist_ ~ .,
                data = pheno,
                sqrt.dist = T)

# it's the same as above: I don't need to calculate the distance myself  
```


# use the normalized count in the deseq way

```{r}
library(DESeq2)
library(vsn)
library(hexbin)
dds <- read_rds('../data/cleaned_pair/deseq_obj_spp.RDS')
vsd <- varianceStabilizingTransformation(dds, blind=T, fitType='local' ) 
vsd_cts <- assay(vsd)
meanSdPlot(vsd_cts)
```


```{r}
meanSdPlot(assay(dds))# check the sd scales so the vst really shrinks the 
```

```{r}
# res_vst_cts <- capscale(formula = t(vsd_cts) ~ .,
#                 data = pheno,
#                 distance = 'bray',
#                 dfun = vegdist, 
#                 #add = T,
#                 sqrt.dist = T)
# error : results may be meaningless because data have negative entries in method “bray”
# this is not making a lot of sense --- transform the data then calculate distance like bray
```

```{r}
# just use the transformed counts and then do a rda
rda_vsd_cts <- rda(t(vsd_cts) ~ ., pheno) 

rda_vsd_cts_ <- rda(t(vsd_cts) ~ ., pheno1) 

rda_vsd_cts_fg <- rda(t(vsd_cts) ~ ., pheno_fg)  
```

## use the weighted unifrac

```{r}
# the matrix that have asv key as the row and samples as the columns and the raw count as the value
source('~/db_connect_simple.R')
connect_database(config_file = '~/dbConfig.txt')

asv_counts_ag <- read_csv('../data/asv_counts_ag_Feb17.csv')

cts <- asv_counts_ag %>% 
  filter(sampleid %in% meta$sampleid) %>% 
  select(asv_key, sampleid, count) %>% 
  spread(key = 'sampleid', value = 'count', fill = 0) %>% 
  arrange(asv_key)  %>% 
  column_to_rownames('asv_key') %>% 
  as.matrix()


# calculate the weighted unifrac distance
all_tree <- ape::read.tree('../data/cleaned_stool/asv_sequences_all.newick')
unifrac_res <- unifrac(cts, weighted = TRUE, tree = all_tree)

unifrac_res <- unifrac(cts, weighted = FALSE, tree = all_tree)
```

```{r}
res_wunifrac <- capscale(formula = unifrac_res ~ .,
                data = pheno,
                sqrt.dist = T)

res_wunifrac_pheno1 <- capscale(formula = unifrac_res ~ .,
                data = pheno1,
                sqrt.dist = T)

res_wunifrac_phenofg <- capscale(formula = unifrac_res ~ .,
                data = pheno_fg,
                sqrt.dist = T)

plot(res_wunifrac)  
```


