---
title: "prepare for the taxUMAP"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(viridis)
library(ggpubr)
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc') 
```

**Updated 2021-12-9 the new source files for the phylo-umap (after the enteral nutrition correction)** 

```{r}
# make the food code counts matrix
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
matri <- dtb %>% 
  select(mrn, fdrt, Food_code, dehydrated_weight) %>% 
  mutate(fid = str_glue('{mrn}d{fdrt}')) %>% 
  select(fid, Food_code, dehydrated_weight) %>%
  group_by(fid, Food_code) %>% 
  summarise(total = sum(dehydrated_weight)) %>% 
  spread('fid', 'total', fill = 0)

matri %>% 
  write_csv('../data/cleaned_diet_data/FINAL_97_food_code_counts_matrix.csv')

```


```{r}
# formatting the counts table to have samples in the rows
cts <- matri %>% 
  gather('fid', 'gram', names(.)[2]:names(.)[ncol(.)])

fid_sum <- cts %>% 
  group_by(fid) %>% 
  summarise(Sum = sum(gram))

cts_all <- cts %>% 
  left_join(fid_sum)  %>% 
  mutate(frelab = gram/Sum) %>% 
  select(Food_code, fid, frelab) %>% 
  spread(key = 'Food_code', value = 'frelab') %>% 
  rename(index_column = fid) %>% 
  mutate(index_column = str_glue('P{index_column}'))

# create pt number for the mrn
link <- cts_all %>% 
  select(index_column) %>% 
  transmute(mrn = str_extract(index_column, 'P.+d')) %>% 
  mutate(mrn = str_replace(mrn, 'P',''),
        mrn = str_replace(mrn, 'd$','') ) %>% 
  distinct() %>% 
  mutate(pt = seq(1, nrow(.))) %>% 
  mutate(pt = str_pad(pt, 2, side = 'left', '0')) %>% 
  mutate(pt = str_glue('P{pt}'))

link_all <- cts_all %>% 
  select(index_column) %>% 
  mutate(fid = index_column) %>% 
  separate(index_column, into = c('mrn','fdrt'), sep = 'd') %>% 
  mutate(mrn = str_replace(mrn, 'P','')) %>% 
  left_join(link) %>% 
  mutate(index_column = str_glue('{pt}d{fdrt}'))

link_all %>% 
  write_csv('../data/cleaned_diet_data/deidentify_dsample_map.csv')

```

**To do the umap I need the diet counts table and the food code taxa file.**

```{r}
cts_all %>% 
  rename(fid = index_column) %>% 
  full_join(link_all %>% select(fid, index_column)) %>% 
  select(index_column, names(.)[2]:names(.)[ncol(.)-1]) %>% 
  write_csv('../softwares/phylo-umap/taxumap/data/taxUMAP_food_cts.csv')




detable <- cts_all %>% 
  gather('foodcode', 'relab', names(.)[2]:names(.)[ncol(.)]) %>% 
  filter(str_detect(foodcode, '^9')) %>% 
  arrange(-relab) %>% 
  rename(fid = index_column) %>% 
  left_join(link_all %>% select(fid, index_column))
```
```{r}
# do a pcoa using the cts_all data
# you know the traditional pcoa, to highlight what is the advantage of the taxUMAP
food_cts <- cts_all %>% 
  column_to_rownames('index_column')

dist_ <- vegan::vegdist(food_cts, method = 'bray')
eigen <- ape::pcoa(dist_)$values$Eigenvalues
percent_var <- signif(eigen/sum(eigen), 3)*100
bc <- cmdscale(dist_, k = 2)


```


```{r}
# find out the most consumed food group for that patient on that day
sum_per_day <- dtb %>% 
  select(mrn, Food_code, fdrt, dehydrated_weight) %>% 
  mutate(fgrp1 = str_sub(as.character(Food_code),1,1 )) %>% 
  group_by(mrn, fdrt) %>% 
  summarise(daytotal = sum(dehydrated_weight))

dom_per_day <- dtb %>% 
  select(mrn, Food_code, fdrt, dehydrated_weight) %>% 
  mutate(fgrp1 = str_sub(as.character(Food_code),1,1 ))  %>% 
  group_by(mrn, fdrt, fgrp1) %>% 
  summarise(dayfgtotal = sum(dehydrated_weight)) %>% 
  left_join(sum_per_day) %>% 
  mutate(fg_frac = dayfgtotal/daytotal) %>% 
  ungroup() %>% 
  group_by(mrn, fdrt) %>% 
  arrange(desc(fg_frac), .by_group = T) %>% 
  slice(1)

dom_pcoa <- bc %>% 
  as.data.frame() %>%
  rownames_to_column('sampleid')  %>% 
  separate(sampleid, into = c('pt','fdrt'), sep = 'd', remove = F) %>% 
  mutate(mrn = as.numeric(str_replace(pt, '^P',''))) %>% 
  mutate(fdrt = as.numeric(fdrt)) %>% 
  full_join(dom_per_day) %>% 
  left_join(key)

color_key <- dom_pcoa %>% 
  ungroup() %>% 
  distinct(shortname, color) %>% 
  select(shortname, color) %>% 
  #mutate(shortname = factor(shortname)) %>% 
  #arrange(shortname) %>% 
  deframe()

dom_pcoa %>% 
  ggscatter(x = 'V1', y = 'V2', color =  'shortname',alpha = 1,size = 1 , shape = 16,) +
  labs(title = '') +
   scale_color_manual(values = color_key) +
  xlab(paste0("PC 1 [",percent_var[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var[2],"%]")) +
  theme(aspect.ratio=1, 
        legend.position= 'none')

ggsave('../figs/paper/016_pcoa_food_cts.jpg',
       width = 80,
       height = 100,
         #height = 60,  
         units = c("mm"),
         dpi = 400)
```


```{r}
# do the same dimensionality reduction and then visualization using umap
library(umap)
food_umap = umap(cts_all[,2:ncol(cts_all)])
all.equal(as.character(dom_pcoa$sampleid), as.character(cts_all$index_column))

food_umap$layout %>% 
  as.data.frame() %>% 
  mutate(sampleid = as.character(cts_all$index_column)) %>% 
  full_join(dom_pcoa %>% 
              select(sampleid, shortname), by = c( "sampleid"))  %>% 
   ggscatter(x = 'V1', y = 'V2', color =  'shortname',alpha = 1,size = 1 , shape = 16,) +
  labs(title = '') +
   scale_color_manual(values = color_key) +
  theme(aspect.ratio=1, 
        legend.position= 'none') +
  lemon::coord_capped_cart( left = 'both') 

ggsave('../figs/paper/016_umap_food_cts.jpg',
       width = 80,
       height = 100,
         #height = 60,  
         units = c("mm"),
         dpi = 400)

```


```{r}
# requested by Jonas (can you send me another file, with the same sample index, that has the total kcal in one column, and the total grams in another in it? )
requested <- dtb %>% 
  group_by(mrn, fdrt) %>% 
  summarise(total_kcal = sum(Calories_kcal),
            total_gram = sum(dehydrated_weight)) %>% 
  full_join(link_all %>% 
              mutate(mrn = as.numeric(mrn),
                     fdrt = as.numeric(fdrt))) %>% 
  ungroup( )%>% 
  select(index_column,total_kcal, total_gram )

requested %>% 
  write_csv('../data/index_with_cal_and_gram.csv')



```


```{r}
# next is the taxanomy table that should contain taxonomic levels. They should be ordered from left to right in decreasing taxonomic hierarchy 
# done in tree building script
```

```{r}
# format the food taxa table 
# go to script 004

ftaxa <- read_csv('../data/cleaned_diet_data/taxUMAP_foodID_taxa.csv') 

ftaxa %>% 
  write_csv('../data/cleaned_diet_data/taxUMAP_foodID_taxa.csv')
```

```{r}
# check if the 
cts_food_code <- cts %>% 
  distinct(Food_code) %>% 
  pull(Food_code)

length(intersect(ftaxa$ASV, cts_food_code))
```


# the umap results

```{r}
dtb <- read_csv('../data/cleaned_diet_data/wide_food_grp-and_nutrients_total.csv')

faith <- read_tsv('../data/cleaned_diet_data/FINAL_97_faith_pd/alpha-diversity.tsv') %>% 
  rename(index_column = ...1)

# average number of samples for patients (matter to the neigh param)
ave <- dtb %>% 
  count(mrn) %>% 
  summary(n)


```
```{bash}
//anaconda2/envs/test/bin/python3.8 run_taxumap.py -m taxumap/data/taxUMAP_food_cts.csv -t taxumap/data/taxUMAP_foodID_taxa.csv --agg_levels L1/L2 --weights 5/0.1 --neigh 24 --min_dist 0.00
```


```{r}
res <- read_csv('../softwares/phylo-umap/results/embedded.csv') %>% 
  full_join(faith) %>% 
  separate(index_column, into = c('mrn','fdrt'), sep = 'd', convert = T) %>% 
  mutate(mrn = as.numeric(str_replace(mrn, 'P',''))) %>% 
  inner_join(dtb) %>% 
  rename(u1 = names(.)[3],
        u2 = names(.)[4] ) %>% 
  gather('type','gram', names(.)[6]:names(.)[ncol(.)])  %>% 
  mutate(type = as.factor(type)) %>% 
  mutate(log_gram = log10(gram + 0.0001))


library(ggpubr)

res_plot <- res  %>% 
  filter(str_detect(type, '^fg')) %>% 
  ggplot(aes(x = u1, y  = u2, color = log_gram , alpha = 0.2)) +
  geom_point() +
  scale_color_viridis() +
  facet_wrap(~type) 

ggsave('../figs/umap_fg.pdf', width = 10, height = 7, plot = res_plot)
res_plot

```

```{r}
shake <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt.csv') %>% 
  filter(Food_code == 95103000) %>% 
  distinct(Food_NSC, Food_code, description)

shake %>% 
  write_csv('../data/cleaned_diet_data/shake_95103000.csv')
```


