---
title: "the mLDM"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mLDM)
library(tidyverse)
help(mLDM)
```

   X   N*P matrix  N samples, P otus  OTU table (N = 490, P = 117)
   M   N*Q matrix  N samples, P environmental factors (Q = 13)
       We encode 'site' (4 cities), 'Dx_bin' (5 diagnosis states) and 'Gender' (male and female) with 0-1 coding and get 4, 5, 2 features respectively.
   X_name  OTU numbers for 117 OTUs
   X_tax   OTU taxonomy for 117 OTUs
   
# use all of the stool samples, no abx filtering

```{r}
stb <- read_csv('../data/cleaned_stool/selected_stool_samples_ALL_abx.csv')

# get the raw counts of the filtered asv
source('~/db_connect_simple.R')
connect_database(config_file = '~/dbConfig.txt')
get_table_from_database_predefined_filter('asv_counts_ag')
get_table_from_database('asv_annotation_blast_ag')

cts <- asv_counts_ag %>% 
  filter(sampleid %in% stb$sampleid) %>% 
  select(asv_key, sampleid, count) %>% 
  spread(key = 'asv_key', value = 'count', fill = 0) %>% 
  arrange(sampleid)  
```
   
```{r}
# filter on this counts table
# how many singletons 
ctsm <- cts %>% 
   column_to_rownames('sampleid') %>% 
   as.matrix()

# keeping asv that appear in at least 10% of samples 

num_zero_thre <- floor(nrow(ctsm) * 0.1)

ctsm_fil <- ctsm[, colSums(ctsm != 0) >= num_zero_thre]
```

# meta up

## Categorize the abx group

```{r}
censor_abx <- c('active_atb_vanco_po',	'active_atb_imipenem',	'active_atb_meropenem',	'active_atb_ertapenem',		'active_atb_cefepime','active_atb_linezolid',	'active_atb_metro',	'active_atb_piptazo')

abx_all <- read_csv('../data/cleaned_stool/abx_all_samples_with_censoring_info.csv')

empirical_abx_samples <- abx_all %>% 
  filter(sampleid %in% stb$sampleid) %>% 
  select(sampleid, active_atb_cipro:active_atb_other) %>% 
  gather(key = 'abx_type', value = 'value', names(.)[2]:names(.)[ncol(.)]) %>% 
  filter(abx_type %in% censor_abx) %>% 
  filter(value == T) %>% 
  distinct(sampleid) %>% 
  pull(sampleid)

stb2 <- stb %>% 
   mutate(abx = if_else(sampleid %in% empirical_abx_samples, 'empirical', 'prophylactic'))

stb2 %>% 
   write_csv('../data/cleaned_stool/selected_stool_samples_type_abx.csv')
```

## get the ave p3d diet data

```{r}
ap3d <- read_csv('../data/cleaned_diet_data/paired_mean_p3d_diet_meta.csv')

meta <- ap3d %>% 
   full_join(stb2) %>% 
   select(-count_total) %>% 
   arrange(sampleid)  

# the columns in the meta table needs to be double so change it!! or code it~!!!

```

```{r}
Meta <- meta %>% 
   mutate(abx = if_else(abx == 'empirical', 1, 0),
          sex = if_else(sex == 'M', 1, 0),
          intensity = if_else(intensity == 'nonablative', 1, if_else(intensity == 'reduced', 2, 3)),
          source = if_else(source == 'unmodified', 1, if_else(source == 'cord', 2, 3))) %>% 
   mutate(mrn = as.numeric(as.factor(mrn))) %>% 
   select(Nut_Carbohydrates:abx) %>% 
   column_to_rownames('sampleid') %>% 
   as.matrix()
```

```{r}
ctsm_fil %>% 
   write.csv('../data/ctsm_fil.csv', row.names = T, quote = F)

Meta %>% 
   write.csv('../data/Meta.csv', row.names = T, quote = F)
```



```{r}
result <- mLDM(ctsm_fil, Meta, Z_mean = 1)
```


```{r}

# NOTE:

# The optimal result selected by model selection
resultOptimal <- result$optimal
# Theta is the precision matrix, the sign of Theta_ij is opposite with the association between OTU-i and OTU-j
Theta <- resultOptimal[[3]]
# B records the associations between EFs and OTUs
B <- resultOptimal[[1]]
# B0 records the baisc abundance of OTUs
B0 <- resultOptimal[[2]]
# Z record the latent variables of mLDM
Z <- resultOptimal[[4]]
# the best lambda1
lambda1 <- resultOptimal[[5]]
# the best lambda2
lambda2 <- resultOptimal[[6]]
EBIC <- resultOptimal[[7]]
# Associations among OTUs and OTUs
Associations_OTU_OTU <- resultOptimal[[9]]
# Associations between environmental factors and OTUs
Associations_EF_OTU <- resultOptimal[[8]]


```



