---
title: "lump all of the stool together and pair with p 2,3,4,5 day"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(vegan)
```

## the stool samples and species count matrix

```{r}
asv_counts_ag <- read_csv('../data/asv_counts_ag_Feb17.csv')
source('~/db_connect_simple.R')
connect_database(config_file = '~/dbConfig.txt')
ANNOT <- get_table_from_database('asv_annotation_blast_ag')
```

```{r}
# use prophylactic only stool samples
stb <- read_csv('../data/cleaned_stool/selected_stool_samples_type_abx.csv') %>% 
  filter(abx == 'prophylactic') 

# get the microbiome counts data of those stool samples
cts <- asv_counts_ag %>% 
    filter(sampleid %in% stb$sampleid) %>% 
    select(asv_key, sampleid, count) %>% 
    spread(key = 'sampleid', value = 'count', fill = 0) %>% 
    arrange(asv_key)  
  
annot <- ANNOT %>% 
    filter(asv_key %in% cts$asv_key) %>% 
    mutate(ordr =  if_else(ordr == '', str_glue('of_class_{class}'), ordr),
           family =  if_else(family == '', str_glue('of_order_{ordr}'), family),
           genus =  if_else(genus == '', str_glue('of_family_{family}'), genus),
           species =  if_else(species == '', str_glue('of_genus_{genus}'), species)) %>% 
    mutate(taxa_species = str_glue('k__{kingdom}|p__{phylum}|c__{class}|o__{ordr}|f__{family}|g__{genus}|s__{species}'))
  
  # replace the asv_key with the genus taxa level
  # summarize from asv level to genus level
  # get the relative abundance for the species
cts_relab <- cts %>% 
    full_join(annot %>%  select(asv_key, taxa_species), by  = 'asv_key') %>% 
    select(-asv_key) %>% 
    gather(key = 'sampleid', value = 'count', names(.)[1]:names(.)[ncol(.) - 1]) %>% 
    group_by(sampleid, taxa_species) %>% 
    summarise(cnt = sum(count)) %>% 
    # get the total count from the db to calculate the relab
    left_join(asv_counts_ag %>% distinct(sampleid,count_total ), by = 'sampleid') %>% 
    mutate(relab = cnt/count_total)

cts_relab %>% 
  write_csv('../data/cleaned_stool/prophylactic_only_stool_samples_species_counts.csv')
```


```{r}
cts_long <- cts_relab %>% 
  select(sampleid, taxa_species, relab) %>% 
  arrange(sampleid) 
```

## pairing stool with previous N days

### previous one day

```{r}
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_enteralTPN.csv')

stb_pNd <- stb %>% 
      mutate(fp1d = sdrt-1,
            fp2d = sdrt-2, 
            fp3d = sdrt-3,
            fp4d = sdrt-4,
            fp5d = sdrt-5) 


p1d <- apply(stb_pNd, 1, function(Row){
  df = dtb %>%  
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['fp1d']])) %>% 
        group_by(Food_code) %>% 
        summarise(ave_dewt = mean(dehydrated_weight))
}) %>% 
  set_names(stb_pNd %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'sampleid', value = 'ave_dewt', fill = 0)

# a subset sampleid are kept so use these samples for the species relab too
p1d_scts <- cts_long %>% 
  filter(sampleid %in% colnames(p1d)[2:ncol(p1d)]) %>% 
  spread('sampleid', 'relab', fill = 0)

```

### previous two day

```{r}
p2d <- apply(stb_pNd, 1, function(Row){
  df = dtb %>%  
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['fp1d']], Row[['fp2d']])) %>% 
        group_by(Food_code) %>% 
        summarise(ave_dewt = mean(dehydrated_weight))
}) %>% 
  set_names(stb_pNd %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'sampleid', value = 'ave_dewt', fill = 0)

# a subset sampleid are kept so use these samples for the species relab too
p2d_scts <- cts_long %>% 
  filter(sampleid %in% colnames(p2d)[2:ncol(p2d)]) %>% 
  spread('sampleid', 'relab', fill = 0)
```

### previous three day

```{r}
p3d <- apply(stb_pNd, 1, function(Row){
  df = dtb %>%  
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['fp1d']], Row[['fp2d']], Row[['fp3d']])) %>% 
        group_by(Food_code) %>% 
        summarise(ave_dewt = mean(dehydrated_weight))
}) %>% 
  set_names(stb_pNd %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'sampleid', value = 'ave_dewt', fill = 0)

# a subset sampleid are kept so use these samples for the species relab too
p3d_scts <- cts_long %>% 
  filter(sampleid %in% colnames(p3d)[2:ncol(p3d)]) %>% 
  spread('sampleid', 'relab', fill = 0)
```

### previous four day

```{r}
p4d <- apply(stb_pNd, 1, function(Row){
  df = dtb %>%  
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['fp1d']], Row[['fp2d']], Row[['fp3d']], Row[['fp4d']])) %>% 
        group_by(Food_code) %>% 
        summarise(ave_dewt = mean(dehydrated_weight))
}) %>% 
  set_names(stb_pNd %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'sampleid', value = 'ave_dewt', fill = 0)

# a subset sampleid are kept so use these samples for the species relab too
p4d_scts <- cts_long %>% 
  filter(sampleid %in% colnames(p4d)[2:ncol(p4d)]) %>% 
  spread('sampleid', 'relab', fill = 0)
```