---
title: "Make the input tables form"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

```{r}


two_list <- Venn(list(All = all$Food_NSC,
                 uni = uniq_food$item1_value_raw_raw))
 
ggvenn(two_list)
# yeah all are located
```

```{r}
# need to correct the all table, some of the NAs
all %>% 
  mutate(Por_eaten = as.numeric(Por_eaten)) %>% 
  filter(Por_eaten != 0) %>% 
  filter(is.na(Calories_kcal) | 
           is.na(Proteing_g) |
           is.na(Fat_g) |
           is.na(Carbohydrates_g) |
           is.na(Fibers_g) |
           is.na(Sugars_g) |
           is.na(Sodium_mg) ) %>% 
  arrange(Food_NSC ) %>% 
  select(-SFA_g, -Cholesterol_mg, -MUFA_g, -PUFA_g) %>% 
  write_csv('../data/source/NA_in_all_table.csv')

```

```{r}
# join the FNDDS code to the all table to produce this master list
master <- all %>% 
  left_join(uniq_food %>% 
              select(-item1_index) %>% 
              rename(Food_NSC = item1_value_raw_raw), by  = 'Food_NSC') %>% 
  rename(Food_code = Food.Code)

master %>% 
  filter(is.na(Food_code))   %>% 
  nrow
  
# FNDDS ref table with energy info
engy <- read_excel('../data/source/2015-2016 FNDDS At A Glance - FNDDS Nutrient Values.xlsx', skip = 1) %>% 
  rename_all(funs(str_replace_all(., ' ','_'))) %>% 
  rename_all(funs(str_replace_all(., '\\(|\\)',''))) %>% 
  select(Food_code, Energy_kcal, Water_g)

Master <- master %>% 
  left_join(engy, by  = 'Food_code') %>% 
  mutate(Calories_kcal = as.numeric(Calories_kcal))

colnames(final)
```

```{r}
final <- Master %>% 
  mutate(total_weight = Calories_kcal/Energy_kcal*100) %>% 
  mutate(dehydrated_weight = total_weight*Water_g/100) %>% 
  select(- ...1) %>% 
  rename(FoodID = Food_code,
         Main.food.description = Food_NSC) %>% 
  mutate(total_weight = if_else(is.nan(total_weight), 0, total_weight),
         dehydrated_weight = if_else(is.nan(dehydrated_weight), 0, dehydrated_weight))

final %>% 
  write_tsv('../data/source/final_master_list.tsv')
```

```{r}
FINAL <- final %>% 
  select(MRN, FoodID, dehydrated_weight) %>% 
  group_by(MRN, FoodID) %>% 
  summarise(total_de_wei = sum(dehydrated_weight)) %>% 
  spread(key = 'MRN', value = 'total_de_wei', fill = 0)
```

```{r}
# need to get rid of the all the special characters, so that you will only see underscores
# all!!!! including the semicolon damn the semi colon
food_database <- uniq_food %>% 
  select(-item1_index) %>% 
  rename(FoodID = Food.Code,
         Main.food.description = FNDDS.Main.Food.Description) %>% 
  select(item1_value_raw_raw: WWEIA.Category.Description) %>% 
  filter(!is.na(FoodID)) %>% 
  mutate(Main.food.description = str_replace_all(Main.food.description,',| |-|\\(|\\)|%|/|"|;','_')) %>% 
  mutate(Main.food.description = str_replace_all(Main.food.description,"'",""))




food_database %>% 
  write_tsv('../data/source/food_database_file.tsv')
  
```


```{r}


```

