---
title: "HOW MANY DAYS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(vegan)
library(tidyverse)
library(ggpubr)
```


TRYING TO figure out how many previous days to combine if just do a asymmetrical procrustes

# what if use all stool samples not only prophylactic ones

```{r}
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')

stb <- read_csv('../data/cleaned_stool/selected_stool_samples_type_abx.csv')
```
```{r}
pt_fdrt <- dtb %>% 
  distinct(mrn, fdrt)

stb_loop <- stb %>%  
  select(mrn, sdrt) %>% 
  transmute(mrn = mrn,
            p1d = sdrt-1,
            p2d = sdrt-2, 
            p3d = sdrt-3,
            p4d = sdrt-4,
            p5d = sdrt-5) 
 
check_p5d_diet <-  function(mrn_, p1d_, p2d_, p3d_, p4d_, p5d_){
  num = pt_fdrt %>% 
    filter(mrn == mrn_) %>% 
    filter(fdrt %in% c(p1d_, p2d_ ,p3d_, p4d_, p5d_ )) %>% 
    nrow()
  return(num)
}

check_p5d_diet_df <- pmap(stb_loop, function(mrn, p1d, p2d, p3d, p4d, p5d){
    check_p5d_diet(mrn, p1d, p2d, p3d, p4d, p5d)
  }) %>% 
  set_names(stb %>% pull(sampleid)) %>% 
  bind_rows() %>% 
  gather('sampleid', 'pNd_num') 

p5d_samples <- check_p5d_diet_df %>% 
  filter(pNd_num == 5) %>% 
  pull(sampleid)  
 
stb_loop_sum <- stb %>%  
  filter(sampleid %in% p5d_samples) %>% 
  mutate(p1d = sdrt-1,
            p2d = sdrt-2, 
            p3d = sdrt-3,
            p4d = sdrt-4,
            p5d = sdrt-5) 
```

```{r}
p1d <- apply(stb_loop_sum, 1, function(Row){
  df = dtb %>%   
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['p1d']])) %>% 
        group_by(Food_code) %>% 
        summarise(ave_dewt = sum(dehydrated_weight))
}) %>% 
  set_names(stb_loop_sum %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'sampleid', value = 'ave_dewt', fill = 0)

p1d <- p1d[, colSums(p1d != 0) > 0]
 
p2d <- apply(stb_loop_sum, 1, function(Row){
  df = dtb %>%  
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['p1d']], Row[['p2d']])) %>% 
        group_by(Food_code) %>% 
        summarise(ave_dewt = sum(dehydrated_weight)/2)
}) %>% 
  set_names(stb_loop_sum %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'sampleid', value = 'ave_dewt', fill = 0)

p2d <- p2d[, colSums(p2d != 0) > 0]

p3d <- apply(stb_loop_sum, 1, function(Row){
  df = dtb %>%  
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['p1d']], Row[['p2d']], Row[['p3d']])) %>% 
        group_by(Food_code) %>% 
        summarise(ave_dewt = sum(dehydrated_weight)/3)
}) %>% 
  set_names(stb_loop_sum %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'sampleid', value = 'ave_dewt', fill = 0)

p3d <- p3d[, colSums(p3d != 0) > 0]


p4d <- apply(stb_loop_sum, 1, function(Row){
  df = dtb %>%  
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['p1d']], Row[['p2d']], Row[['p3d']], Row[['p4d']])) %>% 
        group_by(Food_code) %>% 
        summarise(ave_dewt = sum(dehydrated_weight)/4)
}) %>% 
  set_names(stb_loop_sum %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'sampleid', value = 'ave_dewt', fill = 0) 

p4d <- p4d[, colSums(p4d != 0) > 0]

p5d <- apply(stb_loop_sum, 1, function(Row){
  df = dtb %>%  
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['p1d']], Row[['p2d']], Row[['p3d']], Row[['p4d']], Row[['p5d']])) %>% 
        group_by(Food_code) %>% 
        summarise(ave_dewt = sum(dehydrated_weight)/5)
}) %>% 
  set_names(stb_loop_sum %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'sampleid', value = 'ave_dewt', fill = 0)  

p5d <- p5d[, colSums(p5d != 0) > 0]
```


```{r}
library(vdbR)
connect_database(config_file = '~/dbConfig.txt')
get_table_from_database('asv_annotation_blast_ag')

cts <- get_counts_subset(stb$sampleid)


cts_genus <- cts %>% 
  inner_join(asv_annotation_blast_ag %>%  select(asv_key, genus), by  = 'asv_key') %>% 
  group_by(sampleid, genus) %>% 
  summarise(relab = sum(count_relative)) 

cts_spread <- cts_genus %>% 
  spread('genus', 'relab', fill = 0)

cts_genus %>% 
  write_csv('../data/cleaned_stool/022_ALL_stool_samples_genus_counts.csv')


```


```{r}
# the genus counts data would be :
cts_long <- read_csv('../data/cleaned_stool/022_ALL_stool_samples_genus_counts.csv') %>% 
  filter(sampleid %in% p5d_samples) 

# since the samples in the diet counts are different so need to subset according to each
p1d_scts <- cts_long %>% 
  filter(sampleid %in% colnames(p1d)[2:ncol(p1d)]) %>% 
  spread('sampleid', 'relab', fill = 0)

p2d_scts <- cts_long %>% 
  filter(sampleid %in% colnames(p2d)[2:ncol(p2d)]) %>% 
  spread('sampleid', 'relab', fill = 0)

p3d_scts <- cts_long %>% 
  filter(sampleid %in% colnames(p3d)[2:ncol(p3d)]) %>% 
  spread('sampleid', 'relab', fill = 0)

p4d_scts <- cts_long %>% 
  filter(sampleid %in% colnames(p4d)[2:ncol(p4d)]) %>% 
  spread('sampleid', 'relab', fill = 0)

p5d_scts <- cts_long %>% 
  filter(sampleid %in% colnames(p5d)[2:ncol(p5d)]) %>% 
  spread('sampleid', 'relab', fill = 0)
```


```{r}
# output the food id cts table (need to be in a similar format to fit my previously written snakemake rules)
dcts <- list(p1d = p1d,
             p2d = p2d,
             p3d = p3d,
             p4d = p4d,
             p5d = p5d)

for (i in 1:length(dcts)){
  dcts[[i]] %>% 
    write_tsv(str_glue('../data/finalized/paired/pNday/allstool_{names(dcts)[i]}_diet_foodID_dehydrated_weight_per_pt.tsv'))
}


scts <- list(
  p1d_scts = p1d_scts,
  p2d_scts = p2d_scts,
  p3d_scts = p3d_scts,
  p4d_scts = p4d_scts,
  p5d_scts = p5d_scts
)


for (i in 1:length(scts)){
  scts[[i]] %>% 
    write_tsv(str_glue('../data/finalized/paired/pNday/allstool_{names(scts)[i]}_stool_relab_species.tsv'))
}
```


After running in snakemake:

```{r}
# get the results from the snakemake pipeline that used the qiime2 methods 
# the protest is a test for significance , but I care more about the sum of squares not a p value 


fns_both <- tibble(
  sfolder = list.files('../data/finalized/paired/pNday/', pattern = 'allstool_p.d_scts_stool_relab_species_braycurtis_pcoa$', full.names = T),
  dfolder = list.files('../data/finalized/paired/pNday/', pattern = 'allstool_p.d_diet_foodID_dehydrated_weight_per_pt_unweighted_unifrac_pcoa$', full.names = T)
) %>% 
  mutate(ID = str_replace(sfolder, '_scts_stool_relab_species_braycurtis_pcoa', ''),
         ID = str_replace(ID, '../data/finalized/paired/pNday//allstool_','')) %>% 
  mutate(sfn = str_glue('{sfolder}/ordination.txt'),
         dfn = str_glue('{dfolder}/ordination.txt'))
```


```{r}
# # a function to do the procrustes as a pair
# protest_Nday <- map2(fns_both$dfn, fns_both$sfn, function(dfn, sfn){
#   dpcoa = read_tsv(dfn, skip = 9, col_names = F)  %>% 
#     filter(! X1 %in% c('Biplot','Site constraints')) %>% 
#     column_to_rownames('X1') %>% 
#     as.matrix()
#   
#   spcoa = read_tsv(sfn, skip = 9, col_names = F)  %>% 
#     filter(! X1 %in% c('Biplot','Site constraints')) %>% 
#     column_to_rownames('X1') %>% 
#     as.matrix()
#   
#   protest_res = protest(X = dpcoa, Y = spcoa,  permutations = 999)
#   return( list(pval  = protest_res$signif,
#                corr = protest_res$t0))
# }) 

# # make the above to a df and then plot 
# protest_Nday[[1]]$corr
# 
# pvals <- protest_Nday %>% 
#   set_names(fns_both  %>% pull(ID)) %>%  
#   map_dfr(~ pluck(.x = ., 'pval')) %>% 
#   gather('pNd', 'pval')
# 
# corrs <-  protest_Nday %>% 
#   set_names(fns_both  %>% pull(ID)) %>% 
#   map_dfr(~ pluck(.x = ., 'corr')) %>% 
#   gather('pNd', 'corr')
# 
# allstool_res <- pvals %>% 
#   full_join(corrs)
# 
# allstool_res %>% 
#   gather('type', 'value', pval:corr) %>% 
#   ggboxplot(y =  'value', add = 'dotplot', label = 'pNd', repel = T,
#             xlab = '', ylab = '',
#             title = 'procrustes test  (all qualified stool samples)') +
#   facet_wrap(~ type, scales = 'free_y')

```

```{r sum_of_squares}
procrustes_Nday <- map2_dfc(fns_both$dfn, fns_both$sfn, function(dfn, sfn){
  dpcoa = read_tsv(dfn, skip = 9, col_names = F)  %>% 
    filter(! X1 %in% c('Biplot','Site constraints')) %>% 
    column_to_rownames('X1') %>% 
    as.matrix()
  
  spcoa = read_tsv(sfn, skip = 9, col_names = F)  %>% 
    filter(! X1 %in% c('Biplot','Site constraints')) %>% 
    column_to_rownames('X1') %>% 
    as.matrix()
  
  procrustes_res = procrustes(X = dpcoa, Y = spcoa)
  return( procrustes_res$ss)
}) %>% 
  gather(key = 'pNd', value = 'ss') %>% 
  mutate(pNd = fns_both$ID)
```

```{r}
# convert it to a score so that the p2d is the highest
procrustes_Nday_score <- procrustes_Nday %>% 
  mutate(score = min(.$ss) - ss)
```


```{r sum_of_squares}
# make the figure
axis_text_size <- 10
axis_title_size <- 10

procrustes_Nday_score %>% 
  mutate(pNd = str_extract(pNd, '\\d')) %>% 
  ggdotchart(x = 'pNd', y = 'score', sorting = 'none', ylab = 'Sum of squares',
             xlab = 'Number of previous days\nof dietary intake', size = 1.3) +
  geom_line(aes(x = pNd, y = score), group = 1, linetype = 'dashed', size = 0.3) +
  theme(aspect.ratio=1,
        axis.text=element_text(size=axis_text_size), 
        axis.title=element_text(size=axis_title_size),
        axis.text.x = element_text(angle=0, hjust=0.5)) 

ggsave('../figs/paper/022_fig2_procrustes.eps',
       width = 100,
       height = 50,
         #height = 60,
         units = c("mm"),
         dpi = 400, device = 'eps')

procrustes_Nday_score %>% 
  write_csv('../data/022_procrustes_Nday_score.csv')
```

```{r}
# or plot in another way 
procrustes_Nday %>% 
  ggpubr::ggdotchart(x = 'pNd', y = 'ss',
  ggtheme = theme_bw(), size = 3, xlab = 'No. diet-data days preceding each stool sample', ylab = 'association between\ndiet composition and microbiome composition', label = 'pNd',
    sorting = 'none') +
  theme(axis.text.x = element_blank()) +
  ggsave('../figs/procrustes_Nday_SS.pdf', width = 4.5, height = 4.5) 
```



