---
title: "envfit stool alpha diversity"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(vegan)
library(tidyverse)
library(ggpubr)
library(ape)
```

Fit the family abunance onto stool alpha diversity colored PCoA

# all samples bc distance PCoA colored by stool alpha diversity

```{r}
# all samples genus counts matrix and pcoa
cts <- read_csv('../data/cleaned_stool/ALL_stool_samples_genus_counts.csv') %>% 
  select(sampleid, taxa_genus, relab) %>% 
  spread(key = 'taxa_genus', value = 'relab') %>% 
  column_to_rownames('sampleid')


meta <- read_csv('../data/cleaned_stool/all_samples_meta.csv')

dist_all <- vegdist(cts, method = 'bray')

all_bc <- cmdscale(dist_all, k = 2) %>% 
  as.data.frame() %>% 
  rownames_to_column('sampleid') %>% 
  full_join(meta) %>% 
  mutate(sqrtSR = sqrt(simpson_reciprocal))

# the percent variance
eigen <- pcoa(dist_all)$values$Eigenvalues
percent_var <- signif(eigen/sum(eigen), 3)*100

library("viridis") 

all_bc %>% 
  ggscatter(x = 'V1', y = 'V2', color = 'sqrtSR', alpha = 0.5)  +
  xlab(paste0("PC 1 [",percent_var[1],"%]")) +
  ylab(paste0("PC 2 [",percent_var[2],"%]")) +
  scale_color_viridis()
  

```

```{r}
# all sample family abundance
cts <- asv_counts_ag %>% 
  filter(sampleid %in% dat$sampleid) %>% 
  select(asv_key, sampleid, count) %>% 
  spread(key = 'sampleid', value = 'count', fill = 0) %>% 
  arrange(asv_key)  


annot <- asv_annotation_blast_ag %>% 
  filter(asv_key %in% cts$asv_key) %>% 
  mutate(ordr =  if_else(ordr == '', str_glue('of_class_{class}'), ordr),
         family =  if_else(family == '', str_glue('of_order_{ordr}'), family),
         genus =  if_else(genus == '', str_glue('of_family_{family}'), genus),
         species =  if_else(species == '', str_glue('of_genus_{genus}'), species)) %>% 
   mutate(taxa_family = str_glue('k__{kingdom}|p__{phylum}|c__{class}|o__{ordr}|f__{family}'))


# replace the asv_key with the genus taxa level
# summarize from asv level to genus level
# get the relative abundance for the genera
cts_fam <- cts %>% 
  full_join(annot %>%  select(asv_key, taxa_family), by  = 'asv_key') %>% 
  select(-asv_key) %>% 
  gather(key = 'sampleid', value = 'count', names(.)[1]:names(.)[ncol(.) - 1]) %>% 
  group_by(sampleid, taxa_family) %>% 
  summarise(cnt = sum(count)) %>% 
  # get the total count from the db to calculate the relab
  left_join(asv_counts_ag %>% distinct(sampleid,count_total ), by = 'sampleid') %>% 
  mutate(relab = cnt/count_total)  

cts_fam %>% write_csv('../data/cleaned_stool/ALL_stool_samples_family_counts.csv')


```

```{r}
# get the top n family relab 
topn <- cts_fam %>% group_by(taxa_family) %>% 
  summarise(sum_relab = sum(relab)) %>% 
  arrange(-sum_relab) %>% 
  top_n(15) %>% 
  pull(taxa_family)


topn_cts <- cts_fam %>% 
  filter(taxa_family %in% topn) %>% 
  mutate(taxa_family = str_extract(taxa_family, 'f__.+$')) %>% 
  select(sampleid, taxa_family, relab) %>% 
  spread(key = 'taxa_family', value = 'relab', fill = 0) %>% 
  column_to_rownames('sampleid')


ord <- pcoa(dist_all)
(fit <- envfit(ord, topn_cts, perm = 999))

```

```{r}
myTable = matrix(nrow=20,ncol=10)
for(i in 1:10) {myTable[i,] = sample(1:10,10)}
for(i in 11:20) {myTable[i,] = sample(15:25,10)}

myMetadata = data.frame(FirstColumn = character(), SecondColumn = character(), stringsAsFactors=FALSE)
myMetadata[1:10,1] = 'G1'
myMetadata[11:20,1] = 'G2'
myMetadata[seq(1,20,2),2] = 'G3'
myMetadata[seq(2,20,2),2] = 'G4'

library(vegan)
envfit(myTable ~ myMetadata$FirstColumn, data = myMetadata, perm=1000)
```

