---
title: "the other way around linear mixed effects"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:  
    toc: true
    toc_float: true 
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F)
```

```{r}
library(tidyverse)
library(lmerTest)
library(ggpubr)
```

```{r}
dat <- read_csv('../data/cleaned_stool/all_samples_meta_p2d.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(abx = factor(abx, levels = c('non_empirical','empirical')))

fac_col <- c('mrn','source',  'sex', 'abx')

dat[fac_col] <- lapply(dat[fac_col], factor)  
colnames(dat)

summary(dat)

dat2 <- dat %>% 
  #mutate(abx = as.character(abx)) %>% 
  filter(abx == 'non_empirical')
dat %>% 
  distinct(mrn, .keep_all = T)  %>% 
  count(intensity)
```

```{r}
# visualize how the alpha div change according to time
dat %>% 
  ggscatter(x = 'sdrt', y = 'simpson_reciprocal',alpha = 0.5, 
   add = "loess", conf.int = TRUE) 
```


# important food groups one by one

```{r}
mod23 <-  lmer(simpson_reciprocal ~ 
              #fg_fruit+
               #fg_meat+
               #fg_milk+
               #fg_oils+
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

mod23_2 <-  lmer(simpson_reciprocal ~ 
              #fg_fruit+
               #fg_meat+
               #fg_milk+
               #fg_oils+
                sdrt^2 +
                #sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)
anova(mod23, mod23_2)
# It doesn't seem I need to use the time square term
```


```{r}
mod24 <-  lmer(simpson_reciprocal ~ 
              #fg_fruit+
               fg_meat+
               #fg_milk+
               #fg_oils+
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

anova(mod23, mod24)

# yes meat!
```


```{r}
mod25 <-  lmer(simpson_reciprocal ~ 
              fg_fruit+
               #fg_meat+
               #fg_milk+
               #fg_oils+
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

anova(mod23, mod25)
# no fruit 
```
```{r}
mod26 <-  lmer(simpson_reciprocal ~ 
              #fg_fruit+
               #fg_meat+
               fg_milk+
               #fg_oils+
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

anova(mod23, mod26)
# yes milk!
```
```{r}
mod27 <-  lmer(simpson_reciprocal ~ 
              #fg_fruit+
               #fg_meat+
               #fg_milk+
               fg_oils+
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

anova(mod23, mod27)
# yes oil!
```
```{r}
mod34 <-  lmer(simpson_reciprocal ~ 
              #fg_fruit+
               #fg_meat+
               #fg_milk+
               #fg_oils+
                fg_egg+
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

anova(mod23, mod34)
# yes egg!
```

```{r}
mod35 <-  lmer(simpson_reciprocal ~ 
              #fg_fruit+
               #fg_meat+
               #fg_milk+
               #fg_oils+
                #fg_egg+
                fg_grain+
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

anova(mod23, mod35)
# yes grain!
```
```{r}
mod36 <-  lmer(simpson_reciprocal ~ 
              #fg_fruit+
               #fg_meat+
               #fg_milk+
               #fg_oils+
                #fg_egg+
                #fg_grain+
                fg_sweets+
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

anova(mod23, mod36)
#no sweets!
```
```{r}
mod37 <-  lmer(simpson_reciprocal ~ 
              #fg_fruit+
               #fg_meat+
               #fg_milk+
               #fg_oils+
                #fg_egg+
                #fg_grain+
                #fg_sweets+
                fg_legume+
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

anova(mod23, mod37)
# no legume
```
```{r}
mod38 <-  lmer(simpson_reciprocal ~ 
              #fg_fruit+
               #fg_meat+
               #fg_milk+
               #fg_oils+
                #fg_egg+
                #fg_grain+
                #fg_sweets+
                #fg_legume+
                fg_veggie+
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

anova(mod23, mod38)
# yes fg_veggie!
```

 
# if only looking at nutrients

```{r}
mod28 <-  lmer(simpson_reciprocal ~ 
                Nut_Carbohydrates +
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

anova(mod23, mod28)

# yes Nut_Carbohydrates!
```

```{r}
mod29 <-  lmer(simpson_reciprocal ~ 
                Nut_Fat +
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

anova(mod23, mod29)

# yes Nut_Fat! 
```

```{r}
mod30 <-  lmer(simpson_reciprocal ~ 
                Nut_Proteing +
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

anova(mod23, mod30)

# yes protein!
```
```{r}
mod31 <-  lmer(simpson_reciprocal ~ 
                Nut_Fibers +
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

anova(mod23, mod31)

# no fiber! 
```
```{r}
mod32 <-  lmer(simpson_reciprocal ~ 
                Nut_Sugars +
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

anova(mod23, mod32)
# no Nut_Sugars
```
```{r}
mod33 <-  lmer(simpson_reciprocal ~ 
                Nut_Sodium +
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = FALSE, data = dat)

anova(mod23, mod33)
# yes Nut_Sodium
```

**sodium, fat, protein is important**

# use some functions to do backward model selection

```{r}
# compute correlation matrix for the fg and nut
fmetrics <- dat %>% 
  select(fg_egg:Nut_Sugars)

f_cor <- cor(fmetrics, method = "pearson")

library(caret)
f_cor_res <- findCorrelation(f_cor, names = T)
f_cor_res
```
```{r}
mod99 <-  lmer(simpson_reciprocal ~ 
              fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+
                fg_grain+
                fg_sweets+
                fg_legume+
                fg_veggie+
                Nut_Carbohydrates+
                Nut_Fat+
                Nut_Fibers+
                Nut_Proteing+
                Nut_Sodium+
                Nut_Sugars+
                sdrt+
               abx + 
               source + 
               age +
               (1 + abx | mrn), REML = F, data = dat)
step(mod99)

head(dat$timebin)
```

# finalizing the model: what I care about and wanna model?


```{r}
# mod100 <-  lmer(simpson_reciprocal ~ 
#               fg_fruit+
#                fg_meat+
#                fg_milk+
#                fg_oils+
#                 fg_egg+
#                 fg_grain+
#                 fg_sweets+
#                 fg_legume+
#                 fg_veggie+
#                abx + 
#                intensity + 
#                (timebin || mrn) , REML = F, data = dat)
# summary(mod100)
# Error: number of observations (=796) <= number of random effects (=920) for term (0 + timebin | mrn); the random-effects parameters and the residual variance (or scale parameter) are probably unidentifiable
```

```{r}
mod101 <-  lmer(simpson_reciprocal ~ 
              fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+
                fg_grain+
                fg_sweets+
                #fg_legume+
                fg_veggie+
                sdrt +
               abx + 
               intensity + 
               (1 | mrn)  , REML = F, data = dat )
summary(mod101)

```





