---
title: "Taxa association using deseq2"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
library(tidyverse)
library(DESeq2)
library(ggpubr)
library(stats)
```

# the meta table and adjust to the right format

```{r}
# load the data
# to add a column (mrn_N) that distinguishes the mrn nested within an intensity condition
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d.csv')  %>% 
  arrange(sampleid) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(abx = factor(abx, levels = c('non_empirical','empirical')),
         mrn = factor(mrn),
         source = factor(source),
         sex = factor(sex)) %>% 
  mutate(abx_ = as.numeric(abx),
         intensity_ = as.numeric(intensity),
         mrn_ = as.numeric(mrn)) %>% 
  arrange(intensity_, mrn_) %>% 
  split(.$intensity) %>% 
  map_dfr(~ mutate(.data = ., mrn_N = factor(as.numeric(as.factor(mrn_)))))
```

# the counts table (species count)

```{r}
source('~/db_connect_simple.R')
connect_database(config_file = '~/dbConfig.txt')

get_table_from_database('asv_annotation_blast_ag')

asv_counts_ag <- read_csv('../data/asv_counts_ag_Feb17.csv')

cts <- asv_counts_ag %>% 
  filter(sampleid %in% meta$sampleid) %>% 
  select(asv_key, sampleid, count) %>% 
  spread(key = 'sampleid', value = 'count', fill = 0) %>% 
  arrange(asv_key)  


annot <- asv_annotation_blast_ag %>% 
  filter(asv_key %in% cts$asv_key) %>% 
  mutate(ordr =  if_else(ordr == '', str_glue('of_class_{class}'), ordr),
         family =  if_else(family == '', str_glue('of_order_{ordr}'), family),
         genus =  if_else(genus == '', str_glue('of_family_{family}'), genus),
         species =  if_else(species == '', str_glue('of_genus_{genus}'), species)) %>% 
  mutate(taxa_species = str_glue('k__{kingdom}|p__{phylum}|c__{class}|o__{ordr}|f__{family}|g__{genus}|s__{species}'))
 
# replace the asv_key with the genus taxa level
# summarize from asv level to genus level
# get the relative abundance for the genera
cts_spp <- cts %>% 
  full_join(annot %>%  select(asv_key, taxa_species), by  = 'asv_key') %>% 
  select(-asv_key) %>% 
  gather(key = 'sampleid', value = 'count', names(.)[1]:names(.)[ncol(.) - 1]) %>% 
  group_by(sampleid, taxa_species) %>% 
  summarise(cnt = sum(count)) %>% 
  # get the total count from the db to calculate the relab
  left_join(asv_counts_ag %>% distinct(sampleid,count_total ), by = 'sampleid') %>% 
  mutate(relab = cnt/count_total) 

cts_spp %>% 
  write_csv('../data/cleaned_stool/ALL_stool_samples_species_counts.csv')
```

```{r}
cts <- cts_spp %>% 
  select(sampleid, taxa_species, cnt) %>% 
  arrange(sampleid)
```


# filter on the counts table

```{r}
# the distribution of the total count of the genera
total_cnt <- cts %>% 
  group_by(taxa_species) %>% 
  summarise(total = sum(cnt))

quantile(x = total_cnt$total, probs = seq(0,1,0.05))

# total_cnt %>% 
#   gghistogram(x = 'total', bins = 100)

# also see how many samples per patient
# meta %>% 
#   dplyr::count(mrn) %>% 
#   arrange(n)
```

have at least 5 raw count in at least 10% of the samples

```{r}
# filter the count table
cts_ma <- cts %>% 
  spread(key = 'sampleid', value = 'cnt') %>% 
  column_to_rownames('taxa_species') %>% 
  as.matrix()

num_thre <- floor(ncol(cts_ma) * 0.1)

cts_ma_fil <- cts_ma[rowSums(cts_ma >= 5) >= num_thre, ]
```


# The design matrix

```{r}
design_f <- model.matrix(~  fg_fruit + 
                            fg_meat + 
                            fg_milk + 
                            fg_oils +  
                            fg_egg + 
                            fg_grain + 
                            fg_sweets + 
                            fg_veggie + 
                            fg_legume+ 
                            abx + 
                            intensity + 
                            intensity : mrn_N +  
                            intensity: sdrt, meta)


all.zero <- apply(design_f, 2, function(x) all(x==0))


idx <- which(all.zero)
design_f <- design_f[,-idx]


#df <- as.data.frame(rowSums(cts_ma_fil))
```


# build the deseq object

```{r}
# the deseq2 part
dds <- DESeqDataSetFromMatrix(countData = cts_ma_fil + 1,# to avoid at least one entry has at least one zero
                              colData = meta,
                              design = design_f)

dds %>% 
  write_rds('../data/cleaned_pair/deseq_obj_spp.RDS')
```

# "differential expression" analysis

```{r}
dds <- DESeq(dds, test = 'Wald',
             betaPrior = F,
             full = design_f,
             fitType = 'local',
             parallel = T) 
```

# the results and the significance

```{r}
# the significant results
sig_res <- colnames(design_f)[2:10] %>% 
  set_names(colnames(design_f)[2:10]) %>% 
  map(function(x){
    results(dds, name = x, alpha = 0.1) %>% 
      as.data.frame() %>% 
      rownames_to_column('taxa_species')
    }) %>% 
  bind_rows(.id = 'grp')

sig_only <- sig_res %>% 
  filter(padj < 0.1) %>% 
  mutate(taxa_species = str_extract(taxa_species, 'f__.+$')) %>% 
  arrange(padj)

sig_only %>% 
  write_csv('../data/cleaned_pair/sig_only.csv')
```

```{r}
# other group / factor
resultsNames(dds)
res_abx <- results(dds, name = 'abxempirical', alpha = 0.1)
summary(res_abx)
res_abx %>% 
  as.data.frame() %>% 
  rownames_to_column('taxa_species') %>% 
  arrange(padj)
```

