---
title: "linear mixed effects model for faith alpha diversity for both food and stool"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lmerTest)
library(tidyverse)
library(ggpubr)
library(PhyloMeasures)
```

# calculate stool faith alpha diversity

```{r}
# microbiome counts 
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d.csv') %>% 
    mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
    mutate(abx = factor(abx, levels = c('non_empirical','empirical')),
           mrn = factor(mrn))

asv_counts_ag <- read_csv('../data/asv_counts_ag_Feb17.csv')
cts <- asv_counts_ag %>% 
  filter(sampleid %in% meta$sampleid) %>% 
  select(asv_key, sampleid, count) %>% 
  spread(key = 'asv_key', value = 'count', fill = 0) %>% 
  arrange(sampleid)  %>% 
  column_to_rownames('sampleid') %>% 
  as.matrix()


all_tree <- ape::read.tree('../data/cleaned_stool/asv_sequences_all.newick')
salpha <- pd.query(all_tree, cts, standardize = FALSE,  null.model="uniform", reps=1000)

salpha <- data_frame(
  sampleid = rownames(cts),
  sfaith = salpha
)

all_meta <- meta %>% 
  full_join(salpha)
```

```{r}
# compare the faith and simpson reciprocal
all_meta %>% 
  ggscatter(x = 'simpson_reciprocal', y = 'sfaith',
              add = "reg.line",  # Add regressin line
             add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
             conf.int = TRUE, # Add confidence interval
             cor.coef = TRUE, # Add correlation coefficient. see ?stat_cor
             cor.coeff.args = list(method = "pearson", label.x = 3, label.sep = "\n"))
```


# load food alpha diversity and average the previous 2 days

```{r}
ffaith <- read_tsv('../data/cleaned_diet_data/FINAL_97_faith_pd/alpha-diversity.tsv', col_types = 'cd') %>% 
  separate(X1, into = c('mrn','fdrt'), sep = 'd', convert = T) %>% 
  mutate(mrn = as.numeric(str_replace(mrn, '^P','')))

all_meta_pair <- all_meta %>%  
  select(mrn, sdrt) %>% 
  transmute(mrn = mrn,
            p1d = sdrt-1,
            p2d = sdrt-2) 
 
mean_p2d_ffaith <-  function(mrn_, p1d_, p2d_){
  df = ffaith %>% 
    filter(mrn == mrn_) %>% 
    filter(fdrt %in% c(p1d_, p2d_  )) %>% 
    summarise(ave_ffaith = mean(faith_pd))
  return(df)
}

mean_p2d_ffaith_df <- pmap(all_meta_pair, function(mrn, p1d, p2d){
    mean_p2d_ffaith(mrn, p1d, p2d)
  }) %>% 
  set_names(all_meta$sampleid) %>% 
  bind_rows(.id = 'sampleid') %>% 
  filter(!is.nan(ave_ffaith))# some just don't have previous two days data so remove


final_alpha   <- all_meta %>% 
  inner_join(mean_p2d_ffaith_df) %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) 
```

# linear mixed effects model, controlling time

```{r}
mod104 <-  lmer(sfaith ~ 
                ave_ffaith +
                abx +
                intensity +
                #sdrt +
               (1 | timebin) +
               (1 | mrn) , REML = F, data = final_alpha )
summary(mod104) # the stool alpha decreses mildly as the food alpha increases???
```
```{r}
mod105 <-  lmer(sfaith ~ 
              fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+
                fg_legume+
                fg_veggie+
               # sdrt +
               abx + 
               intensity + 
               (1 | mrn) +
                (1 | timebin), REML = F, data = final_alpha )
summary(mod105)
```

# use the caloric intake as the predictor

```{r}
source('~/db_connect_simple.R')
connect_database(config_file = '~/dbConfig.txt')

dbListTables(con) %>% data.frame() %>% filter(grepl("nutri",.))

get_table_from_database('nutrition_ag')

cal <- nutrition_ag %>% 
  filter(mrn %in% all_meta$mrn) %>% 
  select(mrn, fdrt = days_post_hsct, calories_in = calories__kcal__po)
```

```{r}
mean_p2d_cal <-  function(mrn_, p1d_, p2d_){
  df = cal %>% 
    filter(mrn == mrn_) %>% 
    filter(fdrt %in% c(p1d_, p2d_  )) %>% 
    summarise(ave_cal = mean(calories_in))
  return(df)
}

mean_p2d_cal_df <- pmap(all_meta_pair, function(mrn, p1d, p2d){
    mean_p2d_cal(mrn, p1d, p2d)
  }) %>% 
  set_names(all_meta$sampleid) %>% 
  bind_rows(.id = 'sampleid') %>% 
  filter(!is.nan(ave_cal))

final_cal   <- all_meta %>% 
  inner_join(mean_p2d_cal_df) %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) 
```

```{r}
mod106 <-  lmer(simpson_reciprocal ~ 
                ave_cal +
                abx +
                intensity +
                #sdrt +
               (1 | timebin) +
               (1 | mrn) , REML = F, data = final_cal )
summary(mod106)
```

```{r}
# what about the nutrients level
mod107 <-  lmer(sfaith ~ 
                Nut_Carbohydrates +
                  Nut_Fat +
                  Nut_Fibers +
                  Nut_Proteing +
                  Nut_Sodium +
                  Nut_Sodium +
                abx +
                intensity +
                #sdrt +
               (1 | timebin) +
               (1 | mrn) , REML = F, data = final_cal )
summary(mod107)
```

