---
title: "look at the tree informed microbiome beta diversity using phyloseq"
output: html_document
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(phyloseq)
library(tidyverse)
library(imsig)
```

# build phyloseq object

```{r}
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d.csv') %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(abx = factor(abx, levels = c('non_empirical','empirical')),
           mrn = factor(mrn)) %>% 
  arrange(sampleid) %>% 
  column_to_rownames('sampleid')


asv_counts_ag <- read_csv('../data/asv_counts_ag_Feb17.csv')

cts <- asv_counts_ag %>% 
  filter(sampleid %in% rownames(meta)) %>% 
  select(asv_key, sampleid, count) %>% 
  arrange(sampleid) %>% 
  spread(key = 'sampleid', value = 'count', fill = 0) %>% 
  arrange(asv_key) %>% 
  column_to_rownames('asv_key') %>% 
  as.matrix()

all.equal(colnames(cts), rownames(meta))

source('~/db_connect_simple.R')
connect_database(config_file = '~/dbConfig.txt')

ANNOT <- get_table_from_database('asv_annotation_blast_ag')

annot <- ANNOT %>% 
  filter(asv_key %in% rownames(cts)) %>% 
  dplyr::select(asv_key:species) %>% 
  arrange(asv_key) %>% 
  column_to_rownames('asv_key') %>% 
  as.matrix()

colnames(annot) <- c("Kingdom", "Phylum",  "Class",  "Order",  "Family", "Genus", "Species" )

all(rownames(annot) == rownames(cts))

all_tree <- ape::read.tree('../data/cleaned_stool/asv_sequences_all.newick')
```


```{r}
ps <- phyloseq(otu_table(cts, taxa_are_rows=T), 
               sample_data(meta), 
               tax_table(annot),
               phy_tree(all_tree))

ps
```

# filter in phylum 

```{r}
table(tax_table(ps)[, "Phylum"], exclude = NULL)

# filter out the phylum is NA and only have one feature ones 
ps1 <- subset_taxa(ps, !is.na(Phylum) & !Phylum %in% c("", "uncharacterized"))
```
```{r}
# Compute prevalence of each feature at phylum level, store as data.frame
prevdf = apply(X = otu_table(ps1),
               MARGIN = ifelse(taxa_are_rows(ps1), yes = 1, no = 2),
               FUN = function(x){sum(x > 0)}) %>% 
  as.data.frame() %>% 
  rownames_to_column('asv_key') %>% 
  rename(cnt = names(.)[2])

TotalAbundance = taxa_sums(ps1) %>% 
  as.data.frame() %>% 
  rownames_to_column('asv_key') %>% 
  rename(total = names(.)[2])

prev_df <- annot %>% 
  as.data.frame() %>% 
  rownames_to_column('asv_key') %>% 
  inner_join(prevdf) %>% 
  inner_join(TotalAbundance)

prev_df_summarise <-  prev_df %>% 
  group_by(Phylum) %>% 
  summarise(ave = mean(cnt),
            phy_total = sum(total)) %>% 
  arrange(phy_total)

# remove the ones that have phy_total < 10
rm_phy <- c('Lentisphaerae','Rhodothermaeota','Acidobacteria','Gemmatimonadetes','Armatimonadetes')

ps2 = subset_taxa(ps1, !Phylum %in% rm_phy)
ps2
```

# Prevalence Filtering 

```{r}
# Subset to the remaining phyla

prevdf1 <- prev_df %>% 
  filter(Phylum %in% get_taxa_unique(ps2, "Phylum"))

ggplot(prevdf1, aes(total, cnt / nsamples(ps2),color=Phylum)) +
  geom_hline(yintercept = 0.05, alpha = 0.5, linetype = 2) +  
  geom_point(size = 2, alpha = 0.7) +
  scale_x_log10() +  
  xlab("Total Abundance") + 
  ylab("Prevalence [Frac. Samples]") +
  facet_wrap(~Phylum) + 
  theme(legend.position="none")
```
```{r}
# Define prevalence threshold as 5% of total samples
prevalenceThreshold = 0.05 * nsamples(ps2)
prevalenceThreshold

keepTaxa <- prevdf1 %>% 
  filter(cnt > prevalenceThreshold) %>% 
  pull(asv_key)

ps3 = prune_taxa(keepTaxa, ps2)
```


```{r}
ps3ra = transform_sample_counts(ps3, function(x){x / sum(x)})

out.dpcoa.log <- ordinate(ps3ra, method = "DPCoA")

evals <- out.dpcoa.log$eig

plot_ordination(ps3ra, out.dpcoa.log, 
                color = "simpson_reciprocal")
```


```{r}
plot_ordination(ps3ra, out.dpcoa.log, type = "species", color = "Family") 
```

```{r}
ps_ccpna <- ordinate(ps3ra, "CCA", formula = ps3ra ~ fg_egg + fg_fruit +
                       fg_grain +
                       fg_legume +
                       fg_meat +
                       fg_milk +
                       fg_oils +
                       fg_sweets +
                       fg_veggie +
                       intensity +
                       abx +
                       sdrt +
                       mrn)
ps_scores <- vegan::scores(ps_ccpna)
sites <- data.frame(ps_scores$sites)
sites$sampleid <- rownames(sites)

sites <- sites %>%
  left_join(sample_data(ps3ra) %>% 
              rownames_to_column('sampleid'))

species <- data.frame(ps_scores$species)
species$asv_key <- rownames(otu_table(ps3ra))
species <- species %>%
  left_join(annot %>% 
              as.data.frame() %>% 
              rownames_to_column('asv_key'))

ggplot() +
  geom_point(data = sites, aes(x = CCA1, y = CCA2), shape = 2, alpha = 0.5) +
  geom_point(data = species, aes(x = CCA1, y = CCA2, col = Order), size = 0.5) 
```

