---
title: "bioenv"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(vegan)
library(tidyverse)
```

Function finds the best subset of environmental variables, so that the Euclidean distances of scaled environmental variables have the maximum (rank) correlation with community dissimilarities.

```{r}
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d.csv') %>% 
    mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
    mutate(abx = factor(abx, levels = c('non_empirical','empirical')),
           mrn = factor(mrn)) %>% 
  arrange(sampleid)

pheno <- meta %>% 
  dplyr::select(mrn, abx, intensity, sdrt,
                   fg_fruit,
                   fg_meat,
                   fg_milk,
                   fg_oils,
                   fg_egg,
                   fg_grain,
                   fg_sweets,
                   fg_legume,
                   fg_veggie)
```

# the log transformed BC distance

```{r}
cts_fam <- read_csv('../data/cleaned_stool/ALL_stool_samples_family_counts.csv') %>% 
  filter(sampleid %in% meta$sampleid) %>% 
  arrange(sampleid) %>% 
  mutate(logcnt = log(cnt + 1)) %>% 
  dplyr::select(sampleid, taxa_family, logcnt) %>% 
  spread(key = 'taxa_family', value = 'logcnt', fill = log(1)) %>% 
  column_to_rownames('sampleid') %>% 
  as.matrix()

# filter on this counts matrix?
num_thre <- floor(nrow(cts_fam) * 0.1)

cts_fam_fil <- cts_fam[ ,colSums(cts_fam >= log(5 + 1)) >= num_thre ]
```

```{r}


res <- bioenv(comm = cts_fam,
              env = pheno,
              method = 'spearman',
              index = "bray",
              metric = 'gower',
              parallel = 8)

summary(res)
res

```

# try the envfit again

```{r}
ord <- capscale(formula = cts_fam ~ 1,
                distance = 'bray',
                dfun = vegdist,
                #add = T,
                sqrt.dist = T)

# the percent variance
eigen <- eigenvals(ord)
percent_var <- signif(eigen/sum(eigen), 3)*100

sum(percent_var[1:36])

bray_fam.fit <- envfit(ord ~ abx + intensity + sdrt +
                   fg_fruit+
                   fg_meat+
                   fg_milk+
                   fg_oils+
                   fg_egg+
                   fg_grain+
                   fg_sweets+
                   fg_legume+
                   fg_veggie, pheno, 
                   choices=c(1:36), 
                   strata = pheno$mrn,
                   permutations = 10000 ) 
bray_fam.fit
```

# is the adonis returning the same?

```{r}
pmv <- adonis(cts_fam ~ abx + intensity + sdrt +
                   fg_fruit+
                   fg_meat+
                   fg_milk+
                   fg_oils+
                   fg_egg+
                   fg_grain+
                   fg_sweets+
                   fg_legume+
                   fg_veggie, data=pheno, permutations=999, method = 'bray', strata = pheno$mrn, parallel = 8)

data_frame(
  item = colnames(pheno)[2:ncol(pheno)],
  pval = pmv$aov.tab$`Pr(>F)`[1:12],
  r2 = pmv$aov.tab$R2[1:12]
) %>% 
  mutate(padj = p.adjust(pval, method = 'BH')) %>% 
  arrange(padj)
  

```


```{r}
pmv
colnames(pheno) %>% 
  set_names(colnames(pheno)) %>% 
  map(function(term){
    pmv = adonis(cts_fam ~ term, data=pheno, permutations=999, method = 'bray', strata = mrn)
    return(list(r2 = pmv$aov.tab$R2[1],
                pval = pmv$aov.tab$`Pr(>F)`[1]))
  })


```


```{r}
colnames(pheno)
```

