---
title: "common dominating genera"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
library(tidyverse)
library(ggpubr)
```

```{r}
dat <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(empirical = factor(empirical, levels = c('FALSE','TRUE')))

# look at the genus level
cts <- read_csv('../data/cleaned_stool/ALL_stool_samples_genus_counts.csv') %>% 
  filter(sampleid %in% dat$sampleid) %>% 
  dplyr::select(sampleid, taxa_genus, relab) %>% 
  mutate(taxa_genus = str_extract(taxa_genus, 'g__.+$'))

dat %>% 
  summary
```

## The dominating genera:

g__Enterococcus, 

g__Streptococcus,

g__lactobacillus, 

g__Staphylococcus, 

g__Escherecia, 

g__Klebsiella

```{r}
# get the relab of those genera

domgen <- c('g__Enterococcus', 'g__Streptococcus', 'g__Lactobacillus', 'g__Staphylococcus', 'g__Escherichia', 'g__Klebsiella')

domcts <- cts %>% 
  filter(taxa_genus %in% domgen) %>% 
  mutate(relablog = log10(relab + 2*10^-6)) %>% 
  dplyr::select(-relab) %>% 
  mutate(taxa_genus = str_replace(taxa_genus, 'g__','')) %>% 
  spread(key = 'taxa_genus', value = 'relablog')

all <- domcts %>% 
  full_join(dat, by = "sampleid")

```

## linear mixed model using the dominating genera relab as read-out

### g__Staphylococcus

```{r}
library(lmerTest)

mod_staphy <-  lmer(Staphylococcus ~ 
               fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               empirical +  
               intensity + 
                TPN +
                EN +
               (1 | mrn) +
                (1 | timebin), REML = F, data = all )
summary(mod_staphy)
```



### g__Enterococcus

```{r}
mod_g__Enterococcus <-  lmer(Enterococcus ~ 
              fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               empirical +  
               intensity + 
                TPN +
                EN +
               (1 | mrn) +
                (1 | timebin), REML = F, data = all )
summary(mod_g__Enterococcus)
```

### g__Escherichia

```{r}
mod_g__Escherichia <-  lmer(Escherichia ~ 
               fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               empirical +  
               intensity + 
                TPN +
                EN +
               (1 | mrn) +
                (1 | timebin), REML = F, data = all )
summary(mod_g__Escherichia)
```

### g__Klebsiella

```{r}
mod_g__Klebsiella <-  lmer(Klebsiella ~ 
               fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               empirical +  
               intensity + 
                TPN +
                EN +
               (1 | mrn) +
                (1 | timebin), REML = F, data = all )
summary(mod_g__Klebsiella)
```

### g__Lactobacillus

```{r}
mod_g__Lactobacillus <-  lmer(Lactobacillus ~ 
             fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               empirical +  
               intensity + 
                TPN +
                EN +
               (1 | mrn) +
                (1 | timebin), REML = F, data = all )
summary(mod_g__Lactobacillus)
```

### g__Streptococcus

```{r}
mod_g__Streptococcus <-  lmer(Streptococcus ~ 
              fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               empirical +  
               intensity + 
                TPN +
                EN +
               (1 | mrn) +
                (1 | timebin), REML = F, data = all )
summary(mod_g__Streptococcus)
```

## brms way

```{r function}
# a function to draw the ridge density plot for the bayes results
draw_ridge_density_fg <- function(brm_mod){
  posterior_model <- posterior_samples(brm_mod) %>% 
    select(starts_with('b')) %>% 
    select(-b_Intercept) %>% 
    gather('item', 'value') %>% 
    group_by(item) %>% 
    mutate(meanperitem = mean(value))%>%
    ungroup()

  posterior_model_only_food_group <- posterior_model %>% 
    filter(str_detect(item, '_fg_')) %>% 
    mutate(item = str_replace(item, 'b_fg_',''))
  
  ggplot()+
    ggridges::geom_density_ridges(data  = posterior_model_only_food_group, 
                                  aes(x      = value,
                                      y      = reorder(as.factor(item), meanperitem),
                                      height = ..density..),
                                  scale = 1.5, size = 0.25,
                                  alpha = 0.6) +
    geom_vline(xintercept = 0, col = "red") +
    #scale_x_continuous(limits = c(-0.02,0.03)) +
    labs(y = '',
         title = '') +
    #theme(axis.text.y = element_text(size=40)) +
    ggthemes::theme_tufte() +
    theme(axis.text.y = element_text(size=30),
          axis.text.x = element_text(size=15))
}
```

 
```{r}
# use the brms to check the g__Enterococcus model 
library(brms)   
library(ggmcmc)

model_Staphylococcus <- brm( Staphylococcus ~ 
              fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               empirical +  
               intensity + 
                TPN +
                EN +
               (1 | mrn) +
                (1 | timebin),  
              data = all, 
              warmup = 1000, iter = 3000, 
              cores = 8, chains = 2, 
              seed = 123) 

draw_ridge_density_fg(model_Staphylococcus)
```

```{r}
model_Enterococcus <- brm( Enterococcus ~ 
              fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               empirical +  
               intensity + 
                TPN +
                EN +
               (1 | mrn) +
                (1 | timebin),  
              data = all, 
              warmup = 1000, iter = 3000, 
              cores = 8, chains = 2, 
              seed = 123) 

draw_ridge_density_fg(model_Enterococcus)
```


```{r}
model_Escherichia <- brm( Escherichia ~ 
              fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               empirical +  
               intensity + 
                TPN +
                EN +
               (1 | mrn) +
                (1 | timebin),  
              data = all, 
              warmup = 1000, iter = 3000, 
              cores = 8, chains = 2, 
              seed = 123) 

draw_ridge_density_fg(model_Escherichia)
```

```{r}
model_Klebsiella <- brm( Klebsiella ~ 
               fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               empirical +  
               intensity + 
                TPN +
                EN +
               (1 | mrn) +
                (1 | timebin),  
              data = all, 
              warmup = 1000, iter = 3000, 
              cores = 8, chains = 2, 
              seed = 123) 

draw_ridge_density_fg(model_Klebsiella)
```

```{r}
model_Lactobacillus  <- brm( Lactobacillus  ~ 
               fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               empirical +  
               intensity + 
                TPN +
                EN +
               (1 | mrn) +
                (1 | timebin),  
              data = all, 
              warmup = 1000, iter = 3000, 
              cores = 8, chains = 2, 
              seed = 123) 

draw_ridge_density_fg(model_Lactobacillus)
```
```{r}
model_Streptococcus  <- brm( Streptococcus  ~ 
               fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               empirical +  
               intensity + 
                TPN +
                EN +
               (1 | mrn) +
                (1 | timebin),  
              data = all, 
              warmup = 1000, iter = 3000, 
              cores = 8, chains = 2, 
              seed = 123) 

draw_ridge_density_fg(model_Streptococcus)
```
```{r}
# put them in a facet grid plot
dom <- list(
  model_Streptococcus = model_Streptococcus,
  model_Enterococcus = model_Enterococcus,
  model_Escherichia = model_Escherichia,
  model_Klebsiella = model_Klebsiella,
  model_Staphylococcus = model_Staphylococcus,
  model_Lactobacillus = model_Lactobacillus
) 

dom %>% 
  purrr::map(
    ~ draw_ridge_density_fg(.)
  ) %>% 
  cowplot::plot_grid(plotlist = ., align = 'hv', ncol = 3, labels = names(.))  +
  ggsave('../figs/dom_genera_brms.pdf', width = 14, height = 10)
```
```{r}
# tsoni's idea of the heatmap
domres  <- dom %>% 
  map(~ posterior_samples(x = .) %>% 
    select(starts_with('b')) %>% 
    gather('item', 'value') %>% 
      filter(str_detect(item, '_fg_')) %>% 
    group_by(item) %>% 
    summarise(meanperitem = mean(value))%>%
    ungroup()) %>% 
  bind_rows(.id = 'grp') %>% 
  mutate(grp = str_replace(grp, 'model_',''),
         item = str_replace(item, 'b_fg_','')) %>% 
  spread('item', 'meanperitem') %>% 
  select(-oils, -egg, -legume) %>% 
  column_to_rownames('grp') %>% 
  as.matrix()

library(pheatmap)
pheatmap(
  domres,
  #annotation_col = annot,
  show_rownames = TRUE,
  show_colnames = TRUE,
  filename = '../figs/all6.pdf',
  height = 4,
  width = 8,
  display_numbers = T,
  number_format = "%.3f"
  #cluster_rows =F,
  #cluster_cols=F
)
```

