---
title: "Use brms to check the food groups really not correlating"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

<a href="https://www.rensvandeschoot.com/tutorials/brms-started/" target="_blank">A tutorial</a>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = T)
```

```{r}
library(brms)  
library(ggmcmc)
library(ggridges)
library(ggthemes)
library(tidyverse)
library(ggpubr)
```

## The full model

```{r}
dat <- read_csv('../data/cleaned_stool/all_samples_meta_p2d.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(abx = factor(abx, levels = c('non_empirical','empirical'))) %>% 
  mutate(mrn = factor(mrn)) 
    

dat %>% 
  mutate(simpson_reciprocal = log(simpson_reciprocal)) %>% 
  gghistogram(x = 'simpson_reciprocal', bins = 60, add_density = T)
```


```{r}
model1 <- brm( log(simpson_reciprocal)~ 
              fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+
                fg_legume+
                fg_veggie+
               abx + 
               intensity + 
               (1 | mrn) +
                (1 | timebin),  
              data = dat, 
              warmup = 1000, iter = 3000, 
              cores = 8, chains = 2, 
              seed = 123) 
```

## Model summary

```{r}
summary(model1)

plot(model1)

model1tranformed <- ggs(model1)

vars <- model1tranformed %>% 
  filter(str_detect(Parameter, '_fg_|abx|intensity')) %>% 
  distinct(Parameter) %>% 
  mutate(Parameter = as.character(Parameter)) %>% 
  pull(Parameter)
  

pairs(model1, pars = vars[1:5] ,fixed = FALSE, exact_match = FALSE)

pairs(model1, pars = vars[6:8] ,fixed = FALSE, exact_match = FALSE)

#pairs(model1, pars = vars[9:12] ,fixed = FALSE, exact_match = FALSE)
```

## use sugar in this brm model

```{r}
dat %>% 
  gghistogram(x = 'Nut_Sugars')

dat %>% 
  gghistogram(x = 'fg_fruit')

model_sugar_brm <- brm( log(simpson_reciprocal) ~ 
             Nut_Sugars +
               abx + 
               intensity + 
               (1 | mrn) +
                (1 | timebin),  
              data = dat, 
              warmup = 1000, iter = 3000, 
              cores = 8, chains = 2, 
              seed = 123) 
summary(model_sugar_brm)

plot(model_sugar_brm)
```
```{r}
model_nut_brm <- brm( log(simpson_reciprocal) ~ 
                Nut_Sugars + 
                Nut_Carbohydrates +
                Nut_Fat +
                Nut_Fibers +
                Nut_Proteing +
                Nut_Sodium +
               abx + 
               intensity +  
               (1 | mrn) +
                (1 | timebin),  
              data = dat, 
              warmup = 1000, iter = 3000, 
              cores = 8, chains = 2, 
              seed = 123) 

plot(model_nut_brm)
```



