---
title: "What's in the sweets subgroups"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r}
library(tidyverse)
library(ggpubr)
```

# to get the sweets subgroups for every patient every day 

```{r}
# what's the subgroup of sweets?
sweets2 <- read_tsv('../data/source/NodeLabelsMCT.txt', col_types = 'cc')  %>% 
  filter(str_detect(Level.code, '^9')) %>% 
  filter(str_length(Level.code) == 2) %>% 
  mutate(Main.food.description = if_else(Main.food.description == 'Formulated_nutrition_beverages_energy_drinks_sports_drinks_function', 'Formulated_nutrition_bev', Main.food.description))

sweets3 <-  read_tsv('../data/source/NodeLabelsMCT.txt', col_types = 'cc')  %>% 
  filter(str_detect(Level.code, '^9')) %>% 
  filter(str_length(Level.code) == 3)
```


```{r}
# to get the sweets subgroups for every patient every day 
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_enteralTPN.csv')
```


## what the sweets sub groups look like

```{r}
what_sweets <- dtb %>% 
  mutate(Food_code = as.character(Food_code)) %>% 
  filter(str_detect(Food_code, '^9')) %>% 
  distinct(Food_NSC, Food_code) %>% 
  mutate(L2_grp = str_sub(Food_code, start = 1, end = 2))  %>% 
  left_join(sweets2 %>% rename(L2_grp = Level.code), by  = 'L2_grp') %>% 
  arrange(L2_grp)

what_sweets %>% 
  kableExtra::kable() %>% 
  kableExtra::kable_styling()
```


```{r}
dtb_sweets <- dtb %>% 
  mutate(Food_code = as.character(Food_code)) %>% 
  filter(str_detect(Food_code, '^9')) %>% 
  mutate(L2_grp = str_sub(Food_code, start = 1, end = 2)) %>% 
  group_by(mrn, fdrt, L2_grp) %>% 
  summarise(L2_total = sum(dehydrated_weight))

dtb_sweets %>% write_csv('../data/cleaned_diet_data/all_level2_sweets_group.csv')

# get the mean of previous two days for every stool sample I'm currently using
stb <- read_csv('../data/cleaned_stool/selected_stool_samples_type_abx.csv') %>% 
  mutate(empirical = if_else(abx == 'empirical', T, F)) %>% 
  select(-abx)

# pulling the alpha diversity 
source('~/db_connect_simple.R')
connect_database(config_file = '~/dbConfig.txt')
get_table_from_database_predefined_filter('asv_alpha_diversity_ag')
  

stb_pair <- stb %>%  
  select(mrn, sdrt) %>% 
  transmute(mrn = mrn,
            p1d = sdrt-1,
            p2d = sdrt-2) 
 
mean_p2d_l2_sweets_diet <-  function(mrn_, p1d_, p2d_){
  df = dtb_sweets %>% 
    filter(mrn == mrn_) %>% 
    filter(fdrt %in% c(p1d_, p2d_  )) %>% 
    group_by(L2_grp) %>% 
    summarise(ave_L2 = sum(L2_total)/2)
  return(df)
}


mean_p2d_l2_sweets_df <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_l2_sweets_diet(mrn, p1d, p2d)
  }) %>% 
  set_names(stb %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid')  %>% 
  left_join(sweets2 %>% rename(L2_grp = Level.code), by  = 'L2_grp') %>% 
  select(-L2_grp ) %>% 
  spread('Main.food.description', 'ave_L2', fill = 0) %>% 
  inner_join(stb, by = "sampleid") %>% 
  select(-count_total, -age, -sex, -source) %>% 
  inner_join(asv_alpha_diversity_ag %>% select(sampleid, simpson_reciprocal))
  
mean_p2d_l2_sweets_df %>% 
  write_csv('../data/cleaned_stool/all_samples_meta_p2d_L2_sweets_only.csv')
```

# linear mixed model with only subgroups of sweets

```{r}
library(lmerTest)
mean_p2d_l2_sweets_df <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_L2_sweets_only.csv')

# to make sure the columns are in right type
sweetdat <- mean_p2d_l2_sweets_df %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = factor(mrn))

mod_sweets <-  lmer(log(simpson_reciprocal) ~ 
              Formulated_nutrition_bev+
               Nonalcoholic_beverages+
               Sugars_and_sweets+
               Water_noncarbonated+
               empirical + 
               intensity + 
               (1 | mrn) +
                (1 | timebin), REML = F, data = sweetdat )
summary(mod_sweets)

```
 
# is it the same from the brms model?

```{r}
library(brms)   
library(ggmcmc)

model_sweets <- brm( log(simpson_reciprocal)~ 
               Formulated_nutrition_bev+
               Nonalcoholic_beverages+
               Sugars_and_sweets+
               Water_noncarbonated+
               empirical + 
               intensity + 
               (1 | mrn) +
                (1 | timebin),  
              data = sweetdat, 
              warmup = 1000, iter = 3000, 
              cores = 8, chains = 2, 
              seed = 123) 

plot(model_sweets)
```

# what if add the nutritional drink to my original model, will the sweets signal go away

```{r}
# check if the nutritional drink is strongly correlated with fg_sweets
# get the two columns together in the same df
both <- read_csv('../data/cleaned_stool/all_samples_meta_p2d.csv') %>% 
  inner_join(sweetdat %>% mutate(mrn = as.numeric(as.character(mrn))))

cor.test(both$fg_sweets, both$Formulated_nutrition_bev, method = 'pearson')
# looks like it is strongly correlated
```


```{r}
model_both <- brm( log(simpson_reciprocal)~ 
               Formulated_nutrition_bev+
               Nonalcoholic_beverages+
               Sugars_and_sweets+ 
               Water_noncarbonated+
                 fg_sweets+
               empirical +   
               intensity + 
               (1 | mrn) +
                (1 | timebin),  
              data = both, 
              warmup = 1000, iter = 3000, 
              cores = 8, chains = 2, 
              seed = 123) 

pairs(model_both, pars = c('fg_sweets','Formulated_nutrition_bev') ,fixed = FALSE, exact_match = FALSE)
```


```{r}  
both %>% 
  mutate(simpson_reciprocal = log(simpson_reciprocal)) %>% 
  gghistogram(x = 'simpson_reciprocal')

both %>%  
  mutate(simpson_reciprocal = log(simpson_reciprocal)) %>% 
  ggscatter(x = 'fg_sweets', y = 'Formulated_nutrition_bev', color = 'simpson_reciprocal',
            alpha = 0.6, size = 3.5, 
           # add = "reg.line",  # Add regressin line 
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval  
           #cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "pearson", label.x = 3, label.sep = "\n")) + 
  viridis::scale_color_viridis() +
  scale_x_sqrt() +
  scale_y_sqrt() +
  geom_abline(intercept = 0, slope = 1, col = 'red', linetype = 'dashed')   
 
```

```{r} 
mod_check <-  lmer(log(simpson_reciprocal) ~ 
              fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                #fg_sweets+
                fg_legume+
                fg_veggie+
                Formulated_nutrition_bev +
               abx + 
               intensity + 
               (1 | mrn) +
                (1 | timebin), REML = F, data = both )
summary(mod_check)
```

# how the nutritional drink consumption is like according to time

```{r}
# to put the patients into two groups high nutritional drink consumption and low , by the mean
sweetdat_group <- sweetdat %>% 
  group_by(mrn) %>% 
  summarise(mean_ndrink = mean(Formulated_nutrition_bev))

sweetdat_group %>% 
  ggboxplot(y = 'mean_ndrink', add = 'jitter') +
  scale_y_sqrt()

thre <- median(sweetdat_group$mean_ndrink)

singlet_pt <- sweetdat %>% 
  mutate(mrn = as.numeric(as.character(mrn))) %>% 
  count(mrn) %>% 
  filter(n == 1) %>% 
  pull(mrn)
 
sweetdat_df <- sweetdat %>% 
  filter(!mrn %in% singlet_pt) %>% 
  select(mrn, sdrt, simpson_reciprocal, Formulated_nutrition_bev) %>% 
  mutate(twogrp = if_else(Formulated_nutrition_bev > thre, 'high', 'low'))

sweetdat_df %>% 
  filter(twogrp == 'high') %>% 
  ggplot() +
  geom_line(mapping = aes(x = sdrt, y = Formulated_nutrition_bev), color = 'purple') +
  geom_point(mapping = aes(x = sdrt, y = Formulated_nutrition_bev), color = 'purple') +
  geom_line(mapping = aes(x = sdrt, y = simpson_reciprocal), color = '#A6761D') +
  geom_point(mapping = aes(x = sdrt, y = simpson_reciprocal), color = '#A6761D') +
  facet_wrap(~mrn, scales = 'free_y')  +
  #scale_y_continuous("Fruit consumption (g)", sec.axis = sec_axis(~ . / 4, name = "simpson_reciprocal")) +
  theme_bw()+
  theme(
  strip.text.x = element_blank(),
  legend.position = 'bottom'
) +
  ggsave('../figs/97_nutritional_drink_diversity_high.pdf', width = 12, height = 8)

sweetdat_df %>% 
  filter(twogrp == 'low') %>% 
  ggplot() +
  geom_line(mapping = aes(x = sdrt, y = Formulated_nutrition_bev), color = 'purple') +
  geom_point(mapping = aes(x = sdrt, y = Formulated_nutrition_bev), color = 'purple') +
  geom_line(mapping = aes(x = sdrt, y = simpson_reciprocal), color = '#A6761D') +
  geom_point(mapping = aes(x = sdrt, y = simpson_reciprocal), color = '#A6761D') +
  facet_wrap(~mrn, scales = 'free_y')  +
  #scale_y_continuous("Fruit consumption (g)", sec.axis = sec_axis(~ . / 4, name = "simpson_reciprocal")) +
  theme_bw()+
  theme(
  strip.text.x = element_blank(),
  legend.position = 'bottom'
) +
  ggsave('../figs/97_nutritional_drink_diversity_low.pdf', width = 12, height = 8)
```

