---
title: "look at the fruit subgroups"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F)
```

```{r}
library(tidyverse)
```

```{r}
fruit2 <- read_tsv('../data/source/NodeLabelsMCT.txt', col_types = 'cc')  %>% 
  filter(str_detect(Level.code, '^6')) %>% 
  filter(str_length(Level.code) == 2)

# so the dtbn is acutually my usual dtb 
dtbn <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')

meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')
```
```{r}
# what food items are in the fruit group
what_fruit <- dtbn %>% 
  filter(str_detect(Food_code, '^6')) %>% 
  distinct(Food_NSC, Food_code) %>% 
  mutate(L2_grp = str_sub(Food_code, start = 1, end = 2))  %>% 
  left_join(fruit2 %>% rename(L2_grp = Level.code), by  = 'L2_grp') %>% 
  arrange(L2_grp)

what_fruit %>%
  kableExtra::kable() %>%
  kableExtra::kable_styling()


```


```{r}
# some examples contained in this group 
# set.seed(2)
# what_fruit %>% 
#   group_by(L2_grp) %>% 
#   sample_n(6) %>% 
#   mutate(desc = str_replace_all(Main.food.description, '_',' ')) %>% 
#   ungroup() %>% 
#   select(desc, Food_NSC)
```

```{r}
dtbn_fruit <- dtbn %>% 
  filter(str_detect(Food_code, '^6')) %>% 
  mutate(L2_grp = str_sub(Food_code, start = 1, end = 2)) %>% 
  group_by(mrn, fdrt, L2_grp) %>% 
  summarise(L2_total = sum(dehydrated_weight))


  
# get the mean of previous two days for every stool sample I'm currently using
stb <- meta


  
stb_pair <- stb %>%  
  select(mrn, sdrt) %>% 
  transmute(mrn = mrn,
            p1d = sdrt-1,
            p2d = sdrt-2) 
 
mean_p2d_l2_fruit_diet <-  function(mrn_, p1d_, p2d_){
  df = dtbn_fruit %>% 
    filter(mrn == mrn_) %>% 
    filter(fdrt %in% c(p1d_, p2d_  )) %>% 
    group_by(L2_grp) %>% 
    summarise(ave_L2 = sum(L2_total)/2)
  return(df)
}

mean_p2d_l2_fruit_df <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_l2_fruit_diet(mrn, p1d, p2d)
  }) %>% 
  set_names(stb %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid')  %>% 
  left_join(fruit2 %>% rename(L2_grp = Level.code), by  = 'L2_grp') %>% 
  select(-L2_grp ) %>% 
  spread('Main.food.description', 'ave_L2', fill = 0) %>% 
  right_join(meta, by = "sampleid") %>% 
  mutate(pid = str_glue('P{as.numeric(as.factor(mrn))}')) %>% 
  select(-mrn)

# visualize the sub group fruit intake
mean_p2d_l2_fruit_df %>% 
  select(Citrus_fruits_juices:Other_fruits) %>% 
  gather('group','value', Citrus_fruits_juices:Other_fruits) %>% 
  ggpubr::ggboxplot(x = 'group', y = 'value')

# the columns in this table 
mean_p2d_l2_fruit_df %>% 
  summary
#The Citrus_fruits_juices, Dried_fruits and Other_fruits are the three sub groups of fruits observed in the data and the value is the previous two days average of a collected stool sample
# the columns with fg_ are the food groups intake averaged in the previous two days
# intensity is the conditioning regimen intensity
# sdrt stands for the day relative to transplant of a stool sample collection
# EN, TPN and empirial refer to whether the patients had enteral nutrition of parenteral nutrition in the previous two days or had any empirical abx in the prior two days
# the pid is the anonymized patient ID
# there are 466 stool samples that have nonzero fruit intake in that window and the remaining ones didn't 

```

```{r}
mean_p2d_l2_fruit_df  %>% 
  write_csv('../data/cleaned_stool/036_all_samples_meta_p2d_L2_fruit_only.csv')
```

```{r}
# library(lmerTest)
# 
# # to make sure the columns are in right type
# fruitdat <- mean_p2d_l2_fruit_df %>% 
#   mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
#   mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
#   mutate(mrn = factor(mrn))
# 
# mod_fruit <-  lmer(log(simpson_reciprocal) ~ 
#               Citrus_fruits_juices+
#                Dried_fruits+
#                Other_fruits+
#                  fg_meat+
#                fg_milk+
#                #fg_oils+
#                 #fg_egg+ 
#                 fg_grain+
#                 fg_sweets+  
#                 #fg_legume+
#                 fg_veggie+
#                empirical + 
#                intensity + 
#                (1 | mrn) +
#                 (1 | timebin), REML = F, data = fruitdat )
# summary(mod_fruit)
```

## Summarize the fruits at each food code level

```{r}
each_fruit_code  <- dtbn %>% 
  filter(str_detect(Food_code, '^6')) %>% 
  distinct(Food_code, description) 

each_fruit_code %>% write_csv('../data/036_each_fruit_food_code_description.csv')
# %>% 
#   mutate(L3_grp = str_sub(Food_code, start = 1, end = 3))  %>% 
#   distinct(L3_grp)
#   left_join(fruit2 %>% rename(L2_grp = Level.code), by  = 'L2_grp') %>% 
#   arrange(L2_grp)

dtbn_fruit_code <- dtbn %>% 
  filter(str_detect(Food_code, '^6')) %>% 
  group_by(mrn, fdrt, Food_code) %>% 
  summarise(food_code_total = sum(dehydrated_weight))


mean_p2d_each_fruit_diet <-  function(mrn_, p1d_, p2d_){
  df = dtbn_fruit_code %>% 
    filter(mrn == mrn_) %>% 
    filter(fdrt %in% c(p1d_, p2d_  )) %>% 
    group_by(Food_code) %>% 
    summarise(ave_code = sum(food_code_total)/2)
  return(df)
}

mean_p2d_each_fruit_df <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_each_fruit_diet(mrn, p1d, p2d)
  }) %>% 
  set_names(stb %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid')

each_code <- mean_p2d_each_fruit_df %>% 
  spread('Food_code', 'ave_code', fill = 0) %>% 
  right_join(meta, by = "sampleid") %>% 
  mutate(pid = str_glue('P{as.numeric(as.factor(mrn))}')) %>% 
  select(-mrn)

each_code %>% write_csv('../data/036_all_samples_meta_p2d_each_fruit_food_code.csv')
```

## L3

```{r}
dtbn_fruit_l3 <- dtbn %>% 
  filter(str_detect(Food_code, '^6')) %>% 
  mutate(L3_grp = str_sub(Food_code, start = 1, end = 3)) %>% 
  group_by(mrn, fdrt, L3_grp) %>% 
  summarise(l3_total = sum(dehydrated_weight))


mean_p2d_l3_fruit_diet <-  function(mrn_, p1d_, p2d_){
  df = dtbn_fruit_l3 %>% 
    filter(mrn == mrn_) %>% 
    filter(fdrt %in% c(p1d_, p2d_  )) %>% 
    group_by(L3_grp) %>% 
    summarise(ave_l3 = sum(l3_total)/2)
  return(df)
}

mean_p2d_l3_fruit_df <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_l3_fruit_diet(mrn, p1d, p2d)
  }) %>% 
  set_names(stb %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid')

fruit3 <- read_tsv('../data/source/NodeLabelsMCT.txt', col_types = 'cc')  %>% 
  filter(str_detect(Level.code, '^6')) %>% 
  filter(str_length(Level.code) == 3)

each_l3 <- mean_p2d_l3_fruit_df %>% 
  left_join(fruit3 %>% rename(L3_grp = Level.code), by  = 'L3_grp') %>% 
  select(-L3_grp ) %>% 

  spread('Main.food.description', 'ave_l3', fill = 0) %>% 
  right_join(meta, by = "sampleid") %>% 
  mutate(pid = str_glue('P{as.numeric(as.factor(mrn))}')) %>% 
  select(-mrn)

each_l3 %>% write_csv('../data/036_all_samples_meta_p2d_each_fruit_L3_level.csv')
```

