---
title: "Start from 97 corrected dtb"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
```

Start from the **all_97_cor.csv**

```{r}
combined <- read_csv('../data/!question/all_97_cor.csv') %>% 
  rename(Protein_g = Proteing_g) %>% 
  mutate(Sodium_g = round(Sodium_mg/1000, 3)) %>% 
  select(-Sodium_mg)

all_code <- read_csv('../data/cleaned_diet_data/all_food_nsc_with_code_FINAL.csv') %>% 
  select(-FNDDS.Main.Food.Description)

```

## Foods with zero calorie and their gram weight

```{r}
cal0_peter <- read_excel('../data/cal_0_food_nsc_all_with_unit_Peter.xls')

# the things that should be removed from combined
na_rm <- cal0_peter %>% 
  filter(`gram weight` == 'NA') %>% 
  distinct(Food_NSC) %>% 
  pull(Food_NSC)

combined2 <- combined %>% 
  filter(! Food_NSC %in% na_rm)

cal0_peter_items <- cal0_peter %>% 
  filter(`gram weight` != 'NA')  %>% 
  rename(total_weight = `gram weight`) %>% 
  mutate(total_weight = as.numeric(total_weight)) %>% 
  distinct(Food_NSC) %>% 
  pull(Food_NSC)

cal0_peter_clean <- cal0_peter %>% 
  filter(`gram weight` != 'NA')  %>% 
  rename(total_weight = `gram weight`) %>% 
  mutate(total_weight = as.numeric(total_weight)) %>% 
  distinct()

cal0_split <- combined2 %>% 
  split(.$Food_NSC %in% cal0_peter_items)

cal0_join_with_other <- cal0_split %>% 
  pluck('TRUE') %>%  
  left_join(cal0_peter_clean) %>% 
  filter(is.na(total_weight))  %>% 
  select(-total_weight)


# for the stuff in the above result that is NA in the gram weight goddamn messed up calories for the food! do a calculation instead
cal0_weight <- cal0_split %>% 
  pluck('TRUE') %>%  
  left_join(cal0_peter_clean) %>% 
  filter(!is.na(total_weight))  %>% 
  # join by the food code
  left_join(all_code, by = 'Food_NSC')

# most of the cal!=0 stuff that needs the fndds conversion
other_need <- bind_rows(
  cal0_split %>% pluck('FALSE'),
  cal0_join_with_other
) %>% 
  # join by the food code
  left_join(all_code, by = 'Food_NSC')
```


## Get the food code for the items

## Get the dehydrated weight for the non zero calorie foods

## Convert the date to fdrt

## Add the EN and TPN data

## Check the date range and finalize the data




