---
title: "For abstract"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
library(tidyverse)
library(ggpubr)
```

## import data

```{r}
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg11.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = as.factor(mrn))
```

## visualize the p2d meta with drt

```{r}
library(randomcoloR)
set.seed(112)
n <- 10
palette <- distinctColorPalette(n)
#pie(rep(1, n), col=palette)
set2_palette <- 

# without EN
fg <- meta %>% 
  select(sdrt, starts_with('fg')) %>% 
  select(-fg_EN) %>% 
  gather('term', 'value', names(.)[2]:names(.)[ncol(.)]) %>% 
  ggscatter(x = 'sdrt',y = 'value', color = 'term', palette = palette, alpha = 0.3,
            add = "loess", add.params = list(size = 3),
            xlab = '', ylab = 'Gram weight') + 
  scale_y_sqrt() +
  theme(legend.position = 'right') +
  ggsave('../figs/p2d_meta_fg_sdrt.pdf', width = 9, height = 9)


# with EN
# palette11 <- distinctColorPalette(11)
# meta %>% 
#   select(sdrt, starts_with('fg')) %>% 
#   #select(-fg_EN) %>% 
#   gather('term', 'value', names(.)[2]:names(.)[ncol(.)]) %>% 
#   ggscatter(x = 'sdrt',y = 'value', color = 'term', palette = palette11, alpha = 0.3,
#             add = "loess", add.params = list(size = 3),
#             #xlab = 'Day relative to transplant', 
#             ylab = 'Gram weight') + 
#   scale_y_sqrt() +
#   ggsave('../figs/p2d_meta_fg_sdrt_with_EN.pdf', width = 9, height = 9)

```

```{r}
# the stool diversity change over time
stool <- meta %>% 
  mutate(log_div = log(simpson_reciprocal)) %>% 
  ggscatter(x = 'sdrt', y = 'log_div', alpha = 0.3, color = 'intensity',xlab = '',
            ylab = 'log(diversity)',
            add = 'loess', add.params = list(size = 3)) + ggsci::scale_color_uchicago()+
  theme(legend.position = 'right')
stool
```


```{r}
stool_empirical <-   meta %>% 
  mutate(log_div = log(simpson_reciprocal)) %>% 
  ggscatter(x = 'sdrt', y = 'log_div', alpha = 0.3, color = 'empirical', xlab = 'Day relative to transplant',
            ylab = 'log(diversity)',
            add = 'loess', add.params = list(size = 3)) + ggsci::scale_color_startrek() +
  theme(legend.position = 'right')

stool_empirical 
```


### combine plots

```{r}
library(grid)
library(cowplot)
g <- plot_grid(fg, stool,  stool_empirical, 
          nrow = 3, 
          align = 'hv',
          rel_heights = c(5, 2, 2),
          axis = 'b') +
  ggsave('../figs/p2d_meta_fg_sdrt_combined.pdf', width = 8, height = 8)


```

## color the stool beta with stool alpha

```{r}
# the unifrac pcoa colored by fruit consumption
source('~/db_connect_simple.R')
connect_database(config_file = '~/dbConfig.txt')
get_table_from_database_predefined_filter('asv_counts_ag') 
ANNOT <- get_table_from_database('asv_annotation_blast_ag')

cts <- asv_counts_ag %>% 
  filter(sampleid %in% meta$sampleid) %>% 
  select(asv_key, sampleid, count) 

annot <- ANNOT %>% 
  filter(asv_key %in% cts$asv_key) %>% 
  mutate(ordr =  if_else(ordr == '', str_glue('of_class_{class}'), ordr),
         family =  if_else(family == '', str_glue('of_order_{ordr}'), family),
         genus =  if_else(genus == '', str_glue('of_family_{family}'), genus),
         species =  if_else(species == '', str_glue('of_genus_{genus}'), species)) %>% 
  mutate(taxa_genus = str_glue('k__{kingdom}|p__{phylum}|c__{class}|o__{ordr}|f__{family}|g__{genus}'))

cts_genus <- cts %>% 
  left_join(annot %>%  select(asv_key, taxa_genus), by  = 'asv_key') %>% 
  select(-asv_key) %>% 
  group_by(sampleid, taxa_genus) %>% 
  summarise(cnt = sum(count)) %>% 
  # get the total count from the db to calculate the relab
  left_join(asv_counts_ag %>% distinct(sampleid,count_total ), by = 'sampleid') %>% 
  mutate(relab = cnt/count_total) %>% 
  select(sampleid, taxa_genus, relab) 

cts_ma <- cts_genus %>% 
  spread(key = 'sampleid', value = 'relab', fill = 0) %>% 
  column_to_rownames('taxa_genus') %>% 
  as.matrix()

num_thre <- floor(ncol(cts_ma) * 0.1)

cts_ma_fil <- cts_ma[rowSums(cts_ma >= 0.0001) >= num_thre, ]

# for vegan distance the sampleid needs to be in the rowname
cts_genus_fil <- cts_ma_fil %>% 
  as.data.frame() %>% 
  rownames_to_column('taxa_genus') %>% 
  gather('sampleid', 'relab', names(.)[2]:names(.)[ncol(.)]) %>% 
  spread(key = 'taxa_genus', value = 'relab') %>% 
  column_to_rownames('sampleid')

library(vegan)
cts_genus_fil_dist <- vegdist(cts_genus_fil, method = 'bray')

cts_genus_fil_pcoa <- cmdscale(cts_genus_fil_dist, k = 2) 

cts_genus_fil_pcoa %>% 
    as.data.frame() %>% 
    rownames_to_column('sampleid') %>% 
    full_join(meta, by = 'sampleid') %>% 
    ggscatter(x = 'V1', y = 'V2', color =  'simpson_reciprocal', alpha = 0.3) +
    scale_color_viridis() +
    labs(x = 'PCo 1', y = 'PCo 2', title = '') 

# ok forget about it the pattern isn't as clear as when I do coloring the diet beta with diet alpha
```





## Just stack the diet alpha and stool alpha together 

Tho the diet table values changed, the foods did not change, so the diet faith alpha should not change.

```{r}
faith <- read_tsv('../data/cleaned_diet_data/FINAL_97_faith_pd/alpha-diversity.tsv') %>% 
  separate(X1, into = c('mrn', 'fdrt'), sep = 'd', convert = T)  %>% 
  mutate(mrn = as.numeric(str_replace(mrn, 'P',''))) %>% 
  left_join(ptb %>% select(mrn, source, intensity), by = 'mrn')

diet_alpha <- faith %>% 
  ggscatter('fdrt', 'faith_pd', 
             alpha = 0.8,
            color = 'chartreuse4',
            #size = 1,
            ylab = 'Food alpha diversity', 
            xlab = '',
            title = '',
            add = "loess", 
            add.params = list(color = "darkgreen", fill = "darkgray", size = 2), 
            conf.int = TRUE) +
  xlim(-10, 50)+
  scale_x_continuous(breaks = seq(-10, 50, 10))

# combine with stool alpha diversity
stool_alpha <- meta %>% 
  mutate(log_div = log(simpson_reciprocal)) %>% 
  ggscatter(x = 'sdrt', y = 'simpson_reciprocal', alpha = 0.8, 
            xlab = 'Day relative to transplant',
            ylab = 'Microbiome alpha diversity',
            add = "loess", color = 'darkgoldenrod',
            add.params = list(color = "darkgoldenrod4", fill = "darkgray", size = 2), 
            conf.int = TRUE) +
  xlim(-10, 50) +
  scale_x_continuous(breaks = seq(-10, 50, 10))
  

# combine them
alpha <- plot_grid(diet_alpha, stool_alpha, 
          nrow = 2, 
          align = 'hv',
          rel_heights = c(1,1),
          axis = 'b') 
alpha 
```

## fruit and ndrink boxplot and sdrt

```{r}
box2 <- meta %>% 
  select(fg_fruit, fg_ndrink, fg_sweets, timebin)

box2 %>% 
  group_by(timebin) %>% 
  summarise(median_frui = median(fg_fruit),
            median_fg_ndrink = median(fg_ndrink))
```


```{r}
grp2 <- box2 %>%  
  gather('grp', 'gram', fg_fruit:fg_sweets) %>% 
  ggboxplot(x = 'timebin', y = 'gram', color = 'grp', add = 'jitter', palette = 'nejm', 
            add.params = list(alpha = 0.4),
            title = "Food group intake and fecal microbiome alpha diversity's change\nover weeks") +
  scale_y_sqrt() +
  facet_grid(grp~., scales = 'free_y') +
  stat_summary(fun.y = median, geom = 'line', aes(group = grp, colour =grp)) +
  geom_text(aes(x = timebin[1], y = 140, label = grp)) +
  theme(strip.background = element_blank(),
   strip.text.y = element_blank(),
   legend.position = "none")
grp2
```


```{r}
# I can try putting the diversity into box in the timebins too
food_box <- faith %>% 
  mutate(timebin = cut_width(fdrt, 7, boundary=0, closed = 'left')) %>% 
  ggboxplot(x = 'timebin', y = 'faith_pd', add = 'jitter', color = 'darkgreen', alpha = 0.6) +
  scale_y_sqrt()+
  scale_x_discrete(limits = c("[-14,-7)", "[-7,0)" ,  "[0,7)"  ,  "[7,14)" ,  "[14,21)"  ,"[21,28)" , "[28,35)" , "[35,42)" , "[42,49]" ,'(49,56]' ))

stool_box <- meta %>% 
  ggboxplot(x = 'timebin', y = 'simpson_reciprocal', add = 'jitter', color = 'darkgoldenrod4', alpha = 0.6,
            add.params = list(alpha = 0.4)) +
  scale_y_sqrt()+
  stat_summary(fun = median, geom = 'line', group = 1, color = 'darkgoldenrod4')

box_combined <- plot_grid(grp2, stool_box, 
          nrow = 2, 
          align = 'hv',
          rel_heights = c(3,1),
          
          axis = 'lb')  +
  ggsave('../figs/three_box.pdf', width = 8, height = 10)


```

```{r}
allfig <- plot_grid(box_combined, pos_interval, 
          nrow = 1, 
          align = 'hv',
          rel_heights = c(1,1),
          labels = "AUTO",
          axis = 'b')  +
  ggsave('../figs/all_fig.pdf', width = 15, height = 7)
```


## some simple summary stats

```{r}
summary(ptb$age)

ptb %>% 
  count(intensity) %>% 
  mutate(perc = round(n/97*100, 0))
```

```{r}
dtbn %>% 
  distinct(mrn, Meal, fdrt) %>% 
  arrange(mrn, fdrt, Meal)
```

```{r}
# daily consumption of the nutrients average of the patients?
ave_day <- dtbn %>% 
  select(mrn, fdrt, ends_with('_g')) %>% 
  gather('type', 'value', Protein_g:Sodium_g) %>% 
  group_by(mrn, fdrt, type) %>% 
  summarise(total_day = sum(value)) %>% 
  group_by(type) %>% 
  summarise(ave_pt = mean(total_day))


p2d_ave <- meta %>% 
  select(starts_with('fg')) %>% 
  summarise_all(mean) %>% 
  gather('key', 'value')
```

