---
title: "continue"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
```

## check the pairwise correlation between the predicting variables

```{r}
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg11.csv')	%>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = as.factor(mrn))
```

```{r}
dat <- meta %>% 
  select(-mrn, -sampleid, -sdrt) %>% 
  #mutate(fg_sum = rowSums(.[1:11])) %>% 
  mutate_if(is.double, ~ (scale(.) %>% as.vector)) # standardize all the numeric values (the fg group and the diversity)


library(ggcorrplot)
model.matrix(~0+., data=dat) %>% 
  cor(use="pairwise.complete.obs") %>% 
  ggcorrplot(show.diag = F, type="lower", lab=TRUE, lab_size=2) +
  ggsave('../figs/pairwise.complete.obs.pdf', width = 9, height = 8)
```

## add the faith diet diversity into the model

```{r}
# load the mean p2d diet faith df
mean_p2d_ffaith_df <- read_csv('../data/cleaned_stool/mean_p2d_diet_faith.csv')

Meta <- meta %>% 
  full_join(mean_p2d_ffaith_df) %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = as.factor(mrn))
```


```{r}
library(lmerTest)     
mod_faith <-  lmer(log(simpson_reciprocal) ~ 
              fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
                fg_ndrink+
                fg_EN+
                ave_ffaith+
               empirical +  
               intensity + 
                TPN +
               (1 | mrn) +
                (1 | timebin), REML = F, data = Meta )
summary(mod_faith) 
```

```{r}
brm_faith  <- brm(log(simpson_reciprocal)  ~ 
              fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
                fg_ndrink+
                fg_EN+
                ave_ffaith+
               empirical + 
               intensity + 
                 TPN +
               (1 | mrn) +
                (1 | timebin),  
              data = Meta, 
              warmup = 1000, iter = 3000, 
              cores = 8, chains = 2, 
              seed = 123) 

posterior_model <- posterior_samples(brm_faith) %>% 
  select(starts_with('b')) %>% 
  select(-b_Intercept) %>% 
  gather('item', 'value') %>% 
  group_by(item) %>% 
  mutate(meanperitem = mean(value))%>%
  ungroup()

posterior_model_vars <- posterior_model %>% 
  filter(str_detect(item, '_fg_') | item == 'b_ave_ffaith')

ggplot()+
  ggridges::geom_density_ridges(data  = posterior_model_vars, 
                                aes(x      = value,
                                    y      = reorder(as.factor(item), meanperitem),
                                    height = ..density..),
                                scale = 1.5, size = 0.25,
                                alpha = 0.6) +
  geom_vline(xintercept = 0, col = "red") +
  #scale_x_continuous(limits = c(-0.02,0.03)) +
  labs(y = 'Food groups',
       title = 'Posterior distribution of regression coefficient for food groups') +
  theme(axis.text.y = element_text(size=20)) +
  ggthemes::theme_tufte()
```

```{r}
mod_faith_ <-  lmer(log(simpson_reciprocal) ~ 
             ave_ffaith+
               empirical +  
               intensity + 
                TPN + 
               (1 | mrn) +
                (1 | timebin), REML = F, data = Meta )
summary(mod_faith_) 
```

## use the enterococcus domination as the response

```{r}
dat <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg11.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(empirical = factor(empirical, levels = c('FALSE','TRUE')))

# look at the genus level
cts <- read_csv('../data/cleaned_stool/ALL_stool_samples_genus_counts.csv') %>% 
  filter(sampleid %in% dat$sampleid) %>% 
  dplyr::select(sampleid, taxa_genus, relab) %>% 
  mutate(taxa_genus = str_extract(taxa_genus, 'g__.+$'))

entercts <- cts %>% 
  filter(taxa_genus == 'g__Enterococcus') %>% 
  mutate(enterodom = if_else(relab > 0.3, T, F)) %>% 
  rename(enterorelab = relab) %>% 
  select(-taxa_genus)

All <- Meta %>% 
  full_join(entercts)
```

```{r}
model_enterodom  <- brm( enterodom  ~ 
              fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
                fg_ndrink+
                fg_EN+
               empirical + 
               intensity + 
                 TPN +
               (1 | mrn) +
                (1 | timebin),  
              data = All, 
              family = bernoulli(), 
              warmup = 1000, iter = 3000, 
              cores = 8, chains = 2, 
              seed = 123) 
plot(model_enterodom)
draw_ridge_density_fg(model_enterodom)
stanplot(model_enterodom, type = "trace")
```

```{r}
mod_entero <-  glmer(enterodom ~ 
              fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
                fg_ndrink+
                fg_EN+
               empirical +  
               intensity + 
                TPN +
               (1 | mrn) +
                (1 | timebin),family = binomial, data = All )
print(mod_entero, corr = FALSE)
se <- sqrt(diag(vcov(mod_entero)))
(tab <- cbind(Est = fixef(mod_entero), LL = fixef(mod_entero) - 1.96 * se, UL = fixef(mod_entero) + 1.96 *
    se))
exp(tab)# odd ratio
# OR > 1 indicates increased occurrences of an event
```

```{r}
oddr <- exp(tab) %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  filter(rowname != '(Intercept)') %>% 
  filter(str_detect(rowname, 'fg'))

oddr %>% 
  arrange(Est) %>% 
  ggscatter(x = 'rowname', y = 'Est', color = 'red',
              ylab = 'Odds ratio',
              title = 'Enterococcus domination as outcome',
              xlab = '') +
    geom_errorbar(aes( ymin  = LL,
                     ymax  = UL,
                     width = 0.25))+
  coord_flip() +
  geom_hline(yintercept = 1, col = "firebrick", linetype = 'dashed') +
  scale_y_log10()
```

## use the GVHD Yes and No as the outcome 

```{r}
# get from the patients allo table whether the patients have gvhd
source('~/db_connect_simple.R')
connect_database(config_file = '~/dbConfig.txt')

get_table_from_database('patient_allo_ag')

pt_gvhd <- patient_allo_ag %>% 
  filter(mrn %in% All$mrn) %>% 
  arrange(hct) %>% 
  distinct(mrn, .keep_all = T) %>% 
  distinct(mrn, gvhd) %>% 
  filter(gvhd != 'N/E')

all_gvhd <- All %>% 
  inner_join(pt_gvhd) %>% 
  mutate(gvhd = if_else(gvhd == 'Y', T, F))

all_gvhd %>% 
  count(gvhd)

```

```{r}
model_gvhd  <- brm( gvhd  ~ 
              fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
                fg_ndrink+
                fg_EN+
               empirical + 
               intensity + 
                 TPN +
               (1 | mrn) +
                (1 | timebin),  
              data = all_gvhd, 
              family = bernoulli(), 
              warmup = 10000, iter = 20000, 
              cores = 32, chains = 2, 
              seed = 123) 

stanplot(model_gvhd, type = "trace")
draw_ridge_density_fg(model_gvhd)

modelposterior <- as.mcmc(model_gvhd) # with the as.mcmc() command we can use all the CODA package convergence statistics and plotting options
coda::gelman.diag(modelposterior[, 1:4])
#The Gelman-Rubin Diagnostic shows the PSRF values (using the within and between chain variability). You should look at the Upper CI/Upper limit, which are all should be close to 1. If they aren’t close to 1, you should use more iterations. Note: The Gelman and Rubin diagnostic is also automatically given in the summary of brms under the column Rhat


coda::geweke.diag(modelposterior[, 1:4])
#The Geweke Diagnostic shows the z-scores for a test of equality of means between the first and last parts of each chain, which should be <1.96. A separate statistic is calculated for each variable in each chain. In this way it check whether a chain has stabalized. If this is not the case, you should increase the number of iterations. In the plots you should check how often values exceed the boundary lines of the z-scores. Scores above 1.96 or below -1.96 mean that the two portions of the chain significantly differ and full chain convergence was not obtained.
geweke.plot(modelposterior[, 1:4])


# still need more samples to converge possibly 
```

## use the faith diversity and calories as predictors

```{r}
final <- All %>% 
  full_join(mean_p2d_df_cal) %>% 
  full_join(mean_p2d_ffaith_df)

model_two  <- brm( log(simpson_reciprocal)  ~ 
            ave_ffaith +
              ave_cal+
               empirical + 
               intensity + 
                 TPN +
               (1 | mrn) +
                (1 | timebin),  
              data = final, 
              warmup = 1000, iter = 3000, 
              cores = 16, chains = 2, 
              seed = 123) 


posterior_model <- posterior_samples(model_two) %>% 
    select(starts_with('b')) %>% 
    select(-b_Intercept) %>% 
    gather('item', 'value') %>% 
    group_by(item) %>% 
    mutate(meanperitem = mean(value))%>%
    ungroup()
  
ggplot()+
  ggridges::geom_density_ridges(data  = posterior_model, 
                                aes(x      = value,
                                    y      = reorder(as.factor(item), meanperitem),
                                    height = ..density..),
                                scale = 1.5, size = 0.25,
                                alpha = 0.6) +
  geom_vline(xintercept = 0, col = "red") +
  #scale_x_continuous(limits = c(-0.02,0.03)) +
  labs(y = '',
       title = '') +
  #theme(axis.text.y = element_text(size=40)) +
  ggthemes::theme_tufte() +
  theme(axis.text.y = element_text(size=30),
        axis.text.x = element_text(size=15))

```
 
 