---
title: "brm model coeff heatmap with food and genera"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Response: 48 genera 

```{r}
library(tidyverse)
library(brms)
library(ggpubr)
ncores <- parallel::detectCores()
```

## load tables

```{r}
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = factor(mrn)) %>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100) %>% 
  mutate(inten_non = if_else(intensity == 'nonablative', 1, 0),
         inten_ab = if_else(intensity == 'ablative', 1, 0),
         inten_re = if_else(intensity == 'reduced', 1, 0))

meta %>% 
  summary()
```


```{r}
cts <- read_csv('../data/cleaned_stool/ALL_stool_samples_genus_counts.csv') %>% 
  filter(sampleid %in% meta$sampleid) %>% 
  dplyr::select(sampleid, genus, relab) 


blautia_mod <- Blautia ~ 1 +
                fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               inten_non + inten_ab + inten_re +
                empirical+
                TPN+
                EN+ 
               (1 | mrn) +
                (1 | timebin)


priors <- c(# for the food group variables
            prior(normal(0, 1.2), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_veggie"),
            # for the TPN 
            prior(normal(0, 0.1), class = 'b', coef = "TPNTRUE"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "ENTRUE"),
            # for the empirical 
            prior(normal(0, 0.5), class = 'b', coef = "empiricalTRUE"),
            # for the intensity 
            prior(normal(0, 0.1), class = 'b', coef = "inten_re"),
            prior(normal(0, 0.1), class = 'b', coef = "inten_ab"),
            prior(normal(0, 0.1), class = 'b', coef = "inten_non"),
            prior(normal(-3, 0.4), class = 'Intercept'))

blautia_cts <-  cts %>% 
  filter(genus %in% c('Blautia')) %>% 
  mutate(relablog = log10(relab + 2*10^-6)) %>% 
  dplyr::select(-relab) %>% 
  spread(key = 'genus', value = 'relablog') 
All <- blautia_cts %>% 
  inner_join(meta)


model_blautia <- brm( blautia_mod,  
              data = All, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
              seed = 123, sample_prior = T) 

summary(model_blautia)
post_samples  <- posterior_samples(model_blautia, '^b_')
key <- read_csv('../data/cleaned_diet_data/food_group_color_key.csv', col_types = 'ccccc') 
post_coeff <- post_samples %>% 
  select(starts_with('b_fg')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item = str_replace(item, 'b_fg_','')) %>% 
   mutate(fgrp1 = case_when(
    item ==  'milk' ~ '1',
    item == 'meat' ~ '2',
    item ==  'egg' ~ '3',
    item ==  'legume' ~ '4',
    item == 'grain' ~ '5',
    item == 'fruit' ~ '6',
    item == 'veggie' ~ '7',
    item ==  'oils' ~ '8', 
    item ==  'sweets' ~ '9'
  ))  %>% 
  left_join(key) %>% 
  mutate(fdesc = str_replace_all(fdesc, '_',' ')) %>% 
  mutate(fdesc = str_wrap(fdesc, width = 28, indent = 2, exdent = 0)) %>% 
  mutate(fdesc = str_replace(fdesc, 'and','&')) %>% 
  left_join(key %>% select(fgrp1, color, shortname))  %>% 
  mutate(shortname = fct_reorder(shortname, coeff, .fun=median, .desc = F)) 

fg_colors <- post_coeff %>% 
  distinct(shortname, color) %>% 
  select(shortname, color) %>% 
  deframe()
# plotting the forest
post_coeff %>% 
  ggplot(aes(x = coeff, y = shortname, col = shortname)) +
  stat_pointinterval(.width = c(.66, .95)) +
  geom_vline(xintercept = 0, col = 'red', linetype = 'dashed') +
  labs(x = 'Regression coefficients',
       y = '') +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_manual(values = fg_colors) +
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10),
        aspect.ratio=1)       
```


```{r}
mean_fg <-  meta %>% 
  select(starts_with('fg')) %>% 
  summarise_all(funs(mean))

samples_prior <- prior_samples(model_old)

ave_each_fg <- samples_prior %>% 
  mutate(mean_fg = Intercept + 
           b_fg_fruit*mean_fg$fg_fruit +
           b_fg_meat*mean_fg$fg_meat + 
           b_fg_milk*mean_fg$fg_milk + 
           #b_fg_oils*mean_fg$fg_oils + 
           #b_fg_egg*mean_fg$fg_egg + 
           b_fg_grain*mean_fg$fg_grain +
           b_fg_sweets*mean_fg$fg_sweets +
           #b_fg_legume*mean_fg$fg_legume +
           b_fg_veggie*mean_fg$fg_veggie +
           b_inten_re +
           b_empiF +
           b_tpnF +
           b_enF) %>% 
  select(mean_fg) %>% 
  mutate(grp = 'ave_each') %>% 
  rename(prior_res = mean_fg) %>% 
  select(grp, prior_res)

max_sweets <- samples_prior %>% 
  mutate(mean_fg = Intercept + 
           b_fg_fruit*mean_fg$fg_fruit +
           b_fg_meat*mean_fg$fg_meat + 
           b_fg_milk*mean_fg$fg_milk + 
           #b_fg_oils*mean_fg$fg_oils + 
           #b_fg_egg*mean_fg$fg_egg + 
           b_fg_grain*mean_fg$fg_grain +
           b_fg_sweets*max_fg$fg_sweets +
           #b_fg_legume*mean_fg$fg_legume +
           b_fg_veggie*mean_fg$fg_veggie +
           b_inten_re +
           b_empiF +
           b_tpnF +
           b_enF) %>% 
  select(mean_fg) %>% 
  mutate(grp = 'max_sweets') %>% 
  rename(prior_res = mean_fg) %>% 
  select(grp, prior_res)

bind_rows(ave_each_fg, max_sweets) %>% 
  gghistogram(x = 'prior_res', fill = 'grp')

ave_each_fg %>% 
  count(prior_res >-5 & prior_res<0) %>% 
  mutate(perc = n/4000*100)

```

## filter on the food consumption and the genera

```{r}
thre <- seq(0.0001, 0.001, 0.0001)
thre %>% 
  set_names(thre) %>% 
  map_dfr(function(num){
    cts %>% 
    group_by(genus) %>% 
    count(relab > num) %>% 
    rename(criteria = names(.)[2]) %>% 
    filter(criteria == 'TRUE') %>% 
    arrange(-n) %>% 
    filter(genus != 'NA') %>% 
    mutate(perc = round(n/nrow(meta)*100, 0)) %>% 
    filter(perc > 10) %>% 
      nrow
  }) %>% 
  gather('thre', 'num')

# i think I am happy with 48 genera left after filtering 
```

```{r}
target_genera <-  cts %>% 
  group_by(genus) %>% 
  count(relab > 0.001) %>% 
  rename(criteria = names(.)[2]) %>% 
  filter(criteria == 'TRUE') %>% 
  arrange(-n) %>% 
  filter(genus != 'NA') %>% 
  mutate(perc = round(n/nrow(meta)*100, 0)) %>% 
  filter(perc > 10) %>% 
  pull(genus)
```

```{r}
domcts <- cts %>% 
  filter(genus %in% target_genera) %>% 
  mutate(relablog = log10(relab + 2*10^-6)) %>% 
  dplyr::select(-relab) %>% 
  spread(key = 'genus', value = 'relablog', fill = 0)

All <- domcts %>% 
  full_join(meta, by = "sampleid")

domcts_narrow <- cts %>% 
  filter(genus %in% target_genera) %>% 
  mutate(relablog = log10(relab + 2*10^-6)) %>% 
  dplyr::select(-relab)

range(domcts_narrow$relablog)
domcts_narrow %>% 
ggboxplot(y = 'relablog', facet.by = 'genus') +
  theme_cleveland()
```
 

```{r}
# also need to filter on the food somehow 
fg <- meta %>% 
  select(starts_with('fg')) %>% 
  gather() %>% 
  mutate(key = fct_reorder(key, value, .fun=median, .desc = T)) 

fg %>% 
  ggboxplot(x = 'key', y = 'value') +
  scale_y_sqrt()

# decided: median intake > 0 

remove_fg <- fg %>% 
  group_by(key) %>% 
  summarise(median_intake = median(value)) %>% 
  arrange(median_intake)  %>% 
  filter(median_intake == 0) %>% 
  mutate(key = as.character(key)) %>% 
  pull(key)
  

final <- All %>% 
  select(-all_of(remove_fg))

final %>% 
  write_csv('../data/cleaned_stool/filtered_meta_genera.csv')


```

## using all the target genera as the outcome

```{r}
ret <- target_genera %>% 
  set_names(target_genera) %>% 
  map(function(genus) {
    mod =  brm( as.formula(str_glue('{genus}  ~ 
               fg_fruit+
               fg_meat+
               fg_milk+
               #fg_oils+
                #fg_egg+ 
                fg_grain+
                fg_sweets+  
                #fg_legume+
                fg_veggie+
               empirical +  
               intensity + 
                TPN +
                EN +
               (1 | mrn) +
                (1 | timebin)')),  
              data = final, 
              warmup = 1000, iter = 3000, 
              cores = 16, chains = 2, 
              seed = 123) 
    
    res = posterior_samples(mod) %>% 
      select(starts_with('b')) %>% 
      gather('item', 'value') %>% 
        filter(str_detect(item, '_fg_')) %>% 
      group_by(item) %>% 
      summarise(meanperitem = mean(value),
                q2.5 = quantile(value, probs = 0.025),
                q97.5 = quantile(value, probs = 0.975))%>%
      ungroup()
    
    return(res)
  })
```

```{r}
# df work
retdf <- ret %>% 
  bind_rows(.id = 'genus') %>% 
  mutate(sig = if_else(q97.5 < 0 | q2.5 > 0, T, F)) %>% 
  mutate(item = str_replace(item, 'b_fg_','')) %>% 
  mutate(mark = if_else(sig == T, '*',''))

range(retdf$meanperitem)

retdf_matrix <- retdf %>% 
  select(genus, item, meanperitem) %>% 
  spread('item', 'meanperitem') %>% 
  column_to_rownames('genus') %>% 
  as.matrix()

library(pheatmap)
pheatmap(
  retdf_matrix,
  #annotation_col = annot,
  show_rownames = TRUE,
  show_colnames = TRUE,
  filename = '../figs/heatmap_47_genera.pdf',
  height = 10,
  width = 7,
  display_numbers = T,
  number_format = "%.3f",
  
  #cluster_rows =F,
  #cluster_cols=F
)
```

```{r}
ggplot(retdf, aes(x = item, y = genus)) +
  geom_tile(aes(fill = meanperitem)) +
  geom_text(aes(label = round(meanperitem, 3))) +
  geom_text(aes(label = mark, x = item,y =  genus),
           nudge_y = -0.3, nudge_x = -0.4,size = 8) +
  # As our values are continuous, we'll use scale_fill_continuous instead of scale_fill_manual
  scale_fill_continuous(low = "violetred", high = "aquamarine") +
  ggsave('../figs/heatmap_47_genera_ggplot.pdf')
```

