---
title: "for tct figures"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
```

```{r}
ptb <- read_csv('../data/cleaned_patients/diet_patients_97.csv')

meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) 

faith <- read_tsv('../data/cleaned_diet_data/FINAL_97_faith_pd/alpha-diversity.tsv') %>% 
  separate(X1, into = c('mrn', 'fdrt'), sep = 'd', convert = T)  %>% 
  mutate(mrn = as.numeric(str_replace(mrn, 'P',''))) 
```

```{r}
# make the second row of th figure 
dat <- read_csv('../data/diet_pt_daily_cal_and_faith.csv')


alpha_val <- 0.1
cal_ <- dat %>% 
  ggscatter(x = 'fdrt', y = 'cal', alpha = alpha_val, 
            xlab = 'Day relative to HCT',
            ylab = 'Caloric intake',
            add = "loess", color = 'maroon',
            add.params = list(color = "brown", fill = "darkgray", size = 2), 
            conf.int = TRUE) +
  xlim(-10, 50) +
  scale_x_continuous(breaks = seq(-10, 50, 10)) + theme(aspect.ratio=1)
cal_
```


```{r}
cal_split <- dat %>% 
  ggscatter(x = 'fdrt', y = 'cal', alpha = alpha_val, 
            color = 'intensity', palette = 'lancet',
            xlab = 'Day relative to HCT',
            ylab = 'Caloric intake',
            add = "loess", 
            conf.int = TRUE) +
  xlim(-10, 50) +
  theme(legend.position = 'none') + 
  scale_x_continuous(breaks = seq(-10, 50, 10)) + theme(aspect.ratio=1)
cal_split
```

```{r}
diet_alpha <- faith %>% 
  ggscatter('fdrt', 'faith_pd', 
             alpha = alpha_val,
            color = 'forestgreen',
            #size = 1,
            ylab = 'Diet alpha diversity', 
            xlab = 'Day relative to HCT',
            title = '',
            add = "loess", 
            add.params = list(color = "darkgreen", fill = "darkgray", size = 2), 
            conf.int = TRUE) +
  xlim(-10, 50)+
  scale_x_continuous(breaks = seq(-10, 50, 10)) +
  #scale_color_gradient2(midpoint = mid, low = "black", mid = "cornflowerblue", high = "red", space = "Lab", name = 'Diet\nalpha\ndiversity' )+
  theme(legend.position = c(20,2000)) + theme(aspect.ratio=1)
diet_alpha
```

```{r}
faith_split <- dat %>% 
  ggscatter('fdrt', 'faith_pd', 
             alpha = alpha_val,
            color = 'intensity', palette = 'lancet',
            #size = 1,
            ylab = 'Diet alpha diversity', 
            xlab = 'Day relative to HCT',
            title = '',
            add = "loess", 
            conf.int = TRUE) +
  xlim(-10, 50)+
  scale_x_continuous(breaks = seq(-10, 50, 10)) +
  theme(legend.position = 'none') + 
  theme(aspect.ratio=1)
faith_split
```

```{r}
stool_alpha <- meta %>% 
  mutate(log_div = log(simpson_reciprocal)) %>% 
  ggscatter(x = 'sdrt', y = 'simpson_reciprocal', alpha = alpha_val, 
            xlab = 'Day relative to HCT',
            ylab = 'Microbiome alpha diversity',
            add = "loess", color = 'darkgoldenrod',
            add.params = list(color = "darkgoldenrod4", fill = "darkgray", size = 2), 
            conf.int = TRUE) +
  xlim(-10, 50) +
  scale_x_continuous(breaks = seq(-10, 50, 10)) + theme(aspect.ratio=1)
stool_alpha
```

```{r}
# stool split
stool_split <-  meta %>% 
  mutate(log_div = log(simpson_reciprocal)) %>% 
  ggscatter(x = 'sdrt', y = 'simpson_reciprocal', alpha = alpha_val, 
            xlab = 'Day relative to HCT',
            ylab = 'Microbiome alpha diversity',
            add = "loess", color = 'intensity', palette = 'lancet',
            conf.int = TRUE) +
  xlim(-10, 50) +
  #theme(legend.position = 'none') + 
  scale_x_continuous(breaks = seq(-10, 50, 10)) + theme(aspect.ratio=1)
stool_split
```


```{r}
library(cowplot)
alpha <- plot_grid(cal_, diet_alpha, stool_alpha,
                   byrow = T,
          nrow = 1, 
          align = 'hv',
          #rel_heights = c(1,1),
          axis = 'blrt')  +
  ggsave('../figs/all_alpha.pdf', width = 10, height = 6)


split <- plot_grid(cal_split, faith_split,stool_split,
                   byrow = T,
          nrow = 1, 
          align = 'hv',
          #rel_heights = c(1,1),
          axis = 'blrt')  +
  ggsave('../figs/split_alpha.pdf', width = 12, height = 8)
split 
```
```{r}
# to get the legend with different abbreviations
meta %>% 
  mutate(intensity = case_when(
    intensity == 'ablative' ~'MA',
    intensity == 'reduced' ~'RIC',
    intensity == 'nonablative' ~'NMA'
  )) %>% 
  ggscatter(x = 'sdrt', y = 'simpson_reciprocal', alpha = alpha_val, 
            xlab = 'Day relative to HCT',
            ylab = 'Microbiome alpha diversity',
            add = "loess", color = 'intensity', palette = 'lancet',
            conf.int = TRUE) +
  xlim(-10, 50) +
  theme(legend.position = 'none') + 
  scale_x_continuous(breaks = seq(-10, 50, 10)) + theme(aspect.ratio=1)
```

## the timeline plot 

```{r}
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv') %>% 
  group_by(mrn, fdrt) %>% 
  summarise(cal =  sum(Calories_kcal)) %>% 
  ungroup() %>% 
  mutate(food = 1)

stb <- read_csv('../data/cleaned_stool/selected_stool_samples_type_abx.csv') %>% 
  mutate(stool = 0)
```

```{r}
dtb %>% 
  ggplot(aes(x = fdrt, y = food )) +
  geom_point(color = 'darkolivegreen4', size = 1.5) +
  geom_point(data = stb, aes(x = sdrt, y = stool), color = 'gold4', size = 1.5) +
  facet_wrap(~mrn, scales = 'free') +
  theme_classic() +
  theme(strip.background = element_blank(),
        #strip.text.x = element_blank(),
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        legend.position = "none") +
  ylim(-0.5, 1.5) +
  ggsave('../figs/timeline_pair.pdf', width = 18, height = 9)
```



