---
title: "heatmap family level"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidybayes)
library(brms)
options(mc.cores = parallel::detectCores())
rstan::rstan_options(auto_write = TRUE)
ncores <- parallel::detectCores()
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
axis_text_size <- 7
axis_title_size <- 7
```

Response: family level 

## getting the data ready

```{r}
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = factor(mrn)) %>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100) %>% 
  mutate(inten_non = if_else(intensity == 'nonablative', 1, 0),
         inten_ab = if_else(intensity == 'ablative', 1, 0),
         inten_re = if_else(intensity == 'reduced', 1, 0))

cts <- read_csv('../data/cleaned_stool/ALL_stool_samples_family_counts.csv') %>% 
  filter(sampleid %in% meta$sampleid) %>% 
  dplyr::select(sampleid, taxa_family, relab) %>% 
  mutate(taxa_family = str_extract(taxa_family, 'f__.+$')) %>% 
  mutate(taxa_family = str_replace(taxa_family, 'f__','')) %>% 
  filter(taxa_family != 'NA')

meta %>% 
  distinct(mrn)
```
```{r}
thre <- seq(0.0001, 0.003, 0.0001)
thre %>% 
  set_names(thre) %>% 
  map_dfr(function(num){
    cts %>% 
    group_by(taxa_family) %>% 
    count(relab > num) %>% 
    rename(criteria = names(.)[2]) %>% 
    filter(criteria == 'TRUE') %>% 
    arrange(-n) %>% 
    mutate(perc = round(n/nrow(meta)*100, 0)) %>% 
    filter(perc > 10) %>% 
      nrow
  }) %>% 
  gather('thre', 'num')
# choose 0.002


target_family <-  cts %>% 
  group_by(taxa_family) %>% 
  count(relab > 0.002) %>% 
  rename(criteria = names(.)[2]) %>% 
  filter(criteria == 'TRUE') %>% 
  arrange(-n) %>% 
  mutate(perc = round(n/nrow(meta)*100, 0)) %>% 
  filter(perc > 10) %>% 
  pull(taxa_family)
```
```{r}
fcts <- read_csv('../data/088_family_relab_log10_wide.csv')
domcts <- fcts %>% 
  select(sampleid, all_of(target_family))

All <- domcts %>% 
  full_join(meta, by = "sampleid")

#All <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_dietall_genera36.csv')
```

## setting priors

```{r}
# getting to know the distributionn of the family relab log
domcts_narrow <- cts %>% 
  filter(taxa_family %in% target_family) %>% 
  mutate(relablog = log10(relab + 2*10^-6)) %>% 
  dplyr::select(-relab)

range(domcts_narrow$relablog) # 0 , -5.7

priors <- c(# for the food group variables
            prior(normal(0, 1.2), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_veggie"),
            # for the TPN 
            prior(normal(0, 0.1), class = 'b', coef = "TPNTRUE"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "ENTRUE"),
            # for the empirical 
            prior(normal(0, 0.5), class = 'b', coef = "empiricalTRUE"),
            # for the intensity 
            prior(normal(0, 0.1), class = 'b', coef = "inten_re"),
            prior(normal(0, 0.1), class = 'b', coef = "inten_ab"),
            prior(normal(0, 0.1), class = 'b', coef = "inten_non"),
            prior(normal(-3, 1), class = 'Intercept'))

Enterococcaceae_mod <- Enterococcaceae ~ 1 +
                fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               inten_non + inten_ab + inten_re +
                empirical+
                TPN+
                EN+ 
               (1 | mrn) +
                (1 | timebin)
```

```{r Enterococcaceae}
# the usual model 
Enterococcaceae_model <- brm( Enterococcaceae_mod,  
              data = All, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
              control = list(adapt_delta = 0.99),
              seed = 123, sample_prior = T )

post_enterco <- suppressWarnings(posterior_samples(Enterococcaceae_model)) %>% 
            select(-starts_with('r_'))

post_enterco %>%  write_csv('../data/054_Enterococcaceae_model_post.csv')
```



```{r Enterococcaceae}
post_samples  <- posterior_samples(Enterococcaceae_model, '^b_')

nodes <- read_tsv('../data/source/NodeLabels_withcomma.txt', col_types = 'cc') %>% 
  filter(nchar(Level.code) == 1) %>% 
  rename(fgrp1 = Level.code, 
         fdesc = Main.food.description) 

key <- read_csv('../data/cleaned_diet_data/food_group_color_key.csv', col_types = 'ccccc') 

post_coeff <- post_samples %>% 
  select(starts_with('b_fg')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item = str_replace(item, 'b_fg_','')) %>% 
   mutate(fgrp1 = case_when(
    item ==  'milk' ~ '1',
    item == 'meat' ~ '2',
    item ==  'egg' ~ '3',
    item ==  'legume' ~ '4',
    item == 'grain' ~ '5',
    item == 'fruit' ~ '6',
    item == 'veggie' ~ '7',
    item ==  'oils' ~ '8', 
    item ==  'sweets' ~ '9'
  ))  %>% 
  left_join(key) %>% 
  mutate(fdesc = str_replace_all(fdesc, '_',' ')) %>% 
  mutate(fdesc = str_wrap(fdesc, width = 28, indent = 2, exdent = 0)) %>% 
  mutate(fdesc = str_replace(fdesc, 'and','&')) %>% 
  left_join(key %>% select(fgrp1, color, shortname))  %>% 
  mutate(shortname = fct_reorder(shortname, coeff, .fun=median, .desc = F))  %>% 
  mutate(shortname = factor(shortname, levels = c("Fruits"  , "Sweets"  ,  "Vegetables", "Grains"    , "Milk"   ,    "Meats"    ,   "Eggs"      , "Legumes" ,   "Oils" )))

fg_colors <- post_coeff %>% 
  distinct(shortname, color) %>% 
  select(shortname, color) %>% 
  deframe()

# plotting the forest
Enterococcaceae_model_coeff <- post_coeff %>% 
  ggplot(aes(x = coeff, y = shortname, col = shortname)) +
  stat_pointinterval(.width = c(.66, .95)) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  labs(x = 'Regression coefficients',
       y = '',
       title = 'Enterococcaceae') +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_manual(values = fg_colors) +
  theme(axis.text=element_text(size=8),
        axis.title=element_text(size=8),
        aspect.ratio=1) 

Enterococcaceae_model_coeff %>% 
  write_rds('../data/054_Enterococcaceae_model_coeff.rds')

ggsave('../figs/paper/054_fig2_model_Enterococcaceae_model_coeff_forest.eps',  
       width = 80,
       height = 80, 
         units = c("mm"),
         dpi = 400, device = 'eps')
```

```{r enterococcus_binary}
coeff_bi <- post_samples %>% 
  select(!starts_with('b_fg')) %>% 
  select(-b_Intercept) %>% 
  gather('item', 'coeff') %>% 
  mutate(item_name = case_when(
    item ==  'b_inten_non' ~ 'Intensity: nonablative',
    item == 'b_inten_ab' ~ 'Intensity: ablative',
    item ==  'b_inten_re' ~ 'Intensity: reduced',
    item ==  'b_empiricalTRUE' ~ 'Empirical abx exposure',
    item == 'b_TPNTRUE' ~ 'TPN exposure',
    item ==  'b_ENTRUE' ~ 'EN exposure'
  )) %>% 
  mutate(item = factor(item, levels = c('b_empiF','b_empiT','b_inten_non','b_inten_re','b_inten_ab','b_enF','b_enT','b_tpnF','b_tpnT'))) %>% 
  mutate(item_name = fct_reorder(item_name, coeff, .fun=median, .desc = F)) 

coeff_bi %>% 
  ggplot(aes(x = coeff, y = item_name)) +
  stat_pointinterval(.width = c(.66, .95)) +
  #scale_color_manual(values = c('#EC0000','#00468B')) +
  geom_vline(xintercept = 0, col = 'red', linetype = 'dashed') +
  labs(x = 'Regression coefficients',
       y = 'Binary variables') +
  theme_classic() +
  theme(legend.position = 'none',
        aspect.ratio=1)

ggsave('../figs/paper/054_fig2_model_Enterococcaceae_coeff_forest_binary.eps',  
       width = 100,
       height = 100,
         #height = 60,
         units = c("mm"),
         dpi = 400, device = 'eps') 
```



```{r prior_check}
# prior check
# mean_fg <-  meta %>% 
#   select(starts_with('fg')) %>% 
#   summarise_all(funs(mean))
# 
# samples_prior <- prior_samples(model_old)
# 
# ave_each_fg <- samples_prior %>% 
#   mutate(mean_fg = Intercept + 
#            b_fg_fruit*mean_fg$fg_fruit +
#            b_fg_meat*mean_fg$fg_meat + 
#            b_fg_milk*mean_fg$fg_milk + 
#            b_fg_oils*mean_fg$fg_oils + 
#            b_fg_egg*mean_fg$fg_egg + 
#            b_fg_grain*mean_fg$fg_grain +
#            b_fg_sweets*mean_fg$fg_sweets +
#            b_fg_legume*mean_fg$fg_legume +
#            b_fg_veggie*mean_fg$fg_veggie +
#            b_inten_re +
#            b_empiF +
#            b_tpnF +
#            b_enF) %>% 
#   select(mean_fg) %>% 
#   mutate(grp = 'ave_each') %>% 
#   rename(prior_res = mean_fg) %>% 
#   select(grp, prior_res)
# 
# ave_each_fg %>% 
#   gghistogram(x = 'prior_res')
# 
# ave_each_fg %>% 
#   count(prior_res >-5.7 & prior_res<0) %>% 
#   mutate(perc = n/4000*100) %>% 
#   select(perc) %>% 
#   slice(2) %>% 
#   pull(perc) %>% 
#   round(1)
```

```{r all_fam} 
# wannt to do the above for every family I'm going to run
# so basically run every model and extract the priors later 

## all family model run
ret <- target_family %>% 
  set_names(target_family) %>% 
  purrr::map(function(fam) {
    mod =  brm( as.formula(str_glue('{fam}  ~ 
               1 +
                fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               inten_non + inten_ab + inten_re +
                empirical+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin)')),  
                data = All, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
              control = list(adapt_delta = 0.99),
              seed = 456, sample_prior = T) 

  })


# save the data
prior_df <- ret %>% 
  imap(~ prior_draws(.x) ) %>% 
  bind_rows(.id = 'family')

prior_df %>% 
  write_csv('../data/054_family_model_prior.csv')

post_df <- ret %>% 
  imap(~ (suppressWarnings(posterior_samples(.x)) %>% 
            select(-starts_with('r_'))))  %>% 
  bind_rows(.id = 'family')  

post_df %>% 
  write_csv('../data/054_family_model_post.csv')
```


```{r}
## look at the all family priors
valid_interval_perc <- ret %>% 
  imap(~ prior_draws(.x) %>% 
            mutate(mean_fg = Intercept + 
                     b_fg_fruit*mean_fg$fg_fruit +
                     b_fg_meat*mean_fg$fg_meat + 
                     b_fg_milk*mean_fg$fg_milk + 
                     b_fg_oils*mean_fg$fg_oils + 
                     b_fg_egg*mean_fg$fg_egg + 
                     b_fg_grain*mean_fg$fg_grain +
                     b_fg_sweets*mean_fg$fg_sweets +
                     b_fg_legume*mean_fg$fg_legume +
                     b_fg_veggie*mean_fg$fg_veggie +
                     b_inten_re ) %>% 
            select(mean_fg) %>% 
            mutate(grp = 'ave_each') %>% 
            rename(prior_res = mean_fg) %>% 
            select(grp, prior_res) %>% 
            count(prior_res >-5.7 & prior_res<0) %>% 
            mutate(perc = n/4000*100) %>% 
            select(perc) %>% 
            slice(2) %>% 
            pull(perc) %>% 
            round(1) ) %>% 
  bind_rows(.id = .y) %>% 
  gather('family','within_interval_perc')
# good I'm happy with this prior  


# save the prior 
prior_save <- ret %>% 
  imap(~ (prior_draws(.x) %>% 
          select(starts_with('b_'), Intercept) %>% 
          gather('item','coeff') %>% 
          mutate(family = .y)))  %>% 
  bind_rows()

prior_save %>% 
  write_csv('../figs/paper/data/all_fam_prior_save.csv')

prior_save %>% 
  distinct(item)
```

## look at post coeff


```{r}
# grab the quantiles for the 95% (star) and 75% (color) confidence interval from the posterior samples
# two stars for 97.5% and three stars for 99%
post_df <- read_csv('../data/054_family_model_post.csv')
 
post_res <- post_df %>% 
  select(family, starts_with('b_fg')) %>% 
  gather('item','coeff', names(.)[2]:names(.)[ncol(.)]) %>% 
  group_by(family, item) %>% 
  summarise(q50 = median(coeff),
            q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975),
            q12.5 = quantile(coeff, probs = 0.125),
            q87.5 = quantile(coeff, probs = 0.875),
            q1.25 = quantile(coeff, probs = 0.0125),
            q98.75 = quantile(coeff, probs = 0.9875),
            q0.5 = quantile(coeff, probs = 0.005),
            q99.5 = quantile(coeff, probs = 0.995)
            ) %>% 
  ungroup() %>% 
  mutate(mark = if_else(q99.5 < 0 | q0.5 > 0, '***', if_else(q98.75 < 0 | q1.25 > 0, '**', if_else(q97.5 < 0 | q2.5 > 0, '*', '')))) %>% 
  mutate(color = if_else(q87.5 < 0, 'steelblue', if_else(q12.5 > 0, 'maroon', 'white'))) %>% 
  mutate(family = str_replace(family, '._Incertae_Sedis','')) %>% 
  mutate(item = str_replace(item, 'b_fg_','')) %>% 
  mutate(item = str_to_title(item))
```


```{r}
# trying to order the rows and the columns by similarity in euclidean distances
# make it a numerical matrix and then calculate the distance
dat <- post_res %>% 
  select(family:q50) %>% 
  spread('item', 'q50') %>% 
  column_to_rownames('family')

hc <- hclust(dist(dat))
dend <- as.dendrogram(hc)
family_order <- labels(dend)

# the fg order
dat <- post_res %>% 
  select(family:q50) %>% 
  spread('family', 'q50') %>% 
  column_to_rownames('item')

hc <- hclust(dist(dat))
dend <- as.dendrogram(hc)
fg_order <- labels(dend)

post_res_ordered <- post_res %>% 
  mutate(family = factor(family, levels = family_order),
         item = factor(item, levels = fg_order))
```

## the heatmap

```{r}
col_key <- post_res %>% 
  ungroup() %>% 
  distinct(color) %>% 
  pull(color)

names(col_key) <- col_key


axis_text_size <- 13
axis_title_size <- 10

ggplot(post_res_ordered, aes(x = family, y = item)) +
  geom_tile(aes(fill = color,  x = family, y =  item), alpha = 0.5, color='white', width=0.95, height=0.95) +
 # geom_text(aes(label = round(meanperitem, 3))) +
  geom_text(aes(label = mark, x = family,y =  item),
            nudge_y = -0.1, nudge_x = 0,size = 5) +
  scale_fill_manual(values = col_key, labels = c('Less than 75% CI crosses 0','75% CI < 0 negative','75% CI > 0 positive')) +
  theme_light() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle=50, hjust=1, size=11),
        axis.text.y=element_text(size=11),
        axis.title=element_text(size=axis_title_size),
        #panel.grid.major = element_blank(), 
        #panel.grid.minor = element_blank(),
        legend.position = 'top',
        legend.key = element_rect( colour = "gray50"),
        panel.background = element_blank()) 


ggsave('../figs/paper/054_heatmap_family_24_ggplot.pdf', width = 8, height = 5)
```

```{r}
# the heatmap about the binary variables
post_bi_res <- post_df %>% 
  select(family, starts_with('b_')) %>% 
  select(-starts_with('b_fg'), -b_Intercept) %>% 
  gather('item','coeff', names(.)[2]:names(.)[ncol(.)]) %>% 
  group_by(family, item) %>% 
  summarise(q50 = median(coeff),
            q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975),
            q12.5 = quantile(coeff, probs = 0.125),
            q87.5 = quantile(coeff, probs = 0.875),
            q1.25 = quantile(coeff, probs = 0.0125),
            q98.75 = quantile(coeff, probs = 0.9875),
            q0.5 = quantile(coeff, probs = 0.005),
            q99.5 = quantile(coeff, probs = 0.995)
            ) %>% 
  ungroup() %>% 
  mutate(mark = if_else(q99.5 < 0 | q0.5 > 0, '***', if_else(q98.75 < 0 | q1.25 > 0, '**', if_else(q97.5 < 0 | q2.5 > 0, '*', '')))) %>% 
  mutate(color = if_else(q87.5 < 0, 'steelblue', if_else(q12.5 > 0, 'maroon', 'white'))) %>% 
  mutate(item_name = case_when(
    item ==  'b_inten_non' ~ 'Intensity: nonablative',
    item == 'b_inten_ab' ~ 'Intensity: ablative',
    item ==  'b_inten_re' ~ 'Intensity: reduced',
    item ==  'b_empiricalTRUE' ~ 'Empirical abx exposure',
    item == 'b_TPNTRUE' ~ 'TPN exposure',
    item ==  'b_ENTRUE' ~ 'EN exposure'
  )) %>% 
  mutate(family = str_replace(family, '._Incertae_Sedis','')) 

ggplot(post_bi_res, aes(x = family, y = item_name)) +
  geom_tile(aes(fill = color,  x = family, y =  item_name), alpha = 0.5, color='white', width=0.95, height=0.95) +
  geom_text(aes(label = mark, x = family,y =  item_name),
            nudge_y = -0.1, nudge_x = 0,size = 5) +
  scale_fill_manual(values = col_key, labels = c('Less than 75% CI crosses 0','75% CI < 0 negative','75% CI > 0 positive')) +
  theme_light() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle=50, hjust=1, size=11),
        axis.text.y=element_text(size=11),
        axis.title=element_text(size=axis_title_size),
        #panel.grid.major = element_blank(), 
        #panel.grid.minor = element_blank(),
        legend.position = 'top',
        legend.key = element_rect( colour = "gray50"),
        panel.background = element_blank()) 

ggsave('../figs/paper/054_heatmap_binaries_family_24_ggplot.pdf', width = 9, height = 4)
```


```{r}
# Add a family annotation at the class level 
source('~/db_connect_simple.R')
connect_database(config_file = '~/dbConfig.txt')
get_table_from_database('asv_annotation_blast_ag')
list_table_from_database('blast')

annot_class <- asv_annotation_blast_ag %>% 
  filter(family %in% retdf$family) %>% 
  distinct(family, class) %>% 
  column_to_rownames('family')

annot_phy <- asv_annotation_blast_ag %>% 
  filter(family %in% retdf$family) %>% 
  distinct(family, phylum) %>% 
  column_to_rownames('family')

class_cols <- tibble(
  class = unique(annot_class$class),
  color = RColorBrewer::brewer.pal(n = 9, name = 'Set1')
) %>% 
  deframe()


colGradient <- function( cols, length, cmax=255 )
{ ramp <- colorRamp(cols)
  rgb( ramp(seq(0,1,length=length)), max=cmax )
}

bwrPalette <- colGradient(c("blue","white","red"),length=11) # this is the scale of the score

```





