---
title: "Diet shotgun samples metaphlan"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
metaph <- read_tsv('../data/merged_abundance_table.txt', skip = 1) %>% 
  filter(str_detect(clade_name, 's__')) %>% 
  select(-NCBI_tax_id) %>% 
  rename_all(~ gsub("_profile", "", .)) %>% 
  mutate(clade_name = str_extract(clade_name, 's__.+$')) %>% 
  column_to_rownames('clade_name')

sort(rownames(metaph))

# some filtering 
thre <- floor(ncol(metaph) * 0.1)

metaph_fil <- metaph[rowSums(metaph >= 0.01) >= 3, ]
```


```{r}
library(pheatmap)
pheatmap(
  metaph_fil,
  #color=bwrPalette, 
  #annotation_col = annot,
  show_rownames = TRUE,
  show_colnames = TRUE,
  filename = '../figs/heatmap_11_shotgun_spp_relab.pdf',
  height = 15,
  width = 10,
  display_numbers = T,
  cluster_rows =T,
  cluster_cols=T
)

# great this patient that we have several longitudinal stool samples have developed entercoccus domination!
```

# find the complete genomes of enterococcus faecium from genbank

```{r}
list <- read_tsv('~/Downloads/assembly_summary.txt', skip = 1) %>% 
  filter(assembly_level == 'Complete Genome') %>% 
  mutate(rysnc = str_replace(ftp_path, 'ftp:','rsync:')) %>% 
  mutate(dl_cmd = str_glue('rsync --copy-links --recursive --times --verbose {rysnc} /home/daia1/my_workdir/faecium')) %>% 
  select(dl_cmd) %>% 
  write_csv('../data/download_faecium.sh', col_names = F)
```

```{r}
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv') %>% 
  filter(str_detect(sampleid, '^2142') )
```


