---
title: "iRep analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lmerTest)
```

```{r}
cat <- read_csv('../data/growth/cat_irep_taxa.csv', col_types = cols(.default = col_character())) %>% 
  mutate(iRep = as.numeric(iRep))

meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_and_d0_fg9_updated_g3.csv')

together <- cat %>% 
  left_join(meta, by = "sampleid") %>% 
  filter(!is.na(mrn)) #  there are some that were sent for shotgun sequencing but I didn't have the diet data 

Clostridiales_df <- together %>% 
  filter(str_detect(order, 'Clostridiales'))

hist(cat %>% filter(iRep <=3) %>% pull(iRep), breaks = 50)
```

```{r}
# prepare the table to send to Jonas
send <- together %>% 
  mutate(pt = str_glue('P{as.numeric(as.factor(mrn))}')) %>% 
  select(-mrn, -sampleid) %>% 
  separate(samplebin, into = c('sampleid','binnum'), sep = '\\.fa\\.') %>% 
  mutate(sampleid = str_glue('S{as.numeric(as.factor(sampleid))}'))
send %>% 
  write_csv('../data/growth/Jonas_nutrition_with_irep.csv')

colnames(send)
```


```{r}
mod_Clostridiales <-  lmer(iRep ~ 
            # 0 +
              fg_fruit+ 
               empirical + 
               intensity + 
               (1 | mrn) +
                (1 | sampleid) +
                (1 | timebin), REML = F, data = Clostridiales_df )
summary(mod_Clostridiales)

Clostridiales_df %>% 
  filter(iRep <= 3) %>% 
  ggscatter(x = 'fg_fruit', y = 'iRep', facet.by = 'empirical')

```

```{r}
mod_Clostridiales2 <-  lmer(log(simpson_reciprocal)  ~ 
            # 0 +
              iRep +
               empirical + 
               intensity + 
               (1 | mrn) +
                (1 | sampleid) +
                (1 | timebin), REML = F, data = Clostridiales_df )
summary(mod_Clostridiales2)
```

```{r}
Lactobacillales <- together %>% 
  filter(str_detect(order, 'Lactobacillales'))

mod_Lactobacillales <-  lmer(iRep ~ 
             0 +
              fg_fruit+ 
               empirical + 
               intensity + 
               (1 | mrn) +
                (1 | sampleid) +
                (1 | timebin), REML = F, data = Lactobacillales )
summary(mod_Lactobacillales)

Lactobacillales %>% 
  group_by(sampleid, fg_fruit) %>% 
  summarise(med_irep = median(iRep)) %>% 
  #filter(med_irep < 8) %>% 
  ggscatter(x = 'fg_fruit', y = 'med_irep',
            add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "pearson", label.sep = "\n") )  +
  ggsave('../figs/all_Lactobacillales_irep_fg_fruit.pdf', width = 6, height = 4)
```
```{r}
# the two orders
fam <- read_csv('../data/cleaned_stool/ALL_stool_samples_family_counts.csv')%>% 
  filter(str_detect(taxa_family, 'f__Enterococcaceae')) %>% 
  mutate(family = str_extract(taxa_family, 'f__.+$')) %>% 
  spread('family','relab') %>% 
  select(sampleid, f__Enterococcaceae)

df <- together %>% 
  filter(str_detect(order, 'Lactobacillales|Clostridiales|Bacteroidia')) %>% 
  select(sampleid, iRep, order, fg_egg:TPN) %>% 
  group_by(sampleid, order) %>% 
  summarise(med_irep = median(iRep)) %>% 
  mutate(order = str_replace(order, ' \\(order\\)$| \\(class\\)','')) %>% 
  mutate(order = str_glue('{order}_irep')) %>% 
  spread('order','med_irep', fill = NA) %>% 
  inner_join(meta, by = "sampleid") %>% 
  inner_join(fam)

few <- df %>% 
  ungroup() %>% 
  select(sdrt, mrn, Bacteroidia_irep:Lactobacillales_irep, fg_fruit , f__Enterococcaceae) %>% 
  gather('key', 'value', Bacteroidia_irep:f__Enterococcaceae) 

few %>% 
  split(.$mrn) %>% 
  imap(~ggdotchart(data = ., x = 'sdrt', y = 'value',   add = "segments",
                   sorting = 'none', font.label = list(size = 5, face = "plain"),
                   title = str_glue('{.y}')) +
         theme(axis.text.x = element_text(size=5, angle=90, hjust=1)) +
         facet_grid(key~., scales = 'free') +
         theme_light() +
         ggsave(str_glue('../figs/timeline_irep_{.y}.pdf'), width = 7, height = 7))
```

```{r}
# the scale version 
scale <- df %>% 
  select(Bacteroidia_irep:Lactobacillales_irep) %>% 
  gather('key', 'value', Bacteroidia_irep:Lactobacillales_irep) %>% 
  filter(!is.na(value)) %>% 
  ungroup() %>% 
  split(.$key) %>% 
  map_dfr(~ mutate(.data = ., scalev = (value - min(value))/(max(value) - min(value)))) %>% 
  spread('key','scalev') %>% 
  select(-value) %>% 
  inner_join(meta, by = "sampleid") %>% 
  inner_join(fam)%>% 
  ungroup() %>% 
  select(sdrt, mrn, Bacteroidia_irep:Lactobacillales_irep, fg_fruit , f__Enterococcaceae) %>% 
  gather('key', 'value', Bacteroidia_irep:f__Enterococcaceae) %>% 
  split(.$mrn) %>% 
  imap(~ggdotchart(data = ., x = 'sdrt', y = 'value',   add = "segments",
                   sorting = 'none', font.label = list(size = 5, face = "plain"),
                   title = str_glue('{.y}')) +
         theme(axis.text.x = element_text(size=5, angle=90, hjust=1)) +
         facet_grid(key~., scales = 'free') +
         theme_light() +
         ggsave(str_glue('../figs/timeline_irep_{.y}_scaled_irep.pdf'), width = 7, height = 7))
```

