---
title: "Fig 1 overview panel"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggbiplot)
library(tidyverse)
```

```{r}
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv') %>% 
  mutate(mrn = factor(mrn))
```

# Look at the pca using the nutrients from the 5230 meals

```{r}
# dm stands for day meal 
meal <- dtb %>% 
  group_by(mrn, Meal, fdrt) %>% 
  summarise(dm_pro = sum(Protein_g),
            dm_fat = sum(Fat_g),
            dm_carb = sum(Carbohydrates_g),
            dm_fiber = sum(Fibers_g),
            dm_sugar = sum(Sugars_g),
            dm_sodium = sum(Sodium_g)) %>% 
  ungroup() %>% 
  mutate(ID = str_glue('M{seq(1, nrow(.))}'))

dm_tb <- meal %>% 
  column_to_rownames('ID') %>% 
  mutate(sum = rowSums(.[4:9])) %>% 
  filter(sum > 0) %>% 
  select(-sum) %>% 
  mutate(menu = str_replace(Meal, '^.+Menu: ','')) %>% 
  mutate(time = case_when(
    fdrt < 0 ~"pre_transplant",
    TRUE ~ 'after'
  ))
 
pca <- prcomp(dm_tb[,c(4:9)], center = TRUE,scale. = TRUE)
summary(pca)


# to look at whether time menu or mrn has some separation
# each dot is a meal for that patient on that day 
ggbiplot(pca, alpha = 0.3, groups  = dm_tb$time, ellipse=TRUE)
ggbiplot(pca, alpha = 0.3, groups  = dm_tb$menu, ellipse=TRUE)
ggbiplot(pca, alpha = 0.3, groups  = dm_tb$mrn, ellipse=TRUE) + theme(legend.position = "none")
ggbiplot(pca, alpha = 0.3)
menus <- dm_tb %>% 
  ungroup() %>% 
  distinct(menu)
```
# How many days of dietary data to pair up with microbiome data?




