---
title: "The model re-done with Bayesian"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F)
```

```{r}
library(tidyverse)
library(brms)  
library(ggpubr)
library(tidybayes)
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
```

## Loading meta data table

```{r load_meta}
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = factor(mrn)) %>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100) %>% 
  mutate(empiT = if_else(empirical == 'TRUE', 1, 0),
         empiF = if_else(empirical == 'FALSE', 1, 0),
         tpnT = if_else(TPN == 'TRUE', 1, 0),
         tpnF = if_else(TPN == 'FALSE', 1, 0),
         enT = if_else(TPN == 'TRUE', 1, 0),
         enF = if_else(TPN == 'FALSE', 1, 0),
         inten_non = if_else(intensity == 'nonablative', 1, 0),
         inten_ab = if_else(intensity == 'ablative', 1, 0),
         inten_re = if_else(intensity == 'reduced', 1, 0)) 

```

## Priors 

```{r get_prior}
# what priors I cann set 
model_formular <- log(simpson_reciprocal)~ 1 +
                fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               inten_non + inten_ab + inten_re +
               empiT +  empiF+
                tpnT +tpnF+
                enT +enF+
               (1 | mrn) +
                (1 | timebin)
get_prior( model_formular,  
              data = meta)
```

### Setting priors

```{r set_prior}

priors <- c(# for the food group variables
            prior(normal(0, 1), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie"),
            # for the TPN 
            prior(normal(0, 0.1), class = 'b', coef = "tpnF"),
            prior(normal(0, 0.1), class = 'b', coef = "tpnT"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "enF"),
            prior(normal(0, 0.1), class = 'b', coef = "enT"),
            # for the empirical 
            prior(normal(0, 0.5), class = 'b', coef = "empiF"),
            prior(normal(0, 0.5), class = 'b', coef = "empiT"),
            # for the intensity 
            prior(normal(0, 0.1), class = 'b', coef = "inten_re"),
            prior(normal(0, 0.1), class = 'b', coef = "inten_ab"),
            prior(normal(0, 0.1), class = 'b', coef = "inten_non"),
            prior(normal(2, 0.1), class = 'Intercept'))

# samples are drawn solely from the priors ignoring the likelihood
model_wo_EN <- brm( model_formular,  
              data = meta, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = 16, 
              chains = 2, 
              seed = 123, sample_prior = T) 

# actually draw samples from the priors 
samples_prior <- prior_samples(model_wo_EN)

```

```{r }
# the mean food group intake from our data 
ave_fg <- meta %>% 
  select(starts_with('fg')) %>% 
  summarise_all(funs(mean)) %>% 
  gather

mean_fg <-  meta %>% 
  select(starts_with('fg')) %>% 
  summarise_all(funs(mean))

max_fg <- meta %>% 
  select(starts_with('fg')) %>% 
  summarise_all(funs(max))

min_fg <- meta %>% 
  select(starts_with('fg')) %>% 
  summarise_all(funs(min))

max_log_div <- max(log(meta$simpson_reciprocal)) 
range(log(meta$simpson_reciprocal))
```


```{r}
# create a df with max and min and ave in 9 groups
# create a df with the corresponding value that the samples prior coeff can multiply
max_ <- ave_fg %>% 
  rename(mean_ = value) %>% 
  mutate(max_fg_egg = if_else(key == 'fg_egg', max_fg$fg_egg, mean_),
         max_fg_fruit = if_else(key == 'fg_fruit', max_fg$fg_fruit, mean_),
         max_fg_grain = if_else(key == 'fg_grain', max_fg$fg_grain, mean_),
         max_fg_legume = if_else(key == 'fg_legume', max_fg$fg_legume, mean_),
         max_fg_meat = if_else(key == 'fg_meat', max_fg$fg_meat, mean_),
         max_fg_milk = if_else(key == 'fg_milk', max_fg$fg_milk, mean_),
         max_fg_oils = if_else(key == 'fg_oils', max_fg$fg_oils, mean_),
         max_fg_sweets = if_else(key == 'fg_sweets', max_fg$fg_sweets, mean_),
         max_fg_veggie = if_else(key == 'fg_veggie', max_fg$fg_veggie, mean_)) %>% 
  select(-mean_) %>% 
  mutate(key = if_else(str_detect(key, '^fg'), str_glue('b_{key}'), key))  %>% 
  arrange(key)

prior_coeffs <- samples_prior %>% 
  select(Intercept, b_inten_re, b_empiF, b_tpnF, b_enF, starts_with('b_fg')) %>% 
  gather('term','prior_coeff') %>% 
  split(.$term)
  
values <- max_ %>% 
  select(-key) %>% 
  as.list()

values <- values %>% 
  map(~ set_names(x = ., max_$key))

# calculate the resulted prior log div 
vals <- names(values)

max_each_fg <- vals  %>% 
  set_names(vals) %>% 
  map(function(val) {
    res = prior_coeffs$b_empiF$prior_coeff  +
   prior_coeffs$b_enF$prior_coeff  +
   prior_coeffs$b_fg_egg$prior_coeff  * values %>% pluck(val) %>% pluck('b_fg_egg') +
   prior_coeffs$b_fg_fruit$prior_coeff  * values %>% pluck(val) %>% pluck('b_fg_fruit') +
   prior_coeffs$b_fg_grain$prior_coeff  * values %>% pluck(val) %>% pluck('b_fg_grain') +
   prior_coeffs$b_fg_legume$prior_coeff  * values %>% pluck(val) %>% pluck('b_fg_legume') +
   prior_coeffs$b_fg_meat$prior_coeff * values %>% pluck(val) %>% pluck('b_fg_meat') +
   prior_coeffs$b_fg_milk$prior_coeff  * values %>% pluck(val) %>% pluck('b_fg_milk') +
   prior_coeffs$b_fg_oils$prior_coeff * values %>% pluck(val) %>% pluck('b_fg_oils') +
   prior_coeffs$b_fg_sweets$prior_coeff  * values %>% pluck(val) %>% pluck('b_fg_sweets') +
   prior_coeffs$b_fg_veggie$prior_coeff  * values %>% pluck(val) %>% pluck('b_fg_veggie') +
   prior_coeffs$b_inten_re$prior_coeff  +
   prior_coeffs$b_tpnF$prior_coeff +
   prior_coeffs$Intercept$prior_coeff 
  }) %>% 
  bind_rows(.id = 'grp') %>% 
  gather('grp', 'prior_res')
```


```{r plot_prior}
# combine the max and min and ave together and plot
ave_each_fg <- samples_prior %>% 
  mutate(mean_fg = Intercept + 
          b_fg_fruit *mean_fg$fg_fruit+
           b_fg_meat *mean_fg$fg_meat+ 
           b_fg_milk *mean_fg$fg_milk+ 
           b_fg_oils * mean_fg$fg_oils+ 
           b_fg_egg * mean_fg$fg_egg+ 
           b_fg_grain* mean_fg$fg_grain +
           b_fg_sweets * mean_fg$fg_sweets+
           b_fg_legume * mean_fg$fg_legume+
           b_fg_veggie* mean_fg$fg_veggie +
           b_inten_re +
           b_empiF +
           b_tpnF +
           b_enF) %>% 
  select(mean_fg) %>% 
  mutate(grp = 'ave_each') %>% 
  rename(prior_res = mean_fg) %>% 
  select(grp, prior_res)

prior_all <- bind_rows(ave_each_fg, max_each_fg) 



grps <- prior_all %>% 
  distinct(grp)

fg_cha <- meta %>% 
  select(starts_with('fg')) %>% 
  colnames()

prior_check_list <- fg_cha %>% 
  set_names(fg_cha) %>% 
  map(function(char){
    prior_all %>% 
      filter(str_detect(grp, str_glue('ave_each'))) %>% 
      gghistogram(x = 'prior_res', fill = 'grp', color = 'white', palette = 'lancet', xlab = 'diversity',
                  #add_density = TRUE, 
                  bins = 30,
                  title = str_glue('Prior check {char}'))
    })

g <- cowplot::plot_grid(prior_check_list[[1]],prior_check_list[[2]],prior_check_list[[3]],prior_check_list[[4]],prior_check_list[[5]],prior_check_list[[6]],prior_check_list[[7]],prior_check_list[[8]],prior_check_list[[9]],
    ncol = 3, nrow= 3, 
    o = 'hv',
    #labels = 'AUTO',
    axis = 'bltr') 
g


```

## Posterior

```{r}
# extract the coefficients table
posterior_model <- posterior_samples(model_wo_EN) %>% 
  select(starts_with('b')) %>% 
  #select(-b_Intercept) %>% 
  gather('item', 'value') %>% 
  group_by(item) %>% 
  mutate(meanperitem = mean(value))%>%
  ungroup() 


```

### Extract the posterior samples 

```{r post_sample}
# extract posterior samples for the coeff
post_samples  <- posterior_samples(model_wo_EN, '^b_')

# when the food intake is average mean

ave_each_fg_post <- post_samples %>% 
  mutate(mean_fg = exp(b_Intercept + 
           b_fg_fruit*mean_fg$fg_fruit +
           b_fg_meat*mean_fg$fg_meat + 
           b_fg_milk*mean_fg$fg_milk + 
           b_fg_oils*mean_fg$fg_oils + 
           b_fg_egg*mean_fg$fg_egg + 
           b_fg_grain*mean_fg$fg_grain +
           b_fg_sweets*mean_fg$fg_sweets +
           b_fg_legume*mean_fg$fg_legume +
           b_fg_veggie*mean_fg$fg_veggie +
           b_inten_re +
           b_empiF +
           b_tpnF +
           b_enF)) %>% 
  select(mean_fg) %>% 
  mutate(grp = 'ave_each') %>% 
  rename(post_res = mean_fg) %>% 
  select(grp, post_res)

# when the intake is max
post_coeffs <- post_samples %>% 
  select(b_Intercept, b_inten_re, b_empiF, b_tpnF, b_enF, starts_with('b_fg')) %>% 
  gather('term','post_coeff') %>% 
  split(.$term) 

max_each_fg_post <- vals  %>% 
  set_names(vals) %>% 
  map(function(val) {
    res = exp(post_coeffs$b_empiF$post_coeff  +
   post_coeffs$b_enF$post_coeff  +
   post_coeffs$b_fg_egg$post_coeff * values %>% pluck(val) %>% pluck('b_fg_egg') +
   post_coeffs$b_fg_fruit$post_coeff * values %>% pluck(val) %>% pluck('b_fg_fruit') +
   post_coeffs$b_fg_grain$post_coeff * values %>% pluck(val) %>% pluck('b_fg_grain') +
   post_coeffs$b_fg_legume$post_coeff * values %>% pluck(val) %>% pluck('b_fg_legume') +
   post_coeffs$b_fg_meat$post_coeff * values %>% pluck(val) %>% pluck('b_fg_meat') +
   post_coeffs$b_fg_milk$post_coeff * values %>% pluck(val) %>% pluck('b_fg_milk') +
   post_coeffs$b_fg_oils$post_coeff * values %>% pluck(val) %>% pluck('b_fg_oils') +
   post_coeffs$b_fg_sweets$post_coeff * values %>% pluck(val) %>% pluck('b_fg_sweets') +
   post_coeffs$b_fg_veggie$post_coeff * values %>% pluck(val) %>% pluck('b_fg_veggie') +
   post_coeffs$b_inten_re$post_coeff  +
   post_coeffs$b_tpnF$post_coeff +
   post_coeffs$b_Intercept$post_coeff) 
  }) %>% 
  bind_rows(.id = 'grp')
```
```{r post_diff}
# calculate the absolute difference between the max in each fg and the mean 
# note the mean is from EN-free records.
maxs <- max_each_fg_post %>% 
  as.list()

diff_res <- maxs %>% 
  map(function(vec) {
    tibble(
      max_=vec,
      ave=ave_each_fg_post$post_res
    ) %>% 
      mutate(post_diff_ = max_ - ave)
  }) %>% 
  imap(~ gghistogram(data = .x, x = 'post_diff_', 
                     fill = 'forestgreen', color = 'white', bins = 50,
                     xlab = str_glue('diff between e({.y}) and e(mean_fg)'),
                     title = str_glue('{.y}')) +
         xlim(-10, 5) +
         geom_vline(xintercept = 0, col = 'red', linetype = 'dashed'))

diff <- cowplot::plot_grid(diff_res[[1]],diff_res[[2]],diff_res[[3]],diff_res[[4]],diff_res[[5]],diff_res[[6]],diff_res[[7]],diff_res[[8]],diff_res[[9]],
    ncol = 3, nrow= 3, 
    o = 'hv',
    #labels = 'AUTO',
    axis = 'bltr') 
diff
ggsave('../figs/paper/post_check_9fg_diff_max_including_EN.pdf', width = 15, height = 10, dpi = 300, plot = diff)


all_diff <- maxs %>% 
  map(function(vec) {
    tibble(
      max_=vec,
      ave=ave_each_fg_post$post_res
    ) %>% 
      mutate(post_diff_ = ave - max_)
  }) %>% 
  bind_rows(.id = 'grp')

```

## the forest plot with prior and post 

```{r}
both <- bind_rows(
  samples_prior %>% 
    select(starts_with('b_fg')) %>% mutate(grp = 'prior'),
  post_samples %>% 
    select(starts_with('b_fg')) %>% mutate(grp = 'post')
)  %>% 
  gather('item', 'coeff', b_fg_fruit:b_fg_veggie)

summ <- both %>% 
  group_by(grp, item) %>% 
  summarise(q025 = quantile(coeff, 0.025),
            q975 = quantile(coeff, 0.975),
            q50 = quantile(coeff, 0.5)) %>% 
  arrange(grp, q50) 

summ %>% 
  ggscatter(x = 'item', y = 'q50', 
            #color = 'grp',
            ylab = 'Regression coefficients',
            title = 'Change in log scale simposon reciprocal unit\nassociated with 100g food consumption',
            xlab = 'High-level food categories\nFNDDS') +
  geom_pointrange(aes( ymin  = q025,ymax  = q975), fatten = 5, col = 'maroon') +
  geom_hline(yintercept = 0, col = "black", linetype = 'dashed') +
  facet_grid(~ grp, scales = 'free') +
  scale_y_continuous( breaks = c(-1, -0.5, 0, 0.5, 1 , 1.5, 2)) +
  coord_flip()


```




