---
title: "The model re-done with Bayesian"  
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F)
```


```{r}
library(tidyverse)
library(brms)   
library(ggpubr)
library(tidybayes)
library(cowplot)
library(ggridges)
library(brmstools)

dtb <- read_csv('../data/152_combined_DTB.csv')
theme_set(theme_tidybayes() + panel_border())
ncores <- parallel::detectCores()
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')
axis_text_size <- 10
axis_title_size <- 10

# dtb %>% 
#   distinct(mrn) %>% 
#   write_csv('../data/nutrition_patients_97_mrns.csv', col_names = T)
```

## Loading meta data table

```{r load_meta}


meta <- read_csv('../data/153_combined_META.csv') %>% 
  #filter(!sampleid %in% tb_rm$sampleid) %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = factor(mrn)) %>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100)

meta %>% summary()
```


```{r }
# the mean food group intake from our data 
ave_fg <- meta %>% 
  select(starts_with('fg')) %>% 
  summarise_all(funs(mean)) %>% 
  gather

mean_fg <-  meta %>% 
  select(starts_with('fg')) %>% 
  summarise_all(funs(mean))

max_fg <- meta %>% 
  select(starts_with('fg')) %>% 
  summarise_all(funs(max)) 

meta %>% distinct(mrn)
```

## Priors 

```{r get_prior}
# what priors I can set 
model_formular <- log(simpson_reciprocal) ~ 0 + 
                fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               intensity +
               empirical+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin)
get_prior( model_formular,  
              data = meta)
```


### Setting priors

```{r set_prior}
priors <- c(# for the food group variables
            prior(normal(0, 1), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie"),
            # for the TPN 
            prior(normal(0, 0.1), class = 'b', coef = "TPNTRUE"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "ENTRUE"),
            # for the empirical 
            prior(normal(0, 0.5), class = 'b', coef = "empiricalTRUE"),
            # for the intensity 
            prior(normal(2, 0.1), class = 'b', coef = "intensityreduced"),
            prior(normal(2, 0.1), class = 'b', coef = "intensityablative"),
            prior(normal(2, 0.1), class = 'b', coef = "intensitynonablative"))

# samples are drawn solely from the priors ignoring the likelihood
# model_wo_EN  means the usual model that the EN is still a binary variable and not ann inndivicual group
model_div <- brm( model_formular,  
              data = meta, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
               control = list(adapt_delta = 0.99),
              seed = 123, sample_prior = T) 

# actually draw samples from the priors 
samples_prior <- prior_draws(model_div)


# save it for future use
post_res <- suppressWarnings(posterior_samples(model_div)) 
post_res %>%  write_csv('../data/068_div_model_fg_post.csv')

```

```{r validate_prior}
prior_div <- prior_draws(model_div) 
colnames(prior_div)
ave_each_fg_prior <- prior_div %>% 
  mutate(mean_fg_prior_div = 
           b_fg_fruit*mean_fg$fg_fruit +
           b_fg_meat*mean_fg$fg_meat + 
           b_fg_milk*mean_fg$fg_milk + 
           b_fg_oils*mean_fg$fg_oils + 
           b_fg_egg*mean_fg$fg_egg + 
           b_fg_grain*mean_fg$fg_grain +
           b_fg_sweets*mean_fg$fg_sweets +
           b_fg_legume*mean_fg$fg_legume +
           b_fg_veggie*mean_fg$fg_veggie +
           b_intensityreduced ) %>% 
  select(mean_fg_prior_div) %>% 
  mutate(grp = 'ave_each')  %>% 
  mutate(within_range = if_else(mean_fg_prior_div >= min(log(meta$simpson_reciprocal)) &  mean_fg_prior_div <= max(log(meta$simpson_reciprocal)), T, F))

prior_diversity <- ave_each_fg_prior %>% 
  gghistogram(x = 'mean_fg_prior_div', fill = 'within_range', color = 'white',
              xlab = 'Predicted ln(diversity)\nwith prior distribution',
              title = 'Diversity') +
  geom_vline(xintercept = min(log(meta$simpson_reciprocal)), linetype = 'dashed') +
  geom_vline(xintercept = max(log(meta$simpson_reciprocal)), linetype = 'dashed')  +
  theme(legend.position = 'none')

ave_each_fg_prior %>% 
  count(within_range) %>% 
  mutate(perc = n/(sum(n))*100)


prior_diversity %>% 
  write_rds('../data/068_prior_diversity_hist.rds'
  )
``` 


```{r all_params_csv}
# make 
post_all <-  read_csv('../data/068_div_model_fg_post.csv')

# the mrn ones need to be anonymized

# make  a forest  plot of the mrn intercepts
mrn_forest <- post_all %>% 
  gather() %>% 
  filter(str_detect(key, 'r_mrn')) %>% 
  mutate(mrn = str_extract(key, '\\[.+,'),
         mrn = str_replace(mrn, '\\[', ''),
         mrn = str_replace(mrn, ',', ''),
         patient = as.numeric(factor(mrn)),
         pid = str_pad(as.character(patient), width = 2, side = 'left', pad = '0') ,
         pid = str_glue('P{pid}'),
         key = str_glue('r_mrn[{pid},Intercept]')) 

mrn_figure <- mrn_forest %>% 
  ggplot(aes(x = value, y = pid)) +
  stat_pointinterval(.width = c(.66, .95)) +
  geom_vline(xintercept = 0, col = 'red', linetype = 'dashed') +
  labs(x = '',
       y = '', 
       title = '') +
  theme_classic() +
  theme(legend.position = 'none') +
  theme(axis.text=element_text(size=11),
        axis.title=element_text(size=11),
        aspect.ratio=1)
```


```{r all_params_csv}
ggsave('../data/S6_mrn_intercepts_forest.pdf',
       width = 280,
       height = 400, 
         #height = 60,
         units = c("mm"),
         dpi = 400, device = 'pdf', plot = mrn_figure)

ggsave('../figs/paper/S6_mrn_intercepts_forest.jpg',
       width = 280,
       height = 320, 
         #height = 60,
         units = c("mm"),
         dpi = 400, device = 'jpg', plot = mrn_figure)
```


```{r}
# make a table with the median , thinner interval two sides, thicker interval two sides for all of the parameters. 
mrn_part <- post_all %>% 
  gather() %>% 
  filter(str_detect(key, 'r_mrn')) %>% 
  mutate(mrn = str_extract(key, '\\[.+,'),
         mrn = str_replace(mrn, '\\[', ''),
         mrn = str_replace(mrn, ',', ''),
         patient = as.numeric(factor(mrn)),
         pid = str_pad(as.character(patient), width = 2, side = 'left', pad = '0') ,
         pid = str_glue('P{pid}'),
         key = str_glue('r_mrn[{pid},Intercept]')) %>% 
  group_by(key) %>% 
  tidybayes::median_qi(value , .width = c( .66, .95))

others <-  post_all %>% 
  gather() %>% 
  filter(!str_detect(key, 'r_mrn')) %>% 
  group_by(key) %>% 
  tidybayes::median_qi(value , .width = c( .66, .95))
```


```{r}
all_params <- bind_rows(mrn_part, others) %>% 
  rename(median = value) %>% 
  gather('side', 'value', median:.upper) %>% 
  mutate(name = str_glue('{side}{.width}')) %>% 
  mutate(name = str_replace(name, '^\\.','')) %>% 
  select(key, name, value) %>% 
  spread('name','value') %>% 
  select(-median0.66) %>% 
  rename(median = median0.95,
         param = key) 
all_params %>% 
  write_csv('../data/Supplementary_table1_main_model_all_params_coeff_068.csv')
```

## Posterior

### Extract the posterior samples 


```{r post_sample}
# extract posterior samples for the coeff
post_samples  <- read_csv('../data/068_div_model_fg_post.csv')

# save it out for the forest plot of the coeff
post_fg_coeff <- post_samples %>% 
  select(starts_with('b_fg')) %>% 
  gather('item', 'value')

post_fg_coeff_mean <- post_fg_coeff  %>% 
  group_by(item) %>% 
  summarise(meanperitem = mean(value))

```

```{r post_coeff_forest}
# make the forest plot of the post coeff 
# like the one on the ash abstract

post_coeff <- post_samples %>% 
  select(starts_with('b_fg')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item = str_replace(item, 'b_fg_','')) %>% 
   mutate(fgrp1 = case_when(
    item ==  'milk' ~ '1',
    item == 'meat' ~ '2',
    item ==  'egg' ~ '3',
    item ==  'legume' ~ '4',
    item == 'grain' ~ '5',
    item == 'fruit' ~ '6',
    item == 'veggie' ~ '7',
    item ==  'oils' ~ '8', 
    item ==  'sweets' ~ '9'
  ))  %>% 
  left_join(key %>% select(fgrp1, color, shortname))

fg_labels <- levels(post_coeff$shortname)


cross0 <- post_coeff %>%
  group_by(item) %>% 
  summarise(q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975)) %>% 
  mutate(Cross = if_else(q2.5 > 0 | q97.5 < 0, F, T))

# to find the quantiles of the post_coeff
post_coeff %>% 
  group_by(item) %>% 
  tidybayes::median_qi(coeff, .width = c( .66, .95))

post_coeff %>% 
  group_by(item) %>% 
  summarise(q50 = median(coeff))

post_coeff %>% 
  group_by(item) %>% 
  summarise(ave = mean(coeff))

post_coeff %>%  
  filter(item == 'fruit') %>% 
  count(coeff < 0) %>% 
  mutate(perc = n/sum(n)*100)
```

```{r}
fg_colors <- post_coeff %>% 
  distinct(shortname, color) %>% 
  select(shortname, color) %>% 
  deframe()

title1 <- bquote(Outcome: log[e]~(Simpsons~reciprocal))

div_post <- post_coeff %>% 
  left_join(cross0) %>% 
  ggplot(aes(x = coeff, y = shortname)) +
  stat_pointinterval(.width = c(.66, .95)) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  labs(x = 'ln(diversity) change per 100g of food',
       y = '', 
       title = 'Diversity') +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_manual(values = c("#EC0000", "gray40")) +
  theme(axis.text=element_text(size=8, color  = 'black'),
        axis.title=element_text(size=8),
        aspect.ratio=1)

div_post %>% 
  write_rds('../data/068_div_post.rds')

div_post
```


```{r post_coeff_binary}
coeff_bi <- post_samples %>% 
  select(starts_with('b_')) %>% 
  select(!starts_with('b_fg')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item_name = case_when(
    item ==  'b_intensitynonablative' ~ 'Intensity: nonablative',
    item == 'b_intensityablative' ~ 'Intensity: ablative',
    item ==  'b_intensityreduced' ~ 'Intensity: reduced',
    item ==  'b_empiricalTRUE' ~ 'Empirical abx exposure',
    item == 'b_TPNTRUE' ~ 'TPN exposure',
    item ==  'b_ENTRUE' ~ 'EN exposure'
  )) %>% 
  mutate(item_name = factor(item_name, levels = c('Intensity: nonablative', 'Intensity: reduced',
                                                  'Intensity: ablative', 'TPN exposure','EN exposure',
                                                  'Empirical abx exposure'))) %>% 
  mutate(grp = if_else(str_detect(item_name, 'Intensity'), 'Patient level', 'Sample level'))

# modify it to be the look that we have discussed
diversity_factor <- coeff_bi %>% 
  ggplot(aes(x = coeff, y = item_name)) +
  stat_pointinterval(.width = c(.66, .95)) +
  #scale_color_manual(values = c('#EC0000','#00468B')) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  facet_wrap(grp~ . , scales = 'free', dir = 'v') +
  labs(x = 'Coefficients',
       y = 'Factor variables',
       title = 'Diversity') +
  theme_classic() +
  theme(legend.position = 'none',
        strip.background = element_blank(),
        strip.text = element_blank(),
        aspect.ratio=1/2) 

diversity_factor %>% 
  write_rds('../data/068_diversity_factor_forest.rds')

coeff_bi %>% 
  filter(item == 'b_ENTRUE') %>% 
  count(coeff < 0) %>% 
  mutate(perc = n / sum(n)*100)


coeff_bi %>% 
  filter(!str_detect(item, 'intensity')) %>% 
  ggplot(aes(x = coeff, y = item_name)) +
  stat_pointinterval(.width = c(.66, .95)) +
  #scale_color_manual(values = c('#EC0000','#00468B')) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  facet_wrap(grp ~ . , scales = 'free', dir = 'v') +
  labs(x = 'Coefficients',
       y = 'Factor variables',
       title = 'Diversity') +
  theme_classic() +
  theme(legend.position = 'none',
        strip.background = element_blank(),
        strip.text = element_blank(),
        aspect.ratio=1) 

ggsave('../data/068_only_abx_diversity_bi.pdf', width = 3.5, height = 3)
```

# adjust the f2c

```{r forest_fg}
# make a forest plot of the fg coeff and annotate the percentage
# sort the fg in the order of 

# find the sorting order of the tree, which should be number of food codes in each fg
# fg_order <- dtb %>% distinct(Food_code) %>% mutate(fgrp1 = str_sub(as.character(Food_code),1, 1)) %>% 
#   count(fgrp1) %>% 
#   full_join(key) %>% arrange(n) %>% pull(shortname)

# calculate the percentage of > 0 and < 0 and annotate that to the figure 
percs <- post_coeff %>% 
  count(shortname, coeff > 0) %>% 
  mutate(perc =round(n/4000*100,1))  %>% select(-n) %>% 
  spread('coeff > 0', 'perc') %>% 
  rename(positive = 'TRUE', negative = 'FALSE') %>% 
  mutate(neg_num = negative) %>% 
  mutate(pos_x = 0.8, neg_x = -0.9) %>% 
  mutate(positive = str_glue('{positive}%'),
         negative = str_glue('{negative}%'))

# sort the fg in the negative perc desc order
fg_order <- percs %>% arrange(neg_num) %>% pull(shortname)

percs %>% arrange(neg_num) %>% select(shortname) %>% write_csv('../data/068_fg_sorting_order.csv')

                          # Install scales R package
library("scales") 
                                    # Amount of default colors
hex_codes1 <- hue_pal()(2)                             # Identify hex codes
hex_codes1   
```


```{r forest_fg}
div_post_ridge <- post_coeff %>% 
  left_join(percs) %>%
  mutate(shortname = factor(shortname, levels = fg_order)) %>% 
  ggplot(aes(x = coeff, y = shortname, fill = after_stat(x > 0))) +
  stat_pointinterval(.width = c( .95, .95), size = 0.1) +stat_halfeye() + 
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  geom_text(data = percs, aes(x = pos_x, y = shortname, label = positive, color = after_stat(x > 0))) +
  geom_text(data = percs, aes(x = neg_x, y = shortname, label = negative, color =after_stat(x > 0))) +
  #scale_fill_manual(values = c("gray80", "skyblue")) +
  labs(x = 'ln(diversity) change per 100g of food',
       y = '', 
       title = 'Diversity') +
  theme_classic() +
  theme(legend.position = 'none') +
  #scale_color_manual(values = c("#F8766D", "#00BFC4")) +
  theme(axis.text=element_text(size=axis_text_size, color  = 'black'),
        axis.title=element_text(size=axis_text_size),
        aspect.ratio=1)
div_post_ridge

div_post_ridge %>% 
  write_rds('../data/068_div_post_ridge.rds')


```

