---
title: "Look at binning results from dastool"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
```


```{r}
# all the irep values I got
fns <- list.files('../data/growth/irep/bhatirep/', full.names = T, pattern = '.tsv')

irep <- fns %>% 
  set_names(fns) %>% 
  purrr::map(~  read_tsv(file = ., n_max = 1 , col_types = 'cc',  skip = 2, col_names = c('bin','iRep')) %>%  select(iRep) ) %>% 
  bind_rows(.id = 'fn') %>% 
  mutate(fn = str_replace(fn, '_irep.tsv$',''),
         fn = str_replace(fn, '../data/growth/irep/bhatirep//','')) %>% 
  separate(fn, into = c('sampleid','samplebin'), sep = '__concat__', remove = T) %>% 
  mutate(iRep = as.numeric(iRep)) %>% 
  mutate(samplebin = str_replace(samplebin, '_irep_dastool.tsv','')) %>% 
  mutate(sbid = str_glue('{sampleid}__{samplebin}'))
```


```{r}
tb <- read_tsv('../data/growth/bhatpipeline/binning_table_all_simple.tsv') %>% 
  rename_all(~ gsub("\\.", "_", .)) %>% 
  filter(bin_quality_call %in% c('2) medium quality','3) high quality Nayfach','4) high quality Bowers'))  %>% 
  filter(Completeness >= 75) %>% 
  mutate(Sample = str_replace(Sample, '__concat',''),
         sbid = str_glue('{Sample}__{Bin}')) %>% 
  inner_join(irep, by  = 'sbid') %>% 
  distinct(Sample, best_species, .keep_all = T)
  
# combined %>% 
#   mutate(gt15 = if_else(iRep > 1.5, T, F)) %>% 
#   count(gt15) %>% 
#   mutate(perc = n/sum(n)*100)
```

```{r}
# meta data of the samples
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')

selected <- read_csv('../data/growth/shotgun_request_meta_full.csv') %>% 
  select(sampleid, mrn, sdrt) %>% 
  mutate(sampleid = str_replace(sampleid, 'FMT\\.','FMT_'))


# explore the bins 
df <- tb %>% 
  count(sampleid) %>% 
  left_join(bind_rows(meta %>% select(sampleid, mrn, sdrt), selected) %>% distinct(sampleid, mrn, sdrt), by = "sampleid")

df %>% 
  ggbarplot(x = 'sdrt', y = 'n', facet.by = 'mrn', label = T)
```
```{r}
# the distribution of the bin numbers in each sample
tb %>%  
  count(sampleid) %>% 
  ggboxplot(y = 'n', add = 'jitter') +
  theme_pubclean()

# the irep value 
tb %>% 
  split(is.na(.$iRep)) %>% 
  map_dfr(~ nrow(x = .)) %>% 
  gather() %>% 
  mutate(perc = round(value/sum(value)*100, 2))

# ignore the NA irep values for now
dat <- tb %>% 
  filter(!is.na(iRep))

dat %>% 
  gghistogram(x = 'iRep')

# look at the sample that has the most bins
most <- dat %>%      
  filter(sampleid == 'FMT_0217C') %>% 
  select(sbid, best_species, best_level, iRep)

# look at how many are unclassified 
dat %>% 
  split(.$best_species == 'Unclassified') %>% 
  map_dfr(~ nrow(x = .)) %>% 
  gather() %>% 
  mutate(perc = round(value/sum(value)*100, 2))

# look at the best level column
dat %>% 
  count(best_level, sort = T)  

best_species <- dat %>% 
  count(best_species, best_level, sort = T)  
best_species

Entero <- dat %>% 
  filter(str_detect(best_species, 'Enterococcus'))

# the 4 samples that have 100% E faecium
Entero %>% 
  filter(str_detect(sampleid, '^2142'))
```

```{r}
# join with the meta table 
# there are p2d and d0 diet data
combined <- dat %>% 
  inner_join(meta , by = "sampleid") %>% 
  select(sampleid, iRep, sbid, mrn, best_level, best_species, starts_with('fg'), simpson_reciprocal, empirical)

# some samples don't have diet data 
combined %>% 
  distinct(sampleid) %>% 
  nrow()

# save this table , very important 
combined %>% 
  write_csv('../data/growth/irep_combined_res.csv') 

combined <- read_csv('../data/growth/irep_combined_res.csv')
```

```{r coverage}
# check the coverage of these bins
fns <- list.files('../data/growth/irep/coverage_from_sam/', pattern = 'txt', full.names = T)
covs <- fns %>% 
  set_names(fns) %>% 
  imap(~ read_tsv(.x) %>% 
  summarise(median_depth = median(meandepth)))

covs_df <- covs %>% 
  bind_rows(.id = 'fn') %>% 
  mutate(fn = str_replace(fn, '../data/growth/irep/coverage_from_sam//',''),
         fn = str_replace(fn, '__concat__dastools_align',''),
         fn = str_replace(fn, '_coverage.txt',''))  %>% 
  rename(sbid = fn)  %>% 
  inner_join(combined, by = "sbid")

# basically all but one have cov greater than 5. 

final_combined <- covs_df %>% 
  filter(median_depth > 5)

final_combined %>% 
  write_csv('../data/growth/finalized_irep_combined_res.csv')
```


```{r}
combined %>% 
  filter(str_detect(best_species, 'Blautia')) %>% 
  group_by(sampleid) %>% 
  summarise(ave_irep = mean(iRep)) %>% 
  inner_join(meta) %>% 
  gather('grp', 'gram', fg_egg:fg_veggie) %>% 
  #filter(iRep < 4) %>% 
  ggscatter(x = 'gram', y = 'ave_irep', 
          add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "pearson",  label.sep = "\n")) +
  facet_wrap(grp ~ ., scales = 'free')
 
combined %>% 
  filter(str_detect(best_species, 'Enterococcus')) %>% 
  group_by(sampleid) %>% 
  summarise(ave_irep = mean(iRep)) %>% 
  inner_join(meta) %>% 
  gather('grp', 'gram', fg_egg:fg_veggie) %>%
  filter(ave_irep < 4) %>% 
  ggscatter(x = 'gram', y = 'ave_irep', 
          add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "pearson",  label.sep = "\n")) +
  facet_wrap(grp ~ ., scales = 'free') 


test <- combined %>% 
  filter(str_detect(best_species, 'Enterococcus')) %>% 
  group_by(sampleid) %>% 
  summarise(ave_irep = mean(iRep)) %>% 
  inner_join(meta) %>% 
  gather('grp', 'gram', fg_egg:fg_veggie)
```
 

```{r}
# per sample mean of irep
df <- combined %>% 
  group_by(sampleid) %>% 
  summarise(ave_irep = mean(iRep)) %>% 
  inner_join(meta)

df %>% 
  gather('grp', 'gram', fg_egg:fg_veggie) %>% 
  #filter(str_detect(best_species, 'Escherichia')) %>% 
  #filter(iRep < 4) %>% 
  ggscatter(x = 'gram', y = 'ave_irep', 
          add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n")) +
  facet_wrap(grp ~ ., scales = 'free') 

# milk fruit sweets and veggie be positively linked with mean irep
# what's driving?
```
```{r}
# to look at samples with mean irep > 1.45
# look <- df %>% 
#   filter(ave_irep > median(df$ave_irep)) %>% 
#   pull(sampleid)
# 
# # the distribution of the mean irep
# summary(df$ave_irep)
# 
# look_df <- combined %>% 
#   filter(sampleid %in% look) %>% 
#   filter(best_species != 'Unclassified') %>% 
#   mutate(shortname = str_sub(best_species, 1,5)) 
#   
# library(randomcoloR)
# n <- 14
# palette <- distinctColorPalette(n)
# pie(rep(1, n), col=palette)
# 
# colors <- look_df %>% 
#   count(shortname, sort = T) %>% 
#   mutate(color = c(palette, rep('gray', 33)))
# 
# look_df_ <- look_df %>% 
#   left_join(colors %>% 
#               select(shortname, color))
# 
# look_df %>% 
#   distinct(sampleid, .keep_all = T) %>% 
#   count(mrn, sort = T)
# 
# look_df %>% 
#   split(.$mrn) %>% 
#   map(~ ggdotchart(data = ., x = 'best_species', y = 'iRep', sorting = 'descending') +
#         geom_hline(yintercept = median(df$ave_irep))) 
# 
# 
# look_df_ %>% 
#   filter(iRep  > median(df$ave_irep)) %>% 
#   filter(grp %in% c('fg_milk','fg_fruit','fg_sweets','fg_veggie')) %>% 
#   split(.$mrn) %>% 
#   map(~ ggscatter(data = ., x = 'gram', y = 'iRep', facet.by = 'grp', label = 'shortname', repel = T, color = 'shortname') +
#         geom_hline(yintercept = median(df$ave_irep))+
#         scale_color_manual(values=colors$color, labels = colors$shortname))
```

```{r}
# look_df_ %>% 
#   filter(iRep  > median(df$ave_irep)) %>% 
#   filter(grp %in% c('fg_milk','fg_fruit','fg_sweets','fg_veggie')) %>% 
#   ggscatter(x = 'gram', y = 'iRep', facet.by = 'grp', color = 'shortname') +
#         geom_hline(yintercept = median(df$ave_irep)) +
#   scale_color_manual(values=colors$color, labels = colors$shortname)
```


## the 5 taxa we are interested in

```{r}
target <- c('Blautia','Enterococcus','Lactobacillus','Rothia','Klebsiella')
# if including the outlier
withoutlier <- target %>% 
  set_names(target) %>% 
  imap(function(.x, .y){
    combined %>% 
      filter(str_detect(best_species, .x)) %>% 
      group_by(sampleid) %>% 
      summarise(ave_irep = mean(iRep)) %>% 
      inner_join(meta) %>% 
      gather('grp', 'gram', fg_egg:fg_veggie) %>% 
      #filter(iRep < 4) %>% 
      ggscatter(x = 'gram', y = 'ave_irep', title = .x,
              add = "reg.line",  # Add regressin line
               add.params = list(color = "blue", fill = "lightgray"), # Customize line
               conf.int = TRUE, # Add confidence interval
               cor.coef = TRUE, # Add correlation coefficient.
               cor.coeff.args = list(method = "spearman",  label.sep = "\n", color = 'red')) +
      facet_wrap(grp ~ ., scales = 'free')
  }) 

withoutlier_list <- ggarrange(plotlist = withoutlier, nrow = length(target)) 
ggsave('../figs/mean_irep_5_genus_scatter_with_outlier.pdf', width = 9, height = 28, plot = withoutlier_list)

# if not including the outlier
no_outlier <- target %>% 
  set_names(target) %>% 
  imap(function(.x, .y){
    combined %>% 
      filter(str_detect(best_species, .x)) %>% 
      group_by(sampleid) %>% 
      summarise(ave_irep = mean(iRep)) %>% 
      inner_join(meta) %>% 
      gather('grp', 'gram', fg_egg:fg_veggie) %>% 
      filter(ave_irep < 4) %>% 
      ggscatter(x = 'gram', y = 'ave_irep', title = .x,
              add = "reg.line",  # Add regressin line
               add.params = list(color = "blue", fill = "lightgray"), # Customize line
               conf.int = TRUE, # Add confidence interval
               cor.coef = TRUE, # Add correlation coefficient.
               cor.coeff.args = list(method = "spearman",  label.sep = "\n", color = 'red')) +
      facet_wrap(grp ~ ., scales = 'free')
  }) 

no_outlier_list <- ggarrange(plotlist = no_outlier, nrow = length(target)) 
ggsave('../figs/mean_irep_5_genus_scatter_No_outlier.pdf', width = 9, height = 28, plot = no_outlier_list)
 
```

```{r}
# make a table that records the pvalue and the spearman correlation  
spearman <- target %>% 
  set_names(target) %>% 
  imap(function(.x, .y){
    combined %>% 
      filter(str_detect(best_species, .x)) %>% 
      group_by(sampleid) %>% 
      summarise(ave_irep = mean(iRep)) %>% 
      inner_join(meta, by = "sampleid") %>% 
      gather('grp', 'gram', fg_egg:fg_veggie) %>% 
      split(.$grp) %>% 
      map(function(df){
        res = cor.test(df$ave_irep, df$gram, method = 'spearman', exact = F)
        return(list(pval = res$p.value, rho = res$estimate))
      }) %>% 
      bind_rows(.id = 'grp') %>% 
      mutate(genus = .y)
  })  %>% 
  bind_rows()


spearman_no_outlier <-  target %>% 
  set_names(target) %>% 
  imap(function(.x, .y){
    combined %>% 
      filter(str_detect(best_species, .x)) %>% 
      group_by(sampleid) %>% 
      summarise(ave_irep = mean(iRep)) %>% 
      inner_join(meta, by = "sampleid") %>% 
      gather('grp', 'gram', fg_egg:fg_veggie) %>% 
      filter(ave_irep < 4) %>% 
      split(.$grp) %>% 
      map(function(df){
        res = cor.test(df$ave_irep, df$gram, method = 'spearman', exact = F)
        return(list(pval = res$p.value, rho = res$estimate))
      }) %>% 
      bind_rows(.id = 'grp') %>% 
      mutate(genus = .y)
  })  %>% 
  bind_rows() 

both <- bind_rows(
  spearman_no_outlier %>% mutate(condition = 'no_outlier'),
  spearman %>% mutate(condition = 'yes_outlier')
)

both %>% 
  write_csv('../data/growth/mean_irep_fg_spearman_table.csv')

sig <- both %>% 
  filter(pval < 0.05)

```

```{r}
# all taxa in a sample
# with that outlier 
combined %>% 
  group_by(sampleid, fg_egg, fg_fruit, fg_grain, fg_legume, fg_meat, fg_milk, fg_oils, fg_sweets, fg_veggie) %>% 
  summarise(ave_irep = mean(iRep)) %>% 
  gather('grp', 'gram', fg_egg:fg_veggie) %>% 
  ggscatter(x = 'gram', y = 'ave_irep', title = '',
              add = "reg.line",  # Add regressin line
               add.params = list(color = "blue", fill = "lightgray"), # Customize line
               conf.int = TRUE, # Add confidence interval
               cor.coef = TRUE, # Add correlation coefficient.
               cor.coeff.args = list(method = "spearman",  label.sep = "\n", color = 'red')) +
      facet_wrap(grp ~ ., scales = 'free')


ggsave('../data/growth/sample_mean_irep.pdf', width = 10, height = 7)

combined %>% 
  distinct(sampleid)


combined %>% 
      filter(str_detect(best_species, 'Enterococcus')) %>% 
      distinct(sampleid) 
  
```

```{r}
# ok you can do this, you can get this sh*t done
# add error bars with min and max for each dot 

combined_mean <- combined %>% 
  filter(iRep < 4) %>% # what if I filter out that very high value
  group_by(sampleid, fg_egg, fg_fruit, fg_grain, fg_legume, fg_meat, fg_milk, fg_oils, fg_sweets, fg_veggie) %>% 
  summarise(ave_irep = mean(iRep),
            min_val = min(iRep),
            max_val = max(iRep)) %>% 
  gather('grp', 'gram', fg_egg:fg_veggie) 

combined_mean %>% 
  ggscatter(x = 'gram', y = 'ave_irep', title = '',
              add = "reg.line",  # Add regressin line
               add.params = list(color = "blue", fill = "lightgray"), # Customize line
               conf.int = TRUE, # Add confidence interval
               cor.coef = TRUE, # Add correlation coefficient.
               cor.coeff.args = list(method = "spearman",  label.sep = "\n", color = 'red')) +
  geom_pointrange(aes(ymin  = min_val, ymax  = max_val), fatten = 2, col = 'red')  +
   facet_wrap(grp ~ ., scales = 'free')     

ggsave('../data/growth/sample_mean_irep_with_sample_min_and_max_no_outlier.pdf', width = 10, height = 7)
```

```{r}
# only look at milk and fruit for now since there is a sig p value
combined_mean %>% 
  filter(grp %in% c('fg_milk','fg_fruit')) %>% 
  split(.$grp) %>% 
  imap(function(.x, .y){
    ggscatter( data = .x ,x = 'gram', y = 'ave_irep', title = .y, label = 'sampleid', 
              add = "reg.line",  # Add regressin line
               add.params = list(color = "blue", fill = "lightgray"), # Customize line
               conf.int = TRUE, # Add confidence interval
               cor.coef = TRUE, # Add correlation coefficient.
               cor.coeff.args = list(method = "spearman",  label.sep = "\n", color = 'red')) +
    geom_pointrange(aes(ymin  = min_val, ymax  = max_val), fatten = 2, col = 'red')
    
    ggsave(str_glue('../data/growth/combined_irep_{.y}.pdf'), width = 10)
  })

```

## for paper figure

```{r}
# the fruits and enterococcus irep alone
combined %>% 
  filter(str_detect(best_species, 'Enterococcus')) %>% 
  group_by(sampleid) %>% 
  summarise(ave_irep = mean(iRep)) %>% 
  inner_join(meta) %>% 
  filter(ave_irep < 4) %>% 
  ggscatter(x = 'fg_fruit', y = 'ave_irep', title = 'no outlier for Enterococcus only',
          add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n"))   +
  theme_light() +
  theme(aspect.ratio = 1)

ggsave('../figs/fruit_enterococcus_no_outlier.jpg', width = 5)
```


```{r}
combined %>% 
  filter(str_detect(best_species, 'Enterococcus')) %>% 
  group_by(sampleid) %>% 
  summarise(ave_irep = mean(iRep)) %>% 
  inner_join(meta) %>% 
  #filter(ave_irep < 4) %>% 
  ggscatter(x = 'fg_fruit', y = 'ave_irep', title = 'yes outlier for Enterococcus only',
          add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n"))   +
  theme_light() +
  theme(aspect.ratio = 1)

ggsave('../figs/fruit_enterococcus_yes_outlier.jpg', width = 5)
```

```{r}
# the average but excluding the enterococcus
combined %>% 
  filter(!str_detect(best_species, 'Enterococcus')) %>% 
  group_by(sampleid) %>% 
  summarise(ave_irep = mean(iRep)) %>% 
  inner_join(meta) %>% 
  ggscatter(x = 'fg_fruit', y = 'ave_irep', title = 'Average of all taxa excluding Enterococcus',
          add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n"))   +
  theme_light() +
  theme(aspect.ratio = 1)

ggsave('../figs/fruit_no_enterococcus_ave.jpg', width = 5)
```

### pearson cor

```{r}
combined %>% 
  filter(str_detect(best_species, 'Enterococcus')) %>% 
  group_by(sampleid) %>% 
  summarise(ave_irep = mean(iRep)) %>% 
  inner_join(meta) %>% 
  filter(ave_irep < 4) %>% 
  ggscatter(x = 'fg_fruit', y = 'ave_irep', title = 'no outlier for Enterococcus only (Pearson)',
          add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "pearson",  label.sep = "\n"))   +
  theme_light() +
  theme(aspect.ratio = 1)

ggsave('../figs/fruit_enterococcus_no_outlier_Pearson.jpg', width = 5)




combined %>% 
  filter(str_detect(best_species, 'Enterococcus')) %>% 
  group_by(sampleid) %>% 
  summarise(ave_irep = mean(iRep)) %>% 
  inner_join(meta) %>% 
  #filter(ave_irep < 4) %>% 
  ggscatter(x = 'fg_fruit', y = 'ave_irep', title = 'yes outlier for Enterococcus only (Pearson)',
          add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "pearson",  label.sep = "\n"))   +
  theme_light() +
  theme(aspect.ratio = 1)

ggsave('../figs/fruit_enterococcus_yes_outlier_pearson.jpg', width = 5)

combined %>% 
  filter(!str_detect(best_species, 'Enterococcus')) %>% 
  group_by(sampleid) %>% 
  summarise(ave_irep = mean(iRep)) %>% 
  inner_join(meta) %>% 
  ggscatter(x = 'fg_fruit', y = 'ave_irep', title = 'Average of all taxa excluding Enterococcus (pearson)',
          add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "pearson",  label.sep = "\n"))   +
  theme_light() +
  theme(aspect.ratio = 1)

ggsave('../figs/fruit_no_enterococcus_ave_pearson.jpg', width = 5)
```



