---
title: "Updated forest plot"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
```

Following 068_model_with_bayesian

# sugar content in each food group

```{r}
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
# make modifications for the abstract
# calculate the sugar percentage in each food group using dtb
sugar_perc_all <- dtb %>% 
  select(Food_code, ends_with('_g')) %>% 
  mutate(fgrp1 = str_sub(Food_code, 1, 1)) %>% 
  select(-Food_code) %>% 
  gather('type', 'gram', Protein_g:Sodium_g) 

sugar_perc_total <- sugar_perc_all  %>% 
  group_by(fgrp1) %>% 
  summarise(total = sum(gram))

sugar_perc_sugar <- sugar_perc_all  %>% 
  filter(type == 'Sugars_g') %>% 
  group_by(fgrp1) %>% 
  summarise(total_sugar = sum(gram))

sugar_df <- sugar_perc_total %>% 
  full_join(sugar_perc_sugar) %>% 
  mutate(sugar_frac = total_sugar/total) %>% 
  mutate(fg1_name = case_when(
    fgrp1 == '1' ~ 'fg_milk',
    fgrp1 == '2' ~ 'fg_meat',
    fgrp1 == '3' ~ 'fg_egg',
    fgrp1 == '4' ~ 'fg_legume',
    fgrp1 == '5' ~ 'fg_grain',
    fgrp1 == '6' ~ 'fg_fruit',
    fgrp1 == '7' ~ 'fg_veggie',
    fgrp1 == '8' ~ 'fg_oils', 
    fgrp1 == '9' ~ 'fg_sweets',
    fgrp1 == 'N' ~ 'fg_ndrink',
    fgrp1 == 'E' ~ 'fg_EN'
  )) %>% 
  mutate(sugar_perc = round(sugar_frac*100, 1)) %>% 
  mutate(sugar_perc = str_glue('{sugar_perc}%')) %>% 
  mutate(fg1_name = str_replace(fg1_name, 'fg_',''))
```

# patient exposed 

```{r}
# what % of patients out of the 97 had any amount of that food group?

pt_perc <- dtb %>% 
  select(mrn, Food_code) %>% 
  mutate(fgrp1 = str_sub(Food_code, 1, 1)) %>% 
  distinct(mrn, fgrp1) %>% 
  dplyr::count(fgrp1) %>% 
  mutate(fg1_name = case_when(
    fgrp1 == '1' ~ 'fg_milk',
    fgrp1 == '2' ~ 'fg_meat',
    fgrp1 == '3' ~ 'fg_egg',
    fgrp1 == '4' ~ 'fg_legume',
    fgrp1 == '5' ~ 'fg_grain',
    fgrp1 == '6' ~ 'fg_fruit',
    fgrp1 == '7' ~ 'fg_veggie',
    fgrp1 == '8' ~ 'fg_oils', 
    fgrp1 == '9' ~ 'fg_sweets',
    fgrp1 == 'N' ~ 'fg_ndrink',
    fgrp1 == 'E' ~ 'fg_EN'
  )) %>% 
  mutate(fg1_name = str_replace(fg1_name, 'fg_','')) %>% 
  mutate(pt_perc = round(n/97*100, 1)) %>% 
  mutate(pt_perc = str_glue('{pt_perc}%')) 
```


```{r}
nodes <- read_tsv('../data/source/NodeLabels_withcomma.txt', col_types = 'cc') %>% 
  filter(nchar(Level.code) == 1) %>% 
  rename(fgrp1 = Level.code, 
         fdesc = Main.food.description) 
  
```

```{r}
res <- read_csv('../data/brms_model_var_res_updated.csv') %>% 
  group_by(item, meanperitem) %>% 
  summarise(q2.5 = quantile(value, probs = 0.025),
            q97.5 = quantile(value, probs = 0.975)) %>% 
  filter(str_detect(item, '_fg_')) %>% 
  mutate(item = str_replace(item, 'b_fg_','')) %>% 
   mutate(fgrp1 = case_when(
    item ==  'milk' ~ '1',
    item == 'meat' ~ '2',
    item ==  'egg' ~ '3',
    item ==  'legume' ~ '4',
    item == 'grain' ~ '5',
    item == 'fruit' ~ '6',
    item == 'veggie' ~ '7',
    item ==  'oils' ~ '8', 
    item ==  'sweets' ~ '9'
  ))  %>% 
  left_join(nodes) %>% 
  mutate(fdesc = str_replace_all(fdesc, '_',' ')) %>% 
  mutate(fdesc = str_wrap(fdesc, width = 35, indent = 2, exdent = 0)) %>% 
  ungroup() %>% 
  arrange(meanperitem)  %>% 
  mutate(fdesc = str_replace(fdesc, 'and','&')) %>% 
  full_join(sugar_df %>% select(item = fg1_name, sugar_perc)) %>% 
  full_join(pt_perc %>% select(item = fg1_name, pt_perc)) 

# no need to times 100 since the original fg intake already divided by 100
bottom_ <- res %>%  
  arrange(meanperitem) %>% 
  ggscatter(x = 'fdesc', y = 'meanperitem', color = 'red', size = 3,
            ylab = 'Regression coefficients',
            xlab = 'High-level food categories\n(FNDDS)') + 
  geom_errorbar(aes(ymin  = q2.5,ymax  = q97.5),width = 0.3, size  = 0.7,
                position = "dodge", color="black") +
  labs(title = 'Multivariate mixed-effect model of fecal diversity as a function of food',
       subtitle = '(Controlling for clinical variables, time, and antibiotic exposure)') + 
  geom_point(aes(x = fdesc, y = meanperitem), color = 'red', size = 3) +
  geom_hline(yintercept = 0, col = "red",   size = 1) +
  geom_text(aes(x = fdesc, y = -1.2, label = sugar_perc)) +
  #geom_text(aes(x = fdesc[9], y = -1.2, label = 'Sugar\ncontent'), nudge_x = +0.9) +
  geom_text(aes(x = fdesc, y = -0.9, label = pt_perc)) +
  #geom_text(aes(x = fdesc[9], y = -0.9, label = 'Patients\nexposed'), nudge_x = 0.9) +
  coord_flip()+
  #theme_classic() +
  theme(axis.text=element_text(size=11),
        axis.title=element_text(size=11),
        axis.title.x =element_text(hjust = 0.6),
        plot.title = element_text(size=11, face = 'bold', hjust = 0),
        plot.subtitle = element_text(margin = margin(b = 20))) +
  ylim(-1.2, 1.4) 
  

bottom_

ggsave('../figs/updated_forest_coeff.pdf', width = 9,  height = 4.5, plot = bottom_)
```



```{r}
# assemble to make the full panel 
top <- read_rds('../figs/abstract_top_diversity.rds')

bottom <-  cowplot::plot_grid(bottom_,
          nrow = 1, 
          labels = "C",
          axis = 'brlt')

whole <-  cowplot::plot_grid(top, bottom,
          nrow = 2, 
          align = 'hv',
          #rel_heights = c(1,1),
          labels = NULL,
          axis = 'brlt')  +
  ggsave('../figs/all_fig_ASH.pdf', width = 10, height = 9)
```


```{r}
ptb <- read_csv('../data/cleaned_patients/diet_patients_97.csv')
en <- dtb %>% 
  filter(Meal == 'EN') %>% 
  distinct(mrn)

```

