---
title: "The fig1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setting}
library(tidyverse)
library(ggpubr)
library(cowplot)
library(ggimage)
library(lemon)
axis_text_size <- 8
axis_title_size <- 10
stip_txt_size <- 8
alpha_val <- 0.05
point_size <- 1.2
scatter_col <- 'gray14'
pick_point_size <- 1
pick_line_size <- 0.5
example_pt_line_size <- 0.3
diet_line_color <- '#E41A1C'
stool_line_color <- 'blue'
umap_pt_size <- 1

# the colors for each food group specified and saved here
fpalette <- tribble(
  ~fg1_name, ~color, ~fgrp1,
  #--|--|
  'fg_milk' , '#3498DB', '1',
  'fg_meat' , '#591605', '2',
  'fg_egg' , '#F1C40F', '3',
  'fg_legume' , '#E67E22', '4',
  'fg_grain' , '#D35400', '5',
  'fg_fruit' , '#7D3C98', '6',
  'fg_veggie' , '#229954', '7',
  'fg_oils' , '#707B7C',  '8',
  'fg_sweets' , '#db2589' , '9'
) 
library(vdbR)
connect_database()
get_table_from_database('asv_alpha_diversity_ag')
get_table_from_database('shotgun_lookup_ad')
```

# fig1 bottom 3

The first 2 need to be redo, since the data has been updated.

```{r load_table}
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')

dtb %>% distinct(Food_code)

# how many days of data among all of the patients?
dtb %>% count(mrn,  fdrt) %>% 
  count(mrn) %>% 
  summarise(total_days = sum(n))

dtb %>% distinct(Food_NSC)

dtb %>% count(mrn, fdrt) %>% 
  distinct(mrn, fdrt) 
  
```

```{r}
# summarize how many diet data days we have for the patients?  Median min and max.  
dtb %>% 
  distinct(mrn, fdrt) %>% 
  #count(mrn) %>% 
  summary

# -how common was it? how many of 97 patients consumed at least 1?
#-what fraction of meals (or fraction of days) included a smoothie?
#-for how many meals  (or days) was smoothie the only thing consumed?

# find the food code that has the highest per meal average consumption
smoothie <- dtb %>% 
  group_by(Food_code, description) %>% 
  summarise(total = sum(dehydrated_weight))  %>% 
  arrange(desc(total)) %>% 
  ungroup() %>% 
  slice(1)  %>% 
  pull(Food_code)
```


```{r stool_alpha}

stool_alpha <- meta %>% 
  ggscatter(x = 'sdrt', y = 'simpson_reciprocal', alpha = alpha_val, size = point_size, 
            xlab = 'Day relative to HCT', shape = 'triangle',
            ylab = expression(Microbiome~alpha~diversity),
            title = expression(Microbiome~alpha~diversity),
            add = "loess", conf.int = TRUE, 
            add.params = list(color = stool_line_color, fill = "darkblue", size = 1)) +
   scale_x_continuous( breaks = seq(0, 50, 20)) + 
  theme(axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        aspect.ratio=1) +
  theme(axis.title = element_blank(),
        plot.title = element_blank())
stool_alpha
```

```{r caloric_intake}
day_calori <- dtb %>% 
  group_by(mrn, fdrt) %>% 
  summarise(daycal = sum(Calories_kcal))

# REMEMBER THAT IN AXIS LABLE YOU NEED TO TIMES THE 1000 BACK!!!!!!
day_cal <- day_calori %>% 
  mutate(daycal = daycal/1000) %>% 
  ggscatter(x = 'fdrt', y = 'daycal', alpha = alpha_val, size = point_size, 
            xlab = 'Day relative to HCT',
            ylab = 'Daily caloric intake',
            title = 'Daily caloric intake',
            color = scatter_col,
             add = "loess", conf.int = TRUE, 
            add.params = list(color = diet_line_color, fill = "hotpink", size = 1)) +  
   scale_x_continuous( breaks = seq(0, 50, 20)) + 
  theme(axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        aspect.ratio=2)
```

```{r faith}
# this faith pd is recently calculated in 2021-07
faith <- read_tsv('../data/cleaned_diet_data/FINAL_97_faith_pd/alpha-diversity.tsv') %>% 
  separate(...1, into = c('mrn', 'fdrt'), sep = 'd', convert = T)  %>% 
  mutate(mrn = as.numeric(str_replace(mrn, 'P','')))

# REMEMBER THAT IN AXIS LABLE YOU NEED TO TIMES THE 1000 BACK!!!!!!
diet_alpha <- faith %>% 
  mutate(faith_pd = faith_pd/1000) %>% 
  ggscatter('fdrt', 'faith_pd', 
             alpha = alpha_val,size = point_size, 
            color = scatter_col, 
            ylab = expression(Diet~alpha~diversity), 
            xlab = 'Day relative to HCT',
            title = expression(Diet~alpha~diversity),
             add = "loess", conf.int = TRUE, 
            add.params = list(color = diet_line_color, fill = "hotpink", size = 1)) +
   scale_x_continuous( breaks = seq(0, 50, 20)) + 
  theme(axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        #plot.title = element_text(size=11, hjust = 0.5,  face = 'bold')
        ) + 
  theme(aspect.ratio=2)
```

```{r food2}
# make a combined version of the faith and the day_cal
food <- day_calori %>% 
  full_join(faith)

food2 <- food %>% 
  gather('type', 'value', daycal:faith_pd) %>% 
  mutate(value = value/1000) %>% 
  ggscatter('fdrt', 'value', 
             alpha = 0.02,size = point_size, 
            color = scatter_col, 
            ylab = expression(Diet~alpha~diversity), 
            xlab = 'Day relative to HCT',
            title = 'Daily caloric intake',
             add = "loess", conf.int = TRUE, 
            add.params = list(color = diet_line_color, fill = "hotpink", size = 1)) +
  facet_grid(type ~ .) +
  scale_x_continuous( breaks = seq(0, 50, 20)) + 
  theme_classic() +
  theme(axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        strip.background = element_blank(),
        strip.text = element_blank(),
        #plot.title = element_text(size=11, hjust = 0.5,  face = 'bold')
        ) + 
  theme(aspect.ratio=1)
```


# fig1 top 3

```{r}
# the patient that is picked to showcase the timeline in data collection
#pick <- read_csv('../figs/paper/data/patient_pick_d0_diet.csv')
```

```{r umap}
dcoords <- read_csv('../data/016_umap_embedding_for_angel.csv')
link <- read_csv('../data/cleaned_diet_data/deidentify_dsample_map.csv')
coord <- dcoords %>% 
  inner_join(link) %>% 
  select(-fid, -pt)

fcts_fg <-  read_csv('../data/cleaned_diet_data/summarize_food_groups_pt_daily.csv')
```


```{r umap}
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv')

fcts_fg_dom <- fcts_fg %>%
  group_by(mrn, fdrt) %>% 
  arrange(-grp_frac, .by_group = T) %>% 
  slice(1) %>% 
  ungroup() %>% 
  transmute(fid = str_glue('P{mrn}d{fdrt}'),
            fg1_dom = fg1_name) %>% 
  inner_join(link %>% select(fid, index_column))
   
df <- coord %>% 
  inner_join(fcts_fg_dom) %>% 
  left_join(fpalette %>% select(fg1_dom = fg1_name, color)) %>% 
  add_count(fg1_dom) %>% 
  rename(fg1_name = fg1_dom) %>% 
  left_join(key )

color_key <- df %>% 
  ungroup() %>% 
  distinct(shortname, color) %>% 
  select(shortname, color) %>% 
  #mutate(shortname = factor(shortname)) %>% 
  #arrange(shortname) %>% 
  deframe()

fig1_umap <- df %>% 
  arrange(desc(n)) %>% 
  ggscatter(x = 'taxumap1', y = 'taxumap2', color = 'shortname', alpha = 1,size = umap_pt_size , shape = 16,
            xlab = 'TaxUMAP1', ylab = 'TaxUMAP2') +
  scale_color_manual(values = color_key) +
  theme_classic() +
  #lemon::coord_capped_cart(bottom = 'both', left = 'both') +
  theme(legend.position = "none",
        line = element_blank(),
        legend.title = element_blank(),
        axis.title=element_blank(),
        axis.text= element_blank(),
        axis.ticks = element_blank(),
                 panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
    panel.grid.major = element_blank(), #remove major gridlines
    panel.grid.minor = element_blank(), #remove minor gridlines
    legend.background = element_rect(fill='transparent'), #transparent legend bg
    legend.box.background = element_rect(fill='transparent') ,
        aspect.ratio=1) +
  guides(colour = guide_legend(override.aes = list(alpha=1)))
ggsave( '../data/072_fig1_umap.png', dpi = 300, width = 2.5, height = 2.5,plot = fig1_umap, bg = "transparent")
```

```{r umap_faith}
# another umap colored by the diet diversity?
another <- df %>% 
  full_join(faith)

library(viridis)
umap_faith <- another %>% 
  arrange(desc(n)) %>% 
  mutate(log10faith = log10(faith_pd + 1)) %>% 
  ggscatter(x = 'taxumap1', y = 'taxumap2', color = 'faith_pd', alpha = 1,size = umap_pt_size, shape = 16,
            xlab = '', ylab = '') +
  scale_color_viridis() +
  theme_classic() +
  #lemon::coord_capped_cart(bottom = 'both', left = 'both') +
  theme(
        line = element_blank(),
        legend.title = element_blank(),
        axis.title=element_blank(),
        axis.text= element_blank(),
        axis.ticks = element_blank(),
        aspect.ratio=1,
                 panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
    panel.grid.major = element_blank(), #remove major gridlines
    panel.grid.minor = element_blank(), #remove minor gridlines
    legend.background = element_rect(fill='transparent'), #transparent legend bg
    legend.box.background = element_rect(fill='transparent') ,
        legend.position = 'none')
ggsave( '../data/072_umap_faith.png', dpi = 300, width = 2.5,height = 2.5, plot = umap_faith, bg = "transparent")
```

```{r umap_caloric}
# another umap colored by the daily caloric intake
umap_cal <- df %>% 
  full_join(day_calori)

library(viridis)
umap_caloric <- umap_cal %>% 
  arrange(desc(n)) %>% 
  ggscatter(x = 'taxumap1', y = 'taxumap2', color = 'daycal', alpha = 1,size = umap_pt_size , shape = 16,
            xlab = '', ylab = '') +
  paletteer::scale_color_paletteer_c("viridis::plasma") +
  theme_classic() +
  #lemon::coord_capped_cart(bottom = 'both', left = 'both') +
  theme(legend.position = "none",
        line = element_blank(),
        legend.title = element_blank(),
        axis.title=element_blank(),
        axis.text= element_blank(),
        axis.ticks = element_blank(),
         panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
    panel.grid.major = element_blank(), #remove major gridlines
    panel.grid.minor = element_blank(), #remove minor gridlines
    legend.background = element_rect(fill='transparent'), #transparent legend bg
    legend.box.background = element_rect(fill='transparent') ,
        aspect.ratio=1)
umap_caloric

ggsave( '../data/072_umap_caloric.png', dpi = 300, width = 2.5, height = 2.5,plot = umap_caloric, bg = "transparent")
```

```{r umap_time}
# cuztomizing the times bins of the drt
cutoff = 0 # Day 0 is conveneint but this can be varied
n_groups_pre = 3;  # all HCT days <0 will be split into 3 bins; can vary this number to play
n_groups_post = 6; # all HCT days >0 will be split into 6 bins; can vary this number to play

# split the fdrt into groups:
umap_time <- umap_cal %>% 
  select(taxumap1, taxumap2, fdrt)  

times <- umap_time %>% select( fdrt)  

splits <- times %>% 
  split(.$fdrt <= 0)

pre <- splits %>% 
  pluck('TRUE') %>% 
  mutate(bin = cut_number(fdrt, n_groups_pre))

post <- splits %>% 
  pluck('FALSE') %>% 
  mutate(bin = cut_number(fdrt, n_groups_post)) 

both <- bind_rows(pre, post) %>% 
  distinct(fdrt, .keep_all = T)

umap_time_df <- umap_time %>% 
  left_join(both)

umap_drt_high_to_low_bin <- umap_time_df %>% 
   arrange(desc(fdrt)) %>% 
  #arrange(fdrt) %>% 
   ggscatter(x = 'taxumap1', y = 'taxumap2', color = 'bin', alpha = 1, size = umap_pt_size, shape = 16,
             xlab = '', ylab = '') + 
   scale_color_manual(values = RColorBrewer::brewer.pal(9,"Spectral"))  +
   theme_classic() +
   theme(legend.position = "none",
     #legend.position = 'none',
         line = element_blank(),
         legend.title = element_blank(),
         axis.title=element_blank(),
         axis.text= element_blank(),
         axis.ticks = element_blank(),
              panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
    panel.grid.major = element_blank(), #remove major gridlines
    panel.grid.minor = element_blank(), #remove minor gridlines
    legend.background = element_rect(fill='transparent'), #transparent legend bg
    legend.box.background = element_rect(fill='transparent') ,
        aspect.ratio=1)
ggsave( '../data/072_umap_drt_high_to_low_bin.png', dpi = 300, width = 2.5, height = 2.5,plot = umap_drt_high_to_low_bin, bg = "transparent")
```

```{r  umap_pt}
# Angel: we need a TaxUMAP labeled by patient ID, too. Maybe: a grey umap, and all meals by three patients in three colors highlighted

# figure out the color for them
# randomly select three patients and give them three distinct colors while others remain gray 
set.seed(1234)
umap_pt_color <- umap_cal %>% 
  distinct(mrn) %>% 
  slice_sample(n = 3, replace = F) %>% 
  mutate(colors = RColorBrewer::brewer.pal(3, "Set1"))
umap_pt_color_all <- bind_rows(
   umap_cal %>% 
  distinct(mrn) %>% 
    filter(!mrn %in% umap_pt_color$mrn) %>% 
    mutate(colors = 'gray81'),
  umap_pt_color
)

umap_pt <- umap_cal %>% 
  left_join(umap_pt_color_all) %>% 
  mutate(mrn = as.character(mrn)) %>% 
  arrange(desc(colors))

color_key <- umap_pt_color_all %>% 
  mutate(mrn = as.character(mrn)) %>% 
  ungroup() %>% 
  deframe()

umap_pt_plot <- umap_pt %>% 
  # arrange(desc(fdrt)) %>% 
  #arrange(fdrt) %>% 
   ggscatter(x = 'taxumap1', y = 'taxumap2', color = 'mrn', alpha = 1, size = umap_pt_size, shape = 16,
             xlab = '', ylab = '') + 
    scale_color_manual(values = color_key) +
   theme_classic() +
   theme(legend.position = "bottom",
     #legend.position = 'none',
         line = element_blank(),
         legend.title = element_blank(),
         axis.title=element_blank(),
         axis.text= element_blank(),
         axis.ticks = element_blank(),
              panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
    panel.grid.major = element_blank(), #remove major gridlines
    panel.grid.minor = element_blank(), #remove minor gridlines
    legend.background = element_rect(fill='transparent'), #transparent legend bg
    legend.box.background = element_rect(fill='transparent') ,
        aspect.ratio=1)
ggsave( '../data/072_umap_pt.png', dpi = 300, width = 2.5, height = 2.5,plot = umap_pt_plot, bg = "transparent")
```
```{r}
# make a figure of the patients ABC and the colors
umap_pt_color %>% 
  ggscatter( x= 'mrn', y = 'mrn', color = 'colors') +
   scale_color_manual(values = color_key) 
ggsave('../data/072_umappt_legends.pdf')
```
```{r}
# make a umap to highlight the ICU patients
icu_days <- dtb %>% 
  filter(Meal == 'EN') %>% 
  select(mrn, fdrt) %>% 
  mutate(grp = 'ICU days')

umap_icu <- umap_cal %>% 
  left_join(icu_days, by = c("mrn", "fdrt")) %>% 
  mutate(grp = if_else(is.na(grp), '', grp))

umap_icu_plot <- umap_icu %>% 
  arrange(grp) %>% 
  #arrange(fdrt) %>% 
   ggscatter(x = 'taxumap1', y = 'taxumap2', color = 'grp',palette = 'jco' , 
             alpha = 1, size = umap_pt_size, shape = 16,
             xlab = '', ylab = '') + 
    #scale_color_manual(values = color_key) +
   theme_classic() +
   theme(
     legend.position = 'bottom',
         line = element_blank(),
         legend.title = element_blank(),
         axis.title=element_blank(),
         axis.text= element_blank(),
         axis.ticks = element_blank(),
              panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
    panel.grid.major = element_blank(), #remove major gridlines
    panel.grid.minor = element_blank(), #remove minor gridlines
    legend.background = element_rect(fill='transparent'), #transparent legend bg
    legend.box.background = element_rect(fill='transparent') ,
        aspect.ratio=1)
ggsave( '../data/072_umap_icu.png', dpi = 300, width = 2.5, height = 2.5,plot = umap_icu_plot, bg = "transparent")


```


```{r}
umap_icu %>% 
  filter(icu =='TRUE') %>% 
  gghistogram(x = 'fdrt', facet.by = 'mrn')

df <- umap_icu %>% 
  filter(icu =='TRUE') 
```


```{r tree}
# import the tree from pdf to a ggplot kind of object
p <- '../figs/paper/080_food_tree_ring.png'
tree <- ggdraw() +
  draw_image(p,   scale = 1.3) 
```


# the macronutrients 3 by 2 panel inserted to the bottom row

```{r 3X2}
# the macronutrients scatter plot
m_all <- dtb %>%  
  select(mrn, fdrt,Protein_g:Sodium_g ) %>% 
  gather('grp','gram', Protein_g:Sodium_g) %>% 
  mutate(grp = str_replace(grp, '_g$','')) %>% 
  group_by(mrn, fdrt, grp) %>% 
  summarise(eachsum = sum(gram)) 

m_panel <- m_all %>% 
   ggscatter(x = 'fdrt', y = 'eachsum', alpha = 0.005, size = point_size, 
            xlab = 'Day relative to HCT',
            ylab = 'Grams',
            add = "loess", conf.int = TRUE, 
            add.params = list(color = diet_line_color, fill = "hotpink", size = 1))  +
  facet_wrap(~ grp, nrow = 3, scales = 'free_y') +
  scale_x_continuous( breaks = seq(0, 50, 20)) + 
  theme(axis.text=element_text(size=6),
        strip.background = element_blank(),
        strip.text.x = element_text(size = stip_txt_size), 
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        aspect.ratio=1)
m_panel
```

# the food group daily intake as a 3 by 3 grid panel

```{r 3X3}
fg_all <- dtb %>%  
  mutate(fgrp1 = str_sub(Food_code, 1, 1)) %>% 
  mutate(fgrp1 = as.numeric(fgrp1)) %>% 
  group_by(mrn, fdrt, fgrp1) %>% 
  summarise(eachsum = sum(dehydrated_weight)) %>% 
  left_join(key)

fg_panel <- fg_all %>% 
   ggscatter(x = 'fdrt', y = 'eachsum', alpha = 0.005, size = point_size, 
            xlab = 'Day relative to HCT',
            ylab = 'Grams',
            add = "loess", conf.int = TRUE, 
            add.params = list(color = diet_line_color, fill = "hotpink", size = 1))  +
  facet_wrap(~ shortname, 
             scales = 'free_y',
             nrow = 3, ) +
  scale_x_continuous( breaks = seq(0, 50, 20)) + 
  theme(axis.text=element_text(size=6),
        strip.background = element_blank(),
        strip.text.x = element_text(size = stip_txt_size), 
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        aspect.ratio=1)
fg_panel
```


# Assembling the final version of the figure 1

```{r}
stool_two <- plot_grid(stool_alpha,stool_alpha,
                  nrow = 2,axis = 'lbrt', align = 'hv') 

bot <- plot_grid(food2, m_panel, fg_panel,  stool_two,
          nrow = 1, 
          align = 'hv',
          rel_widths =  c(1,1.2,1.4,1),
          #rel_heights = c(1,1),
          labels = c('E','F', 'G', "H"),
          axis = 'tblr') 



top <- plot_grid(tree, fig1_umap, NA,
                 #labels = c('B', "C", "D"),
                  nrow = 1, rel_widths = c(1.5,1, 1), axis = 'lbrt', align = 'hv')

# assemble all
f1 <-  plot_grid(top, bot,
                 rel_heights = c(1,1),
                 nrow = 2)

ggsave('../figs/paper/F1_overview_072_raw.pdf',
       width = 220,
       height = 140,
         #height = 60,  
         units = c("mm"),
         dpi = 400, plot = f1)
```


```{r}
# a sub figure of only the two umaps so tht I can put them into my current version Figure 1
middle_3_umap <- plot_grid(umap_caloric,umap_faith,umap_drt_high_to_low_bin,
                 labels = c('D'),
                  nrow = 3,axis = 'lbrt', align = 'hv')

ggsave('../figs/paper/F1_overview_072_umap3.pdf',
       width = 80,
       height = 100,
         #height = 60,  
         units = c("mm"),
         dpi = 400, plot = middle_3_umap)
```


```{r spectral_legend}
pdf(file = "../figs/paper/F1_spectral_legend.pdf",   # The directory you want to save the file in
    width = 4, # The width of the plot in inches
    height = 4)
display.brewer.pal(9, "Spectral")
dev.off()
```




```{r}
umap_drt_low_to_high_bin <- umap_time_df %>% 
  arrange(fdrt) %>% 
   ggscatter(x = 'taxumap1', y = 'taxumap2', color = 'bin', alpha = 0.3, size = umap_pt_size, shape = 16,
             xlab = '', ylab = '') + 
  scale_color_manual(values = brewer.pal(9,"Spectral"))  +
   theme_classic() +
   theme(
     #legend.position = 'none',
         line = element_blank(),
         legend.title = element_blank(),
         axis.title=element_blank(),
         axis.text= element_blank(),
         axis.ticks = element_blank(),
        aspect.ratio=1)



umap_drt_high_to_low_bin_no_sorting <- umap_time_df %>% 
  # arrange(desc(fdrt)) %>% 
  #arrange(fdrt) %>% 
   ggscatter(x = 'taxumap1', y = 'taxumap2', color = 'bin', alpha = 0.3,size = umap_pt_size, shape = 16,
             xlab = '', ylab = '') + 
   scale_color_manual(values = brewer.pal(9,"Spectral"))  +
   theme_classic() +
   theme(
     #legend.position = 'none',
         line = element_blank(),
         legend.title = element_blank(),
         axis.title=element_blank(),
         axis.text= element_blank(),
         axis.ticks = element_blank(),
        aspect.ratio=1)


middle_2_umap <- plot_grid(
                           umap_drt_low_to_high_bin, umap_drt_high_to_low_bin,
                           umap_drt_high_to_low_bin_no_sorting,
                 #labels = c('D'),
                  nrow = 2,axis = 'lbrt', align = 'hv')

ggsave('../figs/paper/F1_overview_072_umap2_compare.pdf',
       width = 120,
       height = 120,
         #height = 60,  
         units = c("mm"),
         dpi = 400, plot = middle_2_umap)

ggsave('../figs/paper/F1_overview_072_umap2_compare.jpg',
       width = 120,
       height = 120,
         #height = 60,  
         units = c("mm"),
         dpi = 400, plot = middle_2_umap)
```

```{r}
# is it indeed that corner of the dots 
all_umap <- umap_cal %>% 
  full_join(another) %>% 
  select(index_column:fdrt, daycal,faith_pd )

all_umap %>% 
  #filter(taxumap1 < 16 & taxumap2 < -6) %>% 
   arrange(desc(fdrt)) %>% 
  #arrange(fdrt) %>% 
   ggscatter(x = 'taxumap1', y = 'taxumap2', color = 'fdrt', alpha = 0.3,size = umap_pt_size, shape = 16,
             xlab = '', ylab = '') + 
   #paletteer::scale_color_paletteer_d("khroma::BuRd")  +
   theme_classic() +
   theme(
     #legend.position = 'none',
         legend.title = element_blank(),
         axis.title=element_blank(),
         axis.ticks = element_blank(),
        aspect.ratio=1)
```
```{r}
several <- all_umap %>% 
  filter(fdrt > 30 & taxumap1 < 15.5 & taxumap2 < -6)
```

```{r}
# Tsoni says: I still think a little figure would be helpful. Perhaps best a small histogram of N samples and N meals recorded over transplant time. That would show both the depth of sampling and emphasize the temporal nature of the dataset
# the histogram of the N stool samples over transplant time
stool_hist <- meta %>% 
  gghistogram(x = 'sdrt', xlab = 'Transplant day', ylab = 'Count', color = 'white', fill = stool_line_color, alpha = 1) +
  scale_x_continuous( breaks = seq(-10, 50, 20)) + 
  theme(aspect.ratio=1)
stool_hist

range(meta$sdrt)
```


```{r}
# the histogram of the N meals over transplant time
diet_hist <- dtb %>% 
  distinct(mrn, Meal, fdrt) %>% 
  gghistogram(x = 'fdrt', xlab = 'Transplant day', ylab = 'Count', color = 'white', fill = diet_line_color, alpha = 1)+
    scale_x_continuous( breaks = seq(-10, 50, 20)) + 
  theme(aspect.ratio=1,
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

diet_hist
```
```{r}
hist_two <- plot_grid(diet_hist, stool_hist,
                  nrow = 2,axis = 'lbrt', align = 'hv')

hist_two

ggsave('../data/072_hist2.pdf', height = 3)
```

```{r}
# summary statistics 
# median N samples per patient
n_per_patient <- meta %>% 
  count(mrn) 
summary(n_per_patient$n)
```

