---
title: "growth_rate_and_absoluate_abun"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(vdbR)
connect_database('~/dbConfig.txt')
list_table_from_database('qpcr')
get_table_from_database('qpcr_16s_ag')
get_table_from_database('antibiotics_antibacterial_multicenter_ag')
library(tidyverse)
library(ggpubr)
library(cowplot)
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
```

```{r}
qpcr <- qpcr_16s_ag %>% 
  filter(!str_detect(sample_id_unique, 'heat|ethanol')) %>% 
  filter(!is.na(copies_16s_per_g))
```

```{r}
# all the patients that have a entercoccus growth rate
combined <- read_csv('../data/growth/069_irep_combined_res.csv')
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')
target <- combined %>%  
  filter(str_detect(best_species, 'Enterococcus')) %>% 
  distinct(mrn) %>% 
  pull(mrn) 

entero <- combined %>%  
  filter(str_detect(best_species, 'Enterococcus')) %>% 
  group_by(sampleid, mrn) %>% 
  summarise(ave_irpe = mean(aveirep)) %>% 
  inner_join(meta %>% 
               select(sampleid, sdrt))

# all of these patients stool samples we have 
get_table_from_database('samples_castori_ag')
get_table_from_database('asv_annotation_blast_ag')
sam <- samples_castori_ag %>% 
  filter(mrn %in% target) %>% 
  distinct(sampleid) %>% 
  pull(sampleid)
samps <- samples_castori_ag %>% 
  filter(mrn %in% target) %>% 
  distinct(sampleid, mrn)

# get the entercoccus relab of these samples
cts <- get_counts_subset(sam)
ptb <- read_csv('../data/cleaned_patients/diet_patients_97.csv')

cts_ <- cts %>% 
  left_join(asv_annotation_blast_ag %>% 
              select(asv_key, genus)) %>% 
  group_by(sampleid, genus) %>% 
  summarise(relab = sum(count_relative)) %>% 
  filter(genus == 'Enterococcus')  %>% 
  inner_join(qpcr %>% 
               select(sampleid = sample_id, copies_16s_per_g)) %>% 
  mutate(entero_copy = copies_16s_per_g*relab) %>% 
  inner_join(samples_castori_ag %>% 
               select(sampleid, datecollection)) %>% 
  inner_join(samps) %>% 
  inner_join(ptb %>% 
               select(mrn, hct)) %>% 
  mutate(sdrt = datecollection - hct) %>% 
  filter(sdrt < 54)
```
```{r}
# entero %>% 
#   ggplot(aes(x = sdrt, y = ave_irpe )) +
#   geom_point() +
#   geom_point(data = cts_, aes(x = sdrt, y = entero_copy, col = 'red')) +
#   facet_wrap(~mrn)

# the patients that have both the irep and qpcr results
both <- intersect(cts_$mrn, entero$mrn)
```
```{r}
absl <- both %>%
  set_names(both) %>%
  imap(function(.x, .y){
    # set the min and max in the x axis to be the min and max of the global values
    xmax = max(max(entero %>%
      filter(mrn == .x) %>% pull(sdrt)), max(cts_ %>%
      filter(mrn == .x) %>% pull(sdrt))) + 2

    xmin = min(min(entero %>%
      filter(mrn == .x) %>% pull(sdrt)), min(cts_ %>%
      filter(mrn == .x) %>% pull(sdrt))) -2

    irep = entero %>%
      filter(mrn == .x) %>%
      ggplot(aes(x = sdrt, y = ave_irpe )) +
      geom_point() +
      labs(title = str_glue('{}')) +
      xlim(xmin, xmax) +
      labs(x = '',
           y = 'average irep values')


    copies = cts_ %>%
      filter(mrn == .x) %>%
      ggplot(aes(x = sdrt, y = entero_copy )) +
      geom_point() +
     # scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),
      #          labels = scales::trans_format("log10", scales::math_format(10^.x))) +
      xlim(xmin, xmax) +
      labs(x = 'day relative to transplant',
           y = 'Enterococcus copy\nnumbers')

    res = cowplot::plot_grid(irep, copies, axis = 'tblr', align = 'hv', ncol = 1)
    #ggsave(str_glue('../data/{.y}.pdf'), width = 5, height = 4)
  })
# 
# seq(1, length(absl)) %>% 
#   set_names(seq(1, length(absl))) %>% 
#   imap(~ ggsave(str_glue('../data/Patient{.y}.pdf'), width = 5, height = 4, plot = absl[[.x]]))
```

## customize patient 11 for show

```{r}
# customize patient 11
# use the global highest irep value for the highest in the y axis.
irep_highest <- max(entero$ave_irpe) + 0.05
irep_q25 <- quantile(x = entero$ave_irpe, 0.25)
irep_q50 <- quantile(x = entero$ave_irpe, 0.5)
irep_q75 <- quantile(x = entero$ave_irpe, 0.75)

p11 <- names(absl)[11]
xmax = 15

xmin = -5

quantile_annot_df <- tibble(
  quant = c('25%','50%','75%'),
  height = c(irep_q25, irep_q50, irep_q75)
)

irep = entero %>% 
  filter(sdrt %in% -5:15) %>% 
  filter(mrn == p11) %>% 
  ggplot(aes(x = sdrt, y = ave_irpe )) +
  geom_point() +
  labs(title = str_glue('{}')) +
  geom_hline(yintercept = irep_q25, linetype = 'dashed') +
  #geom_text(data = quantile_annot_df, mapping = aes(x = 14, y = height, label = quant), nudge_y = 0.02, size = 2.5) +
  geom_hline(yintercept = irep_q50, linetype = 'dashed') +
  geom_hline(yintercept = irep_q75, linetype = 'dashed') +
  xlim(xmin, xmax) +
  ylim(1, irep_highest) +
  labs(x = '',
       y = 'Average replication rate',
       title = 'Enterococcus')+
  theme_classic()+
  theme(aspect.ratio=1,
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.grid.major.x = element_line(color = "grey85"),
        plot.margin = margin(b=-0.8,unit="cm"))
  

copies = cts_ %>% 
  filter(sdrt %in% -5:15) %>% 
  filter(mrn == p11) %>% 
  ggplot(aes(x = sdrt, y = entero_copy )) +
  geom_point() +
  geom_line(aes(x = sdrt, y = entero_copy), linetype = 'solid', size = 0.5, col = 'black') +
 # scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), 
  #          labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  xlim(xmin, xmax) +
  labs(x = 'Day relative to transplant',
       y = 'Enterococcus copy\nnumbers',
       title = 'Copy numbers') +
  theme_classic() +
  theme(aspect.ratio=1,
        plot.margin = margin(l=-0.8,unit="cm"),
        panel.grid.major.x = element_line(colour = "grey85"))

# a violin plot to show all the entero irep distribution
entero_box <- ggboxplot(entero,  y = "ave_irpe", add = 'jitter',
                          xlab = '', ylab = 'All Enterococcus replication rate')+
   theme_classic() +
   ylim(1, irep_highest)+
  theme(aspect.ratio=5,
        plot.margin = margin(l=-0.8,unit="cm"),
       axis.ticks.x=element_blank(),
       axis.title.x = element_blank(),
       axis.text.x = element_blank() )
 
 
# a plot to show the fruit intake over time for this patient
# by day 
fruit <- dtb %>%  
  filter(mrn == p11 & fdrt %in% -4:15) %>% 
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^6')) %>% 
  group_by(fdrt) %>% 
  summarise(fruitsum = sum(dehydrated_weight)) %>% 
  full_join(tibble(
    fdrt = seq(-2, 12, 1)
  )) %>% 
  mutate(fruitsum = if_else(is.na(fruitsum), 0, fruitsum))

# a boxplot for all the daily fruit consumption
all_fruit <- dtb %>%  
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^6')) %>% 
  group_by(mrn, fdrt) %>% 
  summarise(fruitdaily = sum(dehydrated_weight))

f_q25 <- quantile(x = all_fruit$fruitdaily, 0.25)
f_q50 <- quantile(x = all_fruit$fruitdaily, 0.5)
f_q75 <- quantile(x = all_fruit$fruitdaily, 0.75)

highest_daily_fruit_intake <- ceiling( max(all_fruit$fruitdaily))
lowest_daily_fruit_intake <- floor( min(all_fruit$fruitdaily))

all_fruit_box <- ggboxplot(all_fruit,  y = "fruitdaily", add = 'jitter',add.params = list(alpha = 0.05),
                          xlab = '', ylab = 'All patients')+
   theme_classic() +
   ylim(lowest_daily_fruit_intake, highest_daily_fruit_intake)+
  theme(aspect.ratio=5,
        plot.margin = margin(l=-0.8,unit="cm"),
       axis.ticks.x=element_blank(),
       axis.title.x = element_blank(),
       axis.text.x = element_blank() )

```

```{r}
fruit_time <- fruit %>% 
  ggplot(aes(x = fdrt, y = fruitsum )) +
  geom_point() +
  geom_line(aes(x = fdrt, y = fruitsum), linetype = 'solid', size = 0.5, col = 'black') +
 # scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), 
  #          labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  xlim(xmin, xmax) +
  labs(x = '',
       y = 'Fruit intake',
       title = 'Fruit intake') +
  theme_classic() + 
  ylim(lowest_daily_fruit_intake, highest_daily_fruit_intake)+
  #scale_y_sqrt() +
  geom_hline(yintercept = f_q25, linetype = 'dashed') +
  geom_hline(yintercept = f_q50, linetype = 'dashed') + 
  geom_hline(yintercept = f_q75, linetype = 'dashed') +
  theme(aspect.ratio=1,#1/2.8
        plot.margin = margin(l=-0.8,unit="cm"),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.grid.major.x = element_line(colour = "grey85"))
```

```{r}
# the sweets intake for this patient
sweets <- dtb %>%  
  filter(mrn == p11 & fdrt %in% -4:15) %>% 
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^9')) %>% 
  group_by(fdrt) %>% 
  summarise(sweetsum = sum(dehydrated_weight)) %>% 
  full_join(tibble(
    fdrt = seq(-2, 12, 1)
  )) %>% 
  mutate(sweetsum = if_else(is.na(sweetsum), 0, sweetsum))

# a boxplot for all the daily sweets consumption
all_sweet <- dtb %>%  
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^9')) %>% 
  group_by(mrn, fdrt) %>% 
  summarise(sweetdaily = sum(dehydrated_weight))

s_q25 <- quantile(x = all_sweet$sweetdaily, 0.25)
s_q50 <- quantile(x = all_sweet$sweetdaily, 0.5)
s_q75 <- quantile(x = all_sweet$sweetdaily, 0.75)

highest_daily_sweet_intake <- ceiling( max(all_sweet$sweetdaily))
lowest_daily_sweet_intake <- floor( min(all_sweet$sweetdaily))

all_sweet_box <- ggboxplot(all_sweet,  y = "sweetdaily", add = 'jitter',add.params = list(alpha = 0.05),
                          xlab = '', ylab = 'All patients')+
   theme_classic() +
   ylim(lowest_daily_sweet_intake, highest_daily_sweet_intake)+
  #scale_y_sqrt() +
  theme(aspect.ratio=5,
        plot.margin = margin(l=-0.8,unit="cm"),
       axis.ticks.x=element_blank(),
       axis.title.x = element_blank(),
       axis.text.x = element_blank() ) 
```
 

```{r}
sweets_time <- sweets %>%    
  ggplot(aes(x = fdrt, y = sweetsum )) +
  geom_point() +
  geom_line(aes(x = fdrt, y = sweetsum), linetype = 'solid', size = 0.5, col = 'black') +
  xlim(xmin, xmax) +
  labs(x = '',
       y = 'Sweets intake',
       title = 'Sweets intake') +
  theme_classic() + 
  ylim(lowest_daily_sweet_intake, highest_daily_sweet_intake)+
  #scale_y_sqrt() +
  geom_hline(yintercept = s_q25, linetype = 'dashed') +
  geom_hline(yintercept = s_q50, linetype = 'dashed') + 
  geom_hline(yintercept = s_q75, linetype = 'dashed') +
  theme(aspect.ratio=1,#1/2.8
        plot.margin = margin(l=-0.8,unit="cm"),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.grid.major.x = element_line(colour = "grey85"))
```



```{r}
# if fruits and sweets combined for this patient
both <- fruit %>% 
  full_join(sweets) %>% 
  mutate(bothwt = fruitsum + sweetsum)

both_all <- all_sweet %>% 
  full_join(all_fruit)  %>% 
  mutate(sweetdaily = if_else(is.na(sweetdaily), 0, sweetdaily),
         fruitdaily = if_else(is.na(fruitdaily), 0, fruitdaily)) %>% 
  mutate(bothwt = fruitdaily + sweetdaily)

both_all_high <-  ceiling( max(both_all$bothwt))
both_all_low <- floor( min(both_all$bothwt))

b_q25 <- quantile(x = both_all$bothwt, 0.25)
b_q50 <- quantile(x = both_all$bothwt, 0.5)
b_q75 <- quantile(x = both_all$bothwt, 0.75)

both_time <- both %>% 
  ggplot(aes(x = fdrt, y = bothwt )) +
  geom_point() +
  geom_line(aes(x = fdrt, y = bothwt), linetype = 'solid', size = 0.5, col = 'black') +
 # scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), 
  #          labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  xlim(xmin, xmax) +
  labs(x = '',
       y = 'Both intake',
       title = 'Both intake') +
  theme_classic() + 
   ylim(both_all_low, both_all_high)+
  #scale_y_sqrt() +
  geom_hline(yintercept = b_q25, linetype = 'dashed') +
  geom_hline(yintercept = b_q50, linetype = 'dashed') + 
  geom_hline(yintercept = b_q75, linetype = 'dashed') +
  theme(aspect.ratio=1,#1/2.8
        plot.margin = margin(l=-0.8,unit="cm"),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.grid.major.x = element_line(colour = "grey85"))


all_both_box <- ggboxplot(both_all,  y = "bothwt", add = 'jitter',add.params = list(alpha = 0.05),
                          xlab = '', ylab = 'All patients')+
   theme_classic() +
   ylim(both_all_low, both_all_high)+
  #scale_y_sqrt() +
  theme(aspect.ratio=5,
        plot.margin = margin(l=-0.8,unit="cm"),
       axis.ticks.x=element_blank(),
       axis.title.x = element_blank(),
       axis.text.x = element_blank() ) 
 
```
```{r}
# check this patient's abx usage
ptb <- read_csv('../data/cleaned_patients/diet_patients_97.csv')
# any vanco?
p11_abx <- antibiotics_antibacterial_multicenter_ag %>% 
  filter(patient_id == p11 ) %>% 
  rename(mrn = patient_id) %>% 
  mutate(mrn = as.numeric(mrn)) %>% 
  left_join(ptb %>% 
              select(mrn, hct)) %>% 
  mutate(startdrt = start - hct,
         stopdrt = stop - hct) %>% 
  # only select the days relevant
  filter(startdrt %in% -5:-2) %>% 
  mutate(drugfull = str_glue('{drug_name_clean} ({route_simple})')) %>% 
  arrange(startdrt, stopdrt) %>% 
  mutate(yval = seq(1, nrow(.))) %>% 
  mutate(startdrt = as.numeric(startdrt) ) %>% 
  mutate(startdrt = if_else(startdrt == -5, -5.1, startdrt))
xmin < -5.1
abx <- ggplot(p11_abx, aes(x = startdrt, y = yval, xend = stopdrt, yend = yval, label = drugfull )) +
  geom_segment(
     size = 0.5, lineend = 'round',
     #arrow = arrow(length = unit(0.05, "inches"))
  ) +
  geom_text(hjust = 'outside', nudge_y = -0.1, nudge_x = 5, size = 2) +
  coord_cartesian(xlim=c(xmin, xmax)) + 
  labs(x = '',
       y = '',
       title = 'Antibiotics') + 
  theme_classic() +
  theme(aspect.ratio=1,
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        panel.grid.major.x = element_line(color = "grey85"))
```

```{r}
p11_ver <- plot_grid(abx, NA,
                     sweets_time, all_sweet_box, 
                     fruit_time,all_fruit_box,  
                     irep, NA, 
                     copies,NA,
                     byrow = T,
          ncol = 2, axis = 'ltbr', align = 'hv')
p11_ver
 

ggsave('../figs/paper/075_irep_p11_vertical.pdf', width = 130,
      height = 250, units = 'mm', dpi = 400, plot = p11_ver)
```





```{r}
boxes <- plot_grid(all_fruit_box, NA, entero_box,
          nrow = 3, rel_heights  = c(1,1, 2))

f3 <-  plot_grid(p11_ver, boxes, 
          nrow = 1, rel_widths   = c(2,1))

ggsave('../figs/paper/075_irep_p11_enterococcus.pdf', width = 160,
      height = 180, units = 'mm', dpi = 400, plot = f3)
```

