---
title: "new samples for qpcr"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(vdbR)
connect_database('~/dbConfig.txt')
list_table_from_database('16s')
get_table_from_database('qpcr_16s_ag')
```

all samples from patients with at least 1 valid irep measurement.

```{r}
# patients with at least one irep results
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')
combined <- read_csv('../data/growth/irep_combined_res.csv')
pts <- combined %>% 
  distinct(mrn) %>% 
  pull(mrn)
selected <- meta %>%   
  filter(mrn %in% pts)  %>% 
  filter(sampleid %in% qpcr_16s_ag$sample_id)  %>% 
  pull(sampleid)

look <- qpcr_16s_ag %>% 
  
  filter(sample_id %in% selected) %>% 
  arrange(copies_16s_per_g)

head(look)

send <-  c(meta %>%   
  filter(mrn %in% pts)  %>% 
  filter(!sampleid %in% qpcr_16s_ag$sample_id) %>% 
  pull(sampleid), c('1687L','1687O'))

tibble(sampleid = send) %>% 
  write_csv('../data/growth/69_samples_for_qpcr.csv', col_names = F)
```



