---
title: "Calculate unifrac beta diversity"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE}
library(tidyverse)
library(phyloseq)
library(ape)
library(vegan)
library(ggpubr)
```

## Beta diversity

The counts table can't have a column that is completely all zeros. 


```{r}
# the feature table
# use the food id instead of the main food description which is a long string
final <- read_csv('../data/finalized/all_patients_record_w_food_code.csv')

food_db <- read_tsv('../data/source/food_database_file.tsv')

# the food id and food name table
food_id_name <- food_cts <- final %>% 
  select(mrn, DayRT, Food_NSC, dehydrated_weight) %>% 
  left_join(food_db %>% 
              select(Food_NSC = item1_value_raw_raw,
                     #Main.food.description,
                     FoodID), by  = 'Food_NSC')

food_cts <- final %>% 
  select(mrn, DayRT, Food_NSC, dehydrated_weight) %>% 
  left_join(food_db %>% 
              select(Food_NSC = item1_value_raw_raw,
                     #Main.food.description,
                     FoodID), by  = 'Food_NSC') %>% 
  group_by(mrn, DayRT, FoodID) %>% 
  summarise(day_de_wt = sum(dehydrated_weight)) %>% 
  ungroup() %>% 
  mutate(mrn = as.character(mrn),
         DayRT = as.character(DayRT)) %>% 
  mutate(DayRT = str_replace(DayRT, '-','_')) %>% 
  mutate(mrnDay = str_glue('{mrn}d{DayRT}')) %>% 
  select(-mrn, -DayRT) 


food_cts_wide <- food_cts %>% 
  spread(key = 'mrnDay', value = 'day_de_wt', fill = 0)

# find the most eaten food and put 10X than the smallest non-value in those eaters that have no solid food on that day
most_eaten_food <- food_cts_wide %>% 
  mutate(row_sum = rowSums(.[2:ncol(.)])) %>% 
  select(FoodID, row_sum) %>% 
  arrange(desc(row_sum)) %>% 
  slice(1) 


most_eaten_food_min_val <- food_cts_wide %>% 
  filter(FoodID == most_eaten_food$FoodID) %>% 
  select(-FoodID) %>% 
  gather('mrnDay', 'wt') %>% 
  filter(wt != 0) %>% 
  arrange(wt) %>% 
  summarise(min_val = 0.1*min(wt))


# what are the patients and days that they don't eat any solid food?
daily_total <- food_cts_wide %>% 
  select(-FoodID) %>% 
  summarise_all(sum) %>% 
  gather('mrnDay', 'wt') %>% 
  arrange(wt) %>% 
  filter(wt == 0) %>% 
  pull(mrnDay)

# now put the value of the most eaten food to be the min value for those 5 mrnDay records
food_cts <- food_cts %>% 
  mutate(day_de_wt = if_else(mrnDay %in% daily_total , most_eaten_food_min_val$min_val, day_de_wt))

# food_cts %>% 
#   filter(mrnDay %in% daily_total)

food_cts_day <- food_cts %>% 
  spread(key = 'mrnDay', value = 'day_de_wt', fill = 0)

```


```{r}
# write out the food_cts_day table cuz now it's per patient per day data
food_cts_day %>% 
  write_tsv('../data/finalized/all_patients_food_dehywt_table_w_fooID_by_day.tsv')
```


```{bash}
biom convert -i all_patients_food_dehywt_table_w_fooID_by_day.tsv -o all_patients_food_dehywt_table_w_fooID_by_day.biom  --to-hdf5 --table-type="Table"
```

```{bash}
qiime tools import \
  --input-path all_patients_food_dehywt_table_w_fooID_by_day.biom \
  --output-path all_patients_food_dehywt_table_w_fooID_by_day.qza \
  --type 'FeatureTable[Frequency]'
```

Regenerated the food tree newick file with the tip being the food id

Convert the tree from newick to qza

```{bash}
qiime tools import \
  --input-path output_food_tree_datatree.newick \
  --output-path output_food_tree_datatree.qza \
  --type 'Phylogeny[Rooted]'
```


Use qiime and the above two files to calculate the **unweighted_unifrac** distance 

```{bash}
qiime diversity beta-phylogenetic \
  --i-table all_patients_food_dehywt_table_w_fooID_by_day.qza \
  --i-phylogeny ../source/output_food_tree_datatree.qza \
  --p-metric unweighted_unifrac \
  --o-distance-matrix unweighted_unifrac_distance_matrix.qza
```


Export the qza format to a readable table format

```{bash}
qiime tools export --input-path unweighted_unifrac_distance_matrix.qza --output-path beta_phylo
```





