---
title: "Tree ring"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(phytools)
library(tidyverse)
library(vdbR)
library(data.tree)

```

```{r}
tre <-   read.newick('../data/cleaned_tree/output_food_tree_datatree.newick')
leaves <- tibble(
  fcode = tre$tip.label
)
dtb <- read_csv('../data/152_combined_DTB.csv')

n_meal <- dtb %>% 
  count(mrn, fdrt, Meal) %>% 
  nrow()

matching <- read_csv('../data/cleaned_diet_data/food_group_color_key.csv', col_types = 'ccc')

food_code_sum <- dtb %>% 
  group_by(Food_code) %>% 
  summarise(fc_sum = sum(dehydrated_weight)) %>% 
  mutate(Food_code = as.character(Food_code))  %>% 
  filter(Food_code %in% leaves$fcode)

food_code_sum_ <- food_code_sum[order(leaves$fcode),]

all.equal(food_code_sum_$Food_code , leaves$fcode)  #I'm fine with 3 mismatches. they are very close anyway
```

```{r}
# the newick string for the nodes
tree_df <- read_csv('../data/source/final_table_for_writing_out_to_newick.csv', col_types = cols(.default = col_character())) %>% 
  select(FoodID, description)
```


## plot with bar plot and then try to overlay

```{r}
# make the circular bar plot
bars <- food_code_sum_ %>% 
  mutate(per_meal_ave = round(fc_sum/n_meal, 3)) %>% 
  mutate(fgrp1 = str_sub(Food_code, 1, 1)) %>% 
  left_join(matching, by = "fgrp1") %>% 
  mutate(fg1_name = factor(fg1_name, levels = c('fg_egg', 'fg_oils', 'fg_legume', 'fg_fruit', 'fg_sweets', 'fg_milk','fg_meat', 'fg_veggie', 'fg_grain' ))) %>% 
  arrange(fg1_name)

food_code_level <- bars %>% pull(Food_code)

bars_ <- bars %>% 
  mutate(Food_code = factor(Food_code, levels = food_code_level))
```

```{r}
# the top several foods in each category
# top_each <- bars_ %>% 
#   select(Food_code,fg1_name, per_meal_ave ) %>% 
#   group_by(fg1_name) %>% 
#   arrange(desc(per_meal_ave)) %>% 
#   slice_max(n = 5, order_by = per_meal_ave) %>% 
#   ungroup() %>% 
#   inner_join(dtb %>% 
#                mutate(Food_code = as.character(Food_code)) %>% 
#                distinct(Food_code, description)) %>% 
#   split(.$fg1_name)
 
```


```{r}
# fill_val <- bars %>% 
#   distinct(fg1_name, color) %>% 
#   deframe()
# 
# # figure out the y axis for the summed ring
# # I was plotting the half of the log10gram
# bars %>% 
#   ggplot(aes(x = Food_code, y = log10gram)) +
#   geom_blank() +
#   theme_classic() +
#   ylim(0, max(bars$log10gram)) +
#   labs(y = '') +
#   theme(axis.text.x = element_blank(),
#         axis.title.x = element_blank(),
#         axis.line.x = element_blank())
# 
# ggsave('../figs/paper/080_ring_y_axis.pdf', height = 1)
```
```{r}
# p <- ggplot(bars_, aes(x=Food_code, y=log10gram, fill = fg1_name)) +  
#   geom_bar(stat="identity") +
#   scale_fill_manual(values = fill_val) +
#   ylim(-50,15) +# this adjust the image to be like a ring
#   theme_minimal() +
#   theme(
#     axis.text = element_blank(),
#     axis.title = element_blank(),
#     panel.grid = element_blank(),
#     legend.position = 'none'
#     #plot.margin = unit(rep(-2,4), "cm")    
#   ) +
#   coord_polar(start = 90)
```

## plot using the graphlan itself
 
Need to make the annotation file to specify how the tree ring looks like

```{r per_meal_ave_ring_annot}
ring <- bars_ %>%  
  select(Food_code, ring_height = per_meal_ave, ring_color = color) %>% 
  mutate(Food_code = as.character(Food_code)) %>% 
  full_join(tree_df %>% select(Food_code = FoodID, description)) %>% 
  select(description, ring_height:ring_color) %>% 
  mutate(ring_width = 0.5) %>% 
  gather('key','value', ring_height:ring_width) %>% 
  mutate(ring_level = 1) %>% 
  select(description, key, ring_level, value) 
  
ring %>% 
  write_tsv('../data/source/ring_annot.txt', col_names = F)
```

```{r one_day}
# add the annotation marker for the example daily meal for that patient 
# dm5 <-  read_csv('../data/cleaned_diet_data/example_pt_dm5_diet.csv') %>% 
#   rename(food_desc = description) %>% 
#   inner_join(tree_df %>% mutate(Food_code = as.numeric(FoodID)), by = "Food_code") %>% 
#   mutate(log10wt = log10(dehydrated_weight))

# clade_markder <- dm5 %>% 
#   select(description, clade_marker_color = color) %>% 
#  mutate(clade_marker_shape = '.',clade_marker_size = 50,clade_marker_edge_color = 'white') %>% 
#   gather('key','value', clade_marker_color:clade_marker_edge_color)
# 
# # the below is the file for the dot on the tree to mark the dm 5 food for that patient.
# clade_markder %>% 
#   write_tsv('../data/source/clade_annot_marker.txt', col_names = F)


ring_itself <- tibble(
  ring_level = c(1),
  ring_internal_separator_thickness = 0,
  ring_external_separator_thickness = 0,
  ring_label_font_size = 5,
  ring_separator_color = 'black'
) %>% 
  gather('key', 'value', ring_internal_separator_thickness:ring_separator_color) %>% 
  select(key, ring_level, value) %>% 
  write_tsv('../data/source/ring_itself.txt', col_names = F)
```

```{r}
# add the day meal log10 wt for the food code to the second ring
# ring2 <- dm5 %>% 
#   mutate(ring_height = log10wt,
#          ring_height = ring_height/2) %>% 
#   select(description, ring_color = color, ring_height) %>% 
#   mutate(ring_alpha = 0.5,
#          ring_width = 1) %>% 
#   gather('key','value', ring_color:ring_width) %>% 
#   mutate(ring_level = 2) %>% 
#   select(description, key, ring_level, value) 
# 
# ring2 %>% write_tsv('../data/source/ring2.txt', col_names = F)
```

```{r}
# add another layer of the ring as the text annotation of what the ring 2 food is
# decided to not want this in the main figure cuz it's not population data 
# dm5_annot <- dm5 %>% 
#   #mutate(ring_height = log10wt,ring_height = ring_height/2) %>% 
#   select(description, annotation = item, annotation_background_color = color) %>% 
#   mutate(annotation_rotation = 90,
#          annotation_font_size = 3)  %>% 
#   gather('key','value', annotation:annotation_font_size) %>% 
#   select(description, key, value) 
# 
# dm5_annot %>% write_tsv('../data/source/dm5_annotation.txt', col_names = F)
```
    
```{r}
# remake the output_food_tree_datatree_name.newick file
# make another tree with leave nodes as the name description so it is not some numbers
final.table <- read_csv('../data/source/final_table_for_writing_out_to_newick.csv')

final_table_name <- final.table%>% 
  mutate(newickstring_name = str_glue('foodtreeroot/{L1}/{L2}/{L3}/{L4}/{L5}/{L6}/{description}'))

#### Make and export the tree ####
foodTree <- as.Node(final_table_name, pathName = "newickstring_name")
tree <- ToNewick(foodTree)
cat(tree, file = '../data/cleaned_tree/output_food_tree_datatree_name.newick')
```
    
```{bash}
#cat ../data/source/annotation.base.txt ../data/source/dm5_annotation.txt > ../data/cleaned_tree/Annot_tree.txt
cat ../data/source/annotation.base.txt ../data/source/ring_itself.txt > ../data/cleaned_tree/Annot_tree2.txt 
cat ../data/cleaned_tree/Annot_tree2.txt ../data/source/ring_annot.txt > ../data/cleaned_tree/Annot_tree4.txt 
```

```{bash}
# this runs in the source folder 
# the key is that the tree and the annot file has to have the string of food name as leaves 
../../softwares/graphlan/graphlan_annotate.py --annot ../cleaned_tree/Annot_tree4.txt ../cleaned_tree/output_food_tree_datatree_name.newick  guide_1_new.xml
../../softwares/graphlan/graphlan.py guide_1_new.xml ../../data/080_food_tree_ring.png --dpi 400 --size 3 --pad 0

```

Succeeded!!!!!!!!!!!!! Now I have the ring added using graphlan!!! Perfectly aligned and the colors match!!!!!!!!