---
title: "the irep combined result analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggpubr)
library(tidyverse)
```

```{r}
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv') %>% 
  select(sampleid, mrn, sdrt, intensity, EN:TPN)

combined <- read_csv('../data/growth/irep_combined_res.csv', show_col_types = FALSE) %>% 
  left_join(meta, by = c("sampleid", "mrn")) %>% 
  arrange(mrn, sdrt) %>% 
  relocate(sdrt, .after = sampleid) %>% 
  relocate(mrn, .after = sdrt)
```

```{r}
# visualize the distribution of irep in every sample 
combined %>% 
  arrange(mrn, sdrt) %>% 
  ggboxplot(x= 'sampleid', y = 'iRep', add = 'jitter')  +
  facet_wrap(~mrn, scales = 'free') +
  theme(axis.text.x = element_text(angle=45, hjust=1))
    
ggsave('../data/growth/combined_per_sample_dist.pdf', width = 18, height = 10)

  
best_spp <- combined %>% 
  dplyr::count(mrn, best_species, sort = T)
```

```{r}
# want to look at the patient that starts sampleid with 1461
look <- combined %>% 
  filter(str_detect(sampleid, "^1461"))

look_max_irep <- look %>% 
  group_by(sampleid) %>% 
  arrange(-iRep, .by_group = T) %>% 
  slice(1) %>% 
  arrange(sdrt)

p1546_max <-  combined %>% 
  filter(str_detect(sampleid, "^1546")) %>% 
  group_by(sampleid) %>% 
  arrange(-iRep, .by_group = T) %>% 
  slice(1) %>% 
  arrange(sdrt)
```

```{r}
# the serveral high irep of rothia is interesting
library(vdbR)
connect_database('~/dbConfig.txt')
list_table_from_database('qpcr')
get_table_from_database('qpcr_16s_ag')
pt1461 <- qpcr_16s_ag %>% 
  filter(str_detect(sample_id, '^1461')) 

genus <- read_csv('../data/cleaned_stool/ALL_stool_samples_genus_counts.csv') %>% 
  filter(genus == 'Rothia') %>% 
  inner_join(pt1461 %>% 
               select(sampleid = sample_id, copies_16s_per_g), by = "sampleid") %>% 
  mutate(rothia_copies = round(copies_16s_per_g * relab))

r1461 <- look_max_irep %>% 
  inner_join(genus, by = "sampleid") %>% 
  relocate(rothia_copies, .after = iRep)
# Rothia is not growing during day 27-31 despite a high irep because of vancomycin

r1461 %>% 
  filter(str_detect(best_species, 'Rothia')) %>% 
  select(sdrt, iRep, rothia_copies) %>% 
  gather('grp', 'value', iRep:rothia_copies) %>% 
  ggdotchart(x = 'sdrt', y = 'value', sorting = 'none',
             title = 'Rothia irep and abs copy') +
  facet_grid(grp~ ., scales = 'free')
```

```{r}
# what about same patient but Streptococcus salivarius between day 37 and 41
# but I don't have the pqcr results yet

strep <- read_csv('../data/cleaned_stool/ALL_stool_samples_genus_counts.csv') %>% 
  filter(genus == 'Streptococcus')  %>% 
  inner_join(pt1461 %>% 
               select(sampleid = sample_id, copies_16s_per_g), by = "sampleid") %>% 
  mutate(copies = round(copies_16s_per_g * relab))

strep_df <- combined %>% 
  filter(str_detect(sampleid, '^1461')) %>% 
  filter(str_detect(best_species, 'Streptococcus'))  %>%   
  group_by(sampleid, sdrt) %>% 
  summarise(ave_irep =  mean(iRep)) %>% 
  inner_join(strep, by = "sampleid") %>% 
  relocate(copies, .after = ave_irep)


strep_df %>% 
  select(sdrt, ave_irep, copies) %>% 
  gather('grp', 'value', ave_irep:copies) %>% 
  ggdotchart(x = 'sdrt', y = 'value', sorting = 'none',
             title = 'Strep irep and abs copy') +
  facet_grid(grp~ ., scales = 'free')
```


```{r}
pt1461_Lactobacillus <- read_csv('../data/cleaned_stool/ALL_stool_samples_genus_counts.csv') %>% 
  filter(genus == 'Lactobacillus')  %>% 
  inner_join(qpcr_16s_ag %>% 
               select(sampleid = sample_id, copies_16s_per_g), by = "sampleid") %>% 
  mutate(copies = round(copies_16s_per_g * relab))

pt1461_Lactobacillus_df <- combined %>% 
  filter(str_detect(sampleid, "^1461")) %>% 
  filter(str_detect(best_species, 'Lactobacillus fermentum')) %>% 
  inner_join(pt1461_Lactobacillus, by = "sampleid") %>% 
  relocate(copies, .after = iRep)
 

pt1461_Lactobacillus_df %>% 
  select(sdrt, iRep, copies) %>% 
  gather('grp', 'value', iRep:copies) %>% 
  ggdotchart(x = 'sdrt', y = 'value', sorting = 'none',
             title = 'Lactobacillus irep and abs copy') +
  facet_grid(grp~ ., scales = 'free') 
```

```{r}
# look another patient that has most entries for Enterococcus faecium T110
en <- read_csv('../data/cleaned_stool/ALL_stool_samples_genus_counts.csv') %>% 
  filter(genus == 'Enterococcus')  %>% 
  inner_join(qpcr_16s_ag %>% 
               select(sampleid = sample_id, copies_16s_per_g), by = "sampleid") %>% 
  mutate(copies = round(copies_16s_per_g * relab))

en10 <- combined %>% 
  filter(str_detect(sampleid, "^1546")) %>% 
  filter(str_detect(best_species, 'Enterococcus faecium')) %>% 
  inner_join(en, by = "sampleid") %>% 
  relocate(copies, .after = iRep)


en10 %>% 
  select(sdrt, iRep, copies) %>% 
  gather('grp', 'value', iRep:copies) %>% 
  ggdotchart(x = 'sdrt', y = 'value', sorting = 'none',
             title = 'Enterococcus irep and abs copy') +
  facet_grid(grp~ ., scales = 'free')   
#G and F sample were sent out for qpcr
```

```{r}
Klebsiella <- read_csv('../data/cleaned_stool/ALL_stool_samples_genus_counts.csv') %>% 
  filter(genus == 'Klebsiella')  %>% 
  inner_join(qpcr_16s_ag %>% 
               select(sampleid = sample_id, copies_16s_per_g), by = "sampleid") %>% 
  mutate(copies = round(copies_16s_per_g * relab))

Klebsiella_df <- combined %>% 
  filter(str_detect(sampleid, "^1574")) %>% 
  filter(str_detect(best_species, 'Klebsiella pneumoniae')) %>% 
  inner_join(Klebsiella, by = "sampleid") %>% 
  relocate(copies, .after = iRep)

Klebsiella_df %>% 
  select(sdrt, iRep, copies) %>% 
  gather('grp', 'value', iRep:copies) %>% 
  ggdotchart(x = 'sdrt', y = 'value', sorting = 'none',
             title = 'Klebsiella irep and abs copy') +
  facet_grid(grp~ ., scales = 'free') 
```

```{r}
pt1574_enter <- read_csv('../data/cleaned_stool/ALL_stool_samples_genus_counts.csv') %>% 
  filter(genus == 'Enterococcus')  %>% 
  inner_join(qpcr_16s_ag %>% 
               select(sampleid = sample_id, copies_16s_per_g), by = "sampleid") %>% 
  mutate(copies = round(copies_16s_per_g * relab))

pt1574_enter_df <- combined %>% 
  filter(str_detect(sampleid, "^1574")) %>% 
  filter(str_detect(best_species, 'Enterococcus faecium')) %>% 
  inner_join(pt1574_enter, by = "sampleid") %>% 
  relocate(copies, .after = iRep)

pt1574_enter_df %>% 
  select(sdrt, iRep, copies) %>% 
  gather('grp', 'value', iRep:copies) %>% 
  ggdotchart(x = 'sdrt', y = 'value', sorting = 'none',
             title = 'Enterococcus irep and abs copy') +
  facet_grid(grp~ ., scales = 'free') 
```
```{r}
pt1521_ecoli_df <-combined %>% 
  filter(str_detect(sampleid, "^1521")) %>% 
  filter(str_detect(best_species, 'Escherichia'))
```

