---
title: "Narcotic"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(brms)   
library(ggpubr)
library(tidybayes)
ncores <- parallel::detectCores()
axis_text_size <- 10
```

```{r}
dat <- read_rds('/Volumes/vandenbrinklab/deep_sequencing/Clinical Annotation/Abx_data_TsoniIDB_pull_2020_07-06/allo_srx.rds')

ptb <- read_csv('../data/cleaned_patients/diet_patients_97.csv')

narcotic <- dat %>% 
  filter(is_narcotic == "Y") %>% 
  filter(grepl("PCA", med_name)) %>% 
  mutate(mrn = as.numeric(MRN)) %>% 
  filter(mrn %in% ptb$mrn) %>% 
  select(mrn, start_date, stop_date)

colnames(dat)

narcotic %>% 
  count(mrn, sort = T)

# there is one patient in our cohort that had narcotics in a previous tranplant but not relavant to us right now.
rm_pt <- narcotic %>% 
  mutate(start_year = year(start_date)) %>% 
  filter(start_year == 2016) %>% 
  distinct(mrn) %>% 
  pull(mrn)

narcotic_early_dates <- narcotic %>% 
  filter(mrn != rm_pt) %>% 
  group_by(mrn) %>% 
  arrange(start_date, .by_group = T) %>% 
  slice(1) %>% 
  ungroup() %>% 
  select(-stop_date)

narcotic_stop_dates <- narcotic %>% 
  filter(mrn != rm_pt) %>% 
  group_by(mrn) %>% 
  arrange(desc(stop_date), .by_group = T) %>% 
  slice(1) %>% 
  ungroup() %>% 
  select(-start_date)

nar_dates <- narcotic_early_dates %>% 
  full_join(narcotic_stop_dates) %>% 
  inner_join(ptb %>% 
               select(mrn, hct)) %>% 
  mutate(start_drt = start_date - hct,
         stop_drt = stop_date - hct) %>% 
  mutate(start_drt = as.numeric(start_drt),
         stop_drt = as.numeric(stop_drt)) %>% 
  # filter out certain periods that are not close to the current cohort transplant date
  filter(start_drt > -46 & start_drt < 82)

# the diet data is -10:49

# look closely at several patients that have very future stop dates, possibly another transplant or disease
change_stop <- nar_dates %>% 
  filter(stop_drt > 100) %>% 
  pull(mrn)

change_stop_date <- c('2019-08-21','2018-05-05','2017-10-13','2017-11-06','2019-07-26')

change <- tibble(
  mrn = change_stop,
  stop_date = change_stop_date
)

meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')

nar_correct <- nar_dates %>% 
  filter(mrn %in% change_stop) %>% 
  select(mrn, start_date, hct, start_drt) %>% 
  full_join(change) %>% 
  mutate(stop_date = ymd(stop_date),
         stop_drt = stop_date - hct,
         stop_drt = as.numeric(stop_drt))  %>% 
  select(colnames(nar_dates))
  
nar_all <- bind_rows(
  nar_dates %>% 
    filter(!mrn %in% change_stop) ,
  nar_correct
)  %>% 
  mutate(nar_int = interval(start_date, stop_date))

nar_all %>% 
  distinct(mrn)
```

```{r}
# clean the data for the second batch 
df2 <- read_rds('/Volumes/vandenBrinkLab/Angel_Dai/batch2_medication_exposures.rds')
ptb <- read_csv('../data/129_ptb2.csv')


pcas <- df2 %>% 
  filter(str_detect(route0, 'PCA IV') | str_detect(misc.info, 'PCA') | str_detect(drug_name_detail, 'PCA')) %>% 
  mutate(mrn = as.numeric(MRN)) %>% 
  filter(mrn %in% ptb$mrn) %>% 
  select(mrn, start_date, stop_date) %>% 
  inner_join(ptb %>% select(mrn, hct)) %>% 
  mutate(startday = as.numeric(start_date - hct),
         stopday = as.numeric(stop_date - hct)) %>% 
  # filter out certain periods that are not close to the current cohort transplant date
  filter(startday > -46 & startday < 82) %>% 
  mutate(nar_int = interval(start_date, stop_date))


library(vdbR)
connect_database('~/dbConfig.txt')
get_table_from_database('samples_castori_ag')
stb2 <- read_csv('../data/153_combined_META.csv') %>% filter(batch == 'batch2')
# find if two intervals overlap
stb_samp <- samples_castori_ag %>% 
  filter(sampleid %in% stb2$sampleid) %>% 
  select(sampleid, datecollection, mrn) %>% 
  mutate(p1d = datecollection -1,
         p2d = datecollection -2) %>% 
  mutate(p2d_int = interval(p2d, p1d)) %>% 
  inner_join(pcas %>% 
               select(mrn, nar_int) ) %>% 
  mutate(use_nar = int_overlaps(p2d_int, nar_int))

use_pca <- stb_samp %>% filter(use_nar == 'TRUE') %>% distinct(sampleid)
use_pca_pt <- stb_samp %>% filter(use_nar == 'TRUE') %>% distinct(mrn)


```


## decide if a patient was exposed to narcotics painkiller in the two days prior to a stool sample collection

```{r}
library(vdbR)
connect_database('~/dbConfig.txt')
get_table_from_database('samples_castori_ag')

# find if two intervals overlap
stb_samp1 <- samples_castori_ag %>% 
  filter(sampleid %in% meta$sampleid) %>% 
  select(sampleid, datecollection, mrn) %>% 
  mutate(p1d = datecollection -1,
         p2d = datecollection -2) %>% 
  mutate(p2d_int = interval(p2d, p1d)) %>% 
  inner_join(nar_all %>% 
               select(mrn, nar_int) ) %>% 
  mutate(use_nar = int_overlaps(p2d_int, nar_int))

use_nar_samp <- stb_samp1 %>% 
  filter(use_nar == 'TRUE')
# how many samples from how many patients
use_nar_samp %>% 
  count(mrn)

use_nar_samp1 <- use_nar_samp %>% 
  distinct(sampleid) %>% pull(sampleid)


```

```{r}
# the total list of the samples that were exposed to pca 
pca_exposed <- c(use_nar_samp1, use_pca %>% pull(sampleid))
```


```{r}
meta <- read_csv('../data/153_combined_META.csv')
meta_new <- meta %>% 
  mutate(narcotics = if_else(sampleid %in% pca_exposed, T, F))  %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = factor(mrn)) %>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100) %>%    
  mutate(abx = if_else(empirical == 'TRUE', 1, 0),
         TPN = if_else(TPN == 'TRUE', 1, 0),
         EN = if_else(EN == 'TRUE', 1, 0),
         pca = if_else(narcotics == 'TRUE', 1, 0)) %>% 
  mutate(      fg_fruit_e= fg_fruit*abx,
                fg_meat_e=fg_meat*abx,
                fg_milk_e=fg_milk*abx,
                fg_oils_e=fg_oils*abx,
                fg_egg_e=fg_egg*abx,
                fg_grain_e=fg_grain*abx,
                fg_sweets_e=fg_sweets*abx,
                fg_legume_e=fg_legume*abx,
                fg_veggie_e = fg_veggie*abx)

meta_new %>% count(narcotics) %>% filter(narcotics == 'TRUE')
```


```{r}
meta_new %>% filter(narcotics == 'TRUE') %>% distinct(mrn) %>% nrow
```


```{r}
model_nar <- log(simpson_reciprocal) ~ 0 +
                intensity+
               fg_fruit_e+
                fg_meat_e+
                fg_milk_e+
                fg_oils_e+
                fg_egg_e+
                fg_grain_e+
                fg_sweets_e+
                fg_legume_e+
                fg_veggie_e+
                abx+
               fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+
                fg_grain+
                fg_sweets+
                fg_legume+
                fg_veggie+
                TPN+
                EN+
                pca+
               (1 | mrn) +
                (1 | timebin)

priors <- c(# for the food group variables
            prior(normal(0, 1), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie"),
            # interaction terms
            prior(normal(0, 1), class = 'b', coef = "fg_egg_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie_e"),
            # for the TPN
            prior(normal(0, 0.1), class = 'b', coef = "TPN"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "EN"),
             # for the PCA
            prior(normal(0, 0.1), class = 'b', coef = "pca"),
            # for the empirical
            prior(normal(0, 0.5), class = 'b', coef = "abx"),
            # for the intensity
            prior(normal( 2, .1), class = 'b', coef = "intensityablative"),
            prior(normal( 2, .1), class = 'b', coef = "intensityreduced"),
            prior(normal( 2, .1), class = 'b', coef = "intensitynonablative")
            )

model_narcotics <- brm( model_nar,  
              data = meta_new, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              control = list(adapt_delta = 0.99),
              chains = 2, 
              seed = 123, sample_prior = T) 



post_pca <- suppressWarnings(posterior_samples(model_narcotics)) 

post_pca %>%  write_csv('../data/084_narcotics_PCA_model_post.csv')
```

```{r} 
fg_order <- c( 'Vegetables','abx + Vegetables',
                 'Oils','abx + Oils',
                 'Fruits','abx + Fruits',
                 'Meats','abx + Meats',
                 'Legumes','abx + Legumes',
                 'Eggs','abx + Eggs',
                 'Milk','abx + Milk',
                 'Grains','abx + Grains',
                 'Sweets','abx + Sweets',
                 "TPN" ,"EN" ,'PCA', 'abx')

key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')

fg_label <- tibble(ord = fg_order) %>% 
  mutate(shortname = str_replace(ord, 'abx \\+ ','')) %>% 
  left_join(key %>% select(shortname, color)) %>% 
  mutate(color = if_else(is.na(color), 'black', color))

cleaned_pca <- post_pca  %>% select(starts_with('b_')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item = str_replace(item, 'b_fg_',''),
         item = str_replace(item, 'b_',''),
         item = str_replace(item, 'intensity','')) %>% 
   mutate(fgrp1 = case_when(
    item ==  'milk' ~ '1',
    item == 'meat' ~ '2',
    item ==  'egg' ~ '3',
    item ==  'legume' ~ '4',
    item == 'grain' ~ '5',
    item == 'fruit' ~ '6',
    item == 'veggie' ~ '7',
    item ==  'oils' ~ '8', 
    item ==  'sweets' ~ '9'
  ))  %>% 
  left_join(key %>% select(fgrp1, color, shortname)) %>% 
  mutate(shortname = case_when(
        item ==  'milk_e' ~ 'abx + Milk',
    item == 'meat_e' ~ 'abx + Meats',
    item ==  'egg_e' ~ 'abx + Eggs',
    item ==  'legume_e' ~ 'abx + Legumes',
    item == 'grain_e' ~ 'abx + Grains',
    item == 'fruit_e' ~ 'abx + Fruits',
    item == 'veggie_e' ~ 'abx + Vegetables',
    item ==  'oils_e' ~ 'abx + Oils', 
    item ==  'sweets_e' ~ 'abx + Sweets',
    item ==  'nonablative' ~ 'Nonablative',
    item ==  'reduced' ~ 'Reduced',
    item ==  'ablative' ~ 'Ablative',
    item ==  'TPN' ~ 'TPN',
    item ==  'EN' ~ 'EN',
    item ==  'pca' ~ 'PCA',
    item ==  'abx' ~ 'abx',
    TRUE ~ `shortname`
  )) %>% 
  mutate(grp = if_else(item %in% c('nonablative','reduced','ablative'), 'patient', 'temporal'))

cross0 <- cleaned_pca %>%
   filter(grp == 'temporal') %>% 
  group_by(item) %>% 
  summarise(q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975)) %>% 
  mutate(Cross = if_else(q2.5 >= 0 | q97.5 <= 0, F, T))

pca_temporal <- cleaned_pca %>% 
  filter(grp == 'temporal') %>% 
  mutate(shortname = factor(shortname, levels = fg_label$ord)) %>% 
  left_join(cross0) %>% 
  ggplot(aes(x = coeff, y = shortname, col = Cross)) +
  stat_pointinterval(.width = c(.66, .95)) +
  #geom_rect( data = cleaned_fg, aes(xmin = -Inf  , xmax = Inf,  ymin = shortname, ymax = shortname), fill = "grey", alpha = 0.8) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  labs(x = 'ln(diversity) change', y = '') +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_manual(values = c("#EC0000", "black")) +
  theme(axis.text = element_text( size = 10),panel.background = element_rect(fill = "#d8dcec",colour = "#d8dcec",size = 0.5, linetype = "solid"),
        axis.title=element_text(size=10), 
        aspect.ratio=1.5)    
pca_temporal


pca_pt <- cleaned_pca %>% 
  filter(grp == 'patient') %>% 
  mutate(shortname = factor(shortname, levels = c('Nonablative','Reduced','Ablative'))) %>% 
  ggplot(aes(x = coeff, y = shortname)) +
  stat_pointinterval(.width = c(.66, .95)) +
  labs(x = 'ln(diversity) change', y = '') +
   #xlim(0.9, 3) +
  theme_classic() +
  theme(legend.position = 'none') +
  theme(axis.text = element_text( size = 10),
         panel.background = element_rect(fill = "#d0cccc",colour = "#d0cccc",size = 0.5, linetype = "solid"),axis.title=element_text(size=10), 
        aspect.ratio=1/3.1) 
pca_pt
```


```{r} 
library(cowplot)
pca_all <-  plot_grid(pca_temporal,pca_pt,
                rel_heights = c(2,1),align = 'vh',axis = 'lrtb',
                 nrow = 2)

title <- ggdraw() + 
  draw_label(
    "Fig. S6",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme( plot.margin = margin(0, 0, 0, 7))

 
combined <- plot_grid(
  title, pca_all,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
) +theme(plot.margin = unit(c(1,4,1,4), "cm"))

ggsave('../data/S6_pca_diversity_084.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', 
      plot = combined, 
      dpi = 300)
```



