---
title: "The full panel of the three lines for every patient"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
```

Make a figure with panels with each patient's timecourse in daily caloric intake, diet and stool alpha diversity as a supplementary figure.

```{r}
library(ggpubr)
library(tidyverse)
pt_line_size <- 0.2
alpha_val <- 1
point_size <- 0.5
diet_line_color <- '#E41A1C'
axis_text_size <- 3
axis_title_size <- 8
stool_line_color <- 'blue'
```


```{r}
# the three datasets split to each patient
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
stool <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')%>% 
  split(.$mrn)

# scale the faith pd and the day cal by dividing by 1000 and then revert this to the original scale by the axis representation
day_calori <- dtb %>% 
  group_by(mrn, fdrt) %>% 
  summarise(daycal = sum(Calories_kcal))%>% 
  mutate(daycal = daycal/1000) %>% 
  split(.$mrn)

faith <- read_tsv('../data/cleaned_diet_data/FINAL_97_faith_pd/alpha-diversity.tsv') %>% 
  separate(...1, into = c('mrn', 'fdrt'), sep = 'd', convert = T)  %>% 
  mutate(mrn = as.numeric(str_replace(mrn, 'P',''))) %>% 
  mutate(faith_pd = faith_pd/1000) %>% 
  split(.$mrn)



# keep the patients that have stool data
mrns <- names(meta)

# the range of the value 
# use the same y axis scale
range(read_tsv('../data/cleaned_diet_data/FINAL_97_faith_pd/alpha-diversity.tsv')$faith_pd)
range(stool$simpson_reciprocal)
```

```{r}
# to put the stool data in the same dimension as the diet data use a scaling factor to bring them to same level when plotting the y but then show on the  y axis scale that they are different
scale_factor <- 20

every_pt_list <-  mrns %>% 
  set_names(mrns) %>% 
  map(function(.x) {
      ggscatter(data =  day_calori[[.x]], x = 'fdrt', y = 'daycal', alpha = alpha_val, size = 0.5, 
                color = diet_line_color,
            xlab = 'Day relative to HCT',
            #title = str_glue('{.x}'),
            ylab = ''
            )  +
      geom_line(data = day_calori[[.x]], aes(x = fdrt, y = daycal), linetype = 'solid', size = pt_line_size, col = diet_line_color) +
      # the diet faith 
      geom_point(data = faith[[.x]], aes(x = fdrt, y = faith_pd), col = diet_line_color, size = point_size) +
      geom_line(data = faith[[.x]], aes(x = fdrt, y = faith_pd), linetype = 'dashed', size = pt_line_size, col = diet_line_color) +
      # the stool data
      geom_point(data = meta[[.x]], aes(x = sdrt, y = simpson_reciprocal/scale_factor), col = stool_line_color, size = point_size, shape = 'triangle') +
      geom_line(data = meta[[.x]], aes(x = sdrt, y = simpson_reciprocal/scale_factor), linetype = 'solid', size = pt_line_size, col = stool_line_color) +
    scale_y_continuous(name = "Daily calories / Faith div\n(*10e3)", limits = c(0, 2.6),
    sec.axis = sec_axis(~.*scale_factor, name = expression(Fecal~alpha~diversity))) +
  theme(axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        axis.title.y = element_text(color = diet_line_color),
        axis.title.y.right = element_text(color = stool_line_color),
        aspect.ratio=1)
  })

```

```{r}
# to put the stool data in the same dimension as the diet data use a scaling factor to bring them to same level when plotting the y but then show on the  y axis scale that they are different


whole_list <-  mrns %>% 
  set_names(mrns) %>% 
  map(function(.x) {
      ggscatter(data =  day_calori[[.x]], x = 'fdrt', y = 'daycal', alpha = alpha_val, size = 0, 
                color = diet_line_color,
            xlab = 'Day relative to HCT',
            #title = str_glue('{.x}'),
            ylab = ''
            )  +
      geom_line(data = day_calori[[.x]], aes(x = fdrt, y = daycal), linetype = 'solid', size = pt_line_size, col = diet_line_color) +
      # the diet faith 
      #geom_point(data = faith[[.x]], aes(x = fdrt, y = faith_pd), col = diet_line_color, size = point_size) +
      geom_line(data = faith[[.x]], aes(x = fdrt, y = faith_pd), linetype = 'dashed', size = pt_line_size, col = diet_line_color) +
      # the stool data
      #geom_point(data = meta[[.x]], aes(x = sdrt, y = simpson_reciprocal/scale_factor), col = stool_line_color, size = point_size, shape = 'triangle') +
      geom_line(data = meta[[.x]], aes(x = sdrt, y = simpson_reciprocal/scale_factor), linetype = 'solid', size = pt_line_size, col = stool_line_color) +
    scale_y_continuous(name = "", limits = c(0, 2.6),
    sec.axis = sec_axis(~.*scale_factor)) +
  theme(axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        axis.title.y = element_text(color = diet_line_color),
        axis.title.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.y = element_blank(),
        axis.title.y.right = element_text(color = stool_line_color),
        aspect.ratio=1)
  })

# arrange the above into a facet-wrap
library(gridExtra)
n <- length(whole_list)
nCol <- 8
all <- do.call("grid.arrange", c(whole_list, ncol=nCol))
ggsave('../figs/paper/085_all_patients_timecourse.eps', 
       width = 8, 
       height = 10,
       plot = all)
```

```{r}
# use one to be the example plot
example <- every_pt_list[[2]]

ggsave('../figs/paper/085_example_patient_timecourse.eps', 
        width = 60,
       height = 60,
         units = c("mm"),
         dpi = 400, device = 'eps',
       plot = example)
```

