---
title: "Figure 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(cowplot)
library(tidybayes)
```

```{r}
axis_text_size <- 10
axis_title_size <- 10
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')
```

# fig2 main figure

```{r 2a_procrustes}
procrustes_Nday_score <- read_csv('../data/022_procrustes_Nday_score.csv')
macro_pro <- read_csv('../data/091_macro_procrustes_Nday_score.csv')

two_score <- bind_rows(
  procrustes_Nday_score %>% mutate(grp = 'Food group based'), 
  macro_pro %>% mutate(grp = 'Macronutrient based')
)
```


```{r 2a_procrustes}
f2a <- two_score %>% 
  mutate(pNd = str_extract(pNd, '\\d')) %>% 
  arrange(desc(grp)) %>% 
  ggplot(aes(x = pNd, y = score, group = grp, color = grp)) +
  geom_line(size = 0.3) +
  geom_point(size = 1.3) +
  labs(x = 'Number of previous days\nof dietary intake',y = 'Procrustes score') +
  scale_color_manual(values = c('black','gray60')) +
  theme_classic()  +
  theme(aspect.ratio=1,
        legend.position = 'none',
        axis.text=element_text(size=axis_text_size), 
        legend.title  = element_blank(),
        axis.title=element_text(size=axis_text_size),
        axis.text.x = element_text(angle=0, hjust=0.5)) 
    
f2a
```
```{r 2b_diagram}
p <- '../figs/paper/cartoon_of_model.png'
diagram <- ggdraw() +
  draw_image(magick::image_read(p),   scale = 0.9) 
diagram 
```


```{r f2d_div_fac}
post_all <-  read_csv('../data/068_div_model_fg_post.csv')

coeff_bi <- post_all %>% 
  select(starts_with('b_')) %>% 
  select(!starts_with('b_fg')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item_name = case_when(
    item ==  'b_intensitynonablative' ~ 'nonablative',
    item == 'b_intensityablative' ~ 'ablative',
    item ==  'b_intensityreduced' ~ 'reduced',
    item ==  'b_empiricalTRUE' ~ 'Empirical abx',
    item == 'b_TPNTRUE' ~ 'TPN',
    item ==  'b_ENTRUE' ~ 'EN'
  )) %>% 
  mutate(item_name = factor(item_name, levels = c('nonablative', 'reduced',
                                                  'ablative', 'TPN','EN',
                                                  'Empirical abx'))) %>% 
  mutate(grp = if_else(str_detect(item_name, 'ablative|reduced'), 'Patient level', 'Sample level'))


percs <- coeff_bi %>% 
  filter(grp == 'Sample level') %>% 
  count(item_name, coeff > 0) %>% 
  mutate(perc =round(n/4000*100,1))  %>% select(-n) %>% 
  spread('coeff > 0', 'perc', fill = 0) %>% 
  rename(positive = 'TRUE', negative = 'FALSE') %>% 
  mutate(neg_num = negative) %>% 
  mutate(pos_x = 0.8, neg_x = -0.9) %>% 
  mutate(positive = str_glue('{positive}%'),
         negative = str_glue('{negative}%'))
```


```{r f2d_div_fac}
# modify it to be the look that we have discussed
f2d <- coeff_bi %>%
  ggplot(aes(x = coeff, y = item_name, fill = after_stat(x > 0))) +
  stat_pointinterval(.width = c( .95, .95), size = 0.1) + stat_halfeye() +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  #scale_fill_manual(values = c("gray80", "skyblue")) +
  facet_wrap(grp~ . , scales = 'free', dir = 'v') +
  labs(x = 'Intercept',
  y = '',
  title = '') +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_manual(values = c( "#00BFC4", "#F8766D")) +
  scale_fill_manual(values = c( "#00BFC4", "#F8766D")) +
  theme(axis.text=element_text(size=axis_text_size, color = 'black'),
  axis.title=element_text(size=axis_text_size)  ,legend.position = 'none',
        strip.background = element_blank(),
        strip.text = element_blank(),
        aspect.ratio=1/2) 




coeff_bi %>% 
  filter(item == 'b_ENTRUE') %>% 
  count(coeff < 0) %>% 
  mutate(perc = n / sum(n)*100)
       
```


```{r 2c_div_fg9}
f2c <- read_rds('../data/168_time_post_ridge.rds')
f2e <- read_rds('../data/068_div_post_ridge.rds')
 
```

```{r}
library(cowplot)
title <- ggdraw() + 
  draw_label(
    "Fig 2",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 7)
  )
```

```{r}
# new version that is without the diversity prediction thing
left <- cowplot::align_plots(f2a, f2c, align = 'v', axis = 'l')



top <- plot_grid(left[[1]], diagram, labels = c('A', 'B'),rel_widths  = c(1, 1) )



bottom <- plot_grid(  left[[2]],f2d,f2e,
                  nrow = 1, labels = c('C','D','E'), rel_widths  = c(1, 1,1))

f2 <-  plot_grid(top,bottom,
                 rel_heights = c(0.5,1),
                 nrow = 2)
f2

combined <- plot_grid(
  title, f2,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)

ggsave('../data/F2_model_results_086_new.pdf',
      width = 210, height = 167, units = "mm", device = 'pdf', plot = combined)
```



```{r align}
# output a version just for the legend of fig2A
f2a_legend <- two_score %>% 
  mutate(pNd = str_extract(pNd, '\\d')) %>% 
  arrange(desc(grp)) %>% 
  ggplot(aes(x = pNd, y = score, group = grp, color = grp)) +
  geom_line(size = 0.3) +
  geom_point(size = 1.3) +
  labs(x = 'Number of previous days\nof dietary intake',y = 'Procrustes score') +
  scale_color_manual(values = c('black','gray60')) +
  theme_classic()  +
  theme(aspect.ratio=1,
        #legend.position = 'none',
        axis.text=element_text(size=8), 
        legend.title  = element_blank(),
        axis.title=element_text(size=8),
        axis.text.x = element_text(angle=0, hjust=0.5)) 

#ggsave('../figs/paper/f2a_legend.pdf', plot =f2a_legend )
```

# accompanying supplementary figure

```{r}
library(cowplot)
title <- ggdraw() + 
  draw_label(
    "Fig S5",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 7)
  )

div_fac <- read_rds('../data/068_diversity_factor_forest.rds')
enter_fac <- read_rds('../data/087_entero_genus_factor_forest.rds')
fac2 <- plot_grid(  enter_fac,NA,
                  nrow = 1)

combined <- plot_grid(
  title, fac2,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)

ggsave('../data/S5_div_entero_factor_086.pdf',
      width = 210, height = 137, units = "mm", device = 'pdf', plot = combined)


```

# accompanying supp figures of the prior simulation of the div and enterococcus model

```{r}
div_prior <- read_rds('../data/068_prior_diversity_hist.rds')
enter_prior <- read_rds('../data/087_prior_enterococcus_hist.rds')
prior <- plot_grid(  div_prior,enter_prior,
                  nrow = 1, labels = c('A','B'), rel_widths = c(1, 1))

   
library(cowplot)
title <- ggdraw() + 
  draw_label(
    "Fig S4",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 7)
  )


combined <- plot_grid(
  title, prior,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)

ggsave('../data/S4_div_entero_prior_086.pdf',
       width = 210, height = 77, units = "mm", device = 'pdf', plot = combined)

```


```{r}
# to put the fg-div two plots together
div2 <- plot_grid(  f2c,div_fac,
                  nrow = 1, labels = c('A','B'), rel_widths = c(1, 1))

ggsave('../data/086_div_fg_2_086.jpg',
       width = 170, height = 60, units = c("mm"),
         dpi = 400, device = 'jpg', plot = div2)
```

