---
title: "Genus ~ fg"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(brms)
library(ggpubr)
options(mc.cores = parallel::detectCores())
rstan::rstan_options(auto_write = TRUE)
ncores <- parallel::detectCores()
dtb <- read_csv('../data/152_combined_DTB.csv')
meta <- read_csv('../data/153_combined_META.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = factor(mrn)) %>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100) 
axis_text_size <- 7
axis_title_size <- 7


```

# The food group predictors with genus as the outcome

```{r}
cts <- read_csv('../data/022_ALL173_stool_samples_genus_counts.csv') %>% 
  filter(sampleid %in% meta$sampleid) 
thre <- seq(0.0001, 0.002, 0.0001)
thre %>% 
  set_names(thre) %>% 
  map_dfr(function(num){
    cts %>% 
    group_by(genus) %>% 
    count(relab > num) %>% 
    rename(criteria = names(.)[2]) %>% 
    filter(criteria == 'TRUE') %>% 
    arrange(-n) %>% 
    filter(genus != 'NA') %>% 
    mutate(perc = round(n/nrow(meta)*100, 0)) %>% 
    filter(perc > 10) %>% 
      nrow
  }) %>% 
  gather('thre', 'num')
target_genera <-  cts %>% 
  group_by(genus) %>% 
  count(relab > 0.002) %>% 
  rename(criteria = names(.)[2]) %>% 
  filter(criteria == 'TRUE') %>% 
  arrange(-n) %>% 
  filter(genus != 'NA') %>% 
  mutate(perc = round(n/nrow(meta)*100, 0)) %>% 
  filter(perc > 10) %>% 
  pull(genus) 
```

```{r}
# please add to S8 klebsiella and other major enterobacteriaceae (e.g. top 5 enterobacteriaceae genera) 
# to find out what genera are in enterobacteriaceae
library(vdbR)
connect_database()
get_table_from_database('asv_annotation_blast_ag')
topn <- asv_annotation_blast_ag %>% 
  filter(family == 'Enterobacteriaceae') %>% 
  distinct(genus)

topn_cts <- cts %>% 
  filter(genus %in% topn$genus)
```


```{r}
thre <- seq(0.0001, 0.001, 0.0001)
thre %>% 
  set_names(thre) %>% 
  map_dfr(function(num){
    topn_cts %>% 
    group_by(genus) %>% 
    count(relab > num) %>% 
    rename(criteria = names(.)[2]) %>% 
    filter(criteria == 'TRUE') %>% 
    arrange(-n) %>% 
    filter(genus != 'NA') %>% 
    mutate(perc = round(n/nrow(meta)*100, 0)) %>% 
    filter(perc > 2) %>% 
      nrow
  }) %>% 
  gather('thre', 'num')

# the selected genus in Enterobacteriaceae
selected_Enterobacteriaceae <-  topn_cts %>% 
  group_by(genus) %>% 
  count(relab > 1e-04) %>% 
  rename(criteria = names(.)[2]) %>% 
  filter(criteria == 'TRUE') %>% 
  arrange(-n) %>% 
  filter(genus != 'NA') %>% 
  mutate(perc = round(n/nrow(meta)*100, 0)) %>% 
  filter(perc > 2) %>% 
  pull(genus)

extra <- read_csv('../data/088_genus_relab_log10_wide.csv') %>% 
  select(sampleid, all_of(selected_Enterobacteriaceae))

extra_full <- meta %>% 
  inner_join(extra)

pathobioents <- c('Enterococcus', selected_Enterobacteriaceae )
tibble(genus = pathobioents) %>% write_csv('../data/087_extra_6_genus_name.csv')
```

```{r}
priors <- c(# for the food group variables
            prior(normal(0, 1.2), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_veggie"),
            # for the TPN 
            prior(normal(0, 0.1), class = 'b', coef = "TPNTRUE"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "ENTRUE"),
            # for the empirical 
            prior(normal(0, 0.5), class = 'b', coef = "empiricalTRUE"),
            # for the intensity 
            prior(normal(-3, 1), class = 'b', coef = "intensityreduced"),
            prior(normal(-3, 1), class = 'b', coef = "intensityablative"),
            prior(normal(-3, 1), class = 'b', coef = "intensitynonablative"))
```


```{r}
ret_genus_extra <- selected_Enterobacteriaceae %>% 
  set_names(selected_Enterobacteriaceae) %>% 
  purrr::map(function(genus) {
    mod =  brm( as.formula(str_glue('{genus}  ~ 
               0 +
                fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               intensity +
                empirical+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin)')),  
                data = extra_full, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
              control = list(adapt_delta = 0.99),
              seed = 456, sample_prior = T) 
  })

prior_df <- ret_genus_extra %>% 
  imap(~ prior_draws(.x) ) %>% 
  bind_rows(.id = 'genus')
prior_df %>% 
  write_csv('../data/087_genus_foodgroup_model_prior_extra_few.csv')


post_df <- ret_genus_extra %>% 
  imap(~ (suppressWarnings(posterior_samples(.x)) ))  %>% 
  bind_rows(.id = 'genus')  
post_df %>% 
  write_csv('../data/087_genus_foodgroup_model_post_extra_few.csv')
```

```{r}
gcts <- read_csv('../data/088_genus_relab_log10_wide.csv') %>% 
  select(sampleid, all_of(target_genera))

full <- meta %>% 
  inner_join(gcts)


```

```{r}
ret_genus <- target_genera %>% 
  set_names(target_genera) %>% 
  purrr::map(function(genus) {
    mod =  brm( as.formula(str_glue('{genus}  ~ 
               0 +
                fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               intensity +
                empirical+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin)')),  
                data = full, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
              control = list(adapt_delta = 0.99),
              seed = 456, sample_prior = T) 
  })
```

```{r}
# save the data
prior_df <- ret_genus %>% 
  imap(~ prior_draws(.x) ) %>% 
  bind_rows(.id = 'genus') 
prior_df %>% 
  write_csv('../data/087_genus_foodgroup_model_prior.csv')

post_df <- ret_genus %>% 
  imap(~ (suppressWarnings(posterior_samples(.x)) ))  %>% 
  bind_rows(.id = 'genus')  
post_df %>% 
  write_csv('../data/087_genus_foodgroup_model_post.csv')
```

```{r}
mean_fg <-  meta %>% 
   select(starts_with('fg')) %>% 
   summarise_all(funs(mean))

  
valid_interval_perc <- ret_genus %>% 
  imap(~ prior_draws(.x) %>% 
            mutate(mean_genera = 
                     b_fg_fruit*mean_fg$fg_fruit +
                     b_fg_meat*mean_fg$fg_meat + 
                     b_fg_milk*mean_fg$fg_milk + 
                     b_fg_oils*mean_fg$fg_oils + 
                     b_fg_egg*mean_fg$fg_egg + 
                     b_fg_grain*mean_fg$fg_grain +
                     b_fg_sweets*mean_fg$fg_sweets +
                     b_fg_legume*mean_fg$fg_legume +
                     b_fg_veggie*mean_fg$fg_veggie +
                     b_intensityreduced ) %>% 
            select(mean_genera) %>% 
            mutate(grp = 'ave_each') %>% 
            rename(prior_res = mean_genera) %>% 
            select(grp, prior_res) %>% 
            count(prior_res > min(gcts$Streptococcus) & prior_res < max(gcts$Streptococcus)) %>% 
            mutate(perc = n/sum(n)*100) %>% 
            select(perc) %>% 
            slice(2) %>% 
            pull(perc) %>% 
            round(1) ) %>% 
  bind_rows(.id = .y) %>% 
  gather('genus','within_interval_perc')
```

```{r}
post_df <- read_csv('../data/087_genus_foodgroup_model_post.csv', col_select = c(1:10))
# post_extra <- read_csv('../data/087_genus_foodgroup_model_post_extra_few.csv', col_select = c(1:10))
# length(intersect(post_df$genus, post_extra$genus))
# unique(post_extra$genus)
# post_all <- bind_rows(post_df, post_extra)
fg_order <- read_csv('../data/068_fg_sorting_order.csv') %>% pull(shortname)
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')

post_res_genera <- post_df %>% 
  select(genus, starts_with('b_fg')) %>% 
  gather('item','coeff', names(.)[2]:names(.)[ncol(.)]) %>% 
  group_by(genus, item) %>% 
  summarise(q50 = median(coeff),
            q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975),
            q12.5 = quantile(coeff, probs = 0.125),
            q87.5 = quantile(coeff, probs = 0.875),
            q1.25 = quantile(coeff, probs = 0.0125),
            q98.75 = quantile(coeff, probs = 0.9875),
            q0.5 = quantile(coeff, probs = 0.005),
            q99.5 = quantile(coeff, probs = 0.995)
            ) %>% 
  ungroup() %>% 
  mutate(mark = if_else(q99.5 < 0 | q0.5 > 0, '***', if_else(q98.75 < 0 | q1.25 > 0, '**', if_else(q97.5 < 0 | q2.5 > 0, '*', '')))) %>% 
  mutate(color = if_else(q87.5 < 0, 'steelblue', if_else(q12.5 > 0, 'maroon', 'white'))) %>% 
  mutate(item = str_replace(item, 'b_ave_','')) %>% 
  mutate(item = str_to_title(item)) %>% 
  mutate(item = str_replace(item, 'B_','')) %>% 
  left_join(key %>% select(item = fg1_name, shortname))


col_key <- post_res_genera %>% 
  ungroup() %>% 
  distinct(color) %>% 
  pull(color)
names(col_key) <- col_key


```

```{r}
genus_fg_main <- ggplot(post_res_genera, aes(x = genus, y = shortname)) +
  geom_tile(aes(fill = color,  x = genus, y =  shortname), alpha = 0.5, color='white', width=0.95, height=0.95) +
  geom_text(aes(label = mark, x = genus,y =  shortname),
            nudge_y = -0.1, nudge_x = 0,size = 3) +
  scale_fill_manual(values = col_key, labels = c('Less than 75% CI crosses 0', '75% CI < 0 negative','75% CI > 0 positive')) +
  theme_pubr() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle=50, hjust=1, size=11),
        axis.text.y=element_text(size=11),
        axis.title=element_text(size=axis_title_size),
        #panel.grid.major = element_blank(), 
        #panel.grid.minor = element_blank(),
        legend.position = 'top',
        panel.background=element_rect(colour="black"),
        legend.key = element_rect( colour = "gray50")) 
genus_fg_main 
 
```

```{r}
# the factors for the genus-fg
post_df <- read_csv('../data/087_genus_foodgroup_model_post.csv', col_select = c(1, 14:16))
# post_extra <- read_csv('../data/087_genus_foodgroup_model_post_extra_few.csv', col_select = c(1, 14:16))
# 
# post_all <- bind_rows(post_df, post_extra)
 
post_bi_res <- post_df %>% 
  gather('item','coeff', names(.)[2]:names(.)[ncol(.)]) %>% 
  group_by(genus, item) %>% 
  summarise(q50 = median(coeff),
            q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975),
            q12.5 = quantile(coeff, probs = 0.125),
            q87.5 = quantile(coeff, probs = 0.875),
            q1.25 = quantile(coeff, probs = 0.0125),
            q98.75 = quantile(coeff, probs = 0.9875),
            q0.5 = quantile(coeff, probs = 0.005),
            q99.5 = quantile(coeff, probs = 0.995)
            ) %>% 
  ungroup() %>% 
  mutate(mark = if_else(q99.5 < 0 | q0.5 > 0, '***', if_else(q98.75 < 0 | q1.25 > 0, '**', if_else(q97.5 < 0 | q2.5 > 0, '*', '')))) %>% 
  mutate(color = if_else(q87.5 < 0, 'steelblue', if_else(q12.5 > 0, 'maroon', 'white'))) %>% 
  mutate(item_name = case_when(
    item ==  'b_empiricalTRUE' ~ 'Empirical abx exposure',
    item == 'b_TPNTRUE' ~ 'TPN exposure',
    item ==  'b_ENTRUE' ~ 'EN exposure'
  )) 


genus_fg_factor <- ggplot(post_bi_res, aes(x = genus, y = item_name)) +
  geom_tile(aes(fill = color,  x = genus, y =  item_name), alpha = 0.5, color='white', width=0.95, height=0.95) +
  geom_text(aes(label = mark, x = genus,y =  item_name),
            nudge_y = -0.1, nudge_x = 0,size = 3) +
  scale_fill_manual(values = col_key, labels = c('Less than 75% CI crosses 0','75% CI < 0 negative','75% CI > 0 positive')) +
  theme_pubr() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle=50, hjust=1, size=11),
        axis.text.y=element_text(size=11),
        axis.title=element_text(size=axis_title_size),
        #panel.grid.major = element_blank(), 
        #panel.grid.minor = element_blank(),
        legend.position = 'top',
        legend.key = element_rect( colour = "gray50"),
        panel.background = element_rect(colour="black")) 
genus_fg_factor
```

```{r}
# stack the two heatmap together
library(cowplot)
title <- ggdraw() + 
  draw_label(
    "Fig S7",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 7)
  )
heatmap <-  plot_grid(  genus_fg_main,genus_fg_factor,
                  nrow = 2, labels = c('A','B'), rel_heights  = c(1, 0.6), align = 'hv', axis = 'tblr')

combined <- plot_grid(
  title, heatmap,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)

ggsave( '../data/S7_heatmap_fg_genus_087.pdf',
     width = 210, height = 197, units = "mm", device = 'pdf', plot = combined)
```

## The Enterococcus genus as outcome

```{r}
entero_genus <- brm( Enterococcus  ~ 
               0 +
                fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               intensity +
                empirical+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin),  
                data = full, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
              control = list(adapt_delta = 0.99),
              seed = 456, sample_prior = T) 

post_enterco <- suppressWarnings(posterior_samples(entero_genus))
post_enterco %>%  write_csv('../data/087_Enterococcus_model_fg_post.csv')
```

```{r Enterococcus}
post_samples  <- read_csv('../data/087_Enterococcus_model_fg_post.csv')

nodes <- read_tsv('../data/source/NodeLabels_withcomma.txt', col_types = 'cc') %>% 
  filter(nchar(Level.code) == 1) %>% 
  rename(fgrp1 = Level.code, 
         fdesc = Main.food.description) 

key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc') 

post_coeff <- post_samples %>% 
  select(starts_with('b_fg')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item = str_replace(item, 'b_fg_','')) %>% 
   mutate(fgrp1 = case_when(
    item ==  'milk' ~ '1',
    item == 'meat' ~ '2',
    item ==  'egg' ~ '3',
    item ==  'legume' ~ '4',
    item == 'grain' ~ '5',
    item == 'fruit' ~ '6',
    item == 'veggie' ~ '7',
    item ==  'oils' ~ '8', 
    item ==  'sweets' ~ '9'
  ))  %>% 
  left_join(key) %>% 
  mutate(fdesc = str_replace_all(fdesc, '_',' ')) %>% 
  mutate(fdesc = str_wrap(fdesc, width = 28, indent = 2, exdent = 0)) %>% 
  mutate(fdesc = str_replace(fdesc, 'and','&')) %>% 
  left_join(key %>% select(fgrp1, color, shortname))  %>% 
  mutate(shortname = fct_reorder(shortname, coeff, .fun=median, .desc = F))  %>% 
  mutate(shortname = factor(shortname, levels = c("Fruits"  , "Sweets"  ,  "Vegetables", "Grains"    , "Milk"   ,    "Meats"    ,   "Eggs"      , "Legumes" ,   "Oils" )))

# find the 66 and 95 CI
post_coeff %>% 
  group_by(item) %>% 
  tidybayes::median_qi(coeff, .width = c( .66, .95))

post_coeff %>% 
  group_by(item) %>% 
  summarise(ave = mean(coeff))
```

```{r Enterococcus}
fg_colors <- post_coeff %>% 
  distinct(shortname, color) %>% 
  select(shortname, color) %>% 
  deframe()

# to find out if the group crosses zero or not
cross0 <- post_coeff %>%
  group_by(item) %>% 
  summarise(q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975)) %>% 
  mutate(Cross = if_else(q2.5 > 0 | q97.5 < 0, F, T))

# plotting the forest
Enterococcaceae_model_coeff <- post_coeff %>% 
  left_join(cross0) %>% 
  ggplot(aes(x = coeff, y = shortname, col = Cross)) +
  tidybayes::stat_pointinterval(.width = c(.66, .95)) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  labs(x = expression(paste(log[10], '(abundance) change', ' per 100g of food')),
       y = '',
       title = 'Enterococcus') +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_manual(values = c("#EC0000", "gray40")) +
  theme(axis.text=element_text(size=8),
        axis.title=element_text(size=8),
        aspect.ratio=1) 

Enterococcaceae_model_coeff %>% 
  write_rds('../data/087_entero_genus_fg_main.rds')

Enterococcaceae_model_coeff
```

```{r enterococcus_factor}
coeff_bi <- post_samples %>% 
  select(starts_with('b_')) %>% 
  select(!starts_with('b_fg')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item_name = case_when(
    item ==  'b_intensitynonablative' ~ 'Intensity: nonablative',
    item == 'b_intensityablative' ~ 'Intensity: ablative',
    item ==  'b_intensityreduced' ~ 'Intensity: reduced',
    item ==  'b_empiricalTRUE' ~ 'Empirical abx exposure',
    item == 'b_TPNTRUE' ~ 'TPN exposure',
    item ==  'b_ENTRUE' ~ 'EN exposure'
  )) %>% 
  mutate(item_name = factor(item_name, levels = c('Intensity: nonablative', 'Intensity: reduced',
                                                  'Intensity: ablative', 'TPN exposure','EN exposure',
                                                  'Empirical abx exposure'))) %>% 
  mutate(grp = if_else(str_detect(item_name, 'Intensity'), 'Patient level', 'Sample level'))


entero_genus_factor <- coeff_bi %>% 
  ggplot(aes(x = coeff, y = item_name)) +
  tidybayes::stat_pointinterval(.width = c(.66, .95)) +
  #scale_color_manual(values = c('#EC0000','#00468B')) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  facet_wrap(grp~ . , scales = 'free', dir = 'v') +
  labs(x = 'Coefficients',
       y = 'Factor variables',
       title = 'Enterococcus') +
  theme_classic() +
  theme(legend.position = 'none',
         strip.background = element_blank(),
        strip.text = element_blank(),
        aspect.ratio=1/2)
 
entero_genus_factor %>% write_rds('../data/087_entero_genus_factor_forest.rds')
```

```{r validate_prior}
prior_entero <- prior_draws(entero_genus) 

ave_each_fg_prior <- prior_entero %>% 
  mutate(mean_fg_prior_entero = 
           b_fg_fruit*mean_fg$fg_fruit +
           b_fg_meat*mean_fg$fg_meat + 
           b_fg_milk*mean_fg$fg_milk + 
           b_fg_oils*mean_fg$fg_oils + 
           b_fg_egg*mean_fg$fg_egg + 
           b_fg_grain*mean_fg$fg_grain +
           b_fg_sweets*mean_fg$fg_sweets +
           b_fg_legume*mean_fg$fg_legume +
           b_fg_veggie*mean_fg$fg_veggie +
           b_intensityreduced ) %>% 
  select(mean_fg_prior_entero) %>% 
  mutate(grp = 'ave_each')  %>% 
  mutate(within_range = if_else(mean_fg_prior_entero >= min(full$Enterococcus) &  mean_fg_prior_entero <= max(full$Enterococcus), T, F))

prior_enterococcus <- ave_each_fg_prior %>% 
  gghistogram(x = 'mean_fg_prior_entero', fill = 'within_range', color = 'white',
              xlab = 'Predicted log10(Enterococcus)\nwith prior distribution',
              title = 'Enterococcus') +
  geom_vline(xintercept = min(full$Enterococcus), linetype = 'dashed') +
  geom_vline(xintercept = max(full$Enterococcus), linetype = 'dashed')  +
  theme(legend.position = 'none')

ave_each_fg_prior %>% 
  count(within_range) %>% 
  mutate(perc = n/sum(n)*100)

prior_enterococcus %>% 
  write_rds('../data/087_prior_enterococcus_hist.rds'
  )
```

# Klebsiella as outcome  

```{r}
gcts_kle <- read_csv('../data/088_genus_relab_log10_wide.csv') %>% 
  select(sampleid, Klebsiella)

full_kle <- meta %>% 
  inner_join(gcts_kle)

kle_genus <- brm( Klebsiella  ~ 
               0 +
                fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               intensity +
                empirical+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin),  
                data = full_kle, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
              control = list(adapt_delta = 0.99),
              seed = 456, sample_prior = T) 

post_kle <- suppressWarnings(posterior_samples(kle_genus))
post_kle %>%  write_csv('../data/087_Klebsiella_model_fg_post.csv')

```

```{r}
post_samples  <- read_csv('../data/087_Klebsiella_model_fg_post.csv')
nodes <- read_tsv('../data/source/NodeLabels_withcomma.txt', col_types = 'cc') %>% 
  filter(nchar(Level.code) == 1) %>% 
  rename(fgrp1 = Level.code, 
         fdesc = Main.food.description) 
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc') 
post_coeff <- post_samples %>% 
  select(starts_with('b_fg')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item = str_replace(item, 'b_fg_','')) %>% 
   mutate(fgrp1 = case_when(
    item ==  'milk' ~ '1',
    item == 'meat' ~ '2',
    item ==  'egg' ~ '3',
    item ==  'legume' ~ '4',
    item == 'grain' ~ '5',
    item == 'fruit' ~ '6',
    item == 'veggie' ~ '7',
    item ==  'oils' ~ '8', 
    item ==  'sweets' ~ '9'
  ))  %>% 
  left_join(key) %>% 
  mutate(fdesc = str_replace_all(fdesc, '_',' ')) %>% 
  mutate(fdesc = str_wrap(fdesc, width = 28, indent = 2, exdent = 0)) %>% 
  mutate(fdesc = str_replace(fdesc, 'and','&')) %>% 
  left_join(key %>% select(fgrp1, color, shortname))  %>% 
  mutate(shortname = fct_reorder(shortname, coeff, .fun=median, .desc = F))  %>% 
  mutate(shortname = factor(shortname, levels = c("Fruits"  , "Sweets"  ,  "Vegetables", "Grains"    , "Milk"   ,    "Meats"    ,   "Eggs"      , "Legumes" ,   "Oils" )))

```
```{r}
fg_colors <- post_coeff %>% 
  distinct(shortname, color) %>% 
  select(shortname, color) %>% 
  deframe()
# to find out if the group crosses zero or not
cross0 <- post_coeff %>%
  group_by(item) %>% 
  summarise(q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975)) %>% 
  mutate(Cross = if_else(q2.5 > 0 | q97.5 < 0, F, T))
# plotting the forest
kle_model_coeff <- post_coeff %>% 
  left_join(cross0) %>% 
  ggplot(aes(x = coeff, y = shortname, col = Cross)) +
  tidybayes::stat_pointinterval(.width = c(.66, .95)) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  labs(x = expression(paste(log[10], '(abundance) change', ' per 100g of food')),
       y = '',
       title = 'Klebsiella') +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_manual(values = c("gray40", "#EC0000")) +
  theme(axis.text=element_text(size=8),
        axis.title=element_text(size=8),
        aspect.ratio=1) 
# kle_model_coeff %>% 
#   write_rds('../data/087_entero_genus_fg_main.rds')
kle_model_coeff

# plot the distribution of the relab of kle
cts %>% 
  filter(genus == 'Klebsiella') %>% 
  ggboxplot(y = 'relab', add = 'jitter', add.params = list(color  = 'forestgreen', alpha = 0.5)) +
  scale_y_log10()

kle <- cts %>% 
  filter(genus == 'Klebsiella')

quantile(kle$relab, 0.7 )
```

