---
title: "beta diversity visualization"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
library(tidyverse)
library(ape)
library(vegan)
library(ggpubr)
```

Check the beta distance matrix

```{r}
beta_un_uni <- read.delim('../data/finalized/beta_phylo/distance-matrix.tsv', sep = '\t', row.names = 1)
food_dist <- as.dist(beta_un_uni)

#pcoa
pcoa_f <- as.data.frame(pcoa(food_dist)$vectors) %>% 
  select(Axis.1, Axis.2) %>% 
  rownames_to_column('mrnDay') %>% 
  separate(mrnDay, into = c('mrn','DayRT'), sep = 'd') %>% 
  mutate(DayRT = str_replace(DayRT,'_','-'),
         DayRT = as.numeric(DayRT),
         mrn = as.numeric(mrn))

# the percent variance
eigen <- pcoa(food_dist)$values$Eigenvalues

percent_var <- signif(eigen/sum(eigen), 4)*100
```

```{r}
# load the pheno data of the patients 
pheno <- read_csv('../data/pheno/final_pheno.csv')

# join the coords with the pheno
beta_un_uni_df <- pcoa_f %>% 
  left_join(pheno, by  = 'mrn')
```

```{r}
# don't split and color all of them by DRT
beta_un_uni_df %>% 
  mutate(mrn = factor(as.character(mrn))) %>% 
ggplot( aes(x = Axis.1, y = Axis.2, col = DayRT)) +
  geom_point(alpha=0.75, size = 2) +
  #stat_ellipse(color = "dark grey", type = "norm", linetype = 2, level = 0.95, alpha = 0.5) +
  theme_classic() +
  scale_color_gradient(low = "yellow", high = "darkblue")
```


```{r}
# plot mark the source and the intensity
beta_un_uni_df %>% 
  mutate(mrn = factor(as.character(mrn))) %>% 
ggplot( aes(x = Axis.1, y = Axis.2, shape = source , col = intensity)) +
  geom_point(alpha=0.75, size = 2) +
  #stat_ellipse(color = "dark grey", type = "norm", linetype = 2, level = 0.95, alpha = 0.5) +
  theme_classic() +
  scale_color_brewer(palette = 'Set1') +
  facet_wrap(~source) +
  ggsave('../figs/beta_un_unifrac_all_pts_source_intensity.jpg', width = 12, height = 8)

```
```{r}
beta_un_uni_df %>% 
  mutate(mrn = factor(as.character(mrn))) %>% 
ggplot( aes(x = Axis.1, y = Axis.2,  col = DayRT)) +
  geom_point(alpha=0.9, size = 2) +
  #stat_ellipse(color = "dark grey", type = "norm", linetype = 2, level = 0.95, alpha = 0.5) +
  theme_classic() +
  scale_color_gradient2(low = "yellow", mid = "red", high = "blue", midpoint = 10) +
  facet_wrap(intensity~source) +
  ggsave('../figs/beta_un_unifrac_all_pts_DayRT.jpg', width = 12, height = 8)
```
```{r}
# look at the distribution of the DayRT cuz have fewer large values
beta_un_uni_df %>% 
  gghistogram('DayRT', bins = 120, fill = 'forestgreen', color = 'white',
              title = 'Distribution of day relative to transplant of the food records',
              xlab = 'Day relative to transplant')
```



```{r}
# include the earlier time points records only
beta_un_uni_df %>% 
  filter(DayRT %in% -10:15) %>% 
  mutate(mrn = factor(as.character(mrn))) %>% 
ggplot( aes(x = Axis.1, y = Axis.2,  col = DayRT)) +
  geom_point(alpha=0.9, size = 2) +
  #stat_ellipse(color = "dark grey", type = "norm", linetype = 2, level = 0.95, alpha = 0.5) +
  theme_classic() +
  scale_color_gradient(low = "yellow", high = "darkblue")  +
  facet_wrap(intensity~source) +
  ggsave('../figs/beta_un_unifrac_all_pts_DayRT_early.jpg', width = 12, height = 8)
```

```{r}
beta_un_uni_df %>% 
  mutate(grp = if_else(DayRT <= -2, 'before', 'after')) %>% 
  mutate(grp = factor(grp, levels = c('before','after'))) %>% 
  ggboxplot(x = 'grp', y = 'Axis.2', add = 'jitter', color = 'grp', palette = 'nejm',
            title = 'Axis 2 unifrac distance PCOA between before and after day -2') +
  stat_compare_means(comparisons = list(c('before', 'after')),
                      label = "p.signif",
                      method = 'wilcox.test',
                      correct=FALSE)
```

```{r}

```

```{r}
# or log transform the time and see if it will be clearer
beta_un_uni_df %>% 
  mutate(DayRT = DayRT + 50,
         log2DayRT = log2(DayRT)) %>% 
  mutate(mrn = factor(as.character(mrn))) %>% 
ggplot( aes(x = Axis.1, y = Axis.2,  col = log2DayRT)) +
  geom_point(alpha=0.9, size = 2) +
  #stat_ellipse(color = "dark grey", type = "norm", linetype = 2, level = 0.95, alpha = 0.5) +
  theme_classic() +
  scale_color_gradient(low = "yellow", high = "darkblue")  +
  facet_wrap(intensity~source) +
  ggsave('../figs/beta_un_unifrac_all_pts_DayRT_log_time.jpg', width = 12, height = 8)
```


```{r out.width="100%"}
# split by each patient and color by day 

beta_un_uni_df %>% 
  ggplot(aes(x = Axis.1, y = Axis.2, color = DayRT, shape = intensity)) +
  geom_point(size = 2) +
  scale_color_continuous(type = 'viridis') +
  theme_classic() +
  facet_wrap(source ~ mrn)  +
  ggsave('../figs/beta_un_unifrac_all_pts.jpg', width = 20, height = 15)
```

```{r}
# one figure for each patient
# beta_un_uni_df %>% 
#   mutate(source = factor(source)) %>% 
#   split(.$mrn) %>% 
#   map(~ ggplot(data = ., aes(x = Axis.1, y = Axis.2, color = DayRT, shape = intensity, size = source)) +
#   geom_point(size = 2) +
#   scale_color_continuous(type = 'viridis') +
#   theme_classic())
  
```


