---
title: "Macronutrients with diversity or genus"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Previous 2 day results** 

```{r}
library(tidyverse)
library(ggpubr)
library(tidybayes)  
library(brms)
library(rstan)
options(mc.cores = parallel::detectCores())
ncores = parallel::detectCores()
rstan_options(auto_write = TRUE)
axis_text_size <- 10
axis_title_size <- 10
#dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
dtb <- read_csv('../data/152_combined_DTB.csv')
meta <- read_csv('../data/153_combined_META.csv') 
```
```{r}
cts <- read_csv('../data/022_ALL173_stool_samples_genus_counts.csv') %>% 
  filter(sampleid %in% meta$sampleid) 
thre <- seq(0.0001, 0.002, 0.0001)
thre %>% 
  set_names(thre) %>% 
  map_dfr(function(num){
    cts %>% 
    group_by(genus) %>% 
    count(relab > num) %>% 
    rename(criteria = names(.)[2]) %>% 
    filter(criteria == 'TRUE') %>% 
    arrange(-n) %>% 
    filter(genus != 'NA') %>% 
    mutate(perc = round(n/nrow(meta)*100, 0)) %>% 
    filter(perc > 10) %>% 
      nrow
  }) %>% 
  gather('thre', 'num')
target_genera <-  cts %>% 
  group_by(genus) %>% 
  count(relab > 0.0001) %>% 
  rename(criteria = names(.)[2]) %>% 
  filter(criteria == 'TRUE') %>% 
  arrange(-n) %>% 
  filter(genus != 'NA') %>% 
  mutate(perc = round(n/nrow(meta)*100, 0)) %>% 
  filter(perc > 10) %>% 
  pull(genus) 

gcts <- read_csv('../data/088_genus_relab_log10_wide.csv') %>% 
  select(sampleid, all_of(target_genera))

full <- meta %>% 
  inner_join(gcts)
```
## p2d average in macronutrients

```{r}
# the daily caloric intake :
all_daily_pt <- dtb %>%
  group_by(mrn, fdrt) %>%
  summarise(total_daily = sum(Calories_kcal))

# the previous two days average for each stool sample

stb_pair <- meta %>%
  select(mrn, sdrt) %>%
  transmute(mrn = mrn,
            p1d = sdrt-1,
            p2d = sdrt-2)

mean_p2d_cal <-  function(mrn_, p1d_, p2d_){
  df = all_daily_pt %>%
    filter(mrn == mrn_) %>%
    filter(fdrt %in% c(p1d_, p2d_  )) %>%
    group_by(mrn) %>%
    summarise(ave_cal = sum(total_daily)/2)
  return(df)
}

mean_p2d_df_cal <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_cal(mrn, p1d, p2d)
  }) %>%
  set_names(meta %>% pull(sampleid)) %>%
  bind_rows(.id = 'sampleid')
```

```{r p2d_nutrients}
# the daily total of each nutrients
nutrients <- dtb %>%
  select(mrn, fdrt, Protein_g:Sugars_g) %>%
  gather('type','gram', Protein_g:Sugars_g) %>%
  group_by(mrn, fdrt, type) %>%
  summarise(total_daily = sum(gram)) %>%
  split(.$type)

mean_p2d_fiber <-  function(mrn_, p1d_, p2d_){
  df = nutrients$Fibers_g %>%
    filter(mrn == mrn_) %>%
    filter(fdrt %in% c(p1d_, p2d_  )) %>%
    group_by(mrn) %>%
    summarise(ave_fiber = sum(total_daily)/2)
  return(df)
}
mean_p2d_carb <-  function(mrn_, p1d_, p2d_){
  df = nutrients$Carbohydrates_g %>%
    filter(mrn == mrn_) %>%
    filter(fdrt %in% c(p1d_, p2d_  )) %>%
    group_by(mrn) %>%
    summarise(ave_carb = sum(total_daily)/2)
  return(df)
}

mean_p2d_fat <-  function(mrn_, p1d_, p2d_){
  df = nutrients$Fat_g %>%
    filter(mrn == mrn_) %>%
    filter(fdrt %in% c(p1d_, p2d_  )) %>%
    group_by(mrn) %>%
    summarise(ave_fat = sum(total_daily)/2)
  return(df)
}
mean_p2d_Protein <-  function(mrn_, p1d_, p2d_){
  df = nutrients$Protein_g %>%
    filter(mrn == mrn_) %>%
    filter(fdrt %in% c(p1d_, p2d_  )) %>%
    group_by(mrn) %>%
    summarise(ave_Protein = sum(total_daily)/2)
  return(df)
}
mean_p2d_Sugars <-  function(mrn_, p1d_, p2d_){
  df = nutrients$Sugars_g %>%
    filter(mrn == mrn_) %>%
    filter(fdrt %in% c(p1d_, p2d_  )) %>%
    group_by(mrn) %>%
    summarise(ave_Sugars = sum(total_daily)/2)
  return(df)
}

mean_p2d_fiber <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_fiber(mrn, p1d, p2d)
  }) %>%
  set_names(meta %>% pull(sampleid)) %>%
  bind_rows(.id = 'sampleid')

mean_p2d_fat <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_fat(mrn, p1d, p2d)
  }) %>%
  set_names(meta %>% pull(sampleid)) %>%
  bind_rows(.id = 'sampleid')

mean_p2d_Protein <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_Protein(mrn, p1d, p2d)
  }) %>%
  set_names(meta %>% pull(sampleid)) %>%
  bind_rows(.id = 'sampleid')

mean_p2d_Sugars <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_Sugars(mrn, p1d, p2d)
  }) %>%
  set_names(meta %>% pull(sampleid)) %>%
  bind_rows(.id = 'sampleid')

mean_p2d_carb <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_carb(mrn, p1d, p2d)
  }) %>%
  set_names(meta %>% pull(sampleid)) %>%
  bind_rows(.id = 'sampleid')

p2d_diet <- mean_p2d_df_cal %>%
  full_join(mean_p2d_fiber, by = c("sampleid", "mrn")) %>%
  full_join(mean_p2d_fat, by = c("sampleid", "mrn")) %>%
  full_join(mean_p2d_Protein, by = c("sampleid", "mrn")) %>%
  full_join(mean_p2d_Sugars, by = c("sampleid", "mrn")) %>%
  full_join(mean_p2d_carb, by = c("sampleid", "mrn"))
```


```{r p2d_nutrients}
full <- meta %>%
  full_join(p2d_diet, by = c("sampleid", "mrn")) %>%
  full_join(gcts, by = "sampleid") %>%
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>%
  mutate(mrn = factor(mrn)) %>%
  mutate(ave_fiber = ave_fiber/100,
       ave_fat = ave_fat/100,
       ave_Protein = ave_Protein/100,
       ave_Sugars = ave_Sugars/100,
       ave_carb = ave_carb/100,
       ave_cal = ave_cal/1000
       ) %>% 
  mutate(intensityAblative = if_else(intensity == 'ablative', T, F),
         intensityNonablative = if_else(intensity == 'nonablative', T, F),
         intensityReduced = if_else(intensity == 'reduced', T, F))

full %>%
  write_csv('../data/090_all_samples_meta_p2d_fg9_dietall_genera90.csv')
```



```{r}
# the high correlation between fat and protein 
fat_pro_cor <- full %>% 
  ggscatter(x = 'ave_fat', y = 'ave_Protein', alpha = 0.2, point = 16, 
            xlab = 'Average fat intake', ylab = 'Average protein intake',
             add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "pearson",  label.sep = "\n"))+
  theme_classic() +
  theme(legend.position = 'none') +
  theme(axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        aspect.ratio=1)

fat_pro_cor %>% write_rds('../data/090_fat_pro_cor.rds')


# the correlation between fat and caloric intake
fat_cal_cor <- full %>% 
  ggscatter(x = 'ave_fat', y = 'ave_cal', alpha = 0.2, point = 16, 
            xlab = 'Average fat intake', ylab = 'Average caloric intake',
             add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "pearson",  label.sep = "\n"))+
  theme_classic() +
  theme(legend.position = 'none') +
  theme(axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        aspect.ratio=1)

fat_cal_cor %>% write_rds('../data/090_fat_cal_cor.rds')

full %>% 
  ggscatter(x = 'ave_fat', y = 'ave_Sugars', alpha = 0.2, point = 16, 
            xlab = 'Average fat intake', ylab = 'Average sugar intake',
             add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "pearson",  label.sep = "\n"))+
  theme_classic() +
  theme(legend.position = 'none') +
  theme(axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        aspect.ratio=1)
```


### simpson reciprocal ~ ave_fiber + ave_fat + ave_Sugars + empirical + intensity + TPN + EN + ...

```{r}
alpha_macro_fat <- log(simpson_reciprocal) ~ 0 +
                ave_fiber +
                ave_fat +
                ave_Sugars +
               intensity +
               EN +
                TPN +
                empirical +
               (1 | mrn) +
                (1 | timebin)

priors_alpha_macro_fat <- c(
            # for the macro nutrients
            prior(normal(0, 0.4), class = 'b', coef = "ave_fiber"),
            prior(normal(0, 0.4), class = 'b', coef = "ave_fat"),
            prior(normal(0, 0.4), class = 'b', coef = "ave_Sugars"),
            # for the TPN 
            prior(normal(0, 0.1), class = 'b', coef = "TPNTRUE"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "ENTRUE"),
            # for the empirical 
            prior(normal(0, 0.5), class = 'b', coef = "empiricalTRUE"),
            # for the intensity 
            prior(normal(2, 0.1), class = 'b', coef = "intensityreduced"),
            prior(normal(2, 0.1), class = 'b', coef = "intensityablative"),
            prior(normal(2, 0.1), class = 'b', coef = "intensitynonablative"))

# vet the prior 
model_alpha_macro_fat  <- brm( alpha_macro_fat,  
              data = full, 
              warmup = 1000, iter = 3000, 
              prior = priors_alpha_macro_fat,
               control = list(adapt_delta = 0.99),
              cores = ncores,
              chains = 2, 
              seed = 123, sample_prior = T)


post_res <- suppressWarnings(posterior_samples(model_alpha_macro_fat))
post_res %>%  write_csv('../data/090_model_alpha_macro_fat_post.csv')

prior_df <- prior_draws(model_alpha_macro_fat) 
prior_df %>% 
  write_csv('../data/090_model_alpha_macro_fat_prior.csv')
```


```{r}
mean_macro <-  full %>% 
  select(starts_with('ave_')) %>% 
  summarise_all(funs(mean))

mean_ave_macro_fat_prior <- prior_draws(model_alpha_macro_fat) %>% 
  mutate(mean_div = 
          b_ave_fiber * mean_macro$ave_fiber+
           b_ave_fat * mean_macro$ave_fat+
           b_ave_Sugars * mean_macro$ave_Sugars+
           b_intensityreduced ) %>% 
  select(mean_div) %>% 
  mutate(grp = 'mean_macro_fat') %>% 
  rename(prior_res = mean_div) %>% 
  select(grp, prior_res)

within_perc <- mean_ave_macro_fat_prior %>% 
  mutate(within = if_else(  between(prior_res, min(log(full$simpson_reciprocal)), max(log(full$simpson_reciprocal))), T, F) ) %>% 
  count(within) %>% 
  mutate(perc = round(n/sum(n)*100, 2))
  
```

```{r}
# plot the above model post coeff
post_coeff <- read_csv('../data/090_model_alpha_macro_fat_post.csv') %>% 
  select(starts_with('b_ave')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item = str_replace(item, 'b_ave_','')) %>% 
   mutate(item = case_when(
    item ==  'fiber' ~ 'Fibers',
    item == 'fat' ~ 'Fat',
    TRUE ~ item
  ))  %>% 
  mutate(item = fct_reorder(item, coeff, .fun=median, .desc = F)) 

macronutrients_alpha_main <- post_coeff %>% 
  ggplot(aes(x = coeff, y = item)) +
  stat_pointinterval(.width = c(.66, .95)) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  labs(x = 'Coefficients',
       y = 'Macronutrients',
       title = expression(Microbiome~alpha~diversity)) +
  theme_classic() +
  theme(legend.position = 'none') +
  theme(axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        aspect.ratio=1)

macronutrients_alpha_main %>% 
  write_rds('../data/090_macronutrients_alpha_main.rds')


# get the value of the actual 66% and 95% CI
post_coeff %>% 
  group_by(item) %>% 
  median_qi(coeff, .width = c(.66, .95)) %>% 
  distinct()
```

```{r}
# the binary vars
coeff_bi <- read_csv('../data/090_model_alpha_macro_fat_post.csv')   %>% 
  select(starts_with('b_')) %>% 
  select(!starts_with('b_ave')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item_name = case_when(
    item ==  'b_intensitynonablative' ~ 'Intensity: nonablative',
    item == 'b_intensityablative' ~ 'Intensity: ablative',
    item ==  'b_intensityreduced' ~ 'Intensity: reduced',
    item ==  'b_empiricalTRUE' ~ 'Empirical abx exposure',
    item == 'b_TPNTRUE' ~ 'TPN exposure',
    item ==  'b_ENTRUE' ~ 'EN exposure'
  )) %>% 
  mutate(item_name = factor(item_name, levels = c('Intensity: nonablative', 'Intensity: reduced',
                                                  'Intensity: ablative', 'TPN exposure','EN exposure',
                                                  'Empirical abx exposure'))) %>% 
  mutate(grp = if_else(str_detect(item_name, 'Intensity'), 'Patient level', 'Sample level'))

macronutrients_alpha_factor <- coeff_bi %>% 
  ggplot(aes(x = coeff, y = item_name)) +
  stat_pointinterval(.width = c(.66, .95)) +
  #scale_color_manual(values = c('#EC0000','#00468B')) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
   facet_wrap(grp~ . , scales = 'free', dir = 'v') +
  labs(x = 'Coefficients',
       y = 'Factor variables',
       title = expression(Microbiome~alpha~diversity)) +
  theme_classic() +
  theme(legend.position = 'none',
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        strip.background = element_blank(),
        strip.text = element_blank(),
        aspect.ratio=1/2)


macronutrients_alpha_factor %>% 
  write_rds('../data/090_macronutrients_alpha_factor.rds')

coeff_bi %>% 
  group_by(item) %>% 
  median_qi(coeff, .width = c(.66, .95)) 

# find the perc of EN < 0
coeff_bi %>% 
  filter(item == 'b_ENTRUE') %>% 
  count(coeff < 0) %>% 
  mutate(perc = n / sum(n)*100)
```



### genus ~ ave_fiber + ave_fat + ave_Sugars + empirical + intensity + TPN + EN + ...

```{r}
# The outcome being each of the genus
# to test and confirm the prior
Enterococcus_mod <- Enterococcus ~ 1 +
              ave_fiber +
              ave_fat +
                ave_Sugars +
               inten_non + inten_ab + inten_re +
                empirical+
                TPN+
                EN+ 
               (1 | mrn) +
                (1 | timebin)

priors_genus_macro_fat <- c(
            # for the macro nutrients
            prior(normal(0, 0.4), class = 'b', coef = "ave_fiber"),
            prior(normal(0, 0.4), class = 'b', coef = "ave_fat"),
            prior(normal(0, 0.4), class = 'b', coef = "ave_Sugars"),
            # for the TPN 
            prior(normal(0, 0.1), class = 'b', coef = "TPNTRUE"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "ENTRUE"),
            # for the empirical 
            prior(normal(0, 0.5), class = 'b', coef = "empiricalTRUE"),
            # for the intensity 
            prior(normal(-3, 1), class = 'b', coef = "intensityreduced"),
            prior(normal(-3, 1), class = 'b', coef = "intensityablative"),
            prior(normal(-3, 1), class = 'b', coef = "intensitynonablative"))

# 
# Enterococcus_model <- brm( Enterococcus_mod,  
#               data = full, 
#               warmup = 1000, iter = 3000, 
#               prior = priors_genus_macro_fat,
#               cores = ncores, 
#               chains = 2, 
#               control = list(adapt_delta = 0.99),
#               seed = 123, sample_prior = T )
```


```{r}
# coeff_bi <- post_samples %>% 
#   select(!starts_with('b_fg')) %>% 
#   select(-b_Intercept) %>% 
#   gather('item', 'coeff') %>% 
#   mutate(item_name = case_when(
#     item ==  'b_inten_non' ~ 'Intensity: nonablative',
#     item == 'b_inten_ab' ~ 'Intensity: ablative',
#     item ==  'b_inten_re' ~ 'Intensity: reduced',
#     item ==  'b_empiricalTRUE' ~ 'Empirical abx exposure',
#     item == 'b_TPNTRUE' ~ 'TPN exposure',
#     item ==  'b_ENTRUE' ~ 'EN exposure'
#   )) %>% 
#   mutate(item = factor(item, levels = c('b_empiF','b_empiT','b_inten_non','b_inten_re','b_inten_ab','b_enF','b_enT','b_tpnF','b_tpnT'))) %>% 
#   mutate(item_name = fct_reorder(item_name, coeff, .fun=median, .desc = F)) 
# 
# coeff_bi %>% 
#   ggplot(aes(x = coeff, y = item_name)) +
#   stat_pointinterval(.width = c(.66, .95)) +
#   #scale_color_manual(values = c('#EC0000','#00468B')) +
#   geom_vline(xintercept = 0, col = 'red', linetype = 'dashed') +
#   labs(x = 'Regression coefficients',
#        y = 'Binary variables') +
#   theme_classic() +
#   theme(legend.position = 'none',
#         aspect.ratio=1)
```


```{r}
# check the priors
# mean_enterococcus_prior <- prior_draws(Enterococcus_model) %>% 
#   mutate(mean_genus = Intercept + 
#           b_ave_fiber * mean_macro$ave_fiber+
#            b_ave_fat * mean_macro$ave_fat+
#            b_ave_Sugars * mean_macro$ave_Sugars+
#            b_inten_re ) %>% 
#   select(mean_genus) %>% 
#   mutate(grp = 'mean_enterococcus') %>% 
#   rename(prior_res = mean_genus) %>% 
#   select(grp, prior_res)
# 
# # calculate the percentage that falls within the actual range of the data
# mean_enterococcus_prior %>% 
#   count(prior_res >= min(full$Enterococcus) & prior_res <= max(full$Enterococcus)) %>% 
#   mutate(fraction = round(n /sum(n), 2))  %>% 
#   slice(2) %>% 
#   pull(fraction)
# 
# # look at the post
# post_coeff <- posterior_samples(Enterococcus_model, '^b_') %>% 
#   select(starts_with('b_ave')) %>% 
#   gather('item', 'coeff') %>% 
#   mutate(item = str_replace(item, 'b_ave_','')) %>% 
#    mutate(item = case_when(
#     item ==  'fiber' ~ 'Fibers',
#     item == 'fat' ~ 'Fat',
#     item ==  'carb' ~ 'Carbohydrates',
#     TRUE ~ item
#   ))  %>% 
#   mutate(item = fct_reorder(item, coeff, .fun=median, .desc = F)) 
# 
# post_coeff %>% 
#   ggplot(aes(x = coeff, y = item)) +
#   stat_pointinterval(.width = c(.66, .95)) +
#   geom_vline(xintercept = 0, col = 'red', linetype = 'dashed') +
#   labs(x = 'Coefficients',
#        y = 'Macronutrients') +
#   theme_classic() +
#   theme(legend.position = 'none') +
#   theme(axis.text=element_text(size=axis_text_size),
#         axis.title=element_text(size=axis_title_size),
#         aspect.ratio=1)
# 
# ggsave('../figs/paper/090_macro_fat_Enterococcus_model.eps' ,width = 80,
#        height = 80,
#          #height = 60,
#          units = c("mm"),
#          dpi = 400, device = 'eps')

```

#### All genera
 
```{r}
ret_genus_macro_fat <- target_genera %>% 
  set_names(target_genera) %>% 
  purrr::map(function(genus) {
    mod =  brm( as.formula(str_glue('{genus}  ~ 
               0 +
               ave_fiber +
               ave_fat +
               ave_Sugars +
               intensity +
                empirical+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin)')),  
                data = full, 
              warmup = 1000, iter = 3000, 
              prior = priors_genus_macro_fat,
              cores = ncores, 
              chains = 2, 
              control = list(adapt_delta = 0.99),
              seed = 456, sample_prior = T) 
  })

# save the data
prior_df <- ret_genus_macro_fat %>% 
  imap(~ prior_draws(.x) ) %>% 
  bind_rows(.id = 'genus')
prior_df %>% 
  write_csv('../data/090_genus_macro_fat_model_prior.csv') 

post_df <- ret_genus_macro_fat %>% 
  imap(~ (suppressWarnings(posterior_samples(.x))))  %>% 
  bind_rows(.id = 'genus')  

post_df %>% 
  write_csv('../data/090_genus_macro_fat_model_post.csv')
```

```{r}
## look at the all genera priors
valid_interval_perc <- ret_genus_macro_fat %>% 
  imap(~ prior_draws(.x) %>% 
            mutate(mean_genera =
                    b_ave_fiber * mean_macro$ave_fiber+
                     b_ave_fat * mean_macro$ave_fat+
                     b_ave_Sugars * mean_macro$ave_Sugars+
                     b_intensityreduced ) %>% 
            select(mean_genera) %>% 
            mutate(grp = 'ave_each') %>% 
            rename(prior_res = mean_genera) %>% 
            select(grp, prior_res) %>% 
            count(prior_res > -5 & prior_res < 0) %>% 
            mutate(perc = n/sum(n)*100) %>% 
            select(perc) %>% 
            slice(2) %>% 
            pull(perc) %>% 
            round(1) ) %>% 
  bind_rows(.id = .y) %>% 
  gather('genus','within_interval_perc')
# looks ok to me
```

```{r}
post_df <- read_csv('../data/090_genus_macro_fat_model_post.csv', col_select = c('genus','b_ave_fiber','b_ave_fat','b_ave_Sugars'))
  
post_res_genera <- post_df %>% 
  select(genus, starts_with('b_ave')) %>% 
  gather('item','coeff', names(.)[2]:names(.)[ncol(.)]) %>% 
  group_by(genus, item) %>% 
  summarise(q50 = median(coeff),
            q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975),
            q12.5 = quantile(coeff, probs = 0.125),
            q87.5 = quantile(coeff, probs = 0.875),
            q1.25 = quantile(coeff, probs = 0.0125),
            q98.75 = quantile(coeff, probs = 0.9875),
            q0.5 = quantile(coeff, probs = 0.005),
            q99.5 = quantile(coeff, probs = 0.995)
            ) %>% 
  ungroup() %>% 
  mutate(mark = if_else(q99.5 < 0 | q0.5 > 0, '***', if_else(q98.75 < 0 | q1.25 > 0, '**', if_else(q97.5 < 0 | q2.5 > 0, '*', '')))) %>% 
  mutate(color = if_else(q87.5 < 0, 'steelblue', if_else(q12.5 > 0, 'maroon', 'white'))) %>% 
  mutate(item = str_replace(item, 'b_ave_','')) %>% 
  mutate(item = str_to_title(item)) %>% 
  mutate(item = if_else(item == 'Fiber', 'Fibers', item))

post_df %>% 
  group_by(genus) %>% 
  median_qi(b_ave_Sugars, .width = c(.66, .95)) 
```
```{r}
# trying to order the rows and the columns by similarity in euclidean distances
# make it a numerical matrix and then calculate the distance
dat <- post_res_genera %>% 
  select(genus:q50) %>% 
  spread('item', 'q50') %>% 
  column_to_rownames('genus')

hc <- hclust(dist(dat))
dend <- as.dendrogram(hc)
genus_order <- labels(dend)

# the macro order
dat <- post_res_genera %>% 
  select(genus:q50) %>% 
  spread('genus', 'q50') %>% 
  column_to_rownames('item')

hc <- hclust(dist(dat))
dend <- as.dendrogram(hc)
macro_order <- labels(dend)

post_res_ordered <- post_res_genera %>% 
  mutate(genus = factor(genus, levels = genus_order),
         item = factor(item, levels = macro_order))


```

```{r}
col_key <- post_res_genera %>% 
  ungroup() %>% 
  distinct(color) %>% 
  pull(color)
names(col_key) <- col_key


 
genus_macro_fat_main <- ggplot(post_res_genera, aes(x = genus, y = item)) +
  geom_tile(aes(fill = color,  x = genus, y =  item), alpha = 0.5, color='white', width=0.95, height=0.95) +
  geom_text(aes(label = mark, x = genus,y =  item),
            nudge_y = -0.1, nudge_x = 0,size = 3) +
  scale_fill_manual(values = col_key, labels = c('Less than 75% CI crosses 0', '75% CI < 0 negative','75% CI > 0 positive')) +
  theme_pubr() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle=50, hjust=1, size=11),
        axis.text.y=element_text(size=11),
        axis.title=element_text(size=axis_title_size),
        legend.title = element_blank() ,
        #panel.grid.major = element_line( colour = "gray50"), 
        #panel.grid.minor = element_line( colour = "gray50"),
        legend.position = 'top',
        legend.key = element_rect( colour = "gray50"),
        panel.background=element_rect(colour="black")) 


genus_macro_fat_main %>% write_rds('../data/090_genus_macro_fat_main.rds')

```

```{r}
coeff_bi %>% 
  distinct(item)
```


```{r}
# the factor variables for the genus macro fat
# doesn't need to include the intensity ones since they are the intercepts
post_df <- read_csv('../data/090_genus_macro_fat_model_post.csv', col_select = c('genus', 'b_ENTRUE', 'b_TPNTRUE', 'b_empiricalTRUE'))

post_bi_res <- post_df %>% 
  gather('item','coeff', names(.)[2]:names(.)[ncol(.)]) %>% 
  group_by(genus, item) %>% 
  summarise(q50 = median(coeff),
            q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975),
            q12.5 = quantile(coeff, probs = 0.125),
            q87.5 = quantile(coeff, probs = 0.875),
            q1.25 = quantile(coeff, probs = 0.0125),
            q98.75 = quantile(coeff, probs = 0.9875),
            q0.5 = quantile(coeff, probs = 0.005),
            q99.5 = quantile(coeff, probs = 0.995)
            ) %>% 
  ungroup() %>% 
  mutate(mark = if_else(q99.5 < 0 | q0.5 > 0, '***', if_else(q98.75 < 0 | q1.25 > 0, '**', if_else(q97.5 < 0 | q2.5 > 0, '*', '')))) %>% 
  mutate(color = if_else(q87.5 < 0, 'steelblue', if_else(q12.5 > 0, 'maroon', 'white'))) %>% 
  mutate(item_name = case_when(
    item ==  'b_empiricalTRUE' ~ 'Empirical abx exposure',
    item == 'b_TPNTRUE' ~ 'TPN exposure',
    item ==  'b_ENTRUE' ~ 'EN exposure'
  )) 


genus_macro_fat_factor <- ggplot(post_bi_res, aes(x = genus, y = item_name)) +
  geom_tile(aes(fill = color,  x = genus, y =  item_name), alpha = 0.5, color='white', width=0.95, height=0.95) +
  geom_text(aes(label = mark, x = genus,y =  item_name),
            nudge_y = -0.1, nudge_x = 0,size = 3) +
  scale_fill_manual(values = col_key, labels = c('Less than 75% CI crosses 0','75% CI < 0 negative','75% CI > 0 positive')) +
  theme_pubr() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle=50, hjust=1, size=11),
        axis.text.y=element_text(size=11),
        axis.title=element_text(size=axis_title_size),
        #panel.grid.major = element_blank(), 
        #panel.grid.minor = element_blank(),
        legend.position = 'top',
        legend.key = element_rect( colour = "gray50"),
        panel.background = element_rect(colour="black")) 

genus_macro_fat_factor %>% 
  write_rds('../data/090_genus_macro_fat_factor.rds')

```

