---
title: "Procrustes using the macronutrients counts"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Now update it to procrustes of the total 173 patients

```{r}
library(vegan)
library(tidyverse)
library(ggpubr)
```


```{r}
dtb <- read_csv('../data/152_combined_DTB.csv') %>% 
  select(mrn, fdrt, ends_with('_g')) %>% 
  gather('nutrient','gram', Protein_g:Sugars_g)

stb <- read_csv('../data/152_combined_STB.csv')
```
```{r}
pt_fdrt <- dtb %>% 
  distinct(mrn, fdrt)

stb_loop <- stb %>%  
  select(mrn, sdrt) %>% 
  transmute(mrn = mrn,
            p1d = sdrt-1,
            p2d = sdrt-2, 
            p3d = sdrt-3,
            p4d = sdrt-4,
            p5d = sdrt-5) 
 
check_p5d_diet <-  function(mrn_, p1d_, p2d_, p3d_, p4d_, p5d_){
  num = pt_fdrt %>% 
    filter(mrn == mrn_) %>% 
    filter(fdrt %in% c(p1d_, p2d_ ,p3d_, p4d_, p5d_ )) %>% 
    nrow()
  return(num)
}

check_p5d_diet_df <- pmap(stb_loop, function(mrn, p1d, p2d, p3d, p4d, p5d){
    check_p5d_diet(mrn, p1d, p2d, p3d, p4d, p5d)
  }) %>% 
  set_names(stb %>% pull(sampleid)) %>% 
  bind_rows() %>% 
  gather('sampleid', 'pNd_num') 

p5d_samples <- check_p5d_diet_df %>% 
  filter(pNd_num == 5) %>% 
  pull(sampleid)  
 
stb_loop_sum <- stb %>%  
  filter(sampleid %in% p5d_samples) %>% 
  mutate(p1d = sdrt-1,
            p2d = sdrt-2, 
            p3d = sdrt-3,
            p4d = sdrt-4,
            p5d = sdrt-5) 
```

```{r}
p1d <- apply(stb_loop_sum, 1, function(Row){
  df = dtb %>%   
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['p1d']])) %>% 
        group_by(nutrient) %>% 
        summarise(ave_gram = sum(gram))
}) %>% 
  set_names(stb_loop_sum %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'sampleid', value = 'ave_gram', fill = 0)

p1d <- p1d[, colSums(p1d != 0) > 0]
 
p2d <- apply(stb_loop_sum, 1, function(Row){
  df = dtb %>%  
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['p1d']], Row[['p2d']])) %>% 
        group_by(nutrient) %>% 
        summarise(ave_gram = sum(gram)/2)
}) %>% 
  set_names(stb_loop_sum %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'sampleid', value = 'ave_gram', fill = 0)

p2d <- p2d[, colSums(p2d != 0) > 0]

p3d <- apply(stb_loop_sum, 1, function(Row){
  df = dtb %>%  
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['p1d']], Row[['p2d']], Row[['p3d']])) %>% 
        group_by(nutrient) %>% 
        summarise(ave_gram = sum(gram)/3)
}) %>% 
  set_names(stb_loop_sum %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'sampleid', value = 'ave_gram', fill = 0)

p3d <- p3d[, colSums(p3d != 0) > 0]


p4d <- apply(stb_loop_sum, 1, function(Row){
  df = dtb %>%  
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['p1d']], Row[['p2d']], Row[['p3d']], Row[['p4d']])) %>% 
        group_by(nutrient) %>% 
        summarise(ave_gram = sum(gram)/4)
}) %>% 
  set_names(stb_loop_sum %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'sampleid', value = 'ave_gram', fill = 0) 

p4d <- p4d[, colSums(p4d != 0) > 0]

p5d <- apply(stb_loop_sum, 1, function(Row){
  df = dtb %>%  
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['p1d']], Row[['p2d']], Row[['p3d']], Row[['p4d']], Row[['p5d']])) %>% 
        group_by(nutrient) %>% 
        summarise(ave_gram = sum(gram)/5)
}) %>% 
  set_names(stb_loop_sum %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'sampleid', value = 'ave_gram', fill = 0)  

p5d <- p5d[, colSums(p5d != 0) > 0]
```

```{r}
# output the macronutrients cts table (need to be in a similar format to fit my previously written snakemake rules)
dcts <- list(p1d = p1d,
             p2d = p2d,
             p3d = p3d,
             p4d = p4d,
             p5d = p5d)

for (i in 1:length(dcts)){
  dcts[[i]] %>% 
    write_tsv(str_glue('../data/finalized/paired/pNday/allstool_{names(dcts)[i]}_diet_macro_dehydrated_weight_per_pt.tsv'))
}
```


After running in snakemake:


```{r}
fns_both <- tibble(
  sfolder = list.files('../data/finalized/paired/pNday/', pattern = 'allstool_p.d_scts_stool_relab_species_braycurtis_pcoa$', full.names = T),
  dfolder = list.files('../data/finalized/paired/pNday/', pattern = 'allstool_p.d_diet_macro_dehydrated_weight_per_pt_bc_pcoa$', full.names = T)
) %>% 
  mutate(ID = str_replace(sfolder, '_scts_stool_relab_species_braycurtis_pcoa', ''),
         ID = str_replace(ID, '../data/finalized/paired/pNday//allstool_','')) %>% 
  mutate(sfn = str_glue('{sfolder}/ordination.txt'),
         dfn = str_glue('{dfolder}/ordination.txt'))
```

```{r sum_of_squares}
procrustes_Nday <- map2_dfc(fns_both$dfn, fns_both$sfn, function(dfn, sfn){
  dpcoa = read_tsv(dfn, skip = 9, col_names = F)  %>% 
    filter(! X1 %in% c('Biplot','Site constraints')) %>% 
    column_to_rownames('X1') %>% 
    as.matrix()
  
  spcoa = read_tsv(sfn, skip = 9, col_names = F)  %>% 
    filter(! X1 %in% c('Biplot','Site constraints')) %>% 
    column_to_rownames('X1') %>% 
    as.matrix()
  
  procrustes_res = procrustes(X = dpcoa, Y = spcoa)
  return( procrustes_res$ss)
}) %>% 
  gather(key = 'pNd', value = 'ss') %>% 
  mutate(pNd = fns_both$ID)

# convert it to a score so that the p2d is the highest
procrustes_Nday_score <- procrustes_Nday %>% 
  mutate(score = min(.$ss) - ss)


procrustes_Nday_score %>% 
  write_csv('../data/091_macro_procrustes_Nday_score.csv')
```
