---
title: "Macronutrient supp panel assemble"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(cowplot)
```

```{r}
fat_cal_cor <- read_rds('../data/090_fat_cal_cor.rds')
corr <- read_rds('../data/090_fat_pro_cor.rds')
alpha_main <- read_rds('../data/090_macronutrients_alpha_main.rds')
alpha_factor <- read_rds('../data/090_macronutrients_alpha_factor.rds')

alpha <-  plot_grid(corr, fat_cal_cor,  alpha_main,alpha_factor,
                  nrow = 2, labels = c('A','B', 'C', "D"),  align = 'hv', axis = 'tblr')
alpha

ggsave('../data/093_macronutrients_alpha_093.pdf',
        width = 220,
       height = 220,
       plot = alpha,
         #height = 60,
         units = c("mm"),
         dpi = 400, device = 'pdf')
```
```{r}
genus_main <- read_rds('../data/090_genus_macro_fat_main.rds')
genus_factor <- read_rds('../data/090_genus_macro_fat_factor.rds')

genus <-  plot_grid(  genus_main,genus_factor,
                  nrow = 2, labels = c('E','F'), 
                  rel_heights  = c(1, 1), 
                  align = 'v', axis = 'lb')
genus
```


```{r}
macro <- plot_grid(  alpha, genus,
                  nrow = 2,  
                  rel_heights  = c(1, 1), 
                  align = 'v', axis = 'tblr')
```

```{r}
library(cowplot)
title <- ggdraw() + 
  draw_label(
    "Fig S3",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 7)
  )

combined <- plot_grid(
  title, macro,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)
```


```{r}
ggsave('../data/S3_macronutrients_alpha_and_genus_093.pdf',
        width = 210, height = 297, units = "mm", device = 'pdf', plot = combined)

```

