---
title: "Figure 3 about irep"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(cowplot) 
library(ggpubr)
```

# Scatter two by two  

```{r} 
combined <- read_csv('../data/growth/069_irep_combined_res.csv')
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc') %>% 
  select(fg = fg1_name,shortname )
scatter_alpha <- 0.35
cor_text_size <- 3
axis_text_size <- 11
axis_title_size <- 11
```

# fruits with or without enterococcus

```{r}
# the median of the fruits
median6 <- median(combined$fg_fruit)
median9 <- median(combined$fg_sweets)


tbt_ent <- bind_rows(
  combined %>% 
    filter(str_detect(best_species, 'Enterococcus')) %>% 
    group_by(sampleid) %>% 
    summarise(ave_irep = mean(aveirep)) %>% 
    inner_join(meta) %>% 
    mutate(grp = 'Enterococcus only'),
  combined %>% 
    filter(!str_detect(best_species, 'Enterococcus')) %>% 
    group_by(sampleid) %>% 
    summarise(ave_irep = mean(aveirep)) %>% 
    inner_join(meta) %>% 
    mutate(grp = 'All taxa excl. Enterococcus')
) %>% 
  select(sampleid, ave_irep, grp, fg_sweets, fg_fruit ) %>% 
  gather('fg', 'gram', fg_sweets:fg_fruit) %>% 
  mutate(grp = factor(grp, levels = c('Enterococcus only','All taxa excl. Enterococcus'))) %>% 
  left_join(key) 

tbt_ent_f <- tbt_ent %>% filter(shortname == 'Fruits') %>% 
  mutate(tier = if_else(gram >= median6, 'higher', 'lower'))

t3a_box <- tbt_ent_f  %>%
  ggboxplot(x = 'tier', y = 'ave_irep', alpha = scatter_alpha,
            xlab = 'Fruits intake in previous 2 days (g)',
            ylab = 'Average growth rate\n(iRep estimation)') +
  facet_grid(. ~ grp) +
 theme_classic() +
stat_compare_means(comparisons= list(c('higher', 'lower')),
										label= "p.signif",
										method= 'wilcox.test',
										correct=FALSE) +
  theme(plot.background = element_blank(),
        aspect.ratio = 1,
           axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
        strip.text.x = element_text(size = 8))
```


```{r}
# I want the top row and bottom row to have different x scales.
t3a <- tbt_ent_f  %>%
  ggscatter(x = 'gram', y = 'ave_irep', alpha = scatter_alpha,
            xlab = 'Fruits intake in previous 2 days (g)',
            ylab = 'Average growth rate\n(iRep estimation)',
             add = "reg.line", 
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE,
           cor.coef = TRUE, 
           cor.coeff.args = list(method = "spearman",  label.sep = ",   ", size = cor_text_size)) +
  facet_grid(. ~ grp) +
 theme_classic() +
  theme(plot.background = element_blank(),
        aspect.ratio = 1,
           axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
        strip.text.x = element_text(size = 8))
 
b3a <- tbt_ent %>% filter(shortname == 'Sweets') %>%
  ggscatter(x = 'gram', y = 'ave_irep', alpha = scatter_alpha,
            xlab = 'Sweets intake in previous 2 days (g)',
            ylab = '',
             add = "reg.line", 
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE,
           cor.coef = TRUE, 
           cor.coeff.args = list(method = "spearman",  label.sep =",   ", size = cor_text_size)) +
  facet_grid(. ~ grp) +
 theme_classic() +
  theme( plot.background = element_blank(),
         aspect.ratio = 1,
            axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
        strip.text.x = element_text(size = 8))

```

# kle

```{r} 
tbt_kle <- bind_rows( 
  combined %>% 
    filter(str_detect(best_species, 'Klebsiella')) %>% 
    group_by(sampleid) %>% 
    summarise(ave_irep = mean(aveirep)) %>% 
    inner_join(meta) %>% 
    mutate(grp = 'Klebsiella only'),
  combined %>% 
    filter(!str_detect(best_species, 'Klebsiella')) %>% 
    group_by(sampleid) %>% 
    summarise(ave_irep = mean(aveirep)) %>% 
    inner_join(meta) %>% 
    mutate(grp = 'All taxa excl. Klebsiella')
) %>% 
  select(sampleid, ave_irep, grp, fg_sweets, fg_fruit ) %>% 
  gather('fg', 'gram', fg_sweets:fg_fruit) %>% 
  mutate(grp = factor(grp, levels = c('Klebsiella only','All taxa excl. Klebsiella'))) %>% 
  left_join(key)


# I want the top row and bottom row to have different x scales.
t3b <- tbt_kle %>% filter(shortname == 'Fruits') %>%
  ggscatter(x = 'gram', y = 'ave_irep', alpha = scatter_alpha,
            xlab = 'Fruits intake in previous 2 days (g)',
            ylab = 'Average growth rate\n(iRep estimation)',
             add = "reg.line", 
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE,
           cor.coef = TRUE, 
           cor.coeff.args = list(method = "spearman",  label.sep = ",   ", size = cor_text_size)) +
  facet_grid(. ~ grp) +
  theme_classic() +
  theme(plot.background = element_blank(),
        aspect.ratio = 1,
           axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
        strip.text.x = element_text(size = 8))
 
b3b <- tbt_kle %>% filter(shortname == 'Sweets') %>%
  ggscatter(x = 'gram', y = 'ave_irep', alpha = scatter_alpha,
            xlab = 'Sweets intake in previous 2 days (g)',
            ylab = '',
             add = "reg.line", 
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE,
           cor.coef = TRUE, 
           cor.coeff.args = list(method = "spearman",  label.sep = ",   ", size = cor_text_size )) +
  facet_grid(. ~ grp) +
  theme_classic() +
  theme( 
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    aspect.ratio = 1,
       axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
    strip.text.x = element_text(size = 8))

# assemble the top and bottom of 3b
f3b <- plot_grid(t3b, b3b,
                     byrow = T,
          ncol = 1, axis = 'ltbr', align = 'hv', rel_widths = c(1, 1))

```

```{r}
# decided to just use the enterococcus and fruit & klebsiella with sweets
ent_fruit <- tbt_ent %>% 
  filter(shortname == 'Fruits' & grp == 'Enterococcus only')

# calculate the p value of the slope of the regression line 
res_ent_fruit <- summary(lm(ave_irep ~ gram, data = ent_fruit ))
ent_fruit_p <- round(res_ent_fruit$coefficients[2, 'Pr(>|t|)'], 2)

f3a <- ent_fruit %>% 
   ggscatter(x = 'gram', y = 'ave_irep', alpha = scatter_alpha, shape = 16,
            xlab = 'Fruits intake in\nprevious 2 days (g)',
            ylab = 'Growth rate',
            title = 'Enterococcus',
             add = "reg.line", 
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE) +
  annotate("text", x = 40, y = 1, label = str_glue("paste(italic(p), \" = {ent_fruit_p}\")"), parse = TRUE) +
  theme_classic() +
  theme( 
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    aspect.ratio = 1,
       axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
    strip.text.x = element_text(size = 8))

f3a

ggsave('../figs/paper/094_f3a.pdf',
       width = 60,
       height = 60,
         #height = 60,
         units = c("mm"),
         dpi = 400, plot = f3a)
f3a %>% write_rds('../data/094_f3a.rds')

ent_fruit %>% 
  mutate(pid = str_extract(sampleid, '^\\d\\d\\d\\d')) %>% 
  count(pid)
```


```{r}
# klebsiella with sweets
kle_sweet <- tbt_kle %>% 
  filter(shortname == 'Sweets' & grp == 'Klebsiella only')

# calculate the p value of the slope of the regression line 
res_kle_sweet <- summary(lm(ave_irep ~ gram, data = kle_sweet ))
kle_sweet_p <- round(res_kle_sweet$coefficients[2, 'Pr(>|t|)'], 2)

f3b <- kle_sweet %>% 
   ggscatter(x = 'gram', y = 'ave_irep', alpha = scatter_alpha, shape = 16,
            xlab = 'Sweets intake in\nprevious 2 days (g)',
            ylab = 'Growth rate',
            title = 'Klebsiella',
             add = "reg.line", 
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE) +
  annotate("text", x = 75, y = 1, label = str_glue("paste(italic(p), \" = {kle_sweet_p}\")"), parse = TRUE) +
  theme_classic() +
  theme( 
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    aspect.ratio = 1,
       axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
    strip.text.x = element_text(size = 8))

ggsave('../figs/paper/094_f3b.pdf',
       width = 60,
       height = 60,
         #height = 60,
         units = c("mm"),
         dpi = 400, plot = f3b)

f3b %>% write_rds('../data/094_f3b.rds')


kle_sweet %>% 
  mutate(pid = str_extract(sampleid, '^\\d\\d\\d\\d')) %>% 
  count(pid)
```



