---
title: "klebsiella high irep"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggpubr)
library(tidyverse)
library(cowplot)
```

```{r}
combined <- read_csv('../data/growth/069_irep_combined_res.csv')
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
all_fruit <- read_csv('../data/075_all_daily_fruit.csv')
all_sweet <- read_csv('../data/075_all_daily_sweet.csv')


highest_daily_fruit_intake <- ceiling( max(all_fruit$fruitdaily))
lowest_daily_fruit_intake <- floor( min(all_fruit$fruitdaily))

highest_daily_sweet_intake <- ceiling( max(all_sweet$sweetdaily))
lowest_daily_sweet_intake <- floor( min(all_sweet$sweetdaily))

all_kle_irep <- combined %>% 
  filter(str_detect(best_species, 'Klebsiella'))

irep_highest <- ceiling( max(all_kle_irep$aveirep))
```

```{r abso}
library(vdbR)
connect_database('~/dbConfig.txt')
get_table_from_database('qpcr_16s_ag')
get_table_from_database('antibiotics_antibacterial_multicenter_ag')
qpcr <- qpcr_16s_ag %>% 
  filter(!str_detect(sample_id_unique, 'heat|ethanol')) %>% 
  filter(!is.na(copies_16s_per_g))


target <- combined %>% 
  filter(str_detect(best_species, 'Klebsiella')) %>% 
  arrange(desc(aveirep)) %>% 
  slice(1) %>% 
  select(mrn) %>% 
  pull(mrn)

# all of the stool samples we have of this patient
get_table_from_database('samples_castori_ag')
get_table_from_database('asv_annotation_blast_ag')
sam <- samples_castori_ag %>% 
  filter(mrn %in% target) %>% 
  distinct(sampleid) %>% 
  pull(sampleid)

samps <- samples_castori_ag %>% 
  filter(mrn %in% target) %>% 
  distinct(sampleid, mrn)

# get the  relab of these samples
cts <- get_counts_subset(sam)
ptb <- read_csv('../data/cleaned_patients/diet_patients_97.csv')
cts_ <- cts %>% 
  left_join(asv_annotation_blast_ag %>% 
              select(asv_key, genus)) %>% 
  group_by(sampleid, genus) %>% 
  summarise(relab = sum(count_relative)) %>% 
  filter(genus == 'Klebsiella')  %>% 
  inner_join(qpcr %>% 
               select(sampleid = sample_id, copies_16s_per_g)) %>% 
  mutate(kle_copy = copies_16s_per_g*relab) %>% 
  inner_join(samples_castori_ag %>% 
               select(sampleid, datecollection)) %>% 
  inner_join(samps) %>% 
  inner_join(ptb %>% 
               select(mrn, hct)) %>% 
  mutate(sdrt = datecollection - hct) 

```
```{r irep}
growth <- combined %>% 
  filter(mrn == target & str_detect(best_species, 'Klebsiella'))
```

```{r food}
# fruit intake
lowerday <- min(growth$sdrt)
highday <- max(growth$sdrt)

fruit <- dtb %>%  
  filter(mrn == target & fdrt %in% lowerday:highday) %>% 
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^6')) %>% 
  group_by(fdrt) %>% 
  summarise(fruitsum = sum(dehydrated_weight)) %>% 
  full_join(tibble(
    fdrt = seq(lowerday, highday, 1)
  )) %>% 
  mutate(fruitsum = if_else(is.na(fruitsum), 0, fruitsum))


sweets <- dtb %>%  
  filter(mrn == target & fdrt %in% lowerday:highday) %>% 
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^9')) %>% 
  group_by(fdrt) %>% 
  summarise(sweetsum = sum(dehydrated_weight)) %>% 
  full_join(tibble(
    fdrt = seq(lowerday, highday, 1)
  )) %>% 
  mutate(sweetsum = if_else(is.na(sweetsum), 0, sweetsum))

```
```{r abx}
# abx
abx <- antibiotics_antibacterial_multicenter_ag %>% 
  filter(patient_id == as.character(target) ) %>% 
  rename(mrn = patient_id) %>% 
  mutate(mrn = as.numeric(mrn)) %>% 
  left_join(ptb %>% 
              select(mrn, hct)) %>% 
  mutate(startdrt = start - hct,
         stopdrt = stop - hct) %>% 
  # only select the days relevant
  filter(startdrt %in% -2:4) %>% 
  mutate(drugfull = str_glue('{drug_name_clean} ({route_simple})')) %>% 
  arrange(startdrt, stopdrt) %>% 
  mutate(yval = seq(1, nrow(.)))
```
```{r plotting}
xmin <- lowerday - 1 
xmax <- highday + 1  
 
# plotting
copies <- cts_ %>% 
  ggplot(aes(x = sdrt, y = kle_copy )) +
  geom_point() +
  geom_line(aes(x = sdrt, y = kle_copy), linetype = 'solid', size = 0.5, col = 'black') +
  xlim(xmin, xmax) +
  labs(x = 'Day relative to transplant',
       y = 'Klebsiella copy\nnumbers',
       title = 'Copy numbers') +
  theme_classic() +
  theme(aspect.ratio=1,
        plot.margin = margin(l=-0.8,unit="cm"),
        panel.grid.major.x = element_line(colour = "grey85"))


fruit_time <- fruit %>% 
  ggplot(aes(x = fdrt, y = fruitsum )) +
  geom_point() +
  geom_line(aes(x = fdrt, y = fruitsum), linetype = 'solid', size = 0.5, col = 'black') +
  xlim(xmin, xmax) +
  labs(x = '',
       y = 'Fruit intake',
       title = 'Fruit intake') +
  theme_classic() + 
  ylim(lowest_daily_fruit_intake, highest_daily_fruit_intake)+
  geom_hline(yintercept = quantile(x = all_fruit$fruitdaily, 0.25), linetype = 'dashed') +
  geom_hline(yintercept = quantile(x = all_fruit$fruitdaily, 0.5), linetype = 'dashed') + 
  geom_hline(yintercept = quantile(x = all_fruit$fruitdaily, 0.75), linetype = 'dashed') +
  theme(aspect.ratio=1,  
        plot.margin = margin(l=-0.8,unit="cm"),
        #axis.text.x=element_blank(),
        #axis.ticks.x=element_blank(),
        panel.grid.major.x = element_line(colour = "grey85"))

  
sweets_time <- sweets %>%    
  ggplot(aes(x = fdrt, y = sweetsum )) +
  geom_point() +
  geom_line(aes(x = fdrt, y = sweetsum), linetype = 'solid', size = 0.5, col = 'black') +
  xlim(xmin, xmax) +
  labs(x = '',
       y = 'Sweets intake',
       title = 'Sweets intake') +
  theme_classic() + 
  ylim(lowest_daily_sweet_intake, highest_daily_sweet_intake)+
  geom_hline(yintercept = quantile(x = all_sweet$sweetdaily, 0.25), linetype = 'dashed') +
  geom_hline(yintercept = quantile(x = all_sweet$sweetdaily, 0.5), linetype = 'dashed') + 
  geom_hline(yintercept = quantile(x = all_sweet$sweetdaily, 0.75), linetype = 'dashed') +
  theme(aspect.ratio=1,
        plot.margin = margin(l=-0.8,unit="cm"),
        #axis.text.x=element_blank(),
        #axis.ticks.x=element_blank(),
        panel.grid.major.x = element_line(colour = "grey85"))

abx_time <- ggplot(abx, aes(x = startdrt, y = yval, xend = stopdrt, yend = yval, label = drugfull )) +
  geom_segment(
     size = 0.5, lineend = 'round',
     arrow = arrow(length = unit(0.05, "inches"))
  ) +
  geom_text(hjust = 'outside', nudge_y = -0.1, nudge_x = 5, size = 2) +
   xlim(xmin, xmax) +
  labs(x = '',
       y = '',
       title = 'Antibiotics') + 
  theme_classic() +
  theme(aspect.ratio=1,
        #axis.text.x=element_blank(),
        #axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        panel.grid.major.x = element_line(color = "grey85"))



irep = growth %>% 
  ggplot(aes(x = sdrt, y = aveirep )) +
  geom_point() +
  labs(title = str_glue('{}')) +
  geom_hline(yintercept = quantile(x = all_kle_irep$aveirep, 0.25), linetype = 'dashed') +
  geom_hline(yintercept = quantile(x = all_kle_irep$aveirep, 0.5), linetype = 'dashed') +
  geom_hline(yintercept = quantile(x = all_kle_irep$aveirep, 0.75), linetype = 'dashed') +
  xlim(xmin, xmax) +
  ylim(1, irep_highest) +
  labs(x = '', 
       y = 'Replication rate',
       title = 'Klebsiella')+
  theme_classic()+
  theme(aspect.ratio=1,
        #axis.text.x=element_blank(),
        #axis.ticks.x=element_blank(),
        panel.grid.major.x = element_line(color = "grey85"))
```


```{r population_box}
# the boxes of the populations 
all_kle <- all_kle_irep %>% 
  ggviolin(y = 'aveirep', add = 'boxplot') +
  theme_classic() +
   ylim(1, irep_highest) +
  theme(aspect.ratio=6,
       axis.ticks.x=element_blank(),
       axis.title.x = element_blank(),
       axis.ticks.y=element_blank(),
       axis.title.y = element_blank(),
       axis.text.y = element_blank(),
       line = element_blank(),
       axis.text.x = element_blank() ) 


violin9 <- all_sweet %>% 
  ggviolin(y = 'sweetdaily', add = 'boxplot') +
  theme_classic() +
   ylim(lowest_daily_sweet_intake, highest_daily_sweet_intake)+
  theme(aspect.ratio=6,
       axis.ticks.x=element_blank(),
       axis.title.x = element_blank(),
       axis.ticks.y=element_blank(),
       axis.title.y = element_blank(),
       axis.text.y = element_blank(),
       line = element_blank(),
       axis.text.x = element_blank() ) 

violin6 <- all_fruit %>% 
  ggviolin(y = 'fruitdaily', add = 'boxplot') +
  theme_classic() +
   ylim(lowest_daily_fruit_intake, highest_daily_fruit_intake)+
  theme(aspect.ratio=6,
       axis.ticks.x=element_blank(),
       axis.title.x = element_blank(),
       axis.ticks.y=element_blank(),
       axis.title.y = element_blank(),
       axis.text.y = element_blank(),
       line = element_blank(),
       axis.text.x = element_blank() ) 
```


```{r population_box}
pkle_ver <- plot_grid(abx_time, NA,
                     sweets_time, violin9,
                     fruit_time, violin6,
                     irep, all_kle,
                     copies,NA,
                     byrow = T,
          ncol = 2, axis = 'ltbr', align = 'hv', rel_widths = c(1, 0.5))
pkle_ver

ggsave('../figs/paper/095_irep_kle_vertical.pdf', width = 130,
      height = 250, units = 'mm', dpi = 400, plot = pkle_ver)
```
```{r scatter}

kle_df <- combined %>% 
  filter(str_detect(best_species, 'Klebsiella')) %>% 
  group_by(sampleid) %>% 
  summarise(ave_irep = mean(aveirep)) %>% 
  inner_join(meta)

non_kle_df <- combined %>% 
  filter(!str_detect(best_species, 'Klebsiella')) %>% 
  group_by(sampleid) %>% 
  summarise(ave_irep = mean(aveirep)) %>% 
  inner_join(meta)

ylowerlim <- min(min(non_kle_df$ave_irep), min(kle_df$ave_irep))
yupperlim <-  max(max(non_kle_df$ave_irep), max(kle_df$ave_irep)) 
  
fruit_kle <- kle_df %>% 
  ggscatter(x = 'fg_fruit', y = 'ave_irep', title = 'Klebsiella only',alpha = 0.7, 
            ylab = 'Average growth rate\n(iRep estimation)',
            xlab = 'Fruit intake in previous 2 days (g)', 
          add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n",  size = 4))   +
  theme_classic() +
  ylim(ylowerlim, yupperlim) +
  theme(aspect.ratio = 1)


fruit_all_other <- non_kle_df %>% 
  ggscatter(x = 'fg_fruit', y = 'ave_irep', title = 'All taxa excluding Klebsiella',
            alpha = 0.7, 
             ylab = 'Average growth rate\n(iRep estimation)',
            xlab = 'Fruit intake in previous 2 days (g)',
          add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n", size = 4))   +
  theme_classic() +
  ylim(ylowerlim, yupperlim) +
  theme(aspect.ratio = 1)
```

```{r}
sweets_kle <- kle_df %>% 
  ggscatter(x = 'fg_sweets', y = 'ave_irep', title = 'Klebsiella only',alpha = 0.7, 
            ylab = 'Average growth rate\n(iRep estimation)',
            xlab = 'Sweets intake in previous 2 days (g)', 
          add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n",  size = 4))   +
  theme_classic() +
  ylim(ylowerlim, yupperlim) +
  theme(aspect.ratio = 1)
```

```{r}
sweets_all_other <- non_kle_df %>% 
  ggscatter(x = 'fg_sweets', y = 'ave_irep', title = 'All taxa excluding Klebsiella',
            alpha = 0.7, 
             ylab = 'Average growth rate\n(iRep estimation)',
            xlab = 'Sweets intake in previous 2 days (g)',
          add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n", size = 4))   +
  theme_classic() +
  ylim(ylowerlim, yupperlim) +
  theme(aspect.ratio = 1)
```

```{r}
kle_all <- plot_grid(sweets_kle, sweets_all_other,
                    fruit_kle, fruit_all_other,
                     byrow = T,
          ncol = 2, axis = 'ltbr', align = 'hv')
kle_all

ggsave('../figs/paper/095_irep_kle_all.pdf', width = 180,
      height = 200, units = 'mm', dpi = 400, plot = kle_all)
```

