---
title: "Streptococcus growth rate"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Streptococcus not growing much def not to the domination



```{r}
library(tidyverse)
library(cowplot)
library(ggpubr)
```

```{r} 
combined <- read_csv('../data/growth/069_irep_combined_res.csv')
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc') %>% 
  select(fg = fg1_name,shortname )
```

# fruits with or without Streptococcus 

```{r}
tbt_strep <- bind_rows(
  combined %>% 
    filter(str_detect(best_species, 'Streptococcus')) %>% 
    group_by(sampleid) %>% 
    summarise(ave_irep = mean(aveirep)) %>% 
    inner_join(meta) %>% 
    mutate(grp = 'Streptococcus only'),
  combined %>% 
    filter(!str_detect(best_species, 'Streptococcus')) %>% 
    group_by(sampleid) %>% 
    summarise(ave_irep = mean(aveirep)) %>% 
    inner_join(meta) %>% 
    mutate(grp = 'All taxa excluding Streptococcus')
) %>% 
  select(sampleid, ave_irep, grp, fg_sweets, fg_fruit ) %>% 
  gather('fg', 'gram', fg_sweets:fg_fruit) %>% 
  mutate(grp = factor(grp, levels = c('Streptococcus only','All taxa excluding Streptococcus'))) %>% 
  left_join(key)

strep <- tbt_strep %>% 
  ggscatter(x = 'gram', y = 'ave_irep',
            xlab = 'Intake in previous 2 days (g)',
            ylab = 'Average growth rate\n(iRep estimation)',
             add = "reg.line", 
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE,
           cor.coef = TRUE, 
           cor.coeff.args = list(method = "spearman",  label.sep = "\n", size = 4, label.x = 190)) +
  facet_grid(shortname ~ grp) +
  theme_bw()  
```