---
title: "Figure S10 fiber versus sugar"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(cowplot)
dtb1 <- read_csv('../data/149_finalized_dtb1.csv')
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')
axis_text_size <- 10
axis_title_size <- 10
```

```{r}
# the top 10 most consumed in fruits , sweets and veggie item 
# total number of meals 
n_meal <- dtb %>% 
  count(mrn, fdrt, Meal) %>% 
  nrow()
  
top3grp <- dtb %>% 
  mutate(fgrp1 = str_sub(Food_code, 1,1)) %>% 
  filter(fgrp1 %in% c('9','6','7')) %>% 
  group_by(Food_code, description, fgrp1) %>% 
  summarise(total_per_code = sum(dehydrated_weight)) %>% 
  group_by(fgrp1) %>% 
  arrange(desc(total_per_code), .by_group = T)  %>% 
  top_n(10) %>% 
  left_join(key) %>% 
  ungroup() %>% 
  mutate(gram_per_meal = total_per_code/n_meal) %>% 
  mutate(fg1_full_name = case_when(
    fgrp1 == '6' ~ 'Fruits',
    fgrp1 == '7' ~ 'Vegetables',
    fgrp1 == '9' ~ 'Sugars, Sweets & Beverages'
  )) %>% 
  mutate(fg1_full_name = factor(fg1_full_name, levels = c('Fruits','Sugars, Sweets & Beverages', 'Vegetables'))) %>% 
  group_by(fg1_full_name) %>% 
  arrange(gram_per_meal, .by_group = T)

# manually add the x text color

x_txt_col <- c(rep('#7D3C98', 10), rep('#db2589', 10), rep('#229954', 10))


# or I just calculate the sugar in percent in those food code
top3grp_sugar <- dtb %>% 
  mutate(fgrp1 = str_sub(Food_code, 1,1)) %>% 
  filter(fgrp1 %in% c('9','6','7')) %>% 
  group_by(Food_code, description, fgrp1) %>% 
  summarise(total_sugar_per_code = sum(Sugars_g)) %>% 
  ungroup() %>% 
  mutate(gram_sugar_per_meal = total_sugar_per_code/n_meal) %>% 
  inner_join(top3grp) %>% 
  mutate(sugar_perc_per_meal = gram_sugar_per_meal/gram_per_meal*100) %>% 
  mutate(description = factor(description, levels = top3grp$description))


```
```{r}
# go back to the dtb to see the sugar data of those 
top50 <- top3grp_sugar <- dtb %>% 
  mutate(fgrp1 = str_sub(Food_code, 1,1)) %>% 
  filter(fgrp1 %in% c('9','6','7')) %>% 
  group_by(Food_code, description, fgrp1) %>% 
  summarise(total_sugar_per_code = sum(Sugars_g)) %>% 
  ungroup() %>% 
  arrange(desc(total_sugar_per_code)) %>% 
  filter(fgrp1 %in% c('6')) %>% 
  slice_head(n = 50)

see <- dtb %>% 
  distinct(Food_NSC, Food_code, description, Por_eaten, Unit, .keep_all = T) %>% 
  select(Food_NSC:description) %>% 
  distinct(Food_NSC, Food_code, .keep_all = T) %>% 
  filter(Food_code %in% top50$Food_code) %>% 
  filter(Sugars_g > 0 & str_detect(description, 'raw')) 

see %>% write_csv('../data/099_raw_fruits_with_sugars.csv')
```


```{r}
# how about I plot it in bar plot and so I can have the sugar in gram per meal in the same bar to show the perc
bars <- top3grp_sugar %>% 
  select(description, fg1_full_name,gram_sugar_per_meal, gram_per_meal ) %>% 
  gather('grp','gram',gram_sugar_per_meal: gram_per_meal) %>% 
  mutate(grp = if_else(grp == 'gram_sugar_per_meal', 'Sugar fraction', 'Total') ) %>% 
  mutate(grp = factor(grp, levels = c('Sugar fraction','Total'))) 
  

ggbarplot(bars, "description", "gram",xlab = '',ylab = 'Per meal average consumption (gram)',
  fill = "grp", color = "grp", palette = c("#FB9A99" ,"gray"),
  width = 0.7, 
  position = position_dodge(0.8)) +
  coord_flip() +
  theme(legend.position = 'bottom',
        axis.text.y = element_text(size=11, colour = x_txt_col),
        legend.title= element_blank())

 
ggsave('../figs/paper/S10_top10_eaten_foods_of_3__and_sugar_099.pdf', width = 8.3, height = 7)
ggsave('../figs/paper/S10_top10_eaten_foods_of_3__and_sugar_099.jpg', width = 8.3, height = 7)
```

```{r}
# the Soft drink, cola thing
# fix <- dtb %>% 
#   filter(description == 'Soft drink, cola') %>% 
#   filter(Sugars_g > dehydrated_weight)
# 
# fix %>% 
#   write_csv('../data/099_soft_drink_cola.csv')
```


# what about adding egg into the picture

```{r}
top4grp <- dtb %>% 
  mutate(fgrp1 = str_sub(Food_code, 1,1)) %>% 
  filter(fgrp1 %in% c('9','6','7','3')) %>% 
  group_by(Food_code, description, fgrp1) %>% 
  summarise(total_per_code = sum(dehydrated_weight)) %>% 
  group_by(fgrp1) %>% 
  arrange(desc(total_per_code), .by_group = T)  %>% 
  top_n(10) %>% 
  left_join(key) %>% 
  ungroup() %>% 
  mutate(gram_per_meal = total_per_code/n_meal) %>% 
  mutate(fg1_full_name = case_when(
    fgrp1 == '6' ~ 'Fruits',
    fgrp1 == '7' ~ 'Vegetables',
    fgrp1 == '9' ~ 'Sugars, Sweets & Beverages',
    fgrp1 == '3' ~ 'Eggs'
  )) %>% 
  mutate(fg1_full_name = factor(fg1_full_name, levels = c('Fruits','Sugars, Sweets & Beverages', 'Vegetables', 'Eggs'))) %>% 
  group_by(fg1_full_name) %>% 
  arrange(gram_per_meal, .by_group = T)

top4grp_sugar <- dtb %>% 
  mutate(fgrp1 = str_sub(Food_code, 1,1)) %>% 
  filter(fgrp1 %in% c('9','6','7','3')) %>% 
  group_by(Food_code, description, fgrp1) %>% 
  summarise(total_sugar_per_code = sum(Sugars_g)) %>% 
  ungroup() %>% 
  mutate(gram_sugar_per_meal = total_sugar_per_code/n_meal) %>% 
  inner_join(top4grp) %>% 
  mutate(sugar_perc_per_meal = gram_sugar_per_meal/gram_per_meal*100) %>% 
  mutate(description = factor(description, levels = top4grp$description))


bars <- top4grp_sugar %>% 
  select(description, fg1_full_name,gram_sugar_per_meal, gram_per_meal ) %>% 
  gather('grp','gram',gram_sugar_per_meal: gram_per_meal) %>% 
  mutate(grp = if_else(grp == 'gram_sugar_per_meal', 'Sugar fraction', 'Total') ) %>% 
  mutate(grp = factor(grp, levels = c('Sugar fraction','Total'))) 
  

x_txt_col <- c(rep('#7D3C98', 10), rep('#db2589', 10), rep('#229954', 10), rep('#F1C40F', 10))

ggbarplot(bars, "description", "gram",xlab = '',ylab = 'Per meal average consumption (gram)',
  fill = "grp", color = "grp", palette = c("#FB9A99" ,"gray"),
  width = 0.7, 
  position = position_dodge(0.8)) +
  coord_flip() +
  theme(legend.position = 'bottom',
        axis.text.y = element_text(size=11, colour = x_txt_col),
        legend.title= element_blank())

ggsave('../figs/paper/099_top10_eaten_foods_of_4__and_sugar_099.jpg', width = 8.3, height = 9)
```

# check all of the top eating foods of each group in the first batch 

```{r}
n_meal <- dtb1 %>% 
  count(mrn, fdrt, Meal) %>% 
  nrow()

top_grp <- dtb1 %>% 
  mutate(fgrp1 = str_sub(Food_code, 1,1)) %>% 
  #filter(fgrp1 %in% c('9','6','7','3')) %>% 
  group_by(Food_code, description, fgrp1) %>% 
  summarise(total_per_code = sum(dehydrated_weight)) %>% 
  group_by(fgrp1) %>% 
  arrange(desc(total_per_code), .by_group = T)  %>% 
  top_n(3) %>% 
  left_join(key) %>% 
  ungroup() %>% 
  mutate(gram_per_meal = total_per_code/n_meal)%>% 
  mutate(description = str_sub(description, end = 50))

ggbarplot(top_grp, "description", "gram_per_meal",xlab = '',ylab = 'Per meal average consumption (gram)',
  fill = "shortname", color = "shortname", 
  width = 0.7, 
  position = position_dodge(0.8)) +
  ylim(0, 5.5) +
  coord_flip() +
  theme(legend.position = 'bottom',
        axis.text.y = element_text(size=11),
        legend.title= element_blank())

ggsave('../data/099_top_food_each_group_batch1.png', width = 8, height = 6)
```



