---
title: "check on hospital day"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
faith <- read_tsv('../data/cleaned_diet_data/FINAL_97_faith_pd/alpha-diversity.tsv') %>% 
  separate(...1, into = c('mrn', 'fdrt'), sep = 'd', convert = T)  %>% 
  mutate(mrn = as.numeric(str_replace(mrn, 'P','')))

# find the earliest day to each patient
# and make that day the day 0
early <- dtb %>% 
  group_by(mrn) %>% 
  arrange(fdrt, .by_group = T) %>% 
  slice(1) %>% 
  mutate(dayoffset = 0 - fdrt) %>% 
  select(mrn, dayoffset) %>% 
  arrange(mrn)

each <- dtb %>% 
  arrange(mrn) %>% 
  split(.$mrn) 

os <- early %>% 
  split(.$mrn) 


res <- map2_dfr(each, os, .f = function(.x, .y){
  mutate(.data = .x, fdrh = fdrt + .y$dayoffset)
})

```


```{r}
# the macronutrients scatter plot
m_all <- res %>%  
  select(mrn, fdrh,Protein_g:Sodium_g ) %>% 
  gather('grp','gram', Protein_g:Sodium_g) %>% 
  mutate(grp = str_replace(grp, '_g$','')) %>% 
  group_by(mrn, fdrh, grp) %>% 
  summarise(eachsum = sum(gram)) 

# nutrition data 
macro_list_adj <- m_all %>% 
  split(.$grp) %>% 
  imap(function(.x, .y) {
      ggscatter(data = .x ,x = 'fdrh', y = 'eachsum', alpha = 0.02, size = point_size, 
            xlab = 'Day relative to hospitalization',
            ylab = 'Grams',
            title = str_glue('{.y}'),
            add = "loess", conf.int = TRUE, 
            add.params = list(color = diet_line_color, fill = "hotpink", size = 1))  +
  theme(axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        aspect.ratio=1)
  })

macro <- plot_grid(macro_list_adj[[1]],macro_list_adj[[2]],macro_list_adj[[3]],macro_list_adj[[4]],macro_list_adj[[5]],macro_list_adj[[6]],
          nrow = 2, 
          align = 'hv',
          #rel_widths =  c(1,1),
          #rel_heights = c(1,1),
          labels = c('A','B','C', 'D','E','F'),
          axis = 'tblr') 

ggsave('../figs/paper/100_macro_fig1_supp_adj.pdf',
       width = 160,
       height = 120,
         #height = 60,
         units = c("mm"),
         dpi = 400, device = 'pdf')
```

```{r}
# the previous two days average faith pd
# the previous two days average for each stool sample

stb_pair <- meta %>%
  select(mrn, sdrt) %>%
  transmute(mrn = mrn,
            p1d = sdrt-1,
            p2d = sdrt-2)

mean_p2d_faith <-  function(mrn_, p1d_, p2d_){
  df = faith %>%
    filter(mrn == mrn_) %>%
    filter(fdrt %in% c(p1d_, p2d_  )) %>%
    group_by(mrn) %>%
    summarise(ave_faith = sum(faith_pd)/2)
  return(df)
}

mean_p2d_faith_df <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_faith(mrn, p1d, p2d)
  }) %>%
  set_names(meta %>% pull(sampleid)) %>%
  bind_rows(.id = 'sampleid')

combined <- mean_p2d_faith_df %>% 
  full_join(full )
```
```{r}
combined %>% 
  ggscatter( x = 'simpson_reciprocal', y = 'ave_faith', alpha = 0.2, 
             add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n" )) +
  scale_y_log10()
```
```{r}
combined %>% 
  select(starts_with('fg_'),  simpson_reciprocal) %>% 
  gather('grp', 'gram', fg_egg:fg_veggie) %>% 
  ggscatter( x = 'simpson_reciprocal', y = 'gram', facet.by = 'grp', alpha = 0.2, 
              add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n" ))
```

```{r}
combined %>% 
  select(starts_with('ave_')) %>% 
  select(-ave_cal) %>% 
  gather('grp', 'gram', ave_fiber:ave_carb) %>% 
  ggscatter( x = 'ave_faith', y = 'gram', facet.by = 'grp', alpha = 0.2, 
              add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n" ))
```

```{r}
# fiber in goods 

```

