---
title: "For the irep whole overview"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(cowplot)
```

```{r}
should <- read_csv('../data/135_selected_samples_for_irep_analysis.csv')
combined <- read_csv('../data/114_combined_irep_915.csv')
meta <- read_csv('../data/153_combined_META.csv')
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc') %>% 
  select(fg = fg1_name,shortname )
scatter_alpha <- 0.35
cor_text_size <- 3
axis_text_size <- 11
axis_title_size <- 11
```

```{r}
# summarizing ireps of all major genera
spp <- combined %>% 
  filter(Sample %in% should$sampleid) %>% 
  count(best_species, best_level) %>% 
  filter(!best_level %in% c('superkingdom', 'family')) %>% 
  mutate(cleaned_genus = str_replace(best_species, '^\\[',''),
         cleaned_genus = str_replace(cleaned_genus, '\\]','')) %>% 
  mutate(cleaned_genus = str_replace(cleaned_genus, ' .+$',''))
c_genus <- spp %>% 
  count(cleaned_genus)

genus_combined <- combined %>% 
  inner_join(spp %>% 
              select(best_species, cleaned_genus)) %>% 
  add_count(cleaned_genus) %>% 
  # remove the genus as singletons
  filter(n > 1) %>% 
  mutate(xlabel = str_glue('{cleaned_genus} ({n})')) %>% 
  mutate(xlabel = fct_reorder(xlabel, iRep, .fun=median, .desc = T))
```


```{r}
# plot in a horizontal way
title <- ggdraw() + 
  draw_label(
    "Fig S10",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 7)
  )

plot <- genus_combined %>% 
  ungroup() %>% 
  ggboxplot(x = 'xlabel', y = 'iRep', orientation = "horizontal",add = 'jitter',xlab = 'Genus',
            add.params = list(alpha = 0.4, size = 2, shape = 16))


combined <- plot_grid(
  title, plot,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)
 
ggsave('../data/S10_genus_irep_boxplot_106.pdf',  width = 210, height = 297, units = "mm", device = 'pdf', plot = combined)

```

