---
title: "068 main model without intercepts"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(brms)   
library(ggpubr)
library(tidybayes)
library(cowplot)
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
theme_set(theme_tidybayes() + panel_border())
ncores <- parallel::detectCores()
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')
axis_text_size <- 10
axis_title_size <- 10


meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = factor(mrn)) %>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100) 


ave_fg <- meta %>% 
  select(starts_with('fg')) %>% 
  summarise_all(funs(mean)) %>% 
  gather
mean_fg <-  meta %>% 
  select(starts_with('fg')) %>% 
  summarise_all(funs(mean))
max_fg <- meta %>% 
  select(starts_with('fg')) %>% 
  summarise_all(funs(max)) 
```


# model

```{r}
# how to get rid of the intercept 
model_formular_no_intercept <- log(simpson_reciprocal) ~ 0 + 
                fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               intensity +
               empirical+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin)
get_prior( model_formular_no_intercept,  
              data = meta)

priors <- c(# for the food group variables
            prior(normal(0, 1), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie"),
            # for the TPN 
            prior(normal(0, 0.1), class = 'b', coef = "TPNTRUE"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "ENTRUE"),
            # for the empirical 
            prior(normal(0, 0.5), class = 'b', coef = "empiricalTRUE"),
            # for the intensity 
            prior(normal(2, 0.1), class = 'b', coef = "intensityablative"),
            prior(normal(2, 0.1), class = 'b', coef = "intensitynonablative"),
            prior(normal(2, 0.1), class = 'b', coef = "intensityreduced"))


model_div <- brm( model_formular_no_intercept,  
              data = meta, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
              seed = 123, sample_prior = T) 


post_res <- suppressWarnings(posterior_samples(model_div)) 
post_res %>%  write_csv('../data/107_div_model_fg_post_without_intercept.csv')
```

```{r}
prior_div <- prior_draws(model_div) 

ave_each_fg_prior <- prior_div %>% 
  mutate(mean_fg_prior_div = 
           b_fg_fruit*mean_fg$fg_fruit +
           b_fg_meat*mean_fg$fg_meat + 
           b_fg_milk*mean_fg$fg_milk + 
           b_fg_oils*mean_fg$fg_oils + 
           b_fg_egg*mean_fg$fg_egg + 
           b_fg_grain*mean_fg$fg_grain +
           b_fg_sweets*mean_fg$fg_sweets +
           b_fg_legume*mean_fg$fg_legume +
           b_fg_veggie*mean_fg$fg_veggie +
           b_intensityreduced ) %>% 
  select(mean_fg_prior_div) %>% 
  mutate(grp = 'ave_each')  %>% 
  mutate(within_range = if_else(mean_fg_prior_div >= min(log(meta$simpson_reciprocal)) &  mean_fg_prior_div <= max(log(meta$simpson_reciprocal)), T, F))

ave_each_fg_prior %>% 
  count(within_range) %>% 
  mutate(perc = n/(sum(n))*100)
```

# post coeff plot

```{r}
post_samples  <- read_csv('../data/107_div_model_fg_post_without_intercept.csv')

post_coeff <- post_samples %>% 
  select(starts_with('b_fg')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item = str_replace(item, 'b_fg_','')) %>% 
   mutate(fgrp1 = case_when(
    item ==  'milk' ~ '1',
    item == 'meat' ~ '2',
    item ==  'egg' ~ '3',
    item ==  'legume' ~ '4',
    item == 'grain' ~ '5',
    item == 'fruit' ~ '6',
    item == 'veggie' ~ '7',
    item ==  'oils' ~ '8', 
    item ==  'sweets' ~ '9'
  ))  %>% 
  left_join(key %>% select(fgrp1, color, shortname))  %>% 
  mutate(shortname = fct_reorder(shortname, coeff, .fun=median, .desc = F)) 

cross0 <- post_coeff %>%
  group_by(item) %>% 
  summarise(q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975)) %>% 
  mutate(Cross = if_else(q2.5 > 0 | q97.5 < 0, F, T))

div_post <- post_coeff %>% 
  left_join(cross0) %>% 
  ggplot(aes(x = coeff, y = shortname, col = Cross)) +
  stat_pointinterval(.width = c(.66, .95)) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  labs(x = 'ln(diversity) change per 100g of food',
       y = '', 
       title = 'Diversity') +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_manual(values = c("#EC0000", "gray40")) +
  theme(axis.text=element_text(size=8),
        axis.title=element_text(size=8),
        aspect.ratio=1)
```

```{r}
coeff_bi <- post_samples %>% 
  select(starts_with('b_')) %>% 
  select(!starts_with('b_fg')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item_name = case_when(
    item ==  'b_intensitynonablative' ~ 'Intensity: nonablative',
    item == 'b_intensityablative' ~ 'Intensity: ablative',
    item ==  'b_intensityreduced' ~ 'Intensity: reduced',
    item ==  'b_empiricalTRUE' ~ 'Empirical abx exposure',
    item == 'b_TPNTRUE' ~ 'TPN exposure',
    item ==  'b_ENTRUE' ~ 'EN exposure'
  )) %>% 
  mutate(item_name = factor(item_name, levels = c('Intensity: nonablative', 'Intensity: reduced',
                                                  'Intensity: ablative', 'TPN exposure','EN exposure',
                                                  'Empirical abx exposure')))  %>% 
  mutate(grp = if_else(str_detect(item_name, 'Intensity'), 'Patient level', 'Sample level'))
```


```{r}
diversity_factor <- coeff_bi %>% 
  ggplot(aes(x = coeff, y = item_name)) +
  stat_pointinterval(.width = c(.66, .95)) +
  #scale_color_manual(values = c('#EC0000','#00468B')) +
  #geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  facet_grid(.~ grp , scales = 'free') +
  labs(x = 'Coefficients',
       y = 'Factor variables',
       title = 'Diversity') +
  theme_classic() +
  theme(legend.position = 'none',
        aspect.ratio=1)


ggsave('../data/107_factor_coeff_model_without_intercept.jpg', device = 'jpg')
```

