---
title: "Figure 3 two patients timecouse"
author: "Angel"
date: '2022-06-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
axis_text_size <- 11
axis_title_size <- 11
plot_ratio <-1.5/2
shorter_ratio <- 1/2
library(tidyverse)
library(ggpubr)
library(vdbR)
library(cowplot)
connect_database('~/dbConfig.txt')
get_table_from_database('qpcr_16s_ag')
get_table_from_database('antibiotics_antibacterial_multicenter_ag')
get_table_from_database('samples_castori_ag')
get_table_from_database('asv_annotation_blast_ag')

updated_qPCR <- qpcr_16s_ag %>%
  rename(sampleid=sample_id,
         copies_16s_per_g_pre = copies_16s_per_g) %>% 
  mutate(
    g = copy_number_16s/ copies_16s_per_g_pre,
    copies_16s_bounded = ifelse(
      copy_number_16s < 12800, 
      (12800*.5),
      ifelse(
        copy_number_16s > 2e8,
        1.5 * (2e8),
        copy_number_16s
      )
    )
  ) %>% 
  mutate(copies_16s_per_g =  copies_16s_bounded/g) 
```

Now I'm gonna really clean out the scripts that makes the figure 3 timecourse, and also add the egg intake data.

```{r}
klept <- read_csv('../data/095_Klebsiella-patient.csv')
ent_pt <- read_csv('../data/075_entero_pt.csv')
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
ptb <- read_csv('../data/cleaned_patients/diet_patients_97.csv')
combined <- read_csv('../data/114_combined_irep_650.csv')
all802 <- read_csv('../data/011_802_total_stool_samples.csv')
# the table that Peter checked for me the real missing days in the timeline of these two patients
missing <- read_csv('../data/114_timeline_2_pt_check_missing_6__PP_check.csv')


# the population data about daily sweets consumption and fruits and eggs comsumption
all9 <- dtb %>%  
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^9')) %>% 
  group_by(mrn, fdrt) %>% 
  summarise(sweetdaily = sum(dehydrated_weight))

s_q25 <- quantile(x = all9$sweetdaily, 0.25)
s_q50 <- quantile(x = all9$sweetdaily, 0.5)
s_q75 <- quantile(x = all9$sweetdaily, 0.75)
highest_daily_sweet_intake <- ceiling( max(all9$sweetdaily))
lowest_daily_sweet_intake <- floor( min(all9$sweetdaily))

# fruits
all6 <- dtb %>%  
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^6')) %>% 
  group_by(mrn, fdrt) %>% 
  summarise(fruitdaily = sum(dehydrated_weight))

f_q25 <- quantile(x = all6$fruitdaily, 0.25)
f_q50 <- quantile(x = all6$fruitdaily, 0.5)
f_q75 <- quantile(x = all6$fruitdaily, 0.75)
highest_daily_fruit_intake <- ceiling( max(all6$fruitdaily))
lowest_daily_fruit_intake <- floor( min(all6$fruitdaily))

# eggs
all3 <- dtb %>%  
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^3')) %>% 
  group_by(mrn, fdrt) %>% 
  summarise(eggdaily = sum(dehydrated_weight))

e_q25 <- quantile(x = all3$eggdaily, 0.25)
e_q50 <- quantile(x = all3$eggdaily, 0.5)
e_q75 <- quantile(x = all3$eggdaily, 0.75)
highest_daily_egg_intake <- ceiling( max(all3$eggdaily))
lowest_daily_egg_intake <- floor( min(all3$eggdaily))
```

# the Enterococcus patient

## the abx p11

```{r}
p11_abx <- antibiotics_antibacterial_multicenter_ag %>% 
  filter(patient_id == ent_pt$mrn ) %>% 
  rename(mrn = patient_id) %>% 
  mutate(mrn = as.numeric(mrn)) %>% 
  left_join(ptb %>% 
              select(mrn, hct)) %>% 
  mutate(startdrt = start - hct,
         stopdrt = stop - hct) %>% 
  # only select the days relevant
  filter(startdrt %in% -5:-2) %>% 
  mutate(drugfull = str_glue('{drug_name_clean} ({route_simple})')) %>% 
  arrange(startdrt, stopdrt) %>% 
  mutate(yval = seq(1, nrow(.))) %>% 
  mutate(startdrt = as.numeric(startdrt) ) %>% 
  mutate(startdrt = if_else(startdrt == -5, -5.1, startdrt))

xmin <- -5.1
xmax = 15

abx_ent <- ggplot(p11_abx, aes(x = startdrt, y = yval, xend = stopdrt, yend = yval, label = drugfull )) +
  geom_segment(
    size = 2, lineend = 'square', alpha = 0.5
  ) +
  geom_text(hjust = 'outside', nudge_y = -0.1, nudge_x = 5, size = 1.3) +
  coord_cartesian(xlim=c(xmin, xmax)) + 
  labs(x = '',
       y = '',
       title = 'Antibiotics') + 
  theme_classic() +
  theme(aspect.ratio=shorter_ratio,axis.ticks.y=element_blank(), axis.text.y=element_blank(),line = element_blank(),axis.text=element_blank(),axis.title=element_blank(),plot.title = element_blank(),panel.grid.major.x = element_blank())
```

## the sweets p11

```{r}
missing_days_p11 <- missing %>% 
  filter(mrn == ent_pt$mrn & diet_data_status == 'missing' ) %>% 
  pull(fdrt)

p11_sweets <- dtb %>%  
  filter(mrn == ent_pt$mrn & fdrt %in% -4:15) %>% 
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^9')) %>% 
  group_by(fdrt) %>% 
  summarise(sweetsum = sum(dehydrated_weight)) %>% 
  full_join(tibble(
    fdrt = seq(-2, 12, 1)
  )) %>% 
  mutate(sweetsum = if_else(is.na(sweetsum), 0, sweetsum)) %>% 
  # there are days that are actually missing
  filter(! fdrt %in% missing_days_p11) %>% 
  mutate(p_size  = if_else(sweetsum > s_q75, 3, 1)) 

sweets_ent <- p11_sweets %>%    
  ggplot(aes(x = fdrt, y = sweetsum )) +
  annotate('rect', xmin = xmin, xmax = xmax, ymin = s_q25, ymax = s_q75, fill='gray',  alpha=0.3) +
  geom_line(aes(x = fdrt, y = sweetsum), linetype = 'solid', size = 0.5, col = 'black') +
  geom_point(aes(size = sweetsum > s_q75, col = sweetsum > s_q75)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  xlim(xmin, xmax) +
  labs(x = '',
       y = 'Sweets(g)',
       title = '') +
  theme_classic() + 
  ylim(0, max(p11_sweets$sweetsum))+
  theme(aspect.ratio=shorter_ratio, legend.position = 'none' ,
        axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        plot.margin = margin(l=-0.8,unit="cm"),
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(colour = "grey85"))
sweets_ent 
```

# the fruits p11

```{r}
p11_fruits <- dtb %>%  
  filter(mrn == ent_pt$mrn & fdrt %in% -4:15) %>% 
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^6')) %>% 
  group_by(fdrt) %>% 
  summarise(fruitsum = sum(dehydrated_weight)) %>% 
  full_join(tibble(
    fdrt = seq(-2, 12, 1)
  )) %>% 
  mutate(fruitsum = if_else(is.na(fruitsum), 0, fruitsum)) %>% 
  # there are days that are actually missing
  filter(! fdrt %in% missing_days_p11) %>% 
  mutate(p_size  = if_else(fruitsum > f_q75, 3, 1)) 

fruits_ent <- p11_fruits %>%    
  ggplot(aes(x = fdrt, y = fruitsum )) +
  annotate('rect', xmin = xmin, xmax = xmax, ymin = f_q25, ymax = f_q75, fill='gray',  alpha=0.3) +
  geom_line(aes(x = fdrt, y = fruitsum), linetype = 'solid', size = 0.5, col = 'black') +
  geom_point(aes(size = fruitsum > f_q75, col = fruitsum > f_q75)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  xlim(xmin, xmax) +
  labs(x = '',
       y = 'Fruits(g)',
       title = '') +
  theme_classic() + 
  ylim(0, max(p11_fruits$fruitsum))+
  theme(aspect.ratio=shorter_ratio, legend.position = 'none' ,
        axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        plot.margin = margin(l=-0.8,unit="cm"),
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(colour = "grey85"))
fruits_ent 
```

# the eggs p11

```{r}
p11_eggs <- dtb %>%  
  filter(mrn == ent_pt$mrn & fdrt %in% -4:15) %>% 
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^3')) %>% 
  group_by(fdrt) %>% 
  summarise(eggsum = sum(dehydrated_weight)) %>% 
  full_join(tibble(
    fdrt = seq(-2, 12, 1)
  )) %>% 
  mutate(eggsum = if_else(is.na(eggsum), 0, eggsum)) %>% 
  # there are days that are actually missing
  filter(! fdrt %in% missing_days_p11) %>% 
  mutate(p_size  = if_else(eggsum > e_q75, 3, 1)) 

eggs_ent <- p11_eggs %>%    
  ggplot(aes(x = fdrt, y = eggsum )) +
  annotate('rect', xmin = xmin, xmax = xmax, ymin = e_q25, ymax = e_q75, fill='gray',  alpha=0.3) +
  geom_line(aes(x = fdrt, y = eggsum), linetype = 'solid', size = 0.5, col = 'black') +
  geom_point(aes(size = eggsum > e_q75, col = eggsum > e_q75)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  xlim(xmin, xmax) +
  labs(x = '',
       y = 'Eggs(g)',
       title = '') +
  theme_classic() + 
  ylim(0, max(p11_eggs$eggsum))+
  theme(aspect.ratio=shorter_ratio, legend.position = 'none' ,
        axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        plot.margin = margin(l=-0.8,unit="cm"),
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(colour = "grey85"))
eggs_ent 
```

# enterococcus growth rate

```{r}
entero_irep_all <- combined %>%  
  filter(str_detect(best_species, 'Enterococcus')) %>% 
  group_by(sampleid, mrn) %>% 
  summarise(ave_irep = mean(aveirep)) %>% 
  inner_join(all802 %>% 
               select(sampleid, sdrt))

e_irep_q25 <- quantile(x = entero_irep_all$ave_irep, 0.25)
e_irep_q50 <- quantile(x = entero_irep_all$ave_irep, 0.5)
e_irep_q75 <- quantile(x = entero_irep_all$ave_irep, 0.75)
irep_highest <- max(entero_irep_all$ave_irep) + 0.05

p11_irep <-  entero_irep_all %>% 
  filter(sdrt %in% -5:15) %>% 
  filter(mrn == ent_pt$mrn) %>%
  ggplot(aes(x = sdrt, y = ave_irep )) +
  annotate('rect', xmin = xmin, xmax = xmax, ymin = e_irep_q25, ymax = e_irep_q75, fill='gray',  alpha=0.3) +
  geom_point(aes(size = ave_irep > e_irep_q75, col = ave_irep > e_irep_q75)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  labs(title = str_glue('{}')) +
  xlim(xmin, xmax) +
  ylim(1, irep_highest) +
  labs(x = '', 
       y = 'Enterococcus\ngrowth rate',
       title = '')+
  theme_classic()+
  theme(aspect.ratio=shorter_ratio, legend.position = 'none' ,
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(color = "grey85"))
p11_irep
```

# enterococcus copy numbers

```{r}

sam <- samples_castori_ag %>% 
  filter(mrn %in% ent_pt$mrn) %>% 
  distinct(sampleid) %>% 
  pull(sampleid)

samps <- samples_castori_ag %>% 
  filter(mrn %in% ent_pt$mrn) %>% 
  distinct(sampleid, mrn)

cts <- get_counts_subset(sam)

cts_entero <- cts %>% 
  left_join(asv_annotation_blast_ag %>% 
              select(asv_key, genus)) %>% 
  group_by(sampleid, genus) %>% 
  summarise(relab = sum(count_relative)) %>% 
  filter(genus == 'Enterococcus')  %>% 
  inner_join(updated_qPCR %>% 
               select(sampleid , copies_16s_per_g)) %>% 
  mutate(entero_copy = copies_16s_per_g*relab) %>% 
  inner_join(samples_castori_ag %>% 
               select(sampleid, datecollection)) %>% 
  inner_join(samps) %>% 
  inner_join(ptb %>% 
               select(mrn, hct)) %>% 
  mutate(sdrt = datecollection - hct) %>% 
  filter(sdrt < 54) %>% 
  mutate(max_pt = if_else(entero_copy == max(cts_entero$entero_copy), T, F))

p11_copies <- cts_entero %>% 
  filter(sdrt %in% -5:15) %>% 
  mutate(entero_copy = entero_copy/1e8) %>% 
  ggplot(aes(x = sdrt, y = entero_copy )) +
  geom_line(aes(x = sdrt, y = entero_copy), linetype = 'solid', size = 0.5, col = 'black') +
  geom_point(aes(size = max_pt, col = max_pt)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  xlim(xmin, xmax) +
  labs(x = 'Transplant day',
       y = 'Enterococcus\ncopies X 108/g',
       title = '') +
  theme_classic() +
  theme(aspect.ratio=shorter_ratio,legend.position = 'none',
        plot.margin = margin(l=-0.8,unit="cm"),
            axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(colour = "grey85"))
p11_copies
```

# kle abx

```{r}
kle_irep <- combined %>% 
  filter(mrn == klept$mrn & str_detect(best_species, 'Klebsiella'))
lowerday <- min(kle_irep$sdrt)
highday <- max(kle_irep$sdrt)
xmin <- lowerday - 1 
xmax <- highday + 1  

kle_abx <- antibiotics_antibacterial_multicenter_ag %>% 
  filter(patient_id == as.character(klept$mrn) ) %>% 
  rename(mrn = patient_id) %>% 
  mutate(mrn = as.numeric(mrn)) %>% 
  left_join(ptb %>% 
              select(mrn, hct)) %>% 
  mutate(startdrt = start - hct,
         stopdrt = stop - hct) %>% 
  # only select the days relevant
  filter(startdrt %in% -2:4) %>% 
  mutate(drugfull = str_glue('{drug_name_clean} ({route_simple})')) %>% 
  arrange(startdrt, stopdrt) %>% 
  mutate(yval = seq(1, nrow(.)))
  
abx_kle <- ggplot(kle_abx, aes(x = startdrt, y = yval, xend = stopdrt, yend = yval, label = drugfull )) +
  geom_segment(
     size = 2, lineend = 'square', alpha = 0.5
  ) +
  geom_text(hjust = 'outside', nudge_y = -0.1, nudge_x = 5, size = 1.3) +
   xlim(xmin, xmax) +
  labs(x = '',
       y = '',
       title = '') + 
  theme_classic() +
  theme(aspect.ratio=shorter_ratio,
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        line = element_blank(),
        axis.text=element_blank(),
        axis.title=element_blank(),
        plot.title = element_blank(),
        panel.grid.major.x = element_blank())
abx_kle
```

# kle sweets
```{r}
missing_days_kle <- missing %>% 
  filter(mrn == klept$mrn & diet_data_status == 'missing' ) %>% 
  pull(fdrt)

kle_sweets <- dtb %>%  
  filter(mrn == klept$mrn & fdrt %in% lowerday:highday) %>% 
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^9')) %>% 
  group_by(fdrt) %>% 
  summarise(sweetsum = sum(dehydrated_weight)) %>% 
  full_join(tibble(
    fdrt = seq(lowerday, highday, 1)
  )) %>% 
  mutate(sweetsum = if_else(is.na(sweetsum), 0, sweetsum)) %>% 
  # there are days that are actually missing
  filter(! fdrt %in% missing_days_kle) %>% 
  mutate(p_size  = if_else(sweetsum > s_q75, 3, 1)) 

sweets_kle <- kle_sweets %>%    
  ggplot(aes(x = fdrt, y = sweetsum )) +
  annotate('rect', xmin = xmin, xmax = xmax, ymin = s_q25, ymax = s_q75, fill='gray',  alpha=0.3) +
  geom_line(aes(x = fdrt, y = sweetsum), linetype = 'solid', size = 0.5, col = 'black') +
  geom_point(aes(size = sweetsum > s_q75, col = sweetsum > s_q75)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  xlim(xmin, xmax) +
  labs(x = '',
       y = 'Sweets(g)',
       title = '') +
  theme_classic() + 
  ylim(0, max(kle_sweets$sweetsum))+
  theme(aspect.ratio=shorter_ratio, legend.position = 'none' ,
        axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        plot.margin = margin(l=-0.8,unit="cm"),
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(colour = "grey85"))
sweets_kle 
```

# kle fruits
```{r}
kle_fruits <- dtb %>%  
  filter(mrn == klept$mrn & fdrt %in% lowerday:highday) %>% 
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^6')) %>% 
  group_by(fdrt) %>% 
  summarise(fruitsum = sum(dehydrated_weight)) %>% 
  full_join(tibble(
    fdrt = seq(lowerday, highday, 1)
  )) %>% 
  mutate(fruitsum = if_else(is.na(fruitsum), 0, fruitsum)) %>% 
  filter(! fdrt %in% missing_days_kle) %>% 
  mutate(p_size  = if_else(fruitsum > f_q75, 3, 1)) 

fruits_kle <- kle_fruits %>%    
  ggplot(aes(x = fdrt, y = fruitsum )) +
  annotate('rect', xmin = xmin, xmax = xmax, ymin = f_q25, ymax = f_q75, fill='gray',  alpha=0.3) +
  geom_line(aes(x = fdrt, y = fruitsum), linetype = 'solid', size = 0.5, col = 'black') +
  geom_point(aes(size = fruitsum > f_q75, col = fruitsum > f_q75)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  xlim(xmin, xmax) +
  labs(x = '',
       y = 'Fruits(g)',
       title = '') +
  theme_classic() + 
  ylim(0, max(kle_fruits$fruitsum))+
  theme(aspect.ratio=shorter_ratio, legend.position = 'none' ,
        axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        plot.margin = margin(l=-0.8,unit="cm"),
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(colour = "grey85"))
fruits_kle 
```

# kle eggs
```{r}
kle_eggs <- dtb %>%  
  filter(mrn == klept$mrn & fdrt %in% lowerday:highday) %>% 
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^3')) %>% 
  group_by(fdrt) %>% 
  summarise(eggsum = sum(dehydrated_weight)) %>% 
  full_join(tibble(
    fdrt = seq(lowerday, highday, 1)
  )) %>% 
  mutate(eggsum = if_else(is.na(eggsum), 0, eggsum)) %>% 
  # there are days that are actually missing
  filter(! fdrt %in% missing_days_p11) %>% 
  mutate(p_size  = if_else(eggsum > e_q75, 3, 1)) 

eggs_kle <- kle_eggs %>%    
  ggplot(aes(x = fdrt, y = eggsum )) +
  annotate('rect', xmin = xmin, xmax = xmax, ymin = e_q25, ymax = e_q75, fill='gray',  alpha=0.3) +
  geom_line(aes(x = fdrt, y = eggsum), linetype = 'solid', size = 0.5, col = 'black') +
  geom_point(aes(size = eggsum > e_q75, col = eggsum > e_q75)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  xlim(xmin, xmax) +
  labs(x = '',
       y = 'Eggs(g)',
       title = '') +
  theme_classic() + 
  ylim(0, max(kle_eggs$eggsum))+
  theme(aspect.ratio=shorter_ratio, legend.position = 'none' ,
        axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        plot.margin = margin(l=-0.8,unit="cm"),
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(colour = "grey85"))
eggs_kle 
```

# kle irep
```{r}
kle_irep_all <- combined %>%  
  filter(str_detect(best_species, 'Klebsiella')) %>% 
  group_by(sampleid, mrn) %>% 
  summarise(ave_irep = mean(aveirep)) %>% 
  inner_join(all802 %>% 
               select(sampleid, sdrt))
k_irep_q25 <- quantile(x = kle_irep_all$ave_irep, 0.25)
k_irep_q50 <- quantile(x = kle_irep_all$ave_irep, 0.5)
k_irep_q75 <- quantile(x = kle_irep_all$ave_irep, 0.75)
k_irep_highest <- max(kle_irep_all$ave_irep) + 0.05


kle_irep <-  kle_irep_all %>% 
  #filter(sdrt %in% -5:15) %>% 
  filter(mrn == klept$mrn) %>%
  ggplot(aes(x = sdrt, y = ave_irep )) +
  annotate('rect', xmin = xmin, xmax = xmax, ymin = k_irep_q25, ymax = k_irep_q75, fill='gray',  alpha=0.3) +
  geom_point(aes(size = ave_irep > k_irep_q75, col = ave_irep > k_irep_q75)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  labs(title = str_glue('{}')) +
  xlim(xmin, xmax) +
  ylim(1, k_irep_highest) +
  labs(x = '', 
       y = 'Klebsiella\ngrowth rate',
       title = '')+
  theme_classic()+
  theme(aspect.ratio=shorter_ratio, legend.position = 'none' ,
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(color = "grey85"))
kle_irep
```

# kle copies 
```{r}
sam <- samples_castori_ag %>% 
  filter(mrn %in% klept$mrn) %>% 
  distinct(sampleid) %>% 
  pull(sampleid)

samps <- samples_castori_ag %>% 
  filter(mrn %in% klept$mrn) %>% 
  distinct(sampleid, mrn)

cts <- get_counts_subset(sam)

cts_kle <- cts %>% 
  left_join(asv_annotation_blast_ag %>% 
              select(asv_key, genus)) %>% 
  group_by(sampleid, genus) %>% 
  summarise(relab = sum(count_relative)) %>% 
  filter(genus == 'Klebsiella')  %>% 
  inner_join(updated_qPCR %>% 
               select(sampleid , copies_16s_per_g)) %>% 
  mutate(kle_copy = copies_16s_per_g*relab) %>% 
  inner_join(samples_castori_ag %>% 
               select(sampleid, datecollection)) %>% 
  inner_join(samps) %>% 
  inner_join(ptb %>% 
               select(mrn, hct)) %>% 
  mutate(sdrt = datecollection - hct) %>% 
  mutate(max_pt = if_else(kle_copy == max(cts_kle$kle_copy), T, F))
 

kle_copies <- cts_kle %>% 
  #filter(sdrt %in% -5:15) %>% 
  mutate(kle_copy = kle_copy/1e7) %>% 
  ggplot(aes(x = sdrt, y = kle_copy )) +
  geom_line(aes(x = sdrt, y = kle_copy), linetype = 'solid', size = 0.5, col = 'black') +
  geom_point(aes(size = max_pt, col = max_pt)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  xlim(xmin, xmax) +
  labs(x = 'Transplant day',
       y = 'Klebsiella\ncopies X 107/g',
       title = '') +  
  theme_classic() +
  theme(aspect.ratio=shorter_ratio,legend.position = 'none',
        plot.margin = margin(l=-0.8,unit="cm"),
            axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(colour = "grey85"))
kle_copies


  
```

# assemble the figures together

```{r}
f3c <- plot_grid(abx_ent, sweets_ent, fruits_ent, p11_irep, p11_copies ,
                  ncol = 1,axis = 'lbrt', align = 'hv') 
f3d <- plot_grid(abx_kle, sweets_kle, fruits_kle, kle_irep, kle_copies ,
                  ncol = 1,axis = 'lbrt', align = 'hv') 
f3_bottom <- plot_grid(f3c, f3d, ncol = 2, labels = c('C', 'D'))
ggsave('../figs/paper/116_f3bottom.pdf',
       width = 200,
       height = 260,
         #height = 60,  
         units = c("mm"),
         dpi = 400, plot = f3_bottom)
```


