---
title: "F2E heatmap panel"
author: "Angel"
date: "2022-07-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggpubr)
library(tidyverse)
axis_title_size <- 8
axis_text_size <- 8
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')
```

Make a small heatmap panel for the F2E with the 5 genera in enterobacteri and Enterococcus

```{r}
# import the model post results
entero <- read_csv('../data/087_Enterococcus_model_fg_post.csv') %>% 
  mutate(genus = 'Enterococcus') %>% 
  relocate(genus, .before = b_fg_fruit)
extra5 <- read_csv('../data/087_genus_foodgroup_model_post_extra_few.csv')

post <- bind_rows(entero, extra5) %>% 
  select(genus, starts_with('b_fg')) %>% 
  gather('item','coeff', names(.)[2]:names(.)[ncol(.)])


post_res_genera <- post %>% 
  group_by(genus, item) %>% 
  summarise(q50 = median(coeff),
            q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975),
            q12.5 = quantile(coeff, probs = 0.125),
            q87.5 = quantile(coeff, probs = 0.875),
            q1.25 = quantile(coeff, probs = 0.0125),
            q98.75 = quantile(coeff, probs = 0.9875),
            q0.5 = quantile(coeff, probs = 0.005),
            q99.5 = quantile(coeff, probs = 0.995)
            ) %>% 
  ungroup() %>% 
  mutate(mark = if_else(q99.5 < 0 | q0.5 > 0, '***', if_else(q98.75 < 0 | q1.25 > 0, '**', if_else(q97.5 < 0 | q2.5 > 0, '*', '')))) %>% 
  mutate(color = if_else(q87.5 < 0, 'steelblue', if_else(q12.5 > 0, 'maroon', 'white'))) %>% 
  mutate(item = str_replace(item, 'b_ave_','')) %>% 
  mutate(item = str_to_title(item)) %>% 
  mutate(item = str_replace(item, 'B_','')) %>% 
  left_join(key %>% select(item = fg1_name, shortname))

```

How about I scale the percentage of the interval that is on eather side of 0 to different shades of blue/red; making all numbers with magnitudes less than .75 white. and it just makes it easier to see what’s important with the asterisks as in the supporting figure.

```{r}
# calculate the percentage of interval that is >|< 0 for each genus/food combo
dtb <- read_csv('../data/152_combined_DTB.csv')
fg_order <- dtb %>% distinct(Food_code) %>% mutate(fgrp1 = str_sub(as.character(Food_code),1, 1)) %>% 
  count(fgrp1) %>% 
  full_join(key) %>% arrange(n) %>% pull(shortname)


perc_side <- post %>% 
  group_by(genus,item ) %>% 
  count(coeff >= 0) %>% 
  mutate(perc = round(n/4000, 2)) %>% 
  mutate(side = if_else(`coeff >= 0` == 'TRUE', 'positive', 'negative')) %>% 
  ungroup() %>% 
  select(genus, item, perc, side) %>% 
  spread('side', 'perc') %>% 
  mutate(item = str_replace(item, 'b_','')) %>% 
  left_join(key %>% select(item = fg1_name, shortname), by = "item") %>%
  mutate(color = if_else(positive >= 0.75, 'maroon', if_else(negative >= 0.75, 'steelblue', 'white'))) %>% 
  mutate(mark = if_else(negative >= 0.99 | positive >= 0.99, '***', if_else(negative >= 0.975 | positive >= 0.975, '**', if_else(negative >= 0.95 | positive >= 0.95, '*', '')))) %>% 
  mutate(genus = factor(genus, levels = c('Enterococcus','Klebsiella','Cronobacter','Enterobacter','Citrobacter','Cedecea','Escherichia'))) %>% 
  mutate(shortname = factor(shortname, levels = fg_order)) 


```

```{r}
col_key <- perc_side %>% 
  ungroup() %>% 
  distinct(color) %>% 
  pull(color)
names(col_key) <- col_key

genus_fg_extra <- ggplot(perc_side, aes(x = genus, y = shortname)) +
  geom_tile(aes(fill = color,  x = genus, y =  shortname), alpha = 0.5, color='gray0', width=1, height=1) +
  geom_text(aes(label = mark, x = genus,y =  shortname),
            nudge_y = -0.05, nudge_x = 0,size = 3) +
  scale_fill_manual(values = col_key, labels = c('Less than 75% CI crosses 0', '75% CI < 0 negative','75% CI > 0 positive')) +
  theme_void() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle=90, hjust=1, size=axis_text_size),
        axis.text.y=element_text(size=axis_text_size, hjust=0.95,vjust=0.2),
        axis.title=element_text(size=axis_title_size),
        legend.position = 'none',legend.text=element_text(size=8),
        legend.key = element_rect( colour = "gray50")) 
genus_fg_extra %>% write_rds('../data/120_F2E_extra_genera.rds')
ggsave('../data/120_F2E_extra_genera.pdf', width =  60,plot = genus_fg_extra,
       height = 70, 
         units = c("mm"),
         dpi = 400)
```