---
output:
  pdf_document: default
  html_document: default
---
title: "iRep Bayesian Model"
output:
  pdf_document:
date: '2022-07-20'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.width = 3, 
                      fig.height = 3,
                      fig.align = 'center')
library(rethinking)
library(dplyr)
library(ggplot2)
library(quantreg)
library(ggpmisc)
library(broom)
```
```{r}
df <- read.csv(file='../data/sum of sugar intake vs max zscore family(E,E).csv')
outpath <- '../data'
```
```{r}
### process dataframe
encode_ordinal <- function(x, order = unique(x)) {
  x <- as.numeric(factor(x, levels = order, exclude = NULL))
  x
}
df$pid_encoded <- encode_ordinal(df$pid)  
## remove NA
df <- df %>% filter(!is.na(sum_sugar) )
## standardize
df$sum_sugar_s <- (df$sum_sugar - mean(df$sum_sugar)) / sd(df$sum_sugar)
df <- df %>% select(iRep_zscore,sum_sugar,sum_sugar_s,genus,best_species,pid,pid_encoded,family)
head(df)
```
```{r}
ggplot(df, aes(x = sum_sugar, y = iRep_zscore)) + geom_point() +
  theme_classic()+
  xlab('Sum of sugar (g) standardized') +
  ylab('iRep zscore') +
  ggtitle(paste0('Sum of sugar intake vs irep zscore \nsamples=',nrow(df))) +
  theme(plot.title = element_text(size = 10, face = "bold")) +
  stat_smooth(method = "lm",formula = y~x) +
  stat_fit_glance(method = 'lm',
                  method.args = list(formula = y ~ x),
                  geom = 'text',
                  aes(label = paste("p-value=", signif(..p.value.., digits = 3),
                                     sep = "")),
                      label.x = 3, label.y = 3, size = 2)

df %>% distinct(pid)
```
```{r}
head(df)
```
```{r}
ggplot(df, aes(x = sum_sugar_s, y = iRep_zscore)) + geom_point() + 
  theme_classic()+
  xlab('Sum (sweets, fruit) (g) standardized') +
  ylab('iREP z-score (family level)') + 
  ggtitle(paste0('Sum (sweets, fruit) intake vs iREP z-score \nsamples=',nrow(df))) + 
  theme(plot.title = element_text(size = 10, face = "bold")) +
  stat_smooth(method = "lm",formula = y~x) + 
  stat_fit_glance(method = 'lm',
                  method.args = list(formula = y ~ x),  
                  geom = 'text', 
                  aes(label = paste("p-value=", signif(..p.value.., digits = 3), 
                                     sep = "")),
                      label.x = 3, label.y = 3, size = 4) 
```
```{r,out.width="50%",out.height="50%", echo=FALSE}
# ggplot(df, aes(x = sum_sugar_s, y = iRep_zscore)) + geom_point(size=0.5) + 
#   theme_classic()+
#   xlab('Sum of sugar (g) standardized') +
#   ylab('iRep zscore') + 
#   ggtitle(paste0('Sum of sugar intake vs irep zscore \nsamples=',nrow(df))) + 
#   theme(plot.title = element_text(size = 10, face = "bold"),
#         axis.title = element_text(size = 5)) +
#   facet_wrap(~pid,nrow = 3) 
# 
# ggplot(df, aes(x = sum_sugar_s, y = iRep_zscore)) + geom_point(size=0.5) + 
#   theme_classic()+
#   xlab('Sum of sugar (g) standardized') +
#   ylab('iRep zscore') + 
#   ggtitle(paste0('Sum of sugar intake vs irep zscore \nsamples=',nrow(df))) + 
#   theme(plot.title = element_text(size = 10, face = "bold"),
#         axis.title = element_text(size = 5)) +
#   facet_wrap(~pid,nrow = 3) + 
#   stat_smooth(method = "lm",formula = y~x)
```
```{r}
```
```{r, echo=FALSE}
d <- list(irep = df$iRep_zscore, 
             sugar = df$sum_sugar_s,
             pid = df$pid_encoded)
mfam <- ulam(
  alist(
    irep ~ dnorm(mu,sigma),
    mu <- a_p[pid] + b*sugar,
    a_p[pid] ~ dnorm(a,sigma_a),
    a ~ dnorm(0,1),
    b ~ dnorm(0,0.5),
    sigma ~ dexp(1),
    sigma_a ~ dexp(5)
  ),data = d, chains = 4, iter=2000
)
precis(mfam)
str(mfam)
```
```{r}
#show(m)
traceplot(mfam)
```
```{r}
#### prior 
min_irep_zscore <- -1
max_irep_zscore <- 3 
curve(dnorm(x , 0, 0.5), from=min_irep_zscore, to=max_irep_zscore,n=100, xlab='')
```
```{r,echo=FALSE}
min_sugar_s <- -2 
max_sugar_s <- 2 
curve(dnorm(x, 0, 2), from=min_sugar_s, to=max_sugar_s,n=100, xlab=' ')
```
```{r}
### prior predictive checks
prior <- extract.prior(mfam)
```
```{r}
curve(dexp(x, rate=3), from=0, to=10)
curve(dexp(x, rate=1), from=0, to=10, add=TRUE, col='red')
```
```{r}
#pdf(paste0(outpath,'prior_prediction.pdf'),width=5,height=5)
#plot(NULL, xlim=(c(-2,2)),ylim=(c(-1,3)),xlab=('sum sugar intake std'),ylab=('iRep z-score fam'))
#abline(h = min(df$iRep_s),lty=2)
#abline(h = max(df$iRep_s),lty=2)
#sugar_seq <- seq(from=-2, to=2, length.out=30)
#mu <- link(mfam, post=post, data=data.frame(sugar=sugar_seq))
#for (i in 1:50) lines(sugar_seq, mu[i,], col=col.alpha("black",0.3))
#dev.off()
```
```{r}
#precis(m, depth = 2)
#pdf(paste0(outpath,'forest_plot.pdf'),width=5,height=5)
plot(precis(mfam,depth=2))
#dev.off()
```
```{r}
post<-extract.samples(mfam)
```
```{r}
plot( df$sum_sugar_s,df$iRep_zscore,pch=16,col=rangi2,
xlab="Sum (sweets, fruit) [standardized]",ylab="max iRep z-score (family)",
xlim=c(-2,2))
#mu<- link(mfam, data=data.frame(sugar=sugar_seq), post=post)
#mu_link <- function(mfam, )
#mu_mean <-apply(mu,2,mean)
#mu_ci <-apply(mu,2,PI,prob=0.95)
lines(sugar_seq,mu_mean,lwd=3)
shade( mu_ci,sugar_seq)
mtext("Posterior prediction iRep model ME sum (sweets, fruit)")
#df
```
```{r}
meanline <- mean(coef(mfam)[1:18])
```
```{r}
df
```
```{r}
#plot( df$sum_sugar_s,df$iRep_zscore,pch=16,col="orange",
#xlab="Sum (sweets, fruit) [standardized]",ylab="max iRep z-score (family)",
#xlim=c(-2,2))
df$family <- as.factor(df$family)
sugar = df$sum_sugar_s
sugar_seq <- seq(from=-2, to=2, length.out=30)
mu.link <- function(sugar) post$a + post$b * sugar
mu <- sapply(sugar_seq, mu.link)
mu.mean <- apply(mu, 2, mean)
mu.CI <- apply(mu, 2, HPDI, prob=0.95)
plot(d$sugar, d$irep,
     xlim=(c(-2,2)),ylim=(c(-2,3)),
     xlab=('Sum (fruit, sweets)'),ylab=('iRep z-score family level'),col=c("green","red")[as.factor(df$family)],pch=16)
legend(-1.5,-1.5,legend = c("Enterococaceae","Enterobacteriaceae"),col=c("green","red"),pch=16)
lines(sugar_seq, mu.mean, lty=1, lwd =1.5)
shade(mu.CI,sugar_seq,xpd=TRUE)
#mu_link <- function (post, data=data.frame(sugar=sugar_seq,pid=1), with {a_p + b*sugar})
#mu_mean <-apply(mu,2,mean)
#mu_ci <-apply(mu_link,2,PI,prob=0.94)
#lines(sugar_seq,mu_mean,lwd=3)
#abline(a=mean(coef(mfam)[1:18]), b=coef(mfam)[20])
#shade( mu_ci,sugar_seq)
mtext("Posterior prediction iRep ME model sum (sweets, fruit)")
```
```{r}
post<-extract.samples(mfam)
plot(precis(mfam, depth=2))
```

