---
title: "peter sample irep values"
author: "Angel"
date: "2022-08-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
axis_title_siza <- 11
```

```{r}
fns <- list.files('../data/growth/irep/peter_samples_irep/', full.names = T, pattern = '.tsv')
df <- tibble(fns = fns)
irep <- fns %>% 
  set_names(fns) %>% 
  purrr::map(~  read_tsv(file = ., n_max = 1 , col_types = 'cc',  skip = 2, col_names = c('bin','iRep')) %>%  select(iRep) ) %>% 
  bind_rows(.id = 'fn') %>% 
  mutate(fn = str_replace(fn, '_irep_dastool.tsv$',''),
         fn = str_replace(fn, '../data/growth/irep/peter_samples_irep//','')) %>% 
  separate(fn, into = c('sampleid','samplebin'), sep = '__concat__', remove = T) %>% 
  mutate(iRep = as.numeric(iRep)) %>% 
  mutate(sbid = str_glue('{sampleid}__{samplebin}')) %>% 
  filter(str_detect(sampleid, '^Sample')) # to only include the project 13141 ones

samp <- irep %>% 
  distinct(sampleid)
```


```{r}
bins <- read_tsv('../data/growth/irep/binning_table_all_simple_peter.tsv') %>% 
  rename_all(~ gsub("\\.", "_", .)) %>% 
  mutate(fpmbp = `# contigs (>= 0 bp)`/Size_Mb) %>% 
  filter(Completeness >= 75 & fpmbp <= 175 & Contamination <= 2) %>% 
  mutate(Sample = str_replace(Sample, '__concat',''),
         sbid = str_glue('{Sample}__{Bin}')) %>% 
  inner_join(irep, by  = 'sbid') %>% 
  relocate(iRep, .after = 'Bin') %>% 
  relocate(best_species, .after = 'iRep') %>% 
  filter(!is.na(iRep)) %>% 
  arrange(Sample,Bin,  best_species) %>% 
  # if there are multiple get the average
  #group_by(Sample, best_species, best_level) %>% 
  #summarise(aveirep = mean(iRep)) %>% 
  filter(best_species != 'Unclassified') %>% 
  mutate(sampleid = str_extract(Sample, '^Sample.+IGO'),
         sampleid = str_replace(sampleid, 'Sample_',''),
         sampleid = str_replace(sampleid, '_IGO','')) %>% 
  relocate(sampleid, .before = 'Sample')  %>% 
  mutate(sampleid = str_replace(sampleid, '_2', ''),
         sampleid = str_replace(sampleid,'FMT_', 'FMT\\.'))

# find the genus and family of the irep bins
colnames(bins)
```



```{r}
# do these samples overlap with the current diet cohort?
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')
stool <- read_csv('../data/011_802_total_stool_samples.csv')
length(intersect(stool$sampleid, bins$sampleid))
length(intersect(meta$sampleid, bins$sampleid)) # 28
has_diet <- intersect(meta$sampleid, bins$sampleid)


# find the previous 2 days sum of fruits and sweets
p2d_sum69 <- meta %>% 
  filter(sampleid %in% has_diet) %>% 
  select(sampleid, fg_fruit, fg_sweets) %>% 
  mutate(sum69 = (fg_fruit + fg_sweets) *2)
```

# the genera in enterococcaea and enterbacteria 

```{r}
library(vdbR)
connect_database()
get_table_from_database('shotgun_lookup_ad')
list_table_from_database('blast')
get_table_from_database('asv_annotation_blast_ag')

target <- asv_annotation_blast_ag %>% 
  filter(family %in% c('Enterobacteriaceae','Enterococcaceae')) %>% 
  distinct(family, genus) %>% 
  summarise(genera = str_c(genus, collapse = "|"))

find_higher <- bins %>% 
  distinct(best_species,  best_level) %>% 
  arrange(best_species) %>% 
  filter(str_detect(best_species, target$genera)) %>% 
  mutate(genus = c('Enterobacter','Enterococcus','Enterococcus','Enterococcus','Escherichia','Klebsiella','Klebsiella'))


family2 <- bins %>% 
  select(sampleid,samplebin,  iRep, best_species,  best_level) %>% 
  inner_join(find_higher) %>% 
  inner_join(p2d_sum69 %>% 
               select(sampleid, sum_sugar = sum69)) %>% 
  select(sampleid, samplebin, iRep, genus, sum_sugar)


family2_irep <- bins %>% 
  select(sampleid,samplebin,  iRep, best_species,  best_level) %>% 
  inner_join(find_higher)

older <-  read_csv('../data/sum of sugar intake vs max zscore family(E,E).csv') %>% 
  select(colnames(family2_irep)) 

all_fam2_irep <- bind_rows(family2_irep,older )%>% 
   split(.$genus) %>% 
  map(function(df){
    df %>% 
      mutate(iRep_zscore = scale(.$iRep, center = T, scale = T)[,1])
  }
    ) %>% 
  bind_rows()  %>%  
  inner_join(all %>% select(sampleid, sum_sugar) )   
```
```{r}
# if there is any sample that is not in the 145

should <- read_csv('../data/135_selected_samples_for_irep_analysis.csv')

them <- read_csv('../data/sum of sugar intake vs max zscore family(E,E).csv') %>% 
  select(sampleid, samplebin, iRep, genus, p1d_Sweets, p2d_Sweets,p1d_Fruits, p2d_Fruits, iRep_zscore, pid, sum_sugar) %>% filter(sampleid %in% should$sampleid) %>% 
  mutate(ave_sugar = sum_sugar/2)  %>% 
  filter(!is.na(ave_sugar)) %>% 
  split(.$genus) %>% 
  map(function(df){
    df %>% 
      mutate(iRep_zscore = scale(.$iRep, center = T, scale = T)[,1])
  }
    ) %>% 
  bind_rows() 
them %>% count(sampleid)

# the color palette used in Jonas version
genus_pal <- tibble(
  genus = them %>% distinct(genus) %>% pull(genus),
  colors = c('#cd2026','#326634','#ee2023','#991b1d') 
) %>% 
  deframe

simple <- them %>%select(sampleid, iRep_zscore, genus) 
```
```{r}
ave_combined <- them %>% 
  ggpubr::ggscatter(x = 'ave_sugar', y = 'iRep_zscore',  color = 'genus',palette = 'lancet',
                    xlab = 'Sweets and fruits intake averaged (g)',
                    ylab = 'Growth rate\n(standardized within genus) ',
                    add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n", label.x.npc = "left", size = 2.5)) +
  scale_color_manual(values = genus_pal) +
  theme(aspect.ratio = 1,
        axis.text=element_text(size=11),
        axis.title=element_text(size=11),
        legend.position = 'top',
        legend.title=element_blank())

ggsave('../data/123_new_2fam_fig3top.pdf', height = 3, plot = ave_combined)

# the number for fig3E
them %>% distinct(pid) %>% nrow

them %>% distinct(sampleid) %>% nrow
```


```{r}
# the data from jonas lab people
them <- read_csv('../data/sum of sugar intake vs max zscore family(E,E).csv') %>% 
  select(sampleid, samplebin, iRep, genus, p1d_Sweets, p2d_Sweets,p1d_Fruits, p2d_Fruits, iRep_zscore, pid, sum_sugar) %>% 
  filter(!is.na(sum_sugar)) %>% 
  mutate(sum_fruits = p1d_Fruits + p2d_Fruits,
         sum_sweets = p1d_Sweets + p2d_Sweets)
 
all <- bind_rows(them, family2) %>% 
  filter(!is.na(sum_sugar))

ave_fruit <- them %>% 
  mutate(ave_fruit = sum_fruits/2) %>% 
  ggpubr::ggscatter(x = 'ave_fruit', y = 'iRep_zscore',  color = 'genus',palette = 'lancet',
                    xlab = 'Fruits intake averaged',
                    ylab = 'Growth rate\n(standardized within genus) ',
                    add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n", label.x.npc = "left")) +
  theme(aspect.ratio = 1,
        legend.position = 'none',
        legend.title=element_blank())

ave_sweets <- them %>% 
  mutate(ave_sweets = sum_sweets/2) %>% 
  ggpubr::ggscatter(x = 'ave_sweets', y = 'iRep_zscore',  color = 'genus',palette = 'lancet',
                    xlab = 'Sweets intake averaged',
                    ylab = 'Growth rate\n(standardized within genus) ',
                    add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n", label.x.npc = "left")) +
  theme(aspect.ratio = 1,
        legend.position = 'none',
        legend.title=element_blank())

axis_text_size <- 10
axis_title_size <- 10
```

```{r}
# adding the new samples
# all_fam2_irep %>% 
#   ggpubr::ggscatter(x = 'sum_sugar', y = 'iRep_zscore',  color = 'genus',palette = 'lancet',
#                     add = "reg.line",  # Add regressin line
#            add.params = list(color = "blue", fill = "lightgray"), # Customize line
#            conf.int = TRUE, # Add confidence interval
#            cor.coef = TRUE, # Add correlation coefficient.
#            cor.coeff.args = list(method = "spearman",  label.sep = "\n", label.x.npc = "left"))
```
 
```{r}
# the gvhd info
clinical <- read_csv('../data/156_transplant_data.csv') 
count(clinical$d100_a_gvhd)
colnames(clinical)

META <- read_csv('../data/153_combined_META.csv') %>% 
  select(sampleid, mrn, sdrt) %>% 
  left_join(shotgun_lookup_ad %>% distinct(sampleid, .keep_all = T) %>% select(sampleid, projectid)) %>% 
  filter(sdrt %in% -10:30) %>% 
  inner_join(clinical %>% select(mrn, d100_a_gvhd:d100_przepiorka_highest_overall_grade))

META %>% write_csv('../data/123_stool_samples.csv')

read_csv('../data/153_combined_META.csv') %>% 
  distinct(mrn) %>% 
  write_csv('../data/123_patients_stools_with_nutrition_intake_in_prior_2_day_window.csv')
```

