---
title: "weighted decaying"
author: "Angel"
date: "2022-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
  
```{r}
library(tidyverse)
library(ggpubr)
library(vegan)
```

```{r}
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')

stb <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')
```
```{r}
pt_fdrt <- dtb %>% 
  distinct(mrn, fdrt)

stb_loop <- stb %>%  
  select(mrn, sdrt) %>% 
  transmute(mrn = mrn,
            p1d = sdrt-1,
            p2d = sdrt-2, 
            p3d = sdrt-3,
            p4d = sdrt-4) 
 
check_p4d_diet <-  function(mrn_, p1d_, p2d_, p3d_, p4d_){
  num = pt_fdrt %>% 
    filter(mrn == mrn_) %>% 
    filter(fdrt %in% c(p1d_, p2d_ ,p3d_, p4d_)) %>% 
    nrow()
  return(num)
}

check_p4d_diet_df <- pmap(stb_loop, function(mrn, p1d, p2d, p3d, p4d){
    check_p4d_diet(mrn, p1d, p2d, p3d, p4d)
  }) %>% 
  set_names(stb %>% pull(sampleid)) %>% 
  bind_rows() %>% 
  gather('sampleid', 'pNd_num') 

# how many samples have all previous 4 days diet
p4d_samples <- check_p4d_diet_df %>% 
  filter(pNd_num == 4) 
p4d_samples %>% 
  nrow
```

In my very rudimentary understanding of this method, we would account for the 4 days prior to the stool sample. So, yes, we would need all 4 days of viable diet data per stool sample (this is not always possible, as we know).

From that, we would take: 100% dry weight from day-1, 50% dry weight from day-2, 25% dry weight from day-3, 12.5% dry weight day-4.

```{r}
stb_loop_sum <- stb %>%  
  filter(sampleid %in% p4d_samples$sampleid) %>% 
  mutate(p1d = sdrt-1,
            p2d = sdrt-2, 
            p3d = sdrt-3,
            p4d = sdrt-4)

dm1 <- apply(stb_loop_sum, 1, function(Row){
  df = dtb %>%   
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['p1d']])) %>% 
        group_by(Food_code) %>% 
        summarise(total_dewt = sum(dehydrated_weight)) %>% 
        mutate(proportion_weight = total_dewt * 1)
}) %>% 
  set_names(stb_loop_sum %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') 

dm2 <- apply(stb_loop_sum, 1, function(Row){
  df = dtb %>%   
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['p2d']])) %>% 
        group_by(Food_code) %>% 
        summarise(total_dewt = sum(dehydrated_weight) ) %>% 
        mutate(proportion_weight = total_dewt * 0.5)
}) %>% 
  set_names(stb_loop_sum %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') 

dm3 <- apply(stb_loop_sum, 1, function(Row){
  df = dtb %>%   
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['p3d']])) %>% 
        group_by(Food_code) %>% 
        summarise(total_dewt = sum(dehydrated_weight) ) %>% 
        mutate(proportion_weight = total_dewt * 0.25)
}) %>% 
  set_names(stb_loop_sum %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') 

dm4 <- apply(stb_loop_sum, 1, function(Row){
  df = dtb %>%   
        filter(mrn == Row[['mrn']]) %>% 
        filter(fdrt %in% c(Row[['p4d']])) %>% 
        group_by(Food_code) %>% 
        summarise(total_dewt = sum(dehydrated_weight) ) %>% 
        mutate(proportion_weight = total_dewt * 0.125)
}) %>% 
  set_names(stb_loop_sum %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') 

total_proportion <- bind_rows(dm1, dm2, dm3, dm4) %>% 
  group_by(sampleid, Food_code) %>% 
  summarise(weighted_wt = sum(proportion_weight)) %>% 
  spread(key = 'sampleid', value = 'weighted_wt', fill = 0)  

total_proportion %>% 
  write_tsv('../data/finalized/paired/pNday/allstool_weighted_diet_foodID_dehydrated_weight_per_pt.tsv')
dm4 %>% distinct(sampleid)
```

```{r}
cts_p4d <- read_csv('../data/cleaned_stool/022_ALL_stool_samples_genus_counts.csv') %>% 
  filter(sampleid %in% p4d_samples$sampleid)  %>% 
  spread('sampleid', 'relab', fill = 0)

cts_p4d %>% 
  write_tsv('../data/finalized/paired/pNday/allstool_weighted_stool_relab_species.tsv')

```

```{r}
# after snakemake 
fns_both <- tibble(
  sfn = '/Users/daia1/Work/projects/MSS_pipeline-/scripts/food_tree/data/finalized/paired/pNday/allstool_weighted_stool_relab_species_braycurtis_pcoa/ordination.txt',
  dfn = '/Users/daia1/Work/projects/MSS_pipeline-/scripts/food_tree/data/finalized/paired/pNday/allstool_weighted_diet_foodID_dehydrated_weight_per_pt_unweighted_unifrac_pcoa/ordination.txt')

sdf <- read_tsv(fns_both$sfn, skip = 9, col_names = F)  %>% 
    filter(! X1 %in% c('Biplot','Site constraints')) %>% 
    column_to_rownames('X1')

ddf <- read_tsv(fns_both$dfn, skip = 9, col_names = F)  %>% 
    filter(! X1 %in% c('Biplot','Site constraints')) %>% 
    column_to_rownames('X1')

procrustes_weighted <- map2_dfc(fns_both$dfn, fns_both$sfn, function(dfn, sfn){
  dpcoa = read_tsv(dfn, skip = 9, col_names = F)  %>% 
    filter(! X1 %in% c('Biplot','Site constraints')) %>% 
    column_to_rownames('X1') %>% 
    as.matrix()
  
  spcoa = read_tsv(sfn, skip = 9, col_names = F)  %>% 
    filter(! X1 %in% c('Biplot','Site constraints')) %>% 
    column_to_rownames('X1') %>% 
    as.matrix()
  
  procrustes_res = vegan::procrustes(X = dpcoa, Y = spcoa)
  return( procrustes_res$ss)
}) %>% 
  gather(key = 'pNd', value = 'ss') %>% 
  mutate(pNd = fns_both$ID)
```