---
title: "Batch 2 new 76 patients"
author: "Angel"
date: "2022-11-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(vdbR)
library(lubridate)
connect_database()
get_table_from_database()
```

```{r}
# the table from John that is the pull of the new patients clinical info
newdtb <- read_csv('../data/127_new_pt.csv')

pts <- read_csv('../data/127_new_pt.csv') %>% 
  distinct(mrn) 

pull <- read_csv('../data/pts_updated_through_june_2022.csv') %>% 
  inner_join(pts, by = c('MRN' = 'mrn')) %>% 
  # convert the hct date to date
  mutate(HCT = dmy(HCT)) %>% 
  arrange(MRN, desc(HCT)) %>%
  # two patients that had two hct, chose the one that is closest to now
  distinct(MRN, .keep_all = T) %>% 
  rename_with(tolower) %>% 
  rename_all(~ gsub(" ", "_", .))

pull %>% write_csv('../data/129_new_76_full_patient_info.csv')
pull %>% distinct(Disease) 

new <- read_csv('../data/129_new_76_full_patient_info.csv')
```

```{r}
# Collapse MSKCC messy diseases into broad, simplified categories

disim <- pull %>% 
  mutate(disease.simple = case_when(
    disease == "Leukemia" & sub_hist == "Acute" & sub_sub_hist == "Myelogenous" ~ 'AML',
    disease == "Leukemia" & sub_hist == "Acute" &sub_sub_hist == "Lymphoblastic" ~ "ALL",
    disease == "Leukemia" & sub_hist == "Chronic" & sub_sub_hist == "Myelogenous" ~ "CML",
    disease == "Leukemia" & sub_hist == "Chronic" & sub_sub_hist == "Myelomonocytic" ~ "MDS/MPN",
    disease == "Leukemia (Second Primary)" & sub_hist == "Acute" & sub_sub_hist == "Myelogenous" ~ "AML",
    disease == "Leukemia" & sub_hist == "Acute" & sub_sub_hist == "Monoblastic" | sub_sub_hist == "Monocytic" | sub_sub_hist == "Myelomonocytic" | sub_sub_hist =="Promyelocytic" ~ "AML",
    str_detect(disease, 'Aplastic') ~ "AA",
    str_detect(sub_hist, 'Aplastic') ~ "AA",
    str_detect(disease, 'Myelodysplastic|Myeloproliferative') ~ "MDS/MPN",
    str_detect(disease, 'Non-Hodgkin') ~ "NHL",
    str_detect(disease, 'Myeloma') ~ "Myeloma",
    str_detect(disease, "Hodgkin's Disease") ~ "Hodgkins",
    str_detect(sub_sub_hist, 'CLL') ~ "CLL",
    str_detect(sub_sub_hist, 'Prolymphocytic') ~ "NHL",
    str_detect(sub_sub_hist, 'Biphenotypic|Plasmacytoid Dendritic|Ambiguous|NK-LGL') ~ "other",
    str_detect(disease, 'Non-Malignant Hemat Disorders') ~ "other"
  ))

# the NA ones 
need_clean <- disim %>% 
  filter(is.na(disease.simple))
colnames(disim)
```

```{r}
ptb_n <- disim %>% 
  select(mrn, source , intensity, hct, age, sex, disease.simple) %>%  
  mutate(source = if_else(str_detect(source, 'Cord' ), 
                             'cord',
                             if_else(str_detect(source, 'SBA|CD34'), 
                                     'TCD',
                                     'unmodified'))) %>% 
  mutate(intensity = if_else(intensity %in% c('Ablative','ABLATIVE'), 'ablative',
                                         if_else(intensity %in% c('NONABL','Nonablative'), 'nonablative','reduced'))) %>% 
  mutate(disease.simple = if_else(is.na(disease.simple), 'AML', disease.simple))
```

```{r}
library(gtsummary)  
ptb_n %>% distinct(disease.simple)
final <- ptb_n %>% 
  select(age, sex, Disease = disease.simple, source,  intensity) %>% 
  mutate(Disease = case_when(
    Disease == 'NHL' ~ "Non-Hodgkin's lymphoma",
    # Myelodysplastic/myeloproliferative neoplasms
    Disease == 'MDS/MPN' ~ 'MDS/MPN',
    Disease == 'AML' ~ 'Acute myeloid leukemia',
    Disease == 'ALL' ~ 'Acute lymphoid leukemia',
    Disease == 'CLL' ~ 'Chronic lymphocytic leukemia',
    Disease == 'CML' ~ 'Other',
    Disease == 'Hodgkins' ~ "Other",
    Disease == 'Myeloma' ~ 'Myeloma', 
    Disease == 'AA' ~ 'Other'
  )) %>% 
  mutate(source = case_when(
    source == 'unmodified' ~ "Unmodified bone marrow or PBSC",
    source == 'cord' ~ "Cord blood",
    source == 'TCD' ~ "T-cell depleted PBSC"
  )) %>% 
  mutate(intensity = case_when(
    intensity == 'nonablative' ~ "Nonmyeloablative",
    intensity == 'ablative' ~ "Ablative",
    intensity == 'reduced' ~ "Reduced intensity"
  )) %>% 
  mutate(intensity = fct_reorder(intensity, intensity, .fun=length, .desc = T),
         source = fct_reorder(source, source, .fun=length, .desc = T),
         Disease = fct_reorder(Disease, Disease, .fun=length, .desc = T),
         sex = fct_reorder(sex, sex, .fun=length, .desc = T)) %>% 
  rename(`Graft type` = source, 
         #`HCT-CI` = ci,
         `Intensity of conditioning regimen` = intensity ) 

final %>% 
  tbl_summary(
    #type = list(all_integer() ~ "continuous"), 
    statistic = list(all_continuous() ~ "{mean} ({sd})")
  ) %>%
  bold_labels() %>% 
  as_gt() %>%
  #gt::tab_footnote(footnote = "MDS/MPN = Myelodysplastic/myeloproliferative neoplasms") %>% 
  gt::gtsave(filename = "../figs/paper/129_table_1_patient_summary.pdf")


```

