---
title: "Compile the most comprehensive meta pheno table for diet!!!"
output: html_document
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

Create a comprehensive meta data table so that I can qiime view 

# this meta table has dietID as for each row, a diet record for each patient on one specific day

## add faith results and transplant info

```{r}
#create a diet sample ID like the our usual sample id that combines the info of the mrn and the day
# the dietID gonna be my sampleid

# use the food id instead of the main food description which is a long string
final <- read_csv('../data/finalized/all_patients_record_w_food_code.csv')

# create fake ID number for patient mrn
link <- final %>% distinct(mrn) %>% 
  mutate(pt = str_pad(seq(1, nrow(.)), width = 3, side = 'left',pad = '0')) %>% 
  mutate(pt = str_glue('Pt{pt}'))

final <- final %>% 
  left_join(link, by  = 'mrn') %>% 
  mutate(DayRT = as.character(DayRT)) %>% 
  mutate(DayRT = str_replace(DayRT, '-','_')) %>% 
  mutate(dietID = str_glue('{pt}d{DayRT}')) 

# the table that has key transplant information
pheno <- read_csv('../data/pheno/final_pheno.csv')


# get the faith for each diet sample
faith <- read_csv('../data/finalized/alpha_faith_daily_all.csv') %>% 
  left_join(link, by = 'mrn') %>% 
  mutate(DayRT = as.character(DayRT)) %>% 
  mutate(DayRT = str_replace(DayRT, '-','_')) %>% 
  mutate(dietID = str_glue('{pt}d{DayRT}')) 

# get the EN TPN info for the patients
en <- read_csv('../data/finalized/TPN_EN_all.csv') %>% 
  # just color by the mrn that is either en or tpn
  distinct(mrn, type) %>% 
  distinct(mrn, .keep_all = T)

tpns <- en %>% 
  filter(type == 'TPN') %>% 
  pull(mrn)

ens <- en %>% 
  filter(type == 'EN') %>% 
  pull(mrn)
```

```{r}
# join them together
meta <- final %>% 
  distinct(dietID, mrn, DayRT) %>% 
  left_join(pheno, by  = 'mrn') %>% 
  full_join(faith %>% 
              select(dietID, faith_pd), by = 'dietID') %>% 
  # change the first column name to work on qiime
  rename(`#SampleID` = names(.)[1]) %>% 
  rename(foodDayRT = DayRT) %>% 
  # change back the foodDayRT to be numeric
  mutate(foodDayRT = str_replace(foodDayRT,'_','-')) %>% 
  mutate(foodDayRT = as.numeric(foodDayRT)) %>% 
  mutate(entronutri = if_else(mrn %in% ens, "EN", 
                              if_else(mrn %in% tpns, "TPN", 'none')))
```

## add nutrition and demographic info

```{r}
# the current nutritional info that we have
source('~/db_connect_simple.R')
connect_database(config_file = '~/dbConfig.txt')
dbListTables(con) %>% data.frame() %>% filter(grepl('nutri',.))
nutri <- get_table_from_database('nutrition_ag')
demogr <- get_table_from_database('nutrition_demographics_ag')

# the info from this table that I wanna integrate into my meta
demo <- demogr %>% 
  select(mrn, sex, age_at_hsct, admit_bmi) %>% 
  filter(mrn %in% meta$mrn)

demo %>% 
  summary

demo %>% 
  count(sex)


meta <- meta %>% 
  left_join(demo , by = 'mrn')
```

## add food group info

```{r}
# load the food group table 
fgroup <- read_csv('../data/finalized/all_diet_sample_with_food_group_info.csv')

group_desc <- fgroup %>% 
  distinct(food_grp, Main.food.description) %>% 
  arrange(food_grp)
```
```{r}
# in every diet sample how the food group is being consumed
fgroup %>% 
  count(mrn, DayRT, food_grp, Main.food.description)  %>% 
  count(food_grp, Main.food.description) %>% 
  arrange(desc(n))
```


```{r}
# to make a table of abs value and perc of each food group for each diet sample
fgroup_meta <- fgroup %>% 
  mutate(simplegroup = case_when(
    food_grp == 1 ~ 'milk',
    food_grp == 2 ~ 'meat',
    food_grp == 3 ~ 'egg',
    food_grp == 4 ~ 'legume',
    food_grp == 5 ~ 'grain',
    food_grp == 6 ~ 'fruit',
    food_grp == 7 ~ 'veggie',
    food_grp == 8 ~ 'fats',
    food_grp == 9 ~ 'sugar',
  )) %>% 
  select(mrn, DayRT, food_grp, grp_tol, grp_relab, simplegroup) %>% 
  # create the diet id
  left_join(link, by  = 'mrn') %>% 
  mutate(DayRT = as.character(DayRT)) %>% 
  mutate(DayRT = str_replace(DayRT, '-','_')) %>% 
  mutate(dietID = str_glue('{pt}d{DayRT}')) %>% 
  select(-mrn, -DayRT, -food_grp, -pt) 
  
fgroup_meta_total <-  fgroup_meta %>% 
  select(-grp_relab) %>% 
  spread(key = 'simplegroup', value = 'grp_tol', fill = 0) %>% 
  rename_all(paste0, "_total") %>% 
  rename(dietID = dietID_total)

fgroup_meta_perc <-  fgroup_meta %>% 
  select(-grp_tol) %>% 
  spread(key = 'simplegroup', value = 'grp_relab', fill = 0) %>% 
  rename_all(paste0, "_perc") %>% 
  rename(dietID = dietID_perc)

# combine the above two to make a single df
fgroup_both <- fgroup_meta_total %>% 
  full_join(fgroup_meta_perc, by = 'dietID')

meta <- meta %>% 
  full_join(fgroup_both %>% rename(`#SampleID` = dietID),  by = '#SampleID')
```

```{r}
# the nutrients (macronutrients and micronutrients)
nutrients_grp <- read_csv('../data/finalized/all_diet_sample_with_nutrients_info.csv')

nutrients_grp %>% 
  count(mrn, DayRT, nutrient)  %>% 
  count(nutrient) %>% 
  arrange(desc(n))


```

```{r}
nutrients_meta <- nutrients_grp %>% 
  select(mrn, DayRT, nutrient, nutrient_tol_day, nut_relab) %>% 
  # create the diet id
  left_join(link, by  = 'mrn') %>% 
  mutate(DayRT = as.character(DayRT)) %>% 
  mutate(DayRT = str_replace(DayRT, '-','_')) %>% 
  mutate(dietID = str_glue('{pt}d{DayRT}')) %>% 
  select(-mrn, -DayRT,  -pt) 
  
nutrients_meta_total <-  nutrients_meta %>% 
  select(-nut_relab) %>% 
  spread(key = 'nutrient', value = 'nutrient_tol_day', fill = 0) %>% 
  rename_all(paste0, "_total") %>% 
  rename(dietID = dietID_total)

nutrients_meta_perc <-  nutrients_meta %>% 
  select(-nutrient_tol_day) %>% 
  spread(key = 'nutrient', value = 'nut_relab', fill = 0) %>% 
  rename_all(paste0, "_perc") %>% 
  rename(dietID = dietID_perc)

# combine the above two to make a single df
nutrients_both <- nutrients_meta_total %>% 
  full_join(nutrients_meta_perc, by = 'dietID') %>% 
  rename(`#SampleID` = dietID)

# the missing 5 samples are cuz the patients are very ill and didn't eat anything probably
meta %>% 
  filter(!`#SampleID` %in% nutrients_both$`#SampleID`)


meta <- meta %>% 
  full_join(nutrients_both,  by = '#SampleID')


summary(meta$Fibers_total)

meta <- meta %>% 
  # remove PHI columns
  select(-indication, -onset) %>% 
  rename(sampleid = `#SampleID`) 
  # deidentify the mrn, could use part of the dietID
  #mutate(mrn = str_extract(sampleid, pattern = '^Pt...'))

```

```{r}
# write out deid version
meta  %>% 
  mutate(PID = as.numeric(as.factor(mrn))) %>% 
  mutate(PID = str_glue("P{str_pad(PID, 3, 'left', '0')}")) %>% 
  write_tsv('../data/finalized/meta_data_67.tsv')
```
