---
title: "The other patients for the figure 3 supplementary"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
axis_text_size <- 11
axis_title_size <- 11
plot_ratio <-1.5/2
shorter_ratio <- 1/2
library(tidyverse)
library(ggpubr)
library(vdbR)
library(cowplot)
connect_database('~/dbConfig.txt')
get_table_from_database('qpcr_16s_ag')
get_table_from_database('antibiotics_antibacterial_multicenter_ag')
get_table_from_database('samples_castori_ag')
get_table_from_database('asv_annotation_blast_ag')
all802 <- read_csv('../data/011_802_total_stool_samples.csv')
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
ptb <- read_csv('../data/cleaned_patients/diet_patients_97.csv')

updated_qPCR <- qpcr_16s_ag %>%
  rename(sampleid=sample_id,
         copies_16s_per_g_pre = copies_16s_per_g) %>% 
  mutate(
    g = copy_number_16s/ copies_16s_per_g_pre,
    copies_16s_bounded = ifelse(
      copy_number_16s < 12800, 
      (12800*.5),
      ifelse(
        copy_number_16s > 2e8,
        1.5 * (2e8),
        copy_number_16s
      )
    )
  ) %>% 
  mutate(copies_16s_per_g =  copies_16s_bounded/g) 
```

We need timelines for each of the selected patients here, like in figure 3A,B. Each time, for the growth rate and total abundance data, use the genus with the highest irep, as per figure 3c

```{r}
# find the genus with the highest irep for the other patients

# the below is the version where there might be missing diet data the original 802 samples and also all of the irep values I've got 
combined <- read_csv('../data/114_combined_irep_915.csv')


meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')
meta <- read_csv('/Volumes/vandenBrinkLab/Angel_Dai/Nutrition_project/data/all_samples_meta_p2d_fg9_updated.csv')
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc') %>% 
  select(fg = fg1_name,shortname )
scatter_alpha <- 0.35
cor_text_size <- 3
axis_text_size <- 11
axis_title_size <- 11

klept <- read_csv('../data/095_Klebsiella-patient.csv')
ent_pt <- read_csv('../data/075_entero_pt.csv')
missing <- read_csv('../data/114_timeline_2_pt_check_missing_6__PP_check.csv')
```

```{r}
# the 12 patients that I have both the irep and the qpcr
both <- read_csv('../data/133_patients_with_both_irep_and_qpcr.csv')

# # find the other patients that don't make it to the fig3 top (10)
target <- both %>% 
  filter(! value %in% c(klept$mrn, ent_pt$mrn))

# find the genus with the highest irep for those patients
irep <- combined %>% 
  filter(mrn %in% target$value)

# find the genus of those species
all_spp <- irep %>% 
  distinct(best_species) %>% 
  mutate(cleaned_spp = str_replace(best_species, '\\[',''),
         cleaned_spp = str_replace(cleaned_spp, '\\]','')) %>% 
  mutate(best_genus = str_extract(cleaned_spp, "[^\\s]+")) %>% 
  filter(!best_genus %in% c('Bacteria','Lachnospiraceae'))

growall <- irep %>% 
  inner_join(all_spp %>% select(best_species, best_genus))

df <- growall %>% distinct(best_genus) 

# find the genus with the highest irep for those patients that are within the 4 genera
max_genus <- growall %>% 
  filter(best_genus %in% c('Enterobacter','Escherichia','Klebsiella','Enterococcus')) %>% 
  arrange(mrn, desc(iRep)) %>% 
  group_by(mrn) %>% 
  slice(1) %>% 
  select(mrn, best_genus, iRep)

ids <- max_genus %>% 
  mutate(pid = as.factor(mrn)) %>% 
  mutate(pid = as.numeric(pid)) %>% 
  mutate(pid = as.character(pid)) %>% 
  mutate(pid = str_glue('P{pid}')) 
```
```{r}
pt_df <- max_genus %>% ungroup() %>% 
  slice(3) 

pt <- pt_df %>% pull(mrn)
ge <- pt_df %>% pull(best_genus)
mrn_ <- pt
```

```{r}
# plot the sweets and fruits intake data
# the population data about daily sweets consumption and fruits and eggs comsumption
all9 <- dtb %>%  
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^9')) %>% 
  group_by(mrn, fdrt) %>% 
  summarise(sweetdaily = sum(dehydrated_weight))

s_q25 <- quantile(x = all9$sweetdaily, 0.25)
s_q50 <- quantile(x = all9$sweetdaily, 0.5)
s_q75 <- quantile(x = all9$sweetdaily, 0.75)
highest_daily_sweet_intake <- ceiling( max(all9$sweetdaily))
lowest_daily_sweet_intake <- floor( min(all9$sweetdaily))

# fruits
all6 <- dtb %>%  
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^6')) %>% 
  group_by(mrn, fdrt) %>% 
  summarise(fruitdaily = sum(dehydrated_weight))

f_q25 <- quantile(x = all6$fruitdaily, 0.25)
f_q50 <- quantile(x = all6$fruitdaily, 0.5)
f_q75 <- quantile(x = all6$fruitdaily, 0.75)
highest_daily_fruit_intake <- ceiling( max(all6$fruitdaily))
lowest_daily_fruit_intake <- floor( min(all6$fruitdaily))
```
```{r}
each_pt_sweets <- dtb %>%  
  filter(mrn == mrn_ & fdrt %in% -10:20) %>% 
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^9')) %>% 
  group_by(fdrt) %>% 
  summarise(sweetsum = sum(dehydrated_weight)) %>% 
  mutate(p_size  = if_else(sweetsum > s_q75, 3, 1)) 

sweets_panel <- each_pt_sweets %>%    
  ggplot(aes(x = fdrt, y = sweetsum )) +
  annotate('rect', xmin = xmin, xmax = xmax, ymin = s_q25, ymax = s_q75, fill='gray',  alpha=0.3) +
  geom_line(aes(x = fdrt, y = sweetsum), linetype = 'solid', size = 0.5, col = 'black') +
  geom_point(aes(size = sweetsum > s_q75, col = sweetsum > s_q75)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  xlim(xmin, xmax) +
  labs(x = '',
       y = 'Sweets(g)',
       title = '') +
  theme_classic() + 
  #ylim(0, max(p11_sweets$sweetsum))+
  theme(aspect.ratio=shorter_ratio, legend.position = 'none' ,
        axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        plot.margin = margin(l=-0.8,unit="cm"),
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(colour = "grey85"))

each_pt_fruits <- dtb %>%  
  filter(mrn == mrn_ & fdrt %in% lowerday:higherday) %>% 
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^6')) %>% 
  group_by(fdrt) %>% 
  summarise(fruitsum = sum(dehydrated_weight)) %>% 
  mutate(p_size  = if_else(fruitsum > f_q75, 3, 1)) 

fruits_panel <- each_pt_fruits %>%    
  ggplot(aes(x = fdrt, y = fruitsum )) +
  annotate('rect', xmin = xmin, xmax = xmax, ymin = f_q25, ymax = f_q75, fill='gray',  alpha=0.3) +
  geom_line(aes(x = fdrt, y = fruitsum), linetype = 'solid', size = 0.5, col = 'black') +
  geom_point(aes(size = fruitsum > f_q75, col = fruitsum > f_q75)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  xlim(xmin, xmax) +
  labs(x = '',
       y = 'Fruits(g)',
       title = '') +
  theme_classic() + 
  #ylim(0, max(p11_fruits$fruitsum))+
  theme(aspect.ratio=shorter_ratio, legend.position = 'none' ,
        axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        plot.margin = margin(l=-0.8,unit="cm"),
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(colour = "grey85"))

```

```{r}
# plot the total abundance data 
sam <- samples_castori_ag %>% 
  filter(mrn %in% pt) %>% 
  distinct(sampleid) %>% 
  pull(sampleid)

samps <- samples_castori_ag %>% 
  filter(mrn %in% pt) %>% 
  distinct(sampleid, mrn)

cts <- get_counts_subset(sam)

cts_ge_df <- cts %>% 
  left_join(asv_annotation_blast_ag %>% 
              select(asv_key, genus)) %>% 
  group_by(sampleid, genus) %>% 
  summarise(relab = sum(count_relative)) %>%
  spread('sampleid', 'relab', fill = 0) %>% 
  filter(genus == ge) %>% 
  gather('sampleid', 'relab', names(.)[2]:names(.)[ncol(.)]) %>% 
  inner_join(updated_qPCR %>% 
               select(sampleid , copies_16s_per_g)) %>% 
  mutate(ge_copy = copies_16s_per_g*relab) %>% 
  inner_join(samples_castori_ag %>% 
               select(sampleid, datecollection)) %>% 
  inner_join(samps) %>% 
  inner_join(ptb %>% 
               select(mrn, hct)) %>% 
  mutate(sdrt = datecollection - hct) %>% 
  filter(!is.na(ge_copy))

cts_ge <- cts_ge_df %>% 
  mutate(max_pt = if_else(ge_copy == max(cts_ge_df$ge_copy), T, F))

# find the samples that have zero relab in this genus


ge_copies <- cts_ge %>% 
  #filter(sdrt %in% -5:15) %>% 
  #mutate(ge_copy = ge_copy/1e7) %>% 
  ggplot(aes(x = sdrt, y = ge_copy )) +
  geom_line(aes(x = sdrt, y = ge_copy), linetype = 'solid', size = 0.5, col = 'black') +
  geom_point(aes(size = max_pt, col = max_pt)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  #xlim(xmin, xmax) +
  labs(x = 'Transplant day',
       y = str_glue('{ge}\ncopies /g'),
       title = '') +  
  theme_classic() +
  theme(aspect.ratio=shorter_ratio,legend.position = 'none',
        plot.margin = margin(l=-0.8,unit="cm"),
            axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(colour = "grey85"))

# plot the irep and total abundance data for those patients for the genus with the highest irep value

# irep
ge_irep_all <- irep %>%  
  filter(str_detect(best_species, ge)) %>% 
  inner_join(all802 %>% 
               select(sampleid, sdrt))
ge_irep_q25 <- quantile(x = ge_irep_all$iRep, 0.25)
ge_irep_q50 <- quantile(x = ge_irep_all$iRep, 0.5)
ge_irep_q75 <- quantile(x = ge_irep_all$iRep, 0.75)
ge_irep_highest <- max(ge_irep_all$iRep) + 0.05

ge_irep_pt <- irep %>% 
  filter(mrn == pt & str_detect(best_species, ge))
lowerday <- min(ge_irep_pt$sdrt)
highday <- max(ge_irep_pt$sdrt)
xmin <- lowerday - 1 
xmax <- highday + 1  


ge_irep <-  ge_irep_all %>% 
  #filter(sdrt %in% -5:15) %>% 
  filter(mrn == pt) %>%
  ggplot(aes(x = sdrt, y = iRep )) +
  annotate('rect', xmin = xmin, xmax = xmax, ymin = ge_irep_q25, ymax = ge_irep_q75, fill='gray',  alpha=0.3) +
  geom_point(aes(size = iRep > ge_irep_q75, col = iRep > ge_irep_q75)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  labs(title = str_glue('{}')) +
  #xlim(xmin, xmax) +
  ylim(1, ge_irep_highest) +
  labs(x = '', 
       y = str_glue('{ge}\ngrowth rate'),
       title = '')+
  theme_classic()+
  theme(aspect.ratio=shorter_ratio, legend.position = 'none' ,
        #axis.text.x=element_blank(),
        #axis.ticks.x=element_blank(),
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(color = "grey85"))
ge_irep

bottom2 <-  plot_grid(ge_irep, ge_copies, 
                  ncol = 1,axis = 'lbrt', align = 'hv') 

```

```{r}
# do this for all of the 10 patients
plot_all4 <- function(mrn_, genus_){
  
 # for the sake of xmin and xmax 
  
    # irep
ge_irep_all <- irep %>%  
  filter(str_detect(best_species, genus_)) %>% 
  inner_join(all802 %>% 
               select(sampleid, sdrt))
ge_irep_q25 <- quantile(x = ge_irep_all$iRep, 0.25)
ge_irep_q50 <- quantile(x = ge_irep_all$iRep, 0.5)
ge_irep_q75 <- quantile(x = ge_irep_all$iRep, 0.75)
ge_irep_highest <- max(ge_irep_all$iRep) + 0.05

ge_irep <- irep %>%   
  filter(mrn == mrn_ & str_detect(best_species, genus_))
lowerday_irep <- min(ge_irep$sdrt)
higherday_irep <- max(ge_irep$sdrt)
  
  # cts of the 16s
sam <- samples_castori_ag %>% 
  filter(mrn %in% mrn_) %>% 
  distinct(sampleid) %>% 
  pull(sampleid)

samps <- samples_castori_ag %>% 
  filter(mrn %in% mrn_) %>% 
  distinct(sampleid, mrn)

cts <- get_counts_subset(sam)

cts_ge_df <- cts %>% 
  left_join(asv_annotation_blast_ag %>% 
              select(asv_key, genus)) %>% 
  group_by(sampleid, genus) %>% 
  summarise(relab = sum(count_relative)) %>%
  spread('sampleid', 'relab', fill = 0) %>% 
   filter(genus == genus_) %>% 
  gather('sampleid', 'relab', names(.)[2]:names(.)[ncol(.)]) %>% 
  inner_join(updated_qPCR %>% 
               select(sampleid , copies_16s_per_g)) %>% 
  mutate(ge_copy = copies_16s_per_g*relab) %>% 
  inner_join(samples_castori_ag %>% 
               select(sampleid, datecollection)) %>% 
  inner_join(samps) %>% 
  inner_join(ptb %>% 
               select(mrn, hct)) %>% 
  mutate(sdrt = datecollection - hct) %>% 
  filter(!is.na(ge_copy)) %>% 
  mutate(sdrt = as.numeric(sdrt))

lowerday_cts <- min(cts_ge_df$sdrt)
higherday_cts <- max(cts_ge_df$sdrt)
lowerday <- min(lowerday_cts, lowerday_irep)
higherday <- max(higherday_cts, higherday_irep)
xmin <- lowerday - 1 
xmax <- higherday + 1  
  
  # sweets and fruits
  each_pt_sweets <- dtb %>%  
  filter(mrn == mrn_ & fdrt %in% lowerday:higherday) %>% 
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^9')) %>% 
  group_by(fdrt) %>% 
  summarise(sweetsum = sum(dehydrated_weight)) %>% 
  mutate(p_size  = if_else(sweetsum > s_q75, 3, 1)) 

sweets_panel <- each_pt_sweets %>%    
  ggplot(aes(x = fdrt, y = sweetsum )) +
  annotate('rect', xmin = xmin, xmax = xmax, ymin = s_q25, ymax = s_q75, fill='gray',  alpha=0.3) +
  geom_line(aes(x = fdrt, y = sweetsum), linetype = 'solid', size = 0.5, col = 'black') +
  geom_point(aes(size = sweetsum > s_q75, col = sweetsum > s_q75)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  xlim(xmin, xmax) +
  labs(x = '',
       y = 'Sweets(g)', 
       title = '') +
  theme_classic() + 
  #ylim(0, max(p11_sweets$sweetsum))+
  theme(aspect.ratio=shorter_ratio, legend.position = 'none' ,
        #axis.ticks.x=element_blank(),
        #axis.text.x=element_blank(),
        plot.margin = margin(l=-0.8,unit="cm"),
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(colour = "grey85"))

each_pt_fruits <- dtb %>%  
  filter(mrn == mrn_ & fdrt %in% lowerday:higherday) %>% 
  mutate(Food_code = as.character(Food_code) ) %>% 
  filter(str_detect(Food_code, '^6')) %>% 
  group_by(fdrt) %>% 
  summarise(fruitsum = sum(dehydrated_weight)) %>% 
  mutate(p_size  = if_else(fruitsum > f_q75, 3, 1)) 

fruits_panel <- each_pt_fruits %>%    
  ggplot(aes(x = fdrt, y = fruitsum )) +
  annotate('rect', xmin = xmin, xmax = xmax, ymin = f_q25, ymax = f_q75, fill='gray',  alpha=0.3) +
  geom_line(aes(x = fdrt, y = fruitsum), linetype = 'solid', size = 0.5, col = 'black') +
  geom_point(aes(size = fruitsum > f_q75, col = fruitsum > f_q75)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  xlim(xmin, xmax) +
  labs(x = '',
       y = 'Fruits(g)',
       title = '') +
  theme_classic() + 
  #ylim(0, max(p11_fruits$fruitsum))+
  theme(aspect.ratio=shorter_ratio, legend.position = 'none' ,
        #axis.ticks.x=element_blank(),
        #axis.text.x=element_blank(),
        plot.margin = margin(l=-0.8,unit="cm"),
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(colour = "grey85"))
  # plot the total abundance data 
  






cts_ge <- cts_ge_df %>% 
  mutate(max_pt = if_else(ge_copy == max(cts_ge_df$ge_copy), T, F))

# find the samples that have zero relab in this genus


ge_copies <- cts_ge %>% 
  #filter(sdrt %in% -5:15) %>% 
  #mutate(ge_copy = ge_copy/1e7) %>% 
  ggplot(aes(x = sdrt, y = ge_copy )) +
  geom_line(aes(x = sdrt, y = ge_copy), linetype = 'solid', size = 0.5, col = 'black') +
  geom_point(aes(size = max_pt, col = max_pt)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  xlim(xmin, xmax) +
  labs(x = 'Transplant day',
       y = str_glue('{genus_}\ncopies /g'),
       title = '') +  
  theme_classic() +
  theme(aspect.ratio=shorter_ratio,legend.position = 'none',
        plot.margin = margin(l=-0.8,unit="cm"),
            axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(colour = "grey85"))

# plot the irep and total abundance data for those patients for the genus with the highest irep value




ge_irep <-  ge_irep_all %>% 
  #filter(sdrt %in% -5:15) %>% 
  filter(mrn == mrn_) %>%
  ggplot(aes(x = sdrt, y = iRep )) +
  annotate('rect', xmin = xmin, xmax = xmax, ymin = ge_irep_q25, ymax = ge_irep_q75, fill='gray',  alpha=0.3) +
  geom_point(aes(size = iRep > ge_irep_q75, col = iRep > ge_irep_q75)) +
  scale_size_manual(values = c(2, 4)) +
  scale_color_manual(values = c('black', 'red')) +
  labs(title = str_glue('{}')) +
  xlim(xmin, xmax) +
  ylim(1, ge_irep_highest) +
  labs(x = '', 
       y = str_glue('{genus_}\ngrowth rate'),
       title = '')+
  theme_classic()+
  theme(aspect.ratio=shorter_ratio, legend.position = 'none' ,
        #axis.text.x=element_blank(),
        #axis.ticks.x=element_blank(),
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major.x = element_line(color = "grey85"))

id <- ids %>% 
  filter(mrn == mrn_) %>% 
  pull(pid)

all4 <-  plot_grid(sweets_panel, fruits_panel,ge_irep, ge_copies, 
                  ncol = 1,axis = 'lbrt', align = 'hv') 
ggsave(str_glue('../data/133_{id}_all4.pdf'), height = 8)
return(all4)
}
pt_df <- max_genus %>% ungroup() %>%
  slice(8)

pt <- pt_df %>% pull(mrn)
ge <- pt_df %>% pull(best_genus)
plot_all4(pt,ge)
```


```{r}
other10 <- pmap(max_genus %>% select(-iRep), function(mrn, best_genus){
    plot_all4(mrn,best_genus)
  }) 
```

