---
title: "Re-clean the abx data"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(lubridate)
library(vdbR)
connect_database('~/dbConfig.txt')
get_table_from_database('samples_castori_ag')
get_table_from_database ("antibiotics_antibacterial_multicenter_ag")
```

```{r}
#abx <- read_rds('/Volumes/vandenbrinklab/Nutrition and microbiota/medication_exposures/meds_nutrition_batch1_2022-11-29.rds')
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
meta <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')
ptb <- read_csv('../data/cleaned_patients/diet_patients_97.csv') %>% 
  mutate(patient_in_model = if_else(mrn %in% meta$mrn, T, F))
ptb %>% write_rds('../data/cleaned_patients/diet_patients_97.rds')

meta %>% distinct(mrn)
```
so we should consider as “exposed” any of these drugs regardless of their route (oral OR IV)
except in the special case of vancomycin, in which case we consider vancomcyin IV to not be an exposure and we consider vancomycin oral to be an expsoure

**should only remove :vancomcyin IV **

```{r}
# start the cleaning of the medication data from the raw source 
picked <-  c('vancomycin', 'imipenem_cilastatin','meropenem','ertapenem', 'cefepime', 'linezolid','metronidazole','piperacillin_tazobactam')

med1 <- read_rds('../data/tasks_nutrition_batch1_2022-11-29.rds') %>% 
  select(MRN, start_date, stop_date, drug_name, route) %>% 
  mutate(drug_name_clean = str_replace_all(drug_name, '-', '_')) %>% 
  mutate(drug_name_clean = str_to_lower(drug_name_clean),
         mrn = as.numeric(MRN)) %>% 
  filter(mrn %in% ptb$mrn)
```



```{r}
now <-   med1 %>% count(drug_name_clean) %>% arrange(desc(n))

allpickes <- tibble(picked = picked) %>% 
  summarise(text = str_c(picked, collapse = "|"))
allhas <- now %>% 
  filter(str_detect(drug_name_clean, allpickes$text))

#allroute <- empirical_med1 %>% count(together) %>% arrange(desc(n))

empirical_med1 <- med1 %>% 
  filter(drug_name_clean %in% picked) %>% 
  select(-drug_name) %>% 
  mutate(together = str_glue('{drug_name_clean}__{route}')) %>%  
  filter(! together %in% c('vancomycin__IV','vancomycin__IVPB'))

empirical_med1 %>% write_csv('../data/134_batch1_empirical_abx.csv')
```


```{r}
# picked <-  c("azithromycin","cefepime", "ciprofloxacin", "imipenem_cilastatin", "ertapenem","levofloxacin","linezolid","meropenem","metronidazole","piperacillin_tazobactam","sulfamethoxazole_trimethoprim")
# 
# abx <- antibiotics_antibacterial_multicenter_ag %>% 
#   filter(institution == 'MSKCC' ) %>% 
#   mutate(mrn = as.numeric(patient_id)) %>% 
#   filter(mrn %in% dtb$mrn) %>% 
#   mutate (drug_clean = if_else (drug_name_clean == "vancomycin",
#                                 if_else (route_simple == "oral","vancomycin_oral", "vancomycin_iv"),
#                                 if_else (drug_name_clean %in% picked, 
#                                          drug_name_clean,"atb_other"))) %>% 
#   left_join(ptb %>% select(mrn, hct)) %>% 
#   mutate(abx_p_start = start - hct,
#          abx_p_stop = stop - hct) %>% 
#   filter (abx_p_start > -30 & abx_p_stop < 70) 
```


```{r}
p2d_df <- meta %>% 
  select(sampleid, mrn) %>% 
  inner_join(samples_castori_ag %>% select(sampleid, datecollection)) %>% 
  mutate(p1d = datecollection -1,
         p2d = datecollection -2) %>% 
  mutate(p2d_int = interval(p2d, p1d)) %>% 
  select(sampleid, datecollection, mrn, p1d, p2d, p2d_int)

# then repeat this for all of the drugs
# all the drugs that I wanna see if there is an exposure in the previous 2 days
exposed_empirical <- empirical_med1 %>% 
  mutate(drug_int =  interval(start_date, stop_date)) %>% 
  inner_join(p2d_df, by = "mrn") %>% 
   mutate(had_drug = int_overlaps(p2d_int, drug_int)) %>% 
        filter(had_drug == 'TRUE')

exposed_empirical %>% distinct(sampleid)
exposed_empirical %>% distinct(MRN)

exposed_empirical %>% write_rds('../data/134_743stool_samples_p2d_drug_exposure.rds')

table <- read_rds('../data/134_743stool_samples_p2d_drug_exposure.rds')
```
```{r}
# find_exposure %>% 
#   gghistogram(x = 'abx_start_day', facet.by = 'drug_clean', fill = 'black') +
#   geom_vline( xintercept =0)
```

```{r}
# # find out the samples that were exposed to empirical abx
# empirical_abx <- c('vancomycin_oral',	'imipenem_cilastatin',	'meropenem',	'ertapenem',		'cefepime',		'linezolid',	'metronidazole',	'piperacillin_tazobactam')
# 
# empirical_exposed <- find_exposure %>% 
#   filter(drug_clean %in% empirical_abx)
# 
# new_exposed <- empirical_exposed %>% distinct(sampleid)
# 
# old_exposed <- meta %>% 
#   filter(empirical == 'TRUE')
# 
# library(ggvenn)
# two_list <- list(old = old_exposed$sampleid,new = new_exposed$sampleid)
# ggvenn(two_list)

```
```{r}
# need to update my meta table with this newly updated exposure data
new_meta <- meta %>% 
  mutate(empirical = if_else(sampleid %in% exposed_empirical$sampleid, T, F))

new_meta %>% write_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv')

new_meta %>% summary()
```

# below is to find the antibiotics usage data in batch 1 patients

```{r}
# I'm gonnna use the dtb time range as the time range here for tallying the abx data
DTB <- read_csv('../data/152_combined_DTB.csv')
PTB <- read_csv('../data/156_combined_PTB.csv')
range(DTB$fdrt)

med1 <- read_rds('../data/tasks_nutrition_batch1_2022-11-29.rds') %>% 
  filter(med_class1 == 'anti-infectives') %>% 
  select(mrn = MRN, start_date, med_class1) %>% 
  mutate(mrn = as.numeric(mrn)) %>% 
  inner_join(ptb %>% select(mrn, hct)) %>% 
  mutate(abx_day = as.numeric(start_date - hct)) %>% 
  filter(abx_day %in% min(DTB$fdrt):max(DTB$fdrt))

med1 %>% distinct(mrn) %>% nrow

# and repeat the above for the batch 2
med2 <- read_rds('../data/batch2_medication_exposures.rds') %>% 
  filter(class %in% c( 'anti.bacterial')) %>% 
   select(mrn = MRN, start_date, class) %>% 
  mutate(mrn = as.numeric(mrn)) %>% 
  inner_join(PTB %>% select(mrn, hct)) %>% 
  mutate(abx_day = as.numeric(start_date - hct)) %>% 
  filter(abx_day %in% min(DTB$fdrt):max(DTB$fdrt))

med2 %>% distinct(mrn) %>% nrow
#All the 173 patients received antibiotics during their diet data collection days. 
```

```{r}
# below I calculate what perc also took the empirical abx
empirical1 <- read_rds('../data/tasks_nutrition_batch1_2022-11-29.rds') %>% 
  select(MRN, start_date, stop_date, drug_name, route) %>% 
  mutate(drug_name_clean = str_replace_all(drug_name, '-', '_')) %>% 
  mutate(drug_name_clean = str_to_lower(drug_name_clean),
         mrn = as.numeric(MRN)) %>% 
  filter(mrn %in% ptb$mrn) %>% 
   filter(drug_name_clean %in% picked) %>% 
  select(-drug_name) %>% 
  mutate(together = str_glue('{drug_name_clean}__{route}')) %>%  
  filter(! together %in% c('vancomycin__IV','vancomycin__IVPB')) %>% 
  inner_join(PTB %>% select(mrn, hct)) %>% 
  mutate(abx_day = as.numeric(start_date - hct)) %>% 
  filter(abx_day %in% min(DTB$fdrt):max(DTB$fdrt))
empirical1 %>% distinct(mrn) %>% nrow
```


```{r}
empirical2 <- read_rds('../data/batch2_medication_exposures.rds') %>% 
  select(MRN:stop_date, drug_name, route) %>% 
  mutate(drug_name_clean = str_replace_all(drug_name, '-', '_')) %>% 
  mutate(drug_name_clean = str_to_lower(drug_name_clean)) %>% 
  mutate(drug_name_clean = case_when(
    drug_name_clean == 'levofloxacin (levaquin)' ~ 'levofloxacin',
    drug_name_clean == 'vancomycin invest' ~ 'vancomycin',
    TRUE ~ drug_name_clean
  )) %>% 
  mutate(mrn = as.numeric(MRN)) %>% 
  filter(drug_name_clean %in% picked) %>% 
  filter(mrn %in% PTB$mrn) %>% 
  mutate(together = str_glue('{drug_name_clean}__{route}')) %>% 
  select(-drug_name) %>% 
  filter(! together %in% c('vancomycin__IV')) %>% 
   inner_join(PTB %>% select(mrn, hct)) %>% 
  mutate(abx_day = as.numeric(start_date - hct)) %>% 
  filter(abx_day %in% min(DTB$fdrt):max(DTB$fdrt))

empirical2 %>% distinct(mrn) %>% nrow
```

