---
title: "The new cohort dtb and the dehydated weight"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)

dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')%>% mutate(Food_code = as.character(Food_code))
dtb %>% summary()


# the high water portion 
```

```{r}
new1 <- read_csv('../data/128_new_dtb.csv') %>% mutate(Food_code = as.character(Food_code))
new1 %>% summary

engy <- readxl::read_excel('../data/source/2015-2016 FNDDS At A Glance - FNDDS Nutrient Values.xlsx', skip = 1, col_types  = 'text') %>% 
  rename_all(funs(str_replace_all(., ' ','_'))) %>% 
  rename_all(funs(str_replace_all(., '\\(|\\)',''))) %>% 
  select(Food_code, Energy_kcal, Water_g) %>% 
  mutate(Energy_kcal = as.numeric(Energy_kcal),
         Water_g = as.numeric(Water_g))

new2 <- new1 %>% 
  left_join(engy, by  = 'Food_code')  %>% 
  mutate(total_weight = if_else(Energy_kcal == 0, 99999, Calories_kcal/Energy_kcal*100)) %>% 
  mutate(dehydrated_weight = if_else(total_weight == 99999, 0.0001, total_weight*(1 - Water_g/100)))

#new2 %>% summary
 
# sanity check
check2 <- new2 %>% 
  select(Food_NSC, Food_code,description,  Por_eaten, Unit,Calories_kcal,  Energy_kcal:dehydrated_weight) %>% 
  filter(dehydrated_weight > 30 & Water_g > 75) %>% 
  arrange(Food_NSC, Por_eaten) %>% 
  distinct(Food_NSC, Unit, .keep_all = T ) %>% 
  arrange(desc(Water_g)) %>% 
  select(Food_NSC:Calories_kcal)


check2 %>% write_csv('../data/136_check_2_batch_cal.csv')
```

```{r}
# find the both batches dehy wight > 30 and water portion > 75 ones
check1 <- dtb %>% 
  left_join(engy, by  = 'Food_code')  %>% 
  mutate(total_weight = if_else(Energy_kcal == 0, 99999, Calories_kcal/Energy_kcal*100)) %>% 
  mutate(dehydrated_weight = if_else(total_weight == 99999, 0.0001, total_weight*(1 - Water_g/100))) %>% 
  select(Food_NSC, Food_code,description,  Por_eaten, Unit,Calories_kcal,  dehydrated_weight:total_weight) %>% 
  filter(dehydrated_weight > 30 & Water_g > 75) %>% 
  arrange(Food_NSC, Por_eaten)  %>% 
  distinct(Food_NSC, Unit, .keep_all = T ) %>% 
  arrange(desc(Water_g)) %>% 
  select(colnames(check2))
check1 %>% write_csv('../data/136_check_1_batch_cal.csv')

```

# Merge the corrected calories to batch 2

```{r}
fixed2 <- read_csv('../data/136_check_2_batch_cal_peter.csv') %>% mutate(Food_code = as.character(Food_code))

total_fixed2 <-  new2 %>%  
  filter(dehydrated_weight > 30 & Water_g > 75)

# expand the 154 to 1815 all different portions
all_portions <- new2 %>% 
  select(Food_NSC, Food_code,description,  Por_eaten, Unit,Calories_kcal,  Energy_kcal:dehydrated_weight) %>% 
  filter(dehydrated_weight > 30 & Water_g > 75) %>% 
  arrange(Food_NSC, Por_eaten) %>% 
  arrange(desc(Water_g)) %>% 
  select(Food_NSC:Calories_kcal) %>% 
  select( -Calories_kcal) %>% 
  left_join(fixed2, by = c("Food_NSC", "Food_code", "description", "Por_eaten", "Unit"))

split_all_portions <- all_portions %>% 
  split(., list(.$Food_NSC, .$Unit))%>%  
  discard( ~nrow(.) == 0) %>% 
  map(function(df){
    df %>% 
        arrange(Calories_kcal) %>% 
        mutate(ratio = Por_eaten/Por_eaten[1]) %>% 
        mutate(scaled_cal = Calories_kcal[1]*ratio)
  })  %>% 
  bind_rows() %>% 
  select(-Calories_kcal, -ratio) %>%    
  rename(Calories_kcal = scaled_cal) %>% 
  distinct()

# expand to have other columns
total_fixed2_df <- total_fixed2 %>% 
  select(-Calories_kcal) %>% 
  inner_join(split_all_portions, by = c("Food_NSC", "Food_code", "Por_eaten", "Unit", "description")) %>% 
  select(colnames(new2))

# the other part of the df that is unchanged
other2 <- new2 %>%  
  mutate(fixed = if_else(dehydrated_weight > 30 & Water_g > 75, T, F)) %>% 
  filter(fixed == 'FALSE') %>% 
  select(-fixed)

 # recalculate the dehydrated weight again
new3 <- bind_rows(total_fixed2_df, other2) %>% 
  select(-Energy_kcal, -Water_g, -total_weight, -dehydrated_weight) %>% 
  left_join(engy, by  = 'Food_code')  %>% 
  mutate(total_weight = if_else(Energy_kcal == 0, 99999, Calories_kcal/Energy_kcal*100)) %>% 
  mutate(dehydrated_weight = if_else(total_weight == 99999, 0.0001, total_weight*(1 - Water_g/100))) %>% 
  filter(Por_eaten > 0) %>% 
  select(colnames(dtb))

sanity_check <- new3 %>% 
  distinct(Food_NSC, Por_eaten, Unit, dehydrated_weight)
# finally it is ok!!!!!!!!!!!omg!!!!!!!!!

new3 %>% write_rds('../data/136_updated_dtb2.rds')
```





