---
title: "previous two days diet with stool"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
```

```{r}
stb <- read_rds('../data/137_stb.rds')
dtb <- read_rds('../data/136_updated_dtb2.rds')
```

```{r}
nodes <- read_tsv('../data/source/NodeLabels.txt', col_types = 'cc') %>% 
  filter(nchar(Level.code) == 1) %>% 
  rename(fgrp1 = Level.code, 
         fdesc = Main.food.description)

fgrps_df <- dtb %>% 
  select(mrn, fdrt, dehydrated_weight, Food_code) %>% 
  mutate(fgrp1 = str_sub(Food_code, 1, 1))

# the total dehydated weight for a patient for one day for a single food group
total_per_group <- fgrps_df %>% 
  group_by(mrn, fdrt, fgrp1) %>% 
  summarise(grp_tol = sum(dehydrated_weight)) %>% 
  mutate(fg1_name = case_when(
    fgrp1 == '1' ~ 'fg_milk',
    fgrp1 == '2' ~ 'fg_meat',
    fgrp1 == '3' ~ 'fg_egg',
    fgrp1 == '4' ~ 'fg_legume',
    fgrp1 == '5' ~ 'fg_grain',
    fgrp1 == '6' ~ 'fg_fruit',
    fgrp1 == '7' ~ 'fg_veggie',
    fgrp1 == '8' ~ 'fg_oils', 
    fgrp1 == '9' ~ 'fg_sweets'
  ))
```
## average on the previous two days diet food groups

```{r}
stb_pair <- stb %>%  
  select(mrn, sdrt) %>% 
  transmute(mrn = mrn,
            p1d = sdrt-1,
            p2d = sdrt-2) 

mean_p2d_diet <-  function(mrn_, p1d_, p2d_){
  df = total_per_group %>% 
    filter(mrn == mrn_) %>% 
    filter(fdrt %in% c(p1d_, p2d_  )) %>% 
    group_by(fg1_name) %>% 
    summarise(ave_fg = sum(grp_tol)/2)
  return(df)
}

mean_p2d_df <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_diet(mrn, p1d, p2d)
  }) %>% 
  set_names(stb %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'fg1_name', value = 'ave_fg', fill = 0) %>% 
  inner_join(stb, by = "sampleid") 

meta <- mean_p2d_df %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = factor(mrn))%>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100)
```

## THE model

```{r}
library(brms)   
library(ggpubr)
library(tidybayes)
library(cowplot)
ncores <- parallel::detectCores()
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')

# what priors I can set 
model_formular <- log(simpson_reciprocal) ~ 0 + 
                fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               intensity +
               empirical+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin)
get_prior( model_formular,  
              data = meta)

priors <- c(# for the food group variables
            prior(normal(0, 1), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie"),
            # for the TPN 
            prior(normal(0, 0.1), class = 'b', coef = "TPNTRUE"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "ENTRUE"),
            # for the empirical 
            prior(normal(0, 0.5), class = 'b', coef = "empiricalTRUE"),
            # for the intensity 
            prior(normal(2, 0.1), class = 'b', coef = "intensityreduced"),
            prior(normal(2, 0.1), class = 'b', coef = "intensityablative"),
            prior(normal(2, 0.1), class = 'b', coef = "intensitynonablative"))
```

```{r}
model_div <- brm( model_formular,  
              data = meta, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
               control = list(adapt_delta = 0.99),
              seed = 123, sample_prior = T)

# save it for future use
post_res <- suppressWarnings(posterior_samples(model_div)) 
post_res %>%  write_csv('../data/138_div_model_fg_post_batch2.csv')
```
```{r}
post_samples  <- read_csv('../data/138_div_model_fg_post_batch2.csv')

post_coeff <- post_samples %>% 
  select(starts_with('b_fg')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item = str_replace(item, 'b_fg_','')) %>% 
   mutate(fgrp1 = case_when(
    item ==  'milk' ~ '1',
    item == 'meat' ~ '2',
    item ==  'egg' ~ '3',
    item ==  'legume' ~ '4',
    item == 'grain' ~ '5',
    item == 'fruit' ~ '6',
    item == 'veggie' ~ '7',
    item ==  'oils' ~ '8', 
    item ==  'sweets' ~ '9'
  ))  %>% 
  left_join(key %>% select(fgrp1, color, shortname))  %>% 
  mutate(shortname = fct_reorder(shortname, coeff, .fun=median, .desc = F)) 

cross0 <- post_coeff %>%
  group_by(item) %>% 
  summarise(q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975)) %>% 
  mutate(Cross = if_else(q2.5 > 0 | q97.5 < 0, F, T))

div_post <- post_coeff %>% 
  left_join(cross0) %>% 
  ggplot(aes(x = coeff, y = shortname, col = Cross)) +
  stat_pointinterval(.width = c(.66, .95)) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  labs(x = 'ln(diversity) change per 100g of food',
       y = '', 
       title = 'Diversity') +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_manual(values = c("#EC0000", "gray40")) +
  theme(axis.text=element_text(size=8, color  = 'black'),
        axis.title=element_text(size=8),
        aspect.ratio=1)
```

```{r}
coeff_bi <- post_samples %>% 
  select(starts_with('b_')) %>% 
  select(!starts_with('b_fg')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item_name = case_when(
    item ==  'b_intensitynonablative' ~ 'Intensity: nonablative',
    item == 'b_intensityablative' ~ 'Intensity: ablative',
    item ==  'b_intensityreduced' ~ 'Intensity: reduced',
    item ==  'b_empiricalTRUE' ~ 'Empirical abx exposure',
    item == 'b_TPNTRUE' ~ 'TPN exposure',
    item ==  'b_ENTRUE' ~ 'EN exposure'
  )) %>% 
  mutate(item_name = factor(item_name, levels = c('Intensity: nonablative', 'Intensity: reduced',
                                                  'Intensity: ablative', 'TPN exposure','EN exposure',
                                                  'Empirical abx exposure'))) %>% 
  mutate(grp = if_else(str_detect(item_name, 'Intensity'), 'Patient level', 'Sample level'))

# modify it to be the look that we have discussed
diversity_factor <- coeff_bi %>% 
  ggplot(aes(x = coeff, y = item_name)) +
  stat_pointinterval(.width = c(.66, .95)) +
  #scale_color_manual(values = c('#EC0000','#00468B')) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  facet_wrap(grp~ . , scales = 'free', dir = 'v') +
  labs(x = 'Coefficients',
       y = 'Factor variables',
       title = 'Diversity') +
  theme_classic() +
  theme(legend.position = 'none',
        strip.background = element_blank(),
        strip.text = element_blank(),
        aspect.ratio=1/2) 
```

## are the dry weight in batch 1 trust worth here we come the racing game ...

```{r}
check1 <-  read_csv('../data/136_check_1_batch_cal.csv') 
check2 <- read_csv('../data/136_check_2_batch_cal_peter.csv')

# find the overlapped food nsc between the two tables
length(intersect(check1$Food_NSC, check2$Food_NSC))

check1_ <- check1 %>% 
  rename(old_cal  = Calories_kcal) %>% 
  left_join(check2 %>% select(Food_NSC, Por_eaten, Unit, Calories_kcal))

# update the check1 for Peter
check1new <- check1 %>% 
  left_join(check2 %>% distinct(Food_NSC, Unit) %>% mutate(grp = 'checked ')) %>% 
  filter(is.na(grp)) %>% 
  select(-grp)

check1new %>% write_csv('../data/136_check_1_batch_cal_new.csv')
```


