---
title: "Calibrate the calories in batch 1"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
```

```{r}
dtb1 <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
dtb1 <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized_OLD.csv')

engy <- readxl::read_excel('../data/source/2015-2016 FNDDS At A Glance - FNDDS Nutrient Values.xlsx', skip = 1, col_types  = 'text') %>% 
  rename_all(funs(str_replace_all(., ' ','_'))) %>% 
  rename_all(funs(str_replace_all(., '\\(|\\)',''))) %>% 
  select(Food_code, Main_food_description, Energy_kcal, Water_g) %>% 
  mutate(Energy_kcal = as.numeric(Energy_kcal),
         Water_g = as.numeric(Water_g),
         Food_code = as.numeric(Food_code))

dtb1_check <- dtb1 %>% 
  left_join(engy, by  = 'Food_code')  %>% 
  mutate(total_weight = if_else(Energy_kcal == 0, 99999, Calories_kcal/Energy_kcal*100)) %>% 
  mutate(dehydrated_weight = if_else(total_weight == 99999, 0.0001, total_weight*(1 - Water_g/100))) %>% 
  mutate(check = if_else(dehydrated_weight > 30 & Water_g > 75, T, F))

dtb1_unchanged <- dtb1_check %>% 
  filter(check == 'FALSE')%>% 
  select(colnames(dtb1))

dtb1_change <- dtb1_check %>% 
  filter(check == 'TRUE') 

# EN ones have the food code we created and the dehydrated weight are converted from the wet weight 
dtb1_EN <- dtb1 %>% 
  filter(Unit == 'EN unit')
```

```{r}
# the unique food nsc and the unit to be checked 
checktotal <- dtb1_change %>% 
   distinct(Food_NSC, Unit, .keep_all = T )

# the unique items with the checked values
check1 <- read_csv('../data/136_check_1_batch_cal_new_peter.csv') %>% 
  select(Food_NSC, Por_eaten:Calories_kcal)
check2 <- read_csv('../data/136_check_2_batch_cal_peter.csv')

# the ones that are checked in batch 2
check1_already <- read_csv('../data/136_check_1_batch_cal.csv')  %>% 
  left_join(check2 %>% distinct(Food_NSC, Unit) %>% mutate(grp = 'checked')) %>% 
  filter(grp == 'checked')  %>% 
  select(Food_NSC, Por_eaten:Calories_kcal)

check1_all <- bind_rows(check1, check1_already)

# need to expand the 295 to 1934
all_portions <- dtb1_change %>% 
  select(Food_NSC,  Por_eaten, Unit) %>% 
  left_join(check1_all, by = c("Food_NSC",  "Por_eaten", "Unit"))

split_all_portions <- all_portions %>% 
  split(., list(.$Food_NSC, .$Unit))%>%  
  discard( ~nrow(.) == 0) %>% 
  map(function(df){
    df %>% 
        arrange(Calories_kcal) %>% 
        mutate(ratio = Por_eaten/Por_eaten[1]) %>% 
        mutate(scaled_cal = Calories_kcal[1]*ratio)
  })  %>% 
  bind_rows() %>% 
  select(-Calories_kcal, -ratio) %>%    
  rename(Calories_kcal = scaled_cal) %>% 
  distinct()

# expand to have other columns
total_dtb1_change <- dtb1_change %>% 
  select(-Calories_kcal) %>% 
  inner_join(split_all_portions, by = c("Food_NSC",  "Por_eaten", "Unit")) %>% 
  select(mrn:fdrt, Calories_kcal) %>% 
   left_join(engy, by  = 'Food_code')  %>% 
  mutate(total_weight = if_else(Energy_kcal == 0, 99999, Calories_kcal/Energy_kcal*100)) %>% 
  mutate(dehydrated_weight = if_else(total_weight == 99999, 0.0001, total_weight*(1 - Water_g/100))) %>% 
  select(colnames(dtb1))

#total_dtb1_change %>% write_csv('../data/140_changed_calories_in_batch1.csv')

# combine them together ...
dtb1_final <- bind_rows(dtb1_unchanged, total_dtb1_change, dtb1_EN)

dtb1_final %>% write_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')
```

```{r}
# double check specifically for the sweets group
double9 <- dtb1_final %>% 
  filter(str_detect(Food_code, '^9')) %>% 
  distinct(Food_code,Food_NSC, .keep_all = T ) %>% 
  arrange(desc(dehydrated_weight)) %>% 
  select(Food_NSC, Food_code, Calories_kcal, dehydrated_weight)

# the heavy stuff are the nutritional drink ones
# and the soda are all the weight of the sugar
```
```{r}
# now I know why the same Food_NSC doesn't have corrected values for a smaller portion 
# it's cuz it doesn't meet the dehydrated_weight > 30 & Water_g > 75 threshold
# below is to make a correction using one item as example for the showing purpose to Jonas
# 2014, Juice,  Apple
vetted_by_peter <- check1 %>% filter(Food_NSC == '2014, Juice,  Apple')

all_portions <- dtb1 %>% 
  filter(Food_NSC == '2014, Juice,  Apple') %>% 
  select(Food_NSC,Food_code,   Por_eaten, Unit) %>% 
  left_join(vetted_by_peter)

scale_all_portions <- all_portions %>% 
  split(., list(.$Food_NSC, .$Unit))%>%  
  discard( ~nrow(.) == 0) %>% 
  map(function(df){
    df %>% 
        arrange(Calories_kcal) %>% 
        mutate(ratio = Por_eaten/Por_eaten[1]) %>% 
        mutate(scaled_cal = Calories_kcal[1]*ratio)
  })  %>% 
  bind_rows() %>% 
   left_join(engy, by  = 'Food_code')  %>% 
  mutate(total_weight = if_else(Energy_kcal == 0, 99999, scaled_cal/Energy_kcal*100)) 
```

