---
title: "the impact of the corrected calories"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)

engy <- readxl::read_excel('../data/source/2015-2016 FNDDS At A Glance - FNDDS Nutrient Values.xlsx', skip = 1, col_types  = 'text') %>% 
  rename_all(funs(str_replace_all(., ' ','_'))) %>% 
  rename_all(funs(str_replace_all(., '\\(|\\)',''))) %>% 
  select(Food_code, Energy_kcal, Water_g) %>% 
  mutate(Energy_kcal = as.numeric(Energy_kcal),
         Water_g = as.numeric(Water_g),
         Food_code = as.numeric(Food_code))
```

```{r}
# the original calories in batch 1 before vetting  
old <- read_csv('../data/140_changed_calories_in_batch1.csv') %>% 
  select(-Energy_kcal, -Water_g, -total_weight) %>% 
   left_join(engy, by  = 'Food_code')  %>% 
  mutate(total_weight = if_else(Energy_kcal == 0, 99999, Calories_kcal/Energy_kcal*100)) %>% 
  mutate(new_dehydrated_weight = if_else(total_weight == 99999, 0.0001, total_weight*(1 - Water_g/100))) %>% 
  select(Food_NSC, Food_code, description, Unit, Por_eaten, dehydrated_weight, new_dehydrated_weight)

most <- old %>% 
  distinct() %>% 
  mutate(ratio = new_dehydrated_weight/dehydrated_weight) %>% 
  arrange(ratio)

decreased_dry_weight <- most %>% 
  filter(ratio < 0.9) %>% 
  distinct(Food_NSC, .keep_all = T)

decreased_dry_weight %>% 
  mutate(fgrp1 = str_sub(as.character(Food_code), 1,1)) %>% 
  select(Food_NSC, fgrp1, old = dehydrated_weight, new =new_dehydrated_weight, ratio ) %>% 
  gather('grp', 'weight', old:new) %>% 
  mutate(grp = factor(grp, levels = c('old','new'))) %>% 
  arrange(fgrp1, ratio) %>% 
  ggbarplot("Food_NSC", "weight",xlab = '',ylab = 'dry weight', 
  fill = "grp", color = "grp", palette = 'jco',
  width = 0.7, 
  position = position_dodge(0.8)) +
  facet_grid(~ fgrp1, scales = 'free') +
  coord_flip() +
  theme(legend.position = 'bottom',
        axis.text.y = element_text(size=11),
        legend.title= element_blank())

ggsave('../data/141_dry_weight_decreased_batch1.pdf', width = 10)
```

# stool sample summarization 

```{r}
meta1 <- read_csv('../data/cleaned_stool/all_samples_meta_p2d_fg9_updated.csv') %>% 
  select(starts_with('fg'), empirical, EN, TPN, simpson_reciprocal, sdrt )

meta1 %>% summary
```
```{r}
meta2 <- read_rds('../data/138_meta2.rds') %>% 
  select(starts_with('fg'), empirical, EN, TPN, simpson_reciprocal, sdrt )

meta2 %>% summary
```
```{r}
# the dry weight and the sum of macro nutrients comparison
dtb <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv') %>% 
  mutate(fgrp2 = str_sub(as.character(Food_code), 1, 2)) %>% 
  mutate(grp = if_else(fgrp2 %in% c('92', '93','94', '95'), 'drinks', 'other'))

nodes <- read_tsv('../data/source/NodeLabels.txt', col_types = 'cc') %>% 
  filter(nchar(Level.code) == 2) %>% 
  rename(fgrp2 = Level.code, 
         fdesc = Main.food.description)
tt <- dtb %>% 
  select( Protein_g:Sodium_g, dehydrated_weight,grp) %>% 
  mutate(summac = Protein_g + Fat_g + Carbohydrates_g + Fibers_g + Sugars_g + Sodium_g)

dtb %>% 
  select( Protein_g:Sodium_g, dehydrated_weight,grp) %>% 
  mutate(summac = Protein_g + Fat_g + Carbohydrates_g + Fibers_g + Sugars_g + Sodium_g) %>% 
  ggpubr::ggscatter(x = 'summac', y = 'dehydrated_weight', color = 'grp', alpha = 0.5, xlab = 'Sum of macronutrients') +
  geom_abline(slope = 1, intercept = 0)
  
```
```{r}
df <- dtb %>% 
  distinct(Food_NSC, Food_code, Unit, .keep_all = T)
```

