---
title: "I've got the vetted data back all of them!!!!"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
```

```{r}
# the current dtb1 
# the final expanded table should be the same number 22840
dtb1 <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')


# the below data has the vetted calories and the total weight in grams
# (waiting for the fruit smoothies breaking down to different food groups)
vet <- readxl::read_excel('../data/142_batch1_diet_calories_check_peter.xlsx') %>% 
  rename(total_g = weight_grams)

# first make sure all of the my entries in cal is not NA
nacor <- read_csv('../data/144_check_NA_ones_peter.csv') %>% 
  inner_join(dtb1 %>% distinct(Food_code, description), by = "Food_code") %>% 
  select(colnames(vet))

# the below are the total vetted ones that are not EN
totalvet <- bind_rows(vet, nacor) 



# the table that has the water gram weight for 100 gram total weight of a food code
engy <- readxl::read_excel('../data/source/2015-2016 FNDDS At A Glance - FNDDS Nutrient Values.xlsx', skip = 1, col_types  = 'text') %>% 
  rename_all(funs(str_replace_all(., ' ','_'))) %>% 
  rename_all(funs(str_replace_all(., '\\(|\\)',''))) %>% 
  select(Food_code, Main_food_description, Water_g, Energy_kcal) %>% 
  mutate(Water_g = as.numeric(Water_g),
         Food_code = as.numeric(Food_code),
         Energy_kcal = as.numeric(Energy_kcal))

# find the unique combinations of all of the portions for (food_nsc + unit)
allcombo <- dtb1 %>% 
  distinct(Food_code, Food_NSC, Por_eaten, Unit) %>% 
  left_join(totalvet %>% 
              select(Food_NSC, Por_eaten, Unit, Calories_kcal, total_g), by = c("Food_NSC", "Unit", "Por_eaten"))

scale_all_combos <- allcombo %>% 
  split(., list(.$Food_NSC, .$Unit))%>%  
  discard( ~nrow(.) == 0) %>% 
  map(function(df){
    df %>% 
        arrange(Calories_kcal) %>% 
        mutate(ratio = Por_eaten/Por_eaten[1]) %>% 
        mutate(scaled_cal = Calories_kcal[1]*ratio,
               scaled_total_g = total_g[1]*ratio)
  })  %>% 
  bind_rows()

# need some manual correction of Specials, Angel Hair Pasta (2) since the data was entered wrong into computrition
part1 <- scale_all_combos %>% 
  filter(Unit != 'EN unit') %>% 
  filter(Food_NSC != 'Specials, Angel Hair Pasta (2)') %>% 
  add_row(totalvet %>% 
            filter(Food_NSC == 'Specials, Angel Hair Pasta (2)') %>% 
            slice(1) %>% 
            mutate(ratio = 1,scaled_cal = 165, scaled_total_g = 105) %>% 
            select(colnames(scale_all_combos)))

# now expand all of the unique combos to the whole dtb1 (excluding EN) 22787 rows
dtb_ <- dtb1 %>% 
  filter(Unit != 'EN unit') %>% 
  # correct the portion and Unit for Specials, Angel Hair Pasta (2) 
  mutate(Por_eaten = if_else(Food_NSC == 'Specials, Angel Hair Pasta (2)', 0.75, Por_eaten),
         Unit = if_else(Food_NSC == 'Specials, Angel Hair Pasta (2)', 'cup', Unit)) %>% 
  select(mrn:Por_eaten, Food_code:fdrt) %>% 
  left_join(part1, by = c("Food_NSC", "Unit", "Por_eaten", "Food_code")) %>% 
  select(mrn:fdrt, Calories_kcal = scaled_cal, total_g = scaled_total_g)
```

```{r}
# I got the vetted data back from Peter
# merging them into my current dtb
calcor <- read_csv('../data/144_check_cal_500_ones_peter.csv')

# find the food_nsc in these and scale to other portions
needcal_food <- calcor %>% 
  distinct(Food_NSC) %>% pull(Food_NSC)

# find all of the combo of Portion + Unit for these food_nsc
calcombo <- dtb_ %>% 
  distinct(Food_code, Food_NSC, Por_eaten, Unit) %>% 
  ungroup() %>% 
  filter(Food_NSC %in% needcal_food) %>% 
  left_join(calcor %>% 
              select(Food_NSC, Por_eaten, Unit, Calories_kcal = scaled_cal, total_g = scaled_total_g), by = c("Food_NSC", "Unit", "Por_eaten"))

scale_cal_check <- calcombo %>% 
  split(., list(.$Food_NSC, .$Unit))%>%  
  discard( ~nrow(.) == 0) %>% 
  map(function(df){
    df %>% 
        arrange(Calories_kcal) %>% 
        mutate(ratio = Por_eaten/Por_eaten[1]) %>% 
        mutate(scaled_cal = Calories_kcal[1]*ratio,
               scaled_total_g = total_g[1]*ratio)
  })  %>% 
  bind_rows()

# there are some NAs in the above table and a result because of the same food with differnt Unit
# try to find the values in the previous vetted data
scale_cal_check_na <- scale_cal_check %>% 
  filter(is.na(scaled_cal)) %>% 
  select(Food_NSC:Food_code) %>% 
  left_join(part1, by = c("Food_NSC", "Unit", "Por_eaten", "Food_code"))

# now combine the above two parts 
scale_cal_check_full <- bind_rows(
   scale_cal_check %>% filter(!is.na(scaled_cal)),
   scale_cal_check_na
)
```

```{r}
# like Jonas said now I get the full meaning of why it would be good to have a relational database
# because you can just calibrate the unit portion for one thing and then scale it to all others accordingly so you don't need to worry about the scaling every single time
# now to have such a unit portion thing 
# there are two parts that I need to assemble
cal2 <- scale_cal_check_full %>% 
  select(Food_NSC, Food_code, Por_eaten, Unit, Calories_kcal = scaled_cal, total_g = scaled_total_g) %>% 
  distinct(Food_NSC,Unit, .keep_all = T ) %>% 
  mutate(cal_per_serving_unit = round(Calories_kcal/Por_eaten,1))

# prepare a table for the food_nsc that is not in the calcor table 
cal1 <- dtb_ %>% 
  filter(!Food_NSC %in% needcal_food) %>% 
  distinct(Food_NSC,Unit, .keep_all = T ) %>% 
  mutate(cal_per_serving_unit = round(Calories_kcal/Por_eaten,1)) %>% 
  select(colnames(cal2))

# combine those two tables
calall <- bind_rows(cal1, cal2) %>% 
  mutate(total_gram_per_serving_unit = round(total_g/Por_eaten,1)) %>% 
  select(Food_NSC, Food_code,Unit, cal_per_serving_unit, total_gram_per_serving_unit) %>% 
  mutate(fd_unit = str_glue('{Food_code}:{Unit}'))  %>% 
  inner_join(dtb1 %>% distinct(Food_code, description), by = "Food_code")

calall %>% write_csv('../data/144_cal_and_gram_per_serving_unit_batch1.csv')

calall <- read_csv('../data/144_cal_and_gram_per_serving_unit_batch1.csv')
```

```{r}
# to make a plot shows that Jonas suggested that has the foodcode+unit combination boxplot to see if they are generallly consistent
  

tally_combo <- calall %>% count(fd_unit, sort = T)
to_plot <- tally_combo %>% 
  filter(n >= 5) %>% pull(fd_unit)

# select to plot the combos that have at least 5 points
to_plot_calall <- calall %>% 
  filter(fd_unit %in% to_plot)

to_plot_calall %>% 
  ggboxplot(y = 'cal_per_serving_unit') +
  facet_wrap(~ fd_unit, scales = 'free')

ggsave('../data/144_fd_unit5.pdf', width = 16, height = 15)
```

```{r}
# calculate the standard deviation of the each food code + unit combo
sd_combo <- calall %>% 
  split(.$fd_unit) %>% 
  map(function(df){
    df %>% 
      mutate(num_data = nrow(.)) %>% 
      group_by(fd_unit, description, num_data) %>% 
      summarise(min_cal = min(cal_per_serving_unit),
                max_cal = max(cal_per_serving_unit),
                mean_cal = mean(cal_per_serving_unit),
                sd_cal = sd(cal_per_serving_unit))
  })

sd_combo_df <- sd_combo %>% bind_rows()
```

```{r}
# make them into a single df
calcombined <- calall %>% 
  left_join(sd_combo_df, by = c("fd_unit", "description")) %>% 
  rename(cal_psu = cal_per_serving_unit,
         g_psu = total_gram_per_serving_unit)
```

```{r}
# first to replace the food code of the old ones of the fruit juices (real) with the newer ones that Peter added that are in the fruit group
juice_cor <- read_csv('../data/142_batch1_fruit_juice_code_correction.csv') %>% 
  inner_join(calall %>% select(Food_NSC, old_code = Food_code) %>% distinct()) %>% 
  distinct()

cor_food <- juice_cor %>% 
  distinct(Food_NSC) %>% pull(Food_NSC)

cal_cor1 <- calall %>% 
  filter(Food_NSC %in% cor_food) %>% 
  select(-Food_code, -fd_unit, -description) %>% 
  left_join(juice_cor %>% select(Food_NSC:description), by = "Food_NSC") %>% 
  mutate(fd_unit = str_glue('{Food_code}:{Unit}')) %>% 
  select(colnames(calall))

cal_cor2 <- calall %>% 
   filter(!Food_NSC %in% cor_food) 

calall2 <- bind_rows(cal_cor1 , cal_cor2)
calall2 %>% write_csv('../data/144_cal_and_gram_per_serving_unit_batch1.csv')
calall2 <- read_csv('../data/144_cal_and_gram_per_serving_unit_batch1.csv')
```

```{r}
# now update the calcombined using the above data 
calall2_summary <- calall2 %>% 
  split(.$fd_unit) %>% 
  map(function(df){
    df %>% 
      mutate(num_data = nrow(.)) %>% 
      group_by(fd_unit, description, num_data) %>% 
      summarise(min_cal = min(cal_per_serving_unit),
                max_cal = max(cal_per_serving_unit),
                mean_cal = mean(cal_per_serving_unit),
                sd_cal = sd(cal_per_serving_unit))
  })  %>% bind_rows()

calcombined2 <- calall2 %>% 
  left_join(calall2_summary, by = c("fd_unit", "description")) %>% 
  rename(cal_psu = cal_per_serving_unit,
         gram_psu = total_gram_per_serving_unit) %>% 
  arrange(desc(sd_cal))

# I wanna take out the smoothie etc for now since it is in a different table that Peter is doing
exclude <- readxl::read_excel('../data/142b_batch1_diet_calories_check_subset_with_macros.xlsx')
excludefood <- exclude %>% 
  distinct(Food_NSC) %>% pull(Food_NSC)

# the below is without the smoothie etc for now since it is in a different table that Peter is doing
calcombined3 <- calcombined2 %>% 
  filter(! Food_NSC %in% excludefood) %>% 
  arrange(desc(sd_cal), cal_psu)

# the ones that need to be merged back after Peter is done with the smoothies:
needsmoothie <- calcombined2 %>% 
  filter(Food_NSC %in% excludefood)

#needsmoothie %>% write_csv('../data/144_he ones that need to be merged back after Peter is done with the smoothies.csv')

# the ones that I decided to let Peter double check:
peter_check_sd_1.55 <- calcombined3 %>% 
  filter(sd_cal > 1.55)
#peter_check_sd_1.55 %>%   write_csv('../data/144_peter_check_sd_gt_1.55_ones.csv')

```

```{r}
# to see if the remaining ones (ones with sd <= 1.55) have anything that is the smoothies, etc
# the answer is no which is good
good <- calcombined3 %>% 
  filter(sd_cal <= 1.55 | is.na(sd_cal)) %>% 
  select(Food_NSC:description)
```

```{r}
# the data that peter double checked : 272, he removed 5 entries to be in the milkshake smoothie group.
p272 <- read_csv('../data/144_peter_check_sd_gt_1.55_ones_peter.csv') %>% 
  select(Food_NSC:description)

# current ones that I have max confidence:
currentgood <- bind_rows(good, p272) %>% 
  select(-fd_unit) %>% 
  left_join(engy %>% select(Food_code,Water_g )) %>% 
  # calculate the water weight
  mutate(water_grams = round(gram_psu * Water_g/100, 2)) %>% 
  select(-Water_g)
```

```{r}
# organize the 142b smoothies 
psmoothie <- readxl::read_excel('../data/142b_batch1_diet_calories_check_subset_with_macros_peter.xlsx') %>% distinct()

# to see if the other ones are captured here
# yes! the cal and macronutrients and water are particularly vetted, cuz the different fruit smoothie even with the same food code can have vastly different values!!!!
# only the scandishakes are split cuz the milk are added separately!
other <- read_csv('../data/144_he ones that need to be merged back after Peter is done with the smoothies.csv') %>% 
  distinct(Food_NSC, Unit) %>% 
  left_join(psmoothie)

# combine the two tables (the scandi shakes are now split two entries per each recipe)
other2 <- bind_rows(
  other %>% filter(!is.na(description)),
  psmoothie %>% filter(str_detect(Food_NSC, '--'))
)

added5 <- setdiff(psmoothie$Food_NSC, other2$Food_NSC)

added5_df <- psmoothie %>% 
  filter(Food_NSC %in% added5) 

other3 <- bind_rows(other2, added5_df)  %>% 
  mutate(dehydrated_psu = weight_grams - water_grams) %>% 
  rename(cal_psu = Calories_kcal,
         gram_psu = weight_grams,
         Protein_psu = protein_grams,
         Carbohydrate_psu = carbohydrate_grams,
         Fat_psu = fat_grams,
         Fiber_psu = fiber_grams,
         Sugars_psu = sugar_grams,
         Water_psu = water_grams) %>% 
  select(-Por_eaten)


other3 %>% write_csv('../data/144_milkshake_smoothie_special_check_full.csv')
```



```{r}
# combine the above to make a whole table for batch 1 unique food_nsc + Unit (2110 + 130 = 2240)
# to get the other nutrients values from FNDDS for the currentgood
nutrients_fndds <- readxl::read_excel('../data/source/2015-2016 FNDDS At A Glance - FNDDS Nutrient Values.xlsx', skip = 1, col_types  = 'text') %>% 
  rename_all(funs(str_replace_all(., ' ','_'))) %>% 
  rename_all(funs(str_replace_all(., '\\(|\\)',''))) %>% 
  rename_all(funs(str_replace_all(., ',',''))) %>% 
  select(Food_code, 
         Protein_g, 
         Carbohydrate_g,
         Sugars_total_g, 
         Fiber_total_dietary_g,
         Total_Fat_g,   
         Water_g) %>% 
  mutate_if(is.character, as.numeric) %>% 
  mutate(Protein_per = Protein_g/100,
         Carbohydrate_per = Carbohydrate_g/100,
         Sugars_per = Sugars_total_g/100,
         Fiber_per = Fiber_total_dietary_g/100,
         Fat_per = Total_Fat_g/100,
         Water_per = Water_g/100)

currentgood_all <- currentgood %>% 
  left_join(nutrients_fndds %>% select(Food_code, ends_with('_per'))) %>% 
  mutate(Protein_psu = gram_psu * Protein_per,
         Carbohydrate_psu = gram_psu * Carbohydrate_per,
          Sugars_psu = gram_psu * Sugars_per,
          Fiber_psu = gram_psu * Fiber_per,
          Fat_psu = gram_psu * Fat_per) %>% 
  select(-ends_with('_per')) %>% 
  mutate(dehydrated_psu = gram_psu - water_grams)

colnames(currentgood_all)
```

```{r}
# I wanna see the comparison between the dry weight from cal and the dry weight from this
currentgood_all_compare <- currentgood_all %>% 
  distinct(Food_NSC, Food_code,Unit,  cal_psu, dehydrated_psu, gram_psu) %>% 
  left_join(engy , by = "Food_code") %>% 
  mutate(total_weight = if_else(Energy_kcal == 0, 99999, cal_psu/Energy_kcal*100)) %>% 
  mutate(dehydrated_convertion = if_else(total_weight == 99999, 0, total_weight*(1 - Water_g/100))) %>% 
  select(-Energy_kcal,  -Water_g) %>% 
  mutate(abs_diff = abs(dehydrated_psu - dehydrated_convertion)) %>% 
  rename(description = Main_food_description) %>% 
  arrange(desc(abs_diff)) %>% 
  relocate(abs_diff, .after = Food_code) %>% 
  select(Food_NSC, Food_code, Unit,  dehydrated_psu,  dehydrated_convertion, abs_diff)

currentgood_all_compare %>% 
  ggscatter(x = 'dehydrated_psu', y = 'dehydrated_convertion',xlab = 'total_g - water_g', ylab = 'dry weight converted from calories', add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "pearson",  label.sep = "\n"))

question <- currentgood_all_compare %>% 
  arrange(desc(dehydrated_psu)) %>% 
  slice(1)
```

```{r}
# after asking Peter to check the top abs_diff ones he said the dehydrated_psu is good to use!
# only need to change the food_code of one thing 
currentgood_all2 <- currentgood_all %>% 
  mutate(Food_code = if_else(Food_NSC == 'Chocolate-Flavored Drink,Whey and Milk Based, cup', 95106000, Food_code),
         description = if_else(Food_NSC == 'Chocolate-Flavored Drink,Whey and Milk Based, cup', 'Nutritional drink or shake, ready-to-drink (Muscle Milk)', description)) %>% 
  select(Food_NSC:description) %>% 
  left_join(nutrients_fndds %>% select(Food_code, ends_with('_per'))) %>% 
  mutate(Protein_psu = gram_psu * Protein_per,
         Carbohydrate_psu = gram_psu * Carbohydrate_per,
          Sugars_psu = gram_psu * Sugars_per,
          Fiber_psu = gram_psu * Fiber_per,
          Fat_psu = gram_psu * Fat_per,
         Water_psu = gram_psu * Water_per) %>% 
  select(-ends_with('_per')) %>% 
  mutate(dehydrated_psu = gram_psu - Water_psu) %>% 
  select(colnames(other3))

colnames(currentgood_all2)
```
```{r}
# finally combine the above two together to make a whole df with (2110 + 130 = 2240)
# yeah!!!!!
combined <- bind_rows(currentgood_all2, other3)
# to double check the number is it ok
# the unique combinations 
dtb_ %>% distinct(Food_NSC, Unit) %>% nrow
# it is Correct!! 6 of the items was split to 2 so the final number is 2234 + 6 = 2240!

combined %>% write_csv('../data/144_non_EN_unit_diet_metrics.csv')
```


```{r}
# the ones that are NA (not EN ones) and also the ones > 500 Kcal after scaling
# checkcc1 <- scale_all_combos %>% 
#   filter(is.na(scaled_cal)) %>% 
#   filter(Unit != 'EN unit') %>% 
#   arrange(Food_code) %>% 
#   select(Food_NSC:total_g)
# 
# checkcc1 %>% write_csv('../data/144_check_NA_ones.csv', na = '')
# 
# # just ask Peter to give me for one unit portion values 
# checkcc2 <- scale_all_combos %>% 
#   filter(scaled_cal > 500) %>% 
#   distinct(Food_NSC, Unit, .keep_all = T) %>% 
#   select(Food_NSC:Food_code, scaled_cal:scaled_total_g) %>% 
#   arrange(Food_code)
# 
# checkcc2 %>% write_csv('../data/144_check_cal>500_ones.csv', na = '')
```

```{r}
# %>% 
#   left_join(engy, by  = 'Food_code')

# scaled <- scale_all_combos %>% 
#   select(Food_NSC:Food_code, Calories_kcal = scaled_cal, total_g = scaled_total_g, description = Main_food_description, Water_g) %>% 
#   mutate(dehydrated_weight = total_g*(1-Water_g/100))

```

```{r}
psmoothie <- readxl::read_excel('../data/142b_batch1_diet_calories_check_subset_with_macros_peter.xlsx') %>% distinct()
psmoothie %>% distinct(Food_NSC)

unit <- read_csv('../data/148_both_batches_UNIT_table_EN_exclu.csv')
length(intersect(psmoothie$Food_NSC, unit$Food_NSC))
```

