---
title: "to see the survey food data"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rjson)
```

```{r}
#nutrients <- read_csv('~/Downloads/FoodData_Central_survey_food_csv_2022-10-28 2/food_nutrient.csv')
#portions <- read_csv('~/Downloads/FoodData_Central_survey_food_csv_2022-10-28 2/food_portion.csv')

# the below table has the matching of fdc_id and food_code and wweia_code
#matching <- read_csv('~/Downloads/FoodData_Central_survey_food_csv_2022-10-28 2/survey_fndds_food.csv')

fndds_json <- fromJSON(file = "~/Downloads/FoodData_Central_survey_food_json_2022-10-28 2.json")

test <- fndds_json[["SurveyFoods"]][[1]]
foodAttributes <- test[['foodAttributes']] # has the WWEIA code
foodNutrients <- test[['foodNutrients']]
names(test)
```

```{r}
foodCode <- test[['foodCode']] # a vector of a single food_code
startDate <- test[['startDate']] 
wweiaFoodCategory <- test[['wweiaFoodCategory']] # has the ID for the WWEIA code
foodPortions <- test[['foodPortions']] # has the gram weight for different measuring unit 
fdcId <- test[['fdcId']]
dataType <- test[['dataType']]

# It seems what really matters is the below:
# foodNutrients
# foodPortions
# foodCode
# foodAttributes

```

# to get the foodPortions values into a concatenated narrow long df

```{r}
# to get the id, gramWeight and portionDescription in each small list 
# to extract the three items out of each portion list
# to also add a column of food_code
foodCode <- test[['foodCode']]

portions_metric <- test %>% 
  pluck('foodPortions') %>% 
  map(function(por){
    ret = bind_cols(
      portion_id = por %>% pluck('id'),
      gramWeight = por %>% pluck('gramWeight'),
      portionDescription = por %>% pluck('portionDescription')
    )
  }) %>% bind_rows() %>% 
  mutate(Food_code = foodCode)
```

```{r}
# now repeat for every other survey food
all_portion_grams <- fndds_json %>% 
  pluck('SurveyFoods') %>% 
  map(function(every_food){
    foodCode <- every_food[['foodCode']]

    portions_grams <- every_food %>% 
      pluck('foodPortions') %>% 
      map(function(por){
        ret = bind_cols(
          portion_code = por %>% pluck('modifier'),
          gramWeight = por %>% pluck('gramWeight'),
          portionDescription = por %>% pluck('portionDescription')
        )
      }) %>% bind_rows() %>% 
      mutate(Food_code = foodCode)
    return(portions_grams)
  }) %>% bind_rows()

all_portion_grams %>% write_csv('../data/145_foodData_Central_all_portion_grams.csv')
```

# to get the nutrient value for each measuring unit for each food

So the json file only has the nutrient values for 100 gram of that food code 
same as this table: 2015-2016 FNDDS At A Glance - FNDDS Nutrient Values.xlsx
