---
title: "Scale the psu (unit portion diet metric) to the full data set and add EN"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
```

```{r}
dtb1 <- read_csv('../data/cleaned_diet_data/FINAL_97_with_code_all_foods_drt_with_EN_finalized.csv')

# there are some cleaning to do, possibly char change during manual work at the spreadsheet  
unit <- read_csv('../data/144_non_EN_unit_diet_metrics.csv')

# find about the portions and dates of the intake among the patients
dtb1_p <- dtb1 %>% 
  filter(Unit != 'EN unit') %>% 
  select(mrn:Unit,fdrt, Por_eaten) %>% 
  mutate(Por_eaten = if_else(Food_NSC == 'Specials, Angel Hair Pasta (2)', 0.75, Por_eaten),
         Unit = if_else(Food_NSC == 'Specials, Angel Hair Pasta (2)', 'cup', Unit))
```

```{r}
# I need to find a way to split the scandi shake ones 
scan_match <- unit %>% 
  filter(str_detect(Food_NSC, 'Scandi')) %>% 
  select(new_nsc =  Food_NSC) %>% 
  separate(new_nsc, into = c('Food_NSC','parts'), remove = F, sep = '--') %>% 
  select(-parts)

dtb1_p_scandi <- dtb1_p %>% 
  filter(str_detect(Food_NSC, 'Scandi')) %>% 
  right_join(scan_match) %>% 
  mutate(Food_NSC = new_nsc) %>% 
  select(-new_nsc) %>% 
  # change the unit for milk to be cup
  mutate(Unit = if_else(str_detect(Food_NSC, 'Milk') & Unit == 'each', 'cup', Unit))

dtb1_p2 <- bind_rows(
  dtb1_p %>% filter(!str_detect(Food_NSC, 'Scandi')),
  dtb1_p_scandi
)

# join the unit table and scale it to all the different portions
dtb1_scale <- dtb1_p2 %>% 
  left_join(unit, by = c("Food_NSC", "Unit")) %>% 
  # and then scale the correct portion's values
  mutate(Calories_kcal = Por_eaten * cal_psu,
         total_weight = Por_eaten * gram_psu,
         Protein_g = Por_eaten * Protein_psu,
         Fat_g = Por_eaten * Fat_psu,
         Carbohydrates_g = Por_eaten * Carbohydrate_psu,
         Fibers_g = Por_eaten * Fiber_psu,
         Sugars_g = Por_eaten * Sugars_psu,
         dehydrated_weight = Por_eaten * dehydrated_psu) %>% 
  select(-ends_with('psu'))
```

```{r}
# here is the calculation for the EN things
ptb <- read_csv('../data/cleaned_patients/diet_patients_97.csv')

# the below table has the updated calculations 
# and it is first calculate the volume for the solids and then convert that to the gram weight!
en <- readxl::read_excel('../data/cleaned_diet_data/NutritionSupport_DietPatients.xlsx') %>% 
  rename(Date = `Date Nutrition Support`) %>% 
  mutate(Date = as.numeric(Date)) %>% 
  mutate(Date = as.Date(Date, origin = "1899-12-30")) %>% 
  filter(`Nutrition Support` == 'EN' & MRN %in% ptb$mrn) %>% 
  left_join(ptb %>% select(MRN = mrn, hct), by = 'MRN') %>% 
  mutate(fdrt = Date - hct) %>% 
  mutate(fdrt = as.numeric(fdrt)) %>% 
  filter(fdrt %in%  5:49) %>% 
  rename_all(funs(str_replace_all(., ' ','_'))) %>% 
  mutate(EN_volume_weight_g = as.numeric(EN_volume_weight_g)) %>% 
  select(-starts_with('TPN')) %>% 
  # to make it more like the dtb format
  select(mrn = MRN, fdrt, Food_NSC = EN_formula, Por_eaten = EN_volume, Calories_kcal = EN_calories,
         Protein_g = EN_PRO, Fat_g = EN_fat, Carbohydrates_g = EN_CHO, Fibers_g = EN_Fiber, Sugars_g = EN_Sugar,
         Food_code = Food.Code, description = FNDDS.Main.Food.Description, dehydrated_weight = EN_volume_weight_g) %>% 
  mutate(Unit = 'ml', Meal = 'Enteral nutrition') %>% 
  mutate_at(c('mrn', 'fdrt','Por_eaten','Calories_kcal','Food_code','dehydrated_weight','Protein_g','Fat_g','Carbohydrates_g','Fibers_g','Sugars_g'), .funs = as.numeric) %>% 
  mutate(total_weight = Por_eaten * 1.05) %>%  # total weight = total_volume * 1.05g/ml
  select(colnames(dtb1_scale))



dtb1_N <- bind_rows(dtb1_scale , en)

dtb1_N %>% write_csv('../data/146_updated_dtb1.csv')
```


```{r}
# can do some sanity check on the unit table

```

