---
title: "scaling the batch 2 dtb"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

# scale the batch 2 dtb using the updated unit table

```{r}
dtb2 <- read_rds('../data/136_updated_dtb2.rds') %>% mutate(Food_code = as.numeric(Food_code))

unit <- read_csv('../data/148_both_batches_UNIT_table_EN_exclu.csv')

dtb2_p <- dtb2 %>% 
  select(mrn:Unit,fdrt, Por_eaten)

dtb2_scale <- dtb2_p %>% 
  left_join(unit, by = c("Food_NSC", "Unit")) %>% 
  # and then scale the correct portion's values
  mutate(Calories_kcal = Por_eaten * cal_psu,
         total_weight = Por_eaten * gram_psu,
         Protein_g = Por_eaten * Protein_psu,
         Fat_g = Por_eaten * Fat_psu,
         Carbohydrates_g = Por_eaten * Carbohydrate_psu,
         Fibers_g = Por_eaten * Fiber_psu,
         Sugars_g = Por_eaten * Sugars_psu,
         dehydrated_weight = Por_eaten * dehydrated_psu) %>% 
  select(-ends_with('psu'))

# write out this updated dtb2!!!!
dtb2_scale %>% write_csv('../data/149_finalized_dtb2.csv')
```

# scale the batch 1 dtb using the updated unit table

```{r}
dtb1 <- read_csv('../data/146_updated_dtb1.csv')

dtb1_p <- dtb1 %>% 
  filter(Meal != 'Enteral nutrition') %>% 
  select(mrn:Unit,fdrt, Por_eaten)

dtb1_scale <- dtb1_p %>% 
  left_join(unit, by = c("Food_NSC", "Unit")) %>% 
  # and then scale the correct portion's values
  mutate(Calories_kcal = Por_eaten * cal_psu,
         total_weight = Por_eaten * gram_psu,
         Protein_g = Por_eaten * Protein_psu,
         Fat_g = Por_eaten * Fat_psu,
         Carbohydrates_g = Por_eaten * Carbohydrate_psu,
         Fibers_g = Por_eaten * Fiber_psu,
         Sugars_g = Por_eaten * Sugars_psu,
         dehydrated_weight = Por_eaten * dehydrated_psu) %>% 
  select(-ends_with('psu')) %>% 
  select(colnames(dtb1))

dtb1_updated <- bind_rows(
  dtb1_scale,
  dtb1 %>% filter(Meal == 'Enteral nutrition')
)
dtb1_updated %>% write_csv('../data/149_finalized_dtb1.csv')

```

```{r}
dtb2 <- read_csv('../data/149_finalized_dtb2.csv')

day_calori <- dtb2 %>% 
  group_by(mrn, fdrt) %>% 
  summarise(daycal = sum(Calories_kcal))

# REMEMBER THAT IN AXIS LABLE YOU NEED TO TIMES THE 1000 BACK!!!!!!
day_cal <- day_calori %>% 
  mutate(daycal = daycal/1000) %>% 
  ggscatter(x = 'fdrt', y = 'daycal', alpha = alpha_val, size = point_size, pch = 16,
            xlab = 'Day relative to HCT',
            ylab = 'Daily caloric intake',
            title = 'Daily caloric intake',
            color = scatter_col,
             add = "loess", conf.int = TRUE, 
            add.params = list(color = diet_line_color, fill = "hotpink", size = 1)) +  
   scale_x_continuous( breaks = seq(0, 50, 20)) + 
  theme(axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        aspect.ratio=1)

ggsave('../data/149_daycal.png',width = 3, height = 3)
```

```{r}
faith2 <- read_tsv('../data/139_batch2_faith_pd/alpha-diversity.tsv') %>% 
  separate(...1, into = c('mrn', 'fdrt'), sep = '_', convert = T)  %>% 
  mutate(mrn = as.numeric(str_replace(mrn, 'P','')))

# REMEMBER THAT IN AXIS LABLE YOU NEED TO TIMES THE 1000 BACK!!!!!!
diet_alpha <- faith2 %>% 
  mutate(faith_pd = faith_pd/1000) %>% 
  ggscatter('fdrt', 'faith_pd', 
             alpha = alpha_val,size = point_size, 
            color = scatter_col, pch = 16, 
            ylab = 'Diet alpha diversity', 
            xlab = 'Day relative to HCT',
            title = 'Diet alpha diversity',
             add = "loess", conf.int = TRUE, 
            add.params = list(color = diet_line_color, fill = "hotpink", size = 1)) +
   scale_x_continuous( breaks = seq(0, 50, 20)) + 
  theme(axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        #plot.title = element_text(size=11, hjust = 0.5,  face = 'bold')
        ) + 
  theme(aspect.ratio=1)

ggsave('../data/149_alphadiet.png',width = 3, height = 3)
```

```{r}
m_all <- dtb2 %>%  
  select(mrn, fdrt,Protein_g:Sugars_g ) %>% 
  gather('grp','gram', Protein_g:Sugars_g) %>% 
  mutate(grp = str_replace(grp, '_g$','')) %>% 
  group_by(mrn, fdrt, grp) %>% 
  summarise(eachsum = sum(gram)) 

m_panel <- m_all %>% 
   ggscatter(x = 'fdrt', y = 'eachsum', alpha = 0.005, size = point_size, 
            xlab = 'Day relative to HCT',
            ylab = 'Grams',
            add = "loess", conf.int = TRUE, 
            add.params = list(color = diet_line_color, fill = "hotpink", size = 1))  +
  facet_wrap(~ grp, nrow = 1, scales = 'free_y') +
  scale_x_continuous( breaks = seq(0, 50, 20)) + 
  theme(axis.text=element_text(size=6),
        strip.background = element_blank(),
        strip.text.x = element_text(size = stip_txt_size), 
        axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        aspect.ratio=1)
m_panel
```

