---
title: "Prepare the mean microbe composition table and mean food counts table for every patient"
output: html_document 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
# get the stool cohort for these patients
stb <- read_csv('../data/finalized/stool/filter_stool_close_to_diet_meta.csv') %>% 
  filter(keep == 'keep')

nrow(stb)
```

# the mean microbe composition table 

```{r}
set.seed(1)  
source('~/db_connect_simple.R')
connect_database(config_file = '~/dbConfig.txt')
get_table_from_database_predefined_filter('asv_counts_ag')
ANNOT <- get_table_from_database('asv_annotation_blast_ag')
```

```{r}
cts <- asv_counts_ag %>% 
  filter(sampleid %in% stb$sampleid) %>% 
  select(asv_key, sampleid, count) %>% 
  spread(key = 'sampleid', value = 'count', fill = 0) %>% 
  arrange(asv_key)  


annot <- ANNOT %>% 
  filter(asv_key %in% cts$asv_key) %>% 
  mutate(ordr =  if_else(ordr == '', str_glue('of_class_{class}'), ordr),
         family =  if_else(family == '', str_glue('of_order_{ordr}'), family),
         genus =  if_else(genus == '', str_glue('of_family_{family}'), genus),
         species =  if_else(species == '', str_glue('of_genus_{genus}'), species)) %>% 
  mutate(taxa_species = str_glue('k__{kingdom}|p__{phylum}|c__{class}|o__{ordr}|f__{family}|g__{genus}|s__{species}'))


# replace the asv_key with the genus taxa level
# summarize from asv level to genus level
# get the relative abundance for the genera
cts_all <- cts %>% 
  full_join(annot %>%  select(asv_key, taxa_species), by  = 'asv_key') %>% 
  select(-asv_key) %>% 
  gather(key = 'sampleid', value = 'count', names(.)[1]:names(.)[ncol(.) - 1]) %>% 
  group_by(sampleid, taxa_species) %>% 
  summarise(cnt = sum(count)) %>% 
  # get the total count from the db to calculate the relab
  left_join(asv_counts_ag %>% distinct(sampleid,count_total ), by = 'sampleid') %>% 
  mutate(relab = cnt/count_total) %>% 
  select(sampleid, taxa_species, relab) %>% 
  left_join(stb %>% select(mrn, sampleid), by = 'sampleid') %>% 
  # get the mean relab for the species for every pt
  group_by(mrn, taxa_species) %>% 
  summarise(mean_relab = mean(relab)) %>% 
  ungroup() %>% 
  # deidentify here
  mutate(mrn = as.numeric(as.factor(mrn))) %>% 
  mutate(mrn = str_glue("P{str_pad(mrn, 3, 'left', '0')}")) %>% 
  spread(key = 'mrn', value = 'mean_relab', fill = 0)


cts_all %>% 
  write_tsv('../data/finalized/stool/mean_microbe_relab_per_pt.tsv')

# and then following will be going to snakefile to do the qiime way. 
```

# the mean food counts table 

```{r}
final <- read_csv('../data/finalized/all_patients_record_w_food_code.csv')

food_mean <- final %>% 
  select(mrn, Food_code, dehydrated_weight) %>% 
  group_by(mrn, Food_code) %>% 
  summarise(mean_dewt = mean(dehydrated_weight)) %>% 
  ungroup() %>% 
  # deidentify here
  mutate(mrn = as.numeric(as.factor(mrn))) %>% 
  mutate(mrn = str_glue("P{str_pad(mrn, 3, 'left', '0')}")) %>% 
  spread(key = 'mrn', value = 'mean_dewt', fill = 0)

food_mean %>% 
  write_tsv('../data/finalized/mean_foodID_dehydrated_weight_per_pt.tsv')

# and then go to qiime and do something simimlar to the microbe
```

# the meta to go with the emperor vis, need to deidentify

```{r}
# i don't need any specific grouping gonna just put the fake mrn there
meta <- read_tsv('../data/finalized/meta_data_67.tsv') %>% 
  mutate(mrn = as.numeric(as.factor(mrn))) %>% 
  mutate(mrn = str_glue("P{str_pad(mrn, 3, 'left', '0')}")) %>% 
  distinct(mrn) %>% 
  arrange(mrn) %>% 
  rename(sampleid = mrn) 

meta %>% 
  write_tsv('../data/finalized/pheno/meta_food_deID_67.tsv')
```


# doing procrustes myself using vegan package

```{r}
library(vegan)

# I should be able to use the pcoa produced by qiime right .
# the ordination.txt contains a list of values and I need to extract the "sites"
food_pcoa <- read_tsv('../data/finalized/mean_foodID_dehydrated_weight_per_pt_unweighted_unifrac_pcoa/ordination.txt', skip = 9, col_names = F)  %>% 
  filter(! X1 %in% c('Biplot','Site constraints')) %>% 
  column_to_rownames('X1') %>% 
  as.matrix()

microbe_pcoa <- read_tsv('../data/finalized/stool/mean_microbe_relab_per_pt_braycurtis_pcoa/ordination.txt', skip = 9, col_names = F)  %>% 
  filter(! X1 %in% c('Biplot','Site constraints')) %>% 
  column_to_rownames('X1') %>% 
  as.matrix()

# the procrustes
pro.mean <- procrustes(food_pcoa, microbe_pcoa)
pro.mean
```


```{r}
plot(pro.mean, kind = 1) 
plot(pro.mean, kind = 2)

protest_mean <- protest(X = food_pcoa, Y = microbe_pcoa,  permutations = 999)
protest_mean 

protest_mean$symmetric
```

# recreat the stretching plot in ggplot

```{r}

```

