---
title: "same day batch 2 stool food correlation"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
```

```{r}
stb2 <- read_rds('../data/137_stb.rds')
dtb2 <- read_csv('../data/149_finalized_dtb2.csv')
```


```{r}
# get the genus counts
library(vdbR)
connect_database()
get_table_from_database('asv_annotation_blast_ag')

cts <- get_counts_subset(stb2$sampleid)


cts_genus <- cts %>% 
  inner_join(asv_annotation_blast_ag %>%  select(asv_key, genus), by  = 'asv_key') %>% 
  group_by(sampleid, genus) %>% 
  summarise(relab = sum(count_relative)) 

cts_spread <- cts_genus %>% 
  spread('genus', 'relab', fill = 0)

cts_genus %>% 
  write_csv('../data/150_b2_stool_samples_genus_counts.csv')

# log10 transform the genus counts 
zero_transform <- log10(0 + 2*10^-6)

genus <- cts_genus %>% 
  mutate(relablog = log10(relab + 2*10^-6)) %>% 
  select(sampleid, genus, relablog) %>% 
  spread('genus', 'relablog', fill = zero_transform) 
 
genus %>% 
  write_csv('../data/150_b2_genus_relab_log10_wide.csv')
```

```{r}
genus <- read_csv('../data/150_b2_genus_relab_log10_wide.csv')

byday_original2 <- dtb2 %>% 
  group_by(mrn, fdrt) %>% 
  summarise(daycal = sum(Calories_kcal),
            d_protein = sum(Protein_g),
            d_fat = sum(Fat_g),
            d_carb = sum(Carbohydrates_g),
            d_fiber = sum(Fibers_g),
            d_sugar = sum(Sugars_g)) %>% 
  rename(drt = fdrt) %>% 
  inner_join(genus %>% 
               inner_join(stb2 %>% select(sampleid, drt = sdrt, mrn, simpson_reciprocal, intensity)), 
             by = c("mrn", "drt")) %>% 
  ungroup()

# pooled the two batches together same day match between food and stool
byday_original <- bind_rows(byday_original1, byday_original2)
```

```{r}
macro_panel <- byday_original %>% 
  mutate(simpson_reciprocal_nlog  = log(simpson_reciprocal)) %>% 
  rename(`log10(Blautia)` = Blautia,
         `log10(Enterococcus)` = Enterococcus,
         `log(Simpson reciprocal)` = simpson_reciprocal_nlog) %>% 
  dplyr::select(`log(Simpson reciprocal)`, `log10(Blautia)`, `log10(Enterococcus)`,  daycal:d_sugar ) %>% 
  mutate(daycal = daycal/1000) %>%  # now divide the value by 1000 to save some space in x axis text!!! 
  gather('yaxis', 'value', `log(Simpson reciprocal)`:`log10(Enterococcus)`) %>% 
  mutate(yaxis = factor(yaxis, levels = c('log(Simpson reciprocal)','log10(Blautia)','log10(Enterococcus)'))) %>% 
  gather('xaxis', 'number', daycal:d_sugar) %>% 
  mutate(xaxis = factor(xaxis, levels = c('daycal','d_carb','d_sugar','d_fiber','d_protein','d_fat'))) %>% 
  mutate(xaxis = if_else(str_detect(xaxis, '^d_'), str_replace(xaxis, 'd_',''), str_replace(xaxis, '^day','')),
         xaxis = if_else(str_detect(xaxis, 'cal'), str_replace(xaxis, 'cal','calorie'), xaxis),
         xaxis = if_else(str_detect(xaxis, 'carb'), str_replace(xaxis, 'carb','carbohydrate'), xaxis),
         xaxis = str_to_title(xaxis),
         xaxis = str_glue('{xaxis}')) %>% 
  mutate(xaxis = factor(xaxis, levels = c('Calorie','Carbohydrate','Sugar','Fiber','Protein','Fat')))
```

```{r}
library(facetscales)
Blautia_lim <- floor(min(byday_original$Blautia))
entero_lim <- floor(min(byday_original$Enterococcus))
simpson_reciprocal_nlog_lim <- max(log(byday_original$simpson_reciprocal))

scales_y <- list(
  `log(Simpson reciprocal)` = scale_y_continuous(limits = c(0, simpson_reciprocal_nlog_lim), breaks = seq(0, simpson_reciprocal_nlog_lim, 1)),
  `log10(Blautia)` = scale_y_continuous(limits = c(Blautia_lim, 0), breaks = seq(Blautia_lim, 0, 2)),
  `log10(Enterococcus)` = scale_y_continuous(limits = c(entero_lim, 0), breaks = seq(entero_lim, 0, 2))
)

# to use the max observed in the data
cal_lim <- max(byday_original$daycal)/1000
protein_lim <- max(byday_original$d_protein)
d_fat_lim <- max(byday_original$d_fat)
d_carb_lim <- max(byday_original$d_carb)
d_fiber_lim <- max(byday_original$d_fiber)
d_sugar_lim <- max(byday_original$d_sugar)

scales_x <- list(
  `Calorie` = scale_x_continuous(limits = c(0, cal_lim), breaks = seq(0, cal_lim, 1)),
  `Protein` = scale_x_continuous(limits = c(0, protein_lim), breaks = seq(0, protein_lim, 50)),
  `Fat` = scale_x_continuous(limits = c(0, d_fat_lim), breaks = seq(0, d_fat_lim, 100)),
  `Carbohydrate` = scale_x_continuous(limits = c(0, d_carb_lim), breaks = seq(0, d_carb_lim, 250)),
  `Fiber` = scale_x_continuous(limits = c(0,d_fiber_lim), breaks = seq(0, d_fiber_lim, 20)),        
  `Sugar` = scale_x_continuous(limits = c(0, d_sugar_lim), breaks = seq(0, d_sugar_lim, 100) )
)
```


```{r}
macro_facets <- macro_panel %>% 
  ggscatter(x = 'number', y = 'value', alpha = 0.002, xlab = '', ylab = '',size = 1.2, shape = 16,
             add = "reg.line",  # Add regressin line
           add.params = list(color = "darkblue", fill = "gray59"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = ", ",label.x.npc = "left", label.y.npc = "bottom", cor.coef.name = c("rho"), size = 2, p.accuracy = 0.01, r.accuracy = 0.01)) +
  facet_grid_sc(rows = vars(yaxis), cols = vars(xaxis), scales = list(y = scales_y, x = scales_x)) +
  theme_classic(base_size = 11) +
  theme(aspect.ratio = 1,
        panel.background = element_rect(fill = "gray97"),axis.title=element_text(size=axis_title_size),
        plot.title = element_text(size=axis_title_size),
        panel.grid.major = element_blank(), 
        strip.background = element_rect(color="white", fill=strip_color, size=1.5,linetype="solid"),
        panel.grid.minor = element_blank()
       )
macro_facets
```


```{r}
ggsave('../data/151_combined_sameday_macronutrients_microbiome.pdf', 
       width = 180, height = 150,
       units = c("mm"),
       plot = macro_facets)
macro_facets %>% write_rds('../data/151_macro_facets.RDS')
```




```{r}
# since I need to annotate the p value of the slope I can't do it in facet wrap
# need to manually arrange them
# calculate the p value of the slopes
pvals <- macro_panel %>% 
  split(., list(.$xaxis, .$yaxis)) %>% 
  map(function(df) {
    res = summary(lm(value ~ number, data = df ))
    return(pval = round(res$coefficients[2, 'Pr(>|t|)'], 3))
  })
 
test <- macro_panel %>% 
  split(., list(.$xaxis, .$yaxis)) %>% 
  pluck('Carb.log10(Blautia)')

spearman_cor = round(cor(test$number, test$value, method = c( "spearman")), 2)
cortest <- cor.test(test$number, test$value, method = c( "spearman"))
```

```{r}
# to split to make each small panel so that I can annotate the p value from the lm and the spearman
combined_split_each_fig <- macro_panel %>% 
  split(., list(.$xaxis, .$yaxis)) %>% 
    imap(function(.x, .y){
      res = summary(lm(value ~ number, data = .x ))
      pval = round(res$coefficients[2, 'Pr(>|t|)'], 2)
      
      # the spearman correlation
      spearman_cor = cor.test(.x$number, .x$value, method = c( "spearman"))
      spearman_rho = round(spearman_cor$estimate, 2)
      spearman_pval = round(spearman_cor$p.value , 2)
      
      ggscatter(data = .x,x = 'number', y = 'value', alpha = 0.1, xlab ='', 
                ylab = '',size = 1.2, pch = 19, 
                title =  str_glue('{.y}\nlm pval: {pval}\nRho: {spearman_rho}\nrank pval:{spearman_pval}'),
                 add = "reg.line",  # Add regressin line
               add.params = list(color = "darkblue", fill = "gray59"), # Customize line
               conf.int = TRUE, # Add confidence interval
              ) +
      #facet_grid_sc(rows = vars(yaxis), cols = vars(xaxis), scales = list(y = scales_y, x = scales_x)) +
      theme_classic(base_size = 11) +
      theme(aspect.ratio = 1,
            panel.background = element_rect(fill = "gray97"),
            panel.grid.major = element_blank(), 
            plot.title = element_text(size=10),
            #strip.background = element_blank(),
            #strip.text = element_blank(),
            panel.grid.minor = element_blank()
           )
    })

g <- cowplot::plot_grid(combined_split_each_fig[[1]],combined_split_each_fig[[2]],combined_split_each_fig[[3]],combined_split_each_fig[[4]],combined_split_each_fig[[5]],combined_split_each_fig[[6]],combined_split_each_fig[[7]],combined_split_each_fig[[8]],combined_split_each_fig[[9]],combined_split_each_fig[[10]],combined_split_each_fig[[11]],combined_split_each_fig[[12]],combined_split_each_fig[[13]],combined_split_each_fig[[14]],combined_split_each_fig[[15]],combined_split_each_fig[[16]],combined_split_each_fig[[17]],combined_split_each_fig[[18]],
    ncol = 6,
    o = 'hv',labels = '',label_y = -2,
    #labels = 'AUTO',
    axis = 'bltr')  
ggsave(str_glue('../data/151_sameday__combined.jpg'), width = 12, height = 8,  plot = g)
```



# split them both combined to the three conditioning levels

```{r}
split3 <- byday_original %>% 
  split(.$intensity) %>% 
  map(function(small_df){
    small_panel <- small_df %>% 
        mutate(simpson_reciprocal_nlog  = log(simpson_reciprocal)) %>% 
        rename(`log10(Blautia)` = Blautia,
               `log10(Enterococcus)` = Enterococcus,
               `log(Simpson reciprocal)` = simpson_reciprocal_nlog) %>% 
        dplyr::select(`log(Simpson reciprocal)`, `log10(Blautia)`, `log10(Enterococcus)`,  daycal:d_sugar ) %>% 
        mutate(daycal = daycal/1000) %>%  # now divide the value by 1000 to save some space in x axis text!!! 
        gather('yaxis', 'value', `log(Simpson reciprocal)`:`log10(Enterococcus)`) %>% 
        mutate(yaxis = factor(yaxis, levels = c('log(Simpson reciprocal)','log10(Blautia)','log10(Enterococcus)'))) %>% 
        gather('xaxis', 'number', daycal:d_sugar) %>% 
        mutate(xaxis = factor(xaxis, levels = c('daycal','d_carb','d_sugar','d_fiber','d_protein','d_fat'))) %>% 
        mutate(xaxis = if_else(str_detect(xaxis, '^d_'), str_replace(xaxis, 'd_',''), str_replace(xaxis, '^day','')),
               xaxis = if_else(str_detect(xaxis, 'cal'), str_replace(xaxis, 'cal','calorie'), xaxis),
               xaxis = str_to_title(xaxis),
               xaxis = str_glue('{xaxis}')) %>% 
        mutate(xaxis = factor(xaxis, levels = c('Calorie','Carb','Sugar','Fiber','Protein','Fat')))
    
    small_panel_split_each <- small_panel %>%  split(., list(.$xaxis, .$yaxis)) 
    
  
    small_panel_split_each_fig <- small_panel_split_each %>% 
    imap(function(.x, .y){
      res = summary(lm(value ~ number, data = .x ))
      pval = round(res$coefficients[2, 'Pr(>|t|)'], 2)
      
      # the spearman correlation
      spearman_cor = cor.test(.x$number, .x$value, method = c( "spearman"))
      spearman_rho = round(spearman_cor$estimate, 2)
      spearman_pval = round(spearman_cor$p.value , 2)
      
      ggscatter(data = .x,x = 'number', y = 'value', alpha = 0.1, xlab ='', 
                ylab = '',size = 1.2, pch = 19, 
               title =  str_glue('{.y}\nlm pval: {pval}\nRho: {spearman_rho}\nrank pval:{spearman_pval}'),
                 add = "reg.line",  # Add regressin line
               add.params = list(color = "darkblue", fill = "gray59"), # Customize line
               conf.int = TRUE, # Add confidence interval
              ) +
      #facet_grid_sc(rows = vars(yaxis), cols = vars(xaxis), scales = list(y = scales_y, x = scales_x)) +
      theme_classic(base_size = 11) +
      theme(aspect.ratio = 1,
            panel.background = element_rect(fill = "gray97"),
            panel.grid.major = element_blank(), 
            plot.title = element_text(size=10),
            #strip.background = element_blank(),
            #strip.text = element_blank(),
            panel.grid.minor = element_blank()
           )
    })
         
  })

# assemble figure
```


```{r}
ablatives <- split3[['ablative']]


g <- cowplot::plot_grid(ablatives[[1]],ablatives[[2]],ablatives[[3]],ablatives[[4]],ablatives[[5]],ablatives[[6]],ablatives[[7]],ablatives[[8]],ablatives[[9]],ablatives[[10]],ablatives[[11]],ablatives[[12]],ablatives[[13]],ablatives[[14]],ablatives[[15]],ablatives[[16]],ablatives[[17]],ablatives[[18]],
    ncol = 6,
    o = 'hv',labels = 'Ablative',label_y = -2,
    #labels = 'AUTO',
    axis = 'bltr')  

ggsave(str_glue('../data/151_sameday_combined_conditioning_ablative.jpg'), width = 12, height = 8,  plot = g)


```

```{r}
nonablative <- split3[['nonablative']]


g <- cowplot::plot_grid(nonablative[[1]],nonablative[[2]],nonablative[[3]],nonablative[[4]],nonablative[[5]],nonablative[[6]],nonablative[[7]],nonablative[[8]],nonablative[[9]],nonablative[[10]],nonablative[[11]],nonablative[[12]],nonablative[[13]],nonablative[[14]],nonablative[[15]],nonablative[[16]],nonablative[[17]],nonablative[[18]],
    ncol = 6,
    o = 'hv',labels = 'Nonablative',label_y = -2,
    #labels = 'AUTO',
    axis = 'bltr') 

ggsave(str_glue('../data/151_sameday_combined_conditioning_nonablative.jpg'), width = 12, height = 8,  plot = g)
```
```{r}
reduced <- split3[['reduced']]

g <- cowplot::plot_grid(reduced[[1]],reduced[[2]],reduced[[3]],reduced[[4]],reduced[[5]],reduced[[6]],reduced[[7]],reduced[[8]],reduced[[9]],reduced[[10]],reduced[[11]],reduced[[12]],reduced[[13]],reduced[[14]],reduced[[15]],reduced[[16]],reduced[[17]],reduced[[18]],
    ncol = 6,
    o = 'hv',labels = 'reduced',label_y = -2,
    #labels = 'AUTO',
    axis = 'bltr') 

ggsave(str_glue('../data/151_sameday_combined_conditioning_reduced.jpg'), width = 12, height = 8,  plot = g)
```

