---
title: "food groups to different conditioning"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(brms)   
library(tidybayes)
library(cowplot)
theme_set(theme_tidybayes() + panel_border())
ncores <- parallel::detectCores()
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')
axis_text_size <- 10
axis_title_size <- 10
```

```{r}
meta2 <- read_csv('../data/138_meta2.csv') %>% 
  select(sampleid:fg_veggie)

STB <- read_csv('../data/152_combined_STB.csv')

meta1 <- read_csv('../data/046_meta1.csv') %>% 
  select(sampleid:fg_veggie)

META <- bind_rows(meta1, meta2) %>% 
  full_join(STB, by = "sampleid") %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left'))

META %>% write_csv('../data/153_combined_META.csv')
```

```{r}
# histogram of the alpha of two batches along time
META %>% 
  gghistogram( x = 'simpson_reciprocal', bins = 50) +
  facet_grid(batch~ intensity)

ggsave('../data/153_alpha_conditioning.pdf')

META %>% 
  ggboxplot( x = 'timebin', y = 'simpson_reciprocal', add = 'jitter') +
  facet_grid(batch~ intensity) +
  theme(axis.text.x = element_text(angle = 90)) 
ggsave('../data/153_timebin_alpha.pdf', width = 10)

```

# the function that takes a df of *meta* and then saves the prior and the post df

```{r}
model_formular <- log(simpson_reciprocal) ~ 0 + 
                fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               intensity +
               empirical+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin)

priors <- c(# for the food group variables
            prior(normal(0, 1), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie"),
            # for the TPN 
            prior(normal(0, 0.1), class = 'b', coef = "TPNTRUE"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "ENTRUE"),
            # for the empirical 
            prior(normal(0, 0.5), class = 'b', coef = "empiricalTRUE"),
            # for the intensity 
            prior(normal(2, 0.1), class = 'b', coef = "intensityreduced"),
            prior(normal(2, 0.1), class = 'b', coef = "intensityablative"),
            prior(normal(2, 0.1), class = 'b', coef = "intensitynonablative"))
```


```{r}
run_fg_model <- function(meta_df, meta_df_name) {
  model_div = brm( model_formular,  
              data = meta_df, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
               control = list(adapt_delta = 0.99),
              seed = 123, sample_prior = T) 
  
  post_res = suppressWarnings(posterior_samples(model_div))
  post_res %>%  write_csv(str_glue('../data/153_model_fg_post_{meta_df_name}.csv'))
  prior_df <- prior_draws(model_div) 
  prior_df %>% write_csv(str_glue('../data/153_model_fg_prior_{meta_df_name}.csv'))
}


```

```{r}
META_mod <- META %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = factor(mrn)) %>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100)
```

```{r}
# pooled two batches 
test <- run_fg_model(META_mod, 'all2')

# each batch individually
META_mod %>% 
  split(.$batch) %>% 
  imap(function(.x, .y){
    run_fg_model(.x, .y)
  })
```

```{r}
model_formular_for_each_conditioning_level <-  log(simpson_reciprocal) ~ 
                fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               #intensity +
               empirical+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin)

priors_without_conditioning <- c(# for the food group variables
            prior(normal(0, 1), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie"),
            # for the TPN 
            prior(normal(0, 0.1), class = 'b', coef = "TPNTRUE"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "ENTRUE"),
            # for the empirical 
            prior(normal(0, 0.5), class = 'b', coef = "empiricalTRUE"),
            # for the intensity 
            prior(normal(2, 0.1), class = 'Intercept'))

run_fg_model_for_each_conditioning_level <- function(meta_df, meta_df_name) {
  model_div = brm( model_formular_for_each_conditioning_level,  
              data = meta_df, 
              warmup = 1000, iter = 3000, 
              prior = priors_without_conditioning,
              cores = ncores, 
              chains = 2, 
               control = list(adapt_delta = 0.99),
              seed = 123, sample_prior = T) 
  
  post_res = suppressWarnings(posterior_samples(model_div))
  post_res %>%  write_csv(str_glue('../data/153_model_fg_post_conditioning_{meta_df_name}.csv'))
  prior_df <- prior_draws(model_div) 
  prior_df %>% write_csv(str_glue('../data/153_model_fg_prior_conditioning_{meta_df_name}.csv'))
}

get_prior(model_formular_for_each_conditioning_level, data = META_mod)
```


```{r}
# pooled two batches and split on conditioning
META_mod %>% 
  split(.$intensity) %>% 
  imap(function(.x, .y){
    run_fg_model_for_each_conditioning_level(.x, .y)
  })
```

```{r}
# split on conditioning for each batch 
META_mod %>% 
  split(., list(.$batch, .$intensity)) %>% 
  imap(function(.x, .y){
    run_fg_model_for_each_conditioning_level(.x, .y)
  })
```

# plot the results

```{r}
test <- read_csv('../data/153_model_fg_post_all2.csv')
```

```{r}
plot_all_diversity_results <- function(fn, post_df_name){
  post_df <- read_csv(fn)
  post_coeff <- post_df %>% 
        select(starts_with('b_fg')) %>% 
        gather('item', 'coeff') %>% 
        mutate(item = str_replace(item, 'b_fg_','')) %>% 
         mutate(fgrp1 = case_when(
          item ==  'milk' ~ '1',
          item == 'meat' ~ '2',
          item ==  'egg' ~ '3',
          item ==  'legume' ~ '4',
          item == 'grain' ~ '5',
          item == 'fruit' ~ '6',
          item == 'veggie' ~ '7',
          item ==  'oils' ~ '8', 
          item ==  'sweets' ~ '9'
        ))  %>% 
        left_join(key %>% select(fgrp1, color, shortname))  %>% 
        mutate(shortname = fct_reorder(shortname, coeff, .fun=median, .desc = F)) 
      
      fg_labels <- levels(post_coeff$shortname)
      
      
      cross0 <- post_coeff %>%
        group_by(item) %>% 
        summarise(q5 = quantile(coeff, probs = 0.05),
                  q95 = quantile(coeff, probs = 0.95)) %>% 
        mutate(Cross = if_else(q5 > 0 | q95 < 0, F, T))
      
      div_post <- post_coeff %>% 
        left_join(cross0) %>% 
        ggplot(aes(x = coeff, y = shortname, col = Cross)) +
        stat_pointinterval(.width = c(.66, .9)) +
        geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
        labs(x = 'ln(diversity) change per 100g of food',
             y = '', 
             title = 'Diversity') +
        theme_classic() +
        theme(legend.position = 'none') +
       scale_color_manual(values = c( "#EC0000", "gray40")) +
        theme(axis.text=element_text(size=8, color  = 'black'),
              axis.title=element_text(size=8),
              aspect.ratio=1)
      
      coeff_bi <- post_df %>% 
        select(starts_with('b_')) %>% 
        select(!starts_with('b_fg')) %>% 
        gather('item', 'coeff') %>% 
        mutate(item_name = case_when(
          item ==  'b_intensitynonablative' ~ 'Intensity: nonablative',
          item == 'b_intensityablative' ~ 'Intensity: ablative',
          item ==  'b_intensityreduced' ~ 'Intensity: reduced',
          item ==  'b_empiricalTRUE' ~ 'Empirical abx exposure',
          item == 'b_TPNTRUE' ~ 'TPN exposure',
          item ==  'b_ENTRUE' ~ 'EN exposure'
        )) %>% 
        mutate(item_name = factor(item_name, levels = c('Intensity: nonablative', 'Intensity: reduced',
                                                        'Intensity: ablative', 'TPN exposure','EN exposure',
                                                        'Empirical abx exposure'))) %>% 
        mutate(grp = if_else(str_detect(item_name, 'Intensity'), 'Patient level', 'Sample level'))
      
      # modify it to be the look that we have discussed
      diversity_factor <- coeff_bi %>% 
        ggplot(aes(x = coeff, y = item_name)) +
        stat_pointinterval(.width = c(.66, .9)) +
        #scale_color_manual(values = c('#EC0000','#00468B')) +
        geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
        facet_wrap(grp~ . , scales = 'free', dir = 'v') +
        labs(x = 'Coefficients',
             y = 'Factor variables',
             title = 'Diversity') +
        theme_classic() +
        theme(legend.position = 'none',
              strip.background = element_blank(),
              strip.text = element_blank(),
              axis.text=element_text(size=8, color  = 'black'),
              axis.title=element_text(size=8),
              aspect.ratio=1/2) 
      
      res = cowplot::plot_grid(div_post, diversity_factor, nrow = 1, align = 'tblr', axis = 'hv' )
      ggsave(str_glue('../data/153_post_combined_{post_df_name}_90.pdf'), width = 8, height = 6)
}
```

```{r}
fns <- c('../data/153_model_fg_post_all2.csv','../data/153_model_fg_post_batch1.csv','../data/153_model_fg_post_batch2.csv')

namesfns <- c('all2','batch1','batch2')
names(fns) <- namesfns

fns %>% 
  imap(function(.x, .y){
    plot_all_diversity_results(.x, .y)
  })
```

```{r}
plot_split_res <- function(fn, df_name){
 post_df <- read_csv(fn)
 post_coeff <- post_df %>% 
        select(starts_with('b_fg')) %>% 
        gather('item', 'coeff') %>% 
        mutate(item = str_replace(item, 'b_fg_','')) %>% 
         mutate(fgrp1 = case_when(
          item ==  'milk' ~ '1',
          item == 'meat' ~ '2',
          item ==  'egg' ~ '3',
          item ==  'legume' ~ '4',
          item == 'grain' ~ '5',
          item == 'fruit' ~ '6',
          item == 'veggie' ~ '7',
          item ==  'oils' ~ '8', 
          item ==  'sweets' ~ '9'
        ))  %>% 
        left_join(key %>% select(fgrp1, color, shortname))  %>% 
        mutate(shortname = fct_reorder(shortname, coeff, .fun=median, .desc = F)) 
      
      fg_labels <- levels(post_coeff$shortname)
      
      
      cross0 <- post_coeff %>%
        group_by(item) %>% 
        summarise(q5 = quantile(coeff, probs = 0.05),
                  q95 = quantile(coeff, probs = 0.95)) %>% 
        mutate(Cross = if_else(q5 > 0 | q95 < 0, F, T))
      
      div_post <- post_coeff %>% 
        left_join(cross0) %>% 
        ggplot(aes(x = coeff, y = shortname)) +
        stat_pointinterval(.width = c(.66, .95)) +
        geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
        labs(x = 'ln(diversity) change per 100g of food',
             y = '', 
             title = 'Diversity') +
        theme_classic() +
        theme(legend.position = 'none') +
       # scale_color_manual(values = c("gray40", "#EC0000")) +
        theme(axis.text=element_text(size=8, color  = 'black'),
              axis.title=element_text(size=8),
              aspect.ratio=1)
      
      coeff_bi <- post_df %>% 
        select(starts_with('b_')) %>% 
        select(!starts_with('b_fg')) %>% 
        gather('item', 'coeff') %>% 
        mutate(item_name = case_when(
          item ==  'b_Intercept' ~ 'Intercept',
          item ==  'b_empiricalTRUE' ~ 'Empirical abx exposure',
          item == 'b_TPNTRUE' ~ 'TPN exposure',
          item ==  'b_ENTRUE' ~ 'EN exposure'
        )) %>% 
        mutate(item_name = factor(item_name, levels = c('Intercept',  'TPN exposure','EN exposure',
                                                        'Empirical abx exposure'))) %>% 
        mutate(grp = if_else(str_detect(item_name, 'Intercept'), 'Patient level', 'Sample level'))
      
      # modify it to be the look that we have discussed
      diversity_factor <- coeff_bi %>% 
        ggplot(aes(x = coeff, y = item_name)) +
        stat_pointinterval(.width = c(.66, .95)) +
        #scale_color_manual(values = c('#EC0000','#00468B')) +
        geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
        facet_wrap(grp~ . , scales = 'free', dir = 'v') +
        labs(x = 'Coefficients',
             y = 'Factor variables',
             title = 'Diversity') +
        theme_classic() +
        theme(legend.position = 'none',
              strip.background = element_blank(),
              strip.text = element_blank(),
              axis.text=element_text(size=8, color  = 'black'),
              axis.title=element_text(size=8),
              aspect.ratio=1/2) 
      
      res = cowplot::plot_grid(div_post, diversity_factor, nrow = 1, align = 'tblr', axis = 'hv' )
      ggsave(str_glue('../data/153_post_conditioning_{df_name}.pdf'), width = 8, height = 6)
}
tibble(
  fn = list.files('../data/', pattern = '153_model_fg_post_conditioning', full.names = T)
) %>% mutate(names = str_replace(fn, '../data//153_model_fg_post_','')) %>% 
  select(names, fn) %>% 
  deframe %>% 
  imap(function(.x, .y){
    plot_split_res(.x, .y)
  })




```
```{r}
META <- read.csv()
```

