---
title: "eight versions of panel L"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
```

```{r}
unit <- read_csv('../data/148_both_batches_UNIT_table_EN_exclu.csv')

en_unit <- DTB %>% filter(Meal == 'Enteral nutrition') %>% 
  mutate(description = if_else(Food_NSC == 'Suplena 1.8', 'Enteral formula, suplena', description)) %>% 
  distinct(Food_NSC,Unit, Food_code, description, .keep_all = T) %>% 
  mutate(protein_per_g = Protein_g/dehydrated_weight,
         fat_per_g = Fat_g/dehydrated_weight,
         Carbohydrate_per_g = Carbohydrates_g/dehydrated_weight,
         Fiber_per_g = Fibers_g/dehydrated_weight,
         Sugars_per_g = Sugars_g/dehydrated_weight) %>% 
  select(Food_NSC, Food_code, description, ends_with('per_g'))  %>% 
  split(.$Food_code) %>% 
  map_dfr(function(eachcode ){
    eachcode %>% mutate(id = seq(nrow(eachcode)))
  }) %>% 
  mutate(new_code = str_glue('{Food_code}_{id}')) %>% 
  select(-id)

```

```{r}
psmoothie <- readxl::read_excel('../data/142b_batch1_diet_calories_check_subset_with_macros_peter.xlsx') %>% distinct()
psmoothie %>% distinct(Food_NSC) %>% nrow

unit <- read_csv('../data/148_both_batches_UNIT_table_EN_exclu.csv')
length(intersect(psmoothie$Food_NSC, unit$Food_NSC))
# which one is missing 
setdiff(psmoothie$Food_NSC, unit$Food_NSC)

smoocode <- psmoothie %>% distinct(Food_code) %>% pull(Food_code)

smoodf <- unit %>%
  filter( Food_code %in% smoocode)  %>% 
  mutate(protein_per_g = Protein_psu/dehydrated_psu,
         fat_per_g = Fat_psu/dehydrated_psu,
         Carbohydrate_per_g = Carbohydrate_psu/dehydrated_psu,
         Fiber_per_g = Fiber_psu/dehydrated_psu,
         Sugars_per_g = Sugars_psu/dehydrated_psu) %>% 
  select(Food_NSC, Food_code, description, ends_with('per_g')) %>% 
  distinct(Food_code, description, protein_per_g, fat_per_g, Carbohydrate_per_g, Fiber_per_g, Sugars_per_g, .keep_all = T) %>% 
  split(.$Food_code) %>% 
  map_dfr(function(eachcode ){
    eachcode %>% mutate(id = seq(nrow(eachcode)))
  }) %>% 
  mutate(new_code = str_glue('{Food_code}_{id}')) %>% 
  select(-id) 
```

```{r}
nonsmoo <-  unit %>%
  filter(! Food_code %in% smoocode) %>% 
  mutate(protein_per_g = Protein_psu/dehydrated_psu,
         fat_per_g = Fat_psu/dehydrated_psu,
         Carbohydrate_per_g = Carbohydrate_psu/dehydrated_psu,
         Fiber_per_g = Fiber_psu/dehydrated_psu,
         Sugars_per_g = Sugars_psu/dehydrated_psu) %>%
  select(Food_NSC, Food_code, description, ends_with('per_g')) %>% 
  distinct(Food_code, .keep_all = T) %>% 
   split(.$Food_code) %>% 
  map_dfr(function(eachcode ){
    eachcode %>% mutate(id = seq(nrow(eachcode)))
  }) %>% 
  mutate(new_code = str_glue('{Food_code}_{id}')) %>% 
  select(-id)
```


```{r}
Will <- bind_rows(en_unit, smoodf, nonsmoo)

Will %>%
  write_csv('../data/154_for_will_pergram_macronutrients_all.csv')
```

```{r}
# need to have a new table with foodnsc foodcode -- new code
smooall <- unit %>%
  filter( Food_code %in% smoocode) %>% 
  distinct(Food_NSC, Food_code)

Will %>% 
  filter(Food_code %in% smoocode) %>% 
  distinct(new_code)
```

```{r}
# but then there are 14 food codes that are in the diet table that don't appear in the macronutrients table
redo <- unit %>%
  mutate(protein_per_g = Protein_psu/dehydrated_psu,
         fat_per_g = Fat_psu/dehydrated_psu,
         Carbohydrate_per_g = Carbohydrate_psu/dehydrated_psu,
         Fiber_per_g = Fiber_psu/dehydrated_psu,
         Sugars_per_g = Sugars_psu/dehydrated_psu) %>%
  distinct(Food_code, protein_per_g,fat_per_g, Carbohydrate_per_g,  Fiber_per_g, Sugars_per_g, .keep_all = T) %>%
  select( Food_code, description, ends_with('per_g'))

redo %>% distinct(Food_code) %>% nrow 

p2d <- read_csv('../data/152_each_food_code_p2d_ave_intake_both_batches.csv') %>% 
  gather %>% 
  filter(str_detect(key, '^\\d')) %>% 
  distinct(key) %>% 
  mutate(key = as.numeric(key))

length(intersect(redo$Food_code, p2d$key))
setdiff(p2d$key, redo$Food_code)

extra <- en_unit %>% 
  select(colnames(redo))

redoall <- bind_rows(redo, extra)

redoall %>% write_csv('../data/154_redo_macronutrients_table.csv')
```



```{r}
# I need to create new code for the smoothie ones and the one EN formular
# I remain calm in all situations and it is going to be ok

```



in combined batch 1 and batch 2
  2-days prior 
  entire cohort vs MAC vs RIC vs NMA (4 settings)

4 versions of panel L

for meeting with Marcel

have the script annotate with both Spearman and lm p values

```{r}
STB <- read_csv('../data/152_combined_STB.csv')

# get the relab of the blautia and enterococcus of those 
cts_genus2 <- read_csv('../data/150_b2_stool_samples_genus_counts.csv')
cts_genus1 <- read_csv('../data/cleaned_stool/022_ALL_stool_samples_genus_counts.csv')

zero_transform <- log10(0 + 2*10^-6)

genera2 <- bind_rows(cts_genus1, cts_genus2) %>% 
  filter(genus %in% c('Enterococcus','Blautia')) %>% 
  mutate(relablog = log10(relab + 2*10^-6)) %>% 
  select(sampleid, genus, relablog) %>% 
  spread('genus', 'relablog', fill = zero_transform) %>% 
  right_join(STB %>% select(sampleid, simpson_reciprocal, intensity)) %>% 
  mutate(Enterococcus = if_else(is.na(Enterococcus), zero_transform, Enterococcus),
         Blautia = if_else(is.na(Blautia), zero_transform, Blautia))
```

```{r}
# get the p2d ave of the cal and 5 macro
DTB <- read_csv('../data/152_combined_DTB.csv')

# the daily caloric intake :
all_daily_pt <- DTB %>%
  group_by(mrn, fdrt) %>%
  summarise(total_daily = sum(Calories_kcal))

# the previous two days average for each stool sample

stb_pair <- STB %>%
  select(mrn, sdrt) %>%
  transmute(mrn = mrn,
            p1d = sdrt-1,
            p2d = sdrt-2)

mean_p2d_cal <-  function(mrn_, p1d_, p2d_){
  df = all_daily_pt %>%
    filter(mrn == mrn_) %>%
    filter(fdrt %in% c(p1d_, p2d_  )) %>%
    group_by(mrn) %>%
    summarise(ave_cal = sum(total_daily)/2)
  return(df)
}

mean_p2d_df_cal <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_cal(mrn, p1d, p2d)
  }) %>%
  set_names(STB %>% pull(sampleid)) %>%
  bind_rows(.id = 'sampleid')
```

```{r}
nutrients <- DTB %>%
  select(mrn, fdrt, Protein_g:Sugars_g) %>%
  gather('type','gram', Protein_g:Sugars_g) %>%
  group_by(mrn, fdrt, type) %>%
  summarise(total_daily = sum(gram)) %>%
  split(.$type)

mean_p2d_fiber <-  function(mrn_, p1d_, p2d_){
  df = nutrients$Fibers_g %>%
    filter(mrn == mrn_) %>%
    filter(fdrt %in% c(p1d_, p2d_  )) %>%
    group_by(mrn) %>%
    summarise(ave_fiber = sum(total_daily)/2)
  return(df)
}
mean_p2d_carb <-  function(mrn_, p1d_, p2d_){
  df = nutrients$Carbohydrates_g %>%
    filter(mrn == mrn_) %>%
    filter(fdrt %in% c(p1d_, p2d_  )) %>%
    group_by(mrn) %>%
    summarise(ave_carb = sum(total_daily)/2)
  return(df)
}

mean_p2d_fat <-  function(mrn_, p1d_, p2d_){
  df = nutrients$Fat_g %>%
    filter(mrn == mrn_) %>%
    filter(fdrt %in% c(p1d_, p2d_  )) %>%
    group_by(mrn) %>%
    summarise(ave_fat = sum(total_daily)/2)
  return(df)
}
mean_p2d_Protein <-  function(mrn_, p1d_, p2d_){
  df = nutrients$Protein_g %>%
    filter(mrn == mrn_) %>%
    filter(fdrt %in% c(p1d_, p2d_  )) %>%
    group_by(mrn) %>%
    summarise(ave_Protein = sum(total_daily)/2)
  return(df)
}
mean_p2d_Sugars <-  function(mrn_, p1d_, p2d_){
  df = nutrients$Sugars_g %>%
    filter(mrn == mrn_) %>%
    filter(fdrt %in% c(p1d_, p2d_  )) %>%
    group_by(mrn) %>%
    summarise(ave_Sugars = sum(total_daily)/2)
  return(df)
}

mean_p2d_fiber <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_fiber(mrn, p1d, p2d)
  }) %>%
  set_names(STB %>% pull(sampleid)) %>%
  bind_rows(.id = 'sampleid')

mean_p2d_fat <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_fat(mrn, p1d, p2d)
  }) %>%
  set_names(STB %>% pull(sampleid)) %>%
  bind_rows(.id = 'sampleid')

mean_p2d_Protein <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_Protein(mrn, p1d, p2d)
  }) %>%
  set_names(STB %>% pull(sampleid)) %>%
  bind_rows(.id = 'sampleid')

mean_p2d_Sugars <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_Sugars(mrn, p1d, p2d)
  }) %>%
  set_names(STB %>% pull(sampleid)) %>%
  bind_rows(.id = 'sampleid')

mean_p2d_carb <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_carb(mrn, p1d, p2d)
  }) %>%
  set_names(STB %>% pull(sampleid)) %>%
  bind_rows(.id = 'sampleid')

p2d_diet <- mean_p2d_df_cal %>%
  full_join(mean_p2d_fiber, by = c("sampleid", "mrn")) %>%
  full_join(mean_p2d_fat, by = c("sampleid", "mrn")) %>%
  full_join(mean_p2d_Protein, by = c("sampleid", "mrn")) %>%
  full_join(mean_p2d_Sugars, by = c("sampleid", "mrn")) %>%
  full_join(mean_p2d_carb, by = c("sampleid", "mrn"))
```

```{r}
p2d_all <- p2d_diet %>% full_join(genera2)
colnames(p2d_all)
```

```{r}
macro_panel <- p2d_all %>% 
  mutate(simpson_reciprocal_nlog  = log(simpson_reciprocal)) %>% 
  rename(`log10(Blautia)` = Blautia,
         `log10(Enterococcus)` = Enterococcus,
         `log(Simpson reciprocal)` = simpson_reciprocal_nlog) %>% 
  dplyr::select(`log(Simpson reciprocal)`, `log10(Blautia)`, `log10(Enterococcus)`,  ave_cal:ave_carb ) %>% 
  mutate(ave_cal = ave_cal/1000) %>%  # now divide the value by 1000 to save some space in x axis text!!! 
  gather('yaxis', 'value', `log(Simpson reciprocal)`:`log10(Enterococcus)`) %>% 
  mutate(yaxis = factor(yaxis, levels = c('log(Simpson reciprocal)','log10(Blautia)','log10(Enterococcus)'))) %>% 
  gather('xaxis', 'number', ave_cal:ave_carb) %>% 
  mutate(xaxis = case_when(
    xaxis == 'ave_cal' ~ 'Calorie',
    xaxis == 'ave_carb' ~ 'Carb',
    xaxis == 'ave_Sugars' ~ 'Sugar',
    xaxis == 'ave_fiber' ~ 'Fiber',
    xaxis == 'ave_Protein' ~ 'Protein',
    xaxis == 'ave_fat' ~ 'Fat'
  )) %>% 
  mutate(xaxis = factor(xaxis, levels = c('Calorie','Carb','Sugar','Fiber','Protein','Fat')))
```

```{r}
library(facetscales)
Blautia_lim <- floor(min(p2d_all$Blautia))
entero_lim <- floor(min(p2d_all$Enterococcus))
simpson_reciprocal_nlog_lim <- max(log(p2d_all$simpson_reciprocal))

scales_y <- list(
  `log(Simpson reciprocal)` = scale_y_continuous(limits = c(0, simpson_reciprocal_nlog_lim), breaks = seq(0, simpson_reciprocal_nlog_lim, 1)),
  `log10(Blautia)` = scale_y_continuous(limits = c(Blautia_lim, 0), breaks = seq(Blautia_lim, 0, 2)),
  `log10(Enterococcus)` = scale_y_continuous(limits = c(entero_lim, 0), breaks = seq(entero_lim, 0, 2))
)

# to use the max observed in the data
cal_lim <- max(p2d_all$ave_cal)/1000
protein_lim <- max(p2d_all$ave_Protein)
d_fat_lim <- max(p2d_all$ave_fat)
d_carb_lim <- max(p2d_all$ave_carb)
d_fiber_lim <- max(p2d_all$ave_fiber)
d_sugar_lim <- max(p2d_all$ave_Sugars)

scales_x <- list(
  `Calorie` = scale_x_continuous(limits = c(0, cal_lim), breaks = seq(0, cal_lim, 1)),
  `Protein` = scale_x_continuous(limits = c(0, protein_lim), breaks = seq(0, protein_lim, 50)),
  `Fat` = scale_x_continuous(limits = c(0, d_fat_lim), breaks = seq(0, d_fat_lim, 50)),
  `Carb` = scale_x_continuous(limits = c(0, d_carb_lim), breaks = seq(0, d_carb_lim, 250)),
  `Fiber` = scale_x_continuous(limits = c(0,d_fiber_lim), breaks = seq(0, d_fiber_lim, 20)),        
  `Sugar` = scale_x_continuous(limits = c(0, d_sugar_lim), breaks = seq(0, d_sugar_lim, 100) )
)
```

```{r}
# to split to make each small panel so that I can annotate the p value from the lm and the spearman
combined_split_each_fig <- macro_panel %>% 
  split(., list(.$xaxis, .$yaxis)) %>% 
    imap(function(.x, .y){
      res = summary(lm(value ~ number, data = .x ))
      pval = round(res$coefficients[2, 'Pr(>|t|)'], 2)
      
      # the spearman correlation
      spearman_cor = cor.test(.x$number, .x$value, method = c( "spearman"))
      spearman_rho = round(spearman_cor$estimate, 2)
      spearman_pval = round(spearman_cor$p.value , 2)
      
      ggscatter(data = .x,x = 'number', y = 'value', alpha = 0.1, xlab ='', 
                ylab = '',size = 1.2, pch = 19, 
                title =  str_glue('{.y}\nlm pval: {pval}\nRho: {spearman_rho}\nrank pval:{spearman_pval}'),
                 add = "reg.line",  # Add regressin line
               add.params = list(color = "darkblue", fill = "gray59"), # Customize line
               conf.int = TRUE, # Add confidence interval
              ) +
      #facet_grid_sc(rows = vars(yaxis), cols = vars(xaxis), scales = list(y = scales_y, x = scales_x)) +
      theme_classic(base_size = 11) +
      theme(aspect.ratio = 1,
            panel.background = element_rect(fill = "gray97"),
            panel.grid.major = element_blank(), 
            plot.title = element_text(size=10),
            #strip.background = element_blank(),
            #strip.text = element_blank(),
            panel.grid.minor = element_blank()
           )
    })

g <- cowplot::plot_grid(combined_split_each_fig[[1]],combined_split_each_fig[[2]],combined_split_each_fig[[3]],combined_split_each_fig[[4]],combined_split_each_fig[[5]],combined_split_each_fig[[6]],combined_split_each_fig[[7]],combined_split_each_fig[[8]],combined_split_each_fig[[9]],combined_split_each_fig[[10]],combined_split_each_fig[[11]],combined_split_each_fig[[12]],combined_split_each_fig[[13]],combined_split_each_fig[[14]],combined_split_each_fig[[15]],combined_split_each_fig[[16]],combined_split_each_fig[[17]],combined_split_each_fig[[18]],
    ncol = 6,
    o = 'hv',labels = '',label_y = -2,
    #labels = 'AUTO',
    axis = 'bltr')  
ggsave(str_glue('../data/154_p2d__combined.jpg'), width = 12, height = 8,  plot = g)
```
# split them both combined to the three conditioning levels

```{r}
split3 <- p2d_all %>% 
  split(.$intensity) %>% 
  map(function(small_df){
    small_panel <- small_df %>% 
        mutate(simpson_reciprocal_nlog  = log(simpson_reciprocal)) %>% 
        rename(`log10(Blautia)` = Blautia,
               `log10(Enterococcus)` = Enterococcus,
               `log(Simpson reciprocal)` = simpson_reciprocal_nlog) %>% 
       dplyr::select(`log(Simpson reciprocal)`, `log10(Blautia)`, `log10(Enterococcus)`,  ave_cal:ave_carb ) %>% 
      mutate(ave_cal = ave_cal/1000) %>%  # now divide the value by 1000 to save some space in x axis text!!! 
      gather('yaxis', 'value', `log(Simpson reciprocal)`:`log10(Enterococcus)`) %>% 
      mutate(yaxis = factor(yaxis, levels = c('log(Simpson reciprocal)','log10(Blautia)','log10(Enterococcus)'))) %>% 
      gather('xaxis', 'number', ave_cal:ave_carb) %>% 
      mutate(xaxis = case_when(
        xaxis == 'ave_cal' ~ 'Calorie',
        xaxis == 'ave_carb' ~ 'Carb',
        xaxis == 'ave_Sugars' ~ 'Sugar',
        xaxis == 'ave_fiber' ~ 'Fiber',
        xaxis == 'ave_Protein' ~ 'Protein',
        xaxis == 'ave_fat' ~ 'Fat'
      )) %>% 
      mutate(xaxis = factor(xaxis, levels = c('Calorie','Carb','Sugar','Fiber','Protein','Fat')))
    
    small_panel_split_each <- small_panel %>%  split(., list(.$xaxis, .$yaxis)) 
    
  
    small_panel_split_each_fig <- small_panel_split_each %>% 
    imap(function(.x, .y){
      res = summary(lm(value ~ number, data = .x ))
      pval = round(res$coefficients[2, 'Pr(>|t|)'], 2)
      
      # the spearman correlation
      spearman_cor = cor.test(.x$number, .x$value, method = c( "spearman"))
      spearman_rho = round(spearman_cor$estimate, 2)
      spearman_pval = round(spearman_cor$p.value , 2)
      
      ggscatter(data = .x,x = 'number', y = 'value', alpha = 0.1, xlab ='', 
                ylab = '',size = 1.2, pch = 19, 
               title =  str_glue('{.y}\nlm pval: {pval}\nRho: {spearman_rho}\nrank pval:{spearman_pval}'),
                 add = "reg.line",  # Add regressin line
               add.params = list(color = "darkblue", fill = "gray59"), # Customize line
               conf.int = TRUE, # Add confidence interval
              ) +
      #facet_grid_sc(rows = vars(yaxis), cols = vars(xaxis), scales = list(y = scales_y, x = scales_x)) +
      theme_classic(base_size = 11) +
      theme(aspect.ratio = 1,
            panel.background = element_rect(fill = "gray97"),
            panel.grid.major = element_blank(), 
            plot.title = element_text(size=10),
            #strip.background = element_blank(),
            #strip.text = element_blank(),
            panel.grid.minor = element_blank()
           )
    })
         
  })

# assemble figure
ablatives <- split3[['ablative']]


g <- cowplot::plot_grid(ablatives[[1]],ablatives[[2]],ablatives[[3]],ablatives[[4]],ablatives[[5]],ablatives[[6]],ablatives[[7]],ablatives[[8]],ablatives[[9]],ablatives[[10]],ablatives[[11]],ablatives[[12]],ablatives[[13]],ablatives[[14]],ablatives[[15]],ablatives[[16]],ablatives[[17]],ablatives[[18]],
    ncol = 6,
    o = 'hv',labels = 'Ablative',label_y = -2,
    #labels = 'AUTO',
    axis = 'bltr')  

ggsave(str_glue('../data/154_p2d_combined_conditioning_ablative.jpg'), width = 12, height = 8,  plot = g)
```


```{r}
nonablative <- split3[['nonablative']]


g <- cowplot::plot_grid(nonablative[[1]],nonablative[[2]],nonablative[[3]],nonablative[[4]],nonablative[[5]],nonablative[[6]],nonablative[[7]],nonablative[[8]],nonablative[[9]],nonablative[[10]],nonablative[[11]],nonablative[[12]],nonablative[[13]],nonablative[[14]],nonablative[[15]],nonablative[[16]],nonablative[[17]],nonablative[[18]],
    ncol = 6,
    o = 'hv',labels = 'Nonablative',label_y = -2,
    #labels = 'AUTO',
    axis = 'bltr') 

ggsave(str_glue('../data/154_p2d_combined_conditioning_nonablative.jpg'), width = 12, height = 8,  plot = g)
```

```{r}
reduced <- split3[['reduced']]

g <- cowplot::plot_grid(reduced[[1]],reduced[[2]],reduced[[3]],reduced[[4]],reduced[[5]],reduced[[6]],reduced[[7]],reduced[[8]],reduced[[9]],reduced[[10]],reduced[[11]],reduced[[12]],reduced[[13]],reduced[[14]],reduced[[15]],reduced[[16]],reduced[[17]],reduced[[18]],
    ncol = 6,
    o = 'hv',labels = 'reduced',label_y = -2,
    #labels = 'AUTO',
    axis = 'bltr') 

ggsave(str_glue('../data/154_p2d_combined_conditioning_reduced.jpg'), width = 12, height = 8,  plot = g)


```


# make a table that is the previous two days consumption of foodnsc + unit

```{r}
# the unique combinations of the foodnsc + unit
DTB %>% 
  mutate(foodall = str_glue('{Food_NSC}__{Unit}')) %>% 
  distinct(foodall) %>% 
  nrow()

STB <- read_csv('../data/152_combined_STB.csv')

#
all_daily_foodall <- DTB %>%
   mutate(foodall = str_glue('{Food_NSC}__{Unit}')) %>% 
  group_by(mrn, fdrt, foodall) %>%
  summarise(total_daily_foodall = sum(dehydrated_weight))

# the previous two days average for each stool sample

stb_pair <- STB %>%
  select(mrn, sdrt) %>%
  transmute(mrn = mrn,
            p1d = sdrt-1,
            p2d = sdrt-2)

mean_p2d_foodall <-  function(mrn_, p1d_, p2d_){
  df = all_daily_foodall %>%
    filter(mrn == mrn_) %>%
    filter(fdrt %in% c(p1d_, p2d_  )) %>%
    group_by(foodall) %>%
    summarise(ave_foodall = sum(total_daily_foodall)/2)
  return(df)
}

mean_p2d_df_foodall <- pmap(stb_pair, function(mrn, p1d, p2d){
    mean_p2d_foodall(mrn, p1d, p2d)
  }) %>%
  set_names(STB %>% pull(sampleid)) %>%
  bind_rows(.id = 'sampleid')

mean_p2d_df_foodall %>% write_csv('../data/154_average_p2d_intake_of_foodnsc_and_unit.csv')
```

