---
title: "the clinical studies"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(lubridate)
```

can you please see if there are last-date of follow-up and vital status, relapse/POD and gvhd data for the patients in batch1 and batch2?

```{r}
# the below table has the more updated data 
pts <- read_csv('../data/pts_updated_through_june_2022.csv') %>% 
  rename_all(~ gsub(" ", "_", .)) %>% 
  rename(mrn = MRN) %>% 
  mutate(hct = lubridate::dmy(HCT))
colnames(pts)
```


```{r}
# Relapse, Relapse Date
# POD, POD Date
# Status , Last Contact
# gvhd data from the patients table
ptb1 <- read_csv('../data/cleaned_patients/diet_patients_97.csv') 
ptb2 <- read_csv('../data/129_ptb2.csv')

ptb <- bind_rows(
  ptb1 %>% select(mrn:disease.simple) %>% mutate(batch = 'batch1'),
  ptb2 %>% select(mrn:disease.simple) %>% mutate(batch = 'batch2')
)

pts_tb <- pts %>% 
  right_join(ptb, by = c("mrn", "hct")) 

# the gvhd data
library(vdbR)
connect_database()
get_table_from_database('patient_allo_ks_20221104')
colnames(patient_allo_ks_20221104)
get_table_from_database('samples_castori_ag')
get_table_from_database('asv_alpha_diversity_ag')
```

```{r}
# find the patients that had a second transplant


all_hct2 <- pts %>% 
  filter(mrn %in% ptb$mrn) %>% 
  select(mrn, hct) %>% 
  filter(duplicated(mrn))

# find all of the hct and to mark which hct are we using their diet data

at2 <- pts %>% 
  filter(mrn %in% all_hct2$mrn) %>% 
  select(mrn, hct) %>% 
  left_join(ptb , by = c("mrn", "hct")) %>% 
  select(mrn, hct, batch) %>% 
  arrange(mrn, hct) %>% 
  split(.$mrn) %>% 
  map_dfr(function(df){
    df %>% mutate(id = seq(1, nrow(.)))
  })

censor_pt <- at2 %>% 
  group_by(mrn) %>% 
  arrange(desc(id)) %>% 
  slice(1) %>% 
  filter(is.na(batch)) %>% 
  pull(mrn)

censor2 <- at2 %>% 
  filter(mrn %in% censor_pt)

censor2 %>% write_csv('../data/156_censor_2_patients_for_second_transplant.csv')
```


```{r}
ptb_gvhd <- patient_allo_ks_20221104 %>% 
  right_join(ptb, by = c("mrn", "hct")) %>% 
  select(mrn, hct, batch, starts_with('d100'))

ptb_all <- pts_tb %>% 
  full_join(ptb_gvhd, by = c("mrn", "hct", "batch")) %>% 
  mutate(ANEUT_500_DATE = dmy(ANEUT_500_DATE)) %>% 
  mutate(ttancday = as.numeric(ANEUT_500_DATE - hct
)) %>% 
  relocate(ttancday, .after = 'TIME_ANEUT_500') %>% 
  # correct one patient engraftment date
  mutate(ANEUT_500_DATE = if_else(ANEUT_500_DATE == '2021-11-16', '2021-10-23', as.character(ANEUT_500_DATE)),
         ANEUT_500_DATE = ymd(ANEUT_500_DATE)) %>% 
  mutate(ttancday = as.numeric(ANEUT_500_DATE - hct)) %>% 
  select(-TIME_ANEUT_500)

ptb_all %>% write_csv('../data/156_combined_clinical_data.csv')

ptb_gvhd %>% count(d100_a_gvhd)

needdata <- ptb_gvhd %>% 
  filter(is.na(d100_a_gvhd))

needdata %>% write_csv('../data/156_missing_GVHD_data.csv', na = '')
```

# clinical analysis

```{r}
## Outcomes of interest
#OS
#length of stay/duration of hospitalization, perhaps duration of hospitalization after engraftment
#TRM (transplant related mortality). TRM is defined as death not preceded by relapse(or progression of disesase)

#Grade 2-4 GVHD diagnosis (for analysis of GVHD outcomes, exclude Graft type "T-cell depleted PBSC")
#GRM (GVHD-related mortality) (for analysis of GVHD outcomes, exclude Graft type "T-cell depleted PBSC")

## Predictors
# total calorie intake averaged between day 0 and day of engraftment (TTANC)
# total [each macronutrient] intake averaged between day 0 and day of engraftment (TTANC)
# total [food group of interest, pick 1 or 2 or just systematically all of them] intake averaged between day 0 and day of engraftment (TTANC)
# 
# in multivariable Cox (or Fine-Gray cuminc cmprsk)  models that have terms for 
# outcome ~ predictor + conditioning_intensity + graft_type

# Tsoni thinks the role of medications in this analysis can be that if we find a relationship between one of the outcomes and one of the predictors, we can further check if the relationship holds after adding a term to account for patients on high doses of opioids (patient controlled analgesia, PCA device) as a surrogate of severe toxicity 
```

```{r}
## Predictors
# total calorie intake averaged between day 0 and day of engraftment (TTANC)
# total [each macronutrient] intake averaged between day 0 and day of engraftment (TTANC)
# total [food group of interest, pick 1 or 2 or just systematically all of them] intake averaged between day 0 and day of engraftment (TTANC)
# average food diversity between the period 
# the diversity close to the engraftment for the patients 


key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')
# make a table withe daily total caloric intake
DTB <- read_csv('../data/152_combined_DTB.csv') %>% 
  mutate(fgrp1 = str_sub(as.character(Food_code), 1, 1))

# a table of the daily each macro
daily <- DTB %>% 
  group_by(mrn, fdrt) %>% 
  summarise(daycal = sum(Calories_kcal),
            d_protein = sum(Protein_g),
            d_fat = sum(Fat_g),
            d_carb = sum(Carbohydrates_g),
            d_fiber = sum(Fibers_g),
            d_sugar = sum(Sugars_g))

dailyfg <- DTB %>% 
  group_by(mrn, fdrt, fgrp1) %>% 
  summarise(dailyfg = sum(dehydrated_weight)) %>% 
  left_join(key %>% select(fgrp1, shortname)) %>% 
  mutate(shortname = str_glue('daily_{shortname}')) %>% 
  select(mrn, fdrt, shortname, dailyfg) %>% 
  spread('shortname', 'dailyfg', fill = 0)

dailyall <- daily %>% 
  full_join(dailyfg)

# calculate the above listed values
# ignore the patients that had died before engraphtment 
pts_ <- ptb_all %>% 
  filter(!is.na(ttancday)) %>% 
  pull(mrn)

ave_ttanc <- pts_ %>% 
  set_names(pts_) %>% 
  map(function(mrn_){
    ttanc_day <- ptb_all %>% 
      filter(mrn == mrn_) %>% 
      pull(ttancday)
    total_days <- dailyall %>% 
      filter(mrn == mrn_ & fdrt %in% 0:ttanc_day) %>% nrow
    ave_values <- dailyall %>% 
      filter(mrn == mrn_ & fdrt %in% 0:ttanc_day) %>% 
      gather('group', 'gram', daycal:daily_Vegetables) %>% 
      group_by(mrn, group) %>% 
      summarise(ave_grp = sum(gram)/total_days)
  }) %>% bind_rows()

ave_ttanc_df <- ave_ttanc %>% 
  spread('group','ave_grp')

# why are there 2 patients that don't have any nutrition predictors
pt2 <- setdiff(pts_, ave_ttanc_df$mrn)
# since we only have diet data pre-transplant


```
 
 
```{r}
# I have attached a table for our 177 patients with the following data:  
# 
# weight data (including admission weight, BMI, discharge weight, weight loss)
# nutritional needs (kilocalories/day, grams of protein/day)
# nutritional risk (per the nutritional risk index, determined at time of admission)
weight <- readxl::read_excel('../data/DietPatients_WeightData.xlsx') %>% 
  mutate(mrn = as.numeric(MRN)) %>% 
  filter(mrn %in% ptb_all$mrn) %>% 
  rename_all(~ gsub(" ", "_", .)) %>% 
  rename_all(~ gsub("\\(|\\)", "", .)) %>% 
  select(mrn, Admission_wt_kg, `Admission_BMI_kg/m^2`,Discharge_wt_kg, Wt_change_kg,`Wt_change_%`,`Kcal_Needs_30_kcal/kg`,`Protein_Needs_1.5_gm/kg`, Nutritional_Risk_Index_NRI ) %>% 
  mutate_if(is.character, as.numeric)
colnames(weight)
```
 
 
```{r}
# "/Volumes/vandenbrinklab/Angel_Dai/Nutrition_project/visits_nutrition_cohort"
# key fields include
# admit_date
# discharge_date
# if you just select the visit where the HCT date is in between the admit_date and the discharge_date  you will identify the main transplant hospitalization, and from that can calculate length of stay and, importantly, duration of hospitalization beyond engraftment, which I think is the clinical variable most likely to correlate with nutrition

visits <- read_csv('/Volumes/vandenbrinklab/Angel_Dai/Nutrition_project/visits_nutrition_cohort/nutrition_cohort_visits_2023-02-16.csv')  %>% 
  mutate(mrn = as.numeric(MRN)) %>% 
  select(mrn, admit_date, discharge_date) %>% 
  mutate(visit_int = interval(admit_date, discharge_date)) %>% 
  inner_join(ptb_all %>% select(mrn, hct)) %>% 
  mutate(hct_int =  interval(hct, hct)) %>% 
  mutate(transplant_hospitalization = int_overlaps(visit_int, hct_int)) %>% 
  distinct()

transplant_stays <- visits %>% 
  filter(transplant_hospitalization == 'TRUE') %>% 
  # there is one entry needs to be removed seems wrong
  arrange(mrn, admit_date) %>% 
  distinct(mrn, .keep_all = T) %>% 
  select(-ends_with('int')) %>% 
  mutate(leng_of_stay = as.numeric(discharge_date - admit_date)) %>% 
  full_join(ptb_all , by = c("mrn", "hct")) %>% 
  # calculate duration of hospitalization beyond engraftment
  mutate(discharge_day = as.numeric(discharge_date - hct)) %>% 
  relocate(discharge_day, .after = 'batch') %>% 
  mutate(beyond_engraftment = discharge_day - ttancday) %>% 
  relocate(ttancday, .after = 'HCT') %>% 
  relocate(beyond_engraftment, .after = 'ttancday') %>% 
  select(-HCT) %>% 
  mutate(discharge_date_for_nutrition = if_else(discharge_date == '2017-02-04', '2017-02-06', as.character(discharge_date))) %>% 
  relocate(discharge_date_for_nutrition, .after = 'hct') %>% 
  relocate(ANEUT_500_DATE, .after = 'discharge_date_for_nutrition') %>% 
  mutate(discharge_date_for_nutrition = ymd(discharge_date_for_nutrition),
         leng_of_stay = as.numeric(discharge_date_for_nutrition - admit_date)) %>% 
  relocate(leng_of_stay, .after = 'ANEUT_500_DATE') %>% 
  mutate(beyond_engraftment = as.numeric(discharge_date_for_nutrition -ANEUT_500_DATE )) %>% 
  relocate(beyond_engraftment, .after = 'leng_of_stay')
  
colnames(transplant_stays)
transplant_stays %>% 
  write_csv('../data/156_transplant_data.csv')
```


```{r}
# combine to get the most comprehensive predcitor data I have
allpred <- ave_ttanc_df %>% 
  right_join(weight, by = "mrn")


allpred %>% write_csv('../data/156_predictors.csv')

colnames(transplant_stays)
```

```{r}
# find the stool sample that is closest to engraftment date for each patient
transplant_data <- read_csv('../data/156_transplant_data.csv') %>% 
  select(mrn,  ANEUT_500_DATE, hct)

all_stool <- samples_castori_ag %>% 
  filter(mrn %in% transplant_data$mrn) %>% 
  select(mrn, sampleid, datecollection) %>% 
  left_join(transplant_data, by = "mrn") %>% 
  mutate(sdrengraft = as.numeric(datecollection - ANEUT_500_DATE)) %>% 
  mutate(abssdrengraft = abs(sdrengraft)) %>% 
  group_by(mrn) %>% 
  slice_min(n = 1, order_by = abssdrengraft) %>% 
  inner_join(asv_alpha_diversity_ag %>% select(sampleid, simpson_reciprocal)) %>% 
  arrange(mrn, abssdrengraft, sdrengraft) %>% 
  distinct(mrn, .keep_all = T)

all_stool %>% write_csv('../data/156_stool_close_to_engraftment.csv')
all_stool %>% gghistogram(x = 'sdrengraft', xlab = 'stool sample collection relative to engraftment')
```

```{r}
# take the earliest single sample collected after engraftment, as long as it was within 7 days
first_in_7 <-  samples_castori_ag %>% 
  filter(mrn %in% transplant_data$mrn) %>% 
  select(mrn, sampleid, datecollection) %>% 
  left_join(transplant_data, by = "mrn") %>% 
  mutate(sdrengraft = as.numeric(datecollection - ANEUT_500_DATE)) %>% 
  filter(sdrengraft %in% 0:7) %>% 
  arrange(mrn, sdrengraft) %>% 
  distinct(mrn, .keep_all = T) %>% 
  inner_join(asv_alpha_diversity_ag %>% select(sampleid, simpson_reciprocal)) %>% 
  rename(first_in_w1 = simpson_reciprocal) %>% distinct() %>% 
  distinct(mrn, .keep_all = T) 
```

```{r}
# get the (median diversity of all samples collected between day 7-21)
median_val <-  samples_castori_ag %>% 
  filter(mrn %in% transplant_data$mrn) %>% 
  select(mrn, sampleid, datecollection) %>% 
  left_join(transplant_data, by = "mrn") %>% 
  mutate(sdrt = as.numeric(datecollection - hct)) %>% 
  filter(sdrt %in% 7:21) %>% 
  inner_join(asv_alpha_diversity_ag %>% select(sampleid, simpson_reciprocal))  %>% 
  group_by(mrn) %>% 
  summarise(median_div = median(simpson_reciprocal)) %>% 
  rename(median7_21 = median_div) %>% 
  full_join(first_in_7 %>% select(mrn, first_in_w1))

median_val %>% distinct(mrn)

median_val %>% write_csv('../data/156_two_stool_alpha_engraftment.csv')
```

```{r}
# to calculate the diet alpha diversity during 0:engraftment
# per patient per day diversity


faith2 <-  read_tsv('../data/139_batch2_faith_pd/alpha-diversity.tsv') %>% 
  separate(...1, into = c('mrn', 'fdrt'), sep = '_', convert = T)  %>% 
  mutate(mrn = as.numeric(str_replace(mrn, 'P','')))

DTB  %>% count(mrn, fdrt) %>% 
  nrow
```


```{r}
# need to redo the batch 1 faith
dtb1 <- DTB %>% filter(batch == 'batch1')
# the weight need to be relative so needs to normalize them 
fc_table <- dtb1 %>% 
  select(mrn, fdrt, Food_code, dehydrated_weight) %>% 
  group_by(mrn, fdrt, Food_code) %>% 
  summarise(total = sum(dehydrated_weight)) %>% 
  ungroup() %>% 
  mutate(index_column = str_glue('P{mrn}_{fdrt}')) %>% 
  select(index_column, Food_code, total)

fcts <-  fc_table %>% 
  spread(key = 'index_column', value = 'total', fill = 0) 
fcts %>% 
  write_tsv('../data/156_batch1_food_code_counts_matrix.tsv')
```

```{bash}
biom convert -i ../data/156_batch1_food_code_counts_matrix.tsv -o ../data/156_batch1_food_code_counts_matrix.biom --to-hdf5 --table-type="Table"
qiime tools import \
  --input-path ../data/156_batch1_food_code_counts_matrix.biom \
  --output-path ../data/156_batch1_food_code_counts_matrix.qza \
  --type 'FeatureTable[Frequency]' 
qiime tools import \
  --input-path ../data/cleaned_tree/output_food_tree_datatree.newick \
  --output-path ../data/cleaned_tree/output_food_tree_datatree.qza \
  --type 'Phylogeny[Rooted]'
qiime diversity alpha-phylogenetic \
  --i-table ../data/156_batch1_food_code_counts_matrix.qza  \
  --i-phylogeny ../data/cleaned_tree/output_food_tree_datatree.qza \
  --p-metric faith_pd \
  --o-alpha-diversity ../data/156_batch1_faith_pd.qza
# export to tsv format
qiime tools export --input-path ../data/156_batch1_faith_pd.qza --output-path ../data/156_batch1_faith_pd
```

```{r}
faith1 <- read_tsv('../data/156_batch1_faith_pd/alpha-diversity.tsv')  %>% 
  separate(...1, into = c('mrn', 'fdrt'), sep = '_', convert = T)  %>% 
  mutate(mrn = as.numeric(str_replace(mrn, 'P','')))
```
```{r}
faith <- bind_rows(faith1, faith2)

ave_ttanc_faith <- pts_ %>% 
  set_names(pts_) %>% 
  map(function(mrn_){
    ttanc_day <- ptb_all %>% 
      filter(mrn == mrn_) %>% 
      pull(ttancday)
    total_days <- faith %>% 
      filter(mrn == mrn_ & fdrt %in% 0:ttanc_day) %>% nrow
    ave_faith <- faith %>% 
      filter(mrn == mrn_ & fdrt %in% 0:ttanc_day) %>% 
      group_by(mrn) %>% 
      summarise(ave_faith = sum(faith_pd)/total_days)
  }) %>% bind_rows() 

output <- ave_ttanc_faith %>% 
  full_join(median_val, by = "mrn") 

output %>% distinct(mrn )

output %>% write_csv('../data/156_extra_predictors.csv')
```
# the pre and post engraftment correlation

```{r}



all_prepost <- pts_ %>% 
  set_names(pts_) %>% 
  map(function(mrn_){
       ttanc_day <- ptb_all %>% 
          filter(mrn == mrn_) %>% 
          pull(ttancday)
       
    df = dailyall %>% 
      filter(mrn == mrn_ & fdrt >= 0) %>% 
      mutate(timegrp = if_else(fdrt %in% 0:ttanc_day, 'pre', if_else(fdrt > ttanc_day, 'post', 'before0'))) %>% 
      select(-fdrt) %>% 
      gather('grp', 'value', daycal:daily_Vegetables) %>% 
      group_by(mrn, timegrp, grp) %>% 
      summarise(ave_timebin = mean(value)) 
  }) %>% bind_rows() %>% 
  spread('timegrp', 'ave_timebin')

all_prepost %>% 
   ggscatter(x = 'pre', y = 'post',   alpha = 0.5,
             conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n")) +
  facet_wrap(~ grp, scales = 'free')

ggsave('../data/156_ALL_pre_post.pdf', width = 10, height = 10)
```

```{r}
# a linear model that takes into account conditioning intensity & graft source
df_main <- read_csv('../data/df_main.csv')
summary(df_main$tLOS)
prepost_df <- all_prepost %>% 
  left_join(ptb_all %>% select(mrn, source, intensity)) %>% 
  left_join(df_main %>% select(mrn, tLOS))

lm_res <- prepost_df %>% 
  split(.$grp) %>% 
  map(function(df) {
    res = summary(lm(post ~ pre + source +intensity, data = df ))
    return(tibble(pval = round(res$coefficients[2, 'Pr(>|t|)'], 3),
           slope = round(res$coefficients[2, 'Estimate'], 3)))
  }) %>% bind_rows(.id = 'grp') %>% 
  select(grp, slope_of_pre = slope, pval)

# an lmer that considers each day and each patient individually
prepost_days <- pts_ %>% 
  set_names(pts_) %>% 
  map(function(mrn_){
       ttanc_day <- ptb_all %>% 
          filter(mrn == mrn_) %>% 
          pull(ttancday)
       
    df = dailyall %>% 
      filter(mrn == mrn_ & fdrt >= 0) %>% 
      mutate(timegrp = if_else(fdrt %in% 0:ttanc_day, 'pre', if_else(fdrt > ttanc_day, 'post', 'before0'))) ao 
  }) %>% bind_rows() 
  

lm_res_all <- prepost_df %>% 
  split(.$grp) %>% 
  map(function(df) {
    res = summary(lm(tLOS ~ pre + post +source +intensity, data = df ))
    return(tibble(
      pre_pval = round(res$coefficients[2, 'Pr(>|t|)'], 3),
      pre_slope = round(res$coefficients[2, 'Estimate'], 3),
      post_pval = round(res$coefficients[3, 'Pr(>|t|)'], 3),
      post_slope = round(res$coefficients[3, 'Estimate'], 3)))
  }) %>% bind_rows(.id = 'grp')
```

