---
title: "Survival analysis"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F)
```

The analysis that don't need the gvhd outcome: OS, TRM and LOS(len of stay)

```{r}
#library(biostatR); 
library(tidyverse)
library(tidycmprsk)
library(survival)
library(gtsummary)
library(ggsurvfit)
library(gtExtras)
# theme_set(mskRvis::theme_biostat()); mskRvis::set_msk_palette()
# theme_gtsummary_compact()
 
few <- read_csv('../data/156_extra_predictors.csv')
df_main <- read_csv('../data/df_main.csv') %>% 
  mutate(Source = source,
         Intensity = factor(Intensity, levels=c("Nonablative","Reduced Intensity",'Ablative')),
          Source = factor(Source,levels=c("unmodified","TCD","cord")) ) %>% 
  full_join(few ) %>% 
  mutate(TRMevent = factor(TRMevent),
         GRMevent = factor(GRMevent)) %>% 
  # to divde the cal by 1000 for easier interpretation, and the other food related vars by 100
  mutate(d_carb = d_carb/100,
         d_fat = d_fat/100,
         d_fiber = d_fiber/100,
         d_protein = d_protein/100,
         d_sugar = d_sugar/100,
         daycal = daycal/1000,
         daily_Eggs = daily_Eggs/100,
         daily_Fruits = daily_Fruits/100,
         daily_Grains = daily_Grains/100,
         daily_Legumes = daily_Legumes/100,
         daily_Meats = daily_Meats/100,
         daily_Oils = daily_Oils/100,
         daily_Sweets = daily_Sweets/100,
         daily_Vegetables = daily_Vegetables/100,
         daily_Milk = daily_Milk/100) %>% 
  mutate(d_carb_med = ifelse(d_carb > median(d_carb,na.rm=T),"Above median", "Below median"),
         d_fat_med = ifelse(d_fat > median(d_fat,na.rm=T),"Above median", "Below median"),
         d_fiber_med = ifelse(d_fiber > median(d_fiber,na.rm=T),"Above median", "Below median"),
         d_protein_med = ifelse(d_protein > median(d_protein,na.rm=T),"Above median", "Below median"),
         d_sugar_med = ifelse(d_sugar > median(d_sugar,na.rm=T),"Above median", "Below median"),
         daycal_med = ifelse(daycal > median(daycal,na.rm=T),"Above median", "Below median"),
         daily_Eggs_med = ifelse(daily_Eggs > median(daily_Eggs,na.rm=T),"Above median", "Below median"),
         daily_Fruits_med = ifelse(daily_Fruits > median(daily_Fruits,na.rm=T),"Above median", "Below median"),
         daily_Grains_med = ifelse(daily_Grains > median(daily_Grains,na.rm=T),"Above median", "Below median"),
         daily_Legumes_med = ifelse(daily_Legumes > median(daily_Legumes,na.rm=T),"Above median", "Below median"),
         daily_Meats_med = ifelse(daily_Meats > median(daily_Meats,na.rm=T),"Above median", "Below median"),
         daily_Oils_med = ifelse(daily_Oils > median(daily_Oils,na.rm=T),"Above median", "Below median"),
         daily_Sweets_med = ifelse(daily_Sweets > median(daily_Sweets,na.rm=T),"Above median", "Below median"),
         daily_Vegetables_med = ifelse(daily_Vegetables > median(daily_Vegetables,na.rm=T),"Above median", "Below median"),
         daily_Milk_med = ifelse(daily_Milk > median(daily_Milk,na.rm=T),"Above median", "Below median")
  )
# the diversity close to the engraftment for the patients 
# average food diversity between the period 

colnames(df_main) 

df_main %>% select(-mrn) %>%  summary

featlist <- c("d_carb_med",
              "d_fat_med",
              "d_fiber_med",
              "d_protein_med",
              "d_sugar_med",
              "daycal_med",
              "daily_Eggs_med",
              "daily_Fruits_med", 
              "daily_Milk_med",
              "daily_Grains_med",
              "daily_Legumes_med",
              "daily_Meats_med",
              "daily_Oils_med",
              "daily_Sweets_med",
              "daily_Vegetables_med")

df_main %>% count(TRMevent, OSevent)  %>% 
  mutate(status = if_else(OSevent ==1, 'dead', 'alive')) %>% 
  select(-OSevent)
```


# OS

```{r OS}
OS_mult_comb_fg <- coxph(Surv(OStime_landmark,OSevent) ~ daily_Eggs + daily_Fruits+ daily_Grains + daily_Legumes +daily_Meats + daily_Oils +daily_Sweets +daily_Vegetables + daily_Milk + Intensity + Source, data=df_main) %>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for Overall Survival, landmarked at day of discharging; all fg")

OS_mult_comb_age <- coxph(Surv(OStime_landmark,OSevent) ~ age, data=df_main %>% mutate(age = age/10)) %>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for Overall Survival, landmarked at day of discharging; age")

OS_mult_comb_macro <- coxph(Surv(OStime_landmark,OSevent) ~ 
                              d_carb + 
                              d_fat + 
                              d_fiber +
                              #d_protein+ 
                              d_sugar + 
                              Intensity + 
                              Source, data=df_main) %>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for Overall Survival, landmarked at day of engraftment; all macronutrients")


OS_mult_comb_cal <- coxph(Surv(OStime_landmark,OSevent) ~ 
                              daycal + 
                              Intensity + 
                              Source, data=df_main) %>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for Overall Survival, landmarked at day of engraftment; calories")

OS_mult_comb_alpha7_21 <- coxph(Surv(OStime_landmark,OSevent) ~ 
                              median7_21 , data=df_main) %>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for Overall Survival, landmarked at day of engraftment; alpha7_21")

OS_mult_comb_alpha_w1 <- coxph(Surv(OStime_landmark,OSevent) ~ 
                              first_in_w1 , data=df_main) %>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for Overall Survival, landmarked at day of engraftment; first_in_w1")

OS_mult_comb_ave_faith <- coxph(Surv(OStime_landmark,OSevent) ~ 
                              ave_faith + 
                              Intensity + 
                              Source, data=df_main) %>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for Overall Survival, landmarked at day of engraftment; ave_faith") 

OS_mult_comb_ave_both <- coxph(Surv(OStime_landmark,OSevent) ~ 
                              daycal + 
                              median7_21 +
                              Intensity + 
                              Source, data=df_main) %>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for Overall Survival, landmarked at day of engraftment; both") 


coxph(Surv(OStime_landmark,OSevent) ~ median7_21 , data=df_main) %>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Univariable analysis for Overall Survival, landmarked at day of engraftment; alpha7_21")  %>% as_gt %>% gt::gtsave(filename = '../data/158_uni_alpha7_21_OS.png')

coxph(Surv(OStime_landmark,OSevent) ~ first_in_w1 , data=df_main) %>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Univariable analysis for Overall Survival, landmarked at day of engraftment; first_in_w1")  %>% as_gt %>% gt::gtsave(filename = '../data/158_uni_first_in_w1_OS.png')
```


```{r teng_OS}
OS_univ_comb <- df_main %>% 
  select(OStime_landmark,
         OSevent,
         d_carb,
         d_fat,
         d_fiber,
         d_protein,
         d_sugar,
         daycal,
         daily_Eggs,
         daily_Fruits, daily_Milk,
         daily_Grains,
         daily_Legumes,
         daily_Meats,
         daily_Oils,
         daily_Sweets,
         daily_Vegetables, Intensity, Source
  ) %>% 
  tbl_uvregression(method=survival::coxph,
                   y=Surv(OStime_landmark,OSevent),
                   formula= "{y} ~ {x} + Intensity + Source",
                   exponentiate = TRUE
  ) %>% bold_p() %>% modify_caption("OS landmarked at engraftment - Cox model adjusted for conditioning intensity and graft source")

OS_univ_comb
gt::gtsave(as_gt(OS_univ_comb), file = file.path('../data/158_OS_univ_comb.png'))
```


```{r}
OS_mult_comb_fg
OS_mult_comb_macro
OS_mult_comb_cal
OS_mult_comb_alpha7_21
OS_mult_comb_alpha_w1
OS_mult_comb_ave_faith
```

# TRM


```{r TRM}
TRM_mult_comb_fg <- crr(Surv(tevent_landmark,TRMevent) ~daily_Eggs + daily_Fruits+ daily_Grains + daily_Legumes +daily_Meats + daily_Oils +daily_Sweets +daily_Vegetables + daily_Milk  + Intensity + Source, data=df_main, failcode = "TRM")%>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for TRM, landmarked at day of discharging; all fg")

TRM_mult_comb_macro <- crr(Surv(tevent_landmark,TRMevent) ~ d_carb +d_fat + d_fiber +d_protein+ d_sugar  + Intensity + Source, data=df_main, failcode = "TRM")%>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for TRM, landmarked at day of discharging; all macronutrients")

TRM_mult_comb_cal <- crr(Surv(tevent_landmark,TRMevent) ~ daycal  + Intensity + Source, data=df_main, failcode = "TRM")%>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for TRM, landmarked at day of discharging; calories")

TRM_mult_comb_median7_21 <- crr(Surv(tevent_landmark,TRMevent) ~ median7_21  + Intensity + Source, data=df_main, failcode = "TRM")%>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for TRM, landmarked at day of discharging; median7_21")

TRM_mult_comb_first_in_w1 <- crr(Surv(tevent_landmark,TRMevent) ~ first_in_w1  + Intensity + Source, data=df_main, failcode = "TRM")%>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for TRM, landmarked at day of discharging; first_in_w1")

TRM_mult_comb_ave_faith <- crr(Surv(tevent_landmark,TRMevent) ~ ave_faith  + Intensity + Source, data=df_main, failcode = "TRM")%>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for TRM, landmarked at day of discharging; ave_faith")


crr(Surv(tevent_landmark,TRMevent) ~ median7_21 , data=df_main) %>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Univariable analysis for TRM, landmarked at day of engraftment; alpha7_21")  %>% as_gt %>% gt::gtsave(filename = '../data/158_uni_alpha7_21_TRM.png')

crr(Surv(tevent_landmark,TRMevent) ~ first_in_w1 , data=df_main) %>% 
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Univariable analysis for TRM, landmarked at day of engraftment; first_in_w1")  %>% as_gt %>% gt::gtsave(filename = '../data/158_uni_first_in_w1_TRM.png')
```

```{r}
TRM_univ_comb <- df_main %>% 
  select(tevent_landmark,
         TRMevent,
         d_carb,
         d_fat,
         d_fiber,
         d_protein,
         d_sugar,
         daycal,
         daily_Eggs,
         daily_Fruits, daily_Milk,
         daily_Grains,
         daily_Legumes,
         daily_Meats,
         daily_Oils,
         daily_Sweets,
         daily_Vegetables, Intensity, Source
  ) %>% 
  tbl_uvregression(method=crr,
                   y=Surv(tevent_landmark,TRMevent),
                   method.args = list(failcode="TRM"),
                   formula= "{y} ~ {x} + Intensity + Source",
                   exponentiate = TRUE
  ) %>% bold_p() %>% modify_caption("TRM landmarked at engraftment - Cox model adjusted for conditioning intensity and graft source")

TRM_univ_comb 
gt::gtsave(as_gt(TRM_univ_comb), file = file.path('../data/158_TRM_univ_comb.png'))
```


```{r}
TRM_mult_comb_fg
TRM_mult_comb_macro
TRM_mult_comb_cal
TRM_mult_comb_median7_21
TRM_mult_comb_first_in_w1
TRM_mult_comb_ave_faith
```

# length of stay

```{r}
#df_main <- df_main %>% filter(batch == 'batch1') 
LOS_mult_comb_fg <- coxph(Surv(tLOS,LOS) ~ daily_Eggs + daily_Fruits+ daily_Grains + daily_Legumes +daily_Meats + daily_Oils +daily_Sweets +daily_Vegetables + daily_Milk + Intensity + Source, data=df_main) %>% 
  tbl_regression(exponentiate=TRUE,estimate_fun = function(x) style_ratio(x,digits=3)) %>% bold_p() %>% modify_caption("Length of stay after engraftment; all fg")

LOS_mult_comb_macro <- coxph(Surv(tLOS,LOS) ~ 
                              d_carb + 
                              d_fat + 
                              d_fiber +
                              #d_protein+ 
                              d_sugar + 
                              Intensity + 
                              Source, data=df_main) %>% 
  tbl_regression(exponentiate=TRUE, estimate_fun = function(x) style_ratio(x,digits=3)) %>% bold_p() %>% modify_caption("Length of stay after engraftment; all macronutrients")


LOS_mult_comb_cal <- coxph(Surv(tLOS,LOS) ~ 
                              daycal + 
                              Intensity + 
                              Source, data=df_main) %>% 
  tbl_regression(exponentiate=TRUE, estimate_fun = function(x) style_ratio(x,digits=3)) %>% bold_p() %>% modify_caption("Length of stay after engraftment; calories")

LOS_mult_comb_alpha7_21 <- coxph(Surv(tLOS,LOS) ~ 
                              median7_21 + 
                              Intensity + 
                              Source, data=df_main) %>% 
  tbl_regression(exponentiate=TRUE, estimate_fun = function(x) style_ratio(x,digits=3)) %>% bold_p() %>% modify_caption("Length of stay after engraftment; alpha7_21")

LOS_mult_comb_alpha_w1 <- coxph(Surv(tLOS,LOS) ~ 
                              first_in_w1 + 
                              Intensity + 
                              Source, data=df_main) %>% 
  tbl_regression(exponentiate=TRUE, estimate_fun = function(x) style_ratio(x,digits=3)) %>% bold_p() %>% modify_caption("Length of stay after engraftment; first_in_w1")

LOS_mult_comb_ave_faith <- coxph(Surv(tLOS,LOS) ~ 
                              ave_faith + 
                              Intensity + 
                              Source, data=df_main) %>% 
  tbl_regression(exponentiate=TRUE, estimate_fun = function(x) style_ratio(x,digits=3)) %>% bold_p() %>% modify_caption("Length of stay after engraftment; ave_faith")
```


```{r}
LOS_univ_comb <- df_main %>% 
  select(tLOS,
         LOS,
         d_carb,
         d_fat,
         d_fiber,
         d_protein,
         d_sugar,
         daycal,
         daily_Eggs,
         daily_Fruits, daily_Milk,
         daily_Grains,
         daily_Legumes,
         daily_Meats,
         daily_Oils,
         daily_Sweets,
         daily_Vegetables, Intensity, Source
  ) %>% 
  tbl_uvregression(method=survival::coxph,
                   y=Surv(tLOS,LOS),
                   formula= "{y} ~ {x} + Intensity + Source",
                   exponentiate = TRUE,
                   estimate_fun = function(x) style_ratio(x,digits=3)
  ) %>% bold_p() %>% modify_caption("Length of stay after engraftment - Cox model adjusted for conditioning intensity and graft source")

LOS_univ_comb
gt::gtsave(as_gt(LOS_univ_comb), file = file.path('../data/158_LOS_univ_comb.png'))
```


```{r}
LOS_mult_comb_fg
LOS_mult_comb_macro
LOS_mult_comb_cal
LOS_mult_comb_alpha7_21
LOS_mult_comb_alpha_w1
LOS_mult_comb_ave_faith
```

## % discharged VS days post engraftment

```{r}
los_plots <- featlist %>% 
  set_names(featlist) %>% 
  map(function(feature_){
    survfit2(as.formula(str_glue("Surv(tLOS,LOS)~{feature_}")), data = df_main) %>%
          ggsurvfit(type = "risk", linewidth = 0.8) +
          add_pvalue("annotation",size=3) +
          add_confidence_interval()+
          ylab("% patients discharged alive")+ggtitle(str_glue('{feature_}'))
  })
 
cowplot::plot_grid(plotlist = los_plots[7:15], align = 'hv', nrow = 2)
ggsave('../data/158_LOS_features_2.pdf', width = 12)
```


# GRM

```{r GRM}
GRM_mult_comb_fg <- crr(Surv(tevent_landmark,GRMevent) ~ daily_Eggs + daily_Fruits+ daily_Grains + daily_Legumes +daily_Meats + daily_Oils +daily_Sweets +daily_Vegetables + daily_Milk + Intensity + Source, data=df_main, failcode = "GRM")%>%
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for GRM, landmarked at day of discharging; all fg")

GRM_mult_comb_macro <- crr(Surv(tevent_landmark,GRMevent) ~  d_carb +d_fat + d_fiber +d_protein+ d_sugar  + Intensity + Source, data=df_main, failcode = "GRM")%>%
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for GRM, landmarked at day of discharging; all macronutrients")

GRM_mult_comb_cal <- crr(Surv(tevent_landmark,GRMevent) ~ daycal  + Intensity + Source, data=df_main, failcode = "GRM")%>%
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for GRM, landmarked at day of discharging; calories")

GRM_mult_comb_median7_21 <- crr(Surv(tevent_landmark,GRMevent) ~ median7_21  + Intensity + Source, data=df_main, failcode = "GRM")%>%
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for GRM, landmarked at day of discharging; median7_21")

GRM_mult_comb_first_in_w1 <- crr(Surv(tevent_landmark,GRMevent) ~ first_in_w1  + Intensity + Source, data=df_main, failcode = "GRM")%>%
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for GRM, landmarked at day of discharging; first_in_w1")

GRM_mult_comb_ave_faith <- crr(Surv(tevent_landmark,GRMevent) ~ ave_faith  + Intensity + Source, data=df_main, failcode = "GRM")%>%
  tbl_regression(exponentiate=TRUE) %>% bold_p() %>% modify_caption("Multivariable analysis for GRM, landmarked at day of discharging; ave_faith")
```

```{r}

GRM_univ_comb <- df_main %>% 
  filter(!is.na(d100_a_gvhd)) %>% 
  select(tevent_landmark,
         GRMevent,
         d_carb,
         d_fat,
         d_fiber,
         d_protein,
         d_sugar,
         daycal,
         daily_Eggs,
         daily_Fruits, daily_Milk,
         daily_Grains,
         daily_Legumes,
         daily_Meats,
         daily_Oils,
         daily_Sweets,
         daily_Vegetables, Intensity, Source
  ) %>% 
  tbl_uvregression(method=crr,
                   y=Surv(tevent_landmark,GRMevent),
                   method.args = list(failcode="GRM"),
                   formula= "{y} ~ {x} + Intensity + Source",
                   exponentiate = TRUE
  ) %>% bold_p() %>% modify_caption("GRM landmarked at engraftment - Cox model adjusted for conditioning intensity and graft source")

gt::gtsave(as_gt(GRM_univ_comb), file = file.path('../data/158_GRM_univ_comb.png'))
```


```{r}
GRM_mult_comb_fg
GRM_mult_comb_macro
GRM_mult_comb_cal
GRM_mult_comb_median7_21
GRM_mult_comb_first_in_w1
GRM_mult_comb_ave_faith
```

