---
title: "to find out the numbers for the manuscript"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(vdbR)
connect_database()
list_table_from_database('patient')
get_table_from_database('patient_allo_ks_20221104')
```

```{r}
# to find out the number and days of EN, TPN patients
PTB <- read_csv('../data/156_combined_PTB.csv')

support <- read_csv('../data/NutritionSupport_DietPatients.csv') %>% 
  filter(MRN %in% PTB$mrn) %>% 
  mutate(date = mdy(`Date Nutrition Support`)) %>% 
  inner_join(PTB %>% select(MRN = mrn, hct))

# TPN days  
tpn <- support %>% 
  filter(`Nutrition Support` == 'TPN') %>% 
  select(mrn = MRN,
         date,hct,
         nutrition_support = `Nutrition Support`) %>% 
  mutate(liquidday = as.numeric(date - hct))

# summary of the TPN days of the patients
tpn %>% distinct(mrn) %>% nrow
summary(tpn$liquidday)
```

```{r}
# EN days
en <- support %>% 
  filter(`Nutrition Support` == 'EN') %>% 
  select(mrn = MRN,
         date,hct,
         nutrition_support = `Nutrition Support`) %>% 
  mutate(liquidday = as.numeric(date - hct))

# summary of the EN days of the patients
en %>% distinct(mrn) %>% nrow
summary(en$liquidday)

all_unique_pt <- bind_rows(en, tpn) %>% distinct(mrn)
```

```{r}
# the patients usage of the antibiotics
# the abx data
b2 <- read_rds('../data/batch2_medication_exposures.rds')
# idk how Tsoni defined the broad spectrum antibiotics
```


```{r}
# the fig 3 numbers F mouse data 
newest <- read_csv("../data/178_mouse_data.csv")

abxgrp <- newest %>%
  filter(abx_treatment == 'biapenem') %>%
  select(Experiment, diet_treatment, abx_treatment, Day,  Mouse_identifier,Log_CFUs_per_GramStool )%>%
  filter(Day != 3) %>%
  spread('Day', 'Log_CFUs_per_GramStool') %>%
  rename(d0 = `0`, d6 = `6`) %>%
  mutate(d60_foldchange = d6/d0)

# summary of the fold change in the text for the abx treated group

sucrose <- abxgrp %>% filter(diet_treatment == 'sucrose')
vehicle <- abxgrp %>% filter(diet_treatment == 'vehicle')
```


```{r}
# the vehicle group
summary(vehicle$d60_foldchange) 
vehicle %>% nrow


# the p value from wilcoxon test
vehiclelong <- vehicle %>% select(-d60_foldchange) %>% 
  gather('time', 'logCFU', d0:d6)

compare_means(
  logCFU ~ time,
  data = vehiclelong,
  method = "wilcox.test",
  paired = T,
  group.by = NULL,
  ref.group = 'd0'
)$p.format
```

```{r} 
# the sucrose group
summary(sucrose$d60_foldchange) 
sucrose %>% nrow

# the p value from wilcoxon test
sucroselong <- sucrose %>% select(-d60_foldchange) %>% 
  gather('time', 'logCFU', d0:d6)

compare_means(
  logCFU ~ time,
  data = sucroselong,
  method = "wilcox.test",
  paired = T,
  group.by = NULL,
  ref.group = 'd0'
)$p.format
```

```{r}
# the p value between the week 1 smoothie VS vehicle in abx group
abx <- newest %>%
  filter(abx_treatment == 'biapenem') %>%
  select( diet_treatment, abx_treatment, Day, Mouse_identifier,Log_CFUs_per_GramStool )%>%
  filter(Day == 6)

compare_means(
  Log_CFUs_per_GramStool ~ diet_treatment,
  data = abx,
  method = "wilcox.test",
  paired = F,
  group.by = NULL,
  ref.group = 'vehicle'
)$p.format
```

```{r}
# the broad spectrum abx data
b2med <- read_csv('../data/137_batch2_empircal_oral.csv')
b1med <- read_csv('../data/134_batch1_empirical_abx.csv')
both <- bind_rows(b1med, b2med)
```

# F2  main results

```{r}
macro <- read_csv('../data/090_model_alpha_macro_fat_post_interaction.csv')
fg <- read_csv('../data/171_div_model_fg_post_interaction.csv')

# to find the quantiles of the post_coeff
macro %>% 
  select(starts_with('b_')) %>% 
  gather('item','coeff') %>% 
  group_by(item) %>% 
  tidybayes::median_qi(coeff, .width = c(.95))

fg %>% 
  select(starts_with('b_')) %>% 
  gather('item','coeff') %>% 
  group_by(item) %>% 
  tidybayes::median_qi(coeff, .width = c(.95))

entero%>% 
  group_by(item) %>% 
  tidybayes::median_qi(coeff, .width = c(.95))


```

# general diet data related

```{r}
dtb <- read_csv('../data/152_combined_DTB.csv')

dtb %>% distinct(Food_code) %>% nrow
```

# about broad spectrum antibiotics   

```{r}
PTB <- read_csv('../data/156_combined_PTB.csv')

picked <-  c('vancomycin', 'imipenem_cilastatin','meropenem','ertapenem', 'cefepime', 'linezolid','metronidazole','piperacillin_tazobactam')

med2 <- read_rds('../data/batch2_medication_exposures.rds') %>% 
  select(MRN:stop_date, drug_name, route) %>% 
  mutate(drug_name_clean = str_replace_all(drug_name, '-', '_')) %>% 
  mutate(drug_name_clean = str_to_lower(drug_name_clean)) %>% 
  mutate(drug_name_clean = case_when(
    drug_name_clean == 'levofloxacin (levaquin)' ~ 'levofloxacin',
    drug_name_clean == 'vancomycin invest' ~ 'vancomycin',
    TRUE ~ drug_name_clean
  )) %>% 
  mutate(mrn = as.numeric(MRN)) %>% 
  #filter(drug_name_clean %in% picked) %>% 
  mutate(together = str_glue('{drug_name_clean}__{route}')) %>% 
  filter(! together %in% c('vancomycin__IV')) 

med1 <- read_rds('../data/tasks_nutrition_batch1_2022-11-29.rds') %>% 
  select(MRN:stop_date, drug_name, route) %>% 
  mutate(drug_name_clean = str_replace_all(drug_name, '-', '_')) %>% 
  mutate(drug_name_clean = str_to_lower(drug_name_clean),
         mrn = as.numeric(MRN))%>% 
  mutate(together = str_glue('{drug_name_clean}__{route}')) %>% 
  filter(! together %in% c('vancomycin__IV')) %>% 
  select(colnames(med2))

med_all <- bind_rows(med1, med2) %>% 
  filter(mrn %in% PTB$mrn) 

med_all %>% write_csv('../data/169_all_medication.csv')

med_all <- read_csv('../data/169_all_medication.csv')
med1 %>% filter(med_class1 == 'anti-infectives') %>% count(med_class2, sort = T)
med1 %>% glimpse()
med1 %>% count(med_class1, sort = T)
# no: antiviral agents, antifungals, antituberculosis agents, antimalarial agents, amebicides, anthelmintics, leprostatics
```

```{r}
# find out about days of using the empirical ones 
meddf <- med_all %>% 
  filter(drug_name_clean %in% picked) %>% 
  left_join(PTB %>% select(mrn, hct)) %>% 
  mutate(startday = as.numeric(start_date - hct))

summary(meddf$startday)

meddf %>% 
  gghistogram(x = 'startday')


meddf %>% distinct(mrn) %>% nrow
```

