---
title: "the CLR transformation of the genus"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(compositions)
library(brms)
library(ggpubr)
options(mc.cores = parallel::detectCores())
rstan::rstan_options(auto_write = TRUE)
ncores <- parallel::detectCores()
```

CLR works with counts, not relab. And also need to add a pseudocount

```{r}
meta <- read_csv('../data/153_combined_META.csv')
library(vdbR)
connect_database('~/dbConfig.txt')
get_table_from_database('asv_annotation_blast_ag')
cts <- get_counts_subset(meta$sampleid)
cts_ <- cts %>% 
  select(asv_key, sampleid, count)
annot <- asv_annotation_blast_ag %>% 
  filter(asv_key %in% cts_$asv_key)
cts_all <- cts_ %>% 
  left_join(annot %>%  select(asv_key, genus), by  = 'asv_key') %>% 
  group_by(sampleid, genus) %>% 
  summarise(cnt = sum(count)) %>% 
  spread('sampleid', 'cnt', fill = 0) %>% 
  filter(!is.na(genus)) %>% 
  column_to_rownames('genus')
```


```{r}
clr_res <- clr(cts_all + 0.5) %>% 
  as.data.frame()  %>% 
  rownames_to_column('genus') %>% 
  gather('sampleid','clr', names(.)[2]:names(.)[ncol(.)])

# the distribution of the transformed counts
# find the median of each genus
clr_medians <- clr_res %>% 
  group_by(genus) %>% 
  summarise(mediangenus = median(clr))

clr_medians %>% gghistogram(x = 'mediangenus')
clr_medians %>% ggboxplot(y = 'mediangenus')

# I need to see the distribution of the actual genus transformed counts
few <- read_csv('../data/087_extra_6_genus_name.csv')

clr_res %>% filter(genus %in% few$genus) %>% 
  gghistogram(x = 'clr', facet.by = 'genus')
```

```{r}
meta <- read_csv('../data/153_combined_META.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = factor(mrn)) %>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100) 

clr_few <- clr_res %>% filter(genus %in% few$genus) %>% 
  spread('genus','clr')

extra_full <- meta %>% 
  inner_join(clr_few)
```


```{r}
model_genus_clr <- Enterococcus ~ 0 + 
                fg_fruit+
               fg_meat+
               fg_milk+
               fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               intensity +
               empirical+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin)
get_prior( model_genus_clr,  
              data = extra_full)

priors <- c(# for the food group variables
            prior(normal(0, 1.2), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1.2), class = 'b', coef = "fg_veggie"),
            # for the TPN 
            prior(normal(0, 0.1), class = 'b', coef = "TPNTRUE"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "ENTRUE"),
            # for the empirical 
            prior(normal(0, 0.5), class = 'b', coef = "empiricalTRUE")
            # for the intensity 
            #prior(normal(-3, 1), class = 'b', coef = "intensityreduced"),
            #prior(normal(-3, 1), class = 'b', coef = "intensityablative"),
            #prior(normal(-3, 1), class = 'b', coef = "intensitynonablative")
            )
```

```{r}
genus6 <- few %>% pull(genus)
ret_genus6 <- genus6 %>% 
  set_names(genus6) %>% 
  purrr::map(function(genus) {
    mod =  brm( as.formula(str_glue('{genus}  ~ 
               0 +
                fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+ 
                fg_grain+
                fg_sweets+  
                fg_legume+
                fg_veggie+
               intensity +
                empirical+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin)')),  
                data = extra_full, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
              control = list(adapt_delta = 0.99),
              seed = 456, sample_prior = T) 
  })

post_df <- ret_genus6 %>% 
  imap(~ (suppressWarnings(posterior_samples(.x)) ))  %>% 
  bind_rows(.id = 'genus')  
post_df %>% 
  write_csv('../data/170_genus6_foodgroup_model_post_extra_few.csv')
```


```{r}
post <- read_csv('../data/170_genus6_foodgroup_model_post_extra_few.csv') %>% 
  select(genus, starts_with('b_fg')) %>% 
  gather('item','coeff', names(.)[2]:names(.)[ncol(.)])

key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')
post_res_genera <- post %>% 
  group_by(genus, item) %>% 
  summarise(q50 = median(coeff),
            q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975),
            q12.5 = quantile(coeff, probs = 0.125),
            q87.5 = quantile(coeff, probs = 0.875),
            q1.25 = quantile(coeff, probs = 0.0125),
            q98.75 = quantile(coeff, probs = 0.9875),
            q0.5 = quantile(coeff, probs = 0.005),
            q99.5 = quantile(coeff, probs = 0.995)
            ) %>% 
  ungroup() %>% 
  mutate(mark = if_else(q99.5 < 0 | q0.5 > 0, '***', if_else(q98.75 < 0 | q1.25 > 0, '**', if_else(q97.5 < 0 | q2.5 > 0, '*', '')))) %>% 
  mutate(color = if_else(q87.5 < 0, 'steelblue', if_else(q12.5 > 0, 'maroon', 'white'))) %>% 
  mutate(item = str_replace(item, 'b_ave_','')) %>% 
  mutate(item = str_to_title(item)) %>% 
  mutate(item = str_replace(item, 'B_','')) %>% 
  left_join(key %>% select(item = fg1_name, shortname))

fg_order <- read_csv('../data/068_fg_sorting_order.csv') %>% pull(shortname)

perc_side <- post %>%
  group_by(genus,item ) %>%
  count(coeff >= 0) %>%
  mutate(perc = round(n/4000, 2)) %>%
  mutate(side = if_else(`coeff >= 0` == 'TRUE', 'positive', 'negative')) %>%
  ungroup() %>%
  select(genus, item, perc, side) %>%
  spread('side', 'perc') %>%
  mutate(item = str_replace(item, 'b_','')) %>%
  left_join(key %>% select(item = fg1_name, shortname), by = "item") %>%
  mutate(color = if_else(positive >= 0.75, 'maroon', if_else(negative >= 0.75, 'steelblue', 'white'))) %>%
  mutate(mark = if_else(negative >= 0.99 | positive >= 0.99, '***', if_else(negative >= 0.975 | positive >= 0.975, '**', if_else(negative >= 0.95 | positive >= 0.95, '*', '')))) %>%
  # order the columns by the number of stars in the columns
  mutate(genus = factor(genus,
   levels =c('Enterococcus','Klebsiella','Escherichia','Enterobacter','Citrobacter','Cronobacter'))) %>%
  mutate(shortname = factor(shortname, levels = fg_order))

col_key <- perc_side %>% 
  ungroup() %>% 
  distinct(color) %>% 
  pull(color)
names(col_key) <- col_key
genus_fg_extra <- ggplot(perc_side, aes(x = genus, y = shortname)) +
  geom_tile(aes(fill = color,  x = genus, y =  shortname), alpha = 0.5, color='gray0', width=1, height=1) +
  geom_text(aes(label = mark, x = genus,y =  shortname),
            nudge_y = -0.05, nudge_x = 0,size = 3) +
  scale_fill_manual(values = col_key, labels = c('Less than 75% CI crosses 0', '75% CI < 0 negative','75% CI > 0 positive')) +
  theme_void() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle=90, hjust=1, size=axis_text_size),
        axis.text.y=element_text(size=axis_text_size, hjust=0.95,vjust=0.2),
        axis.title=element_text(size=axis_title_size),
        legend.position = 'none',legend.text=element_text(size=8),
        legend.key = element_rect( colour = "gray50"))
```


```{r}

ggsave('../data/170_CLR_extra_genera6.pdf', width =  60,plot = genus_fg_extra,
       height = 70, 
         units = c("mm"),
         dpi = 400)
```

```{r}
log10s <- read_csv('../data/088_genus_relab_log10_wide.csv') %>% 
  gather('genus','log10s', names(.)[2]:names(.)[ncol(.)]) %>% 
  group_by(genus) %>% 
  summarise(mediangenus = median(log10s))

log10s %>% gghistogram(x = 'mediangenus', bins = 100)
```