---
title: "Interaction model with diversity"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(1)
library(tidyverse)
library(brms)   
library(ggpubr)
library(tidybayes)
library(cowplot)
library(ggridges)
library(brmstools)
library(bayesplot)
options(mc.cores = parallel::detectCores())
rstan::rstan_options(auto_write = TRUE)
theme_set(theme_tidybayes() + panel_border())
ncores <- parallel::detectCores()
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')
axis_text_size <- 10
axis_title_size <- 10
dtb <- read_csv('../data/152_combined_DTB.csv') 
range(dtb$fdrt)
```

# the interaction model with diversity

```{r}
meta <- read_csv('../data/153_combined_META.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = factor(mrn)) %>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100) %>% 
  mutate(abx = if_else(empirical == 'TRUE', 1, 0),
         TPN = if_else(TPN == 'TRUE', 1, 0),
         EN = if_else(EN == 'TRUE', 1, 0)) %>% 
  mutate(      fg_fruit_e= fg_fruit*abx,  
                fg_meat_e=fg_meat*abx,
                fg_milk_e=fg_milk*abx,
                fg_oils_e=fg_oils*abx,
                fg_egg_e=fg_egg*abx,
                fg_grain_e=fg_grain*abx,
                fg_sweets_e=fg_sweets*abx,
                fg_legume_e=fg_legume*abx,
                fg_veggie_e = fg_veggie*abx)

```


```{r}
div_model  <- log(simpson_reciprocal) ~ 0 +
                intensity+
               fg_fruit_e+
                fg_meat_e+
                fg_milk_e+
                fg_oils_e+
                fg_egg_e+
                fg_grain_e+
                fg_sweets_e+
                fg_legume_e+
                fg_veggie_e+
                abx+
               fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+
                fg_grain+
                fg_sweets+
                fg_legume+
                fg_veggie+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin)
get_prior(div_model,data = meta )

```

```{r}
div_priors <- c(# for the food group variables
            prior(normal(0, 1), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie"),
            # interaction terms
            prior(normal(0, 1), class = 'b', coef = "fg_egg_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie_e"),
            # for the TPN
            prior(normal(0, 0.1), class = 'b', coef = "TPN"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "EN"),
            # for the empirical
            prior(normal(0, 0.5), class = 'b', coef = "abx"),
            # for the intensity
            prior(normal( 2, .1), class = 'b', coef = "intensityablative"),
            prior(normal( 2, .1), class = 'b', coef = "intensityreduced"),
            prior(normal( 2, .1), class = 'b', coef = "intensitynonablative")
            )
```


```{r}
model_div <- brm( div_model,  
              data = meta, 
              warmup = 1000, iter = 3000, 
              prior = div_priors,
              cores = ncores, 
              chains = 2, 
               control = list(adapt_delta = 0.99),
              seed = 123, sample_prior = T) 

# actually draw samples from the priors 
samples_prior <- prior_draws(model_div)
# save it for future use
post_res <- suppressWarnings(posterior_samples(model_div)) 
post_res %>%  write_csv('../data/171_div_model_fg_post_interaction.csv')
colnames(meta)

get_prior(div_model,  
              data = meta)
```
```{r}
brms::stancode(model_div)

df <- posterior_predict(model_div, re_formula = ~ (1 | timebin))
variables(model_div)
```

# use their function to see the interaction effects

```{r}
# I wanna use the original data types for this thing
meta_original <- read_csv('../data/153_combined_META.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = factor(mrn)) 

# %>% 
#   mutate(fg_egg = fg_egg/100,
#          fg_fruit = fg_fruit/100,
#          fg_grain = fg_grain/100,
#          fg_legume = fg_legume/100,
#          fg_meat = fg_meat/100,
#          fg_milk = fg_milk/100,
#          fg_oils = fg_oils/100,
#          fg_sweets = fg_sweets/100,
#          fg_veggie = fg_veggie/100)

mod_original <- log(simpson_reciprocal) ~ 0 +        
                intensity+
                empirical+
               fg_fruit:empirical+
                fg_meat:empirical+
                fg_milk:empirical+
                fg_oils:empirical+
                fg_egg:empirical+
                fg_grain:empirical+
                fg_sweets:empirical+
                fg_legume:empirical+
                fg_veggie:empirical+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin)

get_prior(mod_original,data = meta_original )

div_priors_original <- c(# for the food group variables
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_veggie"),
            # interaction terms
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_veggie"),
            # for the TPN
            prior(normal(0, 0.1), class = 'b', coef = "TPNTRUE"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "ENTRUE"),
            # for the empirical
            prior(normal(0, 0.5), class = 'b', coef = "empiricalTRUE"),
            # for the intensity
            prior(normal( 2, .1), class = 'b', coef = "intensityablative"),
            prior(normal( 2, .1), class = 'b', coef = "intensityreduced"),
            prior(normal( 2, .1), class = 'b', coef = "intensitynonablative")
            )

model_div_original <- brm( mod_original,  
              data = meta_original, 
              warmup = 1000, iter = 3000, 
              prior = div_priors_original,
              cores = ncores, 
              chains = 2, 
               control = list(adapt_delta = 0.99),
              seed = 123, sample_prior = T, file = '../data/173_interaction_conditional_model')
```

```{r}
ce=conditional_effects(model_div_original)
str(ce)
tt_sweets_abx <- ce$`fg_sweets:empirical`
meta_original %>% summarise(across(everything(), list(mean)))
pred_dat = tt_sweets_abx %>% 
  distinct(fg_sweets, empirical) %>% 
  mutate(intensity = 'nonablative',
         TPN = F, EN = F, 
         fg_fruit = mean(meta_original$fg_fruit),
         fg_meat = mean(meta_original$fg_meat),
         fg_milk = mean(meta_original$fg_milk),
         fg_oils = mean(meta_original$fg_oils),
         fg_egg = mean(meta_original$fg_egg),
         fg_grain = mean(meta_original$fg_grain),
         fg_legume = mean(meta_original$fg_legume),
         fg_veggie = mean(meta_original$fg_veggie),
         mrn = NA, timebin= NA)
post.epred = epred_draws(model_div_original, newdata=pred_dat)

```
```{r}
post.epred %>% 
 ggplot(aes(x = fg_sweets, y = .epred, fill = empirical, color = empirical)) +
  stat_lineribbon(.width = seq(from = .03, to = .95, by = .1),
                  alpha = .2, size = 0) 
```

```{r}
# I wanna make a set of all of these with all the other panels

vars <- tibble(vars = names(ce)) %>% 
  filter(str_detect(vars, ':'))

res <- vars %>% 
  pull(vars) %>% 
  set_names(vars %>% 
  pull(vars)) %>% 
  map(function(var){
    pred_dat = ce %>% pluck(var) %>% 
      select(names(.)[1]:names(.)[17]) %>% 
      select(-`log(simpson_reciprocal)`, -simpson_reciprocal) %>% 
      distinct()
    post.epred = epred_draws(model_div_original, newdata=pred_dat)
    
   g=  ggplot(data = post.epred, aes_string(colnames(post.epred)[1], colnames(post.epred)[20], fill = colnames(post.epred)[2], color = colnames(post.epred)[2])) +
  stat_lineribbon(.width = seq(from = .03, to = .69, by = .1),
                  alpha = .2, size = 0) + 
      scale_fill_manual(values = c('darkgray','maroon')) +
  scale_colour_manual(values = c('darkgray','maroon')) +
  #ylim(0, 3) +
  labs(y = 'Predicted log(diversity)') +
  theme_classic() +
  theme(aspect.ratio = 1, legend.position = 'none')
    return(g)
  })
library(cowplot)
ret <- plot_grid(plotlist = res, nrow = 3)
ggsave('../data/173_beam_ce.pdf', width = 9, height = 8) 
```


```{r}
plot(conditional_effects(model_div_original))
```

```{r plot_interaction}
inter <- plot(conditional_effects(model_div_original, effects = 'empirical:fg_sweets'),ask = F ) +
  scale_fill_manual(values = c('darkgray','maroon')) +
  scale_colour_manual(values = c('darkgray','maroon')) +
  ylim(0, 3) +
  labs(y = 'Predicted log(diversity)') +
  theme_classic() +
  theme(aspect.ratio = 1, legend.position = 'none')

dat <- conditional_effects(model_div_original)
   
library(cowplot)
interaction_plots <- plot_grid(plotlist = list(inter[["fg_fruit:empirical"]],inter[["fg_meat:empirical"]], inter[["fg_milk:empirical"]], inter[["fg_oils:empirical"]], inter[["fg_egg:empirical"]], inter[["fg_grain:empirical"]], inter[["fg_sweets:empirical"]], inter[["fg_legume:empirical"]], inter[["fg_veggie:empirical"]] ),
                              nrow = 3)
ggsave('../data/173_interaction_diversity_conditional.pdf', width = 10, height = 8)
```

```{r}
# the below is their default plot by brms
g_sweets <- plot(conditional_effects(model_div_original, effects = 'fg_sweets:empirical', surface = T, resolution = 10000),
     points = F, plot = F)[[1]] + 
  scale_fill_manual(values = c('darkgray','maroon')) +
  scale_colour_manual(values = c('darkgray','maroon')) +
  ylim(0, 3) +
  labs(y = 'Predicted log(diversity)') +
  theme_classic() +
  theme(aspect.ratio = 1, legend.position = 'none')

vars <- tibble(var = names(dat)) %>% filter(str_detect(var, '\\:'))
```

```{r}
dat_conditional <- conditional_effects(model_div_original, surface = T)

condi_dat <- dat_conditional %>% 
  keep(.p = str_detect(names(.), ':')) %>% 
  bind_rows(.id = 'grp')     

condi_dat %>% write_csv('../data/173_conditional_data.csv')
```


```{r}
dat9 %>% 
  ggplot(aes(x = effect1__ )) +
  geom_smooth(data = dat9,
              aes(y = estimate__, ymin = lower__, ymax = upper__, fill = effect2__, color = effect2__),
              stat = "identity",
              alpha = 1/4, linewidth = 1/2)+ 
   geom_point(data = META ,
             aes(x = fg_sweets, y = log(simpson_reciprocal), color = empirical),
             size = 2/3) +
  scale_fill_manual(values = c('darkgray','maroon')) +
  scale_colour_manual(values = c('darkgray','maroon')) +
  scale_x_sqrt() +
  scale_y_sqrt() +
  ylim(0, 3) +
  labs(y = 'Predicted log(diversity)') +
  theme_classic() +
  theme(aspect.ratio = 1, legend.position = 'none')

```


```{r}
gplots <- vars %>% 
  pull(var) %>% 
  set_names(vars %>% 
  pull(var)) %>% 
  map(function(var_){
    plot(conditional_effects(model_div_original, effects = var_),
     points = F, plot = F)[[1]] + 
      scale_fill_manual(values = c('darkgray','maroon')) +
      scale_colour_manual(values = c('darkgray','maroon')) +
      ylim(0, 3.5) +
      labs(y = 'Predicted log(diversity)') +
      theme_classic() +
      theme(aspect.ratio = 1, legend.position = 'none')
  })
interaction_plots <- plot_grid(plotlist =  gplots,
                              nrow = 3)
ggsave('../data/173_interaction_diversity_conditional_2.pdf', width = 10, height = 8)
```




# prior predictive check  

```{r}
div_priors_smaller <- c(# for the food group variables
            prior(normal(0, 0.1), class = 'b', coef = "fg_egg"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_grain"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_legume"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_meat"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_milk"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_oils"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_veggie"),
            # interaction terms
            prior(normal(0, 0.1), class = 'b', coef = "fg_egg_e"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_fruit_e"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_grain_e"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_legume_e"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_meat_e"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_milk_e"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_oils_e"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_sweets_e"),
            prior(normal(0, 0.1), class = 'b', coef = "fg_veggie_e"),
            # for the TPN
            prior(normal(0, 0.1), class = 'b', coef = "TPN"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "EN"),
            # for the empirical
            prior(normal(0, 0.5), class = 'b', coef = "abx"),
            # for the intensity
            prior(normal( 2, .1), class = 'b', coef = "intensityablative"),
            prior(normal( 2, .1), class = 'b', coef = "intensityreduced"),
            prior(normal( 2, .1), class = 'b', coef = "intensitynonablative")
            )

fitPrior <- brm(div_model, data=meta, 
                family = 'gaussian',
                prior=div_priors_smaller, 
           sample_prior = "only")
# the below is the posterior predictive check 
prior_c <- pp_check(fitPrior, type = "scatter_avg", ndraws = 100)$data
```


```{r}
set.seed(123)
prior_pred <- pp_check(fitPrior, type = "boxplot", nreps = 10, notch = FALSE, alpha = 0) +
  labs(y = 'log(microbiome alpha diversity)') +
   scale_color_discrete(labels=c('observed distribution', 'simulated from prior predictive distribution')) +
  theme(legend.position = 'bottom', legend.title = element_blank())
  
prior_pred 
```

# for the S3
# posterior predictive check 

```{r}
fit <- brm(div_model, data=meta, 
                prior=div_priors, 
           sample_prior = "no")

post_pred <- pp_check(fit, type = "boxplot", nreps = 10, notch = FALSE, alpha = 0)+
  labs(y = 'log(microbiome alpha diversity)') +
   scale_color_discrete(labels=c('observed distribution', 'simulated from posterior predictive distribution')) +
  theme(legend.position = 'bottom', legend.title = element_blank())
post_pred 


# the below is the posterior predictive check 
post_c <- pp_check(fit, type = "scatter_avg", ndraws = 100)$data

panels(fit)

#pp_check(fit) 
```

```{r}
# to see the pearson correlation of that 
post_c %>% 
  ggscatter(x = 'y_obs', y = 'value',
           add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "pearson",  label.sep = "\n"))
# I think it's a good fit from the posterior !
```


```{r}
fg_pt <- read_rds('../data/176_fg_intensity.rds')

S3 <- ggarrange(post_pred, fg_pt,
          labels = c("A", "B"), align = "v",
          label.y = 1,
          ncol = 1, nrow = 2)
 
title <- ggdraw() + 
  draw_label(
    "Fig. S3",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 7)
  )

combined <- plot_grid(
  title, S3,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
) +theme(plot.margin = unit(c(2,3,6,3), "cm"))

ggsave('../data/S3_postp_check_and_intensity_173.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', 
      #plot = combined, 
      dpi = 300)
```