---
title: "New interaction model results"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(cowplot)
library(tidybayes)
axis_text_size <- 10
axis_title_size <- 10
```

# fg panel

```{r}
macro <- read_csv('../data/090_model_alpha_macro_fat_post_interaction.csv')
fg <- read_csv('../data/171_div_model_fg_post_interaction.csv')

fg_order <- c( 'Vegetables','abx * Vegetables',
                 'Oils','abx * Oils',
                 'Fruits','abx * Fruits',
                 'Meats','abx * Meats',
                 'Legumes','abx * Legumes',
                 'Eggs','abx * Eggs',
                 'Milk','abx * Milk',
                 'Grains','abx * Grains',
                 'Sweets','abx * Sweets',
                 "TPN" ,"EN" , 'abx')

key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')

fg_label <- tibble(ord = fg_order) %>% 
  mutate(shortname = str_replace(ord, 'abx \\+ ','')) %>% 
  left_join(key %>% select(shortname, color)) %>% 
  mutate(color = if_else(is.na(color), 'black', color))


# to clean the y labels in both of the df
cleaned_fg <- fg  %>% select(starts_with('b_')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item = str_replace(item, 'b_fg_',''),
         item = str_replace(item, 'b_',''),
         item = str_replace(item, 'intensity','')) %>% 
   mutate(fgrp1 = case_when(
    item ==  'milk' ~ '1',
    item == 'meat' ~ '2',
    item ==  'egg' ~ '3',
    item ==  'legume' ~ '4',
    item == 'grain' ~ '5',
    item == 'fruit' ~ '6',
    item == 'veggie' ~ '7',
    item ==  'oils' ~ '8', 
    item ==  'sweets' ~ '9'
  ))  %>% 
  left_join(key %>% select(fgrp1, color, shortname)) %>% 
  mutate(shortname = case_when(
        item ==  'milk_e' ~ 'abx * Milk',
    item == 'meat_e' ~ 'abx * Meats',
    item ==  'egg_e' ~ 'abx * Eggs',
    item ==  'legume_e' ~ 'abx * Legumes',
    item == 'grain_e' ~ 'abx * Grains',
    item == 'fruit_e' ~ 'abx * Fruits',
    item == 'veggie_e' ~ 'abx * Vegetables',
    item ==  'oils_e' ~ 'abx * Oils', 
    item ==  'sweets_e' ~ 'abx * Sweets',
    item ==  'nonablative' ~ 'Nonablative',
    item ==  'reduced' ~ 'Reduced',
    item ==  'ablative' ~ 'Ablative',
    item ==  'TPN' ~ 'TPN',
    item ==  'EN' ~ 'EN',
    item ==  'abx' ~ 'abx',
    TRUE ~ `shortname`
  )) %>% 
  mutate(grp = if_else(item %in% c('nonablative','reduced','ablative'), 'patient', 'temporal'))

```

```{r}
# I need to create a data frame that has the coordinates of the rectangles that I wanna create
interaction_terms <- tibble(
  shortname = fg_label$ord
) %>% 
  mutate(ymin = seq(1, nrow(.)) - 0.5,
         ymax = seq(1, nrow(.)) + 0.5) %>% 
  filter(str_detect(shortname, '\\*')) %>% 
  mutate(xmin = -Inf, xmax = Inf)

cross0 <- cleaned_fg %>%
   filter(grp == 'temporal') %>% 
  group_by(item) %>% 
  summarise(q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975)) %>% 
  mutate(Cross = if_else(q2.5 >= 0 | q97.5 <= 0, F, T))

fg_temporal <- cleaned_fg %>% 
  filter(grp == 'temporal') %>% 
  mutate(shortname = factor(shortname, levels = fg_label$ord)) %>% 
  left_join(cross0) %>% 
  ggplot() +
  stat_pointinterval(aes(x = coeff, y = shortname, col = Cross), .width = c(.66, .95), fatten_point = 1.2) +
  geom_rect(data = interaction_terms, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = 'blue', alpha = .002)) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  labs(x = 'ln(diversity) change', y = '') +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_manual(values = c("#EC0000", "black")) +
  scale_fill_manual(values = c("azure")) +
  theme(axis.text = element_text( size = 10),panel.background = element_rect(fill = "#d8dcec",colour = "#d8dcec",size = 0.5, linetype = "solid"),
        axis.title=element_text(size=10), 
        aspect.ratio=1.5)     
fg_temporal
```

```{r} 
# the fg  patient
fg_pt <- cleaned_fg %>% 
  filter(grp == 'patient') %>% 
  mutate(shortname = factor(shortname, levels = c('Nonablative','Reduced','Ablative'))) %>% 
  ggplot(aes(x = coeff, y = shortname)) +
  stat_pointinterval(.width = c(.66, .95), fatten_point = 1.2) +
  labs(x = 'ln(diversity) change', y = '') +
   xlim(0.9, 3) +
  theme_classic() +
  theme(legend.position = 'none') +
  theme(axis.text = element_text( size = 10),
         panel.background = element_rect(fill = "#d0cccc",colour = "#d0cccc",size = 0.5, linetype = "solid"),axis.title=element_text(size=10), 
        aspect.ratio=1/3.1)    

fg_pt %>% write_rds('../data/176_fg_intensity.rds')

# assemble the ones for the fg
fg_side <-  plot_grid(fg_temporal,NA,
                rel_heights = c(3,.1),align = 'vh',axis = 'lrtb',
                 nrow = 2)
fg_side
```

# macro panel

```{r}
# order the macro panel

cleaned_macro <-  macro %>% select(starts_with('b_')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item = str_replace(item, 'b_ave_',''),
         item = str_replace(item, 'b_',''),
         item = str_replace(item, 'intensity','')) %>% 
  mutate(shortname = case_when(
        item ==  'fiber_e' ~ 'abx * Fiber',  
    item == 'fiber' ~ 'Fiber',
    item ==  'fat_e' ~ 'abx * Fat',
    item ==  'fat' ~ 'Fat',
    item == 'Sugars_e' ~ 'abx * Sugars',
    item == 'Sugars' ~ 'Sugars',
    item ==  'nonablative' ~ 'Nonablative',
    item ==  'reduced' ~ 'Reduced',
    item ==  'ablative' ~ 'Ablative',
    item ==  'TPN' ~ 'TPN',
    item ==  'EN' ~ 'EN',
    item ==  'abx' ~ 'abx'
  )) %>% 
  mutate(grp = if_else(item %in% c('nonablative','reduced','ablative'), 'patient', 'temporal')) %>% 
  mutate(grp = factor(grp, levels = c('temporal','patient')))

cleaned_macro %>% distinct(item) %>% pull(item)
# sort them by the order of the left side of middle q66
macro_e_order <- cleaned_macro %>% filter(str_detect(item, '_e$')) %>% 
  group_by(shortname) %>% 
  tidybayes::median_qi(coeff , .width = c( .66)) %>% 
  arrange(.lower) %>% pull(shortname)

cross0_macro <- cleaned_macro %>%
   filter(grp == 'temporal') %>% 
  group_by(item) %>% 
  summarise(q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975)) %>% 
  mutate(Cross = if_else(q2.5 >= 0 | q97.5 <= 0, F, T))


macro_order <- tibble(
  shortname = c('Fat','abx * Fat',
                 'Fiber','abx * Fiber',
                 'Sugars','abx * Sugars',
                 "TPN" ,"EN" , 'abx')
) %>% inner_join(cleaned_macro %>% distinct(item, shortname)) %>% 
  inner_join(cross0_macro %>% select(item, Cross))

```
 

 
 
```{r}
interaction_terms_macro <- tibble(
  shortname = macro_order$shortname
) %>% 
  mutate(ymin = seq(1, nrow(.)) - 0.5,
         ymax = seq(1, nrow(.)) + 0.5) %>% 
  filter(str_detect(shortname, '\\*')) %>% 
  mutate(xmin = -Inf, xmax = Inf)

macro_temporal <- cleaned_macro %>% 
  filter(grp == 'temporal') %>% 
  mutate(shortname = factor(shortname, levels = macro_order$shortname)) %>% 
  left_join(cross0_macro)  %>% 
  ggplot() +
  stat_pointinterval(aes(x = coeff, y = shortname, col = Cross),.width = c(.66, .95), fatten_point = 1.2) +
  geom_rect(data = interaction_terms_macro, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = 'blue', alpha = .002)) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  labs(x = 'ln(diversity) change', y = '') +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_manual(values = c("#EC0000", "black")) +
  scale_fill_manual(values = c("azure")) +
  theme(axis.text.y = element_text( size = 10),
        axis.title=element_text(size=10), panel.background = element_rect(fill = "#d8dcec",colour = "#d8dcec",size = 0.5, linetype = "solid"),
        aspect.ratio=1/1.5)
macro_temporal
```


```{r}
macro_pt <- cleaned_macro %>% 
  filter(grp == 'patient') %>% 
  mutate(shortname = factor(shortname, levels = c('Nonablative','Reduced','Ablative'))) %>% 
  ggplot(aes(x = coeff, y = shortname)) +
  stat_pointinterval(.width = c(.66, .95), fatten_point = 1.2) +
  labs(x = 'Patient intercept', y = '') +
   xlim(1.5, 2.5) +
  theme_classic() +
  theme(legend.position = 'none') +
  theme(axis.text = element_text( size = 10),
          panel.background = element_rect(fill = "#d0cccc",colour = "#d0cccc",size = 0.5, linetype = "solid"),
        axis.title=element_text(size=10), 
        aspect.ratio=1/2.5)

macro_side <-  plot_grid(macro_pt,NA, macro_temporal,
                rel_heights = c(1,-.8, 1.9),align = 'hv',axis = 'lrtb',
                labels = c('C',NA, 'D'),label_y = .7,
                 ncol = 1 )
macro_side   
```
# the top part of the F2

```{r}
twoscore <- read_csv('../data/086_twoscore_procrustes.csv') 

f2a <- twoscore %>%  
  mutate(pNd = str_extract(pNd, '\\d')) %>% 
  arrange(desc(grp)) %>% 
  mutate(pNd =  factor(pNd)) %>% 
  ggplot(aes(x = pNd, y = score, group = grp, linetype = grp)) +
  geom_line(size = 0.3) +
  geom_point(size = 1.3) +
  labs(x = 'Number of previous days\nof dietary intake',y = 'Procrustes score') +
  scale_linetype_manual(values = c('solid','dashed')) +
  theme_classic()  +
  theme(aspect.ratio=1/2,
        legend.position = c(0.75,0.4),
        axis.text=element_text(size=axis_text_size), 
        axis.title=element_text(size=axis_text_size),
        legend.title = element_blank(), 
        axis.text.x = element_text(angle=0, hjust=0.5)) 
f2a
```


```{r}
p <- '../data/cartoon_of_model.png'
diagram <- ggdraw() +
  draw_image(magick::image_read(p),   scale =.9 ,hjust = -.05) 
diagram
```


```{r}

```


# assemble all parts of F2

```{r}
title <- ggdraw() + 
  draw_label(
    "Fig 2",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 7)
  )

left <- plot_grid(f2a, NA, macro_side,
                  labels = c('A', NA, NA),label_y = 1,
                rel_heights = c(1,-.35, 3.2),
                  ncol = 1) 

right <- plot_grid(diagram,NA, fg_side,
                labels = c('B',NA, 'E'),label_y = .8,
                rel_heights = c(1,-.6,5),
                  ncol = 1)

f2 <-  plot_grid(left,right,
                rel_widths = c(1,1.2),
                 nrow = 1)

combined <- plot_grid(
  title, f2,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
) +theme(plot.margin = unit(c(1,2,1,1), "cm"))

ggsave('../data/F2_model_results_176.pdf',
      width = 210, height = 197, units = "mm", device = 'pdf', 
      #plot = combined, 
      dpi = 300)
```

```{r}
# combine the three intercepts together 
intensity_supp <-  plot_grid(fg_pt,entero_pt,
                             labels = c('A','B'),
                 nrow = 2)

title <- ggdraw() + 
  draw_label(
    "Fig S4",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme( plot.margin = margin(0, 0, 0, 7))
 
combined <- plot_grid(
  title, intensity_supp,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
) +theme(plot.margin = unit(c(2,5,10,3), "cm"))

ggsave('../data/S4_intensity_intercept_176.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', 
      #plot = combined, 
      dpi = 300)
```

 