---
title: "New F3"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(scales)
library(tidybayes)
library(cowplot)
theme_set(theme_pubr(base_size = 8))
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')
```

# prep the df for the volcano plot

```{r}
# correlate top genus abundance with diversity, check if entero and kleb have most negative correlation
set.seed(1)
meta <- read_csv('../data/153_combined_META.csv')
g_relab <- read_csv('../data/022_ALL173_stool_samples_genus_counts.csv') %>% 
  filter(!is.na(genus)) %>% 
  spread('genus','relab', fill = 0) %>% 
  gather('genus','relab', names(.)[2]:names(.)[ncol(.)]) %>% 
  inner_join(meta %>% select(sampleid, simpson_reciprocal)) %>% 
  mutate(pseudotiny = runif(nrow(.), min = 0, max = 10^-10) ) %>% 
  mutate(changed_relab = relab + pseudotiny)

# just calculate the spearman correlation and p value
spearman_res <- g_relab %>% 
  split(.$genus) %>% 
  imap_dfr(function(.x, .y ){
    # the spearman correlation 
      spearman_cor = cor.test(.x$simpson_reciprocal, .x$changed_relab, method = c( "spearman"), exact = T)
      return(list(genus = .y, rho = spearman_cor$estimate, pval = spearman_cor$p.value))
  } ) 

# the smallest nonzero p value 
pvals <- spearman_res %>% 
  filter(pval > 0) 
tinypseudo <- min(pvals$pval)/10

# show the % of the samples that have the relab of the genus > 10^-4
perc_thre <- g_relab %>% 
  count(genus, relab > 10^-4) %>% 
  filter(`relab > 10^-4` == 'TRUE') %>% 
  mutate(passthre_perc = round(n/1009*100, 0))

spearman_all <- spearman_res %>% 
  left_join(perc_thre) %>% 
  mutate(n = ifelse(is.na(n), 0, n),
         passthre_perc = ifelse(is.na(passthre_perc), 0, passthre_perc)) %>% 
    filter(passthre_perc > 10) %>% 
  mutate(changed_pval = if_else(pval == 0, pval + tinypseudo, pval)) %>% 
  mutate(padj = p.adjust(changed_pval, method = 'BH'),
         neglogp = -log10(padj)) %>% 
  mutate(sig05 = if_else(padj < 0.05, 'FDR < 0.05', 'FDR >= 0.05')) %>% 
  mutate(Correlation = if_else(rho >= 0, 'higher diversity', 'lower diversity')) %>% 
  arrange(rho, desc(genus)) 


spearman_all %>% write_csv('../data/172_spearman_all.csv')
```

```{r}
res <- read_csv('../data/172_spearman_all.csv') %>% 
  mutate(Correlation = factor(Correlation, levels = c('lower diversity','higher diversity')))

# make a panel with only top 5 significant ones in either direction for the main figure 3
main <- res %>% 
  filter(sig05 == 'FDR < 0.05') %>% 
  split(.$Correlation) %>% 
  map(function(df){
    df %>% mutate(absrho = abs(rho)) %>% slice_max(order_by =absrho, n = 5 )
  }) %>% bind_rows()

correbar <- main %>% 
  ggbarplot(x = 'genus', y = 'rho', orientation = c( "horizontal"),
            sort.val = "desc",   fill = "Correlation",  color = "white",    palette = "jco",     sort.by.groups = F,     ylab = "Spearman correlation",    xlab = '') +
  theme(legend.position = c(.8,.8),axis.text=element_text(size=10),axis.title=element_text(size=10),legend.text  = element_text(size=8), legend.title = element_text(size = 8), 
         aspect.ratio=1/1.3) +
  guides(fill = guide_legend(title = "Correlated with"))
```

```{r}
# make a panel with all the sig ones for the supplementary
correbar_all <- res %>% 
  filter(sig05 == 'FDR < 0.05') %>% 
  ggbarplot(x = 'genus', y = 'rho', orientation = c( "horizontal"),
            sort.val = "desc",   fill = "Correlation",  color = "white",    palette = "jco",     sort.by.groups = F,     ylab = "Spearman correlation",    xlab = '') +
  theme(legend.position = c(.8,.8),axis.text=element_text(size=10),axis.title=element_text(size=10),legend.text  = element_text(size=8), legend.title = element_text(size = 8), 
         aspect.ratio=1.8) +
  guides(fill = guide_legend(title = "Correlated with"))


title <- ggdraw() + 
  draw_label(
    "Fig. S7",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 7)
  )
 
combined <- plot_grid(
  title, correbar_all,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)+theme(plot.margin = unit(c(1,1,1,1), "cm"))

ggsave('../data/S7_genus_diversity_correlation_178.pdf',
      width = 210, height = 290, units = "mm", device = 'pdf', plot = combined, dpi = 300)
```

# the Enterococcus results

```{r}
entero <- read_csv('../data/171_entero_model_fg_post_interaction.csv')  %>% 
  select(starts_with('b_')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item = str_replace(item, 'b_fg_',''),
         item = str_replace(item, 'b_',''),
         item = str_replace(item, 'intensity','')) %>% 
   mutate(fgrp1 = case_when(
    item ==  'milk' ~ '1',
    item == 'meat' ~ '2',
    item ==  'egg' ~ '3',
    item ==  'legume' ~ '4',
    item == 'grain' ~ '5',
    item == 'fruit' ~ '6',
    item == 'veggie' ~ '7',
    item ==  'oils' ~ '8', 
    item ==  'sweets' ~ '9'
  ))  %>% 
  left_join(key %>% select(fgrp1, color, shortname)) %>% 
  mutate(shortname = case_when(
        item ==  'milk_e' ~ 'abx + Milk',
    item == 'meat_e' ~ 'abx + Meats',
    item ==  'egg_e' ~ 'abx + Eggs',
    item ==  'legume_e' ~ 'abx + Legumes',
    item == 'grain_e' ~ 'abx + Grains',
    item == 'fruit_e' ~ 'abx + Fruits',
    item == 'veggie_e' ~ 'abx + Vegetables',
    item ==  'oils_e' ~ 'abx + Oils', 
    item ==  'sweets_e' ~ 'abx + Sweets',
    item ==  'nonablative' ~ 'Nonablative',
    item ==  'reduced' ~ 'Reduced',
    item ==  'ablative' ~ 'Ablative',
    item ==  'TPN' ~ 'TPN',
    item ==  'EN' ~ 'EN',
    item ==  'abx' ~ 'abx',
    TRUE ~ `shortname`
  )) %>% 
  filter(! shortname %in% c('Nonablative','Reduced','Ablative'))

entero %>% 
  distinct(shortname) %>% pull(shortname)
entero %>% 
  distinct(item) %>% pull(item)
```

```{r}
# deciding on how to order these terms 
# find the q25 of the coeffs
fg_order <- entero %>% filter(str_detect(item, '_e$')) %>% 
  group_by(shortname) %>% 
  tidybayes::median_qi(coeff , .width = c( .66)) %>% 
  arrange(.lower) %>% pull(shortname)
```

```{r}
total_order <- c('Vegetables','abx + Vegetables',
                 'Oils','abx + Oils',
                 'Fruits','abx + Fruits',
                 'Meats','abx + Meats',
                 'Legumes','abx + Legumes',
                 'Eggs','abx + Eggs',
                 'Milk','abx + Milk',
                 'Grains','abx + Grains',
                 'Sweets','abx + Sweets',
                 "TPN" ,"EN" , 'abx')
#tibble(ord = total_order) %>% write_csv('../data/178_coeff_order.csv')
arrange_label <- tibble(ord = total_order) %>% 
  mutate(shortname = str_replace(ord, 'abx \\+ ','')) %>% 
  left_join(key %>% select(shortname, color)) %>% 
  mutate(color = if_else(is.na(color), 'black', color))

```

```{r}
# color the most positive one with red: the abx + sweets        
mostpos <- entero %>%   
  group_by(shortname) %>% 
  count(coeff > 0) %>% 
  ungroup %>% 
  filter(`coeff > 0` == 'TRUE') %>% 
  arrange(desc(n)) %>% 
  top_n(1) %>% 
  pull(shortname)
mostpos

```

```{r}
entero_df <- entero %>% 
  mutate(mark = if_else(shortname %in% mostpos, 'mostpos','others')) %>% 
  mutate(shortname = factor(shortname, levels = total_order))

```

```{r}
entero_panel <- entero_df %>%   
  ggplot(aes(x = coeff, y = shortname, col = mark)) +
  stat_pointinterval(.width = c(.66, .95)) +
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  labs(x = 'CLR(Enterococcus) change', y = '') +
  annotate("text", x = 2, y = 18, label = "97.3% > 0", col = 'coral1') + 
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_manual(values = c("coral1", "black")) +
  theme(axis.text.y = element_text( size = 10),
        axis.title=element_text(size=10),panel.background = element_rect(fill = "#d8dcec",colour = "#d8dcec",size = 0.5, linetype = "solid"), aspect.ratio=1.3 )

entero_panel 
ggsave('../data/178_entero_panel.pdf', width = 4.5, height = 4.5, plot = entero_panel)
```

# the mouse experiment

```{r}
# clean the data  
new <- readxl::read_excel('../data/Sucrose Experiment_July2023.xlsx')  %>% 
  mutate(Log_CFUs_per_GramStool = (((((Colonies_counted*(100/Plated_volume_ul))/100)/(10^Dilution_factor) )*1000)/Stool_weight_mg)+1 ) %>%  
  filter(Day != 1) %>% 
  mutate(Day = factor(Day)) %>% 
  separate(Treatment, into = c('diet_treatment','abx_treatment'), sep = ', ', remove = T) %>% 
  mutate(diet_treatment = if_else(diet_treatment == 'Plain Hydrogel','vehicle','sucrose'),
         abx_treatment = if_else(str_detect(abx_treatment, 'Bia'),'biapenem',abx_treatment),
         diet_treatment = factor(diet_treatment, levels = c('vehicle','sucrose')),
         abx_treatment = factor(abx_treatment, levels = c('PBS','biapenem')))
new %>% count(abx_treatment)
```

```{r combined_data}
newest <- readxl::read_excel('../data/Sucrose_All Experiments Consolidated .xlsx') %>% 
  mutate(Log_CFUs_per_GramStool = (((((Colonies_counted*(100/Plated_volume_ul))/100)/(10^Dilution_factor) )*1000)/Stool_weight_mg)+1 ) %>%   
  filter(Day != 1) %>% 
  separate(Treatment, into = c('diet_treatment','abx_treatment'), sep = ', ', remove = T) %>% 
  mutate(diet_treatment = if_else(diet_treatment == 'Vehicle','vehicle','sucrose'),
         abx_treatment = if_else(str_detect(abx_treatment, 'Bia'),'biapenem',abx_treatment),
         diet_treatment = factor(diet_treatment, levels = c('vehicle','sucrose')),
         abx_treatment = factor(abx_treatment, levels = c('PBS','biapenem'))) %>% 
  select(diet_treatment:Mouse_identifier, Log_CFUs_per_GramStool)
```
```{r}
# the difference or fold change between day 0 and day 3, day 0 and day 6
deltas <- newest %>% 
  spread('Day','Log_CFUs_per_GramStool') %>% 
  rename(d0 = `0`, d3 = `3`,d6 = `6`) %>% 
  mutate(d30_diff = d3 - d0,
         d60_diff = d6 - d0,
         d30_fc = d3 / d0,
         d60_fc = d6 / d0)

# the plotting with the difference
p_diff <- deltas %>% 
  select(diet_treatment:Mouse_identifier, d30_diff, d60_diff) %>% 
  gather('grp','diffvalue', d30_diff:d60_diff) %>% 
  arrange(abx_treatment,diet_treatment,  grp) %>% 
  mutate(xvar = str_glue('{abx_treatment}__{diet_treatment}__{grp}')) 

p_diff %>% 
   count(xvar)

p_diff %>% 
  ggboxplot(x = 'xvar', y = 'diffvalue',add = 'jitter', 
             xlab = '', ylab = 'difference',
            width = 0.6,color  = 'grp')+
   scale_color_manual(values = c('#ffbcdc','deeppink2')) +
  stat_compare_means(comparisons= list(c('biapenem__sucrose__d30_diff', 'biapenem__vehicle__d30_diff'),
                                       c('biapenem__sucrose__d30_diff', 'PBS__sucrose__d30_diff'),
                                       c('biapenem__sucrose__d30_diff', 'PBS__vehicle__d30_diff'),
                                     
                                    c('biapenem__sucrose__d60_diff', 'biapenem__vehicle__d60_diff'),
                                       c('biapenem__sucrose__d60_diff', 'PBS__sucrose__d60_diff'),
                                       c('biapenem__sucrose__d60_diff', 'PBS__vehicle__d60_diff') ),
            label= "p.signif", method= 'wilcox.test',tip.length = 0.04,exact=T,correct=T) +
  scale_y_log10(breaks = c(1 %o% 10^(-1:12)), labels = trans_format("log10", math_format(10^.x))) +
  theme(axis.text.x = element_text(angle = 90),axis.ticks.x=element_blank(),
        axis.text =  element_text(size = 10),legend.position = 'none',aspect.ratio=1/1.3)

ggsave('../data/178_mouse_difference.pdf', height = 10)
```

```{r}
# if I plot in fold change
p_fc <- deltas %>% 
  select(diet_treatment:Mouse_identifier, d30_fc, d60_fc) %>% 
  gather('grp','fcvalue', d30_fc:d60_fc) %>% 
  arrange(abx_treatment,diet_treatment,  grp) %>% 
  mutate(xvar = str_glue('{abx_treatment}__{diet_treatment}__{grp}')) %>% 
  mutate(log10FC = log10(fcvalue))

p_fc %>% 
   count(xvar)

p_fc %>% 
  ggboxplot(x = 'xvar', y = 'log10FC',add = 'jitter', 
             xlab = '', ylab = 'log10FC',
            width = 0.6,color  = 'grp') +
   scale_color_manual(values = c('#ffbcdc','deeppink2')) +
  stat_compare_means(comparisons= list(c('biapenem__sucrose__d30_fc', 'biapenem__vehicle__d30_fc'),
                                       c('biapenem__sucrose__d30_fc', 'PBS__sucrose__d30_fc'),
                                       c('biapenem__sucrose__d30_fc', 'PBS__vehicle__d30_fc'),
                                     
                                    c('biapenem__sucrose__d60_fc', 'biapenem__vehicle__d60_fc'),
                                       c('biapenem__sucrose__d60_fc', 'PBS__sucrose__d60_fc'),
                                       c('biapenem__sucrose__d60_fc', 'PBS__vehicle__d60_fc') ),
            label= "p.signif", method= 'wilcox.test',tip.length = 0.04,exact=T,correct=T) +
  scale_y_continuous(breaks=seq(0, 15, 1)) + 
  theme(axis.text.x = element_text(angle = 90),axis.ticks.x=element_blank(),
        axis.text =  element_text(size = 10),legend.position = 'none',aspect.ratio=1/1.3)
```

```{r}
# to find if there is a slower drop in the abx + sucrose group
# look at the difference between the fold changes in biapenem+sucrose vs biapenem+vehicle
diff_p_fc <- p_fc %>% 
  filter(abx_treatment == 'biapenem') %>% 
  select(diet_treatment:grp, log10FC) %>% 
  spread('grp','log10FC') %>% 
  mutate(diff_2fc = d30_fc - d60_fc)

diff_p_fc %>% 
  ggboxplot(x = 'diet_treatment', y = 'diff_2fc', add = 'jitter') +
  stat_compare_means(comparisons= list(c('vehicle', 'sucrose') ),
            label= "p.signif", method= 'wilcox.test',tip.length = 0.04,exact=T,correct=T)
```


```{r}
# maybe I can plot in a different way 
plotdf <- newest %>% 
  mutate(Day = factor(Day)) %>% 
  arrange(abx_treatment,diet_treatment,  Day) %>% 
  mutate(xvar = str_glue('{abx_treatment}__{diet_treatment}__{Day}'))

plotdf %>% 
  filter(str_detect(xvar, '3$')) %>% count(xvar)
```

```{r}
f3_mouse <- plotdf %>% 
  ggboxplot(x = 'xvar', y = 'Log_CFUs_per_GramStool',add = 'jitter', 
             xlab = '', ylab = 'Enterococcal\nLog10 CFU/gram',
            width = 0.6,color  = 'Day')+
   scale_color_manual(values = c('gray','#ffbcdc','deeppink2')) +
  stat_compare_means(comparisons= list(c('biapenem__sucrose__3', 'biapenem__vehicle__3'),
                                       c('biapenem__sucrose__3', 'PBS__sucrose__3'),
                                       c('biapenem__sucrose__3', 'PBS__vehicle__3'),
                                     
                                       c('biapenem__sucrose__6', 'biapenem__vehicle__6'),
                                       c('biapenem__sucrose__6', 'PBS__sucrose__6'),
                                       c('biapenem__sucrose__6', 'PBS__vehicle__6') ),
            label= "p.signif", method= 'wilcox.test',tip.length = 0.04,exact=T,correct=T) +
  scale_y_log10(breaks = c(1 %o% 10^(-1:12)), 
                labels = trans_format("log10", math_format(10^.x))) +
  theme(axis.text.x = element_blank(),axis.ticks.x=element_blank(),
        axis.text =  element_text(size = 10),legend.position = 'none',aspect.ratio=1/1.3)
  


# assemble
title <- ggdraw() + 
  draw_label(
    "Fig 3",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 5)
  )


f3 <- plot_grid(correbar, entero_panel,f3_mouse, label_size = 12, ncol = 1,labels = c('A','B','C'),
                align = 'vh', axis = 'lrtb', rel_heights = c(1,1.55,1))

 
combined <- plot_grid(
  title, f3,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.05, 1)
)+theme(plot.margin = unit(c(1,7,1,1), "cm"))

ggsave('../data/F3_current_178.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', plot = combined, dpi = 300)

```

# the vardi test to see the change over time whether it is significant 

```{r}
# to plot the abx group data with lines concecting each mouse 
abxgrp <- newest %>% 
  filter(abx_treatment == 'biapenem')
 
abxgrp %>% 
  ggboxplot(x = 'Day', y = 'Log_CFUs_per_GramStool',
            xlab = '', ylab = 'CFUs/gram of stool, Log10 Scale',
            add.params = list(size = 2, color = 'Mouse_identifier', alpha = 0.5, shape = 16),
            title = 'abx group') +
   geom_line(aes(group = Mouse_identifier, color = Mouse_identifier), alpha = 1, size = 1.5) +
  scale_y_log10(breaks = c(1 %o% 10^(-1:12)), labels = trans_format("log10", math_format(10^.x))) +
  facet_grid( ~ diet_treatment) +
  #stat_compare_means(aes(label = after_stat(p.signif)),ref.group = "sucrose_biapenem", method= 'wilcox.test')  +
   theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=.5))

ggsave('../data/178_abx_mouse_line_connected.pdf', width = 10, height = 7)
```



```{r vardi}

newest <- read_csv('../data/178_mouse_data.csv') 
abxgrp <- newest %>% 
  filter(abx_treatment == 'biapenem')


library(clinfun)  
# actually two groups in the abx grp

vardidf <- abxgrp %>% 
  select(diet_treatment:Mouse_identifier, Log_CFUs_per_GramStool) %>% 
  mutate(grp = str_glue('{abx_treatment}__{diet_treatment}')) %>% 
  select(-diet_treatment, -abx_treatment) %>% 
  spread('Day','Log_CFUs_per_GramStool') 
#vardidf %>% count(diet_treatment, abx_treatment, Mouse_identifier)
vardidf
vardicts <- vardidf %>% 
  select(-Mouse_identifier, -grp) %>% as.matrix()

vardigrp <- vardidf$grp
  
# Make pairwise comparisons between all the groups
combos.to.test <-  data.frame(combn(unique(vardigrp),2))
combos.to.test[] <- lapply(combos.to.test, as.character)
stats.results <- plyr::ldply(combos.to.test, function(x) {
  # x <- combos.to.test[[1]]
  paste(x)
  u <- aucVardiTest(vardicts, vardigrp, cgrps=x) 
  u$p.value
  return(data.frame(Grp.Vs = x[1],
                    Gr = x[2],
                    p.value = round(u$p.value, 3)))
}) 


#set thresholds for what asterisks mean
stats.results$.id <- NULL
p.value.star <- 0.05      
p.value.double <- 0.01

stats.results$sig[stats.results$p.value > p.value.star] <- " "
stats.results$sig[stats.results$p.value <= p.value.star] <- "*"
stats.results$sig[stats.results$p.value <= p.value.double] <- "**"
print(stats.results, row.names = F)
#newest %>% write_csv('../data/178_mouse_data.csv')
```  

```{r}
# repeat the vardi test for only day 0 and 6 data
d6 <-  abxgrp %>% 
  select(diet_treatment:Mouse_identifier, Log_CFUs_per_GramStool) %>% 
  filter(Day != '3') %>% 
  mutate(grp = str_glue('{abx_treatment}__{diet_treatment}')) %>% 
  select(-diet_treatment, -abx_treatment) %>% 
  spread('Day','Log_CFUs_per_GramStool') 


cts <- d6 %>% 
  select(-Mouse_identifier, -grp) %>% as.matrix()

grp <- d6$grp
  
# Make pairwise comparisons between all the groups
combos.to.test <-  data.frame(combn(unique(grp),2))
combos.to.test[] <- lapply(combos.to.test, as.character)
stats.results <- plyr::ldply(combos.to.test, function(x) {
  # x <- combos.to.test[[1]]
  paste(x)
  u <- aucVardiTest(cts, grp, cgrps=x) 
  u$p.value
  return(data.frame(Grp.Vs = x[1],
                    Gr = x[2],
                    p.value = round(u$p.value, 3)))
}) 


#set thresholds for what asterisks mean
stats.results$.id <- NULL
p.value.star <- 0.05      
p.value.double <- 0.01

stats.results$sig[stats.results$p.value > p.value.star] <- " "
stats.results$sig[stats.results$p.value <= p.value.star] <- "*"
stats.results$sig[stats.results$p.value <= p.value.double] <- "**"
print(stats.results, row.names = F)
```

