---
title: "make the supp for the genus heatmap"
author: "Anqi Dai"
date: '`r Sys.Date()`'
output: html_document
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)  
```

```{r}
library(tidyverse) 
library(ggpubr)
library(dendextend)
library(ggdendro)
```
 
# make a tree of those taxa genus

```{r}
# make a tree structure from the taxas

# 
# taxas <- asv_annotation_blast_ag %>% 
#   filter(genus %in% genera$genus) %>% 
#   distinct(kingdom,phylum, class, ordr, family,genus  ) %>% 
#   mutate(
#     kingdom = str_glue('k__{kingdom}'),
#     phylum = str_glue('p__{phylum}'),
#     class = str_glue('c__{class}'),
#     ordr = str_glue('o__{ordr}'),
#     family = str_glue('f__{family}'),
#     newickstring = str_glue('foodtreeroot/{kingdom}/{phylum}/{class}/{ordr}/{family}/{genus}'),
#     taxanomy = str_glue('{kingdom};{phylum};{class};{ordr};{family};{genus}'))
# 
# taxas_Tree <- as.Node(taxas, pathName = "newickstring")
# tree <- ToNewick(taxas_Tree)
# cat(tree, file = '../data/180_taxa_tree.newick')


# tree <- read.tree("../data/180_taxa_tree.newick")
# 
# treeplot <- ggtree(tree) + 
#   theme_tree() + 
#   geom_tiplab()  
#   
# get_taxa_name(treeplot)           
# 
# ggsave('../data/180_tree.pdf', width = 30, height = 20)
```

# the genus heatmap with hclust

## I need a different matrix with only the perc positive to make the dendrogram

```{r}
post_df <- read_csv('../data/171_genus_foodgroup_model_post_extra_few_interaction.csv',  col_select = c(1:25)) %>% 
  select(genus, starts_with('b_')) %>% 
  select(-starts_with('b_intensity')) %>% 
  gather('item', 'coeff', names(.)[2]:names(.)[ncol(.)])
post_df
```
 
```{r}
post_matrix <- post_df %>% 
  filter(coeff > 0) %>% 
  count(genus, item) %>% 
  mutate(posperc = n/4000) %>% 
  select(-n) %>% 
  spread('item','posperc') %>% 
  column_to_rownames('genus')

hclust_obj <- hclust(dist(post_matrix), method = "complete")
dendrogram <- as.dendrogram(hclust_obj)
dendro <- ggdendrogram(dendrogram, rotate = TRUE) 
ggsave('../data/180_dendro.pdf', width = 10, height = 10)
```




```{r}
genera <- read_csv('../data/171_post_res_genera.csv')
```


```{r}
# Load the necessary libraries
library(ggplot2)


# Create a data matrix
data <- matrix(rnorm(100), nrow = 10) %>% as.data.frame()

# Perform hierarchical clustering
hclust_obj <- hclust(dist(data), method = "complete")

# Create a dendrogram
dendrogram <- as.dendrogram(hclust_obj)

# Plot the dendrogram
dendro <- ggdendrogram(dendrogram, rotate = TRUE)

# Create a heatmap
heatmap <- ggplot(data = data, aes(x = -10:-1, y = 1:10)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "red")

# Combine the dendrogram and heatmap
final_plot <- ggarrange(heatmap, dendro, nrow = 2, ncol = 1)

# Show the plot
final_plot

```

