---
title: "correlate food group and nutrient with stool alpha diversity"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
library(tidyverse)
library(kableExtra)
library(ggpubr)  
```

```{r}
foods <- read_tsv('../data/finalized/meta_data_67.tsv') %>% 
  select(mrn, Fdrt = foodDayRT, egg_total:Sugars_perc) %>% 
  gather(key = 'type', value = 'value', egg_total:Sugars_perc)
```

## Select a subset patients cohort that each pt has at least 4 pairs(stool and previous 3 days diet

```{r}
# previous 3 days food all types average
fns_all <- list.files(str_glue('../data/finalized/paired/p3day/'), full.names = T)
  
all <- fns_all %>% 
    set_names(fns_all) %>% 
    map(~ read_csv(file = ., col_names = T, col_types = cols(.default = col_character()))) %>% 
    bind_rows() %>% 
    mutate(mrn = as.numeric(mrn))
    
subset_pts <- all %>% 
  count(mrn)  %>% 
  arrange(n) %>% 
  filter(n >= 4) %>% 
  pull(mrn)

all_p3day <- all %>% 
  filter(mrn %in% subset_pts) %>% 
  mutate(ID = str_glue('{mrn}_{sampleid}'))
```

## Get the average of the food group and the nutrients in percentage and in gram weight

```{r}
type_items <-  foods %>% 
  distinct(type) %>% 
  pull(type) 

pair_p3day_food <- apply(all_p3day, 1, function(Row){
    foods %>% 
        filter(mrn == Row[['mrn']]) %>% 
        filter(Fdrt %in% c(Row[['p1dF']], Row[['p2dF']],Row[['p3dF']])) %>% 
        group_by(type) %>% 
        summarise(ave_type = mean(value))
})

names(pair_p3day_food) <- all_p3day$ID

pair_p3day_food_res <- bind_rows(pair_p3day_food, .id = 'ID') %>% 
  separate(ID, into = c('mrn','sampleid'), sep = '_') 

```

```{r}
# output this table the stool sample are uncensored here
pair_p3day_food_res %>% 
  write_csv('../data/finalized/paired/pair_p3day_food_group_n_nutrients_res.csv')
```


## Get the stool alpha diversity from db

```{r}
# get the diversity of those stool samples
source('~/db_connect_simple.R')
connect_database(config_file = '~/dbConfig.txt')
get_table_from_database_predefined_filter('asv_alpha_diversity_ag')

pair_p3day <- pair_p3day_food_res  %>% 
  inner_join(asv_alpha_diversity_ag %>% select(sampleid, simpson_reciprocal, shannon), by = 'sampleid')   
```

## Spearman correlation and plot

```{r}
nutrients <- c('Carbohydrates','Fat','Fibers','Proteing','Sodium','Sugars')

spearman_res <- pair_p3day %>% 
  split(.$type) %>% 
  map(function(df){
    test = cor.test(df$ave_type, 
                   df$simpson_reciprocal, 
                   method = 'spearman', 
                   exact = F)
    return(list(rho = round(test$estimate, 2),
                pval = test$p.value))
  }) %>% 
  bind_rows(.id = 'ID') %>% 
  separate(ID, into = c('item','grp'), sep = '_') %>% 
  mutate(type = if_else(item %in%  nutrients, 'nutrient', 'food_group')) %>% 
  mutate(FDR = p.adjust(pval, method = 'BH')) %>% 
  mutate(neglogFDR = -log(FDR))
```


```{r}
spearman_res %>% 
  filter(type == 'nutrient') %>% 
  ggscatter(x = 'item', y = 'rho', size = 'neglogFDR', label = T, lab.size = 1,
            color = 'grp', palette = 'jama',
            title = 'Spearman cor between ave nutrient metric & stool alpha diversity') +
  theme_cleveland() 


spearman_res %>% 
  filter(type == 'food_group') %>% 
  ggscatter(x = 'item', y = 'rho', size = 'neglogFDR', label = T, lab.size = 1,
            color = 'grp', palette = 'jama',
            title = 'Spearman cor between ave food group metric & stool alpha diversity') +
  theme_cleveland()   
```

## censor samples that are exposed to the list of empiric antibiotics

```{r}
censor_abx <- c('active_atb_vanco_po',	'active_atb_imipenem',	'active_atb_meropenem',	'active_atb_ertapenem',		'active_atb_cefepime',		'active_atb_linezolid',	'active_atb_metro',	'active_atb_piptazo')

abx_all <- read_csv('../data/finalized/abx/abx_all_samples_with_censoring_info.csv')
 
abx_this_censor_samples <- abx_all %>% 
  filter(sampleid %in% pair_p3day$sampleid) %>% 
  select(sampleid, active_atb_cipro:active_atb_other) %>% 
  gather(key = 'abx_type', value = 'value', names(.)[2]:names(.)[ncol(.)]) %>% 
  filter(abx_type %in% censor_abx) %>% 
  filter(value == T) %>% 
  distinct(sampleid) %>% 
  pull(sampleid)
```

```{r}
# redo the above but remove the censored samples
spearman_res_rm <- pair_p3day %>% 
  filter(!sampleid %in% abx_this_censor_samples) %>% 
  split(.$type) %>% 
  map(function(df){
    test = cor.test(df$ave_type, 
                   df$simpson_reciprocal, 
                   method = 'spearman', 
                   exact = F)
    return(list(rho = round(test$estimate, 2),
                pval = test$p.value))
  }) %>% 
  bind_rows(.id = 'ID') %>% 
  separate(ID, into = c('item','grp'), sep = '_') %>% 
  mutate(type = if_else(item %in%  nutrients, 'nutrient', 'food_group')) %>% 
  mutate(FDR = p.adjust(pval, method = 'BH')) %>% 
  mutate(neglogFDR = -log(FDR))


spearman_res_rm %>% 
  filter(type == 'nutrient') %>% 
  ggscatter(x = 'item', y = 'rho', size = 'neglogFDR', label = T, lab.size = 1,
            color = 'grp', palette = 'jama',
            title = 'Spearman cor between ave nutrient metric & stool alpha diversity') +
  theme_cleveland() 


spearman_res_rm %>% 
  filter(type == 'food_group') %>% 
  ggscatter(x = 'item', y = 'rho', size = 'neglogFDR', label = T, lab.size = 1,
            color = 'grp', palette = 'jama',
            title = 'Spearman cor between ave food group metric & stool alpha diversity') +
  theme_cleveland()   
```

## Correlate alpha div with second level food group

```{r}
# the nodes and the second level food group
nodes <- read_tsv('../data/source/NodeLabelsMCT.txt', col_types = cols(.default = col_character())) %>% 
  filter(str_length(Level.code) == 2) %>% 
  # remove the ones ending with 0 like 20 and 50
  filter(!str_detect(Level.code, '0$'))
  
```


```{r}
# the food dewt count data at level 2 group.
food_level2 <- read_csv('../data/finalized/all_patients_record_w_food_code.csv') %>% 
  select(mrn, Food_code, dehydrated_weight, DayRT ) %>% 
  rename(Fdrt = DayRT) %>% 
  mutate(Fdrt = as.character(Fdrt)) %>% 
  mutate(Level.code = str_sub(Food_code, start = 1, end = 2)) %>% 
  group_by(mrn, Fdrt, Level.code) %>% 
  summarise(sum_dewt_l2 = sum(dehydrated_weight)) %>% 
  left_join(nodes , by  = 'Level.code') %>% 
  rename(description = Main.food.description)
  
```

```{r}
# pair the stool with the mean previous 3 day's level 2 food group weight

pair_p3day_food_level2 <- apply(all_p3day, 1, function(Row){
    food_level2 %>% 
        filter(mrn == Row[['mrn']]) %>% 
        filter(Fdrt %in% c(Row[['p1dF']], Row[['p2dF']],Row[['p3dF']])) %>% 
        group_by(Level.code, description) %>% 
        summarise(ave_level2 = mean(sum_dewt_l2))
})

names(pair_p3day_food_level2) <- all_p3day$ID

# also join with the stool alpha diversity
pair_p3day_food_level2_res <- bind_rows(pair_p3day_food_level2, .id = 'ID') %>% 
  separate(ID, into = c('mrn','sampleid'), sep = '_') %>% 
  inner_join(asv_alpha_diversity_ag %>% select(sampleid, simpson_reciprocal), by = 'sampleid')


# filter out the level 2 food groups that have too few items
level2_num_rm <- pair_p3day_food_level2_res %>% 
  count(Level.code) %>% 
  filter(n < 10) %>% 
  pull(Level.code)

# filter out the the above group and also the stool samples that have been affected by the serious abx
pair_p3day_food_level2_res_fil <- pair_p3day_food_level2_res %>% 
  filter(! Level.code %in% level2_num_rm) %>% 
  filter(! sampleid %in% abx_this_censor_samples)     

# spearman test
spearman_res <- pair_p3day_food_level2_res_fil %>% 
  split(.$Level.code) %>% 
  map(function(df){
    test = cor.test(df$ave_level2, 
                   df$simpson_reciprocal, 
                   method = 'spearman', 
                   exact = F)
    return(list(rho = round(test$estimate, 2),
                pval = test$p.value))
  }) %>% 
  bind_rows(.id = 'ID') %>% 
  mutate(FDR = p.adjust(pval, method = 'BH')) %>% 
  mutate(neglogFDR = -log(FDR)) %>% 
  arrange(desc(neglogFDR)) %>% 
  rename(Level.code = ID) %>% 
  left_join(nodes , by  = 'Level.code') %>% 
  filter(!is.na(pval))

# join with the med weight for the level 2 food group
pair_p3day_food_level2_res_fil_med_wt <- pair_p3day_food_level2_res_fil %>% 
  ungroup() %>% 
  group_by(Level.code) %>% 
  summarise(med_wt = median(ave_level2))

spearman_res_plot <- spearman_res %>% 
  inner_join(pair_p3day_food_level2_res_fil_med_wt, by  = 'Level.code')
  

```

```{r}
# plot
spearman_res_plot %>% 
  ggscatter(x = 'rho', y = 'neglogFDR', size = 'med_wt',
            xlab = 'Spearman rho', ylab = '-log(FDR)', 
            title = 'Volcano plot level 2 food group dewt VS simpson r diversity', 
            #color = 'Level.code', legend = 'none',
            alpha = 0.7 , label = 'Level.code', repel = T) +
  geom_hline(yintercept = c(2.3,3), linetype = 'dashed', col = 'red') +
  geom_vline(xintercept = 0, linetype = 'dashed', col = 'red') +
  ggsave('../figs/spearman_level2_food_simpson.pdf', width = 8, height = 7)
```
```{r}
# show the level code and its corresponding description
spearman_res_plot %>% 
  arrange(Level.code) %>% 
  kable() %>% 
  kable_styling(full_width = F, position = 'left')
```

```{r}
# out put the res_fil table for another script that I calculate the correlation with family level taxon
pair_p3day_food_level2_res_fil %>% 
  write_csv('../data/finalized/paired/pair_p3day_food_level2_res_fil.csv')

```

