---
title: "the new 30 cleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(readxl)
```

```{r}
# the computrition output of the new 30
new <- read_excel('../data/source/new30_all.xlsx') %>% 
  distinct(Food_NSC)

# the ones that we already have food code
uni <- read_excel('../data/source/eaten_FNDDS.xlsx', sheet = 1)

uniq_food <- uni %>% 
  distinct(item1_value_raw_raw,  .keep_all = T)

length(intersect(uniq_food$item1_value_raw_raw, new$Food_NSC))

# the ones that don't have exact match with the food nsc thus don't have a code
unknown <- new %>% 
  filter(! Food_NSC %in% uniq_food$item1_value_raw_raw) %>% 
  arrange(Food_NSC) %>% 
  # remove the title lines (not food)
  filter(!str_detect(Food_NSC, '^\\*\\*\\*\\*\\*\\*\\*'))

unknown %>% 
  write_csv('../data/source/new30_unknown_food_nsc.csv')
```
```{r}
# 
final <- read_csv('../data/finalized/all_patients_record_w_food_code.csv') %>% 
  filter(Food_NSC %in% c('Cheese and Crackers Snack Pack','Cheese and Crackers, SF','2017 Panini, Mozzarella Cheese & Tomato (3.5)','2017 Sandwich, Tomato & Mozzarella Pesto Panini','Pie, Apple a La Mode','2017 Salad, Shrimp Caesar - Entree (1.5)','Lettuce and Tomato Garnish'))
```
```{r}
# the food in the first 67 patients that have 2 items food
multiple <- read_csv('../data/finalized/all_patients_record_w_food_code.csv') %>% 
  filter(Food_NSC %in% c('Cheese and Crackers Snack Pack','Cheese and Crackers, SF','2017 Panini, Mozzarella Cheese & Tomato (3.5)','2017 Sandwich, Tomato & Mozzarella Pesto Panini','Pie, Apple a La Mode','2017 Salad, Shrimp Caesar - Entree (1.5)','Lettuce and Tomato Garnish')) %>% 
  select(Food_NSC: Sodium_mg) %>% 
  distinct()

multiple %>% 
  write_csv('../data/source/foods_to_be_split.csv')

# the current cleaned table
final <- read_csv('../data/finalized/all_patients_record_w_food_code.csv')
```

# new 30

## in the list of unique foods with new food codes, ignore the NA ones and ignore the one with 2 items, and combine with the codes I previously have

```{r}
new_unique <- read_excel('../data/new30_FNDDS_Peter.xlsx') %>% 
  filter(Food.Code != 'NA') %>% 
  filter(is.na(...6)) %>% 
  select(Food_NSC:FNDDS.Main.Food.Description)


# the previous unique food and food code I have 
uniq_food_code <- uniq_food %>% 
  distinct(item1_value_raw_raw, Food.Code, FNDDS.Main.Food.Description) %>% 
  rename(Food_NSC = item1_value_raw_raw) %>% 
  mutate(Food.Code = as.character(Food.Code))

# ALL of the unique food nsc and its code!
all_code <- bind_rows(
  uniq_food_code,
  new_unique
)

all_code %>% 
  write_csv('../data/cleaned_diet_data/all_food_nsc_with_code.csv')
```

## get the food code for all items in the new 30 pts

```{r}
new_all <- read_excel('../data/source/new30_all.xlsx')  %>% 
  select(- ...1, - Food) %>% 
  left_join(all_code, by = 'Food_NSC') %>% 
  filter(Por_eaten != 'na') %>% 
  filter(!str_detect(Food_NSC, '^\\*\\*\\*\\*\\*\\*\\*')) %>% 
  mutate(Por_eaten = if_else(str_detect(Por_eaten, '^.'), str_glue('0{Por_eaten}'), Por_eaten)) %>% 
  mutate(Por_eaten = as.numeric(Por_eaten)) %>% 
  filter(Por_eaten > 0) %>% 
  select(-Unit, -Por_ordered) 

new_all %>% 
  write_csv('../data/cleaned_diet_data/new_all_cleaned_with_NA.csv')
```


```{r}
# find the distinct foods (also the portion eaten) that have NA or blanks
new_all_blanks <- new_all %>% 
  select(Food_NSC: Sodium_mg) %>% 
  distinct()  %>% 
  filter(Por_eaten != 'na') %>% 
  mutate(Por_eaten = if_else(str_detect(Por_eaten, '^.'), str_glue('0{Por_eaten}'), Por_eaten)) %>% 
  mutate(Por_eaten = as.numeric(Por_eaten)) %>% 
  filter(Por_eaten > 0) %>% 
  select(-Unit, -Por_ordered) %>% 
  filter(!str_detect(Food_NSC, '^\\*\\*\\*\\*\\*\\*\\*')) %>% 
  filter(is.na(Calories_kcal) | 
           is.na(Proteing_g) |
           is.na(Fat_g) |
           is.na(Carbohydrates_g) |
           is.na(Fibers_g) |
           is.na(Sugars_g) |
           is.na(Sodium_mg) ) %>% 
  arrange(Food_NSC)


length(intersect(new_all_blanks$Food_NSC, final$Food_NSC))

new_all_blanks %>% 
  write_csv('../data/source/new_30_records_with_NA.csv')
```

