---
title: "double check my 67 diet cleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
```

```{r}
all_code <- read_csv('../data/cleaned_diet_data/all_food_nsc_with_code.csv')

# some cleaning , remove unnecessary columns, filter out some unnecessary rows, change column types
all <- read_excel('../data/source/new_list.xls') %>% 
  filter(!str_detect(Food_NSC, '^\\*\\*\\*\\*\\*\\*\\*')) %>% 
  filter(Por_eaten != 'na') %>% 
  select(- ...1, - Food, -Unit, -Por_ordered, -SFA_g, -Cholesterol_mg, -MUFA_g, -PUFA_g, -Name) %>% 
  mutate(Por_eaten = as.numeric(Por_eaten)) %>% 
  filter(Por_eaten > 0) %>% 
  # I have a code for them
  filter(Food_NSC %in% all_code$Food_NSC) %>%  
  mutate(Date = mdy(Date)) %>% 
  # get rid of the + in the values
  mutate(Calories_kcal = str_replace_all(Calories_kcal, '\\+$',''),
           Proteing_g = str_replace_all(Proteing_g, '\\+$',''),
           Fat_g = str_replace_all(Fat_g, '\\+$',''),
           Carbohydrates_g = str_replace_all(Carbohydrates_g, '\\+$',''),
           Fibers_g = str_replace_all(Fibers_g, '\\+$',''),
           Sugars_g = str_replace_all(Sugars_g, '\\+$',''),
           Sodium_mg = str_replace_all(Sodium_mg, '\\+$','')) %>% 
    mutate(Calories_kcal = as.numeric(Calories_kcal),
           Proteing_g = as.numeric(Proteing_g),
           Fat_g = as.numeric(Fat_g),
           Carbohydrates_g = as.numeric(Carbohydrates_g),
           Fibers_g = as.numeric(Fibers_g),
           Sugars_g = as.numeric(Sugars_g),
           Sodium_mg = as.numeric(Sodium_mg)) 
```

## correct the outliers

```{r}
outlier_cor <- read_csv('../data/outlier_very_obvious_peter.csv') %>% 
  select(Food_NSC, Por_eaten:Sodium_mg)

outlier_to_be_corrected <- all %>% 
  filter(Food_NSC %in% outlier_cor$Food_NSC)  %>% 
  distinct(Food_NSC, Por_eaten, .keep_all = T) %>% 
  select(MRN:Por_eaten) %>% 
  left_join(outlier_cor) %>% 
  arrange(Food_NSC)


# ok I have to do this programmatically
outlier_cor_res <- outlier_to_be_corrected %>% 
  arrange(Food_NSC, Calories_kcal) %>% 
  group_by(Food_NSC) %>% 
  mutate(Calories_kcal = Calories_kcal[1],
         Proteing_g = Proteing_g[1],
         Fat_g = Fat_g[1],
         Carbohydrates_g = Carbohydrates_g[1],
         Fibers_g = Fibers_g[1],
         Sugars_g = Sugars_g[1],
         Sodium_mg = Sodium_mg[1]) %>% 
  split(.$Food_NSC) %>% 
  map_dfr(~ mutate(.data = ., ratio = Por_eaten/Por_eaten[1]) %>% 
        split(.$Por_eaten) %>% 
        map_dfr(~ mutate(.data = .,   
                   Calories_kcal = Calories_kcal*ratio,
                   Proteing_g = Proteing_g*ratio,
                   Fat_g = Fat_g*ratio,
                   Carbohydrates_g = Carbohydrates_g*ratio,
                   Fibers_g = Fibers_g*ratio,
                   Sugars_g = Sugars_g*ratio,
                   Sodium_mg = Sodium_mg*ratio)) %>% 
        select(-ratio))


# integrate these to the original all df expanding 30 to 240
outlier_or_not <- all %>% 
  split(.$Food_NSC %in% outlier_cor$Food_NSC)

corrected_all <- outlier_or_not %>% 
  pluck('TRUE') %>% 
  select(MRN: Por_eaten) %>% 
  left_join(outlier_cor_res %>% select(Food_NSC:Sodium_mg), by = c('Food_NSC','Por_eaten'))

all_cor1 <- bind_rows(
  corrected_all,
  outlier_or_not %>% pluck('FALSE')
)
```

## correct the ones with ridiculous calories

```{r}
peter1 <- read_csv('../data/source/All_data_check_calories_peter.csv')
peter2 <- read_csv('../data/source/All_data_to_be_checked_peter.csv')
peter_cal <- bind_rows(peter1, peter2) %>% 
  select(Food_NSC, Por_eaten:Sodium_mg) %>% 
  filter(! Food_NSC %in% outlier_cor_res$Food_NSC)
colnames(peter_cal)

length(intersect(peter_cal$Food_NSC, outlier_cor_res$Food_NSC))

# don't wanna re-correct the outlier_cor_res ones, so just remove those appear in that list

# now do the things very similar to how I correct the outliers
all_peter_cal <- all_cor1 %>% 
  filter(Food_NSC %in% peter_cal$Food_NSC) %>% 
  distinct(Food_NSC, Por_eaten, .keep_all = T) %>% 
  select(MRN:Por_eaten) %>% 
  left_join(peter_cal) %>% 
  arrange(Food_NSC)

# use the ratio to correct other portions
cal_cor_res <- all_peter_cal %>% 
  arrange(Food_NSC, Calories_kcal) %>% 
  group_by(Food_NSC) %>% 
  mutate(Calories_kcal = Calories_kcal[1],
         Proteing_g = Proteing_g[1],
         Fat_g = Fat_g[1],
         Carbohydrates_g = Carbohydrates_g[1],
         Fibers_g = Fibers_g[1],
         Sugars_g = Sugars_g[1],
         Sodium_mg = Sodium_mg[1]) %>% 
  split(.$Food_NSC) %>% 
  map_dfr(~ mutate(.data = ., ratio = Por_eaten/Por_eaten[1]) %>% 
        split(.$Por_eaten) %>% 
        map_dfr(~ mutate(.data = .,   
                   Calories_kcal = Calories_kcal*ratio,
                   Proteing_g = Proteing_g*ratio,
                   Fat_g = Fat_g*ratio,
                   Carbohydrates_g = Carbohydrates_g*ratio,
                   Fibers_g = Fibers_g*ratio,
                   Sugars_g = Sugars_g*ratio,
                   Sodium_mg = Sodium_mg*ratio)) %>% 
        select(-ratio))


# integrate
cal_or_not <- all_cor1 %>% 
  split(.$Food_NSC %in% cal_cor_res$Food_NSC)

corrected_all_cal <- cal_or_not %>% 
  pluck('TRUE') %>% 
  select(MRN: Por_eaten) %>% 
  left_join(cal_cor_res %>% select(Food_NSC:Sodium_mg), by = c('Food_NSC','Por_eaten'))

all_cor2 <- bind_rows(
  corrected_all_cal,
  cal_or_not %>% pluck('FALSE')
)
```

## check the NA ones

```{r}
all_cor2 %>% 
  gather(key = 'item', value = 'value', Por_eaten:Sodium_mg) %>% 
  filter(is.na(value)) %>% 
  nrow
# good there is no NA now


# to keep all of the unique rows (all values in the row should be unique)
all_cor3 <- all_cor2 %>% 
  distinct() 
```

## the food with multiple items

```{r}
multiple <- read_csv('../data/more_than_one_Peter_updated.csv') %>% 
  # remove the Lettuce and Tomato Garnish cuz the cal dont match
  filter(item1_value_raw_raw != 'Lettuce and Tomato Garnish')



# clean the multiple and get back the total cal
multiple_clean <- multiple %>% 
  select(-item1_index, -WWEIA.Category.Code, -WWEIA.Category.Description, -weight) %>% 
  group_by(item1_value_raw_raw) %>% 
  mutate(total_cal = sum(Calories_kcal)) %>% 
  mutate(component = str_replace(FNDDS.Main.Food.Description, ',.+$','')) %>% 
  mutate(Food_NSC = str_glue('{item1_value_raw_raw}--{component}'))

# the food code for these newly created items that need to be added to my food code db
multiple_clean_code <- multiple_clean %>% 
  distinct(Food_NSC, Food.Code, FNDDS.Main.Food.Description)



final_all_code <- bind_rows(
  all_code,
  multiple_clean_code
)

final_all_code %>% 
  write_csv('../data/cleaned_diet_data/all_food_nsc_with_code_FINAL.csv')
```

```{r}
# are there other portions for those foods?
multiple_all <- all_cor3 %>% 
  filter(Food_NSC %in% multiple$item1_value_raw_raw) %>% 
  distinct(Food_NSC, Por_eaten, Calories_kcal) %>% 
  arrange(Food_NSC)
```


## the calories == 0 ones that I need peter to give me the gram weight, all of the patients together

```{r}
old_cal0 <-  all_cor3 %>% 
  filter(Calories_kcal == 0) %>% 
  select(Food_NSC:Sodium_mg) %>% 
  distinct(Food_NSC, Por_eaten, Calories_kcal)


# WAIT FOR PETER TO CORRECT NA ONES FOR THIS PART CUZ SOME OF THE NA ONES SHOULD BE ZERO
new_cal0 <- read_csv('../data/cleaned_diet_data/new_all_cleaned_with_NA.csv')
```

