---
title: "Relax paring threshold"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# make one stool with previous 3 days diet pairing

There has to be one real day's data in the previous 3 days
   
 
## Get all of the qualified stool samples (remove the empirical abx affected ones)

```{r}
all_stool <- read_csv('../data/finalized/stool/filter_stool_close_to_diet_meta.csv') %>% 
  filter(keep == 'keep')  

censor_abx <- c('active_atb_vanco_po',	'active_atb_imipenem',	'active_atb_meropenem',	'active_atb_ertapenem',		'active_atb_cefepime',		'active_atb_linezolid',	'active_atb_metro',	'active_atb_piptazo')

abx_all <- read_csv('../data/finalized/abx/abx_all_samples_with_censoring_info.csv')
  
abx_all_stool_censor_samples <- abx_all %>% 
  filter(sampleid %in% all_stool$sampleid) %>% 
  select(sampleid, active_atb_cipro:active_atb_other) %>% 
  gather(key = 'abx_type', value = 'value', names(.)[2]:names(.)[ncol(.)]) %>% 
  filter(abx_type %in% censor_abx) %>% 
  filter(value == T) %>% 
  distinct(sampleid) %>% 
  pull(sampleid)  

qua_stool <- all_stool %>% 
  filter(!sampleid %in% abx_all_stool_censor_samples) %>% 
  select(mrn, sampleid, drt) %>% 
  mutate(id = paste0("row", 1:nrow(.)))

qua_stool %>% 
  count(mrn) %>% 
  arrange(n)

```


```{r}
# continue selecting qualified stool samples, there has to be at least one real day's diet data in the previous three days.

# list the previous three days drt for every stool sample 
qual_stool_df <- qua_stool %>% 
  mutate(p1d = drt-1,
         p2d = drt-2,
         p3d = drt-3) %>% 
  select(-sampleid, -drt, -id)

# use the non fake diet counts table and get the stool samples that should be removed -- not even one day
no_real_diet_d_to_be_rm_stool_s <- function(mrn_, p1d_, p2d_, p3d_){
  df = dtb67 %>% 
    filter(mrn == mrn_) %>% 
    filter(DayRT == p1d_ | DayRT == p2d_ |DayRT == p3d_ ) %>% 
    nrow()
  
  return(df)
}

qual_stool2 <- pmap(qual_stool_df, function(mrn, p1d, p2d, p3d){
    no_real_diet_d_to_be_rm_stool_s(mrn, p1d, p2d, p3d)
  }) %>% 
  set_names(paste0("row", 1:nrow(qual_stool_df))) %>% 
  bind_rows() %>% 
  gather(key = 'id', value = 'num_d_records') %>% 
  arrange(num_d_records) %>% 
  full_join(qua_stool, by  = 'id')
  
qual_stool_sampled_final <- qual_stool2 %>% 
  filter(num_d_records > 0)  %>% 
  select(-id, -num_d_records)
```

```{r}
mean(c(1,2,NA), na.rm = T)
mean(c(1,2,0), na.rm = T)
```


## get the gram weight and the percentage for the food groups and nutrients for each patient on each diet data day

```{r}
nutrients_df <- filled %>% 
  select(mrn, DayRT, Proteing_g:Sodium_g) %>% 
  gather('nutrient', 'gram', names(.)[3]:names(.)[ncol(.)]) 

nutrients_day_nut_total  <- nutrients_df %>% 
  group_by(mrn, DayRT, nutrient) %>% 
  summarise(nut_day_total = sum(gram))

# the denominator is all the nutrients summed together for that day for that patient
nutrients_day_denomi <- nutrients_df %>% 
  group_by(mrn, DayRT) %>% 
  summarise(all_tol_day = sum(gram))

nutrients_all  <- nutrients_day_nut_total %>% 
  left_join(nutrients_day_denomi) %>% 
  mutate(nut_day_perc = round(nut_day_total/all_tol_day, 2)) %>% 
  mutate(nutrient = str_replace(nutrient, '_g$','')) %>% 
  mutate(nutrient = str_glue('Nut_{nutrient}'))

```

