---
title: "counts_matrix_pca"
author: "Angel"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

I take reference of this page: https://www.datacamp.com/community/tutorials/pca-analysis-r. A very good one. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F)
```

```{r}
library(vegan)
library(tidyverse)
library(ggpubr)
```

```{r}
# create a fake counts matrix, rows: features; columns: samples
set.seed(2)
dat <- c(rep(0, 100), 100 * rgamma(900, shape = 1, rate = 2))
cts <- matrix(data = sample(dat, size = 1000, replace = F),
              nrow = 10,
              ncol = 100)

# log transform the counts (add a pseudo count)
cts_log <- log2(cts + 0.1)


# use the prcomp function (stands for principle components) to do the PCA, for the param center and scale please refer to the function's help page:
# center: a logical value indicating whether the variables should be shifted to be zero centered.
# scale: a logical value indicating whether the variables should be scaled to have unit variance before the analysis takes place. The default is FALSE for consistency with S, but in general scaling is advisable. 
# IMPORTANT: need to transpose the matrix to make samples as the rows
pca_res <- prcomp(t(cts_log), center = TRUE, scale. = TRUE)

# look at the summary of the results, "Proportion of Variance" is what we want to annotate to the axis
summary(pca_res)

# or we can calculate the Proportion of Variance by hand and convert to percentage
percent_var <- round(pca_res$sdev^2/sum(pca_res$sdev^2)*100, 2)


# plot 
pca_res$x %>% 
  as.data.frame() %>% 
  ggscatter(x = 'PC1', y = 'PC2', alpha = 0.7,
            xlab = str_glue("PC1-{percent_var[1]}%"),
            ylab = str_glue("PC2-{percent_var[2]}%"))
```


