---
title: "counts_matrix_pcoa"
author: "Angel"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F)
```

```{r}
library(vegan)
library(tidyverse)
library(ggpubr)
```

```{r}
# create a fake counts matrix, rows: features; columns: samples
set.seed(2)
dat <- c(rep(0, 100), 100 * rgamma(900, shape = 1, rate = 2))
cts <- matrix(data = sample(dat, size = 1000, replace = F),
              nrow = 10,
              ncol = 100)

# normalize by sample
cts_norm <- sweep(cts, 2, colSums(cts), FUN="/")

# calculate pairwise distance, any metric you think suitable
# need to transpose the matrix to make samples as the rows
# here bray curtis is used
dist_ <- vegdist(t(cts_norm), method = 'bray')

# get the pcoa results, request to return eigen values so we can calculate percent variance in each dimension 
pcoa_ <- cmdscale(dist_, eig = T) 

percent_var <- round( pcoa_$eig/sum(pcoa_$eig)*100, digits = 1)

# plot 
pcoa_$points %>% 
  as.data.frame() %>% 
  ggscatter(x = 'V1', y = 'V2', alpha = 0.7,
            xlab = str_glue("MDS1-{percent_var[1]}%"),
            ylab = str_glue("MDS2-{percent_var[2]}%"))
```


