---
title: "human fiber and alpha abstract"
author: "Angel"
date: "2022-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) 
library(ggpubr)         
```

```{r}
meta <- read_csv('~/pipeline/scripts/food_tree/data/090_all_samples_meta_p2d_fg9_dietall_genera34.csv') %>% 
  select(mrn, sdrt, simpson_reciprocal, ave_fiber) %>% 
  mutate(ave_fiber = ave_fiber*100) %>% 
  filter(sdrt %in% 7:21)

meta %>% distinct(mrn)
```
```{r}
meta %>% 
  group_by(mrn) %>% 
  summarise(ave_div = mean(simpson_reciprocal),
            mean_fiber = mean(ave_fiber)) %>% 
  ggscatter(x = 'mean_fiber', y = 'ave_div',
            xlab = 'Prior 2 day fiber intake averaged by patient', ylab = 'microbiome alpha diversity averaged by patient',
            add = "reg.line",  # Add regressin line
           add.params = list(color = "blue", fill = "lightgray"), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "pearson",  label.sep = "\n")) +
  theme(aspect.ratio=1)
```

```{r}
# a box plot
mean_fiber_intake <- mean(meta$ave_fiber)
grps <- meta %>% 
  mutate(grp = if_else(ave_fiber > mean_fiber_intake, 'high', 'low'))

grps %>% 
  ggboxplot(x = 'grp', y = 'simpson_reciprocal', xlab = 'Compared to average prior 2 day fiber intake',
            ylab = 'Microbiome alpha diversity') +
  stat_compare_means(comparisons= list(c('high', 'low')),
            label= "p.format",
            method= 'wilcox.test',
						correct=FALSE)
```


