---
title: "bind the df and normalize and combine to whole df"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggpubr)
```

```{r}

kos <- list.files('../data/done_results/', recursive = T, full.names = T, pattern = 'pred_metagenome_unstrat.tsv')

res <- kos %>% 
  purrr::map(function(fn){
    tb <- read_tsv(fn) %>% 
        gather('sampleid','count', names(.)[2]:names(.)[ncol(.)]) %>% 
        filter(count != 0)
      
      tb_sum <- tb %>% 
        group_by(sampleid) %>% 
        summarise(total =  sum(count))
      
      tb_norm <- tb %>% 
        left_join(tb_sum, by = 'sampleid') %>% 
        mutate(cpm = count/total*1000000) %>% 
        rename(KOID = names(.)[1]) %>% 
        select(KOID, sampleid, cpm)
      return(tb_norm)
  }) %>% 
  bind_rows()

# res %>% 
#   write_csv('/Volumes/vandenBrinkLab/Angel_Dai/picrust2_and_bile/normalized_picrust2_pred_metagenome_KO_all_counts.csv')

```

```{r}
# 10-7 Oriana requested items for 2100 samples
samp <- read_rds('~/Downloads/samples_picrust.rds')
```


```{r}
# the pathway table
pw <- list.files('../data/done_results/', recursive = T, full.names = T, pattern = 'path_abun_unstrat.tsv')

pw_res <- pw %>% 
  purrr::map(function(fn){
    tb <- read_tsv(fn) %>% 
        gather('sampleid','count', names(.)[2]:names(.)[ncol(.)])  %>% rename(pathway = names(.)[1])
      return(tb)
  }) %>% 
  bind_rows()

# the results in the O cohort
O_pathway <- pw_res %>% 
  filter(sampleid %in% samp$sampleid)


O_pathway %>% 
  write_csv('/Volumes/vandenBrinkLab/Angel_Dai/picrust2_and_bile/Oriana_2100_samples_pathway_count.csv')

O_pathway %>% 
  distinct(sampleid)
```


```{r}

O_samp <- res %>% 
  filter(sampleid %in% samp$sampleid)

O_samp %>% 
  count(sampleid)

O_samp %>% 
  write_csv('/Volumes/vandenBrinkLab/Angel_Dai/picrust2_and_bile/Oriana_2100_samples_KO.csv')
```


```{r}
# find the KOs we are interested in
KOs <- c('K01442','K15868','K15869','K15870','K15871','K15872','K15873','K15874',
         'K07007','K22604','K22605','K22606','K22607')

bile_res <- res %>% 
  filter(KOID %in% KOs) 

bile_res_dist <- bile_res %>% 
  dplyr::count(sampleid)

KOID_dist <-  bile_res %>% 
  dplyr::count(KOID)


bile_res %>% 
  write_csv('../data/normalized_picrust2_pred_metagenome_KO_secondary_bile_counts.csv')
```

```{r}
# see the cpm distribution 
# create a df to have the height of the annotation also
KOID_dist_df <- KOID_dist %>% 
  mutate(height = quantile(bile_res %>%  filter(KOID == 'K01442') %>% pull(cpm), 0.9))

bile_res %>% 
  ggboxplot('KOID', 'cpm', title = 'All KOs related to secondary bile acid biosynthesis') +
  geom_text(data = KOID_dist_df, aes(x = KOID, y = height, label = n)) +
  theme_bw() +
  scale_y_continuous( breaks =seq(0, 3000, 200)) +
  ggsave('../figs/All KOs related to secondary bile acid biosynthesis.jpg', width = 6, height = 4)
```

```{r}
# 2020-5-14
# get oriana's her interested samples
samps <- read_csv('~/Downloads/rest_samples_KO.csv')

rest <- res %>% 
  filter(sampleid %in% samps$sampleid)

rest %>% 
  count(sampleid)

length(intersect(samps$sampleid, res %>% distinct(sampleid) %>% pull(sampleid)))

rest %>% 
  write_csv('../data/rest_samples_KO_all.csv')
```

## the Mait samples 2021-2-15

```{r}
mait <- read_csv('../data/samples_picrust.csv')

all <- res %>% 
  distinct(sampleid) %>% pull(sampleid)

length(intersect(all, mait$sampleid ))

library(vdbR)
connect_database('~/dbConfig.txt')
get_table_from_database('asv_alpha_diversity_ag')

no <- setdiff(mait$sampleid , all)

no <- asv_alpha_diversity_ag %>% 
  filter(sampleid %in% no)

current <- res %>% 
  filter(sampleid %in% mait$sampleid)

current %>% 
  write_csv('/Volumes/vandenBrinkLab/Angel_Dai/picrust2_and_bile/Mait_392_samples_picrust2.csv')
```

