---
title: "Chapter 2"
output: html_document  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rethinking)
```

## R code 2.8-2.9

```{r}
# the simple example of MCMC
## R code 2.8
n_samples <- 1000
p <- rep( NA , n_samples )
p[1] <- 0.5
W <- 6
L <- 3

for ( i in 2:n_samples ) {
    p_new <- rnorm( 1 , p[i-1] , 0.1 )
    if ( p_new < 0 ) p_new <- abs( p_new )
    if ( p_new > 1 ) p_new <- 2 - p_new
    q0 <- dbinom( W , W+L , p[i-1] )
    q1 <- dbinom( W , W+L , p_new )
    p[i] <- ifelse( runif(1) < q1/q0 , p_new , p[i-1] )
}

## R code 2.9
dens( p , xlim=c(0,1) )
curve( dbeta( x , W+1 , L+1 ) , lty=2 , add=TRUE ) # lty = 2 means dashed 
```

## the practice 

```{r}
# 2M1
# 1. WWW
N <- 100
p_grid <- seq(from = 0, to = 1, length.out = N)
prior <- rep(1, N)
likelihood <- dbinom(3, 3, p_grid)
posterior_unstd <- likelihood * prior
posterior <- posterior_unstd / sum(posterior_unstd)

plot(x = p_grid, y = posterior, type = 'o') # o for Both “overplotted”

# 2. WWWL
likelihood <- dbinom(x = 3, size = 4, p_grid)
posterior_unstd <- likelihood * prior
posterior <- posterior_unstd / sum(posterior_unstd)
plot(x = p_grid, y = posterior, type = 'o')

# 3. LWWLWWW
likelihood <- dbinom(x = 5, size = 7, p_grid)
posterior_unstd <- likelihood * prior
posterior <- posterior_unstd / sum(posterior_unstd)
plot(x = p_grid, y = posterior, type = 'o')
```

```{r}
# 2M2
prior <- ifelse(p_grid < 0.5, 0, 0.7)
likelihood <- dbinom(3, 3, p_grid)
posterior_unstd <- likelihood * prior
posterior <- posterior_unstd / sum(posterior_unstd)

plot(x = p_grid, y = posterior, type = 'o') # o for Both “overplotted”

# 2. WWWL
likelihood <- dbinom(x = 3, size = 4, p_grid)
posterior_unstd <- likelihood * prior
posterior <- posterior_unstd / sum(posterior_unstd)
plot(x = p_grid, y = posterior, type = 'o')

# 3. LWWLWWW
likelihood <- dbinom(x = 5, size = 7, p_grid)
posterior_unstd <- likelihood * prior
posterior <- posterior_unstd / sum(posterior_unstd)
plot(x = p_grid, y = posterior, type = 'o')
```


```{r}
# 2M3
P = 0.3*0.5/(0.3*0.5 + 1*0.5)
```

