---
title: "The K2XXXX KOs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(seqinr)
```
```{r}
# the genes and its aa seq directly copied from the kegg website
desc <- c('K22604_Elen_0690_3alpha-hydroxycholanate dehydrogenase (NAD+)',
          '22604_EGYY_08520_3alpha-hydroxycholanate dehydrogenase (NAD+)',
          '22604_GPA_01510_3alpha-hydroxycholanate dehydrogenase (NAD+)',
          'K22605_CPF_1154_7-alpha-hydroxysteroid dehydrogenase',
          'K22605_CPR_0991_7-alpha-hydroxysteroid dehydrogenase',
          'K22605_EDN77529_3alpha-hydroxycholanate dehydrogenase (NADP+)',
          'K22606_Elen_0198_short-chain dehydrogenase/reductase SDR',
          'K22606_GPA_22420_Dehydrogenases with different specificities (related to short-chain alcohol dehydrogenases)',
          'K22607_EDN78833_3beta-hydroxycholanate 3-dehydrogenase (NADP+)')


aa <- c('MGIYVITGATSGIGAKTAEILRERGHEVVNIDLNGGDINANLATKEGRAGAIAELHERFP
EGIDAMICNAGVSGGKVPISLIISLNYFGATEMARGVFDLLEKKGGSCVVTSSNSIAQGA
ARMDVAGMLNNHADEDRILELVKDVDPAIGHVYYASTKYALARWVRRMSPDWGSRGVRLN
AIAPGNVRTAMTANMLPEQRAAMEAIPVPTHFGEEPLMDPVEIANAMAFIASPEASGING
VVLFVDGGTDALLNSEKVY',
'MGVYVITGASSGIGAKTAEILRERGHEVVNIDLKDGDINANLATKEGRANALAELHERYP
DGIDAMICNAGVSGGKVPISLIISLNYFGATEMARGAFDLLEKKGGSCLVTSSNSIAQGA
ARMDVAGMLNNHPDEDRILELVKDVDPAIGHVYYASTKYALARWVRRMSPDWGSRGVRLN
AIAPGNVRTAMTSNMLPEQRAAMEAIPVPTHFGEEPLMDPVEIANVMAFVASPEASGLNG
VVLFADGGTDALLNSEKVY',
'MGIYVITGASSGIGAKTAEILRERGHEVVNIDLKDGDIEANLATKEGRAGAIAELHERYP
EGIDAMICNAGVSGGKVPISLIISLNYFGATEMAKGARDLLEKKGGSCVITSSNSIAQGA
ARMDVAGMLNNQADEDRILELVKDVDPAVGHVYYASTKYALARWVRRMSPDWGSRGVRLN
AIAPGNVRTAMTANMLPEQRAAMEAIPVPTHFGEEPLMEPIEIANAMAFIASPEASGING
VVLFVDGGTDALLNSEKVY',
'MDILSKSIKNKVVIVTGGTRGIGFATVKKFLDHGAKVALCGSRKETVDKALEELNHINPN
YDAIGFYPNLLDSNEVKEMVDKVLEKWGTIDILINNAGVSDNKSIYTQSDEDFSKIIDIN
VKAIFNCTKAVSEIMKNKKYGVILNTSSVVSLYGQKTGVGYPTSKFAVNGLTKSLARELG
KDGIRVNAVAPGIIATDMVAALDKKLVDQIAQNVPLGRVGEPEDIANAFLFLASDMASYI
SGEILSVDGSVVL',
'MDILSKSIKNKVVIVTGGTRGIGFATVKKFLDHGAKVALCGSRKETVDKALEELNYINPN
YDAIGFYPNLLDSNEVKEMVDKVLEKWGTIDILINNAGVSDNKSIYTQSDEDFSKIIDIN
VKAIFNCTKAVSEIMKNKKYGVILNTSSVVSLYGQKTGVGYPTSKFAVNGLTKSLARELG
RDGIRVNAVAPGIIATDMVAALDKKLVDQIAQNVPLGRVGEPEDIANAFLFLASDMASYI
SGEILSVDGSVVL',
'MFMMLKNKVAIVTGGTRGIGFAVVKKFIENGAAVSLWGSRQETVDQALEQLKELYPDAKI
SGKYPSLKDTAQVTAMINQVKEEFGAVDILVNNAGISQSTSFYNYQPEEFQKIVDLNVTA
VFNCSQAAAKIMKEQGGGVILNTSSMVSIYGQPSGCGYPASKFAVNGLTKSLARELGCDN
IRVNAVAPGITRTDMVAALPEAVIKPLIATIPLGRVGEPEDIANAFLFLASDMASYVTGE
ILSVDGAARS',
'MYDDLKGKTVVVTGSSKGLGAAMARRFGAEGMNVVANYRSDEEGARETVRAIEEAGGAAA
AVQADVSKNECVDALFDAAMFSFGGVDIWVNNAGIEVASPSDRKSIEEWQRVIDVNLTGV
FAGCRRAIDHFLDRKMPGVIINLSSVHEIIPWPHFADYAASKAGVGMLTKTLALEYADRG
IRVNAIAPGAMNTPINAEKFADPEARAATERLIPMGYVGAPEDVAAAAAWLASDQASYVT
GTTLFVDGGMTLYPGFQFGQG',
'MQDTLSSPILAGQTAVVTGGASGIGKSIVQRFLEAGANCLAADLNEEALAALKEEFAAYG
DKLDIARVDVSDRDAVEGMVDRAVDMFGQMDIIVNNAGIMDNLLPIAEMDDDVWERLMKV
NLNSVMYGTRKAVRYFLDRGEGGVIINTASLSGLCAGRGGCAYTASKFAVVGLTKNVAFM
YADTGIRCNAICPGNTQTNIGVGMRQPSERGMAKATTGYAGATRSGTPEEISAAALFLAS
DQAGFINGETLTIDGGWSAY',
'MNFGGFIMGRFDEKIMLVTGATSGIGRAVAIRAAKEGATVVAVGRNEERGAAVVAAMEEA
GGKGEFMKCDVSNKDAVKALFAEIQEKYGKLDVAVNNAGIVGASKTVEELEDDDWFQVID
ANLNSCFFCCREEVKLMQPSGGAIVNVSSVAGMRGFPSAAAYVASKHAVSGLTKAVAVDY
ATKGITCNAICPAGTDTPLTERSSADIKTRMAEIAAQGKDPMEWLKNSMLSGKTETLQKK
NATPEEQAATILYFASDEARHITGSIVASDGGFTTY'
)

k2_genes <- data_frame(
  ID = desc,
  seq = aa
)
```




```{r}
write.fasta(sequences = as.list(k2_genes$seq), 
              names = k2_genes$ID,
              file.out = '../data/IMG_genes/K2XXXX_genes.fa')

`1```

