---
title: "Correcting batch effect in AUC"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sva)
library(ggpubr)
```

```{r}
auc <- read_csv('/Volumes/vandenbrinklab/oriana/Study ideas/bile_acids/final_datasets/all_BAs_auc.csv') %>% 
  select(-MRN) %>% 
  rename_all(~ gsub("-", "_", .)) %>% 
  rename_all(~ gsub(" ", "__", .))
```

```{r}
cts <- auc %>% 
  select(-BatchID, - Group) %>% 
  gather('BA', 'auc', names(.)[2]:names(.)[ncol(.)]) %>% 
  spread('sampleid', 'auc') %>% 
  column_to_rownames('BA') %>% 
  as.matrix()

cts[cts<0] <- 0

pseudo <- min(cts[cts>0])

ctslog2 <- log2(cts + 1)

# the pheno data
pheno <- auc %>% 
  select(sampleid,BatchID,  Group) %>% 
  arrange(sampleid)

all.equal(pheno$sampleid, colnames(ctslog2))

combat_ctslog2 = ComBat(dat=ctslog2, batch=pheno$BatchID, mod=NULL, par.prior=FALSE, mean.only=TRUE,prior.plots=T )

pca_res <- prcomp(combat_ctslog2 %>% t(), scale. = TRUE, center = T)

pca_res$x
pca_res$x %>% 
  as.data.frame() %>% 
  rownames_to_column('sampleid') %>% 
  select(PC1, PC2, sampleid) %>% 
  full_join(pheno)  %>% 
  ggscatter(x = 'PC1', y = 'PC2', color = 'BatchID')

combat_ctslog2 %>% 
  as.data.frame() %>% 
  rownames_to_column('BA') %>% 
  write_csv('../data/log2_transformed_auc_batch_corrected.csv')
```



