---
title: "A look at KOs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
```

```{r}
serpath <- '/Volumes/vandenbrinklab/oriana/Study ideas/bile_acids/final_datasets/'

meta <- read_csv(file = file.path(serpath, '08_shotgun_meta.csv'))

ba <- read_excel('../data/KO_BAs.xlsx') %>% 
  mutate(ECnum = str_replace(EC, 'EC:',''))

res <- read_csv(file = file.path(serpath, '08_shotgun_KO.csv'))

ba_kos <- res %>% 
  filter(!str_detect(KOID, '\\|')) %>% 
  filter(KOID %in% ba$KO) %>% 
  left_join(meta)
```

```{r}
# look at urso exposed samples
# onset samples
ba_kos %>% 
  filter(in_onset == 'TRUE') %>% 
  filter(urso_expo == 'TRUE') %>% 
  ggboxplot(x  = 'DiseaseGroup', y = 'cpm', facet.by = 'KOID', add = 'jitter') +
  scale_y_log10() +
  stat_compare_means(comparisons= list(c('GVHD', 'CTRL')),
            label= "p.format",
            method= 'wilcox.test',
						correct=FALSE)

ggsave('../figs/09_onset_KO.pdf', width = 8, height = 12)

# peri samples
ba_kos %>% 
  filter(in_peri == 'TRUE') %>% 
  filter(urso_expo == 'TRUE') %>% 
  ggboxplot(x  = 'DiseaseGroup', y = 'cpm', facet.by = 'KOID', add = 'jitter') +
  scale_y_log10() +
  stat_compare_means(comparisons= list(c('GVHD', 'CTRL')),
            label= "p.format",
            method= 'wilcox.test',
						correct=FALSE)

ggsave('../figs/09_peri_KO.pdf', width = 8, height = 12)

 
# how many samples 
ba_kos %>% 
  filter(in_onset == 'TRUE') %>% 
  filter(urso_expo == 'TRUE') %>% 
  distinct(sampleid) %>% 
  nrow

ba_kos %>% 
  filter(in_peri == 'TRUE') %>% 
  filter(urso_expo == 'TRUE') %>% 
  distinct(sampleid) %>% 
  nrow
```
```{r}
# look at the spp contribution 
# K01442 for peri time
K01442 <- res %>% 
  filter(str_detect(KOID, 'K01442\\|')) %>% 
  left_join(meta, by = c("fid", "sampleid")) %>% 
  filter(in_peri == 'TRUE' & urso_expo == 'TRUE') %>% 
  mutate(spp = str_extract(KOID, 's__.+$')) %>% 
  filter(!is.na(spp)) %>% 
  mutate(genus = str_extract(KOID, 'g__.+\\.'))

K01442 %>% 
  ggboxplot(x  = 'DiseaseGroup', y = 'cpm', facet.by = 'genus', add = 'jitter') +
  scale_y_log10() +
  stat_compare_means(comparisons= list(c('GVHD', 'CTRL')),
            label= "p.format",
            method= 'wilcox.test',
						correct=FALSE)

ggsave('../figs/09_K01442_peri_genus.pdf', width = 10, height = 12)
```

