

```{r}
samples_castori_ag <- get_data_from_query_OTU(0,'samples_castori_ag') 
sampleid_mrn<-samples_castori_ag %>% 
    filter((str_detect(sampletype, fixed('stool', ignore_case=TRUE))) | sampletype=="Ostomy") %>% 
  select(sampleid, mrn, datecollection)

shotgun_lookup_ad <- get_data_from_query_OTU(0,'shotgun_lookup_ad') 
shotgun<-shotgun_lookup_ad %>% 
  inner_join(sampleid_mrn, by="sampleid")

patient_allo_ag <- get_data_from_query_OTU(0,'patient_allo_ag') 
clinical<-patient_allo_ag %>% 
  select(mrn, hct, sex, age, disease, pt_status, risk, source, intensity, donor, gvhd, hla, skin, lower, upper, liver, grade, relapse, relapse_date, pod, pod_date, vital_status, last_contact, tt_anc_500)
  #group_by(mrn) %>% 
  #arrange(hct) %>% 
  #slice(1) %>% 
  #ungroup()

all_data<-clinical %>% 
  inner_join(shotgun, by="mrn") %>% 
  mutate(sample_day=(datecollection -  hct)) %>% 
  filter(sample_day>= -30 & sample_day <=90 )%>% 
  filter(gvhd!="NA") %>% 
  filter(gvhd!="N/E") %>% 
  distinct(fid, .keep_all = T)

all_data %>% 
  write_csv('../data/all_data_samplelist_from_O.csv')
```


```{r}
all_data %>% 
  summary(gvhd)

table(all_data$gvhd, useNA = 'always')

mrn_list<-all_data %>% 
  select(mrn, sampleid, sample_day, gvhd, upper, lower, skin, liver, grade, hct) %>% 
  unique() 

table(mrn_list$skin)

write_csv(mrn_list, "/Volumes/vandenBrinkLab/Oriana/Study ideas/bile_acids/mrn_list.csv")

colnames(patient_allo_ag)
length(unique(mrn_list$mrn))

all_data %>% 
  mutate(mrn=as.character(mrn)) %>% 
  ggplot(aes(x=sample_day, y=mrn))+
  geom_point()

write_csv(all_)
```

