---
title: "stacked plot"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

*This is the stacked plot for Oriana's neuroblastoma project*

# load the necessary data for the plotting

```{r}
# Ying pull out the clinical info 
load("/Volumes/castoricenter/Ying.Taur/neuroblastoma_oriana/nb_oriana(2019-09-04).RData")

# the microbiome related info
load("/Volumes/vandenBrinkLab/Oriana/NB/RData/dada2_full_pipeline.RData")
ASV_annotated<-read.table("/Volumes/vandenBrinkLab//Oriana/NB/Sequencing requests/10_18_19/ASV_annotated.txt")
ASV_naming<-read.table("/Volumes/vandenBrinkLab//Oriana/NB/Sequencing requests/10_18_19/seqtab_noprior_ASVnaming.txt")

# the list of mrns that O is interested in
target <- read_csv('/Volumes/vandenBrinkLab/Oriana/Shiny/NBpts.csv') %>% 
  pull(MRN)

# the PCR info that specifies the total quantity of the microbiome
qpcr <- read_excel('/Volumes/vandenBrinkLab/Oriana/NB/Data/PCR/qPCR_Results.xlsx')

# the event table 
event <- read_excel('/Volumes/vandenBrinkLab/Oriana/NB/Data/Supplemental_event_table.xlsx')
```

# select the interested columns out of many ones from each table

```{r}
bculture <- nb.bloodcultures %>% 
  select(MRN, test_date, result_full)

cbc <- nb.cbc %>% 
  select(MRN, test_datetime, Abs.Neut, WBC) %>% 
  # the WBC column is character cuz there are things like "<0.1", which will turn into NA when converting but its fine cuz we only care about WBC > 0.5
  mutate(WBC = as.numeric(WBC),
         Abs.Neut = as.numeric(Abs.Neut)) %>%  
  # define neutropenic period 
  mutate(is_neutrop = if_else(WBC > 0.5 & (Abs.Neut < 0.5 | is.na(Abs.Neut)), T, F))

cdiff <- nb.cdiff %>% 
  select(MRN, test_date, result_full)

gipcr <- nb.gipcr %>% 
  select(MRN, test_date, result) %>% 
  mutate(result = factor(result))

respcr <- nb.resppcr %>% 
  select(MRN, test_date, result) %>% 
  mutate(result = factor(result))

meds <- nb.meds  %>% 
  select(MRN, order_name, med_class1, start_date)
  
patients <- nb.patients %>% 
  select(MRN, dob, death_date)

temp <- nb.temperature %>% 
  # one patient may take multiple temperature a day
  select(MRN, service_datetime, Temp.F) %>% 
  mutate(if_fever = if_else(`Temp.F` >= 100.4, T, F))

# the butyrate producer and anarobic info (to do)
```

## Select one patient as example 

```{r}
# trying to find target has all the interesting attributes
input_df_list <- list(bculture %>% 
                        # that has positive detected some organism
                        filter(!str_detect(result_full, 'Negative')), 
                      cbc, 
                      cdiff, 
                      gipcr, 
                      meds %>% 
                        # used this vaccine that we are interested in
                        filter(str_detect(order_name, 'GD2L')), 
                      respcr, 
                      # that has fever
                      temp %>% filter(if_fever == T))

# wanna see if there is a patient that has records in every those table
tally_res <- input_df_list %>% 
  map_dfr(function(df){
    target %>% 
      set_names(target) %>% 
      map(function(mrn){
        df %>% 
            filter(MRN == mrn) %>% 
            nrow
      })
  }) 
  
# which patient has records in every table?
tar_pat <- apply(tally_res, 2, function(colu){ all(colu != 0) })
  
tar_pat <- names(tar_pat[tar_pat == TRUE])
  
# better yet this patient also has some event
test_mrn <- event %>% 
  filter(!is.na(MRN) & !is.na(`Event Start`) & !is.na(`Event Stop`) & !is.na(`Event Type`)) %>% 
  distinct(MRN) %>% 
  pull(MRN) %>% 
  intersect(tar_pat)
  
set.seed(134)
sample(test_mrn, 1)
# 35553875
```

```{r}
tally_res %>% 
  select('35553875')

ttt <- input_df_list %>% 
  map_dfr(function(df){
        df %>% 
            filter(MRN == '35553875')
      })
```

```{r}
# the different things that need to be cleaned in the gi and respcr table
clean_name <- list(gi = gipcr,
     resp = respcr) %>% 
  map(function(df){
    table(df$result) %>% 
      as.data.frame() 
  }) %>% 
  bind_rows(.id = 'type')

clean_name %>% 
  write_csv('../data/oriana/pcr_name_to_be_cleaned.csv')
```

