---
title: "Grabbing stats of the pipeline"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RColorBrewer)
library(ggpubr)
library(kableExtra)
```

## clumpify tsv file

```{r}
clumpify_logs <- list.files('../data/logs/', 'dedupe_stats.txt$', full.names = T)   

clump <- clumpify_logs %>% 
  set_names(clumpify_logs) %>% 
  map(~ suppressWarnings(read_tsv(., col_names = F, col_types = 'c')) %>% 
        tail(10) %>% 
        rename(clumpify = names(.)[1]) %>% 
        filter(str_detect(clumpify, 'Reads In|Reads Out')) %>% 
        separate(clumpify, into = c('type','Num'), sep = ': ', convert = T) %>% 
        spread(key = 'type', value = 'Num') %>% 
        rename_all(funs(str_replace(., ' ','_'))) %>%  
        mutate(dup_num = Reads_In - Reads_Out)) %>% 
  bind_rows(.id = 'sampleid')  %>% 
  mutate(sampleid = str_replace(sampleid, '../data/logs//',''),
         sampleid = str_replace(sampleid, '_dedupe_stats.txt',''))


  
```

## bbmap 

```{r}
bbmap_logs <- list.files('../data/logs/', '_trimmingAQ.txt$', full.names = T)

bb <- bbmap_logs %>% 
  set_names(bbmap_logs) %>% 
  map(~ suppressWarnings(read_tsv(., col_names = F, col_types = 'cdc')) %>% 
        head(3) %>% 
        rename(content = names(.)[1],
               trim_Num = names(.)[2]) %>% 
        filter(str_detect(content, 'Match')) %>% 
        select(trim_Num) ) %>% 
  bind_rows(.id = 'sampleid') %>% 
  mutate(sampleid = str_replace(sampleid, '../data/logs//',''),
         sampleid = str_replace(sampleid, '_trimmingAQ.txt',''))

```

## kneaddata

```{r}
kneaddata_logs <- list.files('../data/logs/', '_kneaddata.log$', full.names = T)

knead <- kneaddata_logs %>% 
  set_names(kneaddata_logs) %>% 
  map(~ suppressWarnings(read_table(., col_names = F, col_types = 'c')) %>% 
        rename(content = names(.)[1]) %>% 
        filter(str_detect(content, 'Total contaminate sequences in file')) %>% 
        transmute(knead_num = str_extract(content, 'Total contaminate sequences in file.+$')) %>% 
        mutate(knead_num = as.numeric(str_replace(knead_num,'^.+: ',''))) %>% 
        head(1)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  mutate(sampleid = str_replace(sampleid, '../data/logs//',''),
         sampleid = str_replace(sampleid, '_kneaddata.log',''))
```

## humann2 results log

```{r}
hm2 <- list.files('../data/logs/humann2_log/', full.names = T)

hm2_metric <- hm2 %>% 
  set_names(hm2) %>% 
  map(~ suppressWarnings(read_table(., col_names = F, col_types = 'c')) %>% 
  rename(content = names(.)[1]) %>% 
  filter(str_detect(content, 'INFO: Unaligned')) %>% 
  transmute(hm_perc = str_extract(content, 'after.+$')) %>% 
  mutate(hm_perc = str_replace(hm_perc, 'after ','')) %>% 
  separate(hm_perc, into = c('type','perc'), sep = ': ') %>% 
  mutate(type = str_replace(type, ' ','_'),
         perc = as.numeric(str_replace(perc, ' %',''))) %>% 
  spread(key = 'type', value = 'perc')) %>% 
  bind_rows(.id = 'sampleid') %>% 
  # filter out the rows that have NA in translated column
  filter(!is.na(translated_alignment)) %>% 
  arrange(nucleotide_alignment)


# cuz I want put the two perc side by side
hm2_metric %>% 
  gather(key = 'type', value = 'perc', names(.)[2]:names(.)[3]) %>% 
  mutate(sampleid = str_replace(sampleid, '../data/logs/humann2_log//',''),
         sampleid = str_replace(sampleid, '_humann2.log','')) %>% 
  mutate(type = factor(type)) %>% 
  ggplot(aes(x = reorder(sampleid, - perc), y = perc, col = type, fill = type)) +
  geom_bar(stat = 'identity', position = "identity", alpha = 0.8) +
  theme_classic() +
  scale_color_manual(values = c('#E64B35B2', '#3C5488B2'))  +
  scale_fill_manual(values = c('#E64B35B2', '#3C5488B2'))  +
  labs(x = 'Samples',
       y = 'Unaligned reads (%)',
       title = '% of unaligned reads after two step alignment') +
  theme(axis.text.x = element_blank(),
        legend.position="bottom") +
  ggsave('../figs/hm_metric.jpg', width = 15, height = 8, dpi = 300)  
```

```{r}
## the unalingned % stats mean and sd
hm2_metric %>% 
  gather(key = 'type', value = 'perc', names(.)[2]:names(.)[3]) %>% 
  mutate(sampleid = str_replace(sampleid, '../data/logs/humann2_log//',''),
         sampleid = str_replace(sampleid, '_humann2.log','')) %>% 
  mutate(type = factor(type))  %>% 
  group_by(type) %>% 
  summarise(ave = mean(perc),
            sd = sd(perc)) %>% 
  rename(`mean (%)` = names(.)[2],
         `SD (%)` = names(.)[3]) %>% 
  kable() %>% 
  kable_styling(full_width = F) %>% 
  save_kable('../output/sample_unalign_metric.html', self_contained = T)


g <- hm2_metric %>% 
   gather(key = 'type', value = 'perc', names(.)[2]:names(.)[3]) %>% 
   mutate(sampleid = str_replace(sampleid, '../data/logs/humann2_log//',''),
          sampleid = str_replace(sampleid, '_humann2.log','')) %>% 
   mutate(type = factor(type)) %>% 
   ggplot(aes(x = type, y = perc, col = type)) +
   geom_boxplot() +
   theme_classic2() 
```


## join

```{r}
stats <- bb %>% 
  full_join(knead, by = 'sampleid') %>% 
  left_join(clump, by  = 'sampleid') %>% 
  select(sampleid, Reads_In, dup_num, trim_Num, knead_num) %>% 
  mutate(dup_per = round(dup_num/Reads_In*100,2),
         trim_per = round(trim_Num/Reads_In*100,2),
         knead_per = round(knead_num/Reads_In*100,2))
```
 
```{r}
# output the stats
stats %>% 
  write_csv('../output/current_240_sample_preprocessing_stats.csv')
```
 
## box

```{r}
# how many total reads in the raw data 
stats %>%
  select(Reads_In) %>% 
  mutate(Group = 'Raw') %>% 
  ggplot(aes(x = Group, y = Reads_In)) +
  geom_boxplot() +
  geom_jitter(col = 'red', fill = 'red', alpha = 0.6) +
  theme_classic() + 
  labs(x = '',
       y = 'Number of reads',
       title = 'Distribution of the\ntotal number of raw reads\nin the samples') +
  ggsave('../figs/raw_total.jpg', width = 3, height = 5, dpi = 300)

```


```{r}
stats %>% 
  select(ends_with('_per')) %>% 
  gather(key = 'step', value = 'perc') %>% 
  mutate(step = str_replace(step, '_per','')) %>% 
  ggboxplot(x = 'step', y ='perc', palette = 'jco', color = 'step') +
  labs(y = 'Percent', 
       title = 'Percent reads removed in the preprocessing') +
  ggsave('../figs/box.jpg', width = 5, height = 5, dpi = 300)
```

 
## Pie 
 
```{r}
# randomly pick one sample 

pie_df <- stats %>% 
  filter(sampleid == '1403F') %>% 
  select(ends_with('per')) %>% 
  mutate(valid = 100 - dup_per - trim_per - knead_per) %>% 
  gather(key = 'step', value = 'perc') %>% 
  mutate(annot = case_when(
    step == 'dup_per' ~ 'Duplicated reads',
    step == 'trim_per' ~ 'Adapters and low quality reads',
    step == 'knead_per' ~ 'Contaminating human reads',
    step == 'valid' ~ 'Valid microbiome reads',
  )) %>% 
  mutate(lbl = str_glue('{perc}%\n{step}'),
         lbl = str_replace(lbl, '_per','')) 

factor_levels <- c('Duplicated reads','Adapters and low quality reads','Contaminating human reads','Valid microbiome reads')

pie_df
```

```{r}
pie_df %>%  
  mutate(annot = factor(annot, levels = factor_levels)) %>% 
  ggpie(x = 'perc',
        label = 'lbl',
        color = 'white',   
        size = 2,
        fill = 'annot', palette = 'jco')  + 
  theme(legend.position = 'right',
        legend.title = element_blank()) +
  labs(title = 'Preprocessing stats of sample 1403F') +
  ggsave('../figs/pie.jpg', width = 10, height = 8, dpi = 300) 

```
  
## humann2 run time logs

```{r}
humann_log <- list.files('../data/logs/humann2_run/', 'out', full.names = T)

time_log <- humann_log %>% 
  set_names(humann_log) %>% 
  map(~ suppressWarnings(read_table(., col_names = F, col_types = 'c')) %>% 
  rename(content = names(.)[1]) %>% 
  filter(str_detect(content, 'CPU time|Run time')) %>% 
  separate(content , into = c('Group','time_h'), sep = ' : ') %>% 
  mutate(time_h =  as.numeric(str_replace(time_h, ' sec.','')),
         time_h =  round(time_h/3600, 2)) %>% 
  spread(key = 'Group', value = 'time_h')) %>% 
  bind_rows(.id = 'sampleid')

memory_log <-  humann_log %>% 
  set_names(humann_log) %>% 
  map(~ suppressWarnings(read_table(., col_names = F, col_types = 'c')) %>% 
  rename(content = names(.)[1]) %>% 
  filter(str_detect(content, 'Max Memory')) %>% 
  separate(content , into = c('Group','memory'), sep = ' : ') %>% 
  mutate(memory =  as.numeric(str_replace(memory, ' GB',''))) %>% 
  spread(key = 'Group', value = 'memory')) %>% 
  bind_rows(.id = 'sampleid')


huge_all <- time_log %>% 
  full_join(memory_log, by  = 'sampleid') %>% 
  arrange(desc(`Max Memory`)) %>% 
  mutate(sampleid = str_replace(sampleid, '../data/logs/humann2_run//12227512','sample'),
         sampleid = str_replace(sampleid, '.stdout','')) %>% 
  rename(`CPU time (h)` = names(.)[2],
         `Run time (h)` = names(.)[3],
         `Max Memory (GB)` = names(.)[4]) %>% 
  head(5)

huge_all %>% 
  kable(caption = 'Glimpse of humann2 run metric') %>% 
  kable_styling(full_width = F) %>%
  save_kable(file = "../output/sample_run_metric.html", self_contained = T)

```
