---
title: "for Marina bar plot"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(vdbR)
connect_database()
get_table_from_database('asv_annotation_blast_ag')
get_table_from_database('asv_annotation_blast_color_ag')
```

```{r}
FMT <- read_csv('../data/01_FMT_pheno.csv')
pheno <- read_csv('../data/01_pheno_with_alpha.csv')
# PH131 is the slurry of 1964A which is the 16s responder patient stool that FMT to the mice
# PH132 is the slurry of 1943B which is the 16s nonresponder patient stool that FMT to the mice 
```
CAR-T FMT samples

- Donor samples (original/frozen) + slurry

- Pre-A20

- W2 post-CAR

(Barplots of individual samples, all with the same color scheme)

```{r}
# the sampleids of shotgun  34
barshot <- FMT %>% 
  filter(Condition %in% c('Pre-A20','2nd Week post-CAR T cells')) %>% 
  select(sampleid, Group, Condition) %>% 
  add_row(sampleid = 'PH131', Group = 'Responder', Condition = 'Slurry')

# two 16s samples.   2
amplisamp <- c('1964A','1943B')
```

```{r}
# plot at the genus level
# find the genus of the shotgun samples 
all  <- read_csv('../data/01_all_metaphlan.csv')
genus <- all %>% 
  mutate(genus = str_replace(clade_name, '\\|s__.+$','')) %>% 
  group_by(sampleid, genus) %>% 
  summarise(relab = sum(relative_abundance)) %>% 
  ungroup() %>% 
  mutate(ge = str_extract(genus, 'g__.+$'),
         genus = str_replace(ge, 'g__', '')) %>% 
  inner_join(barshot) %>% 
  select(-ge)

# find the genus of the 16s samples  
genus_16 <- get_counts_subset(c('1964A','1943B')) %>% 
  select(asv_key:count_total, count_relative) %>% 
  left_join(asv_annotation_blast_ag %>% 
              select(asv_key,genus), by = "asv_key") %>% 
  group_by(sampleid, genus) %>% 
  summarise(relab = sum(count_relative)) %>% 
  mutate(Group = if_else(sampleid == '1964A', 'Responder', 'Non-Responder'),
         Condition = 'donor')

# find the shared genus of the 16s and shotgun
length(intersect(genus_16$genus, genus$genus))
length(genus_16$genus)
length(genus$genus)
shared_genus <- intersect(genus_16$genus, genus$genus)

# the color pal for the shared genus
shard_pal <- asv_annotation_blast_color_ag %>% 
  filter(genus %in% shared_genus) %>% 
  distinct(genus,color_label_group_distinct, color ) %>% 
  add_row(genus = 'Other', color_label_group_distinct = 'other__other.164', color = '#BBBBBB') %>% 
  rename(genus_cleaned = genus)

# combine them to be the same df
combined <- bind_rows(
  genus,
  genus_16 %>% select(colnames(genus))
) %>% 
  mutate(genus_cleaned = if_else(genus %in% shared_genus, genus, 'Other')) %>% 
  left_join(shard_pal, by = "genus_cleaned") %>% 
  mutate(Condition = factor(Condition, levels = c('donor','Slurry','Pre-A20','2nd Week post-CAR T cells')))

color_set <- shard_pal %>% 
  select(color_label_group_distinct, color) %>% 
  deframe()
```

```{r}
combined %>% 
  ggplot(aes(sampleid, relab, fill = color_label_group_distinct) ) +
  geom_bar(stat = "identity", position="fill", width = 1) +
  theme_classic() +
  labs(title = '',
       x = '',
       y = 'Relative abundance') +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none") +
  scale_fill_manual(values = color_set) +
  facet_grid(Condition ~ Group, scales = 'free') 

ggsave('../data/06_FMT_bar.pdf', width = 5, height = 4)
```

```{r}
# alpha diversity
shotgunalpha <- pheno %>% 
  filter(sampleid %in% barshot$sampleid) %>% 
  select(sampleid:Condition, alpha) %>% 
  mutate(Group = if_else(sampleid == 'PH131', 'Responder',Group ),
         Condition = if_else(sampleid == 'PH131', 'Slurry',Condition ))

alpha16s <- asv_alpha_diversity_ag %>% 
  filter(sampleid %in% amplisamp) %>% 
  select(sampleid, alpha = simpson_reciprocal) %>% 
  mutate(
    Group = if_else(sampleid == '1964A', 'Responder', 'Non-Responder'),
    Condition = 'donor'
  )

both_alpha <- bind_rows(
  shotgunalpha %>% mutate(data = 'shotgun'), 
  alpha16s %>% mutate(data = '16S')
  )

color_key <- both_alpha %>% 
  distinct(Group) %>% 
  mutate(color = c('#42B440','#EC0000')) %>% 
  deframe()

both_alpha %>% 
  mutate(Condition = factor(Condition, levels = c('donor','Slurry','Pre-A20','2nd Week post-CAR T cells'))) %>% 
  ggboxplot(x = 'Condition', y = 'alpha', add = 'jitter', color = 'Group') +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none") + 
  scale_color_manual(values = color_key) +
  facet_grid(data ~ Group, scales = 'free')

ggsave('../data/06_FMT_alpha.pdf', width = 5, height = 6)
```
```{r}
# the genera in donor responder
sub <- combined %>% 
  mutate(Condition = as.character(Condition)) %>% 
  filter(Condition %in% c('donor','Pre-A20'))

# calculate the percentage of the shared genera relative to donor (a distribution)
sub %>% 
  split(.$Group) %>% 
  map(function(each_group){
    # calculate num of shared genera between donor and each preA20 mouse
    
    genera_in_donor =  each_group %>% filter(Condition == 'donor')
    donor_genera_number = genera_in_donor %>% distinct(genus) %>% nrow
    shared_dist <- each_group %>% 
      filter(Condition != 'donor') %>% 
      split(.$sampleid) %>% 
      map(function(each_prea20_sample){
        shared_num = length(intersect(each_prea20_sample$genus, genera_in_donor$genus))
      }) %>% bind_rows(.id = 'sampleid') %>% 
      gather('sampleid','shared_genera_num') %>% 
      mutate(donor_genera_num = donor_genera_number) %>% 
      mutate(perc = round(shared_genera_num/donor_genera_num*100,2))
    return(mean(shared_dist$perc))
  }) 
  
```

