---
title: "finding shotgun samples"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
library(vdbR)
connect_database('~/dbConfig.txt')
get_table_from_database('shotgun_lookup_ad')

samp <- c('FMT.0092K','FMT0092L','FMT.0092Z','1366M','1366N','FMT.0013K','FMT.0013L','1105J','1105U','628M')
pt <- c('1110','1230','1362','FMT.0136','FMT.0023','FMT.0114','FMT.0115','FMT.0217')
```

```{r}
samps <- shotgun_lookup_ad %>% 
  distinct(sampleid, .keep_all = T) %>% 
  filter(sampleid %in% samp)

pts <- shotgun_lookup_ad %>% 
  distinct(sampleid, .keep_all = T) %>% 
  filter(str_detect(sampleid, paste(pt, collapse = '|')))

pts %>% 
  select(sampleid) %>% 
  write_csv('../data/target_patients_samples_yale.csv')

setdiff(samp, samps$sampleid)

need <- bind_rows(pts, samps)

need %>% 
  arrange(directory) %>% 
  select(directory) %>% 
  write_csv('../data/yale_need.csv')
```

```{r}
# the one that oriana wants

want <- read_csv('../data/shotgun_lookup_bile_pts.csv') %>% 
  distinct(sampleid) %>% 
  inner_join(shotgun_lookup_ad %>% 
               distinct(sampleid, .keep_all = T))
running <- read_csv('../data/all01_yale.csv', col_names = F)
length(intersect(want$fid, running$X1))
prepr <- tibble(fid = intersect(want$fid, running$X1))
```


```{r}
cur <- read_delim('../data/current.txt', delim = ' ', skip = 1, col_names = c('folder')) %>% 
  mutate(fid = str_replace(folder, 'Sample_',''),
         fid = str_replace(fid, '_IGO_.+$',''))
cur
length(intersect(cur$fid, need$fid))


rest <- read_csv('../data/rest.csv', col_names = F)
length(intersect(want$fid, rest$X1))
tibble(fid = intersect(want$fid, rest$X1))  %>% 
  mutate(fn = str_glue('/home/daia1/my_workdir/samples/transition/preprocessing/01_processing/05_sync/{fid}_knead_cat.fastq.gz')) %>% 
  mutate(cmd = str_glue('cp {fn} /home/daia1/my_workdir/samples/O423')) %>% 
  select(cmd) %>% 
  write_csv('../data/copy_73.sh', col_names = F)

todo <- tibble(fid = setdiff(want$fid, intersect(want$fid, rest$X1)))

todo %>% 
  write_csv('../data/todo350.csv', col_names = F)

length(intersect(want$fid, need$fid)) 

# the 73 that I need to preprocess again  
the73 <- want %>% 
  filter(! fid %in% todo$fid)

length(intersect(the73$fid, need$fid)) 

# final fid will be 
the10 <- want %>% 
  filter( fid %in% need$fid)

the33 <- need %>% 
  filter(!fid %in% the10$fid) 

fid106 <- bind_rows(the33 %>% select(fid), the73 %>% select(fid))

fid106 %>% 
  write_csv('../data/fid106.csv')
```

