---
title: "Prepare for oriana lefse run"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## vrelapse

```{r}
pheno <- read_csv('/Volumes/vandenBrinkLab/Oriana/NB/Data/lefse/Vrelapse/pheno_baseline_VRelapse.csv')

cts <- read_csv('/Volumes/vandenBrinkLab/Oriana/NB/Data/lefse/Vrelapse/otu_baseline_VRelapse.csv')

cts <- cts %>% 
  mutate(spp = str_glue('k__{kingdom}|p__{phylum}|c__{class}|o__{order}|f__{family}|g__{genus}|s__{species}')) %>% 
  select(sampleid, spp, relab) %>% 
  group_by(sampleid, spp) %>% 
  summarise(Relab = sum(relab)) %>% 
  spread(key = 'sampleid', value = 'Relab', fill = 0) %>% 
  gather(key = 'sampleid', value = 'Relab', names(.)[2]:names(.)[ncol(.)])


cts <- bind_cols(cts[,1],cts[,pheno$sampleid])

all.equal(colnames(cts)[2:ncol(cts)], pheno$sampleid)

cts %>% 
  write_tsv('../../data/oriana/input_lefse_cts.tsv')

pheno %>% 
  select(VRelapse) %>% 
  t %>% 
  write.table('../../data/oriana/input_lefse_pheno.tsv', sep = '\t', quote = F, row.names = T, col.names = F )

```

## titer

```{r}
pheno <- read_csv('/Volumes/vandenBrinkLab/Oriana/NB/Data/lefse/Vtiters/pheno_baseline_titers.csv')

cts <- read_csv('/Volumes/vandenBrinkLab/Oriana/NB/Data/lefse/Vtiters/otu_baseline_titers.csv')

cts <- cts %>% 
  mutate(spp = str_glue('k__{kingdom}|p__{phylum}|c__{class}|o__{order}|f__{family}|g__{genus}|s__{species}')) %>% 
  select(sampleid, spp, relab) %>% 
  group_by(sampleid, spp) %>% 
  summarise(Relab = sum(relab)) %>% 
  spread(key = 'sampleid', value = 'Relab', fill = 0)

cts <- bind_cols(cts[,1],cts[,pheno$sampleid])

all.equal(colnames(cts)[2:ncol(cts)], pheno$sampleid)

cts %>% 
  write_tsv('../../data/oriana/input_lefse_cts.tsv')

pheno %>% 
  select(titers100) %>% 
  t %>% 
  write.table('../../data/oriana/input_lefse_pheno.tsv', sep = '\t', quote = F, row.names = T, col.names = F )

```