'''
This Snakefile will download the metaphlan and KO_cpm, pathwayabun_CPM files to local data dir
and then merge into one single file per every project ID
in biobakery3 env
first run: snakemake -j1 
then run: snakenake -j1 clean 
'''

project = 'IGO_13720'
    
rule all:
    input:
        'split.done'

rule download_files:
    input:
        
    output:
        touch('dl.done')
    params:
        projectid=project
    shell:
        '''
        mkdir /Users/daia1/pipeline/scripts/shotgun_pipeline/data/{params.projectid}
        scp daia1@lilac.mskcc.org:/home/daia1/my_workdir/samples/metaphlan/*{params.projectid}*_metaphlan3_profile.txt /Users/daia1/pipeline/scripts/shotgun_pipeline/data/{params.projectid} 
         scp daia1@lilac.mskcc.org:/home/daia1/my_workdir/samples/humann/*{params.projectid}*cpm*tsv /Users/daia1/pipeline/scripts/shotgun_pipeline/data/{params.projectid} 
        '''

rule join_tables:
    input:
        'dl.done'
    output:
        touch('joined.done')
    params:
        projectid=project,
        data_dir = '/Users/daia1/pipeline/scripts/shotgun_pipeline/data'
    shell:
        '''
        humann_join_tables -s  --input {params.data_dir}/{params.projectid} --file_name humann3_pathabundance_cpm --output {params.data_dir}/{params.projectid}/humann3_pathabundance_cpm_joined.tsv
        humann_join_tables -s  --input {params.data_dir}/{params.projectid}  --file_name humann3_KO_cpm --output {params.data_dir}/{params.projectid}/humann3_KO_cpm_joined.tsv
        merge_metaphlan_tables.py {params.data_dir}/{params.projectid}/*_metaphlan3_profile.txt  > {params.data_dir}/{params.projectid}/merged_abundance_table_metaphlan3.txt
        '''

rule split_tables:
    input:
        'joined.done'
    params:
        data_dir = '/Users/daia1/pipeline/scripts/shotgun_pipeline/data',
        projectid=project,
    output:
        touch('split.done')
    shell:
        '''
        humann_split_stratified_table -i {params.data_dir}/{params.projectid}/humann3_pathabundance_cpm_joined.tsv -o {params.data_dir}/{params.projectid} 
        humann_split_stratified_table -i {params.data_dir}/{params.projectid}/humann3_KO_cpm_joined.tsv -o {params.data_dir}/{params.projectid} 
        '''

rule clean:
    shell:
        'rm *done'
